/* Track: Usage, myths and the evidence. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "usage-rule-or-superstition",
  track: "usage", level: "sentence",
  title: "A rule has evidence behind it; a superstition only has confidence",
  source: "Bryan Garner, Garner's Modern English Usage",
  gatePrompt: "Paste a paragraph you wrote, and beside it paste one correction you made to someone else's writing this month. For each rule you applied, write one line naming the evidence for it and one line naming the reader it protects. Cross out every rule where both lines came out blank.",
  fallback: "Editorial pass on the migration doc before it goes to the customer. Do not start sentences with \"But\" or \"And\", do not end a sentence with a preposition, and change every restrictive \"which\" to \"that\" throughout. Also \"data\" takes a plural verb, so please fix the four places where it does not. These are basic rules and we should be holding the bar on anything that leaves the team.",
  idea: "Before you enforce a rule, name the evidence behind it, the reader it protects, and whether writers you admire actually observe it.",
  why: "Usage advice arrives in two kinds and they feel identical from the inside. One kind tracks something real about how readers process English: an ambiguity that costs a re-read, a distinction that carries meaning, a form so widely observed by careful writers that its absence registers as error. The other kind is inherited assertion, often traceable to one nineteenth-century schoolmaster reasoning from Latin, and it survives because nobody has ever been asked for the evidence.\n\nGarner's three questions separate them, because a real rule answers all three and a superstition answers none. What evidence supports it: corpus data, editorial practice, a demonstrable ambiguity. Who is harmed: a specific reader misreading a specific sentence. Do careful writers observe it: check ten pages of prose you respect. A rule that fails all three still costs you something. It spends editing attention that should be going to characters, actions and sentence order, and it spends credibility with the writer you are correcting, who can usually tell the difference even if they cannot name it.",
  failureMode: "Review comments that stack real problems and folklore at the same volume: \"the second paragraph buries the recommendation, and do not open a sentence with 'But'.\" The writer now has to guess which of your notes is load-bearing, and the safest guess is that none of them are. Worse is the correction that damages a sentence to satisfy a rule nobody can defend, such as fronting a preposition into \"the failure mode about which we warned\", so the clause stalls at exactly the point it should be carrying weight.",
  worked: "Editorial pass on the migration doc before it goes to the customer. One note left, and it is a preference rather than an error: house style wants restrictive \"that\", so the restrictive \"which\"es should change. Evidence: settled American editorial practice and our own style guide. Reader it protects: nobody, so skip it if you are short of time. The other three are gone, because both lines came out blank on every one. No \"But\" or \"And\" to open a sentence: no evidence, no reader. No preposition at the end of a clause: no evidence, no reader. \"Data\" takes a plural verb: the evidence is an argument from Latin, and I cannot name a reader who would be misled by the singular. That leaves a pass with nothing in it about whether the document is comprehensible, which tells you I proofread it instead of reading it. Give me until tomorrow and I will send the pass that matters.\n\nWhat changed is the test each note had to pass, not the tone. Three rules went out because neither line could be filled in, and the survivor is relabelled as house style with an empty reader line, which is a different instruction to the writer than \"these are basic rules and we should be holding the bar\". The cost is not only length. The pass is a quarter of its old size and looks like you barely opened the file, and the appearance is accurate: strip the folklore and there is no comprehension note left, so you have to go back and do the work the rules were standing in for. Auditing four rules for evidence and reader also takes longer than typing four rules, which is most of why nobody does it.",
  experiment: "Open the last three sets of review comments you left on someone's writing. Sort every note into two piles: about the reader's comprehension, and about a rule. For each rule note, write down where you learned that rule. Count the ones you cannot source, and stop enforcing them.",
  reflection: "Which rule turned out to be one you have enforced for years without ever knowing where it came from?",
  recall: {
    q: "What three questions separate a usage rule from a superstition?",
    a: "What evidence supports it, who is harmed when it is broken, and whether careful writers actually observe it. A real rule answers all three with something concrete: corpus data or settled editorial practice, a specific reader misreading a specific sentence, and prose you respect that follows it.\n\nA superstition answers none of them. Its whole support is the confidence of whoever taught it to you."
  },
  deepDive: "Here are the edits I made to a colleague's draft - tell me which ones I can defend on evidence and which ones are folklore I picked up somewhere and never checked."
},
{
  id: "usage-language-change-index",
  track: "usage", level: "sentence",
  title: "The Language-Change Index gives you a scale instead of a verdict",
  source: "Bryan Garner, Garner's Modern English Usage",
  gatePrompt: "Paste a paragraph you wrote. Mark every word or construction you hesitated over, and put each one on a five-point scale from \"rejected by everyone\" to \"nobody notices any more\". Rewrite only the ones you placed at one or two.",
  fallback: "Comments on the runbook. It uses \"impact\" as a verb in four places and \"leverage\" as a verb in two, and neither of those is a word. \"Comprise\" is used backwards in the overview. There is also a \"none of the checks are\" in the rollback section. I have marked all of them as errors; please fix everything before this gets merged, the bar for published runbooks should be the same as for customer docs.",
  idea: "Place each contested usage on a five-stage scale from rejected to fully accepted, then let the stage decide whether you correct it, allow it or ignore it.",
  why: "Garner's index runs from Stage 1, rejected and still an error to nearly everyone, through Stage 3, where a form is widespread but still draws objection from careful readers, up to Stage 5, where the old objection survives in a handful of holdouts. The taxonomy is not the point. The point is that a position replaces a verdict, and a position tells you what to do.\n\nThe mechanism on the reader's side is distraction cost. A Stage 1 usage makes some portion of your readers stop and quietly reassess your competence, which is a genuine cost to whatever you were arguing. A Stage 5 usage costs nothing with anyone who was not already looking for a fight. Between the two, the deciding question is audience: an internal design doc and a customer-facing incident notice sit at different points on the same scale, so the identical word can be unremarkable in one and worth twenty seconds of your time in the other.",
  failureMode: "Editing everything to one standard. A reviewer flags \"impact\" as a verb, \"none of the checks are\", and a genuinely ambiguous \"only\" in a single pass, all labelled errors, and the writer dutifully fixes the two that were never wrong and misses the one that was. The other version is the writer who freezes mid-paragraph to litigate \"comprise\" and loses the thread of the argument they were three sentences into making.",
  worked: "Comments on the runbook, and none of them blocks the merge. \"Impact\" and \"leverage\" as verbs sit near the top of the change index: ordinary in this register, still objected to by a shrinking group, and costing an on-call engineer nothing at 3am. All six stay. \"None of the checks are\" is at the very top of the scale and has taken a plural verb since Old English, so ignore my flag on it. \"Comprised of\" in the overview is the only one still worth an argument. It sits mid-scale, common enough that most readers go straight past it and conspicuous enough that some stop. In a customer doc I would change it. In an internal runbook it costs the reader nothing, so it stays too. The bar for a runbook is not the bar for customer docs, and I was wrong to say it was.\n\nEvery flagged usage got a position on the scale instead of a verdict, and the position did the deciding. Six flags came off because a form that high on the scale costs an internal reader nothing, one came off because it was never an error, and the last survives only as a note about a different audience. Two things went with them. You have lost the single standard, which is what made the old pass fast and defensible in one line, and you now have to hold a different bar for runbooks than for customer docs and be able to say out loud which is which. The author also gets a review that found nothing to fix, and a review that found nothing reads as a reviewer who did not look, not as one who looked at the right things.",
  experiment: "List the five usages you most often correct in other people's drafts. Beside each, write the stage you believe it sits at, then look three of them up in a usage dictionary. Count how many you had placed two or more stages below where the evidence puts them.",
  reflection: "Which usage were you treating as an error that turns out to be near the top of the scale?",
  recall: {
    q: "Why is a five-stage scale more useful than a right-or-wrong verdict on a contested usage?",
    a: "Because the stage tells you what the usage actually costs a reader. A Stage 1 form makes readers question your competence; a Stage 5 form costs nothing with anyone who is not already hunting for errors. The decision to correct depends on that cost and on who is reading.\n\nA binary verdict throws the information away, so you spend the same editing attention on a settled question as on a live one."
  },
  deepDive: "Go through the usages I flagged in this draft, place each on Garner's Language-Change Index, and tell me which are worth changing for this specific audience."
},
{
  id: "usage-strunk-and-white",
  track: "usage", level: "document",
  title: "Fifty years of stupid grammar advice: how Strunk and White survived being wrong",
  source: "Geoffrey K. Pullum, \"50 Years of Stupid Grammar Advice\"",
  gatePrompt: "Open the writing guidance your team actually cites: a style page, an onboarding doc, a review checklist. Mark every rule that comes with an example, then check whether the example is genuinely an instance of the thing the rule names. Write the count of examples that are not.",
  fallback: "Team writing standards, section 2. Use the active voice. Strunk and White is the reference here and every engineer should keep a copy on the desk. Sentences such as \"There were three retries recorded before the circuit opened\" are passive and weak, so rewrite them with a real subject. Reviewers should flag any sentence containing a form of \"to be\" and ask the author to justify it.",
  idea: "Check the examples under a rule before you adopt the rule, because a confidently written guide can be wrong about its own cases.",
  why: "Pullum's demonstration is specific and checkable. Under the heading urging the active voice, Elements of Style offers examples that contain no passive at all. \"There were a great number of dead leaves lying on the ground\" is an existential construction, not a passive one. The authors could not reliably identify the construction their own rule was about, and the book has still sold in the millions and shaped how generations were taught to write.\n\nThat transmission mechanism is the part worth understanding, because it operates on your team's style page too. Folklore spreads on tone, not evidence. A short, confident, unhedged imperative is cheap to remember, cheap to repeat, and impossible to argue with inside a review comment, while the accurate statement is longer and arrives with conditions attached. The wrong rule outcompetes the right one on transmission, and it keeps winning until somebody checks the examples.",
  failureMode: "A team standard that says \"avoid the passive\" and in practice flags every sentence containing a form of \"to be\". Engineers rewrite \"there were three retries before the circuit opened\" into something longer and worse, while the genuinely evasive passives sail through: \"the record was deleted\", agent unnamed, in an incident write-up, which is the one sentence in the document where the missing subject matters.",
  worked: "Team writing standards, section 2. One rule in this section came with an example, and the example is not an instance of what the rule names: one out of one. Name the actor when the actor matters. \"The record was deleted\" in an incident write-up hides the one thing the reader opened the document to find, and \"the backfill job deleted the record\" hands it over. Use the passive on purpose when the actor is unknown, when it is genuinely beside the point, or when the sentence has to open on the thing the last sentence closed on. The example we used to cite here is gone: \"There were three retries recorded before the circuit opened\" is an existential \"there were\", not a passive, and asking people to rewrite sentences like it produced longer prose and no clearer prose. Strunk and White comes off this section as a reference for the same reason, since several of the sentences that book presents as passives are not passives. Reviewers, stop flagging forms of \"to be\". That test catches existentials and plain descriptions, and it misses the sentence where the actor is missing and the missing actor is the whole story.\n\nThe check ran on the example, not the rule, and the example failed. The section was illustrating the passive with a sentence containing no passive, and the reviewer instruction built on top of it was a search for the wrong string. The replacement names a specific reader harm, a missing actor in a document about who did what, and puts conditions on the passive instead of banning it. What it cost is transmission, which is what the old version was winning on. \"Use the active voice\" fits inside a review comment and this does not. You have traded a rule people repeat for a rule people have to read, and reviewers have lost a mechanical test they could apply without understanding the sentence. That is a real loss of throughput, even though the test was finding the wrong sentences.",
  experiment: "Take your team's writing guidance and pick the three rules it states most confidently. For each, find a paragraph of prose you consider genuinely good, from any source, and check whether it obeys the rule. Write down the violation count you find in prose you already rated highly.",
  reflection: "Which rule on your team's page survived contact with prose you admire, and which one did not?",
  recall: {
    q: "What did Pullum show about the passive-voice section of Elements of Style, and why does it matter beyond that one book?",
    a: "Several of the examples the book presents as passives are not passives at all, so the authors could not reliably identify the construction their own rule targeted. The book's authority came from its brevity and tone rather than its accuracy.\n\nIt matters because that is how usage folklore propagates in general. A short confident imperative is easier to remember and repeat than a correct statement with conditions, so it wins on transmission rather than on truth, including on your own team's style page."
  },
  deepDive: "Here is my team's writing guidance - check each rule's examples against what the rule actually claims, and tell me which rules I should delete outright."
},
{
  id: "usage-split-infinitive",
  track: "usage", level: "sentence",
  title: "Split the infinitive when the meaning requires it",
  source: "Bryan Garner, Garner's Modern English Usage",
  gatePrompt: "Paste a paragraph you wrote. Find every infinitive with an adverb near it and write out both placements, inside and outside. Keep the one where the adverb attaches to the verb you meant, and mark any sentence where the unsplit version is ambiguous.",
  fallback: "We intend fully to migrate the remaining tenants before the code freeze. The new scheduler is expected to produce an increase of more than double on write throughput, and operators will be asked promptly to acknowledge any alert raised during the window. If a connector fails mid-cutover we will need quickly to decide whether to roll back or push forward, so the on-call should be briefed the day before.",
  idea: "Put the adverb where it modifies the verb you meant, which is often between \"to\" and the verb.",
  why: "There is nothing in the grammar of English the prohibition could rest on. It was imported by nineteenth-century grammarians reasoning from Latin, where the infinitive is one word and cannot be split, and it has been rejected by every serious usage authority since Fowler. Garner treats it as a superstition, not a close call.\n\nThe cost of obeying it is not aesthetic. Adverb placement in English carries scope, so moving the adverb moves what it modifies. \"We expect to more than double throughput\" has no unsplit form at all. \"We plan quickly to review each connector\" leaves the reader to work out whether the planning is quick or the review is, and they will feel the hesitation before they resolve it. A reader who parses your sentence twice is a larger cost than a reader who was never going to object in the first place.",
  failureMode: "Adverbs exiled into positions that build a garden path: \"operators will be asked promptly to acknowledge any alert\", where \"promptly\" can attach to the asking or the acknowledging, and only one of those is what the runbook needs to say. The extreme case is the sentence that cannot be unsplit and gets inflated instead, so \"expected to more than double\" becomes \"expected to produce an increase of more than double\", eight words to avoid two.",
  worked: "We intend to fully migrate the remaining tenants before the code freeze. The new scheduler is expected to more than double write throughput, and operators will be asked to promptly acknowledge any alert raised during the window. If a connector fails mid-cutover we will need to decide quickly whether to roll back or push forward, so the on-call should be briefed the day before.\n\nFour adverbs moved. \"Intend fully to migrate\" left \"fully\" hovering between the intending and the migrating, and inside the infinitive it lands on the verb you meant. \"Asked promptly to acknowledge\" had the same ambiguity with worse consequences, because the runbook needs promptness from the operator and not from whoever raises the alert. \"Expected to produce an increase of more than double\" collapses back to \"expected to more than double\", since that construction has no unsplit form at all and the eight-word noun phrase existed only to avoid two words. The fourth was not a split: \"need quickly to decide\" wanted the adverb after the verb rather than inside the infinitive, because the move is placement and not splitting for its own sake. The paragraph is five words shorter, and one thing was genuinely given up. A reviewer who still holds the prohibition will read \"to fully migrate\" as carelessness, and you will spend a comment defending a construction that never needed defending.",
  experiment: "Search your last long document for every adverb sitting immediately before the word \"to\". Read each sentence again with the adverb moved inside the infinitive and decide which version says what you meant. Count how many you move and how many you leave.",
  reflection: "How many of your adverbs were outside the infinitive purely out of habit, and did any of them change meaning when you moved them in?",
  recall: {
    q: "What is the actual cost of avoiding a split infinitive?",
    a: "Adverb placement in English determines scope, so moving an adverb out of the infinitive can change or blur what it modifies. \"Asked promptly to acknowledge\" is ambiguous in a way that \"asked to promptly acknowledge\" is not, and some constructions such as \"to more than double\" have no unsplit form.\n\nThe prohibition came from applying Latin, where the infinitive is a single word, to a language where it is two. No reader is helped by it."
  },
  deepDive: "Find the infinitives in this draft where I moved the adverb out to avoid a split, and tell me which of them changed meaning when I did."
},
{
  id: "usage-stranded-prepositions",
  track: "usage", level: "sentence",
  title: "The preposition rule was imported from Latin and never fit English",
  source: "Rodney Huddleston and Geoffrey K. Pullum, The Cambridge Grammar of the English Language",
  gatePrompt: "Paste a paragraph you wrote. Find every \"which\" or \"whom\" with a preposition standing in front of it, rewrite each with the preposition at the end of its clause, and mark the version you would actually say out loud.",
  fallback: "This is the failure mode about which we warned in the March design review. The replica to which the backfill writes is the same one from which the tenant API reads, and that is the condition under which the saturation we saw on Tuesday occurs. Someone needs to decide with which team the connector timeout fix now sits, and by when we expect it.",
  idea: "Leave the preposition at the end of the clause when that is where English puts it.",
  why: "Preposition stranding is native to English, attested for more than a thousand years, and in several constructions it is the only grammatical option. You cannot front the preposition in \"the replica the backfill writes to\" while also dropping the relative pronoun, and you cannot front it at all in a prepositional passive such as \"the queue was written to twice\". A rule that forbids what the grammar obliges you to do is not a rule about English.\n\nOn the reader's side, fronting has a measurable effect on processing. \"The condition under which the saturation occurs\" makes the reader hold an unresolved prepositional phrase across the whole relative clause before the verb arrives. Occasionally that formality is exactly what you want. Applied to every clause in a paragraph because of a rule, it reads as a legal filing, and readers start skimming at precisely the point where the technical content lives.",
  failureMode: "A design doc where every relative clause has been formalised: \"the failure mode about which we warned\", \"the team with which the fix sits\", \"the window during which the backfill runs\". Each one is grammatical, and the accumulation is unreadable. The reliable tell is that you would say none of them to the person sitting next to you.",
  worked: "This is the failure mode we warned about in the March design review. The replica the backfill writes to is the same one the tenant API reads from, and that is the condition the saturation we saw on Tuesday occurs under. Someone needs to decide which team the connector timeout fix now sits with, and when to expect it.\n\nFive prepositions went back to the end of their clauses, and in four of them the relative pronoun went too. \"The replica the backfill writes to\" has no fronted equivalent once \"which\" is gone, which is the plainest evidence that the rule was never describing English. The read-aloud test caught all five, because you would say none of the originals to the person sitting next to you. What it cost is register, and that only reads as nothing because this is a design doc. Send the same sentences to a regulator or put them in a contract and one \"under which\" would have earned its formality. Two things it did not fix. \"The condition the saturation occurs under\" is still the worst sentence here, and its problem is the noun \"condition\" rather than the preposition, which is a different move on a different day. And no sentence lost precision, so if you were expecting the unfronting to tighten the paragraph as well, it did not.",
  experiment: "Take a paragraph you wrote for a document that leaves your team and read it aloud. Wherever you stumble or hear yourself performing, check for a fronted preposition and put it back at the end. Count how many you moved, and note whether the paragraph lost any precision or only lost formality.",
  reflection: "Did any of the sentences you unfronted actually lose precision, or did they only lose ceremony?",
  recall: {
    q: "Why can the prohibition on ending a clause with a preposition not be a rule of English?",
    a: "Because English requires stranding in several constructions. Prepositional passives such as \"the queue was written to twice\", and relative clauses with the pronoun omitted, have no fronted equivalent at all. A rule that bans a form the grammar obliges you to use is describing some other language.\n\nIt was imported by analogy with Latin, where the construction genuinely does not exist."
  },
  deepDive: "Go through this document for fronted prepositions and tell me which ones are earning their formality and which ones are just the rule talking."
},
{
  id: "usage-which-and-that",
  track: "usage", level: "sentence",
  title: "\"Which\" against \"that\" is house style dressed as grammar",
  source: "Geoffrey K. Pullum, \"50 Years of Stupid Grammar Advice\"",
  gatePrompt: "Paste a paragraph you wrote. Mark every relative clause, then label each one: does it identify which thing you mean, or add information about a thing already identified? Fix the commas to match, and ignore the choice of word entirely until they do.",
  fallback: "The scheduler that we rolled out in March is now carrying all tenant traffic. The backfill job that saturated the read replica has been moved to the overnight window. The audit hook that adds a quarter second to every workflow start is the last item outstanding, and the runbook that covers it still needs a rewrite before we hand it to support.",
  idea: "The commas carry the restrictive distinction; the choice between \"which\" and \"that\" is a house convention you either adopt deliberately or drop.",
  why: "Restrictive \"which\" has been in continuous use by good writers for centuries and remains ordinary in British editing. The preference for \"that\" in restrictive clauses began as a reform proposal and spread through American editorial practice and Strunk and White. Pullum's observation is that its own advocates break it constantly, E. B. White included, which is the signature of a convention rather than a rule.\n\nWhat actually carries meaning is the punctuation. \"The connector that we deprecated\" and \"the connector, which we deprecated,\" tell a reader different things: the first says there are several connectors and this is the one, the second says there is one and here is a fact about it. Get the commas wrong and the reader miscounts your nouns and quietly builds the wrong model of your system. Get the word wrong and a copy editor changes it. Those are not the same size of error, and treating them as one spends your attention on the smaller one.",
  failureMode: "A mechanical which-to-that pass that strips the commas along with the word, so every non-restrictive clause turns restrictive. \"The audit hook that adds a quarter second to every start\" now implies there are several audit hooks and this is the slow one. Nobody catches it in review, because every sentence is perfectly grammatical, and the reader walks away believing in components that do not exist.",
  worked: "The scheduler, which we rolled out in March, is now carrying all tenant traffic. The backfill job that saturated the read replica has been moved to the overnight window. The audit hook, which adds a quarter second to every workflow start, is the last item outstanding, and the runbook that covers it still needs a rewrite before we hand it to support.\n\nThe commas did the work, and they changed on two of the four relative clauses. \"The scheduler, which we rolled out in March,\" and \"the audit hook, which adds a quarter second,\" now read as facts about things the reader already knows exist, which is what you meant. The commaless versions were quietly announcing a fleet of schedulers and a set of audit hooks. The other two stayed restrictive because they identify: there are several backfill jobs and several runbooks, and these are the ones. \"Which\" arrived only because the commas did, and under a British house style the restrictive clauses could take \"which\" as well, so anyone running a which-to-that pass over this paragraph has to leave the punctuation alone. The cost is that commas commit you to a claim about your own system. You have now told the reader there is exactly one scheduler and exactly one audit hook, and if there are two of either, the punctuation is lying in a way no reviewer will catch, because every sentence is still grammatical.",
  experiment: "Take a design doc you wrote and list every relative clause in it. For each, ask whether deleting the clause would change which thing you are talking about. Where the answer is no, the clause needs commas. Count the ones missing them, and ignore every \"which\" and \"that\" while you do it.",
  reflection: "How many of your relative clauses had the wrong commas, and did any of them make a reader think there is more of something than there is?",
  recall: {
    q: "What separates the restrictive and non-restrictive distinction from the \"which\" versus \"that\" rule?",
    a: "The distinction is real and it is carried by the commas. A restrictive clause identifies which thing you mean; a non-restrictive one adds information about a thing already identified. Getting the commas wrong changes what the reader believes exists.\n\nThe word choice is an editorial convention, standard in American house styles and not in British ones. Follow it if your style guide says so. It is not a grammar error either way."
  },
  deepDive: "Check the relative clauses in this draft for comma errors and tell me where the punctuation is telling my reader something I did not mean."
},
{
  id: "usage-none-and-initial-and",
  track: "usage", level: "sentence",
  title: "\"None\" was never singular and \"and\" has always opened sentences",
  source: "Merriam-Webster's Dictionary of English Usage",
  gatePrompt: "Paste a paragraph you wrote. Circle every \"Additionally\", \"Furthermore\", \"That said\" and \"However\" standing at the front of a sentence, and rewrite each as \"And\", \"But\" or \"So\". Read both versions aloud and keep the one that sounds like you.",
  fallback: "None of the four connectors was reporting healthy at 09:10, and none of the alerts was routed to the on-call rotation. Additionally, the status dashboard was serving data that was twenty minutes stale. That having been said, customer impact was limited to a single tenant on the shared cluster. Furthermore, we have since corrected the routing rule and added a synthetic check.",
  idea: "Look the rule up before you enforce it, because both of these prohibitions are contradicted by the entire recorded history of the language.",
  why: "\"None\" descends from Old English nan and has taken plural verbs since the ninth century; the singular-only claim is an argument from etymology that no major usage authority has supported in a hundred years. Sentence-initial \"and\" and \"but\" are attested continuously from Old English through every period of English prose since. Neither prohibition has ever described the language it claims to govern.\n\nThey survive because they are cheap to state and because the cost of avoiding them is invisible to the person paying it. Substituting \"additionally\" for \"and\" drops four syllables of Latinate connective at exactly the point where the reader is working out how this sentence relates to the last one. The heavier the connective, the more that relation reads as bureaucratic rather than logical, and a paragraph of them reads as a document written to be filed. Two minutes in a usage dictionary before you correct someone is what stops you spreading that cost across every draft you touch.",
  failureMode: "Paragraphs strung together on heavy connectives because the light ones were forbidden: \"Additionally, the dashboard was showing stale data. That having been said, customer impact was limited. Furthermore, we have corrected the routing rule.\" Three sentences, three throat-clearings, and the actual logical relations are now weaker than \"and\", \"but\" and \"so\" would have made them. The \"none\" version is quieter: \"none of the four connectors was reporting healthy\" is not wrong, but it was chosen out of fear rather than for a singular sense, and the writer will defend it in review as correctness.",
  worked: "None of the four connectors were reporting healthy at 09:10, and none of the alerts were routed to the on-call rotation. And the status dashboard was serving data that was twenty minutes stale. But customer impact was limited to a single tenant on the shared cluster. So we have since corrected the routing rule and added a synthetic check.\n\nThree heavy connectives came out and both \"none\"s went plural. \"Additionally\", \"That having been said\" and \"Furthermore\" became \"And\", \"But\" and \"So\", which drops ten syllables and, more usefully, states the relations instead of gesturing at them: the contrast is now a contrast and the fix is now a consequence of the failures above it. The \"none\" change buys the reader nothing, and that is the honest version. \"Was\" was never wrong. It was chosen out of fear, and the only thing moving it wins is that you stop defending fear as correctness in review. The cost is that the paragraph now opens three consecutive sentences on a conjunction, which is a tic of its own. In a longer write-up you would keep \"But\", where the reversal earns the signal, and let the other two start bare.",
  experiment: "Open your last incident write-up and count the sentence-initial connectives of three syllables or more. Replace half of them with \"And\", \"But\" or \"So\", then read the paragraph aloud. Write down whether anything became less clear, or only less formal.",
  reflection: "Which of the two prohibitions had you genuinely internalised, and what has it been costing your sentences?",
  recall: {
    q: "What does the corpus evidence say about \"none\" taking a plural verb and about opening a sentence with \"and\"?",
    a: "Both are attested throughout the recorded history of English. \"None\" has taken plural verbs since Old English, and sentence-initial \"and\" and \"but\" run continuously from the earliest prose onward. Neither prohibition has ever matched the language.\n\nThe practical move is the habit: any contested correction is worth two minutes in a usage dictionary before you make it, because the cost of the workaround lands on every sentence that follows."
  },
  deepDive: "Take the connectives in this draft and tell me which heavy ones I reached for out of habit, and what each sentence would do with a plain \"but\" instead."
},
{
  id: "usage-readability-formulas",
  track: "usage", level: "document",
  title: "Readability formulas count syllables, and ISO 24495-1 declines to rely on them",
  source: "ISO 24495-1:2023, Plain language, Part 1: Governing principles and guidelines",
  gatePrompt: "Take a document you wrote for a reader outside your team. Write down the one thing that reader has to do after reading it, then mark every place in the document where that action is described. If it appears once, in the middle, note that before you read on.",
  fallback: "We put the migration guide through a readability checker and brought it from grade 14 down to grade 9 by splitting the long sentences and replacing words of three syllables or more. It now scores as plain English, so we are treating the clarity action item as closed. Two of the three pilot customers did still call support to ask which step to run first, but the document meets the bar we set for the quarter.",
  idea: "Judge a document by whether its intended reader can find, understand and use what they need, not by a grade-level score.",
  why: "Flesch-Kincaid and its relatives compute a number from average sentence length and average syllables per word. That is the whole input. They were fitted decades ago against comprehension tests on schoolchildren reading continuous prose, and they cannot see organisation, whether a term is familiar to your audience, whether steps appear in the order the reader performs them, or whether the reader succeeded at the task. ISO 24495-1 defines plain language by reader outcome instead: the intended readers can find what they need, understand it, and use it.\n\nThe measurement problem is that the formulas are trivially gameable in the wrong direction. Splitting one accurate sentence into three choppy ones improves the score. So does swapping a precise technical term for a longer vague phrase, because \"deprecate\" scores worse than \"stop using it the way we said before\". You can optimise a document into a better number and a worse reader, and nothing in the score will tell you that is what happened.",
  failureMode: "A migration guide taken from grade 14 to grade 9 by shortening sentences and words, shipped as \"now plain English\", while pilot customers still ring support to ask which step comes first. The score moved because sentence length moved. The ordering, the unstated prerequisite and the undefined term are all exactly as they were, because the formula never looked at any of them.",
  worked: "We put the migration guide through a readability checker and moved it from grade 14 to grade 9, which is a fact about our sentence lengths and not a finding about our readers. The thing a reader has to do with this guide is run the migration steps in the right order. That order is stated once, in the middle of the document. It is not in the opening, not in the summary and not attached to the first step. Two of the three pilot customers rang support to ask which step to run first, which is that gap arriving in the only place it counts. The clarity item goes back to open. It closes when two customers from the next cohort get through the migration end to end while we watch, without asking us what comes first, and not when a score says grade 9.\n\nThe document is now judged on the one action its reader has to take, and the grade level is demoted to what it measures: average sentence length and average syllables per word, neither of which can see where the step order appears or whether it appears at all. The support calls stopped being a concession at the end of the note and became the finding, because two of three readers failing to work out step one is the outcome the score is blind to. The cost is that the item misses the quarter, and the new test needs two customers, a booked hour and someone willing to sit in silence writing down every stall, where the old test needed a browser tab. It also leaves something unaudited. The grade-9 rewrite has already shipped, and splitting sentences and swapping out three-syllable words may have traded precise terms for vaguer ones. Checking that is a separate pass over the guide itself.",
  experiment: "Take a document you have already shipped and find two people from its intended audience. Ask each to perform the task the document exists for while you watch in silence, and write down every point where they stop, backtrack or ask you a question. Compare that count against whatever readability score the document earns.",
  reflection: "Where did your readers actually stall, and would any readability formula have found that spot?",
  recall: {
    q: "What do readability formulas measure, and what does ISO 24495-1 use in place of them?",
    a: "They compute a score from average sentence length and average syllables per word, and nothing else. They cannot see organisation, task order, term familiarity, or whether a reader succeeded at what they came to do.\n\nISO 24495-1 defines plain language by reader outcome: the intended readers can find what they need, understand it, and use it. That is testable with actual readers, and a grade-level score is not."
  },
  deepDive: "Help me design a five-question check for this document that tests whether a real reader can complete the task, rather than whether my sentences are short."
}
);
