/* Track: The savings rate arithmetic. Ordered foundational first.
 *
 * The savings rate is the term you set and the return is the term you guess at,
 * and most of what follows is algebra rather than evidence. Where there is no
 * trial behind a claim this track says craft and shows the working, because a
 * derivation dressed up as a finding is the easiest lie to tell about money. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "rate-savings-rate-dominates",
  track: "rate", level: "judgement",
  title: "Years to a target balance is set mostly by your savings rate, because the rate moves the finish line as well as the balance",
  source: "The annuity accumulation formula applied to a target written as a multiple of annual spending, which is standard algebra rather than anybody's finding",
  gateIntro: "A colleague has sent you a spreadsheet with one cell shaded yellow and labelled expected annual return. They have put eight percent in it. You think five is closer to honest. Twenty minutes of lunch goes into that argument. Neither of you touches the row three lines above it, which holds the amount that leaves your account on the fifteenth of each month and has not been changed since 2022. The file is still open in front of you and the cursor is in the yellow cell.",
  gatePrompt: "Write the instruction that changes the cell you actually control: the amount, the day it runs, and the account it lands in.",
  evidence: "No trial. This is the annuity accumulation formula with the target written as a multiple of annual spending, and it is arithmetic you can reproduce in a spreadsheet in about five minutes rather than a result anybody measured. It cannot tell you what rate is achievable for you, whether today's spending is a fair proxy for the spending you will have later, or what real return to assume. It only says how the terms trade against one another once you have supplied them, and every one of those inputs is doing more work than the formula is.",
  replication: "craft",
  idea: "Raising the savings rate shortens the horizon twice over, because it adds capital faster and lowers the amount of capital required at the same moment.",
  why: "Write the target as a multiple of annual spending rather than as a dollar figure and the double effect falls straight out. If you save some fraction of income you spend the rest, so the target is proportional to one minus the rate while the annual contribution is proportional to the rate. The number of contribution-years you need is therefore the multiple times one minus the rate, over the rate. At a tenth of income saved that factor is nine. At three tenths it is a shade over two. Tripling the rate cuts the contribution-years required by close to a factor of four, and no return has been credited yet.\n\nThe return then discounts that number and it compounds, so on a long enough horizon it wins. The honest claim is not that returns do not matter. It is that the two terms are different kinds of object. One is a decision you make on a Tuesday afternoon and can revise next month. The other is a draw from a distribution whose mean you will not know until the horizon has already passed, and which no amount of attention on your part will move. Arguing about the second is arguing about the width of a band you do not set.\n\nWhich leaves a rule that is stronger than it sounds. Plan against the rate, because it is the term you choose, and treat the return as a range you test the plan against rather than a number you pick. If the plan works at eight percent and fails at four, the assumption doing the work was never about markets. It was that you would save more than you are saving, and the return cell was quietly carrying that shortfall for you.",
  failureMode: "Three years of reading about asset allocation to add an expected point of return to a balance of ninety thousand dollars, which is nine hundred dollars a year. Over the same three years the transfer stayed at four hundred a month when it could have been six hundred, which was two thousand four hundred dollars a year forgone. The allocation work was real and it was worth roughly a third of the increase you did not make.",
  worked: "This one is a rule about what you are allowed to plan against, and then a transfer:\n\n\"State the plan as a savings rate written down as a percentage of gross pay, and re-run it at three percent real and at seven percent real. If it only works at the top of that band, raise the rate rather than the assumption.\"\n\n\"Increase the standing transfer to fifteen percent of each pay from next cycle, and do not touch the return cell for twelve months.\"\n\nWhat is deliberately absent is a chosen return. The plan has to survive a band rather than rest on a point estimate, because a point estimate is exactly where an optimistic assumption goes to hide. The twelve month freeze on the return cell is there because that cell is the one that is fun to adjust, and adjusting it feels like progress while changing nothing at all.",
  experiment: "Open whatever plan you have, in a spreadsheet or in your head, and find the return assumption. Set it to three percent real and see what breaks. Then replace the savings rate with what you actually saved last month against gross pay, not what you intend to save. Most people find that the plan was resting on an optimistic return and an aspirational rate at the same time, and that the two errors had been covering for each other for years.",
  reflection: "What return was your plan assuming, and what rate were you actually running last month?",
  recall: {
    q: "Why does raising the savings rate shorten the horizon by more than the extra contributions on their own would explain?",
    a: "Because the target is defined by your spending, and spending is what is left after saving. Raising the rate increases the annual contribution and shrinks the multiple of spending you have to reach, so the numerator falls while the denominator rises. The contribution-years required fall as one minus the rate over the rate, which is why going from a tenth to three tenths cuts them by around four rather than three.\n\nThe consequence is that the rate is the only term acting on both ends of the problem. The return acts on one end and you do not set it, so a plan that fails at a conservative return assumption is almost always telling you something about the rate instead."
  },
  deepDive: "Here is my gross income, my actual spending and what I transfer each pay. Compute my real savings rate, then show me how many years the plan moves if I raise the rate by five points, against how many it moves if the real return comes in two points under what I assumed."
},
{
  id: "rate-contributions-dominate-early",
  track: "rate", level: "annual",
  title: "For most of a working accumulation the balance is mostly money you put there, not money it earned",
  source: "The annuity accumulation identity, comparing cumulative contributions against cumulative earnings; arithmetic rather than a study",
  gateIntro: "Your super statement arrives and the line you go to first is investment earnings, because that is the interesting one. It says something in the low thousands. Two lines above it, employer contributions says something noticeably larger, and you have never put those two figures side by side. You are thirty-six. The fund has enclosed a form offering you a choice between two investment options, each with a different fee and a page of risk language, and the form is due in three weeks.",
  gatePrompt: "Write the annual instruction that decides, in order, which of contributions, fees and investment option you look at first and when you stop.",
  evidence: "No trial. Run the annuity sum with a level annual contribution and a constant real return and ask when accumulated earnings first exceed accumulated contributions. It is one equation, the contribution cancels out of it entirely, and the answer lands around the twenty-seventh year at a five percent real return, out past year forty at three percent, and around year twenty at seven percent. What the identity assumes away is everything real: contributions that rise with pay, returns that arrive in a sequence rather than as an average, fees, tax and withdrawals. It is a rough map of when the balance stops being mostly deposits, not a projection of anybody's account.",
  replication: "craft",
  idea: "Cumulative earnings only overtake cumulative contributions decades in, so for the first stretch of an accumulation the decisions worth your attention are the ones about how much goes in.",
  why: "The crossover calculation has a property that makes it unusually trustworthy: the size of the contribution drops out. Both sides scale with it, so what remains is an equation in the return and the number of years alone, and the answer is the same for someone putting in two hundred dollars a month and someone putting in five thousand. At a five percent real return the accumulated earnings pass the accumulated deposits somewhere around year twenty-seven. Almost everybody guesses much earlier.\n\nSo there is a long opening phase in which the balance is largely a record of your own deposits with a return decorating them. During that phase a point of extra return applies to a small balance while a point of extra savings rate applies to your entire income, and the second is larger by a wide margin. The ordering reverses later and reverses permanently, which is why the same person should be paying attention to different things at forty and at sixty.\n\nThe trap is that the return is the more interesting object from day one. Performance tables, option comparisons and allocation arguments are all available, all engaging, and all applied to a balance too small for any of them to move much. The contribution decision is dull and it is the one with the leverage. What the arithmetic buys you is permission to make the dull decision once a year and to stop feeling that ignoring the interesting one is negligence.",
  failureMode: "Two option switches in four years chasing half a percent on a balance of eighty thousand dollars, which is four hundred dollars a year, while the contribution rate sits at the legislated minimum for the entire period. One extra percent of a hundred thousand dollar salary would have been a thousand dollars in the first year and more in every year after, because it grows with your pay and half a percent of a small balance does not.",
  worked: "An annual instruction, and the ordering is the instruction:\n\n\"Every year in July, in this order: check the contribution rate and raise it if it can be raised, then look at fees, then look at the investment option. Stop after twenty minutes whether or not I have got to the third one.\"\n\nAll three are worth doing and they are not worth equal attention. Left alone, attention flows to the third, because that is the one with a chart attached and a form to fill in. Naming the order means the twenty minutes gets spent at the top of the list. The hard stop is there so the exercise stays small enough to actually recur, and because the third item is where an afternoon disappears without changing anything.",
  experiment: "Find your most recent super or brokerage statement and put two figures next to each other: total contributions for the period, and total investment earnings for the period. Whichever is larger tells you which lever you are currently standing on. If contributions are larger, and mid-career they usually are, then this year's decision is a contribution decision and you can close the performance table without guilt.",
  reflection: "Which figure was larger on your last statement, and which of the two had you been reading about?",
  forecast: { q: "Will I raise my contribution rate before I next change my investment option?" },
  recall: {
    q: "Why does the point where accumulated earnings overtake accumulated contributions not depend on how much you contribute?",
    a: "Because both sides scale linearly with the contribution. Cumulative deposits after some number of years are that number times the annual amount, and the balance is the same amount times the annuity factor, so the contribution cancels and what is left is an equation in the return and the years alone.\n\nWhich is why the answer sits so much further out than people expect: around the twenty-seventh year at a five percent real return, past forty at three percent. For most of a working accumulation the balance is a record of deposits, so the deposit is the term worth attention first."
  },
  deepDive: "Here is my balance, my annual contributions and the fee I pay. Work out where my own crossover point falls, and tell me whether changing investment option this year would move more or less than a two point rise in my contribution rate."
},
{
  id: "rate-residual-inversion",
  track: "rate", level: "standing",
  title: "Saving what is left over guarantees a variable savings rate, because a residual absorbs every shock in the budget",
  source: "Pay-yourself-first practice in retail banking and household budgeting, and the accounting identity underneath it",
  gateIntro: "It is the twenty-ninth. Pay landed on the fifteenth, and the plan on the fifteenth was to move whatever survived to the end of the month across to savings. What has survived is sixty-two dollars. Last month it was four hundred and ten. The month before that it was nothing at all, because the car needed two tyres. None of those three months contained a mistake. You are sitting with the transfer screen open and sixty-two dollars in mind.",
  gatePrompt: "Write the instruction that fixes the order rather than the amount, including what happens in a month when it does not fit.",
  evidence: "No trial. Pay-yourself-first is universal advice with no experiment isolating the ordering, and the strongest thing that can be said for it is that the identity behind it is not in dispute and that payroll deduction schemes, which are the institutional version of the same ordering, do show high persistence. What has not been established is how much a household's total saving actually rises when the order is reversed, as opposed to how much of it merely becomes predictable. Predictability is a real benefit and it is a smaller claim than the one usually made.",
  replication: "craft",
  idea: "Income equals spending plus saving, so one of the three is discovered rather than chosen, and choosing which one is the only real decision the identity allows.",
  why: "Income equals spending plus saving. That is an identity, not a theory, so any two of the three fix the third. What a household actually decides is which two it sets and which one it finds out about afterwards, and almost everyone finds out about the saving. The consequence is arithmetic rather than psychological. The discovered term inherits the entire variance of the other two, so every unexpected bill, every good weekend and every month with three birthdays in it lands on that term in full.\n\nReverse the order and the variance moves with it. Set the saving first and spending becomes the quantity you discover, and spending turns out to be surprisingly compressible when it has to be. This is not a claim that people can live on arbitrarily little. It is a claim about where the slack sits. A household running a fixed transfer finds the month's adjustment somewhere inside the part of its outgoings that was always flexible, without ever making an explicit decision about which part.\n\nThe second effect is measurement, and it matters more than it looks. A residual savings rate cannot be planned against, because you do not know it until the period has closed. Any horizon computed from it is a guess about a quantity nobody is controlling. A set rate is known in advance, which makes every other number downstream of it computable. You cannot forecast off a residual, and a plan built on one is a plan built on last month's weather.",
  failureMode: "A year of saving whatever survives produces four hundred and ten, then sixty-two, then nothing, then three hundred, then nothing, then ninety, and the twelve month total comes in under two thousand dollars. A flat two hundred a month across the same year would have been two thousand four hundred, and more usefully it would have been a number you could have built the rest of the plan on.",
  worked: "The instruction has to name the order and then defend it:\n\n\"Transfer $250 to the savings account the day after each pay lands, before any bill is paid, and if the month gets tight, take the shortfall out of the everyday account rather than reversing the transfer.\"\n\nThe second clause is the whole instruction. The first clause on its own is just a transfer, and a transfer with a reversal habit attached is a residual with extra steps. What actually makes spending the adjusting term is a standing rule that the transfer is not the thing that gives way.\n\nWhat is deliberately absent is any rule about what to cut when it is tight. That is on purpose. You do not decide in advance, because the household finds the slack somewhere different every month and it is better at that than any rule you would write now.",
  experiment: "Pull up your last three months of transfers into savings and write the three figures down. If the largest is more than about a fifth above the smallest, you are running a residual. Convert it today: take an amount at the low end of those three rather than the average, and set it as a fixed transfer dated the day after pay. The low end is the point. The number has to survive the worst of those three months without being touched.",
  reflection: "What were your last three months of saving, and how far apart were the highest and the lowest?",
  forecast: { q: "Will I get through the next three months without reversing or reducing the fixed transfer?" },
  recall: {
    q: "Why does a smaller fixed transfer beat saving the leftovers, even in months when the leftovers would have been larger?",
    a: "Because income equals spending plus saving is an identity, so whichever term is solved for last absorbs the variance of the other two. Leaving saving until last means every surprise in the month lands on it, and the resulting series averages down to whatever spending happened to permit.\n\nA fixed transfer moves that variance onto spending, which is where the compressible part of a household budget actually lives. It also makes the rate known in advance, and a known rate is the only kind you can compute a horizon from."
  },
  deepDive: "Here are my last six months of savings transfers and my pay dates. Tell me the largest fixed amount I could have run for all six months without a single reversal, and what that would have totalled against what I actually saved."
},
{
  id: "rate-gross-versus-net",
  track: "rate", level: "annual",
  title: "Most people compute their own savings rate wrong in both directions at the same time",
  source: "Household balance-sheet accounting: the distinction between a payment that reduces a liability and a payment that buys the use of somebody else's capital",
  gateIntro: "Somebody asks you at a barbecue what your savings rate is and you say about eight percent, because that is the transfer divided by your take-home pay and you did the sum standing up. On the drive home it occurs to you that you paid down eleven hundred dollars of loan principal last month, that your employer put twelve percent of your salary into super, and that neither of those appeared anywhere in the eight percent. It also occurs to you that you have no idea whether the fourteen hundred of interest belonged in there.",
  gatePrompt: "Write the annual instruction that fixes the definition: which lines go in the top, which go in the bottom, and which month you do it.",
  evidence: "No trial, because this is a definition rather than a finding. The balance-sheet test is the one national accounting bodies use in substance when they separate a reduction in liabilities from the purchase of a service, and it resolves every disputed line in a household budget consistently. What it cannot do is tell you which definition other people are using when they quote a rate, which is why comparing your number to a published average or to a colleague's is close to meaningless unless you know both definitions. Use it for your own series over time, not for comparison.",
  replication: "craft",
  idea: "Saving is the part of this period's income that ends the period as an asset you own or a debt you no longer owe, which puts loan principal and employer super in, and loan interest and market movements out.",
  why: "One definition settles every argument. Saving is the portion of this period's income that finishes the period as an asset you hold or a liability you have discharged. Run each line through that test and the disputes evaporate. A principal repayment discharges a liability, so it is saving. Interest buys the use of somebody else's money for a month and leaves nothing behind, so it is consumption in exactly the way rent is. An employer contribution to super is income you earned that happened to arrive already saved, so it belongs in both halves of the fraction. A capital gain on something you already owned is not saving at all, because it did not come out of this period's income.\n\nThe two common errors run in opposite directions and most people make both at once. Leaving out principal and employer contributions understates the rate, frequently by more than the entire voluntary transfer being counted. Counting the whole loan repayment, or counting a good year in the market, overstates it. Because the errors have opposite signs the net is unpredictable, which is worse than a bias. A consistently wrong number can at least be tracked.\n\nThe denominator gets chosen even more carelessly than the numerator. Measured against take-home pay, employer contributions are not in the bottom of the fraction, so counting them in the top inflates the result. Measured against total gross remuneration including super, both halves are consistent and the rate stays comparable across a pay rise, a change in tax rates and a change in the legislated contribution. That comparability is why gross is the better denominator, even though it produces a smaller and much less flattering number.",
  failureMode: "You believe you are saving eight percent when the balance-sheet figure is nearer twenty, conclude the horizon is hopeless, and stop planning entirely for two years. Or the mirror image: you count the whole loan repayment and a strong market year, believe you are at thirty-five, and the first flat year removes a saving that was never income in the first place. Both errors cost the same thing, which is a plan resting on a number that does not mean what you think it means.",
  worked: "One annual instruction with the contested lines named, because the argument is always about the same four:\n\n\"Every July, compute the savings rate as voluntary transfers, plus loan principal repaid, plus all superannuation contributions, divided by total gross remuneration including super. Exclude loan interest. Exclude market movements.\"\n\nThen write the answer next to last year's answer, in the same note.\n\nWhat is deliberately absent is any adjustment for offset balances, redraw, one-off bonuses or the value of the house. Every one of those is a place where the number can be improved by argument rather than by saving, and a metric you can argue with is a metric you eventually will.",
  experiment: "Compute it once, today, for the last twelve months. With a loan statement and a super statement in front of you it takes about fifteen minutes. The principal figure is the difference between the opening and closing loan balance, less any redraw. Put the result in a dated note somewhere you will find it. You will want last year's figure in a year and you will not be able to reconstruct it then.",
  reflection: "What was your rate before you added principal and super, and what was it after?",
  forecast: { q: "Will I compute this same number again, using the same definition, twelve months from now?" },
  recall: {
    q: "Why is a loan principal repayment saving while the interest on the same loan is not?",
    a: "Because saving is the part of this period's income that ends the period as an asset held or a liability discharged. Principal reduces the debt, so net worth rises by the amount paid. Interest buys the use of somebody else's capital for the month and leaves no balance-sheet trace, which makes it consumption in the same way rent is.\n\nThe same test settles the other disputed lines. Employer superannuation contributions are income that arrived already saved, so they belong in the top and the bottom of the fraction. A market gain on assets you already held is not saving, because it never passed through this period's income."
  },
  deepDive: "Here are my payslip, my loan statement and my super statement for the last year. Compute my savings rate on the balance-sheet definition and tell me how far my own estimate was off and in which direction."
},
{
  id: "rate-percent-not-dollars",
  track: "rate", level: "standing",
  title: "A savings rate is the only quantity in your plan that inflation cannot quietly erode",
  source: "The definitional property of a ratio of two nominal quantities measured over the same period, set against the way dollar targets and return assumptions each carry a hidden inflation term",
  gateIntro: "The figure in your head is a million dollars, and it has been a million dollars since you were twenty-eight. You are thirty-nine now. It survived the two years when everything got dearer at once, it survived three pay rises, and it survived the house you were pricing back then becoming a house you could not price now. The fortnightly transfer meant to get you there is still six hundred dollars, set in the same year as the figure. Your bank has just emailed asking whether you want to review your automatic transfers.",
  gatePrompt: "Write the instruction so that neither the amount nor the target needs revisiting when prices move.",
  evidence: "No trial, and none is needed, because this is a property of the arithmetic rather than a claim about behaviour. Saving over income in the same period puts the price level in both halves of the fraction, where it cancels. What is a behavioural claim, and is unsupported here, is that people actually re-index dollar figures if you leave them to it. The observation that they mostly do not is drawn from the fact that dollar targets survive for years without revision, which is an impression rather than a measurement, and you should treat it as one.",
  replication: "craft",
  idea: "A savings rate is a ratio of two nominal amounts measured over the same period, so the price level cancels out and the number keeps meaning the same thing without ever being revised.",
  why: "Every other quantity in a household plan carries an inflation term that has to be tracked, and most people track none of them. A dollar target is fixed in nominal terms and therefore shrinks in real terms every year it is left alone. A dollar transfer does the same. A return assumption is either nominal or real, the two differ by enough to move a horizon by a decade, and the label is frequently written down nowhere at all. A rate has none of this. It is this year's saving over this year's income, both in this year's dollars, and the units cancel.\n\nThe practical consequence is that a rate keeps working while nobody is paying attention, which is the property this whole site is organised around. Denominate the transfer as a share of pay and it rises with every increase, tracks prices to whatever extent your pay does, and never needs a review. Denominate it in dollars and it is a decision with a silent expiry date. Nothing will tell you when it passed.\n\nThe caveat is worth naming rather than skipping. A rate is inflation-neutral, not inflation-proof. If your pay lags prices then a constant share of a shrinking real income is shrinking real saving, and the target, which is a multiple of your real spending, has not moved to meet it. What the rate buys is not protection. It is one fewer number you have to remember to re-index, and how many things you have to remember is the constraint that actually binds.",
  failureMode: "A target set eleven years ago and never revised, chased by a transfer set in the same year. Both have been drifting the entire time and in opposite directions: the target has become easier to reach and less adequate once reached, while the transfer has become a smaller share of a larger salary. On paper nothing has changed. Neither number means what it meant when you wrote it.",
  worked: "The instruction is denominated in percent, with a named fallback for a bank that will not do percentages:\n\n\"Set the automatic transfer to twelve percent of each pay, and if the bank will only accept a dollar figure, set it to twelve percent of my current pay and add one line to the July checklist to recompute it.\"\n\nThe target gets the same treatment:\n\n\"State the target as a multiple of my current annual spending, and do not write the dollar figure down anywhere I will read it later.\"\n\nWhat multiple is a separate question and not this one. What is deliberately absent is any inflation forecast, because there is nothing here to forecast: both halves of a ratio are measured in the same year's dollars, so the adjustment happens without an assumption. That is the whole advantage, and it is worth more than a better forecast would have been.",
  experiment: "Check whether each of your recurring transfers is set as a dollar amount or a share of pay. Most banking apps only offer dollars, so do the two minute version: work out what percentage of your current gross pay each one represents and type that percentage into the transfer's description field so it travels with the instruction. Then take the dollar target you have been carrying around and convert it into a multiple of what you spend in a year.",
  reflection: "Was your transfer denominated in dollars or in percent, and when was the amount last set?",
  recall: {
    q: "Why does inflation leave a savings rate alone when it does not leave a dollar target or a return assumption alone?",
    a: "Because a rate is a ratio of two nominal quantities measured over the same period, so the price level appears in the numerator and the denominator and cancels. A dollar target is fixed in nominal terms and falls in real terms every year it is untouched, and a return assumption shifts by several points depending on whether it is stated in nominal or real terms, which often is not recorded anywhere.\n\nNeutral is not the same as protected. If your pay lags prices, a constant share of a shrinking real income is shrinking real saving against a target that has not moved. The gain is one fewer number to remember to re-index, and remembering is the thing that actually fails."
  },
  deepDive: "Here are my recurring transfers, my gross pay and the dollar target I have been carrying in my head for years. Convert all of it to percentages and multiples, and tell me what that target has actually been worth in each of the last five years."
},
{
  id: "rate-marginal-not-average",
  track: "rate", level: "standing",
  title: "The only savings rate available for a decision today is the one on money you have not received yet",
  source: "The distinction between an average and a marginal rate applied to household saving, and the practice of pre-committing a fixed share of new income",
  gateIntro: "You have done the sum and it says eleven percent. You would like twenty. Getting there out of what you already earn means finding nine percent of your income inside a life that currently consumes all of it, and each time you have sketched what that would take, the list has arrived at the car and the suburb and you have put the pen down. There is a bonus due in March and a review in May. You have decided nothing about either, and March is closer than it was.",
  gatePrompt: "Write the rule that applies to money that has not arrived yet, as a share and a deadline, not as an intention.",
  evidence: "No trial. The distinction between an average and a marginal rate is definitional, and the claim that the marginal one is easier to change is an argument about unwind costs rather than a measured result. What weight it has comes from adjacent evidence: pre-commitment schemes that bind future pay rises show high persistence, and the same schemes applied to current income do not exist in the literature to compare against. So the mechanism is plausible and the specific advantage of marginal over average has not been tested head to head by anybody.",
  replication: "craft",
  idea: "Your average savings rate is a summary of arrangements you have already made, and only the rate you apply to income that has not yet arrived can be changed by a decision this afternoon.",
  why: "The average rate is a report on commitments already entered: a lease signed, a loan taken, a car financed, a suburb chosen, a set of subscriptions that renew themselves. Moving it means unwinding one of those, and every one is slow, expensive and emotionally loaded. That is why the distance between the rate people have and the rate they say they want persists for years at a stretch. It is not a character problem. It is that the average is mostly a function of decisions with long unwind times.\n\nMoney that has not arrived has no commitments attached to it. Assigning a share of it costs nothing in the present and unwinds nothing, so the decision is available now in a way that the other one is not. A rule of the form half of anything new goes to the transfer takes a minute to write and then acts on every raise, bonus, refund and side payment from here on with no further attention. The average then rises on its own as income arrives, which is the only route to a substantially higher rate that has ever worked without a crisis behind it.\n\nThe drift arithmetic is worth having explicitly. Hold real spending flat and commit a marginal share above your current average, and every increment of income pulls the average upward, the two converging over years with no single painful step. Commit a marginal share equal to your average and the average never moves. Commit nothing and the average falls, because by default new income joins the spending side.",
  failureMode: "Twice a year you resolve to save more, both times about income you already have, and both resolutions are gone inside two months. The bonus lands in March with no rule attached to it and cannot be traced by June. A rule you could have written in sixty seconds in February would have caught that one, and it would also have caught the next four.",
  worked: "One standing rule, written so that it binds before the money is visible:\n\n\"Fifty percent of any increase in my pay, and fifty percent of any bonus, refund or one-off payment, goes to the transfer within seven days of it landing, and the recurring transfer amount is raised permanently rather than the money being swept across once.\"\n\nPermanently is the word doing the work. Sweeping half a bonus across is a pleasant thing to have done and changes nothing structural. Raising the recurring amount converts a single event into a change in the rate that outlives it.\n\nWhat is deliberately absent is a target for the average rate. The average is an outcome here rather than an input, and setting a target for it invites exactly the unwinding exercise that has already failed every time you have attempted it.",
  experiment: "Write the marginal rule down today, at a share you would genuinely accept on a raise nobody has promised you, and put it wherever your instructions live. Then find the next piece of income that is not your ordinary pay - a bonus date, a tax refund, a leave payout, a side invoice - and put a calendar entry on it with the split already worked out. One rule and one dated entry is the entire install.",
  reflection: "What share of the next dollar you receive is committed, and had you ever set that number before today?",
  forecast: { q: "Will the next payment I receive outside my ordinary pay be split according to the rule I just wrote?" },
  recall: {
    q: "Why is a rule about future income more likely to move your savings rate than a decision to save more out of what you already earn?",
    a: "Because the average rate summarises commitments already in place, and each of them has a long, expensive unwind, which is why the gap between the rate people have and the rate they want survives for years. Income that has not arrived carries no commitments, so assigning a share of it costs nothing today.\n\nAfter that the drift does the work. A marginal share above your current average pulls the average up with every increment of income and no single painful step. A marginal share of nothing lets the average fall, because new income joins the spending side unless something intercepts it."
  },
  deepDive: "Here is my income history for the last five years and my current rate. Tell me what marginal share of new income I would have needed to be where I wanted to be by now, and what it has to be from here."
},
{
  id: "rate-consumption-tracks-income",
  track: "rate", level: "judgement",
  title: "Your spending follows this month's income far more closely than any lifecycle model says it should",
  source: "The excess sensitivity literature on household consumption, running from Hall's random walk test through the tax rebate natural experiments of Johnson, Parker and Souleles, and Carroll, Buffer-Stock Saving and the Life Cycle/Permanent Income Hypothesis (Quarterly Journal of Economics, 1997)",
  gateIntro: "Your income this year will be close to what it was last year, you know that, and you knew it in January. There is nothing here to smooth. And yet the four days after pay look nothing like the four days before it, and you could describe the difference without opening a statement. A friend paid monthly says the same about their third week. You are on the transfer screen about to set an amount, and the two fortnights would give you two very different answers.",
  gatePrompt: "Write the instruction so the money is gone before spending sees it, and name the amount you would size against your leanest week.",
  evidence: "A large body of work rather than one study, which is why it sits here as replicated. The permanent income hypothesis predicts that consumption responds only to news about lifetime resources, so a payment you were told about in advance should move spending on the day you were told rather than the day it lands. Tested on household data the prediction fails in a consistent direction: anticipated payments produce large responses at the moment of receipt, and spending over a pay cycle shows a sawtooth no smoothing model generates. This has been reproduced across countries, datasets and natural experiments including tax rebates. What remains genuinely unsettled is the mechanism - liquidity constraints, precautionary buffers, mental accounting and plain inattention all fit the data - and the size of the response varies a great deal by household and by the size of the payment, so no single figure should be quoted from it.",
  replication: "replicated",
  cheat: "Assume your spending will track your pay rather than your plan: consumption responds to predictable income arriving far more than any smoothing model allows.",
  idea: "Households do not smooth consumption the way the theory requires, so spending moves when income arrives even when the arrival was fully expected.",
  why: "The permanent income hypothesis makes a sharp and testable prediction. Consumption responds to news about lifetime resources and to nothing else, which means a raise you learned about six months ago is already in your spending and the day the money first appears should be unremarkable. A rebate announced in advance should move behaviour on the announcement, not the deposit. Against household data that prediction fails, it fails in the same direction every time, and it has failed across many countries and datasets.\n\nThe name for the failure is excess sensitivity, and it has outlasted a great many attempts to explain it away. The proposed mechanisms differ and the argument between them is live: some households are liquidity constrained, some are running a precautionary buffer, some are doing mental accounting, and some are simply not paying attention. That disagreement is real and worth knowing about. The pattern itself is not what is in dispute.\n\nWhat follows is not a moral conclusion. It is that a plan resting on holding spending flat while income rises is resting on the single behaviour households reliably do not display. The design response is to shrink the income that reaches the account your spending draws on, because interception works with the finding while resolve works directly against it. Anything you build on the assumption that you are the exception should be sized so that being wrong is survivable.",
  failureMode: "You take a job paying twenty thousand more and intend to save the difference. Twelve months on, the difference is not identifiable in any account, and asked to name what it bought you could account for perhaps a third. Nothing was wasted in any way you would recognise as waste. The spending expanded into the space, which is what the evidence says spending does.",
  worked: "The instruction is written to accept the finding rather than argue with it:\n\n\"Any increase in my pay is split at the payroll or gross level before it reaches my everyday account, so the balance my spending sees does not rise by the full amount.\"\n\nWhere payroll cannot do that, the weaker version is still worth installing:\n\n\"On the day a pay increase first lands, raise the standing transfer by the same amount, on the same screen, in the same sitting.\"\n\nWhat is deliberately absent is any commitment about spending behaviour. There is no line here saying I will hold my costs flat, because that is precisely the promise the literature says people do not keep, and writing it into an instruction does not change the base rate.",
  experiment: "Total your transactions for the four days after each of your last two pay dates, then total the four days before each. Most people find a gap they can see without any analysis, and that gap is this finding in your own data. Then decide once whether your next pay increase will be visible in the everyday account at all, and set whatever it takes at the payroll or transfer level to make the answer no.",
  reflection: "What did the four days after pay look like against the four days before, and did the size of the gap surprise you?",
  recall: {
    q: "The theory says a pay rise you learned about months ago should not move your spending on the day it lands. What actually happens, and what should you build instead?",
    a: "Spending responds to income arriving rather than to news about it. Anticipated payments produce large responses at the moment of receipt and consumption over a pay cycle shows a sawtooth that no smoothing model generates, reproduced across countries, datasets and natural experiments. The explanations offered differ - liquidity constraints, precautionary buffers, mental accounting, inattention - and that argument is genuinely unsettled, but the pattern is not.\n\nSo a plan that assumes you will hold spending flat while income rises assumes the one behaviour households do not display. Build so the increase never reaches the account your spending draws on. Interception works with the finding and resolve works against it."
  },
  deepDive: "Here is my transaction history and my pay dates for the last six months. Show me how much of my spending is timed to income arriving rather than to anything I would call a need, and tell me what a gross-level split would have to be to make that pattern disappear."
},
{
  id: "rate-buffer-stock-target",
  track: "rate", level: "standing",
  title: "Below a cash buffer your savings rate is not a decision, because every shock has to be funded by not saving",
  source: "Christopher Carroll, Buffer-Stock Saving and the Life Cycle/Permanent Income Hypothesis (Quarterly Journal of Economics, 1997)",
  gateIntro: "The transfer has been running eight months at fifty dollars a week and you were pleased with it. Then the dentist quotes two thousand dollars for work that cannot wait until the new year. There is eleven hundred in the everyday account and nothing else liquid. The transfer is due to run on Thursday. You are looking at the cancel button and telling yourself it is temporary, and you have told yourself that before.",
  gatePrompt: "Write the two instructions in the order you would install them, and name the balance at which the first one hands over to the second.",
  evidence: "A theoretical model calibrated against household data rather than an experiment. Carroll showed that a consumer who is impatient but faces income risk they cannot insure behaves as though targeting a ratio of wealth to permanent income: below the target precaution dominates and saving is high, above it impatience dominates and spending rises. The model reproduces features of real household data that the standard lifecycle model does not, including consumption tracking income closely and wealth holdings that hover rather than climb steadily through working life. It is one paper, it is a calibration rather than a test against an intervention, and the target ratio it implies depends on parameters - impatience, risk aversion, the size and persistence of income shocks - that are estimated rather than observed.",
  replication: "single",
  idea: "Until there is a liquid buffer, a shock can only be funded out of that month's saving, so the rate reports what went wrong rather than what you chose.",
  why: "Carroll's consumers are impatient enough to prefer spending to accumulating, and exposed enough to income risk that they will not let their balance reach zero. Those two forces meet at a target ratio of liquid wealth to income. Below it, precaution wins and saving is high. Above it, impatience wins and spending rises until the ratio comes back down. The household therefore hovers around a buffer instead of accumulating steadily, which is what household data actually looks like and is not what the textbook model predicts.\n\nRead as a description of your own position, the useful part is what it says about the variance of your rate. If your liquid balance sits under your own target then the tyres, the vet and the insurance excess are all funded by not saving that month, because there is nowhere else for them to come from. The rate in any given month is then a report on what went wrong in it. That is the mechanism behind a savings history that looks like noise rather than like a policy.\n\nAbove the buffer, the identical shock is funded by the buffer and the transfer keeps running untouched. The rate becomes something you set. Which reorders the usual advice: the first job is not a high rate, it is a buffer large enough that the rate stops being a residual, and only after that is the rate worth pushing. How large the buffer should be is a separate question with its own literature and this entry does not settle it. What the model settles is the ordering.",
  failureMode: "Eight months of a fifty dollar weekly transfer, then a two thousand dollar bill, then a cancellation, then four months of nothing while you recover. The year totals roughly what six months of the transfer would have been. Worse, the arrangement now has a failure in its history, and a past failure is the single best predictor that the next version will not survive either.",
  worked: "Two instructions in sequence, and the sequence is the point:\n\n\"Until the buffer account reaches the amount I have written down, the entire transfer goes there and nothing goes anywhere else.\"\n\n\"On the first pay after the buffer reaches that amount, the whole transfer redirects to the long-term account, and the buffer is used for nothing except an unplanned expense.\"\n\nWhat is deliberately absent is any attempt to invest the buffer. Its job is to be there in the week the bill arrives, and every improvement to its return costs some of that. Also absent is permission to renegotiate the target amount in the middle of a bad month. Pick the number today, write it down, and revise it once a year, because a threshold you renegotiate under stress was never a threshold.",
  experiment: "Work out your liquid balance as a number of months of your own outgoings. If it is below the figure you would name as your own comfort point, redirect the entire transfer there this pay and stop splitting it. Splitting a small transfer between a buffer and a long-term account is the slowest available route to having either, and the buffer is the thing that stops the long-term one being cancelled in a bad month.",
  reflection: "How many months of outgoings are sitting liquid, and has a shock ever cancelled one of your transfers?",
  recall: {
    q: "Why does a household below its buffer have a savings rate it does not really control?",
    a: "Because with nothing liquid to absorb a shock, the only place a shock can be funded from is that month's saving. The rate then reports what went wrong during the month rather than what was decided at the start of it, which is why savings histories at low balances look like noise.\n\nCarroll's model reaches the same place from the other direction: an impatient consumer facing uninsurable income risk behaves as though targeting a ratio of wealth to income, saving hard below it and spending above it. It is a single calibrated model rather than a trial, but it explains why the first job is a buffer big enough for the rate to become a decision, and only then a higher rate."
  },
  deepDive: "Here are my monthly outgoings and my liquid balance. Tell me how many months I am carrying, what a shock the size of the largest one I have actually had in three years would do to my transfer, and whether I should be splitting the transfer at all yet."
},
{
  id: "rate-creep-moves-the-target",
  track: "rate", level: "standing",
  title: "A raise absorbed into your baseline moves the finish line further away, it does not merely fail to move you toward it",
  source: "The ratchet in household spending after an income increase, set against a target written as a multiple of spending; observation and arithmetic rather than a trial",
  gateIntro: "A recruiter has offered you a role at eighteen thousand more and you have accepted it. You start in five weeks. Between now and then you will make three or four choices that are each perfectly reasonable on their own: the better lease, replacing a car that is eleven years old, the childcare option you have been rationing. You have made none of them yet. Your transfer has not been touched since before the interview and you have not opened the app.",
  gatePrompt: "Write the instruction and the date it executes, both of them before the first pay at the new rate lands.",
  evidence: "No trial. That spending ratchets up after an income increase is close to universally observed and close to never measured cleanly, because the counterfactual household that got the same raise and did not absorb it is not available. The claim about timing, that absorption happens within a couple of pay cycles, is an impression rather than a finding and you should treat it as one. What is not an impression is the arithmetic: if the target is a multiple of spending then lifting baseline spending lifts the target by that multiple, and that part follows from the definition rather than from anybody's data.",
  replication: "craft",
  idea: "Because the target is a multiple of what you spend, absorbing a raise leaves the contribution flat while raising the amount you must accumulate, so the horizon gets longer than if the raise had never arrived.",
  why: "Everybody knows an absorbed raise fails to improve the rate. The part that gets missed is the double effect from the first entry in this track, running in reverse. If the target is a multiple of annual spending, then raising baseline spending raises the target by that same multiple. Twelve thousand dollars a year of new recurring outgoings does not just leave the annual contribution where it was, it adds twelve thousand times the multiple to the pile you have to build. Absorbing a raise leaves you further from the target than not receiving one would have.\n\nThe absorption itself is quick and it is not made of impulses. It is made of a handful of choices that are individually defensible and structurally permanent: a lease, a car payment, a school, a service tier, a suburb. Each is decided once and then recurs with no further decision, so the increase is committed long before anybody has thought about it as a pool of money. By the time you sit down to work out where it went, the answer is a set of standing arrangements rather than a set of purchases, and standing arrangements are not the sort of thing you can regret your way out of.\n\nThe ratchet is asymmetric, which is what makes it expensive. Adding a commitment takes an afternoon. Removing one takes months, usually involves a break fee or a sale, and feels like going backwards in a way that never having added it would not have. So the window in which new income is cheap to allocate is the few weeks before it starts arriving, and it closes without announcing itself. That is why the instruction here carries a date instead of an appeal to restraint.",
  failureMode: "Eighteen thousand more a year, of which around six thousand has become recurring commitments inside four months. The rate is unchanged, the income is higher, and the target, being a multiple of what you spend, has moved out by that multiple times six thousand, which on any plausible multiple is a six-figure addition to what you have to accumulate. The raise was real and it made the problem bigger.",
  worked: "The instruction is dated to the window rather than left as a principle:\n\n\"Before the first pay at the new rate lands, increase the standing transfer by sixty percent of the after-tax increase, effective that same pay.\"\n\nAnd the clause that keeps the window open long enough to matter:\n\n\"No new recurring commitment - lease, finance, subscription tier, ongoing service - for the first three months at the new income.\"\n\nWhat is deliberately absent is any limit on one-off spending. Buy the thing. A one-off purchase does not move the target, because the target is a multiple of what recurs, and a rule that bans both gets broken on the first weekend and then abandoned in full. The entire restriction sits on the recurring side, which is the side with the multiple attached to it.",
  experiment: "Take your last income increase, whenever it was, and list the recurring commitments that began within six months of it. Add up what they cost a year. That figure times whatever target multiple you use is the amount that raise added to your finish line. Then find the date of your next income change, whatever kind it is, and put the transfer increase in the calendar for the day before it with the new amount already typed into the title.",
  reflection: "Which recurring commitments started within six months of your last raise, and what do they cost you a year?",
  forecast: { q: "Will my next income increase pass without a single new recurring commitment starting in the three months after it?" },
  recall: {
    q: "In horizon terms, why is absorbing a raise worse than never having received it?",
    a: "Because the target is a multiple of what you spend. Absorbing the whole increase into recurring outgoings leaves the annual contribution exactly where it was while lifting the target by the multiple times the new spending, so the finish line moves away and the horizon is longer than it would have been with no raise at all.\n\nThe absorption is fast because it is built from a few individually defensible commitments, each decided once and then recurring without further decision. Adding one takes an afternoon and unwinding one takes months and a fee, so the money is only cheap to allocate in the weeks before it starts arriving."
  },
  deepDive: "Here is my current income, my spending and the increase I am about to receive. Tell me how far my horizon moves if I absorb all of it, half of it, or none of it, and which of my existing recurring commitments began within six months of a previous raise."
},
{
  id: "rate-cut-without-capture",
  track: "rate", level: "standing",
  title: "A spending cut only raises your savings rate if something moves the money the same day, and usually nothing does",
  source: "The compounding arithmetic behind the latte factor and its many relatives, examined for the step it skips between cutting and saving",
  gateIntro: "You have just cancelled four subscriptions in one sitting. Eighty dollars a month, gone, and the feeling is genuinely good. You close the laptop. Nothing else about the month has changed: same transfer on the same date, same everyday account, same card in the same wallet. There is now eighty dollars a month that has nowhere in particular to be, and the app you would need to open to give it somewhere is the one you have just closed.",
  gatePrompt: "Write the second half of what you just did, as an instruction with the same amount in it.",
  evidence: "No trial supports the causal step, and the causal step is where the entire claim lives. The compounding arithmetic is correct and nobody disputes it: a recurring amount removed and invested for decades reaches a large figure. What has never been shown is that the released money is saved rather than reabsorbed. The adjacent evidence runs the other way, since households spend a large fraction of income that becomes available to them, and nobody has separately measured what happens to an avoided cost, which is if anything less visible than a payment of the same size. Treating a cut as equivalent to a contribution assumes a marginal savings rate of one on the released money, and that is not a rate anybody has observed.",
  replication: "overclaimed",
  idea: "Cutting a cost releases cash into the account you spend from, and cash in the account you spend from is spending until an instruction moves it.",
  why: "The compounding sum is right and it is not the claim. Take a recurring cost, remove it, compound the amount over thirty years, and the number is genuinely large. Every arithmetic step of that holds. The unstated premise is that the released money entered the compounding, and the only mechanism ever offered for that is that you will notice it sitting there and do something about it. That is a claim about behaviour with nothing behind it, standing next to a literature that says the opposite about money which becomes available.\n\nCuts also have a salience problem that windfalls do not. A payment arriving is at least visible: it has a date, an amount and a line in the account. An avoided cost has none of those. It appears as a slightly larger balance at the end of a month that contained forty other things, which is precisely the form in which money gets absorbed without anybody deciding anything. If anything, a cut is easier to lose than a windfall of identical size.\n\nSo the correct version of the advice has two halves, and the second one is always the missing one. Cut the cost, and on the same day raise the standing transfer by what you cut. Do both or do neither. A cut with no capture is a small increase in your discretionary budget, which may be an entirely reasonable thing to want, but it should not be written down anywhere as saving and it will not show up in the rate at the end of the year.",
  failureMode: "Four subscriptions cancelled, eighty dollars a month, and nothing else touched. Twelve months later there is no trace of nine hundred and sixty dollars anywhere in the savings account, and the honest answer to where it went is that it never went anywhere. It stayed in the everyday account and did what money in the everyday account does.",
  worked: "Two clauses, and they have to run in the same sitting:\n\n\"Whenever I cancel or reduce a recurring cost, I raise the standing transfer by the same monthly amount before I close the app.\"\n\nAnd for a reduction that is annual rather than monthly:\n\n\"When a renewal comes in lower than last year, move the difference across as a single payment that day rather than intending to later.\"\n\nWhat is deliberately absent is any target for how much to cut. The size of the cut is not what this is about. The pairing is what it is about, and a small cut that is captured beats a large one that is not by an unbounded margin, because the second one is zero.",
  experiment: "List every recurring cost you have cancelled or reduced in the last two years and total the monthly amount. Then check whether your savings transfer ever went up by anything like that figure. For most people the two series are unrelated, which means the cutting was real and the saving was not. Fix it forwards rather than backwards: raise the transfer today by whatever share of those past cuts you can still afford, and pair every future one on the spot.",
  reflection: "What have you cut in the last two years, and did the transfer ever rise to match it?",
  recall: {
    q: "The compounding arithmetic behind cutting a small recurring cost is correct. Why is the advice still overclaimed?",
    a: "Because the arithmetic quietly assumes the released money entered the compounding, which requires a marginal savings rate of one on money that has become available. Nobody has measured such a rate on a household, and the evidence on income that becomes available runs the other way. Cash released into the account you spend from is spending.\n\nAn avoided cost is also harder to catch than a payment of the same size, because it has no date, no amount and no line in the account. It surfaces only as a slightly larger balance at the end of a busy month. The fix is to pair the cut with a transfer increase in the same sitting, or to stop calling the cut saving."
  },
  deepDive: "Here is a list of recurring costs I have cut in the last two years and my transfer history over the same period. Tell me how much of the cutting actually reached savings, and write me the pairing rule in a form I would plausibly follow."
},
{
  id: "rate-fixed-cost-ceiling",
  track: "rate", level: "annual",
  title: "Your maximum savings rate is one minus your fixed-cost share, and almost nobody has computed theirs",
  source: "Australian Bureau of Statistics household expenditure collections on the composition of household spending, read as a constraint on the achievable savings rate rather than as a description of it",
  gateIntro: "Somebody on a forum says they save half their income and you have just spent twenty minutes deciding whether to believe them. They are telling the truth, as it turns out: they rent a room, they do not own a car, and they earn roughly what you earn. You have a mortgage on a house chosen for the school catchment and two cars because of where that house is. You are sitting down to set a target for next year and you have never written down what those two things cost you.",
  gatePrompt: "Write the annual instruction that computes the ceiling before it sets the target, and name the month it runs.",
  evidence: "No trial, and the two halves of this entry rest on different things. The measurement half is descriptive national statistics: Australian household expenditure collections consistently show housing as the single largest category of household spending with transport among the next largest, and periodic collection means the composition is well described even where the latest figures are some years old. The published averages pool renters, mortgaged owners and outright owners, whose housing shares are not remotely comparable, so the average describes no actual household. The ceiling half is arithmetic laid on top: a survey measures what households did spend, never what they could have spent, so nothing in it establishes that any particular share is unavoidable for you. Compute your own and ignore the national figure.",
  replication: "craft",
  idea: "The most you can save is your income less the costs that recur without a decision, so your ceiling is set by where you live and how you travel rather than by anything a spending audit would find.",
  why: "Split your outgoings into two groups: things that recur whether or not you decide anything, and things you decide each time. The first group is your fixed cost, and the most you could possibly save is one minus that group as a share of income. It is a genuine ceiling, because reaching it would mean discretionary spending of exactly zero, and nobody operates at their ceiling. But it tells you the size of the room you are standing in, and it is the only number that distinguishes an ambitious target from an impossible one.\n\nIn wealthy countries housing is consistently the largest single line in household spending and transport is among the next largest, and between them they dominate the fixed group. Which means the ceiling is set almost entirely by two choices, where you live and how you get about, each made once every several years and then lived with. National averages will not help you locate your own, because they pool renters, people mid-mortgage and people who own outright, and those three have nothing in common on this measure.\n\nTwo people on identical incomes can have ceilings twenty points apart, and no quantity of discipline moves either of them toward the other. That is the honest reason a rate somebody else achieves may be genuinely unavailable to you. It is also the reason that a rate sitting well below your own ceiling is a choice you are making rather than a constraint you are under. Both are worth knowing and only the computed ceiling tells them apart.\n\nRaising the ceiling is a different sort of act from raising the rate. It happens at a lease end, a refinance, a move or a vehicle replacement, perhaps once every few years, and when it happens it is permanent. That is why it belongs on an annual list rather than a monthly one.",
  failureMode: "You set a target of thirty percent against a ceiling of twenty-six, miss it every month for a year, and conclude you have a discipline problem. You have an arithmetic problem, and fifteen minutes of adding up standing arrangements would have shown it in January. The year goes into the wrong intervention entirely: audits, apps and resolutions, none of which touch either of the two commitments that set the number.",
  worked: "An annual instruction that computes the ceiling before it allows a target:\n\n\"Every July, before setting any savings target, add up twelve months of housing, transport, insurance, utilities, loan payments and everything else that recurs without a decision. Divide by gross income. One minus that is the ceiling, and the target goes underneath it.\"\n\nThen the line that makes it actionable rather than merely deflating:\n\n\"If the ceiling is lower than I want it to be, write down the date of the next lease end, refinance window or vehicle replacement, because those are the only days in the year on which it can move.\"\n\nWhat is deliberately absent is a benchmark to compare the ceiling against. There is no published number worth comparing it to, because the averages pool households whose housing arrangements make them incomparable, and a benchmark you cannot trust is worse than having none.",
  experiment: "Do the fifteen minute version today. Add up one month of costs that recur without a decision, divide by one month of gross income, and subtract from one. That is roughly your ceiling. Write your current rate next to it. The distance between the two is the room you actually have, and it is almost always either much larger or much smaller than people guess, which is the entire reason to compute it rather than estimate it.",
  reflection: "What is your ceiling, and how far below it is the rate you are actually running?",
  recall: {
    q: "Why does computing your fixed-cost share tell you more about your achievable rate than a discretionary spending audit does?",
    a: "Because the maximum rate available to you is one minus the share of income committed to costs that recur without a decision. That share is a hard ceiling and the discretionary category is only the room underneath it. Housing and transport dominate the fixed group and both are set by choices made once every several years, which is not a horizon a monthly audit can reach.\n\nIt also separates two situations that feel identical from inside. A target above the ceiling is arithmetically impossible and no amount of discipline repairs it. A rate well below the ceiling is a decision you are making. Only the computed number tells you which one you are in."
  },
  deepDive: "Here are twelve months of transactions. Split them into costs that recur without a decision and costs I choose each time, compute my ceiling against gross income, and tell me which single commitment would move the ceiling most and when its next decision point falls."
},
{
  id: "rate-fifty-thirty-twenty",
  track: "rate", level: "standing",
  title: "The fifty thirty twenty rule is a communication device with no evidence behind it, and its twenty is somebody else's ceiling",
  source: "Elizabeth Warren and Amelia Warren Tyagi, All Your Worth: The Ultimate Lifetime Money Plan, and the fifty thirty twenty rule as it now circulates independently of the book",
  gateIntro: "You have opened the spreadsheet three times to split your income into fifty, thirty and twenty, and each time you have run into the same argument with yourself. The car is a need because it gets you to work and a want because you chose that car. Childcare fits none of the three in any way you can defend. The private health cover is either, depending on the sentence you use. This is the third attempt, the tabs are still open, and the twenty is still empty.",
  gatePrompt: "Write the single instruction that replaces all three categories, with a percentage in it that you got from your own numbers.",
  evidence: "No trial, no cohort study, no evaluation of any kind. The rule appeared in a popular book as a way of explaining a budget in one sentence and it succeeded completely at that, which is a different achievement from being right. Nobody has tested whether households given the rule end up wealthier than households given nothing, whether the three categories are stable enough to allocate against, or whether twenty percent is adequate for anybody in particular. Two structural problems compound the absence. The boundary between needs and wants is undefined and moves with income. And the fifty percent needs allowance is comfortably breached by housing plus transport plus utilities for a great many mortgaged and renting households, while being slack for a household that owns outright, which makes it one national number applied to a wide distribution.",
  replication: "overclaimed",
  idea: "A rule that allocates income into three named buckets fails at the boundaries between them, and its saving figure is one number applied to households whose ceilings are twenty points apart.",
  why: "The rule earned its popularity honestly. It is memorable, it fits in a sentence, and it gives somebody with no framework at all a place to begin, which is worth something real. The trouble starts the moment anybody tries to use it, because it requires a needs and wants distinction that nobody has defined and that moves with income. The car that gets you to work, the childcare that makes the job possible, the cover that is technically optional: none of these has an answer, and the hours spent manufacturing one are hours not spent installing anything.\n\nThe deeper failure is the third number. A single saving figure applied across a population is applied to households whose fixed-cost ceilings differ by twenty points or more, so it is out of reach for some and lazy for others at the same time. For a household whose housing and transport already take more than half of gross income it announces a failure that arithmetic guaranteed. For a household that owns outright and cycles to work it certifies a success that required nothing. Neither has learned anything.\n\nAnd the shape of the rule is wrong for the mechanism. It is a budget, which means it works by allocating spending in advance and then requiring compliance with the allocation for the rest of the month, which puts saving at the end of a chain of decisions. The finding this whole corpus rests on says to delete the chain: one transfer, dated, at a rate taken from your own ceiling, and no categories whatsoever.",
  failureMode: "Three weekends across two years building allocation spreadsheets, each abandoned inside a month, because the boundary arguments have no answers and the categories drift as soon as anything changes. Roughly eighteen hours, and not one standing instruction at the end of any of them. The twenty percent target was never checked against a ceiling either, so it may never have been reachable in the first place.",
  worked: "The replacement is one instruction with no categories in it at all:\n\n\"Transfer eighteen percent of each pay to the savings account the day after pay lands, and spend the rest without allocating it.\"\n\nThe eighteen comes from your own ceiling computed against your own fixed costs rather than from anybody's rule, and it sits below that ceiling deliberately.\n\nWhat is deliberately absent is every category. No needs figure, no wants figure, no bucket structure, because the boundary between the categories is exactly where the previous three attempts died. Once the saving has left the account, what happens to the remainder does not need governing, and that freedom on the spending side is most of why the instruction survives the month.",
  experiment: "If you have a bucket allocation running, delete the categories today and keep only the figure that was going to savings. Convert it to a share of pay, check it against the ceiling you computed, adjust it once, and set it as a single dated transfer. Then close the spreadsheet for good. If you have never had one, skip the exercise entirely and do the transfer, which was always the only part of it capable of doing anything.",
  reflection: "How many times have you built a category budget, and how long did the longest one survive?",
  recall: {
    q: "The fifty thirty twenty rule is memorable and easy to explain. Why does it still not work?",
    a: "Because it needs a needs and wants boundary that nobody has defined and that shifts with income, so the first hour of using it goes into arguments with no answers, and those arguments are where the attempt usually ends. No trial has ever tested whether households given the rule do better than households given nothing at all.\n\nThe saving figure is the deeper problem. One number applied across households whose fixed-cost ceilings differ by twenty points or more is unreachable for some and slack for others, and tells neither group anything true. It is also structurally a budget, which places saving at the end of a chain of monthly compliance decisions when the entire point is to remove the chain."
  },
  deepDive: "I have tried a category budget three times and abandoned it three times. Here are my income and my fixed costs. Give me the single transfer that replaces the whole thing, and tell me honestly what I lose by having no categories at all."
},
{
  id: "rate-budgeting-apps",
  track: "rate", level: "standing",
  title: "Nobody has shown that a budgeting app raises anybody's savings rate, at a scale of use where somebody should have",
  source: "The efficacy claims made for personal financial management applications, set against the evaluation literature that exists for them",
  gateIntro: "You have had the app fourteen months. The categorisation is good, the charts are legible, and last Sunday went on recoding a batch of transactions the algorithm had filed under the wrong heading. You know your restaurant spending to the dollar for every month since installation. The savings transfer is the same amount it was the week you set the app up, and the app has never once asked you to change it.",
  gatePrompt: "Write the instruction that makes the app cause something, including what happens if two quarters pass and it has not.",
  evidence: "No trial this entry can point to, which at this scale of use is itself the finding. Budgeting and personal financial management applications are used by enormous numbers of people and have been evaluated remarkably little: what exists tends to be short, small, run with the provider, and measured on engagement or self-reported behaviour rather than on a balance twelve months later. This is an absence of evidence rather than evidence of absence, and the honest position is that nobody knows. Two things make the absence suspicious rather than neutral. Tracking and feedback is an information intervention, and information interventions in household finance have a well documented habit of decaying. And the app can only reach a balance through a decision it does not make for you, which puts it on the wrong side of the distinction that opens this corpus.",
  replication: "overclaimed",
  idea: "An app produces measurement, and measurement only reaches a balance through a subsequent decision that nothing in the app makes on your behalf.",
  why: "The app is a measurement instrument and it is frequently a good one. The question is what measurement does on its own, and the answer from the wider literature is not encouraging. Knowing a number is an information intervention, and information interventions in household finance are the category with the smallest and least durable effects on record. The app sits squarely on the side of that line this corpus opens by dismissing. It tells you things. It does not move money.\n\nThere is also a failure mode that measurement tools have and defaults do not, which is that the work they generate feels like the work that matters. Recoding transactions, tuning categories and reviewing a dashboard all have visible output and none of them changes a balance. An hour on a Sunday spent recategorising felt productive and moved nothing, and it competes directly for attention with the eleven minutes that would have moved something.\n\nThe honest position is that the evidence is absent rather than negative. If you are someone for whom seeing the number reliably produces a change in the standing instruction, then the app has earned its place and this entry does not apply to you. That is a testable claim about yourself and testing it takes one line: has the transfer amount changed since you installed it? If it has not, the app is a hobby, and it is a harmless one right up to the point where it is being counted as the intervention.",
  failureMode: "Fourteen months of clean data, forty minutes a fortnight of maintenance, and a transfer amount unchanged since installation. That is somewhere around fifteen hours of work with a measurable output of zero dollars, sitting next to an eleven minute task that was available on any one of those Sundays.",
  worked: "The instruction converts the app from an intervention into a trigger:\n\n\"Once a quarter, open the app for ten minutes, and if the savings transfer has not increased since the last time I looked, increase it now by one percent of pay before closing the app.\"\n\nThen the honest fallback, which has to be written down in advance or it never happens:\n\n\"If two consecutive quarters pass with no change to the transfer, delete the app and keep the transfer.\"\n\nWhat is deliberately absent is any requirement to maintain the data. No recategorising, no reconciling, no monthly review. The app either causes the transfer to move or it does not, and the quality of the categorisation has never been the variable that decided which.",
  experiment: "Check one thing today: the date and amount of your last change to a savings transfer, against the date you installed whatever tracking tool you use. If the transfer has not moved since, the tool has not yet done anything, and you can establish that in under a minute. Then set the quarterly instruction with the increase written into it, so that the next time you open the app something is obliged to happen.",
  reflection: "When did you last change a transfer amount, and how long have you had the app?",
  recall: {
    q: "Budgeting apps are used at enormous scale. Why is that not evidence that they work?",
    a: "Because usage is not an outcome, and remarkably little credible evaluation exists at that scale. What there is tends to be short, small, run with the provider, and measured on engagement or self-report rather than on a balance a year later. The honest verdict is that nobody knows, which is a different thing from knowing the effect is zero.\n\nWhat makes the absence suspicious rather than neutral is the mechanism. An app produces measurement, and measurement only reaches a balance through a decision the app does not make for you, which puts it on the information side of the line this corpus opens with. The maintenance work it generates also feels like the work that matters while changing nothing."
  },
  deepDive: "Here is what my tracking app tells me and here is my transfer history over the same period. Tell me whether the app has ever caused a change in what I save, and if it has not, what single instruction should replace it."
},
{
  id: "rate-rich-save-more",
  track: "rate", level: "judgement",
  title: "Saving rates rise with permanent income, and the reason is fixed costs rather than virtue",
  source: "Karen Dynan, Jonathan Skinner and Stephen Zeldes, Do the Rich Save More? (Journal of Political Economy, 2004)",
  gateIntro: "A senior colleague mentions in passing, without making anything of it, that they put away about a third of what they earn. You are on eleven percent and you make perhaps sixty percent of what they make, and the immediate feeling is that they have something you do not. On the drive home it occurs to you that their mortgage is smaller than yours in dollars and not only as a share, because they bought nine years earlier. You are not sure what to do with that.",
  gatePrompt: "Write the rule that applies to your next income increase, as a share of the increase and a deadline, not as a target rate.",
  evidence: "One paper, and it is careful about a question much harder than it appears. Measuring saving rates against current income builds the answer in, because a high current income usually contains a transitory component and transitory income is mostly saved, so the rich look thrifty by construction. Dynan, Skinner and Zeldes used United States household survey data with instruments for permanent income, including education, consumption and lagged and future earnings, to strip that channel out, and a positive relationship between permanent income and the saving rate survived across several definitions of saving. It is one country, one period, survey data with the measurement error that implies, and instruments for permanent income are always arguable. Treat the direction as the result and not any magnitude.",
  replication: "single",
  idea: "Higher permanent income comes with a higher saving rate because the costs that recur do not scale with income, so the difference is available room rather than superior discipline.",
  why: "The finding is harder to establish than it sounds, which is what makes the paper worth knowing. Compare saving to current income and the wealthy appear thrifty automatically, since a good year is largely a transitory shock and transitory shocks are mostly saved. Instrumenting for permanent income removes that mechanical channel, and the positive relationship persisted, which is what turns it from an artefact into a result.\n\nThe mechanism is the ceiling argument run across people rather than across years. Food, utilities, one set of insurances, one commute and somewhere to live do not scale one for one with income. So as permanent income rises, the group of costs that recur without a decision falls as a share of it, and the ceiling rises. What reads as a difference in character is substantially a difference in the room available, and the arithmetic will produce that difference between two households with identical preferences.\n\nThe uncomfortable implication and the useful one are the same sentence. The uncomfortable half is that a rate somebody else achieves may not be available to you at your income, so comparing yourself to them measures your income more than your behaviour. The useful half is that the same mechanism is not person-specific: your own ceiling rises as your own income rises. The paper is cross-sectional and cannot establish that within-person version, so treat it as the mechanism pointing somewhere rather than as a measured result. But it is where the marginal rule earns its keep, and it is the only part of this finding you can act on.",
  failureMode: "You compare your eleven percent to a colleague's third, decide the difference is discipline, and spend a year working on discipline. Most of the gap was that their fixed costs are a smaller share of a larger income and their loan is nine years older than yours. That year could have gone into the two things that move your own number, which are the share you commit on new income and the date of your next housing or transport decision.",
  worked: "The instruction turns the population pattern into something that happens to you rather than around you:\n\n\"Every time my income rises, commit a share of the increase larger than my current savings rate, and write the new rate next to the old one on the same day.\"\n\nAnd the comparison rule, which is the other half of it:\n\n\"Before comparing my rate to anybody else's, find out their housing cost as a share of their income. If I do not know it, do not make the comparison.\"\n\nWhat is deliberately absent is any target rate borrowed from another household. The finding says rates differ with income for structural reasons, which is precisely why somebody else's rate is not a target. Your ceiling is yours, and the only comparison that carries information is against last year's version of yourself.",
  experiment: "Take the last income increase you received and work out what share of it you actually committed. Then work out what share you would have needed to commit for your overall rate to rise by one point. Most people find the second figure much smaller than expected and find that they committed less than it. Write the required share down as a rule for the next increase, while there is not one on the table.",
  reflection: "What share of your last income increase did you commit, and what would one point on your overall rate have needed?",
  recall: {
    q: "Why is it hard to establish that saving rates rise with permanent income, and what explains the relationship once it is established?",
    a: "Because measuring saving against current income builds the answer in. A high current income usually contains a transitory component, transitory income is mostly saved, so the rich appear thrifty by construction. Dynan, Skinner and Zeldes instrumented for permanent income to remove that channel and the positive relationship survived, which is what makes it a result rather than an artefact.\n\nThe explanation is structural rather than moral. Food, utilities, insurance, a commute and somewhere to live do not scale one for one with income, so as permanent income rises the costs that recur without a decision shrink as a share of it and the ceiling rises. Two households with identical preferences and different incomes will show different rates for that reason alone."
  },
  deepDive: "Here is my income, my housing cost and my rate, and here is what I know about the colleague I keep comparing myself to. Tell me how much of the gap is structural and how much is behaviour I could actually change."
},
{
  id: "rate-adequacy-contested",
  track: "rate", level: "judgement",
  title: "Whether your savings rate is too low is a question about a model, and the two main literatures answer it in opposite directions",
  source: "Scholz, Seshadri and Khitatrakun, Are Americans Saving Optimally for Retirement? (Journal of Political Economy, 2006), set against the large replacement-rate literature reporting widespread undersaving",
  gateIntro: "Two things landed in the same week. Your fund's projection says you are on track for a comfortable retirement. An article on Tuesday said most people your age are catastrophically behind, and it had a chart. Both were computed from real data by people who are not lying, and the gap between them amounts to something like eighteen years of contributions. Your review is in a fortnight and you were going to use one of the two to decide how much of the raise to commit.",
  gatePrompt: "Write the instruction that does not depend on which of the two is right, plus the two questions you will ask of the next projection anybody hands you.",
  evidence: "Two careful literatures reaching opposite conclusions from the same kind of data, where the disagreement is entirely about the model rather than the measurements. Scholz, Seshadri and Khitatrakun solved a lifecycle model with uncertain income, uncertain lifespan and uncertain medical expenses separately for each household in a large United States survey of older Americans, producing a household-specific optimal wealth target, and found the large majority holding wealth at or above their own target with most shortfalls small. Against that sits a substantial literature using replacement-rate benchmarks and simpler targets that reports widespread and severe undersaving. What separates them is what the model assumes about how far consumption falls when work stops, whether home equity counts, how much family and public provision substitutes for private saving, and what discount rate a household is entitled to. One country and one cohort, so no level transfers; what transfers is that the question has no answer independent of the model.",
  replication: "contested",
  idea: "Adequacy is a model output rather than a measurement, and the assumptions inside the model settle the answer before any data is consulted.",
  why: "Scholz, Seshadri and Khitatrakun did something unusually demanding. Rather than compare households against a rule of thumb, they solved a lifecycle model for each household separately, with its own earnings history, family structure, mortality risk and medical expense risk, generating an optimal wealth target specific to that household. Judged against those targets the great majority of their sample was saving enough, and most of the shortfalls that did exist were small. That sits directly against a large body of work using replacement-rate benchmarks which reports the opposite in strong terms.\n\nThe two are not arguing about the data. They are arguing about what retirement costs, and specifically about whether consumption falls when work stops, whether the house counts, whether family and public provision substitute for private saving, and what rate a household is entitled to discount its own future at. Move any one of those and the verdict on an identical household flips. So an adequacy figure handed to you without its assumptions is not information. It is somebody's model with the assumptions taken out.\n\nThe practical response is not to pick a side. It is to notice that the disagreement is about the target rather than about the rate. Whatever the target turns out to be, a higher rate reaches it sooner and a rate that is actually running reaches it at all, and both literatures agree on that completely. The decision available to you therefore does not require the question to be settled, which is the only good news in this entry: you can act while the field argues, as long as you act on the term nobody is disputing.\n\nWhen somebody does hand you a projection, two questions tell you what it is worth. What spending does it assume, and is the return nominal or real. A projection that will not answer either is a marketing document with a chart on it.",
  failureMode: "You take a projection at face value, conclude you are on track, and hold your rate flat for four years. The projection assumed your spending would fall by a quarter at retirement and used a return it never labelled as nominal or real. Neither assumption was exactly hidden from you. Neither was in the sentence you actually read, and four years of a rate you could have raised does not come back.",
  worked: "The instruction is a filter on projections and a floor on your own behaviour:\n\n\"Whenever I am given a retirement projection, ask two questions before believing any of it: what spending does it assume, and is the return nominal or real. If either answer is unavailable, discard the projection.\"\n\nThen the floor, which does not depend on the answer to anything:\n\n\"Regardless of what any projection says, the standing transfer never goes down, and it rises with every income increase.\"\n\nWhat is deliberately absent is a target balance. The field cannot agree on one, and adopting a stranger's number without their assumptions is how a plan ends up resting on somebody else's view of how much your spending will fall in retirement.",
  experiment: "Find the most recent projection anybody has given you, from a fund, a calculator or an adviser, and try to locate its two key assumptions: the spending it assumes in retirement, and whether its return is nominal or real. If you can find both inside five minutes, the projection is honest and worth keeping. If you cannot, that is your result, and the instruction that survives it is the transfer.",
  reflection: "Could you find the assumptions inside your last projection, and how long did it take you?",
  recall: {
    q: "Two careful literatures disagree about whether households save enough. What is the disagreement actually about, and how should you act while it stands?",
    a: "About the model rather than the data. Scholz, Seshadri and Khitatrakun solved a lifecycle model household by household, each with its own earnings history, family structure, mortality risk and medical expense risk, and found the large majority saving at or above their own optimal target. A large replacement-rate literature reports the opposite. What separates them is whether consumption falls when work stops, whether the house counts, whether family and public provision substitutes for private saving, and what discount rate a household is entitled to.\n\nSo an adequacy figure handed over without its assumptions is a model with the assumptions removed. The response is to notice that the argument is about the target and not about the rate. Whatever the target is, a higher rate reaches it sooner and a running rate reaches it at all, and both sides accept that, so act on the term nobody is disputing."
  },
  deepDive: "Here is my fund's projection and here is my actual position. Pull out what the projection assumes about my retirement spending and its return, tell me what the answer becomes under two less generous sets of assumptions, and then tell me the one thing worth doing under all three."
}
);
