/* Track: Building the thing that survives you. Ordered foundational first.
 *
 * Every other track supplies instructions. This one is the meta-system: how an
 * instruction gets installed, how you find out it stopped, when to retire it,
 * and how the arrangement survives a job change, a bank change, a partner, or
 * your death.
 *
 * Mostly craft, and it says so. There is no randomised trial on how to name a
 * bank account, and an honest "No trial." beats a citation that would not
 * survive being looked up. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "install-one-per-session",
  track: "install", level: "standing",
  title: "A session that installs three things installs none, because the third one is where you stop and none of them get finished",
  source: "Operational practice in change management and deployment: one change at a time, verified before the next",
  gateIntro: "You have a free Saturday morning and a list of six things: open a second savings account, set up a transfer, consolidate two super accounts, review the insurance, cancel a subscription, and increase the salary sacrifice. It is nine o'clock and you feel capable of all of it. By eleven you will have three tabs open, two half-finished forms, and a verification email you cannot find.",
  gatePrompt: "Pick exactly one of the six and write it as an instruction. Then write what you will do with the other five.",
  evidence: "No trial. This is the deployment discipline used wherever a change has to be verified before the next one lands: ship one thing, confirm it took effect, then ship the next. The rationale is diagnostic rather than motivational. When three changes go out together and something is wrong a fortnight later, there is no way to tell which one did it without unpicking all three, and the same is true of a Saturday morning that touched six financial arrangements at once.",
  replication: "craft",
  idea: "Install one thing, verify it actually happened, and stop, because the value is in the verification and the verification is what gets dropped when the list is long.",
  why: "The failure is not that ambition runs out. It is that each of these acts has a tail. A transfer has to actually execute once before you know the account numbers were right. A consolidation has an insurance policy attached to the account you are closing, which you will only discover when it lapses. A salary sacrifice change has to appear on a payslip. Every one of them is unfinished at the moment the form is submitted, and the tail is where the errors live.\n\nSix submissions on one morning generates six tails, all landing over the following fortnight, mixed together and unlabelled. You will not track them. What actually happens is that the ones which worked are invisible and the one which silently did not is discovered a year later.\n\nOne per session inverts that. The single tail is short enough to hold in your head, and you can write down the date you expect confirmation. That is the whole discipline, and the reason it feels unsatisfying is exactly why it works: the constraint is on your appetite, not on your capability.",
  failureMode: "Nine months after a productive Saturday you find that the consolidation went through but took the income protection cover with it, the second transfer was set against a closed account and has been silently failing, and the salary sacrifice never reached payroll. Every one of those was recoverable in the week it happened. None was noticed, because six things landed at once and nothing was verified.",
  worked: "One instruction, and then the disposal of the rest:\n\n\"Today I set up the transfer, and nothing else. I will check on the fifteenth that it executed, and only then open the next item.\"\n\nAnd the other five, which need a home or they will be back next Saturday:\n\n\"The remaining five go into a single note titled 'next installs', in priority order, and I take exactly one per fortnight.\"\n\nThe list is not procrastination. It is what stops the appetite you have at nine o'clock from converting into six unverified changes by eleven, and it means the next session starts with a decision already made.",
  experiment: "Write your own list of pending financial changes, however long it is, and then pick one. Do that one today and set a reminder for the date you expect to see it confirmed, whether that is a payslip, a statement line or an email. Do not touch the others. The discipline being trained is stopping, not starting.",
  reflection: "Which one did you do, and what date are you expecting confirmation?",
  forecast: { q: "Will I have verified today's install actually took effect, from a payslip or statement rather than from memory, within thirty days?" },
  recall: {
    q: "Why is one financial change per session a diagnostic discipline rather than a motivational one?",
    a: "Because every change has a tail. A transfer is not finished when the form is submitted, only when it has executed once; a consolidation may take an attached insurance policy with it; a salary sacrifice has to appear on a payslip. The errors live in the tail, not in the submission.\n\nSix changes at once produce six tails landing over a fortnight, mixed and unlabelled, so the ones that worked are invisible and the one that silently failed is found a year later. A single tail is short enough to hold and to date, which is why the constraint is on appetite rather than capability."
  },
  deepDive: "Here is my list of pending financial changes. Put them in an order and tell me what verification each one needs before I move to the next."
},
{
  id: "install-look-less-often",
  track: "install", level: "standing",
  title: "People shown their returns less frequently take more risk and end up better off, and the effect is causal",
  source: "Shlomo Benartzi and Richard Thaler, Myopic Loss Aversion and the Equity Premium Puzzle (Quarterly Journal of Economics, 1995), and Thaler, Tversky, Kahneman and Schwartz, The Effect of Myopia and Loss Aversion on Risk Taking (Quarterly Journal of Economics, 1997)",
  gateIntro: "The app is on your phone and you open it most days, sometimes twice. You have never traded on what you saw, so you regard the habit as harmless curiosity rather than a problem. Yesterday it was down and you thought about it in the shower this morning. You are about to open it again while the kettle boils.",
  gatePrompt: "Write the instruction that changes how often you can see the number. Be specific about the mechanism, not the intention.",
  evidence: "An experimental literature manipulating feedback frequency while holding the underlying investment identical. Participants shown outcomes aggregated over longer periods allocated more to the riskier and higher-returning asset than those shown frequent individual outcomes, and consequently ended up with more. The mechanism proposed is that loss aversion combines with frequent evaluation: the more often you look, the more often you see a loss, because short intervals contain more losing periods than long ones do even in a rising series. These are laboratory experiments with student and professional subjects and modest stakes, not field measurements of real portfolios, so the mechanism is well identified and the magnitude in real life is not.",
  replication: "replicated",
  cheat: "Cut how often you can see the balance: frequent evaluation makes losses more visible than gains and reliably pushes people into holding less risk than suits them.",
  idea: "The frequency at which you look is itself a portfolio decision, because it determines how many losses you experience without changing how many occur.",
  why: "Consider a series that rises over time with ordinary volatility. Sampled yearly, most observations are gains. Sampled daily, a little under half are losses. The underlying process is identical; only the sampling changed. Now add loss aversion, where a loss of a given size registers roughly twice as hard as a gain of the same size, and the daily viewer is absorbing a continuous stream of unpleasantness that the annual viewer never experiences.\n\nThat accumulated unpleasantness has to go somewhere, and where it goes is risk tolerance. The daily viewer is not irrational; they are correctly responding to a subjective experience that their own sampling created. They then hold a more conservative allocation than their horizon warrants, and pay for it over decades.\n\nThe useful part is that looking frequency is one of the few genuinely free variables here. You cannot choose the volatility, the return or your own loss aversion. You can choose the sampling interval, and it is a setting on a phone.",
  failureMode: "You check daily for a decade, never trade, and consider the habit costless. Meanwhile the allocation you chose in year two was set on a Tuesday after a bad week, and it is two notches more conservative than your horizon justifies. Nothing you did looks like a mistake at any point, and the cost only appears in a counterfactual you never see.",
  worked: "The instruction has to be mechanical, because intention is exactly what fails here:\n\n\"Delete the investment app from my phone. The balance is checkable from a desktop browser, and I will look on the first of each quarter.\"\n\nAnd the clause for the situation that will actually arise:\n\n\"If I need to check for a real reason, such as verifying a contribution landed, I check that specific thing and do not open the performance view.\"\n\nDeletion rather than resolve is the whole design. A commitment to look less that relies on remembering not to look is not a commitment, and the app is engineered by people whose job is to defeat it.",
  experiment: "Find out how many times you opened your investment or banking app in the last week. Most phones report this under screen time by application. Then remove the app from the phone entirely and note where you would go instead. The count is the measurement and the removal is the install, and the count is worth having first because most people are wrong about it by a factor of several.",
  reflection: "How many times had you actually opened it, and what did you replace the habit with?",
  forecast: { q: "Ninety days from now, will I be checking my balance no more than once a month?" },
  recall: {
    q: "Why does looking at your portfolio more often lead to holding less risk, even if you never trade?",
    a: "Because the sampling interval determines how many losses you experience without changing how many occur. A rising series sampled yearly shows mostly gains; sampled daily it shows losses just under half the time. Combined with loss aversion, where a loss registers roughly twice as hard as an equivalent gain, frequent viewers absorb a continuous stream of unpleasantness that infrequent viewers never encounter.\n\nThat experience feeds back into allocation, so the frequent viewer chooses a more conservative portfolio than their horizon warrants and pays for it over decades. Looking frequency is one of the few free variables available, since you cannot choose volatility, returns or your own loss aversion."
  },
  deepDive: "Help me set a looking schedule for my portfolio and work out what I actually need to check versus what I merely want to see."
},
{
  id: "install-sunset-every-instruction",
  track: "install", level: "annual",
  title: "An instruction with no end date becomes sediment, and sediment is indistinguishable from a decision",
  source: "Operational practice in configuration and infrastructure management: every rule carries an owner and a review date, or it accumulates",
  gateIntro: "There is a fifty dollar transfer running to an account you opened for a holiday you took in 2022. It has moved about six thousand dollars since, which is not lost, but it is also not anywhere you chose. You have seen the line on your statement perhaps thirty times and have never once acted on it, because each time it registered as something you had already decided.",
  gatePrompt: "Write the rule that would have caught this in 2023, as an instruction attached to the transfer rather than to your attention.",
  evidence: "No trial. This is standard practice wherever configuration accumulates faster than anybody reads it: a rule is created with an owner and an expiry, and an unreviewed rule is treated as suspect rather than as settled. The rationale is that a system's behaviour drifts from its intent through accretion rather than through error, and that nothing in the system distinguishes a rule someone still wants from a rule nobody has looked at in three years.",
  replication: "craft",
  idea: "Attach a review date at the moment you create an instruction, because afterwards it will look identical to a decision you are still making.",
  why: "The reason this particular error is so persistent is that the evidence for it is invisible by construction. A transfer that is wrong looks exactly like a transfer that is right: a line on a statement, running as configured, doing what it was told. There is no signal. The only thing that distinguishes the good one is a fact about your current intentions, and your statement does not have access to that.\n\nSo the drift is silent and cumulative. Each individual instruction was correct when it was created, nothing broke, and the arrangement as a whole slowly stops matching what you want, one obsolete rule at a time. This is precisely the mechanism that makes automation valuable turned against you: it keeps executing regardless of whether anyone still means it.\n\nThe fix has to be attached to the instruction rather than to you, because you are the component that is not paying attention. A date written at creation time is a note from the version of you that knew why, addressed to the version that will not remember.",
  failureMode: "Four automated arrangements, two of which serve goals that no longer exist, one that routes money to an account paying nothing, and one that is genuinely load-bearing. On the statement they are four identical lines. You have looked at them monthly for years and the information needed to tell them apart was never on the page.",
  worked: "The rule is attached to the instruction, not to your memory:\n\n\"Every automated transfer gets a line in one note: what it is for, the date I set it, and the date I will next ask whether it still applies.\"\n\nAnd the default that makes the review cheap enough to actually perform:\n\n\"Anything whose stated purpose I can no longer name in one sentence gets cancelled at review, not investigated.\"\n\nThat default is doing the real work. A review where every item requires a decision is a review you abandon halfway. A review where the absence of a remembered purpose is itself the answer takes twenty minutes.",
  experiment: "List every recurring transfer, direct debit and automatic contribution currently running against your accounts. Next to each, write its purpose in one sentence and the date you believe you set it up. Anything where you cannot do both is a candidate. You do not have to cancel anything today, but write the list, because the list is the artefact that does not currently exist.",
  reflection: "How many running instructions could you not state a current purpose for?",
  forecast: { q: "Will I have cancelled or consciously renewed every instruction on my list within sixty days?" },
  recall: {
    q: "Why does an obsolete automated transfer stay in place for years despite being visible on every statement?",
    a: "Because it is indistinguishable from a correct one. A wrong transfer and a right transfer both appear as a line executing as configured, and nothing in the record encodes whether you still want it. The only distinguishing fact is your current intent, which the statement has no access to.\n\nSo the arrangement drifts by accretion rather than by failure, one correct-at-the-time rule at a time, and the property that makes automation valuable works against you: it keeps executing whether or not anyone still means it. The remedy has to be attached to the instruction at creation, since you are the component not paying attention."
  },
  deepDive: "Here is every recurring transfer I have. Help me work out which ones still serve a purpose I can name and which are sediment."
},
{
  id: "install-detect-the-silence",
  track: "install", level: "annual",
  title: "You will find out an instruction stopped by accident, years late, unless something checks for its absence",
  source: "Monitoring practice: alerting on the absence of an expected event, rather than only on the presence of an error",
  gateIntro: "Your employer changed payroll providers in March. Your salary has arrived correctly every fortnight since, the amount is right, and nothing has looked wrong. You have not checked whether the salary sacrifice arrangement came across with the migration, and there is no reason you would have, because the thing that would tell you is a number that is quietly not there.",
  gatePrompt: "Write the check that would catch a contribution that stopped arriving, and say when it runs.",
  evidence: "No trial. This is the standard monitoring distinction between an error, which announces itself, and a silent stop, which does not, and the corresponding practice of alerting on the absence of an expected event within a window. The rationale carries over directly: a failed transfer usually generates a notification, whereas an arrangement that was never migrated, was cancelled by a system change, or lapsed on a card expiry produces no event at all, and no amount of watching for errors will surface it.",
  replication: "craft",
  idea: "Errors announce themselves and absences do not, so build a check that looks for the thing that should have happened rather than waiting for something to go wrong.",
  why: "Consider the two ways an automated contribution can stop. It can fail, in which case a bank or a payroll system generates a message, and you find out within days. Or it can simply cease to be configured, because a provider changed, a card expired, an account was consolidated, or a form did not carry across, and in that case there is no event at all. Nothing failed. The instruction is not there to fail.\n\nEvery instinct you have is calibrated for the first case. You watch for problems, and no problems appear, and you conclude that things are working. The second case is invisible to that entire strategy, and it is also the more common one, because the moments that break arrangements are administrative transitions rather than technical faults.\n\nWhat detects it is an expectation with a deadline: by this date, this number should have increased by at least that much. That reframes the check from watching for badness to confirming an expected presence, and it is the only formulation that catches a silence.",
  failureMode: "Eighteen months of salary sacrifice that stopped at the payroll migration and was never reinstated. Nothing alerted, because nothing failed. You find out at tax time when the contribution total is a third of what you expected, and the concessional cap you were carefully managing was never approached.",
  worked: "The check is a presence test with a date on it:\n\n\"On the second payday of each quarter, confirm that the employer contribution and the salary sacrifice both appear on the payslip, at the expected amounts.\"\n\nAnd the annual version that catches everything the quarterly one misses:\n\n\"In the week after 1 July, check the ATO portal for the full four quarters of contributions, because that record is complete and a missing quarter is visible rather than merely late.\"\n\nThe payslip check is deliberately on a payday rather than on a date. Tying a check to an event that already happens is what makes it survive; a date in a calendar competes with everything else in the calendar.",
  experiment: "Look at your most recent payslip and confirm that every deduction and contribution you believe is configured actually appears on it, with the amount you expect. If any is missing or wrong, you have just found something that has probably been wrong for months. Then set the quarterly check, attached to a payday rather than to a date.",
  reflection: "Did everything you expected actually appear, and how long would it have taken you to notice otherwise?",
  forecast: { q: "Over the next two quarters, will every expected contribution appear on the payslip at the expected amount without my intervention?" },
  recall: {
    q: "Why does watching for errors fail to detect a stopped contribution?",
    a: "Because there are two failure modes and only one of them generates an event. A transfer that fails produces a notification from the bank or payroll system and is found within days. An arrangement that ceases to be configured, through a provider change, a card expiry, a consolidation or a form that did not migrate, produces no event at all, because there is nothing left to fail.\n\nWatching for problems therefore returns silence and reads as health. What catches the second case is an expectation with a deadline - by this date this number should have risen by at least this much - which tests for presence rather than for badness, and administrative transitions are where arrangements actually break."
  },
  deepDive: "Here are the automated contributions and transfers I believe are running. Design the smallest set of checks that would catch any of them stopping silently."
},
{
  id: "install-waiting-period-before-trades",
  track: "install", level: "standing",
  title: "The households that traded most earned the least, and the gap was not explained by which securities they picked",
  source: "Brad Barber and Terrance Odean, Trading Is Hazardous to Your Wealth: The Common Stock Investment Performance of Individual Investors (Journal of Finance, 2000)",
  gateIntro: "A position you hold is down eleven percent on news you have now read three summaries of, and you have a reasonable-sounding argument for why the thesis is broken. The market closes in forty minutes. You have had this exact feeling before and cannot immediately recall what happened the last two times, and there is no record anywhere of what you decided or why.",
  gatePrompt: "Write the rule that would sit between you and the sell button. Include a duration and what has to exist before you may act.",
  evidence: "Trading records for tens of thousands of households at a large United States discount broker over the 1990s, sorted by portfolio turnover. The most active traders substantially underperformed both the least active and the market, and the shortfall was driven overwhelmingly by transaction costs rather than by poor security selection: gross returns across turnover groups were far closer than net returns. Observational rather than randomised, one broker, one country, one period, and a self-directed brokerage population that is not representative of investors generally. The direction has since been found repeatedly in other datasets.",
  replication: "replicated",
  cheat: "Put a mandatory waiting period between deciding to trade and trading: the most active households underperformed mainly through costs, not bad picks.",
  idea: "The cost of trading is charged on the activity rather than on being wrong, so a rule that reduces the number of trades is worth more than a rule that improves them.",
  why: "The finding is more useful than the usual summary of it. If active traders had underperformed because they picked badly, the remedy would be better analysis, which is expensive and which almost nobody can actually supply. But the gross returns were much closer than the net returns, meaning their picks were roughly as good as anyone's. What separated them was the toll charged per transaction, paid whether the trade was right or wrong.\n\nThat changes the shape of the fix entirely. You do not need to become a better judge of securities. You need to trade less, and trading less is a mechanical problem with a mechanical solution.\n\nThe reason a waiting period specifically is that the impulse to trade has a short half-life and the argument for it does not survive being written down. Forty minutes before the close, with a plausible story and a red number, the trade feels obligatory. The same trade, reconsidered on Thursday against a note you wrote on Monday, usually does not, and the ones that still look right after that are the ones worth making.",
  failureMode: "Nine discretionary trades in a year, each individually defensible, each with a spread and a tax event attached. The portfolio you would have held by doing nothing is ahead, and no single decision in the sequence was obviously the mistake. The mistake was the count.",
  worked: "The rule needs a duration and an artefact, or it is just an intention:\n\n\"Before any discretionary trade, I write the reason in a note with the date, and I may not execute for seventy-two hours. If the reason still holds on reading it back, I trade.\"\n\nAnd the clause that makes the rule teach you something rather than merely slow you down:\n\n\"The note stays whether or not I trade, and I read the last year of notes each July.\"\n\nThat log is the part with lasting value. After a year you have a record of what your urgent convictions were and what happened next, which is the only calibration data on your own judgement that will ever exist.",
  experiment: "Set up the note now, before you need it, because a rule invented during the forty minutes before a close is not a rule. One file, one line per entry: date, what I want to do, why, and a blank column for what I decided after the waiting period. Then write in it the next time you feel the urge, even if you go on to trade.",
  reflection: "What is your rule's waiting period, and where does the note live?",
  forecast: { q: "Over the next ninety days, will every discretionary trade I make have a dated note written at least seventy-two hours beforehand?" },
  recall: {
    q: "Active traders underperformed. Why does it matter that their gross returns were close to everyone else's?",
    a: "Because it locates the problem in cost rather than in skill. If they had underperformed on security selection, the remedy would be better analysis, which is expensive and which almost nobody can supply. Gross returns being close while net returns diverged means the picks were roughly as good as anyone's and the toll was charged per transaction, whether the trade was right or wrong.\n\nSo the fix is mechanical rather than analytical: reduce the number of trades. A mandatory waiting period works because the impulse has a short half-life and the argument for it rarely survives being written down and read back."
  },
  deepDive: "Design a pre-trade waiting rule for me, including what I have to write down and what would count as a legitimate exception."
},
{
  id: "install-anchor-the-annual-review",
  track: "install", level: "annual",
  title: "A review scheduled for when you feel like it is a review that happens in the years nothing needs reviewing",
  source: "Operational practice: periodic review tied to an external calendar event rather than to discretion",
  gateIntro: "You have intended to do a proper annual sort-out for three years. In the first year you were between jobs and it felt like the wrong moment. In the second you did about half of it in November. This year you have thought about it twice, both times while doing something else, and it is now September.",
  gatePrompt: "Write the review as an instruction with a fixed external date and a fixed list. No more than five items on the list.",
  evidence: "No trial. This is the ordinary practice of tying a recurring task to an external event rather than to intention, on the reasoning that a discretionary schedule is systematically biased: the periods when you feel able to review are the periods when little has changed, and the periods when a review would find something are the periods when you are too busy to run one. In Australia the natural anchor is the 1 July financial year boundary, which is also when contribution records complete and many rates and thresholds change.",
  replication: "craft",
  idea: "Pin the review to a date that arrives whether or not you are ready, because discretion selects for the years when there is nothing to find.",
  why: "The selection problem is the whole argument. Consider what makes a year feel like a bad time to review your finances: a job change, a house move, a new child, a period of overwork. Now consider which years most need a review. They are the same years. A discretionary schedule therefore inverts itself, running most reliably in the quiet years when the answer is that nothing has changed.\n\nAn external anchor removes the judgement. The date arrives, and the arrival is not conditional on your assessment of whether it is warranted, which is the assessment that was systematically wrong.\n\nThe second design choice is the fixed list. A review with an open scope expands to fill the afternoon and then does not finish, so the next one carries a memory of being unbounded and is easier to postpone. Five items, written in advance, means the review has an end, and a task with a visible end gets started.",
  failureMode: "Three years of intending, one half-completed session, and a set of arrangements that were last deliberately chosen when your income was forty percent lower and you had no dependants. Nothing broke. The arrangements are simply answers to a question nobody has asked again.",
  worked: "Fixed date, fixed list, and the list is short on purpose:\n\n\"In the first full week of July, every year: check the four quarters of super contributions arrived, confirm one super account only, shop the home and car insurance, ask the lender for a rate review, and recompute my savings rate from records.\"\n\nAnd the clause that protects the list from itself:\n\n\"Anything that occurs to me during the review that is not on the list goes into next install, not into today.\"\n\nWithout that clause the review discovers three new problems, tries to solve them, runs out of afternoon, and finishes none of the five it came for. The capture rule is what lets you notice something without derailing.",
  experiment: "Put the calendar entry in now, dated the first full week of July, recurring annually, with the five items written into the body of the entry rather than in a document you would have to find. That last detail matters more than it sounds: a review whose checklist lives somewhere else starts with a search, and the search is where it stops.",
  reflection: "What five items are on your list, and is the entry in the calendar with the list inside it?",
  recall: {
    q: "Why does a discretionary review schedule fail systematically rather than randomly?",
    a: "Because the years that feel like a bad time to review are the same years that most need one. A job change, a move, a new child or a period of overwork all make a review feel impossible and all change the answers, so discretion selects for the quiet years when nothing has changed and the review confirms it.\n\nAn external anchor removes that judgement, since the date arrives whether or not you assess it as warranted. A fixed short list is the second half: an open-scoped review expands, does not finish, and makes the next one easier to postpone."
  },
  deepDive: "Help me write the five items for my annual financial review, given my situation, and tell me what I am likely to want to add that should be excluded."
},
{
  id: "install-write-it-before-you-need-it",
  track: "install", level: "standing",
  title: "The plan exists to be read on the worst day, not to be correct on the day you wrote it",
  source: "The investment policy statement as practised in institutional investing, and the general practice of committing a decision rule to writing in advance of the conditions it governs",
  gateIntro: "Markets are down about a quarter and have been for six weeks. Two people you respect have said in the same fortnight that this time the structure really is different, and you find that you cannot construct a counterargument, only a feeling that you have heard it before. Your allocation was chosen four years ago on reasoning you can no longer reconstruct.",
  gatePrompt: "Write the paragraph you wish existed right now, addressed to yourself, and date it today.",
  evidence: "No trial on personal use. Institutional investors maintain a written policy statement setting allocation, ranges and the conditions for changing them, and the stated purpose is governance: a committee that has written its rules down in calm conditions is harder to talk out of them in bad ones. Whether this improves outcomes for an individual has not been tested that I am aware of, and the mechanism it relies on - that a written prior commitment resists in-the-moment reasoning - is supported by the commitment device literature in this corpus rather than by anything specific to investment policy documents.",
  replication: "craft",
  idea: "Write the reasoning down while nothing is happening, because the function of the document is to be more persuasive than you will be on a bad day.",
  why: "The asymmetry is in the quality of thinking available at the two moments. When you set an allocation in a calm week you have time, no adrenaline, and no story competing for your attention. When you reconsider it during a fall you have a vivid narrative, social confirmation from people you respect, and a strong incentive to make the discomfort stop. The second state feels like clarity and is not.\n\nA written statement does not resolve that by being smarter. It resolves it by being from the first state and available in the second. You are not required to obey it. You are required to read it and to write down why it was wrong, which is a much higher bar than the one you would otherwise clear, because the argument for selling during a fall is almost never one you would put in writing next to your own prior reasoning.\n\nThe document should therefore be short and honest rather than comprehensive. Its job is not to anticipate the specific crisis. Its job is to make the abandonment expensive enough to be deliberate.",
  failureMode: "You sell into the fall, feel relief, and never re-enter, because there is no point at which re-entering feels safer than staying out. The decision to sell took ninety minutes and the decision not to re-enter takes four years and is never actually made. Nothing you could read afterwards undoes it, which is why the document has to exist beforehand.",
  worked: "One page, and the operative section is the last one:\n\n\"My allocation is X, chosen because my horizon is Y years and I have Z months of expenses outside it. I expect falls of a third to happen several times over that horizon and I do not intend to act on them.\"\n\n\"I will change this allocation only if my horizon or my income changes materially. If I want to change it for any other reason, I must first write here, dated, what I now believe and why the reasoning above is wrong.\"\n\nThat final requirement is the entire mechanism. It does not forbid anything. It just makes you argue with yourself in writing, in a document that will still be there next year.",
  experiment: "Write the page today, while nothing is falling. Four sentences is enough: what you hold, why, what you expect to go wrong, and what would legitimately change your mind. Put it where you would find it in a bad week, which for most people means the same note application as everything else rather than a file you would have to go looking for.",
  reflection: "What did you write, and where does it live?",
  forecast: { q: "If markets fall more than twenty percent in the next year, will I read this document before making any change?" },
  recall: {
    q: "What is the actual function of a written investment policy, given that it does not bind you to anything?",
    a: "To make abandonment deliberate rather than easy. The reasoning available in a calm week and during a fall differ in quality: the second comes with a vivid narrative, social confirmation and an incentive to end discomfort, and it feels like clarity. The document is not smarter, it is simply from the first state and available in the second.\n\nIts operative clause is the requirement to write down, dated, why the prior reasoning was wrong before changing anything. That bar is higher than the one an in-the-moment argument clears, because the case for selling during a fall is rarely one you would put in writing beside your own earlier reasoning."
  },
  deepDive: "Help me write a one-page policy for my own portfolio, and then attack it: tell me which sentence I will most want to ignore in a bad month."
},
{
  id: "install-job-change-breaks-everything",
  track: "install", level: "standing",
  title: "Changing jobs silently detaches every arrangement that was attached to your employer",
  source: "Operational practice: treating a systems migration as a checklist event rather than as a continuation",
  gateIntro: "You start somewhere new on the third. There is an onboarding portal, a form about bank details, a super question you answer quickly because there are eleven other forms, and a first payslip that looks approximately right. Six weeks in, everything feels settled. Nobody at either the old place or the new one has any reason to think about what you had configured at the last one.",
  gatePrompt: "Write the checklist you would run in week one of a new job. Four items, each one something that was attached to the old employer.",
  evidence: "No trial. This is the ordinary migration discipline of enumerating what depends on a system before it is replaced, applied to the fact that a substantial part of most people's financial automation is hosted by an employer rather than by them: salary sacrifice, the contribution rate above the legislated minimum, insurance held inside a workplace default arrangement, share plans, and the pay cycle that every personally-scheduled transfer was dated against. None of those travel by default, and the mechanism by which each stops is administrative rather than technical.",
  replication: "craft",
  idea: "Anything configured on the employer's side ceases to exist when the employer does, and the new payslip looking correct is not evidence that it survived.",
  why: "The trap is that the salary arrives. Your most visible financial signal continues working perfectly, and it is the one thing that was always going to be reconfigured because payroll cannot pay you without it. Everything less visible had no such forcing function.\n\nWork through what was actually attached over there. A salary sacrifice arrangement lived in the old payroll system. Any contribution rate above the statutory minimum was a setting in that plan. Insurance cover inside the workplace default was tied to that arrangement and may lapse rather than transfer. And your own transfers were dated against the old pay cycle, which the new employer has no reason to match.\n\nEach of those fails silently, and they fail at the one moment when you are least likely to notice, because a new job absorbs all available attention for about two months. The checklist has to exist beforehand for exactly that reason: week one is when you have the least capacity and the most exposure.",
  failureMode: "Fourteen months at the new place before you notice the salary sacrifice never restarted, the contribution reverted to the legislated minimum, and the transfer you set for the twenty-eighth now lands four days before pay rather than one day after, having failed twice. All four were configured correctly at the old employer and none of them was anybody's job to move.",
  worked: "Four items, run in week one, while the onboarding forms are still open:\n\n\"Re-establish the salary sacrifice. Set the contribution rate above the minimum. Check what insurance I now hold and what I lost. Re-date every personal transfer against the new pay cycle.\"\n\nAnd the item that makes the list survive to the next job:\n\n\"Keep this list in the same note as my instructions, so the next migration starts from a checklist rather than from memory.\"\n\nThat last one is what turns a one-off recovery into an install. You will change jobs again, and the version of you doing it will have forgotten all of this.",
  experiment: "If you have changed jobs in the last three years, run the four checks now against your current arrangements rather than assuming they carried. If you have not, write the list anyway and put it with your other instructions, because the moment you need it is the moment you will have no capacity to construct it.",
  reflection: "Which of the four turned out not to have survived your last change, and how long had it been?",
  forecast: { q: "If I change employer in the next two years, will I have run all four checks within the first fortnight?" },
  recall: {
    q: "Why is a correct-looking first payslip at a new job weak evidence that your arrangements survived?",
    a: "Because salary is the one thing that had to be reconfigured, since payroll cannot pay you without it. Its correctness is guaranteed by a forcing function that nothing else has.\n\nWhat was attached to the old employer and does not travel includes the salary sacrifice, any contribution rate above the statutory minimum, insurance held inside the workplace default arrangement, and your own transfers dated against the old pay cycle. Each fails administratively rather than technically, so none generates an error, and they fail during the two months when a new job consumes all available attention."
  },
  deepDive: "I am starting a new job. Build me the week-one checklist of everything that was attached to my old employer and will not travel."
},
{
  id: "install-someone-else-can-reach-it",
  track: "install", level: "annual",
  title: "An automated system nobody else can reach becomes a problem for the people you leave it to",
  source: "Practice in operational handover and estate administration, and the structural fact that superannuation in Australia is not distributed by your will",
  gateIntro: "Everything is automated, consolidated and tidy. Two accounts, one fund, four instructions, all documented in a note on your phone behind a biometric lock. Your partner knows roughly what exists and could not name the institutions. You have been quietly pleased with how clean the arrangement is for about two years.",
  gatePrompt: "Write the instruction that makes this reachable by one other person, without writing any credential down in it.",
  evidence: "No trial, and this is partly legal structure rather than practice. Superannuation is generally not distributed under your will; it is paid by the fund trustee, and where a valid nomination exists it directs that payment. Nominations may be binding or non-binding depending on the fund and the form used, and many funds require a binding nomination to be renewed periodically rather than treating it as permanent. The specifics vary by fund and change, so treat this as a prompt to check your own fund's rules rather than as a statement of them. The handover half is ordinary operational practice: a system with one operator has one point of failure.",
  replication: "craft",
  idea: "Automation concentrates knowledge as well as effort, so the tidier your arrangement gets the more it depends on a single person being available.",
  why: "There are two distinct failures here and they get bundled. The first is access: if you are unavailable for a month through illness or an accident, can anyone pay the bills, see what exists, or stop a transfer that has become a problem. That one is about continuity and it applies long before anyone dies.\n\nThe second is distribution, and it has a structural surprise in it. Superannuation is often the largest asset a working person holds, and it does not flow through the will the way the rest does. It is paid by the trustee, and a nomination is how you direct that. A nomination you made when you started the job, or never made at all, is a decision that will be honoured, and for many people it is the single most consequential unreviewed default they own.\n\nBoth failures share a property that makes them easy to defer indefinitely: nothing goes wrong while you are fine, and the cost lands entirely on somebody else at the worst possible moment.",
  failureMode: "A three-week hospital stay during which nobody can see the accounts, two direct debits fail, and the person trying to help spends an afternoon on hold establishing what institutions are even involved. Nothing was lost permanently. The cost was entirely borne by someone who was already having a bad month, and it was preventable by one conversation.",
  worked: "The instruction names a person and a location, and no credentials:\n\n\"Write a single page listing every institution, account purpose and adviser, with no passwords, and tell my partner where it is. Then check my super beneficiary nomination and whether it needs renewing.\"\n\nAnd the access half, which needs a real mechanism rather than a promise:\n\n\"Set up emergency access in my password manager for one named person, with whatever delay period it offers.\"\n\nThe delay period is what makes this comfortable. Emergency access with a waiting window means the other person can start a request that you can cancel, so nothing is handed over today and nothing requires trust you have not already extended.",
  experiment: "Do the list first, because it needs no software and takes fifteen minutes: institutions, what each is for, and who to contact. No credentials on it. Then look up whether your super fund holds a beneficiary nomination for you, what kind it is, and whether it expires. Most people discover either that there is none or that it names someone from a previous decade.",
  reflection: "What did your super nomination turn out to say, and who now knows where the list is?",
  recall: {
    q: "Name the two distinct failures that follow from being the only person who can operate your financial system.",
    a: "Access and distribution. Access is a continuity problem that bites long before death: if you are unavailable for weeks, nobody can see what exists, pay what is due, or stop an instruction that has become a problem. Distribution is structural, because superannuation is generally not paid under your will but by the fund trustee, directed by a nomination that may be binding or non-binding and that many funds require you to renew.\n\nBoth defer easily because nothing goes wrong while you are well, and the entire cost lands on someone else at the worst moment. The remedy is a credential-free list of institutions someone knows the location of, plus a delayed emergency access mechanism."
  },
  deepDive: "Help me write the one-page list of what exists and who to contact, and tell me what I should check about my super nomination."
},
{
  id: "install-second-person-in-the-loop",
  track: "install", level: "judgement",
  title: "An instruction only one of you knows about will be reversed by the other one, correctly, at the worst moment",
  source: "Practice in shared operational ownership: a change one operator makes and does not communicate is a change the next operator undoes",
  gateIntro: "You increased the automatic transfer by two hundred a fortnight in June. It was clearly the right call and it came out of your own discretionary spending, so you did not raise it. In October your partner is looking at why the joint account is tighter than expected, finds a transfer they do not recognise, and is about to change it back.",
  gatePrompt: "Write what you should have sent in June. One message, and it should not be an explanation of the arithmetic.",
  evidence: "No trial specific to household finance. This is the general shape of shared ownership of any operational system: an undocumented change made by one operator looks, to the next person examining the system, indistinguishable from a fault. The household version adds that the second person is not merely maintaining the system but has standing to disagree with it, so the fix is agreement rather than documentation. The evidence on whether joint financial arrangements improve savings outcomes is thin and I would not lean on it.",
  replication: "craft",
  idea: "In a shared financial system the unit that has to survive is the agreement, not the instruction, because an instruction without an agreement gets reversed by someone acting reasonably.",
  why: "The reversal is not a failure of communication in the usual sense. Put yourself on the other side. You find an unexplained recurring outflow you did not authorise, during a month when money is tighter than expected. Reverting it is the correct response to that information. The person undoing your good decision is behaving exactly as you would want them to behave if the transfer had been an error.\n\nSo the thing that failed is upstream. A change to shared cash flow made unilaterally is not actually installed, however correctly it is configured, because it lacks the only property that would let it survive contact with the other person: they know why it exists.\n\nThis also cuts against the instinct that a change coming out of your own spending needs no discussion. The money may be yours; the visible effect on the joint account is not, and the effect is what the other person is reasoning from.",
  failureMode: "Four months of an increased transfer, reversed in an afternoon, followed by a conversation in which you are both right and both annoyed. The saving was real and is gone, and the more expensive casualty is that the next improvement you want to make now has a bad precedent attached to it.",
  worked: "One message, sent in June, and it is short because length signals that permission is being sought:\n\n\"I bumped the savings transfer by $200 a fortnight from my side. You will see it on the statement. Say if that is tighter than it should be.\"\n\nAnd the standing version, which is the actual install:\n\n\"Any change to a recurring amount that shows up on a shared statement gets a one-line message on the day I make it.\"\n\nOne line, on the day. Not a discussion, not a budget meeting, not a proposal. The requirement is only that the change is never a surprise to someone reading the statement, because surprise is what triggers the reversal.",
  experiment: "Look at the recurring transfers and debits on any shared account and identify any that the other person could not explain if asked. Send the one-line message for each of them now, retrospectively. Then agree the standing rule, which takes about thirty seconds and prevents the entire class of problem.",
  reflection: "How many shared recurring items could the other person not have explained?",
  forecast: { q: "Over the next six months, will every change I make to a shared recurring amount have been messaged on the day I made it?" },
  recall: {
    q: "Why does a unilateral increase to a shared savings transfer get reversed even when it was the right decision?",
    a: "Because to the person who finds it, an unexplained recurring outflow during a tight month is indistinguishable from an error, and reversing it is the correct response to that information. They are behaving exactly as you would want if it genuinely had been a mistake.\n\nSo the failure is upstream of the configuration. In a shared system the unit that has to survive is the agreement rather than the instruction, and the fact that the money came from your own discretionary spending does not help, because the other person is reasoning from the visible effect on the joint statement."
  },
  deepDive: "Here are the recurring items on our shared accounts. Help me work out which ones my partner could not explain and draft the one-line messages."
},
{
  id: "install-separate-list-from-decision",
  track: "install", level: "judgement",
  title: "A checklist with one judgement call on it stops being a checklist and stops getting done",
  source: "Checklist practice in aviation and surgery, including the WHO surgical safety checklist programme, read as an analogy rather than as transportable evidence",
  gateIntro: "Your annual review list has six items. Five are checks with a yes or no answer. The sixth is whether to change your asset allocation given that your income has grown and there is now a dependant. Last July you got to item five, looked at item six, and decided to come back to it properly at the weekend. You did not, and the list has not been opened since.",
  gatePrompt: "Split the list. Write which items stay on it and where the sixth one goes instead.",
  evidence: "No trial in this domain. Checklists have documented benefits in surgical and aviation settings, most prominently through the WHO surgical safety checklist programme, and the mechanism proposed is that they catch known, forgettable steps under load. Transporting that to a household financial review is an analogy and not evidence, and the analogy is weaker than it looks because the surgical setting has enforced compliance and a team. What carries over is the design principle rather than the effect: a list works on items that are verifiable and fails on items that require deliberation.",
  replication: "craft",
  idea: "Verifiable checks and open decisions need separate homes, because a list containing both stalls at the decision and takes the checks down with it.",
  why: "A checklist is a device for defeating forgetting under conditions of limited attention. Its power comes entirely from the items being closed: each one is a state you can observe and tick, so the list can be completed by someone tired, and completion is what gets it repeated.\n\nAn open decision has none of those properties. It requires unhurried thought, a view about the future, sometimes a conversation with another person, and it cannot be resolved by observation. Placing one on the list makes the list uncompletable, and an uncompletable list is abandoned rather than partially banked, because the memory it leaves behind is of not finishing.\n\nWorse, the decision is also badly served. Item six deserves an hour of proper attention and instead gets whatever is left at the end of an administrative session, which is the condition under which people default to changing nothing. So the mixed list reliably produces the worst available outcome on both halves: the checks lapse and the decision is made by exhaustion.",
  failureMode: "A list that was working fine for two years accumulates one genuinely important decision, stalls, and is not opened again for eighteen months. The five checks it used to catch stop being caught, and the decision that broke it is still unmade. Nothing about the list got worse except its composition.",
  worked: "Split it, and give the decision a date of its own:\n\n\"The July list holds only items with a yes or no answer. Anything requiring a decision comes off it and goes into a separate note called open questions, each with a date I will sit down with it.\"\n\nAnd the rule that keeps the split holding over time, because the drift back is gradual:\n\n\"If an item on the July list ever makes me pause to think, it is not a check, and it moves to open questions during that same session.\"\n\nThat migration rule matters because lists rot in one direction. Circumstances turn a formerly trivial check into a live question, and without a rule for noticing it, the list quietly acquires the item that will eventually kill it.",
  experiment: "Take whatever financial checklist you already have, formal or in your head, and sort each item into verifiable or decision. Move every decision to a separate list with its own date. If the exercise leaves your checklist shorter than you expected, that is the point: the removed items were the reason it was not getting done.",
  reflection: "Which item had been quietly stalling your list, and when have you scheduled it?",
  recall: {
    q: "Why does adding one genuine decision to an otherwise verifiable checklist damage both the list and the decision?",
    a: "Because a checklist's power comes from every item being closed and observable, which is what lets a tired person complete it, and completion is what makes it get repeated. An open decision needs unhurried thought and cannot be resolved by observation, so it makes the list uncompletable, and an uncompletable list gets abandoned rather than partially banked.\n\nThe decision suffers too, because it receives whatever attention is left at the end of an administrative session, which is the condition under which people default to changing nothing. The mixed list produces the worst outcome on both halves at once."
  },
  deepDive: "Here is my financial checklist. Sort it into verifiable checks and open decisions, and tell me which items are about to migrate."
},
{
  id: "install-keep-a-dated-log",
  track: "install", level: "annual",
  title: "Without a dated record of what you changed, you cannot tell which change did anything",
  source: "Change-log practice in operations: record what was altered and when, so a later effect can be attributed to a cause",
  gateIntro: "Your savings rate is four points higher than it was two years ago and you are pleased. In that period you changed employer, increased a transfer twice, consolidated two accounts, cancelled some subscriptions, moved house, and started paying more attention generally. Asked which of those did the work, you would guess, and your guess would be the one you remember putting effort into.",
  gatePrompt: "Write the log entry for the most recent change you made, in the format you would want to still be using in three years.",
  evidence: "No trial. This is ordinary change-log discipline: record the alteration and its date, so that when a metric moves later there is a candidate list of causes rather than a reconstruction from memory. The reason it matters more than it seems is documented elsewhere in this corpus rather than here: self-reported financial history is systematically distorted, and the entries on survey-versus-register measurement and on backtest overfitting both describe the same underlying failure of reasoning from a record you assembled after the fact.",
  replication: "craft",
  idea: "Write down what you changed and when, because a metric that moves two years later has no way of telling you which of six changes moved it.",
  why: "The attribution problem is unavoidable at the scale of one household. You cannot run a control, so the only evidence you will ever have about what works for you is the sequence of what you did and what followed. If the sequence is not recorded, the evidence does not exist, and what fills the gap is a narrative built from whichever change felt most effortful.\n\nThat bias has a predictable direction. Effort is memorable and structural changes are not, so you will over-credit the subscription audit you agonised over and under-credit the transfer increase that took ninety seconds and then ran for two years. Which means your accumulated sense of what works drifts steadily toward the interventions that felt like work, and those are exactly the ones this site argues are the weak ones.\n\nThe log fixes it cheaply and asymmetrically. It costs one line at the moment of change, when the information is free because you are already there, and it pays out years later at the only moment you would otherwise be guessing.",
  failureMode: "Two years of genuine improvement, credited almost entirely to a spending discipline you abandoned after four months, while the two automatic increases that actually did it are not in the story at all. You then repeat the thing you credited, it does nothing again, and you conclude your finances are mysterious.",
  worked: "One line per change, in a format you will still tolerate in three years:\n\n\"2026-09-03: raised fortnightly transfer from $400 to $500. Reason: pay review. Expect savings rate up about 1.5 points.\"\n\nAnd the field that makes it evidence rather than a diary:\n\n\"Every entry records what I expect to happen, so that reading it back tells me whether I was right rather than only what I did.\"\n\nThe expectation is the whole difference. A log of actions tells you the history. A log of actions with predictions attached is the only calibration data you will ever have on your own judgement about your own money, and it is the same discipline the forecast book in this site applies to a single question.",
  experiment: "Start the log with the change you made most recently, backdated as accurately as you can, including what you expected. Then commit to the rule that no instruction gets installed without a line. It lives in the same note as everything else; a log in a separate application is a log you will stop opening.",
  reflection: "What was your first log entry, and what did you write in the expectation field?",
  forecast: { q: "Will every financial change I make over the next six months have a dated log line with an expectation in it?" },
  recall: {
    q: "Why does the absence of a change log bias your beliefs in a specific direction rather than just leaving them vague?",
    a: "Because what fills the gap is memory, and memory is weighted by effort. Structural changes that took ninety seconds and then ran for years are forgettable, while an agonising spending audit is vivid, so credit flows to the interventions that felt like work.\n\nThose are precisely the interventions with the weakest evidence, so an unlogged history drifts steadily toward believing in the things that do not work. The remedy is asymmetrically cheap: one line at the moment of change, when the information is free, paying out years later at the only moment you would otherwise be guessing. Recording the expected effect is what turns the log from a diary into evidence."
  },
  deepDive: "Help me reconstruct a dated log of the financial changes I have made in the last two years, and tell me which ones I am probably over-crediting."
},
{
  id: "install-surviving-a-provider-change",
  track: "install", level: "annual",
  title: "Moving banks does not move your instructions, and the ones you forget are the ones nobody bills you for",
  source: "Migration practice: enumerate dependencies before cutover, and verify each one after",
  gateIntro: "You are switching to a bank with a better rate. The new account is open, the salary redirection form is submitted, and you are planning to leave the old account open for a couple of months to catch anything you missed. That plan sounds prudent and it is how most people discover, in about January, that something they missed was not a bill.",
  gatePrompt: "Write the migration list, in the order you would run it, and say what tells you it is safe to close the old account.",
  evidence: "No trial. Standard migration discipline: enumerate what depends on the system being replaced, cut over in a controlled order, and verify each dependency afterwards rather than assuming absence of complaint means success. The specific hazard in a bank change is asymmetric visibility, which is the same mechanism as the entry in this track on detecting silent stops: an unpaid bill generates a demand, and an unmade savings transfer generates nothing at all.",
  replication: "craft",
  idea: "Outgoing obligations announce themselves when they fail and your own savings instructions do not, so a migration verified by the absence of complaints will silently drop exactly the arrangements this site is about.",
  why: "Think about what happens to each category when the old account runs dry. A utility direct debit fails and the utility contacts you, loudly and within a fortnight. An insurance premium fails and you get a lapse notice. Every outgoing obligation has a counterparty whose job includes noticing.\n\nYour transfer into savings has no counterparty. If it fails, or if you simply never recreate it on the new account, the only entity that would care is you, and you are the one who is busy switching banks. So a migration that is validated by watching for problems will reliably preserve everything that bills you and lose the things that build you.\n\nThe second hazard is the two-month grace period, which feels like a safety net and is actually a delay. It postpones discovery past the point where you remember what you were doing, and it lets the old account keep servicing arrangements you have forgotten exist, so you learn nothing during the window that was supposed to be for learning.",
  failureMode: "The utilities, insurance and loan all transition perfectly because each has an organisation chasing you. The two automatic savings transfers do not survive, and you notice in March when a balance you expected to be several thousand higher is not. The migration went well by every signal you were monitoring.",
  worked: "The list runs from the invisible to the loud, which is the reverse of the intuitive order:\n\n\"First recreate every transfer into savings and investment, because nothing will remind me. Then the direct debits, which will remind me. Then redirect the salary. Then verify each one has executed once on the new account before closing the old.\"\n\nAnd the closing condition, which is a test rather than a duration:\n\n\"I close the old account when every item on the list has executed once from the new one, not after two months.\"\n\nExecuted once is the standard because it is the only evidence that the account details were right. A configured instruction that has never run is indistinguishable from a mistyped one.",
  experiment: "You do not need to be switching banks to do the useful half. Write the dependency list now: everything that debits or credits your main account, sorted into things with a counterparty who would chase you and things without. The second list is short, and it is the one you would lose. Keep it with your other instructions.",
  reflection: "How many items were on your no-counterparty list, and had you ever written them down before?",
  forecast: { q: "If I change bank or account in the next two years, will every no-counterparty instruction have executed once from the new account before I close the old one?" },
  recall: {
    q: "Why does a bank migration verified by watching for problems reliably lose your savings arrangements?",
    a: "Because visibility is asymmetric. Every outgoing obligation has a counterparty whose job includes noticing: a failed utility debit produces a demand, a failed premium produces a lapse notice. A transfer into your own savings has no counterparty, so if it is never recreated the only entity that would care is you, and you are the person busy switching banks.\n\nSo monitoring for complaints preserves everything that bills you and drops the things that build you. The two-month grace period compounds it by postponing discovery past the point where you remember what you were doing, and the right closing condition is that every instruction has executed once from the new account rather than that a duration has elapsed."
  },
  deepDive: "Here is everything that debits and credits my main account. Sort it by whether anyone would chase me, and build me a migration order."
},
{
  id: "install-decide-when-to-abandon",
  track: "install", level: "judgement",
  title: "Write the abandonment criterion when you install the thing, because afterwards quitting and persevering feel identical",
  source: "The practice of specifying a stopping rule in advance, as applied to a personal arrangement rather than to a trial",
  gateIntro: "The transfer has been running eleven weeks. Twice you have moved money back out of the savings account within days of it landing, which you told yourself was a timing issue both times. The arrangement is technically still in place and you would describe it as working if someone asked. You have not defined what would count as it not working.",
  gatePrompt: "Write the criterion that would tell you this instruction has failed, with a number and a window in it.",
  evidence: "No trial. This is the ordinary discipline of specifying a stopping rule before observing the outcome, and the reason it appears in this track is that its absence has a specific consequence for automated arrangements: an instruction that is configured but routinely reversed reads as compliance in every place you would look. The related evidence is the commitment device literature elsewhere in this corpus, which finds that over-restrictive arrangements get abandoned outright, meaning the correct response to a failing instruction is often a smaller one rather than more resolve.",
  replication: "craft",
  idea: "Define the failure condition at install time, because a running instruction you keep reversing looks exactly like a running instruction that works.",
  why: "The specific pathology of an automated arrangement is that its status is not the same as its effect. The transfer executes, the statement shows it, the count of instructions is unchanged, and none of those records knows that you moved the money back three days later. Every measurement you have says the thing is in place.\n\nThat means the ordinary signal for reconsidering something, namely that it visibly is not happening, never arrives. You get to keep the feeling of having installed it indefinitely, which is worse than an outright failure because an outright failure would prompt a fix.\n\nAnd the fix is usually counterintuitive. The commitment literature's finding is that people abandon restrictions they set too tight, so a transfer you keep reversing is more often evidence that the amount was wrong than that your discipline is. Persevering with the same number is the intuitive response and the wrong one. Halving it and letting it run is the move that produces the decade of contributions, and you will only reach for it if you decided in advance what failure looked like.",
  failureMode: "Nine months of an instruction that has been reversed in six of them, still counted among your installs, still described as working. The honest version of that arrangement is a transfer at a third of the amount that would have run untouched for the same nine months, and nothing in the system was ever going to suggest it.",
  worked: "The criterion needs a number and a window:\n\n\"If I withdraw from this account more than once in any three-month period, the amount is wrong. I halve the transfer rather than trying harder, and I log the change.\"\n\nAnd the second clause, which prevents the criterion from being an excuse:\n\n\"Halving is available twice. If it fails at a quarter of the original amount, the problem is not the size and I stop and work out what it actually is.\"\n\nTwo halvings and then a stop, because an escape hatch with no limit is just a slow cancellation. What that structure buys you is a defined path from a failing instruction to a running one, decided while you were calm, so the decision in month three is a lookup rather than a judgement about your own character.",
  experiment: "For the instruction you most recently installed, write the criterion now: what observation, within what window, would mean the amount is wrong rather than that you are. Add it to the log line for that instruction so the criterion and the install live in the same place. Then check whether any currently running instruction already meets its own criterion.",
  reflection: "Which of your running instructions already meets a failure criterion you had never written down?",
  forecast: { q: "Will every instruction I install over the next six months carry a written failure criterion at the moment I install it?" },
  recall: {
    q: "Why does an automated arrangement need an explicit failure criterion more than a manual habit does?",
    a: "Because its status and its effect come apart. The transfer executes, the statement records it and the instruction count is unchanged, and none of those signals knows you moved the money back three days later, so every available measurement reports compliance. The ordinary prompt to reconsider something, that it visibly is not happening, never arrives.\n\nThe criterion also points at the right fix. The commitment evidence suggests people abandon restrictions set too tight, so repeated reversal is usually evidence the amount was wrong rather than that discipline was. Halving and letting it run beats persevering at the same number, and you only reach for that if failure was defined in advance."
  },
  deepDive: "Here is an instruction I keep reversing. Tell me whether the amount is wrong or the arrangement is, and what the smaller version should be."
},
{
  id: "install-what-cannot-be-installed",
  track: "install", level: "judgement",
  title: "Every instruction here presupposes a target, and no default will ever supply one",
  source: "The boundary of this method, stated explicitly rather than left for the reader to discover",
  gateIntro: "You now have five things running, a log, a July date and a failure criterion for each. The machinery is genuinely good and it is doing what this site said it would. Someone asks you what you are saving for and you produce an answer about retirement that you notice you do not really believe, and which would not survive them asking a second question.",
  gatePrompt: "Write the question you cannot currently answer, as a question rather than as an attempt at an answer.",
  evidence: "No trial, and no possibility of one. What the evidence in this corpus supports is that defaults, commitment and automation change behaviour at magnitudes that dwarf financial education. None of that literature addresses what the behaviour should be aimed at, because the trials all take the objective as given: more saving is treated as the outcome. That is a reasonable simplification for a study and it is not one you can carry into your own life without noticing you have carried it.",
  replication: "craft",
  idea: "Automation is a way of routing around inattention, and it has nothing to offer against not knowing what the money is for.",
  why: "Notice the shape of every mechanism in this corpus. A default works because doing nothing produces the good outcome, which requires somebody to have decided which outcome is good. A commitment device works by making defection expensive, which requires knowing what you are committing to. An escalation rule works by binding a future raise, which requires a view about how much of your life should be spent accumulating rather than spending. In each case the machinery is downstream of a judgement it cannot make.\n\nThis is why the levels in this site exist and why some entries are marked as judgement rather than standing. The honest reading of the whole method is that it is extremely good at the part where your attention runs out, and silent on the part where your reasons do. Those are different failures and only one of them has a solution you can install.\n\nWhich also means the machinery can go wrong in a way none of its own signals will detect. Five instructions running perfectly toward a target you do not believe in is a well-engineered system pointed somewhere you did not choose, and the counters will look excellent throughout.",
  failureMode: "A decade of rising balances, every instruction honoured, and a growing sense that the accumulation is not connected to anything you want, followed by either an abrupt abandonment of the whole arrangement or a continuation on inertia. The machinery was never the problem and cannot be the fix. It did exactly what it was configured to do.",
  worked: "The output here is a question rather than an instruction, which is the point:\n\n\"What is the number for, and what would I do differently in the next two years if I already had it?\"\n\nAnd the one honest scheduling move available, since this cannot be automated but can at least be given a place:\n\n\"Once a year, in a different month from the July checklist, I sit down with the question of what this is for. Not as an item on a list, and not in the same session as the checks.\"\n\nA different month is deliberate. Bundling the question into the administrative review is how it gets answered in four minutes by whoever is tired at the end of the list, and this track has already established what that does to both halves.",
  experiment: "Write the question down without answering it. Put a date on it, in a month that is not July, and leave it. The discipline being practised is refusing to resolve a judgement call at administrative speed, which is the opposite of every other experiment in this track and is the reason this entry is last.",
  reflection: "What is the question you could not answer, and what month did you give it?",
  recall: {
    q: "What class of problem is this entire method unable to address, and how would you notice?",
    a: "It cannot supply a target. Every mechanism here is downstream of a judgement it cannot make: a default needs someone to have decided which outcome is good, a commitment device needs to know what is being committed to, an escalation rule needs a view on how much of a life should go to accumulating. The method routes around inattention and has nothing to offer against not knowing what the money is for.\n\nYou would not notice from the system's own signals, which is the danger. Instructions running perfectly toward a target you do not believe in produce excellent counters throughout, so the only detection is asking the question deliberately, in a session separated from the administrative one."
  },
  deepDive: "I have the machinery running and I cannot say what it is for. Interrogate me until the question has a shape, and do not let me answer it quickly."
}
);
