/* Track: Where the answer goes. Ordered foundational first.
 *
 * Position rather than wording. Everything here is about a sentence that was
 * written correctly and put somewhere the reader was never going to reach,
 * which is a different defect from writing it badly and has a different fix.
 * The last two entries are about the medium doing the burying for you. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "order-answer-first",
  track: "order", level: "reply",
  title: "Lead with the answer, not the road you took to it",
  source: "Barbara Minto, The Pyramid Principle",
  gateIntro: "The VP of engineering asked exactly one question in a thread this morning: can we ship Thursday. Your draft reply runs to four paragraphs.\n\nIt opens with what you found when you looked at the test failures, moves through which of them were flakes and which were real, explains the dependency on the vendor's staging window, and covers what happened when you tried the workaround on Tuesday.\n\nThe answer is in the final sentence. It is no, and the earliest is the following Monday.",
  gatePrompt: "Write what the VP does after reading the first two paragraphs, which is as far as they get.",
  evidence: "No trial. Minto developed the pyramid as a house standard at McKinsey and taught it as craft; it has never been tested against an alternative ordering under controlled conditions. It has been the default in consulting and much of technical writing for four decades, which is evidence about adoption rather than about effect. The adjacent claim that readers of professional prose scan rather than read linearly is better supported and is not the same claim.",
  replication: "craft",
  cheat: "Put the answer in the first sentence and the derivation under it. A reader who stops after one line should still be holding the answer.",
  idea: "State the conclusion first and make everything after it optional, so that a reader who stops early stops holding your finding rather than holding your working.",
  why: "You wrote it in the order you discovered it, which is the order that makes sense only to somebody who already knows the ending. The investigation felt like the substance because that is where the week went, so it arrives first and the finding arrives last, and that sequence is a faithful record of your effort rather than a message.\n\nThe reader is doing something else entirely. They arrived holding a question and they are scanning for the shape of an answer, so everything before it is cost. If they stop early, and they usually do, what they leave with depends on where you put the conclusion. At the top they leave with the answer and no detail. At the bottom they leave with detail and no answer, which is worse than sending nothing, because it consumed their attention and left them still not knowing. Putting the conclusion first also changes what the detail is for: it stops being an argument they have to follow and becomes support they can audit if they choose, which is a much lower demand on somebody who was only ever going to spend forty seconds.",
  failureMode: "You get asked the same question again a day later, sometimes by the same person, and you conclude they did not read it. They did read it. They read the part you put first, and it was about test flakes.",
  worked: "\"No, Thursday is not achievable. Earliest is Monday the 24th.\n\nWhy: the vendor's staging window does not open until Friday and we cannot run the integration suite without it. That is the whole blocker. Everything else is now fixed.\n\nDetail if you want it: of the eleven test failures, nine were flakes from the parallel runner and are gone. The two real ones were the serialisation bug, fixed Tuesday. We tried a workaround for the staging dependency and it needs a credential we will not have by Thursday.\n\nIf Monday is a problem, the lever is the vendor rather than us, and I would need you to make that call today.\"\n\nStill four paragraphs. The reader who stops after seven words has the answer, the reader who stops after two has what to escalate, and the reader who wants the working has it.",
  experiment: "Take the last five substantial replies you sent and find the sentence carrying the answer. Note which paragraph it was in. If the median is not the first, you have a systematic ordering problem rather than five individual lapses, and the fix is a habit rather than a rewrite.",
  reflection: "What did you get asked twice this month, and where was the answer in your first reply?",
  recall: {
    q: "Why is a message that ends in its conclusion worse than sending nothing, and what else changes when the conclusion moves to the top?",
    a: "Because a reader who stops early leaves with detail and no answer, having spent attention and gained nothing, whereas stopping early on a conclusion-first message still leaves them correct. Moving it also changes what the detail is for: it stops being an argument that must be followed and becomes support that can be audited, which is a far lower demand on somebody spending forty seconds."
  },
  deepDive: "Here is a reply I drafted. Find the sentence that actually answers the question and rewrite it so that sentence comes first."
},
{
  id: "order-bury-the-lede",
  track: "order", level: "record",
  title: "The load-bearing sentence drifts into the middle on its own",
  source: "The newsroom convention of the lede, and the standing instruction against burying it",
  gateIntro: "You have written a 900-word update on the payments migration. It is well organised: background, current state, the three workstreams, risks, next steps.\n\nUnder risks, fourth bullet, sits this sentence: \"We have not yet found a way to reconcile the historical ledger, and if we cannot, the cutover cannot be reversed once it starts.\"\n\nYou are aware this is the most important sentence in the document. You filed it under risks because that is where risks go.",
  gatePrompt: "Write what the three people who read this to the end believe about whether the migration is safe.",
  evidence: "No trial. The instruction comes from newsroom practice, where it is enforced by editors rather than derived from research, and it entered technical and business writing by transfer. What supports it indirectly is the better-established finding that readers of professional prose scan rather than read linearly, which makes position load-bearing whether or not anybody has measured this particular rule.",
  replication: "craft",
  cheat: "Find the sentence that would change somebody's plans, then check whether it is in the first three lines or in a bullet under risks.",
  idea: "Locate the sentence that would change what somebody does and put it where the structure cannot absorb it, which usually means breaking the structure you were taught.",
  why: "A conventional structure is a filing system, and filing systems sort by category rather than by importance. Background goes first because it is background. Risks go near the end because that is where risks go. So a sentence that should stop the room ends up stored beside four sentences that should not, formatted identically, and the reader's eye grants it exactly the weight the format assigns.\n\nThe author almost always knows which sentence it is, and that is the part worth noticing, because it means this is not a failure of judgement about content. It is a failure to let the judgement override the template. What keeps it in place is that a tidy document feels finished, and hoisting the frightening line to the top makes it feel alarmist. The discomfort of appearing alarmist is immediate and lands on you. The cost of being ignored is deferred and lands on somebody else, which is a trade people make without ever seeing it as one.",
  failureMode: "Nobody is surprised afterwards, because it was in the document, and nobody acted at the time, because it was in the document under risks. The retrospective finds the sentence, quotes it, and concludes the information was available. Being able to point at where you wrote it is the consolation available to people who did the other half badly.",
  worked: "The document keeps its structure. What it acquires is a first paragraph the structure had no slot for.\n\n\"One thing before the detail: we do not currently have a way to reconcile the historical ledger, and until we do, the cutover is irreversible once it starts. That is a change from what this group was told in June, when the plan assumed a rollback path.\n\nI am not asking for a decision today. I am asking that nobody plans around a rollback until I confirm we have one, and that we do not commit to a date in front of the customer this week.\n\nBackground, current state and the three workstreams are below, unchanged from last week.\"\n\nThe other 900 words are untouched. What was added names the change, says what it invalidates, and states what it does and does not ask for, which is the thing that stops a hoisted line from reading as alarm.",
  experiment: "Take a document you wrote in the last month and ask one question of it: which single sentence, if the reader missed it, would leave them planning wrongly? Then find where it sits. Do this for three documents before concluding anything, because one instance is a lapse and three is a habit.",
  reflection: "What did you write down, correctly, that nobody acted on?",
  recall: {
    q: "Why does a conventional document structure reliably bury its most important sentence, and what keeps authors from fixing it when they can see it happening?",
    a: "Because the structure sorts by category rather than importance, so a sentence that should stop the room is filed beside routine ones and formatted identically, and the eye grants it the weight the format assigns. Authors leave it because hoisting it feels alarmist, and the discomfort of appearing alarmist is immediate and theirs while the cost of being ignored is deferred and somebody else's."
  },
  deepDive: "Here is a document I wrote. Tell me which sentence would change a reader's plans, where it currently sits, and how to hoist it without sounding alarmist."
},
{
  id: "order-stopping-points",
  track: "order", level: "broadcast",
  title: "What you know about how people scan is overclaimed, and the robust move does not need it",
  source: "Serial position effects in recall, and the eye-tracking scanning claims that outran them",
  gateIntro: "You are posting to the engineering channel about changes to the on-call handover. Six points: the new rota tool, the escalation path, weekend cover, the paging threshold for the ingest service dropping so it now fires on one failed batch rather than three, where the runbooks moved to, and how to raise problems.\n\nThey are in that order because that is the order the working group covered them in. The fourth is the one that will wake somebody at three in the morning.",
  gatePrompt: "Write what an on-call engineer remembers about this post a week later, at three in the morning.",
  evidence: "Real, and sold well past what it supports. Serial position effects, where the start and end of a list are recalled better than the middle, are among the most replicated findings in memory research, but they were established on lists of unrelated items recalled immediately, which is not what reading a work announcement is. The popular version, that readers scan in an F-shaped pattern and skip the middle, comes from Nielsen Norman eye-tracking work on early web pages that were largely unstructured text: a real observation on a narrow sample, routinely quoted as a law of reading. The direction of both is probably right and the confidence attached to them is borrowed rather than earned.",
  replication: "overclaimed",
  cheat: "Check that a reader who stops after the first line, and again after the first paragraph, is left holding something true rather than something partial.",
  idea: "Build the message so that stopping at any point leaves the reader with a true and useful picture, instead of optimising the layout against a model of where their attention goes.",
  why: "The models are weaker than their reputation, and the weakness is specific. Findings about recall of word lists were never measured for the medium you are writing in, and the eye-tracking work everybody quotes was done on a kind of page that no longer exists. Designing your announcement around a claim about where an eye travels means designing around a number nobody collected for your case, and being confidently wrong about it is worse than having no model, because it produces a layout you trust.\n\nWhat survives the uncertainty is a weaker rule that turns out to be more useful. If you cannot know where a reader stops, make every stopping point safe: the first line true on its own, the summary true without the detail, and anything that changes what somebody does lifted out of the sequence rather than left at position four. This costs nothing if the scanning research holds and still works if it does not, which is the property you want in a rule you will apply several times a day without thinking about it.",
  failureMode: "The post is complete, correctly ordered, and read by everybody, and at three in the morning an engineer pages on a single batch and does not know why. Nobody misread anything. The item sat in the position where things go to not be recalled, and the format gave it the same weight as where the runbooks moved to.",
  worked: "One item is lifted out of the list. The rest keeps its order.\n\n\"On-call changes, effective Monday. One of these will affect you at three in the morning, so it is first.\n\nIngest now pages on a single failed batch, down from three. If you are on call for ingest, expect more pages, and the first thing to check is whether the batch retried on its own before you escalate anything. Runbook section 4 covers it.\n\nEverything else is administrative: new rota tool, escalation path unchanged, weekend cover moves to two people, runbooks have moved, problems to this channel. Detail in the thread.\"\n\nAll six points survive. What changed is that one of them stopped being an item in a list.",
  experiment: "Take your next multi-point announcement and ask, for each item, what happens if the reader misses this one. Most lists have exactly one item where the answer is serious. Lift that one out and leave the others as a list, and notice how much you wanted to preserve the tidy parallel structure.",
  reflection: "What did you announce in the middle of a list that somebody later said they had not known about?",
  recall: {
    q: "Why is designing a message around where readers scan a weaker move than making every stopping point true?",
    a: "Because the scanning claims carry more confidence than they earned: serial position was established on immediate recall of unrelated word lists, and the F-pattern comes from eye-tracking on early unstructured web pages, so neither was measured for the medium you write in. Making each stopping point true costs nothing if those findings hold and still works if they do not."
  },
  deepDive: "Here is a multi-point announcement. Tell me which single item is serious if missed, and rewrite it so that item is not in the list."
},
{
  id: "order-name-the-problem-part",
  track: "order", level: "reply",
  title: "Say which part is the problem, because a third of feedback conversations make things worse",
  source: "Kluger and DeNisi's meta-analysis of feedback interventions",
  gateIntro: "You are replying to a design document from an engineer two levels below you. The architecture is fine. The data model has a problem that becomes expensive in about eighteen months, and they have not seen it.\n\nYour draft opens with two sentences on how thorough the document is, moves into the data model concern, and closes by saying the overall direction is right and you are glad they picked this up.\n\nAll of it is sincere. You do think it is thorough and you do think the direction is right.",
  gatePrompt: "Write what this engineer tells their manager the review said.",
  evidence: "Kluger and DeNisi's meta-analysis of 607 effect sizes found feedback interventions raised performance by around 0.4 of a standard deviation on average, and that more than a third of them lowered it. That result is well established and has held up. What it does not establish is the remedy offered here. Their proposed mechanism, that harm comes from feedback drawing attention to the self rather than to the task, is well argued and much less well tested, and the specific prohibition on wrapping criticism in praise is craft with no trial behind it at all.",
  replication: "replicated",
  cheat: "Say which sentence is the request and which is the compliment. If the reader has to work it out, they will pick the flattering reading.",
  idea: "Mark the critical part explicitly as the thing you want changed and keep the praise out of contact with it, because a reader deciding how seriously to take a review resolves ambiguity in whichever direction costs them least.",
  why: "The average effect conceals the finding worth having, which is that feedback is not reliably helpful and a substantial minority of it makes performance worse. The proposed explanation is that direction depends on where attention lands: feedback pointing at the task improves the task, and feedback pointing at the self, favourably or otherwise, competes with it. That is a mechanism rather than a demonstrated law, and it remains the most useful available account of why well-intentioned reviews so often change nothing.\n\nThe practical form of the failure is ambiguity about which part was the point. When a criticism sits between two compliments and all three arrive in the same register, the reader has to decide how much weight the middle carries, and they decide under an incentive: one reading requires eighteen months of rework and the other requires nothing. People do not resolve that neutrally, and it is not dishonesty when they do not. The fix is not removing the praise. It is stopping the praise and the problem from being the same kind of sentence, so that no interpretation is called for.",
  failureMode: "You leave believing you raised it. They leave believing they got a positive review with a note attached. Eighteen months later the data model is expensive and both of you can produce the document showing it was mentioned, which is the property that keeps this failure invisible for exactly as long as it takes to become unfixable.",
  worked: "The praise and the problem are separated and given different shapes.\n\n\"One thing to change before this goes ahead, then some smaller notes.\n\nThe change: the model keys events on the tenant identifier rather than on an internal id. That holds until a tenant is renamed or merged, and both happen. When it does, every historical event for that tenant becomes unattributable and there is no migration that recovers it. I want this keyed on an internal id before we build anything on top. If you think that is wrong, tell me why and I will look again.\n\nSeparately, and not a qualification of the above: this is the most thorough design document I have read this quarter, the failure-mode section especially, and I am glad you picked the problem up.\"\n\nThe compliment survives intact and now reads as a compliment rather than as a cushion, because it has been moved out of contact with the request and labelled as separate.",
  experiment: "Take your last three written reviews and give each to somebody uninvolved, asking them to tell you what the author is meant to change. Where they cannot say, the review contained no request, whatever you believed you were doing when you wrote it.",
  reflection: "What did you raise in a review that came back unchanged, and how was it phrased?",
  recall: {
    q: "What does the feedback meta-analysis actually establish, and what is it commonly stretched to support?",
    a: "It establishes that feedback interventions raise performance by roughly 0.4 of a standard deviation on average and that over a third of them lower it, which is well replicated. It is stretched to support specific delivery techniques, including the ban on sandwiching criticism in praise, which has no trial behind it and rests on the proposed self-versus-task attention mechanism rather than on the meta-analytic result."
  },
  deepDive: "Here is a review I am about to send. Tell me whether a reader could mistake which part is the request, and rewrite it so they cannot."
},
{
  id: "order-first-line-preview",
  track: "order", level: "broadcast",
  title: "For most of your readers the first line is the whole message",
  source: "Notification and preview conventions, where the first line is what the reader is actually shown",
  gateIntro: "You are sending to twelve people about a security patch that has to be applied by Friday. The draft opens: \"Hi all, hope everyone had a good week. Following up on the discussion in Tuesday's platform sync and the thread that came out of it, I wanted to circulate some detail on the CVE that was raised.\"\n\nThe deadline and the action appear in the fourth sentence. Six of the twelve will see this as a notification preview on a phone.",
  gatePrompt: "Write what the preview actually shows, and what a reader decides to do with the message on that basis.",
  evidence: "No study, and the important half is not a claim about people. Mail clients and chat applications render a truncated preview whose length is a design choice varying by client, platform and notification setting, so the constraint is a property of software. The behavioural half, that readers triage from previews, is evident from how the interfaces are used and has not been measured in any way worth citing. It is here because the constraint is real and almost nobody writes for it.",
  replication: "craft",
  cheat: "Read your first line with everything after it deleted. If it does not say who does what by when, the preview has been spent on nothing.",
  idea: "Write the opening line to survive being the only line the reader is shown, because in most clients the preview is what they are given before deciding whether to open anything at all.",
  why: "There is a rendering step between what you wrote and what the reader receives, and it truncates. A greeting, a context sentence and a reference to the meeting where this came up will consume the entire preview in most clients, so what the reader is shown appears to be a message about a meeting. They then triage that against everything else on the screen, and a message about a meeting loses.\n\nWhat makes this different from ordinary burying is that the reader has not read your message badly. They have not read it at all, and the decision not to was made on a fragment the software chose. The greeting was politeness and the context was diligence, and both were spent on the only real estate you were guaranteed. The move is not to be abrupt. It is to put the greeting after the load-bearing line, which reads perfectly well and which almost nobody does, because the ordering of a message feels like it belongs to etiquette rather than to the delivery mechanism.",
  failureMode: "Six of the twelve do not apply the patch, and when you check, they say they saw it and took it for a summary of the platform sync. You did send it, they did see it, and no part of the exchange was unreasonable, which is why the same thing happens again next Friday.",
  worked: "\"Action needed by Friday: apply the platform patch, ten minutes, steps below.\n\nHi all. This is the CVE raised in Tuesday's platform sync and in the thread afterwards. It affects the auth sidecar on any service still running 2.14.\n\nWhat to do: bump to 2.16 and redeploy. About ten minutes per service. If you are on 2.16 already there is nothing to do.\n\nIf you cannot make Friday, tell me before Thursday and I will arrange cover rather than find out about it on Monday.\"\n\nThe greeting survived. It moved down one line, which costs nothing, and the preview now carries the action and the deadline.",
  experiment: "Send yourself your next three important messages first and look at them as notifications on your phone without opening them. It takes about a minute and it is the only way to see what your recipients are shown, because you cannot see your own preview from the compose window.",
  reflection: "What did you send that people later said they had seen and not acted on?",
  recall: {
    q: "Why is a greeting followed by context an expensive opening, independent of how well the rest is written?",
    a: "Because clients render a truncated preview and triage happens there, so the greeting and context consume the only guaranteed real estate and the reader is shown something that looks like a meeting summary. The decision not to open is then made on a fragment the software chose, which means the message was not read badly, it was not read."
  },
  deepDive: "Here is a message I am about to send. Tell me what its notification preview will show, and rewrite the opening so the preview carries the action and the deadline."
}
);
