/* Track: What it will read as. Ordered foundational first.
 *
 * Tone, and the things that get read when nothing was written. This is the
 * track where the folklore lives, so two of the five are corrections rather
 * than moves: the seven per cent figure is about neither words nor
 * communication, and the well-supported asymmetry is a direction rather than
 * a ratio. Neither carries a cheatsheet row, because knowing a claim is false
 * is not something you reach for with a message half-written. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "reads-egocentrism-over-email",
  track: "reads", level: "reply",
  title: "You cannot hear your own tone, and neither can they",
  source: "Kruger, Epley, Parker and Ng, Egocentrism over e-mail",
  gateIntro: "You are replying to an engineer who has proposed rewriting the ingest pipeline. You think the proposal is good and you want them to run with it, and you also have two real concerns you want addressed first.\n\nYour draft: \"Interesting. Have we thought about what happens to the replay path? And I'd want to understand the cost before we commit. Worth digging into.\"\n\nIn your head this is enthusiastic. You are reading it in the voice you wrote it in.",
  gatePrompt: "Write what this engineer tells their partner that evening about how the proposal went down.",
  evidence: "Kruger and colleagues had participants write messages intended as sarcastic or serious and predict how accurately recipients would identify the intent. Senders expected to be understood around eighty per cent of the time and recipients performed close to chance, a little over fifty. The study is widely cited and rarely directly replicated, and it was small, lab-based, and used sarcasm, which is the hardest case rather than a representative one. The direction sits comfortably with the broader perspective-taking literature. The specific numbers should not be carried around.",
  replication: "single",
  cheat: "Write the verdict as a plain sentence: I think this is right and I want you to do it. Tone does not survive the trip.",
  idea: "State the attitude in words rather than trusting it to the phrasing, because you read your own message in the voice you composed it in and the reader has no access to that voice.",
  why: "When you read something you wrote, the tone is in your head before your eyes reach the words, because you produced the intention first and the sentence second. The reader has the sentence only. What they put in place of your voice is whatever their situation suggests, and for somebody waiting on a verdict about their own proposal, the ambient suggestion is not the generous one.\n\nThe experimental version of this is that senders substantially overestimate how well intent survives text, and the gap in the best-known study was large. Those particular figures came from a small lab study using sarcasm, which is the hardest possible case, and they should not be treated as a general rate. What survives the caveats is the direction and the reason for it: you cannot run the experiment on yourself, because you cannot read your own sentence without already knowing what it was for.\n\nThe fix is unglamorous. Say the attitude. Not through punctuation or emoji, which are compensations for the same problem and drift in meaning between people, but as a plain clause. I think this is right and I want you to do it has exactly one reading.",
  failureMode: "They spend the next week rewriting the proposal to address concerns you raised in passing, and they do not start the work, because nothing in your message told them to. You believed you had said yes with conditions. You had written four sentences of conditions and no yes.",
  worked: "\"I think this is right and I want you to do it. Treat that as a yes rather than as encouragement.\n\nTwo things I want addressed, neither of which blocks you starting.\n\nThe replay path. I do not think it survives the new partitioning and I would rather know that now than in month two. If it does not survive, that is fine, it just needs a plan.\n\nThe cost. I need a number before we commit hardware, not before you start designing. Rough is fine.\n\nAnd the part I nearly left implicit: this is the clearest proposal anyone has brought me this quarter and I want you to own it end to end.\"\n\nNo content changed. What was added is a sentence stating the verdict and a sentence stating the attitude, both in a form that admits one reading.",
  experiment: "Take a message you sent this week that contained both approval and a concern, and read it as though you were the recipient waiting on an answer. Then find the sentence that states the approval. If there is not one, you have located a habit rather than an incident.",
  reflection: "What did you approve this week without ever writing down that you approved it?",
  recall: {
    q: "Why can you not evaluate the tone of your own message, and what does the reader put in its place?",
    a: "Because you produced the intention before the sentence, so the tone is in your head before your eyes reach the words and you cannot read it without already knowing what it meant. The reader has only the sentence and fills the gap with whatever their situation suggests, which for somebody awaiting a verdict on their own work is not the generous reading."
  },
  deepDive: "Here is a message containing both approval and concerns. Tell me whether the approval is actually stated anywhere, and rewrite it so it cannot be missed."
},
{
  id: "reads-the-seven-per-cent-myth",
  track: "reads", level: "broadcast",
  title: "The claim that words are seven per cent of communication is about neither words nor communication",
  source: "Albert Mehrabian's 1967 experiments on inferring liking from tone, and what was done with them afterwards",
  gateIntro: "You are deciding whether to deliver a difficult reorganisation message in writing or to wait nine days until you can do it in person. Half the affected team is remote and will receive it on a video call either way.\n\nSomebody senior tells you in a corridor that this has to be face to face, because only seven per cent of communication is the words, and you should not put something like this in writing.\n\nNine days is a long time in a team that has already started guessing.",
  gatePrompt: "Write what happens inside that team over the nine days, and what they conclude when the message finally arrives.",
  evidence: "Mehrabian ran two small studies in 1967. One asked listeners to judge the attitude conveyed by a single word spoken in different tones. The other set recorded words against photographs. Combining them produced the 7-38-55 split, which describes the relative weight of word, tone and expression when a listener is inferring liking from a deliberately inconsistent single-word stimulus. It was never a finding about communication in general, and Mehrabian has said so publicly and repeatedly for decades. The experiments are real, small, and not much replicated, largely because almost nobody claims the thing they actually showed.",
  replication: "overclaimed",
  idea: "Choose the channel on what the message has to accomplish rather than on a statistic about tone, because the figure everybody quotes measured something else and the real trade is between precision and presence.",
  why: "The number is real and it measures something almost nobody who cites it intends. Two small studies asked listeners to infer whether a speaker liked them, from a single word delivered in a tone that contradicted it, and under those conditions the tone dominated. That is the entire finding. It does not establish that words carry seven per cent of meaning, it does not generalise past inferences about liking, and it says nothing whatsoever about how to deliver a reorganisation. The author has spent decades correcting this to no effect, which is worth noticing on its own: a claim that is useful to believe survives correction.\n\nWhat you actually face is a trade with real terms on both sides. Writing is precise, identical for everybody, rereadable, and cannot be softened afterwards into something that was not said. Speaking is present, allows questions, and lets a room see that somebody was prepared to stand in front of them. Neither of those is a percentage. Nine days of silence is also a message, delivered continuously, and it is the only one in this situation that nobody controls.\n\nThe usual answer for something of this kind is both, in a specific order. Written first, so the facts are identical for everybody including the people on leave, then live for the questions, and never live-only for anything somebody will need to reread.",
  failureMode: "You wait the nine days. By the time you speak, a version assembled from fragments has been circulating for a week, three people have taken calls with recruiters, and your accurate account arrives as a correction to a rumour rather than as news. That is a much weaker position and you chose it.",
  worked: "The channel decision, written down where somebody can argue with it.\n\n\"I am putting the reorganisation detail in writing on Tuesday morning and holding a call at four the same day.\n\nWhy that order: everybody needs the same facts at the same time, including the people who are remote and the two on leave, and a written version is the only way to achieve that. It can also be reread, which matters for anything that affects somebody's job. The call is for questions and for the parts a document should not be answering.\n\nWhat I am not doing is waiting nine days to say it in a room. Nine days of people knowing something is coming and not knowing what does more damage than the message will.\"\n\nThe decision is now defended on what the message has to accomplish, which also makes it something the corridor advice can be argued against with.",
  experiment: "The next time somebody cites a communication statistic at you, ask what it was measuring. Not to win the exchange, but because you will find you cannot answer the same question about two or three of the numbers you carry around yourself.",
  reflection: "What have you delayed saying because it felt like something that had to be said in person?",
  recall: {
    q: "What did the 7-38-55 studies actually measure, and what is the real trade when choosing a channel for difficult news?",
    a: "They measured how listeners infer liking from a single word delivered in a contradicting tone, across two small 1967 studies, which says nothing about communication generally. The real trade is that writing is precise, identical for everybody and rereadable, while speaking is present and allows questions, and that silence while you wait for a room is itself a continuous message nobody controls."
  },
  deepDive: "I have difficult news to deliver and I am deciding between writing it and saying it. Help me work out what the message has to accomplish and choose the channel from that."
},
{
  id: "reads-brevity-from-above",
  track: "reads", level: "reply",
  title: "A short answer from somebody senior is read as displeasure",
  source: "Craft, and the observation that length is taken as a proxy for attention",
  gateIntro: "You are a director. An engineer sent you a detailed proposal at eleven at night and you are reading it on your phone at six the next morning, between two other things.\n\nYou think it is fine. Your reply, sent from the phone, reads: \"Looks good.\"\n\nIt took four seconds and you meant it as approval.",
  gatePrompt: "Write what this engineer concludes from two words in reply to eleven paragraphs, and what they do with the proposal.",
  evidence: "No study. The inference from length to attention is an ordinary conversational heuristic and it is usually reliable, which is what makes it hard to suspend. The claim that it breaks asymmetrically across a power gradient is craft, defended here by the observation that the reader cannot resolve the ambiguity by asking, and measured by nobody.",
  replication: "craft",
  cheat: "If the reply is short and the thing was not, say why it is short. Approved, on my phone, more on Thursday costs nothing.",
  idea: "Match the length of a reply to the stakes for the reader rather than to the effort the answer took you, or say explicitly that the brevity is circumstantial.",
  why: "Length is read as attention, and attention is read as regard. That inference is usually sound, which is why it is difficult to switch off: somebody who cares about a thing does tend to write more about it. When it breaks, it breaks asymmetrically. Two words from a peer are two words. Two words from somebody who controls your work carry a signal, because the reader cannot distinguish approval from dismissal and has every reason to check.\n\nSeniority is the aggravating factor because the reader cannot ask. Requesting clarification of a two-word approval means admitting you read something into it, which is itself a small exposure, so the interpretation stays private and unresolved. They will show it to a colleague and ask what they think it means, and two people will now spend fifteen minutes on a message that took four seconds.\n\nThe fix is not writing long replies. It is spending one clause on the thing brevity destroyed, which is the reason for it.",
  failureMode: "The proposal does not move. They read the reply as permission without enthusiasm, conclude the political risk of proceeding sits with them, and wait for a second signal you have no reason to send, because from where you sit the matter was settled at six in the morning.",
  worked: "\"Approved. Go ahead and start.\n\nWriting this on my phone, so it is short for that reason and no other. I read the whole thing and the partitioning argument is the part that convinced me.\n\nI will send proper comments on Thursday. Do not wait for them, they will be details rather than objections.\"\n\nThree sentences, still under twenty seconds. It states the decision, explains the brevity, proves the document was read, and removes the reason to wait.",
  experiment: "For a week, whenever you send a reply of under ten words to something somebody worked on, add a clause explaining why it is short. Then count how many you sent, because the count is a better measure of the problem than any individual message.",
  reflection: "What did you approve in under five words, and did it move?",
  recall: {
    q: "Why does brevity from a senior person read differently than the same brevity from a peer, and why does the reader not simply ask?",
    a: "Because length reads as attention and attention as regard, and from somebody who controls your work the ambiguity between approval and dismissal is worth resolving. They do not ask because requesting clarification of a two-word approval means admitting they read something into it, so the interpretation stays private and gets settled with a colleague instead."
  },
  deepDive: "Here is a short reply I am about to send to something somebody spent real time on. Tell me how it reads and what one clause would fix it."
},
{
  id: "reads-bad-is-stronger-than-good",
  track: "reads", level: "reply",
  title: "The one critical line is the message, whatever else is in it",
  source: "Baumeister, Bratslavsky, Finkenauer and Vohs, Bad is stronger than good",
  gateIntro: "You are reviewing a colleague's document and your comments run to eleven notes. Nine are minor, one is a genuine compliment about the risk section, and one says the cost model assumes linear scaling and will be out by roughly an order of magnitude at their target volume.\n\nYou spent about the same time on each. In your head this is a positive review with one substantive issue in it.",
  gatePrompt: "Write what this colleague says the review was, a week later, when somebody asks how it went.",
  evidence: "The asymmetry is one of the better-supported generalisations in social psychology. Baumeister and colleagues assembled evidence across impression formation, memory, learning, relationships and emotion, and Rozin and Royzman made the parallel case for negativity dominance in the same year. It reproduces across many domains and methods, which is what makes it credible. That breadth is also its limitation as a citation: it is a review across literatures rather than one effect with one size, so it supports the direction robustly and supports no particular ratio at all.",
  replication: "replicated",
  idea: "Assume the critical line is what the message delivered and everything else was packaging, and if that is not the balance you intended, state the balance rather than distributing it across the notes.",
  why: "Negative information carries more weight than positive information of comparable size, consistently, across impression formation and memory and learning. This is one of the better-supported generalisations available, though it is a pattern assembled from many literatures rather than a single measured effect, so it supports a direction and no particular ratio. The direction is enough. Eleven notes containing one serious criticism is not received as a document with one problem. It is received as a criticism, with ten pieces of packaging around it.\n\nThe practical consequence is that you cannot fix this by adjusting proportions. Adding more positive notes does not dilute the negative one, it only makes the message longer, and the reader still leaves holding the criticism. What works is stating the verdict outright, because the verdict is the one thing a reader cannot reconstruct from the notes: the difference between this is nearly there and one thing has to change, and this has a problem serious enough that I am not sure about it, is encoded nowhere in eleven individual comments.\n\nWriting the verdict also forces you to have one. Reviewers frequently discover, at the moment of composing that sentence, that they do not actually know whether they think the document is good.",
  failureMode: "They rewrite the whole thing. You get back a substantially different document that has also addressed nine trivial notes and lost the section you praised, and you will read that as an overreaction rather than as the reasonable response to a review that never said what it thought.",
  worked: "\"Summary before the notes: this is good and I think it ships, with one thing that has to change first. The other ten notes are optional.\n\nThe one that matters: the cost model assumes linear scaling and it will not be linear at your target volume. My guess is it is out by roughly an order of magnitude at the top end. That has to be redone before anybody plans against these numbers, and I am happy to sit down and go through it.\n\nThe risk section is the best I have read on this system and I would not change a line of it.\n\nThe remaining nine notes are in the document and are all minor. Take them or leave them.\"\n\nEleven notes, unchanged. What was added is a verdict, which is the one thing the notes cannot carry between them.",
  experiment: "Before sending your next review, write the one-sentence verdict first and check the notes against it. Where they disagree, either the notes are right and the verdict was a courtesy, or the verdict is right and you have been distributing an opinion across comments instead of stating it.",
  reflection: "What review did you send that got a bigger reaction than you expected?",
  recall: {
    q: "Why does adding more positive comments fail to balance a review, and what is the only thing that can?",
    a: "Because negative information outweighs positive information of comparable size, so extra positive notes lengthen the message without changing what the reader leaves holding. Only a stated verdict works, since the difference between nearly there with one fix and serious enough that I am unsure is not encoded anywhere in the individual notes."
  },
  deepDive: "Here is a set of review comments. Help me write the one-sentence verdict, and tell me whether the comments are consistent with it."
},
{
  id: "reads-silence-is-read",
  track: "reads", level: "reply",
  title: "Not replying is a reply, and you do not choose what it says",
  source: "Craft, and the observation that an unanswered message is interpreted continuously rather than held in suspense",
  gateIntro: "On Tuesday a product manager sent you a long message making the case for reprioritising the quarter. It is thoughtful, and you need two or three days to think about it properly and to talk to two people first.\n\nIt is now Friday. You have not replied, because you do not have an answer yet and a holding message felt like noise.\n\nThey have seen you post in three other channels since Tuesday.",
  gatePrompt: "Write what this person concludes by Friday afternoon about what you think of their proposal, and about them.",
  evidence: "No study, and the quantity of interest is not observable: what would need measuring is an interpretation the sender never states and never raises. What can be said is that the charitable explanation is the one that decays under evidence of you being active elsewhere, which is a matter of ordinary inference rather than psychology. Everything past that is craft.",
  replication: "craft",
  cheat: "Send the holding reply with a date on it. A holding message without a date is a second silence in a polite envelope.",
  idea: "Send the holding reply and put a date in it, because silence gets interpreted continuously and the interpretation worsens the longer it runs while staying entirely invisible to you.",
  why: "An unanswered message does not sit in a neutral state. The sender checks, finds nothing, and constructs an explanation, and they repeat this over days with each pass reinforcing the one before. The available explanations are not evenly weighted: you are busy, you did not think it worth answering, or you disagree and are avoiding saying so. The first is the charitable one and it decays fastest, because evidence accumulates against it every time they see you active somewhere else.\n\nWhat separates this from other misreads is that the sender knows you may simply be busy, so they do not raise it, so it never gets corrected. They also cannot chase without appearing impatient about something you have not actually refused. The interpretation therefore runs unopposed for exactly as long as the silence does, and the first thing you will notice is a change in what they bring you.\n\nA holding message costs one line and removes the whole ambiguity, provided it carries a date. Without one it is a second silence with a courteous opening on it, and it postpones the identical problem by a week.",
  failureMode: "You reply properly on Monday with a considered answer, and it lands on somebody who has spent five days concluding you were not interested. They will be gracious about it. What changes is that the next proposal of that kind goes to somebody else first.",
  worked: "Sent on Tuesday afternoon, two minutes after reading it.\n\n\"I have read this properly and I am not going to answer it today, because it deserves more than a quick reaction and I want to talk to Ana and Dev first.\n\nMy initial view, so you are not guessing all week: I think the argument about ingest sequencing is right and I am not yet convinced by the headcount half. That is a first impression rather than a position.\n\nYou will have a real answer from me by Friday.\"\n\nThree sentences on Tuesday, replacing four days of silence. The date is the part doing the work, and the first impression is what stops the holding message from being a slower version of the same silence.",
  experiment: "Go through your inbox for anything unanswered for more than three days that somebody put real effort into, and send each a holding reply with a date, now. The discomfort of doing this is a fair measure of how long the silence had already been saying something.",
  reflection: "What is sitting unanswered right now that somebody worked on?",
  recall: {
    q: "Why does an unanswered message get worse rather than staying neutral, and why does the sender not raise it?",
    a: "Because the sender checks repeatedly and builds an explanation each time, and the charitable one decays fastest as they see you active elsewhere. They do not raise it because you may genuinely be busy and they cannot chase without appearing impatient about something you have not refused, so the interpretation runs unopposed and surfaces later as a change in what they bring you."
  },
  deepDive: "Here is a message I have not answered for several days and do not yet have an answer to. Help me write the holding reply."
}
);
