/* Track: After it lands. Ordered foundational first.
 *
 * The half nobody practises. Everything before this track is about drafting;
 * this one is about the only feedback channel that exists, which is the reply,
 * and about what you owe once the message has done whatever it did. The
 * diagnostic entry carries no cheatsheet row on purpose: working out which of
 * four things went wrong is not something you do mid-draft. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "after-read-the-reply-for-the-misread",
  track: "after", level: "reply",
  title: "The reply is the only instrument you have for what they actually heard",
  source: "Craft, and the observation that a restatement is a measurement",
  gateIntro: "You sent a message on Monday explaining that your team will be taking on the connector work, and that you want the existing owner to stay involved as the reviewer rather than hand it over entirely.\n\nThe reply came back: \"Understood, I'll get the handover doc together this week and make sure everything is documented before I step away.\"\n\nIt is a cooperative, positive reply. You are about to send a thumbs up.",
  gatePrompt: "Write what this person believes is happening to their involvement, and where in your original message they got it.",
  evidence: "No study. That a reply contains a restatement and that the restatement is informative is a property of how people answer messages rather than a finding, and the specific claim, that agreeable replies conceal misreads better than disagreeable ones do, follows from disagreement being legible. It has not been measured and the measurement would be difficult, since the cases of interest are the ones nobody noticed.",
  replication: "craft",
  cheat: "Read replies for the words they introduced rather than for whether they agreed. A translation is where the reading lives.",
  idea: "Read every reply for what it reveals about the reading rather than for whether they agreed, because the reply is the only observation you will ever get of what your message actually did.",
  why: "You cannot see a misread directly. The single channel through which it becomes visible is the reply, and replies are almost always scanned for the wrong thing: whether the person agreed, whether they are annoyed, whether anything needs doing. Underneath all of that, every reply contains a restatement, and the restatement is a measurement of what arrived.\n\nThe agreeable reply is the dangerous one. Disagreement is legible, so a misread that produces an objection gets caught on the spot, and the cases that survive are the ones where the reader misunderstood you and then cooperated enthusiastically with the misunderstanding. The enthusiasm is what stops you looking.\n\nThe habit worth building is to read a substantive reply twice: once for content, once for vocabulary. The second pass asks one question, which is which words describing the situation are theirs rather than mine. A word the reader introduced is either a synonym or a translation, and the translations are where the reading lives.",
  failureMode: "They write the handover document, hand it over, and disengage. Two months later the connector work has a problem only they would have caught, and you discover that the reviewer arrangement you thought you had set up was never in place. Nobody disagreed with anything at any point.",
  worked: "\"Stop before you write the handover doc, because I have not been clear and I would rather fix it now than in a month.\n\nYou are not stepping away. My team takes the implementation and you stay on as the reviewer, which means you are in the design review and you approve the changes. That is the arrangement rather than a transition to something else.\n\nRereading what I sent on Monday: I said we would be taking on the connector work and then put the reviewer part in the third paragraph, and taking on reads as taking over. That is on me.\n\nWhat I actually need from you this week is a list of the things you would want a reviewer watching for, which is a much shorter document than a handover.\"\n\nThe correction names where in the original the misread came from, which is what stops it reading as a change of plan.",
  experiment: "For a fortnight, read every substantive reply twice, marking on the second pass every word describing the situation that you did not use yourself. Most replies contain one or two and most are harmless. The exercise earns its cost on the ones that are not.",
  reflection: "What reply did you accept this week that restated your message in words you had not used?",
  recall: {
    q: "Why is an agreeable reply more dangerous than a disagreeable one, and what should the second read of a reply look for?",
    a: "Because disagreement is legible and catches a misread immediately, so the ones that survive are those where the reader misunderstood and cooperated enthusiastically, and the enthusiasm stops you looking. The second read looks for words describing the situation that you did not use, since a word the reader introduced is either a synonym or a translation, and the translation is the reading."
  },
  deepDive: "Here is a message I sent and the reply I got. Tell me what words they introduced and what those words say about how it was read."
},
{
  id: "after-correcting-without-relitigating",
  track: "after", level: "reply",
  title: "Correct the reading without reopening the argument",
  source: "Craft, and the observation that length in a shared channel is read as defensiveness",
  gateIntro: "You told a partner team last week that you would not take on the connector reliability work this quarter, and you explained the ranking behind it.\n\nToday somebody from that team has written in a shared channel: \"Since platform isn't able to help with connector reliability, we're going to have to descope the Q3 integration.\"\n\nThe ranking was a decision. Not able to is not what you said, and the sentence is now in a channel with forty people in it.",
  gatePrompt: "Write what happens if you reply with a full restatement of the prioritisation reasoning.",
  evidence: "No study. The distinction between correcting a description and defending a decision is a matter of what each response does rather than a psychological claim. The reading of length as defensiveness in a public thread is craft, reported widely enough to be conventional wisdom and never isolated, and it is confounded with the ordinary fact that longer replies tend to come from people who feel more strongly.",
  replication: "craft",
  cheat: "Fix the wrong clause, restate the decision once without arguing for it, and offer somewhere else for the argument to go.",
  idea: "Correct the specific clause that is wrong and stop, because a correction that re-argues the underlying decision is received as reopening it and invites everybody to have the original conversation again in public.",
  why: "A misread and a disagreement need different responses, and they are easy to confuse because they arrive inside the same sentence. Not able to is a factual error about what you said and takes one clause to fix. The ranking underneath it is a decision, and it is not what has gone wrong here. Restating the whole argument treats the misread as though it were a challenge, which converts a two-line correction into a public negotiation.\n\nThe forty people are why this matters. In a shared channel, length is read as defensiveness, and a long reply to a single incorrect clause suggests the writer feels exposed on the larger point. It also gives everybody else a surface to attach to: a paragraph of reasoning invites replies to the reasoning, and the thread you are now in is about whether the decision was right rather than about what you actually said.\n\nThe discipline is to fix the clause, restate the decision in one sentence without arguing for it, and give the argument somewhere else to go. The last part is what keeps a short reply from reading as a brush-off.",
  failureMode: "You post four paragraphs of prioritisation reasoning. Two people reply questioning the ranking, somebody senior asks for context, and you spend a day defending a decision that nobody had challenged until you defended it.",
  worked: "\"One correction: it is not that we are unable to. We ranked it below the ingest reliability work for this quarter. That was a decision and I stand behind it.\n\nOn the descope, that is your call and I am not going to argue with it. If the four days on the retry path I offered last week would change the picture, that offer is still open.\n\nIf anybody wants to argue about the ranking itself, that is a fair conversation and I would rather have it properly than in this thread. Ana owns both sides of it and I am happy to set it up.\"\n\nThree short paragraphs. The clause is corrected, the decision is restated once with no case attached, the practical offer is repeated, and the argument is given somewhere else to be.",
  experiment: "The next time somebody restates your position incorrectly in public, write the reply you want to send, then delete every sentence that argues for the decision rather than correcting the description. Send what remains and see whether anything you cut turns out to have been needed.",
  reflection: "What did you over-explain in public that nobody had actually challenged?",
  recall: {
    q: "Why does re-arguing a decision in response to a misread make things worse, and what does length signal in a shared channel?",
    a: "Because a misread is a factual error needing one clause while the decision is not what went wrong, so restating the argument treats the error as a challenge and turns a correction into a public negotiation. In a shared channel length reads as defensiveness, and a paragraph of reasoning gives everybody a surface to attach replies to."
  },
  deepDive: "Somebody restated my position incorrectly in a public channel. Help me correct the clause without reopening the decision."
},
{
  id: "after-the-return-you-promised",
  track: "after", level: "reply",
  title: "The unclosed loop costs more than the answer would have",
  source: "Craft, and the observation that a reporter can observe your silence and cannot observe your fix",
  gateIntro: "Six weeks ago you told a support lead you would go deep on four tenant cost anomalies they reported, and that you would come back to them.\n\nYou did go deep. It turned out to be one cause rather than four, the fix shipped a fortnight ago, and you never sent the message, because by the time it was done it felt like old news.\n\nThey have not asked.",
  gatePrompt: "Write what this person has concluded about what happened to their report, and what they do with the next one.",
  evidence: "No study, and what would need measuring is reports that were never sent, which is not observable. The asymmetry the entry rests on needs no evidence: the fix is invisible to the reporter and the silence is not, so silence is the only signal they have. Everything about what that does to future reporting is craft and is consistent with the general voice literature without being established by it.",
  replication: "craft",
  cheat: "Send the return even when it is late and stale. The reporter can observe your silence and cannot observe your fix.",
  idea: "Send the return you promised even when it is late and no longer news, because the loop is what the reporter is actually tracking and a fix landing in silence reads as the report having gone nowhere.",
  why: "The person who reported something is not tracking the fix. They cannot see it. What they are tracking is whether reporting produces an outcome, and the only observation available to them is whether you came back. A fix that ships in silence is, from where they sit, indistinguishable from nothing having happened, and the silence is more informative to them than the fix would have been, because the silence is the part they can actually observe.\n\nWhat keeps the loop open is that closing it feels pointless once the work is done. The problem is solved, the news is stale, and a message about it now looks like taking credit for something nobody asked about. That reasoning is entirely about you. The message is not for you, and its content is not really the fix. It is the demonstration that a report from that person reaches a conclusion, which is what determines whether the next one gets sent.\n\nLate is also fine and much better than never. A return that opens by acknowledging it is late costs nothing and is more credible than a prompt one, because it shows the loop was tracked rather than merely convenient.",
  failureMode: "The next anomaly they spot does not come to you. It goes into their own backlog or nowhere, and you lose the exact input you told them was valuable. You will not see this happen and you will not attribute the quiet to anything.",
  worked: "\"Closing the loop on the four tenant anomalies you sent in June. This is late and I should have sent it two weeks ago when the fix went out.\n\nWhat it turned out to be: one cause, not four. All four were hitting the same unbounded query on the audit path, which only appears for tenants above a certain object count, which is why it looked tenant-specific. Yours were the first four to cross that line.\n\nWhat happened: fix shipped on the 14th. Cost on those four is back to roughly where it was in April, and the same fix removes the problem for about thirty other tenants before they reach it.\n\nWhat I want you to take from this: your report is what made it findable. Four instances across four tenants is what turned an oddity into a pattern, and none of us would have got there from one. Please keep sending them.\"\n\nThe last paragraph is the actual message. Everything above it is the evidence that makes it credible.",
  experiment: "List everything you said you would come back to somebody about in the last quarter and check whether you did. Send the outstanding ones today, however stale, and note how many there were, because the count is the finding rather than any individual lapse.",
  reflection: "What did you promise to come back on and never close?",
  recall: {
    q: "Why is a fix that ships in silence worse than no fix from the reporter's point of view, and why does staleness not excuse the return?",
    a: "Because the reporter cannot observe the fix and can observe the silence, so what they are tracking is whether reporting produces an outcome, and a silent fix is indistinguishable from nothing happening. Staleness is no excuse because the message is not about the fix, it is the demonstration that a report from that person reaches a conclusion, which decides whether the next one is sent."
  },
  deepDive: "Here is something I promised to come back on and never did. Help me write the late return without making the lateness the subject."
},
{
  id: "after-the-message-that-failed",
  track: "after", level: "broadcast",
  title: "When a message does not land, diagnose it rather than sending it again louder",
  source: "Craft, and the four places a message can fail between sending and acting",
  gateIntro: "You announced the new deployment process three weeks ago in a channel post. It was clear, it was complete, and about a third of deploys are still going through the old path.\n\nYour draft is a second announcement. It says much the same thing with a bolder opening and a line noting that this was already communicated on the 3rd.\n\nYou are fairly annoyed.",
  gatePrompt: "Write what the people still on the old path take away from a second announcement that mentions the first one.",
  evidence: "No study. The four-way split is a taxonomy rather than a finding, offered because it is exhaustive enough to be useful and because each branch has a different repair. What can be said is that resending addresses only one of the four, which is arithmetic rather than psychology, and that the accusatory line closes the channel through which the fourth would have been reported, which is craft.",
  replication: "craft",
  idea: "Work out which of the four failure points the message hit before resending anything, because a second attempt repairs only one of them and a reference to the first attempt makes two of them worse.",
  why: "A message that produced no change failed at one of four places, and they need different repairs. It was not seen, which is a channel and timing problem. It was seen and not read, which is an opening problem. It was read and not understood as applying to the reader, which is the category-versus-name problem. Or it was read, understood and not acted on, which means the action is harder than you think or something else is blocking it. Resending repairs only the first.\n\nPointing out that you said it three weeks ago does damage of its own. It converts an information problem into an accusation, and everybody who genuinely did not see it, which is most of them, now knows you believe they ignored you. It also tells anybody blocked by a real obstacle that reporting the obstacle will be received as an excuse, which closes the one channel through which you would have discovered what is actually wrong.\n\nThe cheapest diagnostic is to ask three people still on the old path what happened, individually, with no implication that they were at fault. In practice the answer is usually the fourth failure: the new path does not work for some case you did not know about, and the message was fine all along.",
  failureMode: "You send the second announcement. Old-path deploys drop slightly and then recover, and you conclude the team is resistant to change. The actual cause is that the new path does not support the one service that deploys most often, and the person who knows this has decided that saying so now would sound like an excuse.",
  worked: "\"Three weeks in and about a third of deploys are still on the old path, so something about my announcement or about the new path is not working. I would rather find out which.\n\nI am not asking anybody to switch today. I am asking three questions of anybody still on the old one: did you see the post on the 3rd, did it read as applying to your service, and did you try the new path and hit something.\n\nIf it is the third, please tell me what you hit. That is the most useful answer and the one I am least likely to hear, because it sounds like an excuse and it is not.\n\nI will follow up individually rather than in this thread if that is easier.\"\n\nThe second message is not a second announcement. It is an instrument for finding out which of the four things went wrong, and it explicitly protects the answer that is hardest to give.",
  experiment: "Find a message you sent that did not produce the change you wanted, and ask three recipients individually what happened, asking about the message rather than about their behaviour. You are looking for which of the four failure points it was, and one conversation will usually settle it.",
  reflection: "What did you announce that did not change anything, and did you ever find out why?",
  recall: {
    q: "What are the four places a message can fail, and what does referencing the first attempt cost you?",
    a: "Not seen, seen but not read, read but not understood as applying to the reader, or read and understood but blocked by something. Referencing the first attempt converts an information problem into an accusation and tells anybody with a real obstacle that reporting it will sound like an excuse, which closes the one channel that would have told you the cause."
  },
  deepDive: "Here is a message that did not produce the change I wanted. Help me work out which of the four failure points it hit before I resend anything."
},
{
  id: "after-changing-your-mind-in-public",
  track: "after", level: "record",
  title: "Say you were wrong in the same place you were confident",
  source: "Craft, and the observation that a public claim and a private correction are not symmetric",
  gateIntro: "Two months ago you argued in a design forum, at length and in writing, that the event schema should be denormalised. You won the argument and the team built it that way.\n\nIt has gone badly. The join you eliminated has reappeared in five places, and the migration cost you predicted for the alternative would have been paid back by now.\n\nYou have mentioned this to two people individually. The forum thread is still there and still says what you said.",
  gatePrompt: "Write what somebody who disagreed with you at the time now believes about whether it is worth disagreeing with you again.",
  evidence: "No study. The asymmetry is structural rather than psychological: a public claim reaches everybody who reads the thread and a private correction reaches whoever you happened to talk to, so the record retains the confident version. What the silence teaches the people who were right is craft, consistent with the voice literature on whether speaking up appears to change anything, and not established by it.",
  replication: "craft",
  cheat: "Post the correction in the thread where you were confident, at comparable length, and name whoever was right.",
  idea: "Post the correction in the same place and at the same weight as the original claim and name whoever argued the other side, because a confident position corrected privately leaves the confident version as the only public record.",
  why: "Two things are at stake and only one of them is the schema. The first is the record: the thread is what a new engineer reads in six months, and it currently holds a strong argument for a decision that did not work, unqualified. The second is what happened to the people who took the other side. They were right, in public, against somebody who prevailed, and nothing has been said about it. What they learn from the silence is a fair estimate of what disagreement is worth here.\n\nCorrections happen privately because private is cheaper and feels sufficient. You told two people, you have updated your own view, and the practical consequence is being handled. But the confidence was public and the correction was not, so the asymmetry runs in the direction that protects you: the strong claim reached everybody and the revision reached whoever you happened to talk to.\n\nMatching the venue and the weight is the whole move. A one-line note under a four-paragraph argument reads as a technicality. A correction of comparable weight, naming who was right, is the only version that changes what the thread teaches.",
  failureMode: "The next design forum gets less argument rather than more. The people who were right last time are still there and still competent, and have concluded that winning on the merits produces no visible outcome, so they say the thing once and let it go. That is precisely the failure the forum exists to prevent.",
  worked: "Posted in the original thread rather than in a new one.\n\n\"I was wrong about this and I want to say so here rather than in the hallway, since here is where I argued it.\n\nWhat I claimed in August: that denormalising the event schema would remove the join, and that the migration cost of the normalised version would not pay back inside a year.\n\nWhat happened: the join is back in five places, because the cases I treated as edge cases were not edge cases. On the second point I was wrong about the arithmetic rather than the principle, and the payback would have landed around now.\n\nPriya and Dev both argued the other side in this thread in August and both were right, including about the specific reason, which was the multi-tenant read path.\n\nWhat I am doing about it: proposing we normalise in Q1, and I will write that up. I am not asking anybody to relitigate the original decision. It was made and it was mine.\"\n\nThe naming is the part that costs something and the part that does the work.",
  experiment: "Find a position you argued publicly in the last year that turned out to be wrong, and check where your revision currently lives. If it is in your head or in two conversations, the correction has not been made yet, whatever you believe about your own openness.",
  reflection: "What did you argue for in writing that turned out to be wrong, and where does the correction live?",
  recall: {
    q: "Why is a private correction of a public claim insufficient, and what specifically has to be matched?",
    a: "Because the confident version remains the public record while the revision reaches only the people you happened to tell, so the asymmetry runs in the direction that protects you. The venue and the weight have to be matched and whoever argued the other side has to be named, otherwise the thread teaches that being right in a disagreement produces no visible outcome."
  },
  deepDive: "I argued something publicly that turned out to be wrong. Help me write the correction in the same thread, and make sure I name whoever was right."
}
);
