/* Track: Retry and amplification. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "retry-jitter-not-backoff",
  track: "retry", level: "mechanism",
  title: "Backoff without jitter re-synchronises the clients it was meant to spread",
  source: "Marc Brooker, Exponential Backoff And Jitter, AWS Architecture Blog (2015)",
  gateIntro: "A few hundred clients share one dependency. The dependency has a brief capacity dip and effectively every client fails inside the same second. Every client is running the vendor SDK on default settings, with a bounded attempt count that no client exceeds. Over the following minutes the dependency does not see a smooth ramp of returning load. It sees a short tall arrival spike, then quiet, then another spike roughly twice as far out as the last, each one large enough to push it back over its limit. Time to drain the backlog is many times longer than the original dip.",
  cheat: "Backoff spreads nothing on its own - add full jitter, a delay uniform between zero and the current cap, at every shared retry site.",
  idea: "It is the randomisation and not the doubling that spreads retry load, because clients that failed together stay in phase through every doubling of a pure exponential delay.",
  why: "Exponential backoff reduces the rate at which one client retries. It does nothing to the correlation between clients. If a thousand callers fail at t=0 and all wait 1s, then 2s, then 4s, they arrive together at t=1, t=3, t=7. The peak the dependency has to survive is unchanged, it just happens less often, and each peak is capable of re-triggering the failure that created the correlation in the first place. The system converges on a stable oscillation instead of recovering.\n\nBrooker's simulation of contending clients is the useful part: adding full jitter, where the delay is uniform between zero and the current cap, cut both total work done and time to completion substantially against pure exponential backoff. The counterintuitive result is that randomising downward, sometimes retrying sooner than the backoff would allow, reduces total load, because it converts a spike into a rate.",
  failureMode: "A cache tier restarts. Every application pod fails its first read, backs off identically, and hammers the cold cache in synchronised waves. Each wave times out, so each wave doubles, so the interval grows but the amplitude does not, and the tier never gets a quiet window long enough to warm. Someone eventually fixes it by scaling application pods down, which is the only lever that actually reduces peak concurrency.",
  experiment: "Grep every Go and Python service for its retry construction and add a jitter column. In Go, code using cenkalti/backoff via NewExponentialBackOff gets a 0.5 randomisation factor for free, but code that builds the struct literally, or hand-rolls a loop with time.Sleep of a doubling duration, gets none. In Python, tenacity wait_exponential has no jitter while wait_random_exponential and wait_exponential_jitter do. Output is one row per retry site with yes or no. Count the no rows.",
  reflection: "Which of your retry sites are shared by enough callers that correlated failure is the normal case rather than the exception?",
  recall: {
    q: "A thousand clients fail simultaneously and all use capped exponential backoff with no randomisation. What happens to the peak load the dependency must survive, and why does adding jitter reduce total work rather than just moving it?",
    a: "The peak is unchanged. Backoff reduces each client's rate but not the correlation between clients, so the fleet arrives in synchronised waves at t=1, 3, 7 and each wave is as tall as the first. Jitter spreads arrivals into a rate rather than a spike, so more attempts succeed on the first try, which means fewer total attempts and a shorter time to drain."
  },
  deepDive: "Help me audit the retry construction across my Go and Python services and rank the sites where correlated client failure makes missing jitter most dangerous."
},
{
  id: "retry-layer-multiplication",
  track: "retry", level: "mechanism",
  title: "Three tiers retrying three times each is twenty-seven requests at the bottom",
  source: "Mike Ulrich, Addressing Cascading Failures, Google SRE book chapter 22",
  gateIntro: "A user-facing path crosses three internal services. The bottom service has a partial failure affecting a minority of its requests. Within a minute its inbound request rate is more than an order of magnitude above baseline while the edge is measuring flat, unchanged user traffic. Each of the three teams checks its own configuration and finds it conservative: a small attempt count, well under the number the internal guidance recommends. Nobody's service is misconfigured by its own measure, and none of the three can explain the load from the numbers on their own dashboard.",
  idea: "Retry counts multiply down the call stack rather than adding, so the only safe design is to retry at exactly one layer and make every layer above it fail fast.",
  why: "Each layer sees a failure from the layer below and issues its own attempts. Three attempts at the edge, each of which triggers three attempts at the middle tier, each of which triggers three at the bottom, is twenty-seven requests to the bottom service for one user action. Each individual policy looks reasonable in its own code review. The product is not visible anywhere, because no single service can see the whole stack.\n\nThe SRE book's prescription is a retry budget expressed as a fraction of the request rate, plus a rule that only the layer closest to the failure retries. Everything above it either propagates the error or, better, propagates a signal that says do not retry this, I already did. The cheapest version of that is a response header or gRPC trailer that upper layers are required to honour.",
  failureMode: "Your ingress retries a 503. The Go service behind it retries once through its HTTP client, which was configured for a different purpose two years ago. The Temporal activity wrapping the call has an unlimited retry policy. One workflow start becomes a sustained stream against the tenant-config service, and the graph that shows it lives in a namespace none of the three owners look at.",
  experiment: "Take your busiest user-facing path and write the layers down in order: ingress, gateway, service, client library, activity policy. Put the maximum attempts for each next to it and multiply. Do the same for the underlying HTTP client, which usually retries too and is usually forgotten. The output is one integer. If it is above about three, you have found the entry.",
  reflection: "In your top path, which single layer should own the retry, and what has to change in every layer above it to make that true?",
  recall: {
    q: "Why can every team in a three-tier stack have a conservative retry policy and still produce an order-of-magnitude amplification, and what is the structural fix?",
    a: "Retries compose multiplicatively, not additively: three attempts at each of three layers is twenty-seven requests at the bottom, and no single service can observe the product. The fix is to retry at exactly one layer, normally the one closest to the failure, and have every layer above it fail fast on a non-retryable signal, with a fleet-level budget rather than a per-request count."
  },
  deepDive: "Walk my top three request paths layer by layer and compute the true multiplied attempt count, including the HTTP clients and Temporal activity policies."
},
{
  id: "retry-timeout-too-tight",
  track: "retry", level: "mechanism",
  title: "The retry is correct and the timeout is wrong",
  source: "Marc Brooker, Timeouts, retries, and backoff with jitter, Amazon Builders' Library",
  gateIntro: "A service reports itself healthy. Server-side success rate is above 99.9 percent and the server-side latency histogram has not changed shape in a month. Clients report widespread failure. As offered load rises through the morning, client-observed error rate and backend inbound request rate rise together, while the count of distinct user actions is flat. In the backend logs, a large number of requests complete successfully with nobody left on the connection to receive them. The client timeout was derived from the p99 measured during a quiet week.",
  idea: "A timeout set below the real tail of the latency distribution converts healthy slow requests into duplicate load, which raises the tail further and makes the timeout look justified.",
  why: "A timeout is a claim about the latency distribution: everything past this point is a failure. Set it at the p99 of a quiet period and you have declared that one percent of healthy requests are failures, and each of those becomes a retry. The retry adds load, load moves the distribution right, more requests cross the threshold, and the loop closes. Nothing in the system is broken. The threshold is simply in the wrong place relative to the distribution it is measuring.\n\nThis is why Brooker's advice is to set timeouts from the actual distribution with headroom, and to treat a timeout as a load-shedding decision rather than a health signal. It is also why the pathology is so hard to diagnose from the server side: the server sees success. The mismatch only shows up if you compare client-observed outcomes against server-observed outcomes for the same requests.",
  failureMode: "A 2 second client timeout on a ClickHouse query whose real p99.9 under a large tenant's load is 6 seconds. Every large-tenant query times out, retries, and adds another concurrent query to the same server, so p99.9 climbs, so mid-sized tenants start timing out too. The ClickHouse dashboard shows queries succeeding the whole way through.",
  experiment: "Pick your three tightest client timeouts. For each, query the last thirty days of server-side duration from ClickHouse and compute the fraction of requests that exceeded the configured timeout, split by tenant. Anything over a fraction of a percent for a request that gets retried is a source of self-inflicted load, and the per-tenant split will usually show one large tenant carrying nearly all of it.",
  reflection: "Which of your timeouts was set from a number someone measured once, and what is the actual tail today?",
  recall: {
    q: "The server reports 99.9 percent success and an unchanged latency histogram while clients see widespread errors and backend load is climbing. What is the mechanism, and what measurement confirms it?",
    a: "The client timeout sits inside the healthy latency distribution, so normal slow requests are being classified as failures and retried, and the extra load pushes the tail further right so more requests cross the line. Confirm it by computing, from server-side duration data, the fraction of requests that exceed the client's configured timeout, and by looking for successful server responses whose connection is already gone."
  },
  deepDive: "Compare my configured client timeouts against the real server-side duration tails per tenant and tell me which ones are inside the healthy distribution."
},
{
  id: "retry-dynamodb-2015-metadata",
  track: "retry", level: "amplifier",
  title: "Amazon DynamoDB, 20 September 2015: the retries held the metadata service down after the trigger had passed",
  source: "AWS, Summary of the Amazon DynamoDB Service Disruption and Related Impacts in the US-East Region (September 2015)",
  gateIntro: "On Sunday 20 September 2015, at 2:19 AM PDT, Amazon DynamoDB in the US-East region began returning errors on a significant share of requests. A brief network disruption a few minutes earlier had already ended on its own. Error rates did not recover with it. They stayed elevated for hours and took a set of dependent AWS services in the region with them, including queueing, autoscaling and console functions. Adding capacity to the affected internal service did not restore it. Recovery came only after engineers intervened on that service's inbound path.",
  idea: "Storage nodes that could not reach the metadata service retried their membership requests, and that retry traffic became the entire load keeping the metadata service unreachable.",
  why: "DynamoDB storage servers periodically fetch their partition membership from an internal metadata service. A recently launched feature had increased the size of that membership data substantially for some tables, so the requests took longer to serve. When a brief network event made some of those requests fail, the affected storage servers took themselves out of service and retried. Each retry was now an expensive request, and there were enough of them to keep the metadata service saturated indefinitely.\n\nThe trigger lasted minutes. The outage lasted hours. That gap is the whole lesson: once the retry traffic exceeds the capacity of the thing being retried against, the original cause is irrelevant to recovery, and the system has no path back on its own. AWS could not scale out of it, because added capacity was consumed by the same retry stream. They had to suppress the inbound membership requests first, then add capacity, then let the fleet back in.",
  failureMode: "Any control plane that every data node must reach on startup or on a timer has this shape. If the fleet's response to a failed control-plane call is to call again, the control plane's own load is proportional to its own unavailability, and the feedback is positive.",
  experiment: "List the services in your estate that every workload must reach at startup: the Kubernetes API server, the Temporal frontend, your tenant-config service, your secrets sidecar. For each, find the last time it had a brownout and pull its inbound request rate from Grafana for that window. If inbound rate went up while it was failing, that dependency has the DynamoDB shape and will not self-recover.",
  reflection: "Which of your control-plane dependencies gets more load the worse it is doing, and what would you actually block first to bring it back?",
  recall: {
    q: "The network blip that started the 2015 DynamoDB event lasted minutes, but the outage lasted hours and adding capacity did not help. Why not, and what did recovery require?",
    a: "Storage servers that could not fetch their membership data retried, and those requests had recently become much more expensive, so retry traffic alone was enough to keep the metadata service saturated after the trigger had gone. New capacity was consumed by the same retry stream. Recovery required suppressing the inbound membership requests first, then adding capacity, then readmitting the fleet."
  },
  deepDive: "Identify the control-plane dependencies in my Kubernetes and Temporal estate whose inbound load rises when they fail, and tell me what the equivalent of blocking membership requests would be for each."
},
{
  id: "retry-budget-token-bucket",
  track: "retry", level: "mechanism",
  title: "A retry budget caps retries as a fraction of traffic rather than per request",
  source: "AWS SDKs and Tools Reference Guide, retry behavior and adaptive retry mode",
  gateIntro: "A shared dependency degrades to a high error rate for one class of request. Every client in the calling fleet is configured with a maximum of three attempts and every client honours it exactly. Measured at the dependency, total inbound request rate is several times baseline while the rate of distinct client operations is unchanged. As the dependency's error rate rises, its inbound rate rises with it, so the failure rate and the offered load are now moving together. No client is misconfigured and no client can see the aggregate.",
  idea: "Per-request retry limits still allow unbounded fleet-wide amplification, whereas a shared token bucket makes the retry rate a property of the client as a whole and drains under sustained failure.",
  why: "A per-request cap of three is a statement about one request. It says nothing about the fleet. If the error rate goes to 100 percent, every request costs three, so the load the dependency sees while failing is three times the load it sees while healthy. That is exactly backwards: a failing dependency needs less traffic, not more.\n\nA retry budget inverts the control. The AWS SDKs implement this as a token bucket held per client: a retry costs tokens, a success refunds some, and when the bucket is empty the SDK stops retrying and surfaces the error immediately. Under a brief blip the bucket absorbs the retries and nobody notices. Under sustained failure the bucket drains within seconds and the client degenerates to one attempt per request, which is the behaviour you want. Adaptive mode goes further and rate-limits sends based on observed throttling. The important property is that the retry rate is now bounded as a share of traffic, not per request.",
  failureMode: "Your Go clients all use three attempts with good jitter. A ClickHouse node goes read-only. Inbound query rate triples at exactly the moment ClickHouse has least capacity, and the two remaining nodes tip over under the redirected load plus the tripling.",
  experiment: "Check the retry mode on every AWS SDK client in your services: standard mode applies a retry quota token bucket, adaptive adds client-side rate limiting on top of it, legacy predates both, and a hand-rolled retry loop has nothing at all. Then instrument one non-AWS client with two counters, attempts and logical operations, and put the ratio on a Grafana panel. During the next dependency blip the ratio is your amplification factor, measured rather than assumed.",
  reflection: "For your most-shared internal dependency, what is the maximum multiple of baseline load it can receive from its own callers while it is failing?",
  recall: {
    q: "Why does a per-request limit of three attempts fail to bound fleet-wide retry load, and what does a token-bucket retry budget do differently under sustained failure?",
    a: "A per-request cap means load scales with the failure rate: at 100 percent errors every request costs three, so the dependency receives three times baseline exactly when it has least capacity. A token bucket is shared across requests, so it absorbs short blips but drains under sustained failure, after which the client falls back to a single attempt and the retry rate stays bounded as a fraction of traffic."
  },
  deepDive: "Show me how to add a shared retry token bucket to my Go and Python internal clients and what to emit so I can see the attempts-per-operation ratio in Grafana."
},
{
  id: "retry-idempotency-key",
  track: "retry", level: "mechanism",
  title: "Idempotency is what makes a retry a retry instead of a duplicate",
  source: "Malcolm Featonby, Making retries safe with idempotent APIs, Amazon Builders' Library",
  gateIntro: "A write path shows a low but persistent rate of duplicated effects: the same logical operation recorded twice, seconds to minutes apart, always during windows of elevated latency and never during quiet periods. Client-side logs show a single user action. Server-side logs show two successful writes with different request identifiers and near-identical payloads. Error rate during the affected windows is normal by every dashboard. Nothing failed, and the duplicates only appear in customer complaints and in a reconciliation job that runs weekly.",
  idea: "Every retry policy silently assumes at-least-once delivery is acceptable, and an idempotency key with a stored result is the only thing that makes that assumption true for writes.",
  why: "A client that times out cannot distinguish a request that never arrived from one that arrived, succeeded, and lost its response. Retrying is correct in the first case and duplicating in the second, and the client has no way to tell them apart. So the safety has to live on the server: the caller supplies a key, the server records the key alongside the result of the first execution, and a repeat of the same key returns the stored result rather than executing again.\n\nThe detail that gets skipped is storing the result. A server that only deduplicates in flight, or that records the key but not the outcome, still gives the retrying client a different answer the second time, which pushes the ambiguity back to the caller. The key also has to be generated by the client before the first attempt and reused across all attempts of the same logical operation, which means the retry loop and the key generation have to live at the same layer.",
  failureMode: "A Temporal activity that provisions a tenant resource has the default unlimited retry policy. The provisioning API is slow rather than broken. Every StartToClose expiry creates another resource, the activity eventually succeeds, and the workflow completes green with four orphaned resources billed to the tenant.",
  experiment: "Take the three write endpoints in your estate that are most retried, which you can get from your attempts-per-operation instrumentation or just from the activity policies in the workflow code. For each, answer two questions in writing: does it accept a caller-supplied idempotency key, and does it store the result of the first execution rather than just a marker. Most will fail the second question. That is the finding.",
  reflection: "Which of your Temporal activities is not idempotent, and what does its retry policy currently do about that?",
  recall: {
    q: "A client times out on a write and retries. What can it not know, and what exactly must the server store to make the retry safe?",
    a: "It cannot distinguish a request that never arrived from one that succeeded and lost its response, so retrying is either correct or duplicating and the client cannot tell which. The server must accept a client-generated idempotency key, created before the first attempt and reused for every attempt, and store the result of the first execution so a repeat of the key returns the same answer without executing again."
  },
  deepDive: "Audit my Temporal activities for non-idempotent side effects and tell me which ones need idempotency keys before their retry policies are safe."
},
{
  id: "retry-breaker-frees-caller",
  track: "retry", level: "mechanism",
  title: "A circuit breaker converts a slow failure into a fast one",
  source: "Michael Nygard, Release It! (2007)",
  gateIntro: "A downstream dependency slows from single-digit milliseconds to several seconds. It keeps returning correct answers the whole time and its error rate never rises. Within about two minutes the service calling it stops serving anything at all, including endpoints that never touch that dependency, and its health checks start failing. CPU on the calling service is near idle. Thread pool and connection pool utilisation are pinned at maximum. The dependency recovers on its own a few minutes later. The caller does not, and has to be restarted.",
  idea: "The value of a breaker is not protecting the callee but releasing the caller's threads and connections, which is what stops a downstream slowdown from becoming an upstream outage.",
  why: "Slow is worse than down. A dependency returning errors in a millisecond releases the caller's resources immediately. A dependency taking five seconds holds a thread, a connection and a slot in every pool for five seconds, and by Little's law the caller's concurrency requirement grows in direct proportion to that latency at unchanged arrival rate. The pools fill, unrelated endpoints starve, and the caller is now the outage.\n\nA breaker is a resource-release mechanism for the caller. Once it is open, calls fail in microseconds, the pools drain, and the endpoints that do not depend on the sick service keep working. Nygard's framing is that the breaker is one of a set of stability patterns whose job is to stop a fault crossing an integration point, and its most important effect is on the side that holds the resource, not the side that is sick.",
  failureMode: "One shared Go http.Client with no per-dependency isolation, used for six downstream calls. The slowest of the six saturates MaxIdleConnsPerHost and the transport's connection pool, and all six start queueing. The dashboard for the five healthy dependencies shows their latency rising, so the investigation starts in the wrong place.",
  experiment: "Count the distinct downstream dependencies sharing a single HTTP client, connection pool or worker pool in each of your services. In Go, grep for http.Client construction and count call sites per client. The output is a bulkhead map. Anywhere the count is above one, a slowdown in the worst dependency is an outage in all of them, and you can verify that with a single latency injection in staging.",
  reflection: "Which of your services would go down entirely if its slowest non-critical dependency started taking five seconds and returning correct answers?",
  recall: {
    q: "A dependency slows down but never returns an error, and the caller goes fully down while its CPU sits idle. What resource ran out, and what does a breaker actually protect?",
    a: "Threads and connections. At a fixed arrival rate, concurrency scales with latency, so a five-second dependency holds pool slots until the pools are exhausted and unrelated endpoints starve. The breaker protects the caller by converting a slow failure into an immediate one so those resources are released, which matters more than any load reduction it gives the callee."
  },
  deepDive: "Map which of my Go services share one HTTP client or worker pool across multiple downstream dependencies, and rank them by blast radius if the slowest one degrades."
},
{
  id: "retry-breaker-mistuned",
  track: "retry", level: "amplifier",
  title: "A circuit breaker is a control loop you have to tune, and a badly tuned one holds a healthy service down",
  source: "Marc Brooker, Will circuit breakers solve my problems? (brooker.co.za, 2022)",
  gateIntro: "A dependency starts failing for one tenant's shard. It is a low single-digit percentage of all calls, entirely from one slice of traffic, and the other shards are measurably fine. Within a minute the calling service is returning errors for every tenant, including the ones whose shard never had a problem. The dependency's own error rate peaks and then falls back to baseline within a few minutes. The caller's error rate does not follow it down. It stays flat and high for another twenty minutes, and clears only when someone restarts the caller.",
  idea: "Breakers add hysteresis and a threshold you rarely revisit, so they can trip on a partial failure, keep tripping through the half-open probe, and turn a degradation affecting some tenants into an outage affecting all of them.",
  why: "A breaker is a feedback controller with a threshold, a window and a recovery probe, and none of those three are self-tuning. Brooker's objection is that the threshold is a guess about a distribution that changes, and the state machine introduces a mode where the system's behaviour is discontinuous: one extra failed request flips it from serving everything to serving nothing.\n\nThe worst version is a breaker whose scope is wider than the failure's scope. A partial failure affecting one shard, one tenant or one endpoint trips a breaker that covers the whole dependency, so the breaker converts a partial outage into a total one. Recovery then depends on the half-open probe: if the probe rate is low, or if the probe happens to hit the still-sick shard, the breaker re-opens and the caller stays down long after the dependency is healthy. Load shedding, concurrency limits and good timeouts degrade continuously and are usually the better tool.",
  failureMode: "A breaker keyed on the dependency's hostname rather than on tenant or shard. One large tenant's queries are slow, the breaker opens for the hostname, and every other tenant gets an immediate error from a healthy backend. The tell is that the caller's failure outlives the callee's by a wide margin.",
  experiment: "List every breaker in the estate, in code and in the service mesh config. For each, write down four things: the failure threshold, the window, the half-open probe rate, and the scope it is keyed on. Then compare the scope to the granularity at which your failures actually occur, which for you is per tenant and per shard. Any breaker keyed more coarsely than the failure granularity is a partial-to-total converter.",
  reflection: "Do any of your breakers have a scope wider than the unit at which your failures happen, and when did anyone last look at the threshold?",
  recall: {
    q: "A dependency has a partial failure confined to one shard, and the caller fails completely for far longer than the dependency did. What went wrong, and what makes it self-sustaining?",
    a: "The breaker's scope was coarser than the failure's, so a partial degradation opened the circuit for all traffic and converted it into a total outage. It persists because recovery depends on the half-open probe: a low probe rate or a probe that keeps landing on the still-sick slice re-opens the breaker, so the caller stays down after the callee is healthy."
  },
  deepDive: "Review the breakers in my service mesh and application code against per-tenant failure granularity, and tell me which ones should be replaced with concurrency limits instead."
},
{
  id: "retry-cache-stampede",
  track: "retry", level: "mechanism",
  title: "One expiring cache key becomes every concurrent request",
  source: "Nishtala et al., Scaling Memcache at Facebook, NSDI 2013",
  gateIntro: "A read path serving at a very high cache hit rate. Every so often, with no change in client traffic and no deploy, the origin database sees several thousand near-identical queries arrive inside a few hundred milliseconds, which is enough to exhaust its connection pool and add a second of latency to everything else on that database. The spikes are irregular in timing but each one is dominated by a single object. Cache hit rate dips for about a second and returns to normal. The database recovers on its own, and it happens again a few hours later.",
  idea: "On a miss the cache offers no protection at all, so a hot key expiring under load sends the full request rate to the origin unless a lease or single-flight coalescer lets exactly one caller do the fill.",
  why: "A cache's hit rate is a property of the steady state, not of the transition. At the instant a hot key expires, the protection it was providing goes to zero and the origin is exposed to the raw request rate for that key for the whole duration of one fill. If the key is served 5,000 times a second and the fill takes 200ms, the origin receives a thousand identical queries, each of which makes the fill slower, which lengthens the exposure window.\n\nThe Facebook memcache work solves this with leases: on a miss, the cache hands exactly one client a token authorising it to compute and set the value, and makes the others wait or serve stale. The same shape in a single process is Go's singleflight. The general principle is that a miss on a hot key must be coalesced into one origin request, and the second protection, serving stale while the fill is in flight, is what removes the latency cliff entirely.",
  failureMode: "A tenant metadata lookup cached with a fixed TTL and populated at deploy time. Every pod in the deployment caches it at the same moment, so every copy expires at the same moment, and the origin gets the entire fleet's miss traffic in one burst. Uniform TTLs manufacture the correlation that the stampede needs.",
  experiment: "Find your cache fills and check each for coalescing: in Go, whether it goes through singleflight or an equivalent, in Python whether anything prevents concurrent identical fills. Then check the TTLs for a fixed constant with no randomisation, which is the same synchronisation bug as backoff without jitter. Output: a list of fill sites with two columns, coalesced and jittered TTL. Fills that are neither are your stampede candidates.",
  reflection: "Which of your cached objects is hot enough that a single miss would deliver the full request rate to the origin?",
  recall: {
    q: "A hot key expires and the origin receives thousands of identical queries in a few hundred milliseconds. Why does the request rate to the origin equal the full read rate, and what are the two mitigations?",
    a: "Because the cache provides zero protection during a miss: for the duration of one fill, every concurrent reader of that key goes to the origin, and each additional query slows the fill and lengthens the window. Coalesce the fill so exactly one caller does it, via a lease or singleflight, and serve stale to the rest while it is in flight. Jittered TTLs stop the whole fleet expiring together."
  },
  deepDive: "Find the cache fill sites in my services that lack request coalescing or use fixed TTLs, and estimate the origin load each would produce on a miss."
},
{
  id: "retry-gcp-2025-herd",
  track: "retry", level: "amplifier",
  title: "Google Cloud, 12 June 2025: the herd during recovery was harder to survive than the original crash",
  source: "Google Cloud, Service Health incident report for the 12 June 2025 disruption",
  gateIntro: "On 12 June 2025 at 10:51 AM PDT, API requests to a large number of Google Cloud services began failing worldwide, in every region simultaneously. Engineers identified the cause within roughly ten minutes and had a mitigation rolling out shortly after. Most regions were serving normally again within about two hours of the start. One region, the largest, was not. It remained degraded well after the fix was already in place everywhere else, and required a further, deliberate intervention by the team before it came back.",
  idea: "When crash-looping instances came back, every client retried at once against a cold service in the largest region, and recovery required deliberately throttling the herd rather than letting it converge.",
  why: "The trigger was a bad globally-replicated policy record that caused Service Control to crash on a null field, everywhere at once. The fix was fast. What was not fast was the return: when the crash-looping tasks in the largest region restarted together, they hit their underlying infrastructure with a synchronised burst of requests, and that infrastructure was overloaded by the recovery traffic itself. Google's own report calls out the absence of randomised exponential backoff in that path as a contributing factor.\n\nThis is the general property of recovery: a service coming back has cold caches, empty connection pools, unwarmed JITs and no admission history, so its capacity at t=0 is a fraction of steady state, while the demand arriving at t=0 is the entire backlog plus current traffic. Capacity at its minimum meets demand at its maximum. The larger the region, the worse the ratio, which is why the biggest region is the one that stays down.",
  failureMode: "A cluster-wide restart in your estate has this exact shape. Every workflow worker reconnects to the Temporal frontend at once, every pod hits the tenant-config service at once, and the thing that was fine at steady state cannot serve the reconnection burst. The incident then looks like it has a second, unrelated cause, because the fix for the first one is already deployed.",
  experiment: "Measure your own cold-start ratio. Take one service, restart the whole deployment in a non-production cluster, and plot request rate and error rate against time for the first ninety seconds. Compare the throughput it sustains in the first ten seconds to its steady state. Then compute what the whole fleet would offer it at t=0 after a cluster-wide event. If demand at t=0 exceeds cold capacity, you need staged admission, not faster restarts.",
  reflection: "For your largest tenant cluster, what would you throttle first during a mass restart, and do you have a lever to do it?",
  recall: {
    q: "The mitigation was deployed globally within an hour, but the largest region stayed down much longer. Why is recovery load harder to survive than the original failure, and what did it take to get out?",
    a: "A recovering service has minimum capacity exactly when demand is at maximum: cold caches, empty pools and no warmup meet the entire backlog plus live traffic arriving in one synchronised burst. Without randomised backoff the burst was self-reinforcing and the underlying infrastructure was overloaded by the recovery itself, so the team had to deliberately throttle the returning traffic rather than wait for convergence."
  },
  deepDive: "Model what my Temporal frontend and tenant-config service would receive during a cluster-wide pod restart, and what admission control would let me stage the return."
},
{
  id: "retry-deadline-propagation",
  track: "retry", level: "mechanism",
  title: "Retrying after the caller's deadline has passed is work nobody is waiting for",
  source: "gRPC documentation, Deadlines and deadline propagation",
  gateIntro: "A request path with a two second client deadline crosses four services. Under load, the leaf service's CPU is fully consumed and its queue depth grows steadily. A large share of the responses it produces are never delivered, because the connection has already gone by the time the answer is ready. Successful completions counted at the leaf and successful completions counted at the edge diverge sharply and keep diverging. Adding capacity to the leaf moves the point at which the divergence starts but does not close it.",
  idea: "A retry decision needs the remaining deadline as an input, because a retry issued past it consumes capacity to produce a result that will be discarded, which is pure amplification with zero success probability.",
  why: "Deadlines are absolute and they belong to the original caller. Once a service receives a request with 400ms remaining, every downstream call it makes, and every retry of those calls, has to fit inside that 400ms or it is producing garbage. gRPC propagates the deadline through the context precisely so each hop can subtract elapsed time and refuse work it cannot finish in time.\n\nThe failure is a service that treats its timeout as a local constant. It has a 2 second per-call timeout, it retries three times, and the whole sequence can run for six seconds against a caller who left after two. That work is not merely wasted, it is actively harmful: it occupies the exact capacity that in-deadline requests need, which pushes more of them past their deadlines, which produces more doomed retries. Checking the remaining deadline before each attempt costs nothing and removes the entire class.",
  failureMode: "Go code that creates a fresh context.Background() inside a request handler because the request context kept getting cancelled and cancellation looked like the bug. The cancellations were the system working. Replacing them with Background turns every abandoned request into a full-length backend job.",
  experiment: "Grep your Go services for context.Background() and context.TODO() inside anything reachable from a request handler or a Temporal activity. Each hit is a place where the caller's deadline stops propagating. Then add a single counter at your leaf service for responses completed after the deadline had already expired, and put it on a panel. A non-trivial rate there is capacity you are spending on nobody.",
  reflection: "How much of your leaf service's busiest hour is spent producing answers that arrive after their caller has gone?",
  recall: {
    q: "Why is a retry issued after the caller's deadline worse than no retry at all, and what is the mechanical fix?",
    a: "It has zero probability of a useful outcome but consumes the same capacity as a live request, which pushes other in-flight requests past their own deadlines and creates more doomed work. The fix is deadline propagation: carry the absolute deadline through every hop, subtract elapsed time, and check the remaining budget before each attempt rather than treating the timeout as a local constant."
  },
  deepDive: "Trace deadline propagation through one of my Go request paths end to end and show me where the caller's remaining budget is being discarded."
},
{
  id: "retry-hedged-requests",
  track: "retry", level: "mechanism",
  title: "A hedged request is a retry you send before the failure",
  source: "Jeffrey Dean and Luiz Andre Barroso, The Tail at Scale, CACM 2013",
  gateIntro: "A read service fans a single user request out to a large number of backends and cannot answer until the slowest of them has replied. Each backend is healthy: per-backend p99 is a few milliseconds, error rates are zero and capacity is ample everywhere. End-user p99 is over a second, three orders of magnitude worse than any individual backend. Doubling the backend fleet does not move the user-visible number. Nothing in the system is in a failed state and nothing appears in the incident channel.",
  idea: "Sending a second copy of a request after the 95th percentile elapses buys most of the tail-latency benefit of aggressive retries for a few percent extra load, provided the hedge is cancelled when the first response lands.",
  why: "With a large fan-out, the probability that at least one leg lands in the tail approaches one. Dean and Barroso's point is that at that scale the tail is not an exception you can ignore, it is the common case for the composite request, and the only fix is a technique that tolerates variability rather than one that tries to eliminate it.\n\nA hedge sends the second copy on a timer rather than on a failure. Set the timer at the 95th percentile and by construction you send it for only about five percent of requests, so the extra load is small and bounded, while the composite latency becomes the minimum of two independent draws instead of one. Their BigTable example shows the 99.9th percentile falling substantially for a low single-digit percentage increase in requests. The two conditions that make it safe are that the operation is idempotent and that the loser is cancelled: without cancellation the extra load is not bounded, and under overload a hedge is amplification by another name, which is why it has to sit under the same retry budget.",
  failureMode: "A hedge set at the mean rather than the tail, so it fires on half the traffic and adds fifty percent load. Or a hedge with no cancellation on a ClickHouse query, so the loser keeps burning a query slot and the hedge makes the tail worse under exactly the load that motivated it.",
  experiment: "For your widest fan-out path, pull the per-leg p99 and the end-to-end p99 from ClickHouse and compute the ratio. Then estimate what the composite would be if each leg were capped at its own p95 by a hedge. If the ratio is large, you have a variability problem rather than a capacity problem, and buying more backends is not going to fix it.",
  reflection: "Where in your estate does one user-visible request wait on many independent legs, and what is the gap between per-leg and end-to-end p99?",
  recall: {
    q: "Every backend in a large fan-out is healthy with a low p99, yet user-visible p99 is a thousand times worse. What is happening, and what makes a hedge cheap where a retry is expensive?",
    a: "With a wide fan-out the composite request waits on the slowest leg, so the probability that some leg lands in its tail approaches one and per-leg health is irrelevant. A hedge fires on a timer at roughly the 95th percentile, so it applies to only about five percent of requests and turns the latency into the minimum of two draws. It stays cheap only if the operation is idempotent, the loser is cancelled, and it is subject to the same retry budget."
  },
  deepDive: "Work out whether hedging would help my widest fan-out read path, and what cancellation and budget it would need to be safe under load."
},
{
  id: "retry-client-load-shedding",
  track: "retry", level: "mechanism",
  title: "The client should shed its own load before the server has to",
  source: "Netflix Technology Blog, Performance Under Load: adaptive concurrency limits (2018)",
  gateIntro: "A shared dependency reaches saturation. Its rejection path is working exactly as designed: it returns a fast, cheap 429 for anything over its configured limit, and the limit was set from a load test six months ago. Under real overload, queue latency at the dependency stays above a second for twenty minutes while useful throughput does not improve. A large and growing share of its CPU is going into producing rejections. Callers receive their rejections quickly and their offered rate does not fall.",
  idea: "A client that infers a concurrency limit from observed latency stops sending requests it cannot get served, which protects the shared dependency without needing the server to be healthy enough to reject anything.",
  why: "Server-side admission control has two structural weaknesses. It costs something to reject a request, so at sufficient overload the rejection work itself consumes the server, and the static limit it enforces is a guess made at a moment when the system looked different from today. Netflix's argument is that the correct concurrency limit is not a constant at all: it follows from Little's law and the currently observed latency, so it should be measured continuously rather than configured.\n\nThe client-side version is stronger because it removes the load before it crosses the network. The client tracks its own observed round-trip latency, compares it against the minimum it has seen recently, and treats a rising ratio as evidence of queueing downstream. It then shrinks its own in-flight limit, in the same shape as TCP congestion control. Every caller doing this independently produces a fleet-wide reduction with no coordination and no server participation, which matters because the server is exactly the component you cannot rely on during overload.",
  failureMode: "A dependency whose only protection is a fixed server-side limit. During overload it spends its capacity emitting 429s, the callers retry them because 429 looks retryable, and the shed load returns immediately as new load. Adaptive client limits are what stop the rejected work from coming straight back.",
  experiment: "Instrument one Go client with two numbers: in-flight requests and the ratio of current latency to the minimum observed in the last few minutes. Put both on a Grafana panel and watch them during your next load spike. If in-flight rises while the latency ratio rises, the client is pushing into a queue, and you have both the evidence and the control signal you need to add an adaptive limit.",
  reflection: "Which of your clients keeps pushing into a saturated dependency because nothing on the client side is watching latency?",
  recall: {
    q: "A saturated service rejects excess load quickly and correctly, and stays saturated anyway. What are the two weaknesses of server-side shedding, and what signal does a client use instead?",
    a: "Rejecting costs the server real capacity, so at high overload it can spend itself producing rejections, and the static limit it enforces is a stale guess. A client-side adaptive limit instead compares its currently observed latency to the recent minimum, treats a rising ratio as evidence of downstream queueing, and shrinks its own in-flight limit like congestion control, which removes load before it crosses the network and needs no participation from the sick service."
  },
  deepDive: "Show me how to add adaptive concurrency limits to my Go clients for the two most-shared internal dependencies, and what to measure first to size them."
},
{
  id: "retry-fallback-untested",
  track: "retry", level: "mechanism",
  title: "The fallback path is the least tested code in the system and it runs only during incidents",
  source: "Jacob Gabrielson, Avoiding fallback in distributed systems, Amazon Builders' Library",
  gateIntro: "A service has a designed degradation path: when its primary data source is unavailable it serves from a secondary. The primary has a fifteen minute disruption. The service does not degrade gracefully. It fails harder and more widely than the primary's own disruption would explain, produces a class of error nobody has seen before, and the resulting incident outlasts the primary's recovery by more than an hour. The secondary path had been in the code for two years, had unit tests, and had never carried production traffic.",
  idea: "Fallbacks are retries with different code, exercised at exactly the moment the system is least able to absorb surprise, so it is usually safer to fail the request than to take an untested second path.",
  why: "Gabrielson's argument is about correlation of risk. The fallback path runs only when the primary is broken, which means its success rate is unmeasured in normal operation and its capacity is unproven. It is also almost always slower or weaker, so it runs under the load the primary was handling plus whatever retry amplification the failure has already produced. You are asking your least-exercised code to handle your worst-ever traffic, during an incident, at 2am.\n\nThe recommended alternative is to remove the mode difference: either make the fallback path the only path, so it is exercised constantly, or delete it and fail fast. If you must keep it, it has to run continuously against real traffic, be capacity-tested at full primary load, and be tripped deliberately rather than automatically, so a human decides to take the untested path with the current state visible.",
  failureMode: "A tenant-config lookup that falls back to a local file when the config service is unreachable. The file is stale by six months for half the tenants. During a config service outage the pods do not fail, they come up healthy with wrong configuration, which is a much longer and much worse incident than a crashloop would have been.",
  experiment: "List every fallback and degradation path in your estate and put a date next to each: the last time it actually carried production traffic. Grep for the words fallback, degraded, stale and secondary in your Go and Python services to find the ones nobody remembers. Any row where the answer is never, or more than a quarter ago, is a path that will surprise you during the incident it exists for.",
  reflection: "Which of your fallbacks has never run in production, and would failing the request outright be better than taking it?",
  recall: {
    q: "Why is a fallback path structurally more dangerous than failing the request, and what are the two ways to make one acceptable?",
    a: "It executes only when the primary is broken, so its correctness and capacity are unmeasured, and it runs under the primary's full load plus any retry amplification the failure has already caused. Either exercise it continuously with real production traffic and capacity-test it at full primary load, or remove it and fail fast. A path that only runs during incidents is a path you have never tested."
  },
  deepDive: "Inventory the fallback and degraded-mode paths in my services and tell me which ones I should delete rather than keep untested."
},
{
  id: "retry-temporal-activity-layers",
  track: "retry", level: "mechanism",
  title: "Temporal activity retries multiply with workflow retries and with the HTTP client underneath",
  source: "Temporal documentation, Retry Policies, Activity Timeouts and ScheduleToClose",
  gateIntro: "A workflow worker calls an internal HTTP API as part of a tenant onboarding path. The API has a bad ten minutes and recovers. More than an hour after the API team declares the incident closed, they are still seeing sustained inbound request volume from that worker at a steady rate that never decays. Workflow start count is flat and unremarkable. No workflow has failed. The affected executions all show as Running, with no terminal error recorded anywhere, and nobody on the workflow side has an alert.",
  cheat: "Temporal MaximumAttempts defaults to zero, meaning unlimited; StartToClose bounds a single attempt, so ScheduleToClose is what bounds the sequence.",
  idea: "A default-unlimited activity retry policy sitting above a Go SDK client that already retries turns one logical call into a sustained request stream, and StartToClose against ScheduleToClose is where you actually bound it.",
  why: "Temporal's default activity retry policy has an initial interval of one second, a backoff coefficient of two, a maximum interval capped at a multiple of the initial, and a maximum attempts of zero, which means unlimited. Combined with the interval cap, the steady state is not exponential decay at all: it is a fixed retry rate that continues for as long as the activity keeps failing. Add the HTTP client inside the activity doing its own attempts and you have the multiplicative stack, with the outer layer having no bound.\n\nThe two timeouts do different jobs and this is the part people get wrong. StartToClose bounds a single attempt. ScheduleToClose bounds the entire sequence including every retry and every wait between them. Setting only StartToClose gives you a bounded attempt inside an unbounded loop, which is exactly the shape above. If you want the workflow to give up, ScheduleToClose or MaximumAttempts is the field, and non-retryable error types are how you stop retrying the failures that will never succeed.",
  failureMode: "During the Argo to Temporal cutover this is easy to introduce, because the Argo workflow it replaces had retryStrategy limit set to a small number and the equivalent Temporal policy left at default is unlimited. The behaviour change is silent, does not show up in a diff review, and only manifests when the downstream is unhealthy.",
  experiment: "Dump every ActivityOptions in the workflow code and produce a table: activity name, StartToClose, ScheduleToClose, MaximumAttempts, NonRetryableErrorTypes. Count the rows where ScheduleToClose is unset and MaximumAttempts is zero. Those are unbounded. Cross-check with the Argo manifests you are migrating from and flag any activity whose Temporal policy is weaker than the retryStrategy it replaced.",
  reflection: "How many of your migrated activities are currently unbounded, and which downstream would notice first?",
  recall: {
    q: "A Temporal activity keeps a failing downstream under sustained load for hours with no workflow failure recorded. Which default causes it, and which timeout is the one that bounds the whole sequence?",
    a: "MaximumAttempts defaults to zero, meaning unlimited, and because the retry interval is capped the result is a steady retry rate rather than a decaying one. StartToClose bounds only a single attempt. ScheduleToClose is the timeout that covers the entire sequence including all retries and waits, so it or MaximumAttempts is what actually stops it."
  },
  deepDive: "Audit every ActivityOptions in my workflows for unbounded retry policies and compare each against the Argo retryStrategy it replaced."
},
{
  id: "retry-crashloop-backoff",
  track: "retry", level: "amplifier",
  title: "CrashLoopBackOff is a retry loop with no budget and no jitter",
  source: "Kubernetes documentation, Pod lifecycle and container restart backoff",
  gateIntro: "A rollout goes out across a multi-tenant cluster: a few hundred pods across dozens of namespaces, all of which read configuration from one internal service during startup. The image has a bug that kills the process a few seconds after it starts. Over the following hours the configuration service sees inbound request rate settle at a steady elevated plateau. It does not spike and it does not decay. Pod count is unchanged, no new pods are being created, nobody is deploying anything, and the plateau is still there the next morning.",
  idea: "Kubelet restart backoff is per container and caps at five minutes, so a bad rollout across a multi-tenant cluster produces a steady synchronised request rate against whatever dependency the pods hit on startup.",
  why: "The kubelet restarts a failed container with an exponential delay that doubles from ten seconds and is capped, in the documented default, at five minutes. Capped exponential backoff is not exponential in the limit, it is a constant rate. Once every crashing pod has reached the cap you have a fixed number of startup attempts per five minutes, forever, until someone intervenes. There is no attempt limit, no budget and no jitter, and the counter only resets after the container has run successfully for long enough.\n\nThe multi-tenant part is what makes it dangerous. The pods were created by one rollout, so they crash together and their backoff timers stay roughly in phase, which puts the startup requests into synchronised bursts against a shared dependency. And because the dependency is shared, the blast radius of one tenant's bad image is every tenant that reads from the same config service, secrets store or Kubernetes API. From the dependency's side there is no signal at all about where the load is coming from.",
  failureMode: "The worse version is when the startup dependency is the thing that is sick. Pods crash because the config service is slow, restart, hit the config service again, and keep it saturated. The kubelet is now a retry client with unlimited attempts pointed at a service that needs less load, and no amount of waiting resolves it.",
  experiment: "Run the PromQL sum by (namespace) (increase(kube_pod_container_status_restarts_total[6h])) across your tenant clusters and sort descending. For the top namespaces, work out what each container calls during startup. Then multiply: number of crashing containers divided by five minutes gives you the floor rate that dependency is receiving indefinitely. Compare it to that dependency's normal request rate.",
  reflection: "Which shared service in your clusters is on the startup path of the most pods, and what steady rate would a hundred crashlooping containers put on it?",
  recall: {
    q: "Why does a capped restart backoff produce a constant load rather than a decaying one, and what makes the multi-tenant case worse than a single bad deployment?",
    a: "Once every crashing container reaches the five minute cap the retry interval stops growing, so the fleet delivers a fixed number of startup attempts per five minutes indefinitely, with no attempt limit, no budget and no jitter. In a shared cluster the pods crash in phase from one rollout and all hit the same startup dependency, so one tenant's bad image becomes steady synchronised load on a service every other tenant needs."
  },
  deepDive: "Find which shared services sit on the container startup path across my tenant clusters and calculate the floor load a sustained crashloop would put on each."
}
);
