/* Track: Configuration and deploy. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "config-legal-values-wrong-place",
  track: "config", level: "mechanism",
  title: "Configuration changes are the most common documented trigger of large outages",
  source: "Zuoning Yin, Xiao Ma, Jing Zheng, Yuanyuan Zhou, Lakshmi N. Bairavasundaram and Shankar Pasupathy, An Empirical Study on Configuration Errors in Commercial and Open Source Systems, SOSP 2011",
  gateIntro: "A storage vendor's customer support database and the bug trackers of four widely deployed open source servers were mined for every case where the eventual fix was a settings change rather than a code change. Several hundred cases survived the filter. In most of them the affected system had come up and run normally for some period before anyone noticed anything wrong. A meaningful share produced no symptom at all until some later, apparently unrelated event.",
  idea: "The misconfigurations that cause outages are overwhelmingly legal values in the wrong place, not malformed ones, which is why syntax validation catches almost none of them and why config needs the same staged rollout and review as code.",
  why: "Yin and colleagues classified real, customer-reported configuration errors from a commercial storage vendor and from CentOS, MySQL, Apache and OpenLDAP. The headline result is that only a minority of the errors were illegal parameters - values a parser could reject. The majority were syntactically valid entries that were inconsistent with something else: another parameter, the environment, the hardware, the version. A type checker sees a well-formed integer. The system sees a thread pool sized for a machine that no longer exists.\n\nThe second result is the one that hurts on call. A substantial fraction of these errors were latent: the wrong value sat in production without symptom until a later event exercised the path. Failover, a restart, a traffic shift, a leap second. That decouples the change from the failure, so the deploy timeline is no longer a list of suspects. Configuration is at or near the top of every published tally of outage causes, and the reason is structural rather than cultural: config carries the same power as code with none of the review, testing, staging or version discipline that code gets by default.",
  failureMode: "Someone raises the Temporal worker's maxConcurrentActivityTaskPollers in a values file. It is an integer, it is in range, the chart renders, the pods start, the probes pass. Three weeks later a large tenant backfill arrives, the pollers all wake at once and the task queue's downstream connection pool saturates. The change that caused it is twenty deploys back and nobody looks there.",
  experiment: "Take the Helm values for one workload you run and count the keys. Then count how many of those keys are covered by a values.schema.json or any static check beyond YAML parsing. The ratio is the fraction of your configuration surface where the only validator is production.",
  reflection: "How many configuration keys in that one chart could take a legal value that would break you, and which of those has no test?",
  recall: {
    q: "Yin et al. found that most real configuration errors are not illegal parameters. What are they instead, and what does that imply about where validation has to live?",
    a: "They are syntactically legal values that are inconsistent with something else in the system: another parameter, the hardware, the version, the environment. A parser cannot reject them because there is nothing malformed to reject.\n\nSo validation has to be semantic and has to run before production: a typed schema, cross-field constraints, and tests that assert on behaviour. Failing that, the value gets validated by the first request that exercises it, which is the definition of an outage."
  },
  deepDive: "Take the values files for my Temporal workers and my tenant-scoped Argo workflows and tell me which keys can hold a legal value that would cause a production failure, ranked by blast radius."
},
{
  id: "config-gcp-global-policy-record",
  track: "config", level: "mechanism",
  title: "Google Cloud, 12 June 2025: a globally replicated policy record reached every region in seconds",
  source: "Google Cloud, incident report for the 12 June 2025 Service Control disruption",
  gateIntro: "At about 10:51 US Pacific on 12 June 2025, a large set of Google Cloud APIs began returning 503s. Not one region degrading and then another: external API requests were failing in every region within the same few minutes, and Google Workspace products went with them. Engineering identified a cause and triggered a mitigation within about forty minutes, after which most regions recovered quickly. One large region did not, and took closer to three hours.",
  idea: "A binary rollout can be staged region by region, but a globally replicated data record cannot, so any code path whose behaviour depends on that data has a worldwide blast radius no matter how carefully the binary was deployed.",
  why: "Two independent changes had to meet. Weeks earlier, a new quota policy check was added to Service Control, the component that authorises and validates every API request. That code shipped without adequate error handling and without a feature flag, so the new path was live and unguarded everywhere it had been deployed. On 12 June a policy record containing unintended blank fields was written. Service Control reads policy from a globally replicated store, so the record was present in every region within seconds. Every regional Service Control instance hit the blank field on the new path, dereferenced nothing, and entered a crash loop.\n\nThe part worth internalising is why the deploy discipline did not help. The binary rollout was staged. The data was not, and the data was the trigger. When the mitigation landed, the largest region then failed to recover on schedule, because the whole regional Service Control fleet restarting at once overwhelmed the infrastructure it reads its own policy from - a thundering herd created by the recovery rather than by the fault. Two lessons in one incident: the config plane needs its own rollout, and the recovery path needs its own capacity model.",
  failureMode: "Any control-plane record that replicates globally is an untested global deploy. A tenant entitlement row, a routing table, a feature configuration document in a shared store. A new consumer of that data ships without a flag, someone writes an unusual but legal row, and every consumer in every region reads it before any monitoring window has closed.",
  experiment: "List the data stores your platform reads that replicate to every cluster rather than being written per cluster. For each, answer one question in writing: could a single row written now change behaviour in every cell within a minute? Any yes is a global deploy channel with no rollout policy.",
  reflection: "Which of your global stores has a writer that is not itself behind change review, and who can write to it today?",
  recall: {
    q: "Google Cloud staged its binary rollouts and still failed globally within two minutes on 12 June 2025. Why did staging not help, and why was recovery slowest in the largest region?",
    a: "The binary was staged but the trigger was a policy record in a globally replicated store, which reached every region in seconds. A new code path with no feature flag and no error handling met a blank field in that record and crash-looped everywhere at once.\n\nRecovery was slowest in the largest region because the fleet restarting simultaneously overloaded the infrastructure backing Service Control's own policy reads. The recovery generated a herd that the steady state never produced."
  },
  deepDive: "Find the globally replicated records in my estate that any cluster reads on the request path, and tell me which of them can change behaviour in every cell without passing through a deploy pipeline."
},
{
  id: "config-knight-capital-reused-flag",
  track: "config", level: "recovery",
  title: "Knight Capital, 1 August 2012: the deploy reached seven of eight servers and a reused flag woke dead code",
  source: "US Securities and Exchange Commission, In the Matter of Knight Capital Americas LLC, administrative proceeding, October 2013",
  gateIntro: "At 09:30 on 1 August 2012, when US equity markets opened, a broker-dealer's order router began pushing orders into the market at a rate far beyond anything its desk had intended, eventually executing more than four million trades in 154 stocks. System emails referencing an error condition had gone out to a group of staff more than an hour before the open and were not treated as alerts by anyone. It took the technology team roughly forty-five minutes to stop the flow, and their first remediation step made the rate worse. The firm realised a loss of over 460 million dollars.",
  idea: "A partial deployment plus a repurposed flag means the old meaning of that flag is still live somewhere, and when the effect of the change is external state there is no rollback to perform.",
  why: "Knight deployed new order-routing code to eight servers manually. One did not receive it. The new code reused a flag that in the old code had activated Power Peg, a function retired in 2003 whose code had been left in the binary and whose fill-tracking dependency had been moved in 2005. On the seven updated servers the flag meant the new thing. On the eighth it meant Power Peg, which sent child orders continuously because the counter that was supposed to stop it no longer counted.\n\nThe recovery is the lesson. Facing a runaway, the team's first action was to remove the new code from the seven servers that had it - a rollback, and a reasonable instinct. That gave all eight servers the old flag semantics, so the behaviour spread from one server to eight and the order rate rose for roughly twenty minutes before they stopped it properly. And there was nothing to undo at the end: the orders were filled, the position was real, and the only remaining action was to sell it at a loss. Dead code left in the binary is a loaded weapon; a reused flag is the trigger; a manual eight-server deploy is the hand.",
  failureMode: "You have a partial rollout because one node's pull failed, or one cluster's Argo sync is stuck, or one region's Helm release timed out and nobody chased it. The mixed fleet is not a degraded version of either state, it is a third state nobody designed. Then the rollback broadcasts the old semantics to everything.",
  experiment: "Pick one flag or feature key currently in your config store and grep the whole repository for it, including deleted-but-present code paths and any branch older than a year. Then check every cluster for the current value of that key. If any two clusters disagree, or if the grep finds more than one consumer, write down which one you did not know about.",
  reflection: "Which of your changes produce external state that cannot be rolled back, and what is the actual stop mechanism for each - not the rollback, the stop?",
  recall: {
    q: "Knight Capital's first remediation step was a rollback, and it made the incident worse. Why?",
    a: "The new deploy had reached seven of eight servers, and it had reused a flag whose old meaning activated retired code. Removing the new code from the seven restored the old meaning everywhere, so instead of one server misbehaving, all eight did.\n\nThe deeper problem is that there was nothing to roll back to. The effect was executed trades, which are external state. Once a change writes to the outside world the pipeline no longer has an undo, only a stop."
  },
  deepDive: "Walk through my Argo to Temporal cutover and identify every point where a partial rollout leaves the fleet in a third state, and where a rollback would broadcast the old behaviour rather than contain it."
},
{
  id: "config-canary-population-coverage",
  track: "config", level: "mechanism",
  title: "Canaries only catch the failures your canary population can experience",
  source: "Google, The Site Reliability Workbook, chapter 16, Canarying Releases",
  gateIntro: "A change goes through the pipeline. It sits on the canary fleet for the standard bake period taking real production traffic, the error rate and latency gates stay green throughout, and promotion proceeds automatically. Some hours after the change reaches the full fleet, the failure appears and is unambiguous. Every gate had reported green, and every gate had been reporting honestly about what it could see.",
  idea: "A canary is a statistical experiment whose power is set by the traffic it receives, the time it runs and the population it samples, and a canary that cannot experience the failure provides confidence without providing coverage.",
  why: "The workbook frames canarying as hypothesis testing: the null is that the canary behaves like the control, and you are looking for evidence to reject it. That framing makes the three failure modes explicit. Insufficient traffic means the effect size you can detect is larger than the effect you have. Insufficient duration means you promote before the incubation period elapses - memory leaks, cache fill, cert expiry, cron-triggered paths and anything that only fires at the hour boundary all live here. And an unrepresentative population means the failing input never arrives at the canary at all.\n\nThe third is the one that gets multi-tenant platforms. Canary selection is usually implicit: whichever pods the deployment controller happens to update first, or a fixed small cluster. That set of pods serves whichever tenants route to it. If the failure needs a particular data shape - the tenant with two million assets, the one whose lineage graph has a cycle, the one still on the old connector - then canary success means only that the failing tenant was not in the sample. You have measured your routing, not your change.",
  failureMode: "The change goes to the canary and the canary serves your five largest tenants because they generate most of the traffic. The failure needs a tenant with an empty catalogue and a null default connection, which is your smallest tenants, who route elsewhere. Green canary, then the long tail breaks at full rollout and the error rate never crosses the aggregate threshold because those tenants are a rounding error in request volume.",
  experiment: "For one deployment, work out which tenants actually land on the canary pods. Then take your list of known awkward tenants - biggest, oldest, weirdest schema, the one with the custom connector - and check how many are in that set. If the answer is zero, your canary is sampling convenience, not risk.",
  reflection: "What is the incubation period of the last failure that got past a canary, and how does it compare with your bake time?",
  recall: {
    q: "Name the three ways a canary can be green and wrong.",
    a: "Too little traffic, so the experiment lacks the power to detect the effect. Too little time, so the failure's incubation period exceeds the bake window. And an unrepresentative population, so the input that triggers the failure never reaches the canary.\n\nIn a multi-tenant system the third dominates, because canary membership is usually decided by pod ordering or routing rather than by deliberate selection of the tenants whose data shapes are unusual."
  },
  deepDive: "Design a canary tenant set for my platform that deliberately includes the awkward data shapes, and tell me what it would cost in rollout time."
},
{
  id: "config-cloudflare-waf-regex-global",
  track: "config", level: "amplifier",
  title: "Cloudflare, 2 July 2019: a WAF regex is code and it deployed everywhere at once",
  source: "John Graham-Cumming, Details of the Cloudflare outage on July 2, 2019, Cloudflare blog",
  gateIntro: "At 13:42 UTC on 2 July 2019, Cloudflare's edge started returning 502s for most traffic through the network. CPU utilisation on the machines serving that traffic went to effectively 100 percent in every data centre simultaneously - the graph is a vertical line, not a curve. Traffic dropped by around 80 percent. The team had trouble reaching their own internal systems to diagnose it, because those systems were served through the same path. A global mitigation restored service after about 27 minutes.",
  idea: "Anything that changes behaviour at runtime is code regardless of what file it lives in, and a change classified as data will be shipped by a data pipeline that has none of the staging a code pipeline has.",
  why: "The trigger was a single expression in a managed WAF rule containing a nested quantifier over an overlapping character class. On most inputs it matched quickly. On some inputs the backtracking was superlinear and one match consumed a core. The regex was not compiled with a backtracking limit, so nothing bounded the cost per request.\n\nThe amplifier is the deploy channel. Managed rules were treated as data, and data updates were designed to be fast and global so that a new attack signature reaches the edge in seconds. That property is exactly what you want for a WAF and exactly what makes it a fleet-wide code deploy with no canary. The failure mode is also the worst kind for the edge: not a crash, which fails a health check and sheds the machine, but CPU saturation, which leaves the machine up and useless. And because Cloudflare's own tooling sat behind the same edge, the people fixing it were locked out by the thing they were fixing. Recovery was a global kill switch for the WAF, which is the right control to have built in advance and the only one available in the time budget.",
  failureMode: "Your equivalent is anything an operator can change without a pull request that then executes in the request path: OPA or Kyverno policies, an ingress annotation with a Lua or CEL snippet, a ClickHouse materialised view definition, a dynamically loaded Temporal search attribute mapping, a jq filter in a workflow template. Each has a distribution channel built for speed.",
  experiment: "List every mechanism in your platform that changes runtime behaviour without going through the code pipeline. For each, write down the propagation time to the whole fleet and the name of the kill switch. Any row where the propagation time is under a minute and the kill switch column is blank is a July 2019.",
  reflection: "Which of your runtime-behaviour-changing channels has no per-request cost bound, and what would you disable to stop it?",
  recall: {
    q: "Cloudflare deployed code through a staged pipeline and still took the whole edge down in seconds. What was the classification error?",
    a: "The change was a WAF rule, and rules were classified as data. The data channel was built to push new attack signatures globally in seconds, which meant a rule update was an unstaged global deploy of something that executes on every request.\n\nThe rule contained catastrophic backtracking with no CPU bound per match, so it saturated every core in the fleet at once. The failure did not fail health checks, so nothing shed load. Recovery was a pre-built global kill switch for the WAF."
  },
  deepDive: "Enumerate every channel in my platform that changes request-path behaviour without a pull request, and tell me which of them lacks both a cost bound and a kill switch."
},
{
  id: "config-cloudflare-duplicate-rows-flap",
  track: "config", level: "mechanism",
  title: "Cloudflare, 18 November 2025: valid syntax, catastrophic semantics, regenerated every few minutes",
  source: "Cloudflare, Cloudflare outage on November 18, 2025, Cloudflare blog",
  gateIntro: "At about 11:20 UTC on 18 November 2025, Cloudflare's network began returning 5xx errors for a large share of traffic. The first hypothesis inside the company was a very large attack, helped along by an unrelated third-party status page going down at almost the same moment. Then the errors stopped and traffic recovered. Then they came back. The pattern repeated on a roughly five-minute cycle for over an hour before the failure settled into being continuous. Core traffic was restored in the early afternoon and full restoration took most of the working day.",
  idea: "A configuration artefact that is generated on a schedule rather than deployed once will oscillate between good and bad while the underlying cause persists, and oscillation reads as an external attack rather than as an internal change.",
  why: "A permissions change on a ClickHouse cluster caused a query against the column metadata to start returning rows the query had never seen before, because the underlying tables were now visible under more than one database name. The query had no reason to deduplicate, so the generated bot management feature file doubled in size. The proxy that consumed that file preallocated memory for a bounded number of features, and the oversized file exceeded that bound, so the Rust code hit an unhandled error and the proxy failed. Every field in the file was well formed. The syntax was perfect. The semantics were fatal.\n\nThe flapping is the part to memorise. The file was regenerated every five minutes, and the permissions change had only reached some nodes of the ClickHouse cluster. A generation run on an updated node produced the bad file; a run on a node not yet updated produced a good one. So the platform alternated between healthy and broken on the generation cadence. An intermittent, network-wide, self-resolving-then-recurring failure is the signature of a distributed attack, which is exactly what the responders reasonably suspected first, and every minute spent on that hypothesis was a minute not spent on the config artefact. Recovery required stopping generation and propagation, then pushing a known-good file, then restarting the proxy.",
  failureMode: "You have generated configuration too. A tenant routing table built from a ClickHouse query on a cron, a Temporal task queue mapping assembled from the catalogue, an allowlist rebuilt hourly. A schema, permission or replication change upstream alters the result set without altering the query, and the artefact is regenerated into production without anyone deploying anything.",
  experiment: "Find every artefact in your platform that is generated by a query and consumed by a running service. For each, check two things: does the consumer assert on the artefact's size and shape before loading it, and does the generator refuse to publish when the output differs from the previous version by more than some threshold. Count how many have neither.",
  reflection: "Which generated artefact in your estate would double in size if an upstream permissions or schema change made a query return duplicates, and what would notice?",
  recall: {
    q: "What made the 18 November 2025 Cloudflare failure present as an attack rather than as a configuration change?",
    a: "The bad artefact was regenerated on a five-minute schedule, and the upstream permissions change had only propagated to part of the ClickHouse cluster. Generation runs alternated between producing a good file and a bad one, so the network alternated between healthy and failing.\n\nIntermittent, network-wide, self-recovering failure is the signature of a volumetric attack, so the initial hypothesis was wrong in a way that was entirely reasonable and still cost time."
  },
  deepDive: "List the configuration artefacts in my platform that are generated from a ClickHouse query and loaded by a running service, and tell me what each consumer does when the artefact is twice the expected size."
},
{
  id: "config-crowdstrike-content-channel",
  track: "config", level: "amplifier",
  title: "CrowdStrike, 19 July 2024: content updates that ship outside the code release process reach every host at once",
  source: "CrowdStrike, Channel File 291 External Technical Root Cause Analysis, 2024",
  gateIntro: "Beginning at 04:09 UTC on 19 July 2024, Windows hosts running a widely deployed endpoint agent started bugchecking. Around 8.5 million machines were affected. The vendor identified and reverted the trigger within about 78 minutes, and that reversion did nothing at all for any host that had already crashed. Airlines, hospitals and payment networks were disrupted for days, because bringing a machine back required physical or out-of-band access to it, in many cases to type a recovery key by hand.",
  idea: "Splitting your release process into a staged code channel and an unstaged content channel means the unstaged channel is the one that will take everything down, and if the consumer runs in kernel mode the blast radius includes your ability to fix it remotely.",
  why: "The sensor shipped through a staged release process. Rapid Response Content did not, by design: it exists so that a new threat signature reaches every endpoint in minutes. A template type in the sensor expected 21 input fields; the integration supplying them provided 20. A content instance that referenced the twenty-first caused an out-of-bounds read in the content interpreter. The validator that was supposed to catch mismatches had a defect and passed it. The content then went to every host on the channel at once.\n\nThe amplifier that makes this the defining outage of its year is not the crash, it is the recovery topology. The failing component ran in kernel mode, so the host bugchecked during boot, before networking and before the agent could receive its own reversion. The fix pipeline required the machine to be reachable and the machine could not become reachable. Remote remediation, the thing every fleet operator relies on, evaporated. Full-disk encryption then removed the last automated path, because the recovery key lived in a system many organisations could no longer reach either. Every step of the recovery was a human standing in front of a screen.",
  failureMode: "Ask of every remote update channel you own: if this update makes the host unable to start, can the next update reach it? Anything in an init container, a CNI plugin, a node bootstrap script, a DaemonSet that gates readiness, or a mutating webhook occupies the same position. The update that breaks boot is the update you cannot undo remotely.",
  experiment: "Write the list of things your platform pushes to nodes or pods outside the application deploy pipeline: node agent configs, CNI updates, kernel modules, sidecar images pinned to a floating tag, admission policies. For each, answer whether a bad push leaves the node able to receive the next push. Any no is a manual recovery per node, multiplied by your node count.",
  reflection: "How many nodes would you have to touch by hand, and how long would that take with the people who are actually awake?",
  recall: {
    q: "CrowdStrike reverted the bad content in 78 minutes. Why did that not end the incident?",
    a: "The failing component ran in kernel mode, so affected hosts bugchecked during boot before networking came up. A host that cannot boot cannot receive the corrected content, so the reversion only protected machines that had not yet crashed.\n\nRecovery therefore required physical or out-of-band access to each machine individually, and full-disk encryption meant many of those machines needed a recovery key entered by hand. The blast radius of the change included the channel that would have fixed it."
  },
  deepDive: "Identify everything my platform pushes to Kubernetes nodes outside the application deploy pipeline, and tell me which of those, if bad, would leave the node unable to receive the fix."
},
{
  id: "config-azure-flighting-bypassed",
  track: "config", level: "mechanism",
  title: "Azure Storage, 18 November 2014: the flighting process existed and was bypassed",
  source: "Jason Zander, Update on Azure Storage Service Interruption, Microsoft Azure blog, November 2014",
  gateIntro: "On 18 November 2014, Azure Storage became unavailable across the majority of regions at once, and because a great many other Azure services sit on Storage, Virtual Machines, Websites and others failed with it. Impact lasted for many hours, with a residual set of storage nodes taking longer still. The change involved had already been running in production in a subset of clusters for several weeks without incident.",
  idea: "A staged rollout process that can be skipped is not a control, and the strongest evidence that it can be skipped is that it was, by a competent engineer, on the day it mattered.",
  why: "A performance improvement for the Azure Storage Table front ends had been flighted in production for weeks. The improvement was enabled by a configuration switch. When the team moved to enable it more broadly, the change was applied across the fleet rather than through the standard incremental deployment. A bug in the front end meant that when the switch was applied, the front end entered an infinite loop and stopped taking traffic. Applied incrementally, that bug takes down a slice. Applied broadly, it takes down Storage.\n\nTwo things follow. First, weeks of successful production flighting is evidence about the code path under the old switch value, not about the transition. The bug was in what happened when the setting changed, and flighting had not exercised that transition at scale. Second, the failure mode was a hang rather than a crash, so nothing self-healed and recovery required restarting the front ends everywhere. Zander's post is unusually direct about the process point: the incremental deployment policy existed, it was not followed, and the fix was to make it enforceable rather than advisory. That is the correct conclusion. A checklist that lives in a runbook is a suggestion; a pipeline that physically cannot promote without a soak is a control.",
  failureMode: "Your rollout policy says four waves with a soak between them. Someone with cluster-admin runs helm upgrade across all clusters because the change is small, or an Argo CD app with automated sync and no sync windows fans a values change out to every cluster in one reconcile. Nothing rejected it, because nothing was in a position to.",
  experiment: "Try to break your own rollout policy. From your normal access, see how few actions it takes to apply a configuration change to every production cluster at once. If you get there without an override, an approval or an error, your staged rollout is documentation.",
  reflection: "Who in your organisation can bypass staged rollout today, and does the bypass leave a record that someone reads?",
  recall: {
    q: "Azure had flighted the 2014 Storage change in production for weeks. Why was that not protection?",
    a: "The flighting exercised the code path with the new setting in a subset of clusters, but the bug was in the front end's behaviour when the configuration switch was applied. Broad application triggered an infinite loop, so the front ends hung rather than crashed and nothing self-healed.\n\nThe process point matters more than the bug. The standard incremental deployment policy existed and was not followed. A rollout control that depends on the operator choosing to use it will eventually not be used."
  },
  deepDive: "Show me, concretely, the shortest path by which someone on my team could apply a config change to every production cluster at once, and what would have to change to make that path impossible rather than discouraged."
},
{
  id: "config-fastly-latent-defect",
  track: "config", level: "mechanism",
  title: "Fastly, 8 June 2021: a valid customer configuration triggered a bug that had shipped weeks earlier",
  source: "Nick Rockwell, Summary of June 8 outage, Fastly blog, 2021",
  gateIntro: "At 09:47 UTC on 8 June 2021, 85 percent of a global CDN's network began returning errors and a long list of well known sites went dark at the same moment. The provider detected it within about a minute. Working out what to do took about 49 minutes, after which 95 percent of the network was serving normally again. Recovery, once the mitigation was identified, was quick. Explaining why the failure happened at that particular minute took considerably longer.",
  idea: "When the change that introduces a defect and the change that triggers it are separated by weeks, the deploy log is the wrong place to look and looking there anyway is where the time goes.",
  why: "Fastly began a software deployment on 12 May that contained a bug reachable only under a specific customer configuration. Nothing was wrong for four weeks. On 8 June a customer pushed a configuration change that was entirely valid, within their rights, and unremarkable, and it took out most of the network. Two changes were required for the failure and neither was defective on its own.\n\nThis breaks the standard first move. At 09:48 the on-call opens the deploy timeline and finds nothing, because the causal change is 27 days back and the triggering change belongs to a customer and probably is not in the platform's change log at all. In a multi-tenant system, tenant-initiated configuration is a change stream you do not control, do not review and often do not record alongside your own. The right instinct when the deploy log is clean is not to conclude that nothing changed, it is to ask which of the change streams you do not own moved. Fastly's own remediation was the honest one: find why the specific combination went undetected, and fix the detection rather than only the bug.",
  failureMode: "Your Argo to Temporal cutover ships a worker change that handles a workflow input shape nobody currently sends. Three weeks later a tenant enables a connector that produces exactly that shape. The platform deploy log is clean, the tenant's action is a supported product feature, and the two are in different systems with different retention.",
  experiment: "Build one Grafana view that overlays platform deploys, config changes and tenant-initiated configuration events on a single time axis for the last thirty days. If tenant events are not currently emitted as annotations, that gap is the finding, and it is the one to fix first.",
  reflection: "Which tenant-initiated actions can change your platform's execution path, and are any of them on the same timeline as your deploys?",
  recall: {
    q: "Fastly's network failed on 8 June 2021 but the causal deploy was on 12 May. What does that pattern do to incident response?",
    a: "It invalidates the first move. The on-call checks the deploy timeline, finds nothing recent, and concludes the failure is not change-related, when in fact two changes were required: a latent defect from weeks earlier and a triggering configuration pushed by a customer.\n\nIn a multi-tenant platform the triggering change often belongs to a tenant and is not recorded in the platform's change log at all. A clean deploy log should prompt the question of which change stream you do not own moved, not the conclusion that nothing changed."
  },
  deepDive: "Work out which tenant-initiated configuration actions in my platform can reach a code path that platform deploys also touch, and design the annotation stream that would put both on one timeline."
},
{
  id: "config-cells-bound-blast-radius",
  track: "config", level: "mechanism",
  title: "Cells bound the blast radius that staged rollout only delays",
  source: "Amazon Web Services, Reducing the Scope of Impact with Cell-Based Architecture, AWS whitepaper, 2023",
  gateIntro: "A platform runs a staged rollout with four waves and a bake at each. Over two years it has caught most bad changes in wave one, and the team's confidence in it is well earned. Then a change clears every wave gate cleanly and fails only under a load pattern that does not exist below full scale. Every tenant in the estate is affected inside the same minute. The rollout policy performed exactly as designed and nothing about it was misconfigured.",
  idea: "Staged rollout controls how fast a bad change spreads; only partitioning into independent cells with independent control planes controls how far it can spread at all.",
  why: "The two mechanisms are often confused because both are described as reducing risk. They do different things. Staged rollout is temporal: it buys detection time by ordering the exposure, and its protection is entirely conditional on someone or something noticing during the window. If the failure needs full scale, or the metric that would show it is aggregated, or the pipeline promotes faster than the alarm fires, staged rollout delivers the same end state slightly later. Cell partitioning is spatial: the estate is divided into independent instances of the whole stack, each with its own control plane, and a change or a fault confined to one cell cannot reach the others because there is no shared component through which it could travel.\n\nThe design work is in the boundary, and the whitepaper is clear that shared components are where cell architectures leak. A shared control plane, a shared identity service, a shared database, a shared config store: any of these turns your cells back into one system with extra hostnames. For a tenant-scoped SaaS the mapping is natural, because tenants are already the partition key. The cost is real and worth naming: more infrastructure, per-cell capacity headroom, a router that must itself be simple enough not to become the shared failure domain, and operational tooling that has to work across N cells instead of one.",
  failureMode: "You have cells in name only. Separate clusters per region, but one Temporal namespace, one shared ClickHouse for observability that everything writes to synchronously, one global config store that every cluster reads on startup, one CI pipeline that pushes to all of them. The bad change travels through the shared component and the cell boundary was decorative.",
  experiment: "Draw your intended cell boundary, then list every component that sits on both sides of it. Config stores, identity, DNS, the deploy pipeline, the metrics path, the message bus. For each, ask whether a failure in it takes out more than one cell. That list is the actual size of your blast radius, whatever the diagram says.",
  reflection: "What is the largest number of tenants a single bad change can reach in your platform today, and which shared component sets that number?",
  recall: {
    q: "What does cell partitioning give you that staged rollout does not?",
    a: "Staged rollout is temporal. It orders the exposure and buys detection time, but if detection does not happen inside the window the change still reaches everything. Cell partitioning is spatial: independent instances with independent control planes mean a fault has no path to the other cells at all.\n\nThe whole property depends on the absence of shared components. One shared config store, control plane or database on the cell boundary reduces the architecture to a single system with more hostnames."
  },
  deepDive: "Given my multi-tenant Kubernetes estate, propose a cell boundary and then list every component that currently crosses it, ordered by how many tenants it would take down."
},
{
  id: "config-flag-is-an-untracked-deploy",
  track: "config", level: "mechanism",
  title: "A feature flag is a deploy with no version, no review and no rollback record",
  source: "Pete Hodgson, Feature Toggles (aka Feature Flags), martinfowler.com, 2017",
  gateIntro: "An incident starts at 14:12. The team pulls up the deploy timeline for the service and the last pipeline run was two days ago. The repository's git log shows nothing relevant. Infrastructure changes for the day are empty. Every system the team treats as a change log is quiet, and the service demonstrably behaved differently at 14:12 than it did at 14:11.",
  idea: "Flags move the release decision out of the pipeline and into a runtime store, so unless flag changes carry the same audit trail and staged rollout as code, they become the largest untracked source of production change you have.",
  why: "Hodgson's taxonomy is the useful part: release toggles, experiment toggles, ops toggles and permissioning toggles have different lifetimes, different owners and different change rates, and conflating them is where the trouble starts. A release toggle should be short-lived and removed. An ops toggle is long-lived by design and is flipped during incidents. A permissioning toggle may live for years and is effectively part of the product. The same UI flips all four, and that UI usually sits outside the deploy pipeline entirely.\n\nWhat the pipeline gives code and typically does not give flags: a version, a diff, a reviewer, a staged rollout, an automated rollback, and a durable record of who changed what when. Remove all six and you have a mechanism that can change production behaviour instantly, globally, from a web form, with the audit trail living in a vendor's dashboard that nobody has wired into their incident timeline. The second failure is accumulation. Toggles that were meant to be temporary are not removed, the combinatorial state space grows, and nothing tests the combination that is actually live. The value of flags is real; the discipline they need is the discipline of a deploy, because that is what they are.",
  failureMode: "Someone enables a flag for all tenants that has only ever been tested for two, in a dropdown, at 14:12, without telling anyone. Or worse: a flag from a project that shipped eighteen months ago is still in the code with a default that nobody has re-examined, and a config store migration resets it.",
  experiment: "Export the full list of flags in your flag store. Sort by last-modified date. Count how many have not been touched in six months and how many have no named owner. Then take the three most recently changed and check whether each change appears anywhere in your incident timeline tooling. That last number is the one that matters at 2am.",
  reflection: "If you had to reconstruct every production behaviour change in the last week, how many separate systems would you have to open?",
  recall: {
    q: "Why is a feature flag change more dangerous than a code deploy, given that it is usually smaller?",
    a: "Because the pipeline's six protections do not apply to it: no version, no diff, no reviewer, no staged rollout, no automated rollback and often no record in the timeline the on-call actually reads. It can change global production behaviour instantly from a web form.\n\nHodgson's second point compounds it. Toggles have different lifetimes by category, temporary ones do not get removed, and the live combination of flags is a state nobody has tested."
  },
  deepDive: "Take my flag store and tell me which flags could change tenant-visible behaviour globally in one action, and what it would take to get those changes onto the same timeline as my deploys."
},
{
  id: "config-bake-time-versus-detection",
  track: "config", level: "mechanism",
  title: "Bake time has to exceed your time to detect or the pipeline has already moved on",
  source: "Clare Liguori, Automating safe, hands-off deployments, Amazon Builders' Library",
  gateIntro: "A change enters an automated pipeline at 09:00. It clears the one-box stage, then the first region, then the second, then the rest, and it is running in every production cell by 09:40. At 10:15 the alarm that would have caught it fires. Nobody skipped a manual step and nobody overrode a gate. Each stage's health check was genuinely green at the moment the pipeline read it.",
  idea: "An automated pipeline that promotes a stage faster than the failure becomes visible in metrics guarantees the bad change reaches production, so bake time is a function of detection latency and not of how long the team is willing to wait.",
  why: "Liguori's description of the Amazon pipeline makes bake time a first-class artefact rather than a delay. The point of soaking a stage is to accumulate enough requests, enough time and enough alarm evaluation periods that a regression has a chance to become statistically visible before promotion. That budget has real components you can measure: the metric's scrape interval, the alarm's evaluation window and datapoints-to-alarm, the aggregation delay in your metrics store, and the incubation period of the class of failure you are trying to catch. Add them and you have a lower bound. Anything shorter is theatre with a progress bar.\n\nThere is a second half that gets dropped more often than the first. Bake time only protects you if something is watching during the bake and can act on what it sees. Amazon's pipelines attach rollback monitors to the alarms that matter, so the deployment auto-reverts on a regression rather than waiting for a human to be paged, look at a dashboard and decide. Without that, a long bake time just means the failure has more time to accumulate before a person notices. The pairing is what works: a soak long enough to observe, plus an automated reversal fast enough to matter.",
  failureMode: "Your Argo CD sync progresses on pod readiness, which is a liveness statement about the process and says nothing about correctness. Readiness goes green in ninety seconds. Your Grafana alert on workflow failure rate needs five minutes of data and three evaluation periods. The pipeline is done before the alert can exist.",
  experiment: "Take one alert you would rely on to catch a bad deploy. Add up its scrape interval, its evaluation window, its datapoints-to-alarm and any ingestion delay in your metrics path. Compare that number with the actual wall-clock time your pipeline takes to go from first stage to full rollout. If the pipeline is faster, write both numbers down and show them to whoever owns the pipeline.",
  reflection: "What is your real time to detect for the failure class you most fear, and what is your current bake time?",
  recall: {
    q: "How do you set bake time correctly, and what has to accompany it?",
    a: "Bake time is set by detection latency: scrape interval plus alarm evaluation window plus datapoints-to-alarm plus ingestion delay plus the incubation period of the failure class. If the pipeline promotes faster than that sum, the bad change reaches production before the signal can exist.\n\nIt only works paired with automated rollback on the alarms that matter. A long soak with no monitor attached just gives the failure more time to accumulate before a human happens to look."
  },
  deepDive: "Compute the real detection latency for my top three deploy-catching alerts and compare it against the wall-clock rollout time of my Argo CD and Temporal worker pipelines."
},
{
  id: "config-schema-before-ui",
  track: "config", level: "mechanism",
  title: "Configuration needs a schema, a type checker and tests before it needs a UI",
  source: "Google, The Site Reliability Workbook, chapters 14 and 15, Configuration Design and Best Practices and Configuration Specifics",
  gateIntro: "A team ships a change to a values file. The file parses, the chart renders, the service starts, the readiness probe passes and the pods report healthy. Four hours later a scheduled job for one tenant fails, and the eventual fix is a change to a single number in that same file. Nothing between the pull request and the failure was in a position to reject the value that had been written, and the reviewer had approved a one-line diff that looked entirely reasonable.",
  idea: "A configuration language that permits arbitrary values pushes all correctness checking to runtime in production, whereas a typed schema with static validation converts a class of outage into a failed build.",
  why: "The workbook's framing is that configuration is a user interface for the operator, and that the design question is what the operator has to know in order to be correct. Mandatory fields with no safe default, values whose correctness depends on another value, units left implicit, and settings whose effect is only visible under load are all interface defects. The remedy is ordered: define the schema, generate or check the config against it, then test the resulting configuration the way you test code, and only then worry about ergonomics.\n\nThe mechanism is straightforward. Every constraint you can express statically is a failure that happens in CI to one engineer instead of in production to every tenant. Types catch units and shapes. Cross-field constraints catch inconsistency, which is precisely the category Yin and colleagues found dominates real misconfigurations. Range assertions catch fat fingers. What is left, the genuinely semantic errors, is the residue that staged rollout and canarying exist to handle, and it is a much smaller residue than most teams have. Note also the workbook's separation of configuration from the mechanism that delivers it: a config that is correct and a config that has safely reached the right subset of machines are two different guarantees and need two different controls.",
  failureMode: "Your Helm chart takes a timeout as a bare integer. One caller writes seconds, another writes milliseconds, both are valid YAML, both render, and the mismatch surfaces as a tenant workflow that times out on the slow path only. Or a resource limit lower than a request, which is legal in the values file and rejected only by the scheduler, at rollout, in production.",
  experiment: "Pick your most-edited chart and write a values.schema.json for just the ten keys most likely to be wrong: types, ranges, required, enums. Run helm template against last month's values files and see how many of them the schema now rejects. Any rejection is an outage you have already had or were going to have.",
  reflection: "Which of your config keys carries an implicit unit, and what would it cost to make the unit part of the type?",
  recall: {
    q: "What is the correct order of investment in a configuration system, and why is a schema ahead of tooling?",
    a: "Schema first, then static validation against it, then tests of the resulting configuration, then ergonomics. A schema moves errors from production runtime to build time, where they cost one engineer a few minutes instead of costing every tenant an outage.\n\nCross-field constraints matter most, because the dominant class of real misconfiguration is a legal value that is inconsistent with another value, the hardware or the version. Nothing about a nicer UI catches that."
  },
  deepDive: "Look at my most-edited Helm values files and propose the schema constraints that would have caught the largest number of past changes, ranked by how likely each error class is."
},
{
  id: "config-reddit-forgotten-autoscaler",
  track: "config", level: "amplifier",
  title: "Reddit, 11 August 2016: an autoscaler nobody remembered was running woke up mid-migration",
  source: "Reddit engineering, Why Reddit was down on Aug 11, r/announcements, 2016",
  gateIntro: "On the afternoon of 11 August 2016, Reddit went down and stayed down for about an hour and a half. The site had not been under unusual load. A planned infrastructure migration was in progress, being carried out deliberately by engineers who knew the system well. Over the course of a few minutes most of the application fleet ceased to exist, and it took the operators a while to work out what was removing it, because nothing they were doing should have removed anything.",
  idea: "Automation that has been disabled by stopping a process rather than by changing a declared state will come back at the worst possible moment, and it will act on whatever it finds faster than a human can interpret what it is seeing.",
  why: "The team was migrating their Zookeeper configuration and had shut down the autoscaler for the duration, because the autoscaler reads coordination state and the coordination state was mid-move. A package operation during the migration restarted the autoscaler service. It came up, read the partially migrated state, concluded that far fewer servers should exist than did, and terminated most of the application fleet. It was doing its job correctly on incorrect input.\n\nTwo mechanisms compound here. The first is that disabling automation by stopping a process is not durable: package managers, config management, node reboots and health-check supervisors all exist specifically to restart stopped processes, so a stopped service is a service scheduled to come back. Durable disablement means changing the declared desired state, which is the thing the restart mechanism reads. The second is speed. An autoscaler with API credentials can destroy a fleet faster than a human can form a hypothesis about what is happening, so the window in which intervention is theoretically possible is smaller than the human reaction time. That is why rate limits and floor values on destructive automation are not paranoia: they convert an unrecoverable minute into a recoverable ten.",
  failureMode: "You silence an alert, cordon a node, scale a Deployment to zero or pause an Argo CD app by hand during a migration. Then Argo CD reconciles the declared state back, or a node reboot restarts the DaemonSet, or the HPA that you thought was off resumes from its manifest. The reconciliation loop is doing exactly what you configured it to do, against state you were halfway through changing.",
  experiment: "List every controller in your clusters that can delete or scale down workloads: HPA, VPA, cluster autoscaler, descheduler, Argo CD auto-sync with prune enabled, any cleanup CronJob. For each, write down how you would disable it during a migration in a way that survives a reboot and a reconcile, and what its floor is. Any controller with no floor can take the fleet to zero.",
  reflection: "During your Argo to Temporal cutover, which automation are you planning to turn off, and is the off switch declared or manual?",
  recall: {
    q: "Reddit's team had deliberately disabled the autoscaler before the migration. Why did it run anyway, and why was the damage so fast?",
    a: "They disabled it by stopping the process, not by changing declared state, and a package operation during the migration restarted it. It then read partially migrated coordination state, concluded the fleet was oversized and terminated most of it.\n\nIt was faster than human interpretation. An automation with API credentials and no floor value can destroy a fleet in less time than an operator needs to form a hypothesis, which is the argument for rate limits and minimum-instance floors on anything destructive."
  },
  deepDive: "Enumerate the controllers in my clusters that can scale down or delete workloads, and tell me for each whether my planned way of disabling it during the Temporal cutover survives a node reboot and an Argo CD reconcile."
},
{
  id: "config-cloudflare-backbone-scope",
  track: "config", level: "amplifier",
  title: "Cloudflare, 17 July 2020: a routing change has a blast radius set by the protocol, not by the deploy tool",
  source: "John Graham-Cumming, Cloudflare outage on July 17, 2020, Cloudflare blog",
  gateIntro: "At 21:12 UTC on 17 July 2020, Cloudflare's global traffic dropped by about 50 percent and 27 minutes of widespread errors followed. The affected locations were spread across North America and Europe and were not clustered anywhere a single change had been applied. The edge machines in those locations were healthy throughout and continued to serve requests locally. The mitigation was to disable one location.",
  idea: "Some configuration changes have their scope determined by a distributed protocol that will propagate them regardless of your rollout percentage, and for those changes the only meaningful containment is designing the protocol's reaction in advance.",
  why: "The change was made on the backbone in Atlanta while working on congestion there. A term added to a routing policy had the effect of advertising routes far more widely than intended, so Atlanta began attracting backbone traffic from across the network. Atlanta could not carry it. Traffic from many locations that had been perfectly healthy was pulled into a single congested point and dropped there. One router in one city, one policy term, half the global traffic.\n\nThe generalisable point is about what determines scope. A container image rollout has a scope set by your deployment controller, and you can dial it. A routing change has a scope set by the routing protocol, whose entire purpose is to propagate reachability information to everyone who needs it as fast as possible. There is no ten percent BGP. The same is true of DNS with a long TTL already cached, of anycast, of a service mesh's global config distribution, of Kubernetes NetworkPolicy across a flat CNI, and of anything else where the mechanism you are configuring is itself a propagation mechanism. Containment for these has to be designed in: policy simulation before commit, automatic commit-confirm timers that revert if not acknowledged, capacity checks in the change, and the ability to remove a location from the topology quickly, which is what actually ended this one.",
  failureMode: "Someone updates a NetworkPolicy or a mesh destination rule for one namespace, and the CNI or control plane distributes it to every node in every cluster because that is what distribution means. Or a change to a shared ingress annotation shifts routing for tenants who were never in the change's scope, because the routing layer does not know about your rollout waves.",
  experiment: "Take one change to your routing or network layer that you would classify as low risk. Trace how far the resulting state actually propagates: how many nodes, how many clusters, how many tenants receive it, and how long it takes. Compare that against the rollout percentage you would have written on the change ticket.",
  reflection: "Which layers in your stack propagate configuration by their own protocol rather than by your deploy tool, and what is the revert time for each?",
  recall: {
    q: "Cloudflare's edge machines were healthy during the 17 July 2020 outage, and locations far from the change were affected. What determined the scope?",
    a: "The routing protocol. A policy term on a backbone router in Atlanta caused routes to be advertised more widely than intended, so traffic from many healthy locations was pulled towards Atlanta, which could not carry it.\n\nA rollout percentage is meaningless for changes whose scope is decided by a propagation protocol. Containment has to come from simulation before commit, commit-confirm timers that auto-revert, and the ability to remove a location from the topology quickly."
  },
  deepDive: "Identify the layers in my stack where a configuration change propagates by the layer's own protocol rather than by Argo CD, and tell me what the revert path and revert time is for each."
},
{
  id: "config-admission-webhook-fail-closed",
  track: "config", level: "mechanism",
  title: "An admission webhook that fails closed can stop every tenant from scheduling anything",
  source: "Kubernetes documentation, Dynamic Admission Control, failurePolicy",
  gateIntro: "A shared multi-tenant Kubernetes cluster stops accepting writes. Existing pods keep running and keep serving traffic, so external synthetic monitoring stays green and no customer-facing SLO burns for the first several minutes. But no Deployment can be updated, no Temporal worker can be scaled, no Job can be created, and the platform team's own remediation, which requires applying a manifest, fails with the same error every other write is getting. The API server itself is up and answering reads normally.",
  idea: "A validating or mutating webhook with failurePolicy Fail puts its own availability in the write path of the API server, so a webhook backend outage in a multi-tenant cluster becomes a cluster-wide inability to change state.",
  why: "The tradeoff is genuine and the documentation is explicit about both sides. failurePolicy Ignore means a webhook outage silently skips your policy, so pods can be admitted without the injected sidecar, the resource quota, the tenant label or the security context you rely on. failurePolicy Fail means the policy is never skipped, and the cost is that the webhook is now a hard dependency of every API write matching its rules. Pick Ignore and you get silent policy bypass; pick Fail and you get a new single point of failure in the control plane. There is no third option, only a narrowing of scope.\n\nNarrowing is the actual engineering. The rules field decides which resources, operations, API groups and namespaces the webhook intercepts, and a webhook scoped to one CRD in one namespace has a blast radius the size of that CRD. A webhook matching every resource in every namespace has the blast radius of the cluster. Two more properties matter: namespaceSelector and objectSelector let you exclude the namespaces that must keep working, notably kube-system and your own platform namespace, so the remediation path is not gated on the thing that is broken. And timeoutSeconds bounds how long each write waits, which is the difference between a failing API and an API so slow that controllers time out and start retrying. If the webhook is important enough to fail closed, it needs to be run like a control-plane component: multiple replicas, spread across nodes, no dependency on the workloads it admits.",
  failureMode: "You install a policy engine for tenant isolation with failurePolicy Fail and rules matching all resources. The policy pods land on nodes that get drained during an upgrade. Now nothing can be created anywhere, including the pods that would restore the policy engine, and including the workloads in kube-system that the upgrade needs. You are locked out of your own cluster by the control you added to make it safe.",
  experiment: "Run kubectl get validatingwebhookconfigurations and mutatingwebhookconfigurations and for each one print failurePolicy, the rules scope, timeoutSeconds and the namespaceSelector. Flag any webhook that fails closed, matches broadly, and has no exclusion for the namespaces you would need to fix it from. Then check where its backend pods actually run.",
  reflection: "If your policy webhook's backend went down right now, which of your remediation commands would still work?",
  recall: {
    q: "What does failurePolicy Fail buy you, what does it cost, and how do you reduce the cost without switching to Ignore?",
    a: "It guarantees the policy is never bypassed, at the cost of making the webhook backend a hard dependency of every matching API write. Ignore trades that for silent policy bypass during an outage, which is often worse for an isolation control.\n\nYou reduce the cost by narrowing scope rather than by weakening the policy: tight rules on resources and operations, a namespaceSelector that excludes kube-system and your platform namespace so remediation still works, a short timeoutSeconds, and a backend run with control-plane availability rather than as an ordinary workload."
  },
  deepDive: "Audit the admission webhooks in my clusters and tell me which ones could prevent me from applying the manifest that would fix them, then propose the narrowest rules and selectors that keep the policy intact."
}
);
