/* Track: Data, schema and migration. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "data-compat-direction",
  track: "data", level: "mechanism",
  title: "Backward compatible means the new reader handles old data, and that is the direction people invert",
  source: "Martin Kleppmann, Designing Data-Intensive Applications, chapter 4",
  gateIntro: "A release goes out at 09:40 across a fleet on a rolling update. At 10:15 a fraction of requests start failing on one service. The team calls it at 10:22 and rolls back. The error rate does not fall, it climbs, and it keeps climbing after the rollback completes. Client traffic is flat throughout. Hosts running the previous image fail on a subset of rows that hosts running the new image read without complaint.",
  idea: "Backward compatibility is a property of the new reader, forward compatibility is a property of the old one, and a rolling deploy needs both at the same time.",
  why: "Kleppmann's definitions are precise and the industry uses them loosely. Backward compatible means newer code can read data written by older code. Forward compatible means older code can read data written by newer code. Backward compatibility is the easy one, because the author of the new code knows exactly what the old format looked like. Forward compatibility is the hard one, because the old code has to tolerate a shape nobody had invented when it was written.\n\nA rolling deployment runs both versions against the same store for the whole rollout window, so data flows in both directions the entire time. The moment the new version persists something the old version cannot interpret, the rollback path is gone, and it is gone silently. Rolling back removes the code, not the rows. That is why this class of incident starts at the rollback rather than at the deploy, and why the graph gets worse exactly when the mitigation lands.",
  failureMode: "A column is widened from int32 to int64. An enum gains a variant. A JSON field that was a string becomes an object. A Temporal workflow input struct gains a field the previous worker build treats as required. The new pods write it, the old half of the rolling update fails on parse, and the team rolls back into a store that now contains records only the version they just removed could read.",
  experiment: "Take the last three schema, protobuf or workflow-payload changes your team merged. For each one, answer from the diff alone whether a pod running the previous image can read a record written by the new one. Count how many you can answer. The ones you cannot answer had no rollback path and nobody noticed at review time.",
  reflection: "Which of your persisted or transmitted formats - table columns, Temporal workflow inputs and activity results, Kafka payloads, CRD spec fields - has no owner who thinks about the old reader?",
  recall: {
    q: "During a rolling deploy, which compatibility direction determines whether you can roll back, and why is it the harder one to achieve?",
    a: "Forward compatibility: the old code reading data the new code wrote. It is harder because the old version must tolerate a shape its authors never saw, which means the defensiveness had to be written before the change existed.\n\nBackward compatibility only protects the roll forward. A rollback removes the new code but not the records it already persisted, so if the old reader cannot parse them the rollback deepens the outage rather than ending it."
  },
  deepDive: "Walk our Temporal workflow input types and ClickHouse ingest schemas and tell me which recent changes left the previous release unable to read what the current one writes."
},

{
  id: "data-two-phase-deploy",
  track: "data", level: "mechanism",
  title: "Deploy the readers before the writers, always in two phases",
  source: "Sandeep Pokkunuri, Ensuring rollback safety during deployments, Amazon Builders' Library",
  gateIntro: "A service is rolled out across an autoscaling group over about 40 minutes. From the first minute, roughly half of a background job's tasks fail and half succeed, and which half depends on which host picks the task up. Overall success returns to 100 percent when the rollout finishes and the team closes the alert. Two hours later a scaling event adds capacity and the failures come back, in proportion to how many of the new hosts launched from the older image.",
  idea: "Any change to a persisted or transmitted format ships as two separate releases: one that can read the new form, and a later one that starts writing it.",
  why: "The Builders' Library rule is that a deployment is only rollback-safe if every intermediate state of the fleet is a valid state, and during a rolling deploy or a rollback the fleet is always in a mixed state. Two-phase deployment produces that property mechanically. After phase one, every host understands both the old and the new form and nothing has written the new one, so phase one is trivially reversible. After phase two the new form exists in the store, but every host already understands it, so phase two is reversible too. There is no window in which a host can encounter bytes it cannot interpret.\n\nThe corollary people skip is that phase one must be fully deployed and confirmed everywhere before phase two begins. Everywhere includes hosts an autoscaler will launch later from a cached older image, a disaster recovery region on a different release cadence, batch jobs and analytics readers that consume the same data out of band, and anything pinned to a version because someone deferred an upgrade. The mixed-version window is not the rollout window. It is however long the slowest reader takes to catch up.",
  failureMode: "A single-phase change ships on a Friday, looks clean because the rollout finished, and then bites weeks later when an autoscaler launches from a stale image, a DR region fails over, or an unrelated rollback puts a subset of hosts back onto the reader that was never taught the new form.",
  experiment: "Pick the next format change in your backlog and write both pull requests before you merge either. If the reader-only PR is empty, the change is not really a format change and you can ship it in one. If you cannot cleanly separate them, the change needs redesigning before it ships, not after.",
  reflection: "What is the longest-lived stale reader in your estate: an image an autoscaler caches, a pinned worker build, a DR region, or a Python job someone forgot?",
  recall: {
    q: "Why must phase one of a two-phase format change be confirmed everywhere before phase two starts, and where does 'everywhere' usually turn out to be larger than the rollout?",
    a: "Because phase two writes bytes that only phase-one readers can interpret, so any reader still on the pre-phase-one build encounters an unparseable record. Confirming the rollout finished is not the same as confirming every reader upgraded.\n\nEverywhere usually includes autoscaler images cached from before the rollout, DR regions on a slower cadence, out-of-band consumers such as analytics jobs and replicas, and any pinned worker version."
  },
  deepDive: "Help me find every out-of-band reader of our workflow event data, including analytics and DR, so I can size the real mixed-version window rather than the rollout window."
},

{
  id: "data-replication-not-backup",
  track: "data", level: "mechanism",
  title: "Replication copies your corruption faster than you can notice it",
  source: "Raymond Blum and Rhandeev Singh, Data Integrity: What You Read Is What You Write, Google SRE book chapter 26",
  gateIntro: "A routine batch job writes a bad set of rows into a primary at 02:14. Replication is healthy throughout: three replicas across two regions, lag under a second, no alert. A customer notices the wrong values 31 hours later. Every replica holds an identical copy of the wrong values, the failover candidate is no better than the primary, and the newest snapshot the team can locate was taken after 02:14.",
  idea: "Replication protects against hardware loss and nothing else, so data integrity needs separate layers with increasing isolation and increasing recovery time.",
  why: "Blum and Singh's framing is that the threats to data are not one thing. Hardware failure, software bugs and operator error all destroy data, but only the first is addressed by having more copies. A replica is a device for propagating whatever the primary did, faithfully and fast. When what the primary did was a bad delete or a corrupting migration, replication is the amplifier: it takes the blast radius from one machine to every machine, in under a second, with green dashboards the whole way.\n\nThe chapter's answer is defence in depth across layers that fail independently. Soft deletion first, so that user-visible and accidental deletes are reversible at the application layer within a retention window. Backups and their recovery paths second, isolated from the live system so a bug in the live system cannot reach them. Early detection third, out-of-band validators that read the data and check invariants, because the layers above only help if you find the damage inside the window in which they still hold a good copy. The chapter is explicit that backups exist to be restored, and that a system with no proven restore has no second layer, whatever its backup schedule says.",
  failureMode: "A logical corruption gets a day and a half of head start because everything monitoring the data was measuring availability and lag rather than correctness. By the time it is found, the retention window on the only isolated copy has rolled past the damage.",
  experiment: "Write one out-of-band validator today for your single most important table: a query that asserts an invariant you believe cannot be violated, scheduled, alerting when the violation count is non-zero rather than when the job fails. Run it once against production now and record the count.",
  reflection: "For your top three datasets, how long could a logical corruption sit undetected, and does that number fit inside the retention of the copy you would restore from?",
  recall: {
    q: "Name the three layers of defence in depth for data integrity, in order, and say what each one protects against that the previous one does not.",
    a: "Soft deletion, then backups with a proven recovery path, then out-of-band early detection. Soft deletion makes accidental and user-driven deletes reversible inside the application. Backups sit outside the live system, so a bug in the live system cannot reach them, and cover corruption soft deletion never saw.\n\nEarly detection is what makes the first two usable, because both have finite retention. A corruption found after the window has rolled is a corruption no backup covers. Replication sits below all three and covers only device loss."
  },
  deepDive: "Design three out-of-band integrity validators for our tenant metadata store that would catch a logical corruption within an hour rather than a day."
},

{
  id: "data-gitlab-2017-backups",
  track: "data", level: "recovery",
  title: "GitLab, 31 January 2017: five backup mechanisms and none produced a restorable artifact",
  source: "GitLab, Postmortem of database outage of January 31 2017",
  gateIntro: "On 31 January 2017, while working through replication problems on GitLab.com under load from an ongoing spam incident, an engineer ran a directory removal against a database node believing it was the secondary. It was the primary. He noticed the directory shrinking and interrupted the command about a second in, leaving roughly 4.5 GB of a 310 GB data directory. GitLab.com went offline. The team worked the recovery in public on a live-streamed document. The restore point they eventually reached was around six hours old, and the site was down for roughly 18 hours.",
  idea: "Backups that are monitored for having run, rather than for producing a restorable artifact, are not backups.",
  why: "GitLab had five separate mechanisms that a reasonable reviewer would have counted as data protection, and on the night none of them produced a usable copy. The regular pg_dump backups were being taken by a client binary a major version behind the server, so the dump errored out and wrote near-empty files. The failure notifications for that did go out, by email, to an address whose provider rejected them for DMARC, so nobody read the notice that had been arriving for months. Azure disk snapshots were enabled on the NFS server but not on the database servers. The S3 bucket the backups were meant to be synchronised to was empty. LVM snapshots were not being taken on the cadence anyone believed.\n\nThe copy that saved them was incidental: an LVM snapshot taken six hours before the incident onto staging, for an unrelated load-testing purpose. Recovery was then slow for a reason worth noticing separately, which is that nobody had ever timed a restore of this size. Copying the data back to production over the available link took hours that nobody had budgeted for, because the plan had only ever been validated as far as 'the backup exists'.",
  failureMode: "Every dashboard says green because every dashboard is watching a job's exit status, a cron entry or a bucket's existence. The first time anyone reads the actual artifact is during an outage, which is also the first time anyone measures how long reading it takes.",
  experiment: "Restore yesterday's backup of your most important datastore into a scratch namespace today. Time it end to end and run one real query against the result. Write down the wall-clock number and the count of steps that required a person to remember something undocumented. Both numbers are your real RTO.",
  reflection: "Which of your recovery paths has produced a verified restorable artifact in the last 90 days, as opposed to a successful job run?",
  recall: {
    q: "GitLab had five data protection mechanisms in place. What single check, applied to all five, would have found that none of them worked, and why did their existing monitoring miss it?",
    a: "Periodically restoring from each mechanism and reading the result. Their monitoring watched whether backup processes ran and whether configuration existed, which is satisfied by a pg_dump that errors out and writes an empty file, by an S3 sync to an empty bucket, and by snapshots configured on the wrong hosts.\n\nThe failure notifications that would have surfaced the pg_dump version mismatch were sent by email to an address that rejected them, so a monitoring signal existed and was undeliverable for months. A restore test does not depend on anyone reading a notification."
  },
  deepDive: "Build me a scheduled restore-and-verify job for our primary Postgres and ClickHouse data that fails loudly when the restored artifact does not satisfy a real query."
},

{
  id: "data-dual-write-divergence",
  track: "data", level: "mechanism",
  title: "Dual write during a migration hides divergence until you compare",
  source: "Jacqueline Xu, Online migrations at scale, Stripe engineering (2017)",
  gateIntro: "A team completes a long migration of a core table to a new store, cuts reads over cleanly, watches error rates stay flat for two weeks, and decommissions the old table on a Thursday. Support tickets about missing or stale records start the following Monday at a few a day, all from long-tenured accounts, none reproducible on demand. The new store is internally consistent. No error was logged at any point during the migration. The records the customers are describing cannot be produced from anything the team still holds.",
  idea: "The comparison phase is the only part of a dual-write migration that can tell you the two stores disagree, so skipping it means learning about the drift after the old store is gone.",
  why: "Stripe's four-phase pattern is dual write to old and new, backfill the historical rows, read from the new store while comparing against the old, then cut over and retire. The phases people find easy to justify are the first two, because they produce visible progress. The third produces nothing except a discrepancy count, which is why it is the one that gets compressed when the migration runs late.\n\nDual writing does not give you equivalence. It gives you two write paths that agree only when every code path goes through the wrapper, every failure is atomic across both stores, and the backfill's view of history matches what the live writes assumed. None of those hold by default. Partial write failures leave one store ahead. An admin script or a job written before the wrapper existed writes to only one. The backfill races live writes on the same rows and the loser wins. Each of these produces a small, quiet, unevenly distributed divergence, and the only instrument that sees it is a read-time comparison with a counter attached.",
  failureMode: "Divergence concentrates in exactly the rows least likely to be sampled: old accounts, unusual states, records touched by a legacy admin path. It is invisible while the old store still exists, and unrecoverable the moment it does not.",
  experiment: "For any migration currently in flight in your estate, including the Argo to Temporal cutover, find the discrepancy counter. If there is not one, write a job today that reads N rows from both sides and emits a count of mismatches by field. Run it once. Any non-zero result is your migration's real status.",
  reflection: "For the migration you are running now, what is the discrepancy rate, and if you cannot state it as a number, what exactly are you planning to rely on at cutover?",
  recall: {
    q: "In a four-phase dual-write migration, which phase is the only one that can detect divergence, and name three ordinary reasons the two stores drift even when both writes appear to succeed.",
    a: "The dual-read-with-comparison phase. Nothing in dual writing itself asserts equivalence, and nothing in the backfill does either.\n\nDrift comes from partial write failures where one store commits and the other does not, from write paths that bypass the dual-write wrapper such as admin scripts and older jobs, and from the backfill racing live writes on the same rows. Each is quiet and unevenly distributed, which is why it concentrates in rows nobody samples."
  },
  deepDive: "Design the comparison phase for our Argo to Temporal cutover: what to compare, at what sample rate, and what discrepancy rate should block the cutover."
},

{
  id: "data-backfill-load",
  track: "data", level: "mechanism",
  title: "A backfill is production load with no user waiting for it",
  source: "Shlomi Noach, gh-ost: GitHub's online schema migration tool (2016)",
  gateIntro: "A schema migration on a large table is started at 14:30 on a Tuesday, inside an agreed low-traffic window. Forty minutes in, p99 latency on endpoints that do not touch that table goes from around 120 ms to several seconds, and read replicas start serving results minutes stale. Client traffic is normal for a Tuesday. The migration reports no progress percentage, and the engineer running it does not know whether interrupting it is safe.",
  idea: "Migration tooling must throttle against a live production signal and be interruptible at any instant, because a backfill that cannot pause converts your capacity margin into an outage on a schedule you do not control.",
  why: "The design argument Noach makes for gh-ost is that the migration is a first-class production workload and should be built like one. It copies rows in controlled chunks, it reads the binary log rather than installing triggers on the hot table, and critically it throttles on a signal that reflects actual production health, primarily replication lag, with the throttle adjustable while the migration is running and a hard pause available at any moment. It is also resumable, because a migration you can only abandon is a migration you will not stop.\n\nThe mechanism this defends against is that a backfill has no natural back-pressure. A user request that gets slow produces an unhappy user and eventually a timeout, which sheds load. A backfill loop that gets slow just runs longer at the same intensity, consuming IO, buffer pool and replication bandwidth at whatever rate the loop was written to. The contention shows up on unrelated queries first, because they are the ones with a latency budget. And a backfill scheduled for a quiet window is scheduled against last week's traffic, not against whatever is happening today.",
  failureMode: "A one-off script with a tight loop and no sleep saturates IO, replication lag climbs, read replicas serve stale data, and the on-call engineer cannot stop the script because stopping it halfway leaves the data in a state nobody defined.",
  experiment: "Take the last backfill or migration script your team ran and answer two questions from the source: what live signal does it read to decide whether to slow down, and what happens if you send it SIGTERM at a random point. If the answers are 'none' and 'unknown', that script is an unscheduled outage waiting for a busy afternoon.",
  reflection: "Which of your tenant-scoped batch jobs can saturate shared infrastructure, and what would the other tenants see first?",
  recall: {
    q: "Why does a backfill create more risk than an equivalent volume of user traffic, and what two properties make one safe?",
    a: "User traffic has natural back-pressure: slow requests time out, users retry less, load sheds. A backfill loop has none - when it gets slow it simply runs longer at the same intensity, so it keeps consuming IO and replication bandwidth while the contention surfaces on the latency-sensitive queries beside it.\n\nThe two properties are throttling against a live production signal such as replication lag, adjustable while running, and being interruptible and resumable at any point so that pausing is a decision anyone can make in seconds."
  },
  deepDive: "Review our tenant backfill jobs for a throttle that reads a live signal and for safe interruption, and tell me which ones are unsafe to run during business hours."
},

{
  id: "data-crd-conversion",
  track: "data", level: "mechanism",
  title: "Argo Workflows: a CRD schema change with no conversion path orphans the objects mid-flight",
  source: "Kubernetes documentation, CustomResourceDefinition versioning and conversion webhooks",
  gateIntro: "A controller upgrade is applied to a cluster running several thousand workflows. Workflows submitted after the upgrade run normally end to end. Workflows that were mid-flight when the upgrade landed stop advancing: their pods finish and exit zero, their objects stay in the cluster, and the controller logs nothing about them at all. Reconcile queue depth is flat, controller CPU is idle, and no error rate anywhere is elevated.",
  idea: "Custom resources are persisted at a stored version, so changing their shape without a conversion path leaves the controller unable to interpret the objects that already exist.",
  why: "A CRD is a database schema with a Kubernetes API in front of it. Objects are serialised into etcd at the CRD's designated storage version and stay in that encoding until something rewrites them. The API server will serve an object at a requested version, but with the default None conversion strategy all it does is rewrite the apiVersion field. It does not move data between differently shaped fields, and it does not tell you it declined to. So a controller that now expects a field somewhere else reads an object where that field is absent, and absent is not an error, it is a zero value.\n\nThis is the estate-local form of the unreadable-rollback problem, with two aggravations. The persisted objects are live state, not history: an in-flight Argo workflow's node status is the only record of where it got to, so a misread is not a stale row, it is a lost execution. And the rollback is worse than the roll forward, because objects written by the new controller are now in the store and the old controller has the same problem in reverse. The correct mechanism is a conversion webhook, or the discipline of only ever adding optional fields and never moving or repurposing an existing one.",
  failureMode: "Workflows submitted before the upgrade sit forever in a state the controller silently skips, their pods complete without anyone recording it, and the operator's instinct - roll the controller back - leaves the objects the new controller wrote equally unreadable in the other direction.",
  experiment: "For every CRD in your clusters, check whether spec.conversion.strategy is None and whether status.storedVersions lists more than one version. Any CRD with multiple stored versions and no webhook has objects in etcd that only one version of your code understands. Count them.",
  reflection: "Which of your operators would notice that it is skipping objects it cannot interpret, versus which would just go quiet on them?",
  recall: {
    q: "With the default conversion strategy, what does the API server actually do when a client requests a custom resource at a different version than it was stored in, and why is that dangerous for a controller?",
    a: "It rewrites the apiVersion field and nothing else. No data moves between fields that changed shape, and no error is raised.\n\nA controller reading a moved or renamed field therefore sees an absent field, which deserialises to a zero value rather than a failure. For in-flight workflow objects the persisted status is the only record of execution progress, so a silent zero value is lost state, not a stale read."
  },
  deepDive: "Audit our Argo and Temporal-related CRDs for stored version drift and tell me which schema changes we have made that needed a conversion webhook and did not get one."
},

{
  id: "data-poison-message",
  track: "data", level: "mechanism",
  title: "One message that cannot be processed stops the partition behind it",
  source: "Gregor Hohpe and Bobby Woolf, Enterprise Integration Patterns, Dead Letter Channel (2003)",
  gateIntro: "Consumer lag on one partition of a topic starts climbing at 03:00 and rises in a straight line all night. The other eleven partitions sit at zero. The consumer group is healthy, every member is alive and rebalancing normally, CPU is low. The consumer's reported per-message processing rate for the stuck partition reads as several hundred a second. No alert fires, because the service's own success rate is 100 percent and its error rate is zero.",
  idea: "Ordered consumption plus unbounded retry on a message that can never succeed means the queue never drains, and the fix is a bounded attempt count plus a channel for messages that cannot be processed.",
  why: "Hohpe and Woolf separate two cases that get conflated. An invalid message is one the receiver cannot interpret at all, and it goes to an Invalid Message Channel because it is a sender problem, not a delivery problem. A dead letter is a message the messaging system could not deliver. The engineering point common to both is that there must exist a terminal disposition other than success. A consumer whose only two outcomes are 'processed' and 'try again' has no way to make progress past a message that will fail deterministically for the rest of time.\n\nThe amplifier is ordering. On an unordered work queue a poison message burns a worker and the rest of the queue drains around it, which is a capacity problem. On an ordered partition it is a head-of-line block, so a single malformed record stops every message behind it for that key or partition, indefinitely, while every health signal reads normal. Worse, the retry loop often looks like throughput: the consumer really is processing hundreds of messages a second, all of them the same one.",
  failureMode: "A tenant emits one record with an unexpected null or an oversized field. Their partition stops draining at 03:00. Nothing pages, because lag alerting is set on the aggregate across partitions and eleven of twelve are at zero. The tenant discovers it at 09:00 when their data is six hours stale.",
  experiment: "Pick your busiest consumer and answer from the code: after how many attempts does a single message stop being retried, and where does it go. Then check whether your lag alert is on the maximum across partitions or the sum. If it is the sum, one stuck partition is invisible.",
  reflection: "Which of your ordered streams would hide a single stuck tenant behind an aggregate metric, and for how long?",
  recall: {
    q: "Why does a poison message on an ordered partition present with normal health metrics, and what two things must exist for the consumer to make progress past it?",
    a: "Because the consumer is not failing. It is successfully attempting the same message repeatedly, so its throughput, CPU and error rate all look healthy while lag climbs on that partition alone. Aggregate lag alerting hides it when the other partitions are fine.\n\nProgress requires a bounded attempt count and a terminal disposition other than success: an invalid message channel or dead letter channel that takes the record out of the stream and makes its existence loud."
  },
  deepDive: "Check our Temporal and Kafka consumers for bounded retry and a dead letter path, and tell me which lag alerts aggregate across partitions in a way that would hide one stuck tenant."
},

{
  id: "data-instapaper-table-ceiling",
  track: "data", level: "mechanism",
  title: "Instapaper, February 2017: a silent per-table ceiling inherited from an old instance",
  source: "Brian Donohue, Instapaper Outage Cause and Recovery (2017)",
  gateIntro: "In early February 2017 Instapaper stopped accepting writes. There was no traffic spike, no deploy, no configuration change and no alert in advance of it. Reads continued for a period and then the service went down entirely. Recovery required moving the data onto a new database instance, and the service was unavailable or degraded for more than a day while that happened.",
  idea: "A table's growth curve is a resource with a ceiling, and if nobody owns the curve the ceiling arrives as an outage rather than as an alert.",
  why: "Instapaper's database ran on an RDS MySQL instance created years earlier, before RDS supported the file system configuration that lifts the per-table file size limit. Instances created before that change carried a 2 TB ceiling per table, and the bookmarks table reached it. The property that made this an outage rather than a maintenance ticket is that the limit was not visible from anywhere: it was not a documented attribute of the running instance, RDS exposed no metric for per-table file size, and the first signal of any kind was writes failing at the moment the limit was hit.\n\nThe general shape is that inherited infrastructure carries constraints from the conditions of its creation, and those constraints do not migrate into your monitoring just because the workload did. Recovery was slow for the corresponding reason: the remedy is to move the data to an instance without the limit, and a dump and reload of a table that size takes many hours whether or not you are down.",
  failureMode: "A table nobody owns grows monotonically for years against a limit nobody knows about. The alert you would have wanted is not 'the table is large', it is 'the table will reach a boundary in 60 days', and that alert cannot exist because nobody has written down what the boundary is.",
  experiment: "List your five largest tables and, for each, get the current size and the size 30 days ago. Extrapolate to the nearest hard limit you can name for that engine and instance: file size, partition count, key range, disk. If you cannot name a limit for a table, that is the finding.",
  reflection: "What in your estate is still running on infrastructure created under conditions nobody currently on the team remembers?",
  recall: {
    q: "Why did Instapaper get no warning before writes stopped, and what class of alert would have caught it?",
    a: "The ceiling was an attribute of how the RDS instance had been created years earlier rather than of the workload, so it appeared in no metric and no documentation the team was watching. The first observable was writes failing at the boundary.\n\nThe alert that catches it is not one on table size, it is one on projected time to a named limit: growth rate extrapolated against a boundary someone has written down for that engine and that instance. Without the boundary recorded, the alert cannot be expressed."
  },
  deepDive: "For our largest ClickHouse and Postgres tables, work out the growth rate and the nearest hard engine or instance limit, and give me a projected date for each."
},

{
  id: "data-txid-wraparound",
  track: "data", level: "mechanism",
  title: "Postgres transaction IDs are a counter that runs out if vacuum falls behind",
  source: "PostgreSQL documentation, Routine Vacuuming: Preventing Transaction ID Wraparound Failures",
  gateIntro: "A Postgres cluster that has run for four years starts refusing writes at 04:50, returning the same error on every connection that attempts one. Reads are entirely unaffected. Disk is 40 percent free, connection count is normal, CPU is near idle, and there has been no deploy for nine days. Restarting the primary changes nothing. Disk, connections and lock contention are all ruled out inside ten minutes and the team has no fourth hypothesis.",
  idea: "Transaction IDs are a finite circular space, and if freezing falls behind the write rate the database will stop accepting writes to protect itself from silently losing the past.",
  why: "Postgres row visibility is decided by comparing a row's inserting transaction ID against the current one in a 32-bit circular space, which means only about two billion transactions are visible in each direction. Autovacuum's freeze job marks old rows as unconditionally visible so their transaction IDs can be reused. When the oldest unfrozen transaction age approaches the wraparound point, the database refuses new transactions rather than allow rows that are in the past to be reinterpreted as being in the future, which would present as data silently vanishing.\n\nWhat makes this a 2am problem is the combination of causes and the shape of the remedy. Anything that holds an old transaction horizon blocks freezing: a long-running analytics query, an idle-in-transaction connection someone left open, an abandoned replication slot, a prepared transaction nobody committed. Meanwhile the write rate keeps consuming the counter. The database gives you a metric for this well in advance, and almost nobody alerts on it. The recovery is a vacuum freeze that is single threaded per table and reads every unfrozen page, so its duration is a function of table size, and you are already down for the whole of it.",
  failureMode: "A replication slot left behind by a decommissioned consumer, or an idle-in-transaction connection from a service that crashed without closing, pins the horizon for weeks. Nobody notices because the only symptom until the very end is that autovacuum keeps running and never advances anything.",
  experiment: "Run a query for the maximum age of datfrozenxid across your databases and compare it to autovacuum_freeze_max_age. Then list every replication slot and every connection sitting in the idle in transaction state. If you cannot produce that first number today, you have no alert on it either.",
  reflection: "Which finite counters in your systems, not just this one, have no alert on their consumption rate?",
  recall: {
    q: "What causes a Postgres cluster to refuse writes on transaction ID wraparound, what blocks the freeze that would have prevented it, and why is the recovery slow?",
    a: "Transaction IDs live in a 32-bit circular space and visibility is a comparison within it, so if the oldest unfrozen transaction gets close to two billion behind, the database refuses new transactions rather than let past rows be reinterpreted as future ones.\n\nFreezing is blocked by anything pinning an old transaction horizon: long-running queries, idle-in-transaction sessions, abandoned replication slots, uncommitted prepared transactions. Recovery is a vacuum freeze that scans every unfrozen page and runs single threaded per table, so its duration scales with table size and it happens while you are already down."
  },
  deepDive: "Write me the queries and alert thresholds for transaction ID age, replication slot lag and idle-in-transaction sessions across our Postgres fleet."
},

{
  id: "data-argo-etcd-size",
  track: "data", level: "mechanism",
  title: "Argo workflow objects grow until etcd refuses them",
  source: "Argo Workflows documentation, node status offloading and etcd size limits",
  gateIntro: "A fan-out workflow with several thousand parallel steps runs normally for about 40 minutes. Its steps keep completing and their pods keep exiting zero, but the workflow's own reported status stops advancing and the controller starts logging the same error against that one object, repeatedly. Every other workflow in the cluster is unaffected. Deleting and resubmitting reproduces it at roughly the same point each time. Node pressure, etcd latency and API server error rate are all normal.",
  idea: "Storing per-step status inside a single custom resource makes the object's size a function of workflow shape, so a wide enough fan-out exceeds the backing store's value size limit regardless of cluster load.",
  why: "Argo Workflows keeps the status of every node in the DAG inside the status field of one Workflow object. etcd enforces a maximum size per value, around 1.5 MiB by default, and the API server rejects any update that would exceed it. So the controller can execute the workflow perfectly and still be unable to record that it did, at which point the object's persisted state stops tracking reality and the workflow stalls with all of its actual work succeeding.\n\nThe reason this is a distinct shape worth recognising is that the trigger is the workflow's topology, not the cluster's load. A wide fan-out over a tenant with more objects than the others hits it while an identical template over a smaller tenant never will, which makes it look tenant-specific and load-independent and sends people looking at the wrong layer. Argo's mitigations are compressing the node status and offloading it to a SQL persistence layer so the object stays small, both of which have to be enabled deliberately. The general lesson generalises past Argo: any design that accumulates per-item state in a single record has a maximum item count, and you should know what it is before a customer finds it.",
  failureMode: "The biggest tenant's largest scheduled job fails at 40 minutes in, every time, while the same template passes in staging and for every other tenant. The failure is reproducible, which makes it look like a bug in the workflow rather than a ceiling in the store.",
  experiment: "Query your workflow objects for their serialised size and find the 99th percentile and the maximum. Compare the maximum against your etcd value limit and work out the fan-out width that reaches it. Then check whether node status offloading is enabled.",
  reflection: "Where else in your estate does per-item state accumulate inside a single record, and what is the item count that breaks it?",
  recall: {
    q: "Why does a large Argo fan-out workflow stall while all of its pods succeed, and why does the failure look tenant-specific rather than load-related?",
    a: "Argo stores every node's status inside one Workflow object, and etcd rejects updates beyond a per-value size limit of roughly 1.5 MiB. The steps execute fine, but the controller cannot persist the record of it, so the workflow's state stops advancing.\n\nThe trigger is workflow topology rather than cluster load, so the same template breaks for a tenant with a wide fan-out and passes everywhere else, reproducibly, with every cluster health signal normal."
  },
  deepDive: "Measure the size distribution of our Argo workflow objects, tell me the fan-out width that hits the etcd limit, and say whether offloading would change the answer."
},

{
  id: "data-clickhouse-mutations",
  track: "data", level: "mechanism",
  title: "ClickHouse deletes are asynchronous mutations that rewrite parts",
  source: "ClickHouse documentation, ALTER TABLE DELETE and mutations",
  gateIntro: "A tenant offboarding runs at 21:00 as a single statement against a large ClickHouse table. The statement returns in under a second and the operator closes the ticket. Over the next four hours, ingest lag on unrelated tables in the same cluster climbs from seconds to over an hour, disk IO saturates, and merges back up behind it. Nobody connects the two events, because the only action anyone took that evening was reported as finished before any of the symptoms began.",
  idea: "A logical row deletion in ClickHouse is a background rewrite of every affected part, so a compliance deletion or a tenant offboarding is an hours-long IO event competing with ingest rather than a metadata change.",
  why: "ClickHouse stores data in immutable parts. There is no in-place row deletion, so ALTER TABLE DELETE is a mutation: for every part containing a matching row, the server writes a new version of that part without those rows and then swaps it in. The cost is proportional to the data volume in the affected parts, not to the number of rows deleted, so a predicate that removes a handful of rows spread thinly across a year of data rewrites a year of data. The statement itself is asynchronous, returning as soon as the mutation is accepted, with real progress visible only in system.mutations.\n\nTwo consequences follow. Operationally, the deletion competes for exactly the resources ingest and merges need, on the same disks, and it does so long after the operator who started it has moved on. Semantically, the return of the statement is not the completion of the deletion, which matters when the deletion is a legal obligation and someone is going to ask when the data was actually gone. Lightweight deletes change the immediate experience by masking rows rather than rewriting parts, but the physical removal still has to happen eventually.",
  failureMode: "An offboarding or a GDPR erasure is run in business hours as if it were a DELETE against Postgres. Hours later, tenants who have nothing to do with the offboarded one see stale dashboards, and the incident timeline starts at the symptom because the cause was recorded as complete.",
  experiment: "Query system.mutations on your ClickHouse cluster for anything not yet done, and for the elapsed time of the last few that finished. Then take your standard tenant offboarding statement and work out from part sizes how much data it will rewrite. Compare that to how long the person running it thinks it takes.",
  reflection: "Which of your routine operations return immediately and then do hours of work that nobody is watching?",
  recall: {
    q: "Why is the cost of a ClickHouse ALTER TABLE DELETE proportional to something other than the number of rows deleted, and what is the operational trap in the statement returning quickly?",
    a: "Parts are immutable, so deletion rewrites every part containing a matching row. Cost scales with the volume of the affected parts, which means a predicate matching a few rows scattered across a year rewrites a year of data.\n\nThe statement is asynchronous and returns on acceptance, so the operator records the task as done while hours of IO contention with ingest and merges are still ahead. Real progress is only in system.mutations, and for a compliance deletion the completion time is the number that matters."
  },
  deepDive: "Work out the real cost and duration of our tenant offboarding deletion in ClickHouse, and propose a partitioning scheme that turns it into a partition drop."
},

{
  id: "data-plan-flip",
  track: "data", level: "mechanism",
  title: "An index stops being used the moment the planner's estimate changes",
  source: "Markus Winand, Use The Index, Luke and SQL Performance Explained",
  gateIntro: "A dashboard query that has run in under 50 ms for a year starts taking 30 seconds. There has been no deploy in six days, no schema change, no unusual data load, and the query text is byte-identical to what it has always been. It is slow for some tenants and fast for others. Restarting the application does not help and neither does restarting the database. Overnight it goes fast again on its own, then slow again the next afternoon.",
  idea: "Plan choice is a runtime decision made from statistics and parameter values, so a query can flip from an index scan to a sequential scan with no deploy and no schema change to blame it on.",
  why: "Winand's core point is that an index is not something a query uses, it is something the optimiser chooses. That choice is a cost comparison built on estimates: how many rows the predicate will match, how correlated the data is with the index order, how much of the table is cached. When the estimated selectivity of a predicate crosses the threshold where a sequential scan looks cheaper, the plan flips, and the plan flips atomically rather than degrading. A query does not get gradually slower. It is fast, and then it is a different query.\n\nEverything that moves those estimates moves without a deploy. A statistics refresh after enough churn. Data growth changing the distribution. A histogram that no longer represents the values being queried. Most awkwardly, in a multi-tenant table, parameter values themselves: a plan cached or chosen for a tenant with a thousand rows is the wrong plan for the tenant with ten million, and which one you get depends on which query happened to run first. That is why the same statement is fast for some tenants and slow for others with no code difference anywhere.",
  failureMode: "A multi-tenant table where tenant_id is the leading predicate. The planner's estimate is an average across tenants, so the plan is wrong at both ends of the distribution, and the largest customer is the one who gets the sequential scan.",
  experiment: "Take your three slowest queries from the last week and run EXPLAIN with real production parameter values for your largest tenant and for a small one. Compare the plans. If they differ, that query's performance is a property of who is asking, not of the query.",
  reflection: "Which of your queries have only ever been explained with a developer's test tenant as the parameter?",
  recall: {
    q: "Why can a query flip from fast to slow with no deploy and no schema change, and why does it often affect only some tenants?",
    a: "The plan is chosen at runtime from statistics and parameter values, and the choice between index and sequential scan is a cost threshold. When estimated selectivity crosses it the plan flips atomically, so the query does not degrade, it becomes a different query. Statistics refreshes, growth and distribution shifts all move that estimate without any code change.\n\nIn a multi-tenant table the parameter value itself changes the right answer. A plan appropriate for a tenant with a thousand rows is wrong for one with ten million, so the same statement is fast for some tenants and slow for others."
  },
  deepDive: "Explain our top dashboard queries with parameters from our largest and smallest tenants and tell me which ones have plans that depend on who is asking."
},

{
  id: "data-referential-assumption",
  track: "data", level: "mechanism",
  title: "Referential integrity enforced only by application code is an assumption, not a constraint",
  source: "Scott Ambler and Pramod Sadalage, Refactoring Databases: Evolutionary Database Design (2006)",
  gateIntro: "A nightly aggregation job that has run for two years without a failure starts throwing null dereferences on about 0.4 percent of rows. Every affected row references a parent record that the application's own code guarantees must exist, and the code is right: there is no path through the application that could produce these rows. A migration onto a replacement service has been running in the background for three weeks. Nothing in the application logs shows any write matching them.",
  idea: "A constraint the database does not enforce is a claim about every writer that will ever touch the data, including the ones that do not exist yet.",
  why: "Ambler and Sadalage's framing is that a database with more than one application is the normal case, not the degenerate one, and that integrity has to live where all writers meet. Application-level referential integrity is a statement about one code path. It holds exactly as long as that code path is the only writer, and the set of writers grows without anyone deciding to grow it: a backfill script, an admin console, a data-fix run during an incident, a support tool, an ETL job writing back, a replacement service during a migration, a replication stream from somewhere else.\n\nThe migration case is the sharpest because it is the moment you deliberately add a second writer to the same data, usually one written by people who read the schema rather than the application code. The schema does not say the relationship is mandatory, so the new writer does not know. And unlike a constraint violation, which fails loudly at write time at the point of the bug, an orphan row fails quietly at read time, somewhere else, later, in a job whose stack trace points at the reader.",
  failureMode: "Deletes are the common source. A parent row is removed by an admin script or a cleanup job that does not know it is a parent, the children survive, and the failure surfaces weeks later in an aggregation or an export where the reader assumed the join would always match.",
  experiment: "Pick one relationship your application code treats as mandatory and run the anti-join today: count child rows whose parent does not exist. If the count is not zero, you have already found the writers you did not know about. If it is zero, add the foreign key or a scheduled check before your next migration adds a writer.",
  reflection: "How many distinct processes write to your most important table, and when did you last enumerate them rather than estimate?",
  recall: {
    q: "Why does application-enforced referential integrity fail specifically during migrations, and why is the resulting bug hard to trace?",
    a: "A migration deliberately introduces a second writer to the same data, usually one built from the schema rather than from the application code, and the schema does not encode a relationship that only exists as a convention. Backfills, admin scripts and data fixes add writers the same way, without a decision.\n\nThe bug is hard to trace because an orphan row does not fail at write time at the point of the defect. It fails later, at read time, in a different job, with a stack trace pointing at the innocent reader."
  },
  deepDive: "Run the anti-join checks across our core tenant tables for every relationship the code treats as mandatory but the schema does not enforce, and rank what we found by blast radius."
},

{
  id: "data-atlassian-2022-delete",
  track: "data", level: "amplifier",
  title: "Atlassian, April 2022: the script was correct and the input list was wrong",
  source: "Atlassian, Post-Incident Review of the April 2022 outage",
  gateIntro: "On 5 April 2022 a set of Atlassian cloud customers found their Jira, Confluence and Opsgenie sites gone: not erroring, not degraded, absent, along with the URLs that reached them. The affected set was small against the customer base and nobody else was touched. Atlassian's platform monitoring reported healthy throughout, and the company learned of it from customers. The count it published first was later revised upward to 775 sites, and some customers were not fully restored until 18 April, fourteen days in.",
  idea: "A deletion executed intentionally at the storage layer is indistinguishable from correct behaviour to everything downstream, so nothing between the command and the data will stop it.",
  why: "A maintenance routine was deactivating a legacy standalone app whose functionality had been folded into the product. The script ran correctly. It was given a list of identifiers for the wrong kind of entity - cloud site IDs rather than app IDs - against an endpoint that accepted both, and it was run in a mode that permanently deleted rather than marking for deletion. Two independent defects had to line up: the ambiguity in the interface, and a runbook that specified the destructive mode where it did not need to.\n\nThe amplifier worth taking away is that nothing downstream had any reason to object. Every guard rail that catches accidental data loss is built to detect anomaly, and an authorised maintenance job issuing a valid permanent delete against valid identifiers is not anomalous. The rate limits, the audit trail, the monitoring and the replication all behaved exactly as designed. Recovery was then slow for a structurally separate reason: Atlassian could restore the whole multi-tenant environment quickly, but restoring individual sites back into a running environment shared with unaffected customers was not an automated capability, so it had to be done semi-manually, in batches, which is where the fourteen days went.",
  failureMode: "The blast radius is decided by the input list, and the input list is the least reviewed artifact in the change. The runbook, the script and the approval all get scrutiny. The identifiers get pasted.",
  experiment: "Find every runbook or job in your estate that can permanently delete tenant-scoped data. For each, answer: is there a soft-delete mode, is it the default, and what validates that the identifiers are of the right entity type before anything executes. Then check how long a single-tenant restore into a live shared environment takes, if it is possible at all.",
  reflection: "Can you restore one tenant without disturbing the others, and have you ever done it?",
  recall: {
    q: "Why did no downstream control stop the Atlassian deletion, and why did restoration take two weeks when the backups were intact?",
    a: "Because the deletion was authorised, valid and intentional at the storage layer. Controls that catch data loss look for anomaly, and a maintenance job issuing a legitimate permanent delete against legitimate identifiers is not anomalous. The two defects were an endpoint that accepted the wrong entity type of identifier and a runbook specifying permanent rather than soft delete.\n\nRestoration was slow because restoring the whole shared environment was fast but restoring individual sites into a live environment holding unaffected customers was not an automated capability, so it ran semi-manually in batches."
  },
  deepDive: "Audit our tenant-scoped destructive operations for soft-delete defaults and entity-type validation on the input list, and tell me whether we can restore a single tenant into a live cluster."
},

{
  id: "data-cloudbleed-tenant-leak",
  track: "data", level: "amplifier",
  title: "Cloudflare, February 2017: a memory bug in a shared process leaks every tenant's data",
  source: "John Graham-Cumming, Incident report on memory leak caused by Cloudflare parser bug (2017)",
  gateIntro: "On 17 February 2017 an external security researcher contacted Cloudflare with fragments of other people's HTTP traffic - cookies, POST bodies, private messages, credentials - which he had found sitting in ordinary public web search results. The data had passed through Cloudflare's edge. There had been no intrusion and no unauthorised access, no elevated error rate, no customer report, and nothing anomalous in Cloudflare's own metrics for the period, which turned out to have started months earlier.",
  idea: "When many tenants share one address space, a memory safety bug does not corrupt one customer's request, it emits fragments of every other customer's traffic to whoever asked.",
  why: "The proximate defect was a pointer check in a Ragel-generated HTML parser that tested for equality with the end of the buffer rather than for having passed it, so a particular malformed input walked past the end. That code had been latent for a long time; introducing a new parser changed the buffering conditions in a way that started exercising it. When the parser ran off the end it kept emitting bytes, and the bytes adjacent in memory were whatever else that process had been handling.\n\nThe amplifier is the tenancy model, not the bug. In a shared edge process the neighbouring memory is other customers' requests and responses, so a memory error converts into a cross-tenant data disclosure with no privilege boundary crossed. Then the output was returned as page content, which meant search engine crawlers fetched and cached it, and the leaked data outlived the fix by an unbounded amount in third-party systems Cloudflare did not control. Fixing the parser took hours. Cleanup meant working with Google, Bing and Yahoo to purge caches, and by construction it could never be proven complete. Cloudflare's estimate was that roughly one in every 3,300,000 requests through their network could have leaked memory, and the highest-impact window was about five days.",
  failureMode: "The detection path is the tell. Nothing internal fired, because from inside the system every request succeeded. The first signal came from outside, from someone finding your customers' data somewhere it should not be, which means your time to detection is set by a stranger's curiosity.",
  experiment: "Identify every place in your estate where more than one tenant's data occupies one process, one buffer pool, one cache namespace or one temporary directory. For the top three, ask what an off-by-one or a missing key prefix would emit, and whether any internal signal would show it. Write down which ones would only be found by an outsider.",
  reflection: "Which of your shared components could return one tenant's data to another with every metric green, and who would tell you?",
  recall: {
    q: "What turned a memory safety bug into a cross-tenant disclosure at Cloudflare, and why did the cleanup extend beyond Cloudflare's own systems?",
    a: "Shared tenancy in a single process. The bytes adjacent to the overrun were other customers' in-flight requests and responses, so a parser walking past the end of a buffer emitted other tenants' data without any privilege boundary being crossed and without any error being raised.\n\nThe leaked bytes were served as page content, so search engine crawlers fetched and cached them. Remediation required purging third-party caches, and completeness could never be established. Detection came from an external researcher because internally every request had succeeded."
  },
  deepDive: "Map where tenant data shares a process, cache namespace or buffer in our platform, and tell me which of those boundaries has no internal signal that would catch a leak."
}
);
