/* Track: Time, clocks and expiry. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "time-certificates-inside-the-system",
  track: "time", level: "mechanism",
  title: "Ericsson, 6 December 2018: the expired certificates were inside the software, not at the edge",
  source: "Ericsson statement and Ofcom reporting on the O2 and SoftBank network outage, December 2018",
  gateIntro: "On 6 December 2018 a UK mobile operator lost data service for tens of millions of subscribers for most of the day. Inside the same window an operator in Japan lost data service to millions more. The two share no network, no data centre and no traffic, and neither had deployed anything that day. Voice largely kept working. Neither operator recovered until it had rolled its core nodes to a different software version, which took most of a working day in each country.",
  idea: "The certificates that take you down are the ones inside the system, because your monitoring watches the ones facing the internet.",
  why: "Edge certificates are the ones with automated issuance, public transparency logs and an external probe checking them every minute. Everything about the edge pushes you towards renewal being solved. Internal certificates have none of that: mutual TLS between services, kubelet client certs, a mesh intermediate CA, an admission webhook CA bundle, a token signing key baked into a vendor container image. Nothing outside can see them, so nothing outside can warn you.\n\nThe vendor case is the sharp one. An expiry compiled into an artefact you did not build is a constant shared by every customer of that vendor, so it fires everywhere at once, at an instant with no relationship to your load, your deploys or your topology. That is why the signature looks impossible: two operators on different continents failing in the same hour with nothing in common except a supplier.",
  failureMode: "A correlated outage across tenants, regions and unrelated clusters with a flat deploy graph and flat traffic, and no explanation in anything you control. In a Kubernetes estate the usual candidates are the cluster CA and kubeadm control-plane certs on a cluster that has been up longer than a year, kubelet client certs on long-lived nodes, admission webhook serving certs, and the mesh intermediate. cert-manager renews what cert-manager issued. It does not know about the signing key inside a vendor image.",
  experiment: "Enumerate every x509 in the estate and sort by notAfter. Across every cluster: dump all secrets of type kubernetes.io/tls and decode notAfter, run the control-plane cert expiry check on each control plane, and pull the caBundle out of every validating and mutating webhook configuration. Produce one sorted table. The finding is any certificate expiring inside 90 days that cert-manager did not issue, because that is the set nothing is renewing.",
  reflection: "Which certificate in your estate would you learn about from a customer rather than from a dashboard?",
  recall: {
    q: "Edge certificate monitoring is green and three unrelated clusters started failing in the same minute. What class of cause are you on, and why did monitoring miss it?",
    a: "An expiry inside the system rather than at the edge: an internal CA, a client certificate, a mesh intermediate, or a key embedded in a vendor artefact. Edge monitoring probes from outside, so it can only see what is reachable from outside.\n\nThe simultaneity across unrelated systems is the diagnostic. A shared absolute time with no shared load or deploy means a constant somebody compiled in, not something you did."
  },
  deepDive: "Help me enumerate every certificate and signing key in my multi-tenant Kubernetes estate that cert-manager does not issue, and rank them by what stops working the moment each one expires."
},
{
  id: "time-revocation-not-expiry",
  track: "time", level: "recovery",
  title: "Let's Encrypt, March 2020: a certificate can become invalid long before it expires",
  source: "Let's Encrypt, 2020.02.29 CAA Rechecking Bug incident report and mass revocation notice",
  gateIntro: "On 29 February 2020 a certificate authority told its subscribers that around three million certificates would stop being trusted at 20:00 UTC on 4 March, roughly 72 hours later. Every one of those certificates was inside its validity window and most had months left to run. Expiry dashboards were green. Some operators had thousands of affected hostnames spread across systems with no shared renewal path, and the deadline was the same for all of them.",
  idea: "Validity dates are not what keeps a certificate working, so the capability that saves you is emergency mass reissue, not an expiry calendar.",
  why: "A certificate stops working when a relying party stops trusting it, and expiry is only one route to that. A CA that discovers a validation defect is obliged to revoke on a short, externally imposed clock. The certificate on disk is unchanged and still shows months of validity. Your expiry monitoring, by construction, reports nothing.\n\nThe operational asymmetry is what matters. Expiry gives you months of warning per certificate and naturally staggers, so a slow manual renewal path survives for years without anyone noticing it is slow. Revocation gives an arbitrary subset of your estate one common deadline chosen by someone else. The number that governs your outcome is not the earliest notAfter, it is how many certificates you can reissue and deploy in parallel per hour without a human per certificate.",
  failureMode: "You can name the expiry date of every certificate and cannot say how long it takes to replace them all. The estate splits into three tiers: ACME-automated hosts that reissue themselves, internally issued certs that need a pipeline run, and two or three appliances or managed services where reissue is a support ticket with a business-hours SLA. The ticket tier sets the recovery time for the whole estate, and nobody measured it because it was never the tier that expired.",
  experiment: "Pick the certificate you believe is hardest to replace and replace it today in a non-production cluster with a stopwatch running. Record wall-clock minutes and how many of them needed a human. Multiply by the number of certificates sharing that issuance path. Write the number on the runbook. That number, not the earliest expiry, is your exposure to a CA incident.",
  reflection: "How many hours to reissue and redeploy every certificate you own, and which single one dominates that total?",
  recall: {
    q: "Why is an expiry dashboard insufficient protection against a certificate authority incident?",
    a: "Revocation makes valid, unexpired certificates untrusted on a deadline set by the CA, so the expiry dashboard stays green through the whole event. The mechanism you need is throughput of reissue, not visibility of dates.\n\nMeasure it as a drill: time one replacement end to end, then multiply by the certificates that share its path. The slowest path is your recovery time."
  },
  deepDive: "Design me a mass certificate reissue drill for a multi-tenant Kubernetes estate that measures throughput rather than correctness, and tell me what to record so the result is comparable next quarter."
},
{
  id: "time-leap-day-plus-one-year",
  track: "time", level: "amplifier",
  title: "Microsoft Azure, 29 February 2012: today plus one year is not always a valid date",
  source: "Bill Laing, Summary of Windows Azure Service Disruption on Feb 29th, 2012 (Microsoft, 2012)",
  gateIntro: "From 17:45 UTC on 28 February 2012 a cloud platform began failing to bring up newly created virtual machines in one cluster. The platform read those failures as faulty hardware and relocated the workloads, which then failed on the new hardware too. Inside about ninety minutes enough nodes had been marked bad that the cluster stopped accepting work, and the same pattern started in other clusters. Management operations for the whole service were unavailable into the next day. A fix deployed during recovery contained the wrong version of a component and took out a further set of clusters.",
  idea: "Date arithmetic that assumes every day has a same-day-next-year is a bomb with a calendar fuse, and a self-healing platform will convert that deterministic failure into a cluster-wide one.",
  why: "The initialisation step generated a transient certificate valid from today until today plus one year. On 29 February 2012 that expression produced 30 February 2013, which is not a date. The certificate could not be created, the agent could not initialise, and the host waited out its timeout and declared the start a failure.\n\nEverything after that was the platform working as designed on a wrong assumption. Its health model said a workload that fails to start on a node implies a bad node. That assumption holds for host-correlated failures and is exactly inverted for input-correlated ones: relocation carries the poison to the next host and marks each one as it goes. The cluster-level brake that halts healing when too many nodes look bad then turned a workload failure into a control-plane outage, which is why a bad date in one code path took out management operations across regions.",
  failureMode: "Any retry-on-a-different-host policy that does not distinguish host-correlated from input-correlated failure. An Argo workflow whose pod crashes on a poison input and gets rescheduled across the whole node pool. Temporal activity retries that land on a fresh worker each attempt. A node problem detector that cordons a node because the same broken image crashed on it three times. In each case the platform spends healthy capacity proving a deterministic fact.",
  experiment: "Take one workflow and make it fail deterministically on a poison input in a non-production cluster: an image that exits non-zero at startup is enough. Then count. How many distinct nodes does the platform touch before something stops it, does anything mark those nodes degraded or unschedulable, and how long until a human is told. If the count is unbounded you have the Azure amplifier in your estate.",
  reflection: "What in your platform can mark hardware bad on the evidence of a workload failing, and what is its ceiling?",
  recall: {
    q: "Why does automatic relocation make a deterministic input failure worse than a random one?",
    a: "Relocation assumes the failure was a property of the host. When it was a property of the input, every move reproduces the failure and marks another healthy host as suspect, so the blast radius grows with each recovery attempt.\n\nThe amplifier is the healing loop, not the bug. The counter is a bound: cap how much capacity one failing workload may condemn, and treat identical failures on distinct hosts as evidence about the workload."
  },
  deepDive: "Look at my Argo and Temporal retry configuration and tell me where a deterministic input failure would be able to condemn healthy capacity before anything stopped it."
},
{
  id: "time-leap-second-kernel",
  track: "time", level: "mechanism",
  title: "30 June 2012: the leap second was a kernel bug, not a clock problem",
  source: "Linux kernel hrtimer and futex leap second defect reports and fixes, June and July 2012",
  gateIntro: "Just after midnight UTC on 1 July 2012, unrelated organisations running unrelated software began reporting servers pinned at full CPU in the same minute. Reddit was down. Java services, database hosts and hypervisors were all represented, across different providers and different data centres. There was no deploy, no traffic change, no shared vendor and no shared network. The workloads had nothing in common with each other; the hosts were ordinary Linux servers of roughly the same vintage.",
  idea: "The 2012 leap second did not break clocks, it broke a kernel timer path, which is why the blast radius was every workload on the host rather than only the time-sensitive ones.",
  why: "Inserting the second updated the kernel's notion of wall time without reprogramming high resolution timers that had already been armed against the old view. Timers with deadlines in the affected window were treated as expired the moment they were examined and immediately re-armed, so threads sleeping on timed waits woke in a tight loop. Anything using a condition variable with a timeout was affected, which in practice is every JVM, most database servers and a great deal of ordinary application code. The classic workaround was to force the kernel to reprogram its timers by setting the system clock to its own current value.\n\nThe general lesson is about correlation, not about leap seconds. When a failure hits many systems at the same instant with no shared deploy, no shared vendor, no shared traffic and no shared network, the shared thing is a layer everybody runs. That layer is almost always something you standardised on and stopped thinking about: a kernel, a runtime, a base image, a libc, a sidecar.",
  failureMode: "You spend the first hour of the incident in your own change log finding nothing, then on the provider status page finding nothing, then correlating tenants that have nothing in common. Meanwhile every autoscaler in the estate reads CPU saturation as load and expands onto more hosts running the same kernel, so the mitigation grows the affected surface. Leap seconds are now smeared by the major time services and none has been inserted since 2016, but the correlated-monoculture shape long outlives that particular trigger.",
  experiment: "Ask what in your estate is uniformly one version. Count distinct kernel versions, container runtime versions and base image digests across all node pools and all clusters, and put the counts in a table. Anything with a count of one across the whole estate is a correlated-failure surface, and you should be able to say out loud what happens if it fails everywhere simultaneously at 00:00 UTC with no deploy to roll back.",
  reflection: "Name the layer that every workload you run depends on and no team owns.",
  recall: {
    q: "A failure hits unrelated systems in the same minute with no deploy, no traffic change and no shared vendor. Where do you look?",
    a: "At the layer everything shares. Kernel, runtime, base image, libc, sidecar, or an absolute-time trigger such as an expiry or a calendar boundary. Application-level explanations cannot produce that simultaneity across unrelated workloads.\n\nThe corollary is that a version monoculture is a correlated-failure surface, and you should be able to enumerate yours before the night it matters."
  },
  deepDive: "Inventory the version monoculture in my Kubernetes estate and tell me which single shared component has the largest blast radius if it fails on every node at once."
},
{
  id: "time-negative-duration",
  track: "time", level: "mechanism",
  title: "Cloudflare, 1 January 2017: time went backwards and the arithmetic had no case for it",
  source: "John Graham-Cumming, How and why the leap second affected Cloudflare DNS (Cloudflare, 2017)",
  gateIntro: "Shortly after 00:00 UTC on 1 January 2017 a small percentage of DNS queries to a large public resolver started returning errors. The failures were spread thinly across the whole fleet rather than concentrated in one location. Query volume was normal, no upstream was down, and nothing had been deployed over the holiday period. The errors persisted until an engineer wrote a patch and it was rolled out.",
  idea: "Subtracting two wall-clock timestamps produces a signed number, and code that assumes it is positive is one clock correction away from an arithmetic error in a hot path.",
  why: "The resolver measured how long an upstream took by subtracting one wall-clock reading from another. Go's time.Now returned wall time only at the version in use, so across the inserted second the subtraction produced a negative duration. That value flowed into the logic that chose which upstream to use, where a negative input was not a case anybody had written, and the result was errors returned to real queries. The fix was to clamp the value; the durable fix was Go gaining a monotonic reading.\n\nWall clock is not monotonic and never was. NTP steps it, leap seconds shift it, a live migration moves it, a resumed VM lands somewhere else entirely, and a container inherits whatever the host decided. Any duration reconstructed from two wall-clock reads can be negative or enormous. Use a monotonic source for elapsed time and a wall clock only for instants you intend to display or compare across machines, and even then decide in advance what you do when the comparison comes out backwards.",
  failureMode: "Negative durations poison three things quietly. Latency histograms get a negative sample and your p99 is now a lie. Timeout arithmetic computes deadline minus now, goes negative, and the call either fires instantly or waits forever depending on the sign handling. Rate limiters accrue tokens as elapsed times rate, so negative elapsed removes tokens and the limiter locks out traffic. In Go, time.Since is monotonic, but the monotonic reading is stripped the moment a timestamp is serialised, so a Temporal activity comparing its own now against a scheduled time from the workflow history is back to comparing two machines' wall clocks.",
  experiment: "Run one query. In ClickHouse, compute the distribution of activity start time minus scheduled time for the last day of workflow executions and look at the minimum, not the median. A negative minimum means clock skew between your Temporal service and your workers, and it means you have already been recording negative latencies somewhere. Then grep the Go and Python code for any subtraction where one operand came off the wire rather than out of a local monotonic read.",
  reflection: "Where in your code does a duration get computed from a timestamp that crossed a process boundary?",
  recall: {
    q: "You use time.Since everywhere in Go. Where can a negative duration still appear?",
    a: "Wherever the timestamp crossed a process boundary. Go strips the monotonic reading on marshalling, so a time that arrived over the wire, out of a database column, or out of a Temporal history is a plain wall clock from another machine.\n\nComparing that against your local now is a comparison of two independent clocks, and the difference is bounded only by your skew, not by zero."
  },
  deepDive: "Find every place in my Go and Python services where an elapsed time is computed against a timestamp that came from another process, and tell me which of them would misbehave on a negative result."
},
{
  id: "time-lease-needs-a-fence",
  track: "time", level: "mechanism",
  title: "A lease is only as safe as your bound on clock skew and process pauses",
  source: "Martin Kleppmann, How to do distributed locking (2016)",
  gateIntro: "A scheduler guarantees that at most one worker runs a given tenant's sync at a time, using a lock with a timeout. In production two workers occasionally write conflicting output for the same tenant inside the same second. Both workers' logs show them holding the lock, neither logs an error, and the lock service shows exactly one holder at every point in its own history. The problem is rare, it correlates with nothing in the input, and it is more common on the busiest nodes.",
  idea: "A lease provides mutual exclusion only if the resource itself rejects writes from an expired holder, because the holder cannot tell a pause from an instant.",
  why: "Lease correctness rests on the holder noticing expiry before it acts. Between the check and the write there can be a garbage collection pause, hypervisor steal, a page fault storm, CPU throttling in a cgroup, or a clock jump. The lock service expires the lease on its own clock and hands it to somebody else. The paused process resumes and completes a write it correctly believed was protected when it checked. No component behaved incorrectly and no log line is wrong.\n\nThe fix is not a longer timeout, because a longer timeout only makes the window rarer, and rarer means you will meet it during an incident when pauses are longest. The fix is a monotonically increasing token issued with the lease and checked by the resource on every write, where the resource rejects any token lower than the highest it has already accepted. That converts the safety property from a timing assumption into an ordering one. If the resource cannot check a token, you do not have a lock, you have a probability.",
  failureMode: "CPU limits make pauses routine. A throttled pod stalls for hundreds of milliseconds at a time in normal operation, and a heap collection under memory pressure goes much further. So the estate that most needs fencing is exactly the one where the lease TTLs were chosen assuming processes run continuously. Look at leader election in custom operators, the Argo controller, and anything whose shape is check the lock, then write to object storage or ClickHouse, where the destination accepts every write it is offered.",
  experiment: "Pick one lock and answer whether the resource it protects checks anything at write time. If it does not, reproduce the failure today: SIGSTOP the holder for longer than the lease TTL, let a second worker acquire the lease, then SIGCONT the first and see whether its write lands. If it lands, you have measured the guarantee you actually have rather than the one in the design document.",
  reflection: "Which of your locks protects a resource that cannot reject a stale writer?",
  recall: {
    q: "Why does increasing the lease TTL not fix a lock without fencing?",
    a: "A longer TTL shrinks the window but does not remove it, and the pauses that hit the window are longest exactly when the system is degraded, so the failure concentrates in incidents.\n\nSafety has to be enforced at the resource: a monotonically increasing fencing token, checked on every write, with anything lower rejected. Ordering is checkable, timing is not."
  },
  deepDive: "List every lock and leader election in my estate, and for each say whether the protected resource could reject a stale writer and what the token would have to be."
},
{
  id: "time-bound-the-uncertainty",
  track: "time", level: "mechanism",
  title: "Spanner makes clock uncertainty explicit and waits it out",
  source: "Corbett et al., Spanner: Google's Globally-Distributed Database, OSDI 2012",
  gateIntro: "A globally distributed database offers external consistency: any transaction beginning after another has committed observes its writes, across continents, with no consensus round in the read path for that guarantee. Its commit latency contains a deliberate wait of a few milliseconds that performs no work and cannot be optimised away. The operators install GPS receivers and atomic clocks in every data centre and treat the resulting hardware as a production dependency.",
  idea: "You either bound your clock error, expose the bound and pay for it in latency, or assume it is zero and pay for it in silently wrong ordering.",
  why: "TrueTime returns an interval rather than an instant: a pair guaranteed to contain the true time, with a width derived from drift since the last synchronisation against GPS and atomic references. Because the width is known, the system can reason about it. After choosing a commit timestamp, the coordinator waits until the interval has moved past it, so no later transaction can be assigned an earlier timestamp. Uncertainty is paid as commit latency, and the investment in clock hardware exists to keep that payment small.\n\nEvery system that orders events by timestamp has the same dependency. The difference is whether the dependency is named. Last-write-wins conflict resolution keyed on a wall-clock timestamp makes exactly the same assumption as Spanner, with no bound, no measurement and no wait. The right question about any timestamp-ordered system is: what maximum clock error does this assume, who measures the actual error, and what is the observable when it is exceeded.",
  failureMode: "Last-write-wins on a wall-clock column is the common case and it fails silently. A ClickHouse ReplacingMergeTree deduplicating on a version column populated with an ingestion timestamp keeps the row with the larger value, so if two writers are skewed, the older write wins permanently at merge time and nothing errors. Same for an upsert path that keeps the larger updated_at. The lost write is not logged, is not retried, and surfaces months later as a value that will not stay corrected.",
  experiment: "Measure your actual skew instead of assuming it. Chrony or the node exporter publishes an estimated offset per host; graph the maximum minus the minimum across the fleet in Grafana for a week and record the peak. Then find one decision in your system where two processes on different hosts compare timestamps to pick an outcome, and compare that peak against the time granularity of the decision. If the peak is larger, the decision is already sometimes wrong.",
  reflection: "What is your measured worst-case skew, and which decision in your system is finer-grained than it?",
  recall: {
    q: "What does TrueTime return, and what does the database do with it?",
    a: "An interval guaranteed to contain the true time, rather than a single instant. The uncertainty is explicit and bounded.\n\nAt commit the coordinator waits until the interval has passed the chosen timestamp, so ordering is safe by construction. The cost is a few milliseconds of latency, which is the price of not pretending the error is zero."
  },
  deepDive: "Find every place in my estate where a wall-clock timestamp decides which of two writes wins, and tell me what skew would have to exist for the wrong one to win."
},
{
  id: "time-wall-clock-schedules",
  track: "time", level: "mechanism",
  title: "A daily schedule in a zone with daylight saving runs twice or not at all",
  source: "Noah Sussman, Falsehoods programmers believe about time (2012), and the IANA time zone database",
  gateIntro: "Two tenant reports, seven months apart, about the same nightly reconciliation scheduled for 02:30 local. The first tenant says the job produced its output twice for a single date and the downstream ledger double counted. The second says there was no output at all for a single date, with no failed run recorded anywhere: the scheduler simply has no execution for that day. No configuration changed for either tenant, both are in the same country, and tenants elsewhere saw nothing.",
  idea: "A schedule expressed as a wall-clock time in a zone with daylight saving will run twice on one day of the year and not at all on another.",
  why: "Cron semantics are: fire when the local wall clock reads this. At the autumn transition 02:30 occurs twice, and at the spring transition it does not occur at all. Schedulers resolve that ambiguity differently and none of them is wrong: some skip, some run once, some run twice, some fire the missing run at the transition instant. So the behaviour you get is a property of the specific scheduler implementation, not of cron.\n\nMulti-tenant makes it worse in two ways. The transition dates differ per zone, the southern hemisphere is offset by roughly six months from the northern, plenty of zones have no transition at all, and the tz database changes several times a year when a government moves its rules, sometimes with weeks of notice. That means the correct UTC instant for a future local time is not knowable in advance. Store the zone identifier and the local time and resolve at fire time, never a precomputed instant, and make the job idempotent so it survives whichever way the ambiguity resolves.",
  failureMode: "Argo CronWorkflow takes an IANA timezone. Temporal schedules take a calendar spec with a time zone name. Both therefore inherit the ambiguity, and nothing guarantees the two resolve it identically. During a migration from one to the other that difference is a silent behavioural change on two days a year per zone, with no ticket, no diff in the schedule definition, and a symptom that appears months after the cutover as either a duplicated side effect or a missing run.",
  experiment: "Take one non-UTC schedule and compute its next 400 days of fire times with each scheduler's own library, Argo's and Temporal's, then diff the two lists. Any date where the lists disagree is a behavioural change your cutover is carrying. Then count, across the estate, how many schedules have a non-UTC zone and group them by zone, so you know how many tenants are exposed and on which dates.",
  reflection: "How many of your scheduled workloads are expressed in a zone that has a transition, and are any of them non-idempotent?",
  recall: {
    q: "A tenant's nightly job ran twice for one date, and a different tenant's did not run at all months later. What is the mechanism and what is the fix?",
    a: "A wall-clock schedule in a zone with daylight saving. The autumn transition repeats a local time and the spring transition removes one, and how the scheduler resolves that is implementation-specific.\n\nFix in two parts: store the IANA zone plus the local time and resolve at fire time rather than precomputing an instant, and make the job idempotent so both resolutions are survivable."
  },
  deepDive: "Compare how Argo CronWorkflow and Temporal schedules resolve a duplicated and a skipped local time, and tell me which of my tenant schedules would change behaviour on the cutover."
},
{
  id: "time-date-packed-into-an-int",
  track: "time", level: "mechanism",
  title: "Microsoft Exchange, 1 January 2022: a date packed into a signed 32-bit integer overflowed",
  source: "Microsoft, Email Stuck in Exchange On-premises Transport Queues (January 2022)",
  gateIntro: "At the local midnight ending 31 December 2021, on-premises mail servers worldwide stopped delivering mail and messages piled up in transport queues. Every version, patch level and hardware configuration failed the same way at the same local moment. Servers untouched for months behaved identically to freshly patched ones. There was no common network, no common load and no common administrator, and the vendor's interim guidance was to disable a component rather than to roll anything back.",
  idea: "A date encoded as a number inside a fixed-width field has a cliff at one specific calendar instant, and the entire installed base crosses it together.",
  why: "The scanning component derived its update version number from the date, so 1 January 2022 produced a value beginning 2201010001. That exceeds the maximum signed 32-bit integer, 2147483647. The update could not be loaded, and the component's failure stopped the transport queue. Note that the date was never compared to anything: it was packed into an integer as decimal digits, so the cliff was not a meaningful time boundary like 2038, it was the arbitrary instant at which the digit string outgrew the field.\n\nThis class has three properties worth memorising. Zero correlation with load, change or topology. Simultaneity across the whole installed base. And immunity to rollback, because the older version has the same cliff. That combination is diagnostic: when a failure appears everywhere at once and going back a version does not help, you are looking at an absolute-time trigger rather than anything you did.",
  failureMode: "The estate versions of this are dull and everywhere. Seconds in a signed 32-bit column, which is 2038. Milliseconds in a 32-bit field, which overflows about 24 days after its epoch and therefore breaks immediately. Dates written as YYYYMMDD integers in a type too small for them. And the analytics one: ClickHouse DateTime is 32-bit unsigned seconds and stops in 2106, which is invisible for ingestion timestamps and not invisible at all when somebody stores a contract end date or a retention horizon in that column.",
  experiment: "In ClickHouse, list every column of type DateTime rather than DateTime64, and every integer column whose name contains time, date, ts or epoch. For each integer column take min and max and work out its unit and epoch from the magnitude. Anything holding milliseconds in a 32-bit type, anything holding a date as packed digits, and any DateTime column that receives a future business date gets recorded against its table with the date it fails.",
  reflection: "Which column in your schema holds a future date in a type that cannot represent it?",
  recall: {
    q: "Two unrelated services fail identically at the same instant and rolling back to last month's image does not help. What have you narrowed it to?",
    a: "An absolute-time trigger: an expiry, a calendar boundary, or a value that overflows its field at a specific date. Nothing driven by load, change or topology produces simultaneity across unrelated systems.\n\nRollback immunity is the second half of the signature. If the previous version has the same constant compiled in, going back cannot help, and the mitigation is usually to disable the component or move the clock."
  },
  deepDive: "Audit my ClickHouse and Postgres schemas for date and timestamp columns whose type cannot represent the values the business will eventually put in them, and give me the date each one fails."
},
{
  id: "time-token-outlives-the-operation",
  track: "time", level: "mechanism",
  title: "A token that expires mid-operation fails at the least convenient point",
  source: "Kubernetes documentation, ServiceAccount token volume projection and bound token expiry",
  gateIntro: "A batch job that takes between forty minutes and six hours succeeds in staging and fails in production, but only for the largest tenants. It runs for hours and then fails on its final write with an authorisation error. Rerunning it succeeds whenever the tenant is small. The service account has the right permissions, the same permissions work for every short job in the same namespace, and nothing in the failure correlates with data content.",
  idea: "A credential whose lifetime is shorter than the operation holding it will fail at the last step, which is the most expensive place available to fail.",
  why: "Projected service account tokens are bound and short-lived, with an expiry on the order of an hour, and the kubelet rewrites the file on disk well before it expires. A client that reads the token once at process start is holding a string that will be rejected later, and no amount of correct RBAC changes that. The same shape appears with STS credentials assumed at startup, an OAuth access token cached in a client object, a database password derived from a token, and a presigned URL generated in one step and consumed after a queue wait in another.\n\nIt fails at the end because long operations read early and commit late, so the first call after expiry is usually the write you least want to lose. And it hides in staging because staging data is small enough that the whole operation finishes inside the credential lifetime. Duration-dependent failure that only affects your biggest tenants is the tell: the variable is elapsed time, not input.",
  failureMode: "A Temporal activity that runs for hours holding a client constructed at activity start. An Argo step that presigns object storage URLs which a later step consumes after sitting in a queue. A long ClickHouse extraction authenticated once at session open. Each of these looks correct in review, because the credential acquisition is right next to the operation in the code and the gap between them only exists at runtime, only for large inputs.",
  experiment: "Take the longest-running workflow you operate and get its p99 duration from history rather than from memory. List every credential it acquires and the lifetime of each: projected token expirationSeconds, STS session duration, presigned URL expiry, OAuth token TTL. Any lifetime shorter than that p99 is a live defect. Then check whether the client re-reads the token path or reads it once, because refresh in the path is the only real fix.",
  reflection: "What is the longest operation you run, and does every credential it holds outlive it?",
  recall: {
    q: "A job fails only for large tenants and only on its final step. What is your first hypothesis?",
    a: "A credential that expired during the run. Long operations read early and write late, so the first call after expiry is the commit, and small tenants never reach the boundary.\n\nCheck credential lifetime against p99 operation duration, and check whether the client refreshes from the token path or captured the value once at startup."
  },
  deepDive: "Compare the p99 duration of my longest Temporal workflows against the lifetime of every credential they hold, and tell me which clients read their token once instead of refreshing."
},
{
  id: "time-partitions-run-out",
  track: "time", level: "mechanism",
  title: "Time-based partitions stop being created before you notice they are missing",
  source: "PostgreSQL documentation, declarative partitioning and partition maintenance",
  gateIntro: "At 00:00 UTC on a Saturday every insert into the largest table in the analytics database began to fail. Query load was normal, the host had spare disk, CPU and connections, and no schema change had been deployed for eleven weeks. The writing service had not been modified in months. Reads against the same table continued to work perfectly, and the engineer who originally built the table left the company in the spring.",
  idea: "Time-based partitioning schedules a failure for a calendar date rather than triggering it with load, so the alert has to be on remaining runway rather than on errors.",
  why: "With declarative partitioning and no default partition, a row whose key falls outside every existing partition is rejected outright. Partitions are created ahead of time by a maintenance job. If that job dies, nothing breaks: the pre-created runway absorbs it. The system keeps working perfectly until the last partition's upper bound is reached, and then every insert fails at once, at midnight, on a boundary.\n\nThe gap between cause and symptom is the whole problem. The maintenance job failed weeks or months before the outage, far enough back that nobody connects the two, and the person who would have connected them may have left. The same shape covers anything pre-provisioned in advance: certificates, IP space in a CIDR block, licence files, pre-generated identifier ranges. For all of them the monitorable quantity is runway in days, and the error rate is not an early warning, it is the outage.",
  failureMode: "In ClickHouse the mirror image bites instead. Partitions are created implicitly, so you never run out, and the hazard runs the other way: an over-granular PARTITION BY produces many small parts, merges cannot keep up, and inserts are eventually rejected for too many parts. One estate can hold both shapes at once, and neither is triggered by traffic. One is a wall on a date, the other is a slope that intersects the limit on a date.",
  experiment: "For every time-partitioned table you own, compute days of runway as the highest partition upper bound minus today. Put the minimum across all tables on a single Grafana panel and alert at 30 days. Then do the ClickHouse mirror check: parts per partition and total parts per table against the rejection threshold, graphed as a trend rather than a level, so you can read the date it intersects.",
  reflection: "How many days of partition runway do you have on your most important table, and who would be paged when the maintenance job dies rather than when the runway ends?",
  recall: {
    q: "Why does a broken partition maintenance job not page you when it breaks?",
    a: "Because the pre-created partitions keep absorbing writes. The system is fully healthy for as long as the runway lasts, so the failure surfaces weeks or months later at a partition boundary, with no change anywhere near the outage.\n\nAlert on runway in days, not on insert errors. The same rule applies to anything provisioned in advance: certificates, address space, licences, identifier ranges."
  },
  deepDive: "Work out the partition runway across my Postgres and the parts trend across my ClickHouse tables, and give me the two alerts that would have caught each shape a month early."
},
{
  id: "time-retention-is-a-scheduled-delete",
  track: "time", level: "mechanism",
  title: "A retention policy is a delete you scheduled months ago and will not remember",
  source: "ClickHouse documentation, TTL for columns and tables",
  gateIntro: "A quarterly tenant usage report that has run cleanly for two years returns numbers that are too low. Nothing errors. The pipeline is green, every source table is present, and row counts for recent days look exactly as expected. The discrepancy grows the further back the report reaches. A different team added a second report against the same tables six weeks ago, and that one looks fine.",
  idea: "A retention policy is a delete scheduled by whoever created the table, and it executes against consumers who were not in the room.",
  why: "A TTL expression on a table or column removes data as merges run, on a timetable driven by merge activity rather than by any job a human watches. The row is simply not there. There is no error, no audit line in the query path, and no difference between data that never arrived and data that was correctly aged out. A query that used to return a number returns a smaller one.\n\nThe real defect is coupling. Retention is set once, by one team, for one consumer, and every later consumer inherits an invisible constraint that nothing in the schema declares. Nothing tells the new report that rows older than N days are not merely absent from this environment but guaranteed to be absent forever. Because TTL applies during merges rather than at a boundary instant, the data also disappears gradually, so the report degrades instead of breaking, which is the failure mode least likely to be noticed.",
  failureMode: "An audit table with 90 day retention that compliance later needs a twelve month lookback against. A metrics table whose downsampling drops exactly the resolution a capacity model was built on. A Temporal namespace retention period shorter than the window a monthly reconciliation reaches back over, so the reconciliation quietly stops seeing closed executions. In every case the owner of the policy never learns, because the loss is only observable from the consumer's side.",
  experiment: "Put every retention rule in the estate on one page. In ClickHouse: SELECT database, table, engine_full FROM system.tables WHERE engine_full LIKE '%TTL%'. Add your Temporal namespace retention, log and trace retention, and object storage lifecycle rules. Then, next to each, write the longest lookback any consumer performs against it. Every row where the consumer window exceeds the source retention is a report that is already wrong.",
  reflection: "Which of your retention windows was chosen by someone who no longer knows who reads that data?",
  recall: {
    q: "What distinguishes a retention problem from a pipeline bug in a report that returns numbers too low?",
    a: "A pipeline bug hits recent data and usually errors somewhere. Retention loss is silent, affects only old data, and gets monotonically worse the further back the query reaches.\n\nThe confirming test is a clean rerun. If reprocessing from source reproduces the same shortfall, the rows are genuinely gone rather than missed, and you are looking at a policy rather than a defect."
  },
  deepDive: "Collect every retention and TTL setting across my ClickHouse, Temporal and object storage, and flag each one where some consumer's lookback window is longer than the data it depends on lives."
}
);
