/* Track: Risk capacity and sequence. Ordered foundational first.
 *
 * Drafted, then independently fact-checked against primary sources, then
 * revised against those verdicts. Entries whose central claim did not survive
 * the check were dropped rather than softened.
 */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "first-decade-decides-the-thirty-years",
  track: "risk",
  level: "core",
  title: "The first decade of equity returns predicts your thirty-year withdrawal rate better than the full thirty years do",
  source: "Michael Kitces, \"Understanding Sequence Of Return Risk: Safe Withdrawal Rates, Bear Market Crashes, And Bad Decades\", Nerd's Eye View (kitces.com), 1 October 2014",
  evidence: "Rolling historical US 30-year retirements, correlating the maximum sustainable inflation-adjusted withdrawal rate from a 60/40 portfolio against equity (S&P 500) returns over different windows. Note the predictor throughout is equity returns, not the 60/40 portfolio's own returns. Correlation with the first year's equity return: 0.21. With the first 10 years' nominal equity return: 0.44. With the first 10 years' real equity return: 0.79 as quoted in the body text, though the article elsewhere reports the correlation peaking at 0.810 after 9 years and still 0.808 after 10, so the article carries two figures for the same window. With the full 30-year real equity return: 0.43. Against the full 30-year nominal equity return the correlation is slightly negative, which Kitces attributes to inflation rather than to sequence. Shiller CAEP (E10/P) at the retirement date correlates 0.77 with the 30-year safe withdrawal rate. The article does not state its data window or the number of rolling periods.",
  replication: "single",
  gateIntro: "You are ten years out. Someone offers you a choice of one piece of information about the thirty years of retirement ahead: either the total real return equities deliver across the whole thirty years, or the real return equities deliver in just the first decade. You get one, and you have to set a spending rate off it. Which one do you take, and how much better do you think it is than the other?",
  idea: "For a portfolio you are drawing down, when the returns arrive matters more than how much they total. Across historical US 30-year retirements, the first decade's real equity return correlates 0.79 with the sustainable withdrawal rate of a 60/40 portfolio, against 0.43 for the full thirty years' real equity return - roughly twice as informative. The thirty-year nominal return correlates slightly negatively, but that is an inflation artefact rather than a sequence effect, and the same window measured in real terms flips positive.",
  why: "The mechanism is that withdrawals convert a percentage loss into a permanent unit loss. Multiplication commutes, so if no money moves in or out, a sequence of returns in any order lands on the same ending balance. The moment you sell units to fund spending, it stops commuting. A 30% fall in year two means you sell more units at the bottom to raise the same dollars, and those units are gone before the recovery arrives. The recovery then compounds a smaller base for the remaining twenty-eight years.\n\nThat is why the correlation profile has the shape it does. The first decade sets how much of your capital base survives to compound. Returns in years twenty to thirty arrive when the number of units still standing has already been decided, so they move your terminal wealth but barely move the question of whether you ran out. It is worth noticing that the predictor Kitces uses is the equity sleeve specifically, not the blended 60/40 return - equities are the volatile component and the one whose fall does the damage, even though the withdrawal rate being predicted comes from the blended portfolio.\n\nDo not over-read the negative correlation on thirty-year nominal returns. Kitces attributes it to inflation, not to sequence: nominal returns run high when inflation runs high, and high inflation is exactly what forces an inflation-indexed withdrawal path upward. The proof is that the same thirty-year window measured in real terms flips to +0.43, which Kitces describes as a solid correlation and as being about as predictive as the first decade's nominal figure. The full-period real return is genuinely informative. It is just half as informative as the first decade.\n\nThe same logic runs in reverse during accumulation and this is the part people invert. When you are contributing, a crash in your first decade is a discount on units you are still buying, and a crash in your last decade hits the largest balance you will ever have. The saver's exposure is back-loaded, the retiree's is front-loaded, and the crossover sits right around the point where your contributions stop and your drawdowns start. Note what is filed here and what is not: this is one practitioner's analysis with no stated data window and no independent re-run, which is why it sits at single. The direction of the effect is not seriously disputed, but the coefficients are one team's arithmetic on one country's history and should be treated as illustrative magnitudes, not estimates with error bars.",
  failureMode: "You look at a long-run average return, call it 7.5% real minus a 4% draw, conclude you have 3.5% of headroom, and set your spending on that. Then you retire into a bad first decade and discover the average was never the constraint. Concretely: two retirees with identical thirty-year average returns can end at wildly different places, and the one who took the losses first does not get to spend the difference. The failure is silent for years, because the balance still looks big while the unit count is quietly falling below what the remaining term needs.",
  experiment: "Pull your own super balance and write down the number you would be drawing from if you stopped work at preservation age. Now apply a 30% fall in year one while still withdrawing your planned annual amount in dollars, and compound the remainder at your assumed long-run rate for the remaining twenty-nine years. Do it again with the 30% fall in year twenty-nine instead. The ending balances will differ by a multiple, not a margin, and the size of that gap is your personal sequence exposure. If the gap makes you uncomfortable, that is a capacity signal, not a nerve signal.",
  reflection: "If you knew today that your first retirement decade would deliver zero real return on equities, what would you change now - the retirement date, the spending rate, the asset mix, or the size of the cash buffer? Pick exactly one and say why the others are worse.",
  recall: {
    q: "Why does the first decade of equity returns predict a thirty-year retirement's sustainable withdrawal rate better than the full thirty years do, and what should you not read into the negative correlation with thirty-year nominal returns?",
    a: "Because withdrawals break the commutativity of returns. Without cashflows, the order of returns cannot change the ending balance - multiplication commutes. With withdrawals, a loss early forces you to sell more units to raise the same dollars, and those units never come back to participate in the recovery. A whole-period average is a summary statistic that has thrown away exactly the information that mattered, namely when the losses landed. In the Kitces analysis the predictor is equity returns and the thing predicted is the safe withdrawal rate of a 60/40 portfolio: the first decade's real equity return correlates 0.79, the full thirty years' real equity return 0.43.\n\nThe negative correlation on thirty-year nominal returns is not extra evidence for sequence risk. Kitces attributes it to inflation - nominal returns run high when inflation runs high, and inflation is what drives an indexed withdrawal path upward - and he demonstrates it by showing the same window flips to +0.43 once deflated. So the honest reading is that the full-period real return is genuinely predictive, just about half as predictive as the first decade. The number to watch is the one describing conditions at and just after your start date. That is also why valuation at the retirement date shows up strongly, with Shiller CAEP correlating 0.77 with the thirty-year safe withdrawal rate. Practically, your retirement date is a risk decision in its own right, and a plan that is only robust to the average is not robust at all."
  },
  deepDive: "Walk me through a 1966 US retiree and a 1982 US retiree year by year on the same 4% inflation-adjusted plan, and show me the exact year at which the 1966 retiree's position became unrecoverable even with perfect subsequent returns."
},
{
  id: "four-percent-is-forty-one-overlapping-windows",
  track: "risk",
  level: "core",
  title: "The 4% rule is forty-one overlapping windows of one country's best century, not a 95% probability",
  source: "Philip L. Cooley, Carl M. Hubbard and Daniel T. Walz, \"Retirement Savings: Choosing a Withdrawal Rate That Is Sustainable\", AAII Journal, February 1998 (the Trinity study), Table 3",
  evidence: "Annual US returns 1926 to 1995, S&P 500 for stocks and long-term high-grade corporate bonds, Ibbotson data, no tax or transaction costs. Table 3 reports inflation-adjusted withdrawals. At a 4% initial withdrawal rate over a 30-year payout period the portfolio success rates are 95% for 100% stocks, 98% for 75/25, 95% for 50/50, 71% for 25/75 and 20% for 100% bonds. At a 12% withdrawal rate over the same 30-year period only the all-stock portfolio survives at all, at 15%, while every mix containing bonds scores 0. The paper states that the number of overlapping 30-year payout periods from 1926 to 1995 is 41. Arithmetic on that stated window, not a claim of the paper: those 41 windows run 1926-1955 through 1966-1995, adjacent windows share 29 of their 30 years, and seventy years of data contains at most two non-overlapping 30-year windows. The paper reports no effective sample size and makes no independence claim either way.",
  replication: "overclaimed",
  gateIntro: "You have read that the 4% rule has a 95% success rate over thirty years. Before you go further: what do you think that 95% is a percentage of? How many genuinely independent thirty-year retirements do you think the number was computed over, given that the study used seventy years of market history?",
  idea: "The 4% figure is real and it is not a fabrication - a 4% inflation-adjusted draw survived 95% of the 41 rolling 30-year windows in 1926 to 1995 US data for an all-stock portfolio, and 98% for a 75/25 mix. But those 41 windows are carved out of 70 years of one country's history, and adjacent windows share twenty-nine of their thirty years. The popular version treats the 95% as a probability drawn from 41 independent retirements. It is not a sampling distribution, and the paper never claims it is.",
  why: "Overlapping windows are not independent observations. The 1926 window and the 1927 window share twenty-nine of their thirty years. The full set runs from 1926-1955 through 1966-1995, so there is no single year present in all 41 - the first and last windows do not overlap at all - but almost every adjacent pair is nearly identical, and the middle decades of the century appear in most of them. Seventy years of returns contains at most two non-overlapping thirty-year retirements. What the 95% actually tells you is that a 4% draw survived the US twentieth century almost everywhere you could slice it. That is a genuinely useful fact. It is not a sampling distribution, it carries no confidence interval, and the paper reports no effective sample size, which is why the interval field on this entry is empty rather than invented.\n\nThe sensitivity of the table to small changes shows how thin the base is. Hold the 4% draw and the 30-year term fixed and just change the asset mix: 98% for 75/25, 95% for 100% stocks and 50/50, 71% for 25/75, 20% for all bonds. A single decision about bond weight moves the headline number by 78 percentage points. Note also that the popular version usually attaches the 95% to an all-stock portfolio when the best mix in that row is actually 75/25. A statistic this fragile is describing a specific historical path, not a stable property of markets.\n\nThe assumptions stack the same way. The study explicitly excludes taxes and transaction costs. It assumes you hold the withdrawal path rigid through a crash, which almost nobody does. It uses US large caps and long-term corporates, an asset pair that had an unusually good century relative to almost every other developed market. Each of those makes the published number more optimistic than your situation.\n\nWhat survives all of this is the ordering, not the level, and the ordering is the opposite of the folk version. Cooley, Hubbard and Walz conclude that bonds raise the success rate at low to mid withdrawal rates, while stocks are what make high withdrawal rates survivable at all. Table 3's 30-year row shows it directly: at 4% the 75/25 mix scores 98 against all-stock's 95, and at 12% the all-stock portfolio scores 15 while every mix containing bonds scores 0. Longer horizons need lower rates. Those relationships are robust across every version of the table. The specific 4% and the specific 95% are the parts you should hold loosely.",
  failureMode: "You treat 4% as a solved constant and plan a retirement date around it, which means you have bought a false sense of precision at the exact moment precision matters. The cost is that you stop asking the question that actually determines the outcome - what happens if I get the bad tail - because you believe a study already answered it with 95% confidence. The real exposure is that you retire on a number calibrated to a country and a century that is not yours, with a rigid spending rule the study assumed and you will not follow.",
  experiment: "Take your projected retirement balance and compute 4% of it. Then compute what your actual annual spending is today, after tax, from your last twelve months of bank and card statements. Look at the gap. If your spending is above the 4% figure, the interesting question is not whether the rule is 95% or 85% accurate - it is which line items are genuinely fixed and which are discretionary, because the flexibility in that second bucket is worth more than any refinement to the withdrawal rate. Write down the dollar value of the discretionary bucket. That number is your real safety margin.",
  reflection: "If the 4% figure came from forty-one overlapping windows of a single country's history, what would you need to see before you would raise your own planned withdrawal rate above it - and is that evidence obtainable at all?",
  recall: {
    q: "The Trinity study reports a 95% portfolio success rate for a 4% inflation-adjusted withdrawal over thirty years. Why is that not a 95% probability that your retirement will work, and what is it actually a statement about?",
    a: "It is a statement about historical coverage, not probability. The 95% is the share of 41 rolling 30-year windows in 1926 to 1995 US data that a 4% inflation-adjusted draw survived with an all-stock portfolio. Those 41 windows overlap heavily - adjacent windows share twenty-nine of thirty years, and seventy years of data contains at most two non-overlapping thirty-year retirements. So the number says a 4% draw survived nearly every slice of the US twentieth century, which is real evidence, but it carries nothing like 41 observations' worth of information and no genuine confidence interval.\n\nIt is also conditional on assumptions that do not describe you. No tax, no transaction costs, a rigid inflation-indexed withdrawal path held through every crash, and US large caps plus long-term corporates over a century that flattered them. Change only the bond weight and the same table gives 98% for 75/25 and 20% for all bonds, a swing that shows the figure is tracking a historical path rather than a stable market property. What generalises is the shape: bonds raise the success rate at low to mid withdrawal rates while stocks are what make high rates survivable at all, longer horizons need lower rates, and flexibility in spending is worth more than precision in the rate."
  },
  deepDive: "Rebuild the Trinity Table 3 result for Australian data instead of US data, and tell me honestly how much of the difference is real and how much is an artefact of a shorter or noisier series."
},
{
  id: "volatility-drag-is-half-the-variance",
  track: "risk",
  level: "advanced",
  title: "Volatility subtracts about half the variance from your compound return, every year, whether or not anything goes wrong",
  source: "Michael Kitces, \"Volatility Drag: How Variance Drains Investment Returns\", Nerd's Eye View (kitces.com), Examples 1 to 3, at kitces.com/blog/volatility-drag-variance-drain-mean-arithmetic-vs-geometric-average-investment-returns/",
  evidence: "Geometric return is approximately arithmetic return minus variance/2. S&P 500, 2007 to 2016: arithmetic mean 8.75%, standard deviation 18.86%, so variance 3.56%, giving 8.75% minus 1.78% = 6.97% against an actual compound return of 6.94%. Barclays Aggregate Bond over the same ten years: arithmetic mean 4.39%, standard deviation 3.12%, variance 0.10%, giving 4.39% minus 0.05% = 4.34% against an actual 4.35%. Both approximations land within 0.03 percentage points of the realised compound return. Both series come from the same article, the same author and the same decade, which is why this is filed as single rather than replicated.",
  replication: "single",
  gateIntro: "Two funds report the same average annual return of 8.75% over the last decade. One has a standard deviation of 19%, the other 3%. You put a dollar in each at the start and leave it alone. Before reading on: how far apart are the two ending balances, and can you say roughly how much of the gap the volatility alone explains?",
  idea: "An average annual return is an arithmetic mean and your money grows at the geometric mean, which is lower. The gap is approximately half the variance, and over 2007 to 2016 that approximation landed within 0.03 percentage points of the realised compound return on both equities and bonds. It is an approximation that falls out of the algebra of compounding rather than an empirical effect, which is why it shows up wherever you look - and also why it degrades as volatility rises.",
  why: "Losses and gains are asymmetric in percentage terms. Down 50% then up 50% leaves you at 0.75, not 1.00, because the up move applies to a smaller base. Formalise that across many periods under lognormality and the compound growth rate is approximately the arithmetic mean minus half the variance. The term is not a fee, a behavioural error or a market inefficiency. It is what happens when you multiply rather than add.\n\nThe practical bite is that the penalty scales with the square of volatility. Going from 3.12% to 18.86% standard deviation is roughly a six-fold rise in volatility but roughly a thirty-six-fold rise in the drag term - 0.05 percentage points against 1.78 percentage points a year. That is why the drag is invisible in bonds and material in equities, and why it grows disproportionately as you reach for return by reaching for risk.\n\nThis interacts directly with sequence risk but is not the same thing. Volatility drag applies with no cashflows at all. Sequence risk applies only when money is moving in or out. Stack them and a decumulating portfolio pays the drag on the compounding and pays again on the units it liquidates into a fall. A projection built on an arithmetic mean return with no volatility term is overstating both.\n\nBe careful about what is being claimed, in two directions. First, geometric equals arithmetic minus half the variance is an approximation, not an identity. It assumes an underlying lognormal distribution and a real return series will not perfectly conform, which is why the fit above is close rather than exact, and the fit degrades as volatility rises. Second, the correction has a direction, and getting the direction wrong is the more expensive error. A Monte Carlo simulator generates the drag itself out of the volatility you hand it, so feeding it a drag-adjusted return counts volatility twice, understating long-term returns and overstating the plan's risk. Kitces makes exactly that point in the same article. The subtraction belongs in deterministic single-rate projections, not in simulators.",
  failureMode: "You build a thirty-year projection in a spreadsheet that compounds one fixed rate a year, and you plug in a 10% expected return taken from the long-run arithmetic average of a series with 17% volatility. The correct compound figure is about 8.56%. Over thirty years that 1.44 percentage point gap compounds to roughly a third less terminal wealth than your projection promised, and you will not notice until you are close enough to retirement that the correction is unaffordable. The same error inflates every replacement-rate calculation downstream of it. The mirror-image error costs you too: hand a geometric return to a Monte Carlo tool that also applies its own volatility, and you will conclude your plan is riskier than it is and over-insure against it.",
  experiment: "Open whatever retirement projection you use, find the return assumption, and first work out which kind of tool you are holding. If it compounds a single fixed rate with no volatility - a spreadsheet, most fund calculators - the figure needs to be a geometric return. If the documentation does not say, assume it is arithmetic and subtract half the square of your assumed volatility: 7.5% with 12% volatility becomes 7.5% minus 0.72% = 6.78%. Rerun and compare terminal balances; the difference is the error you have been carrying. If instead it is a Monte Carlo simulator drawing random returns from a volatility you supply, do the opposite - it manufactures the drag itself, so it wants the arithmetic mean, and subtracting half the variance before you run it counts the volatility twice.",
  reflection: "Where in your current planning does an arithmetic mean masquerade as a compound growth rate - and is there anywhere you have handed a compound rate to a tool that was going to apply the drag again itself?",
  recall: {
    q: "Why is the geometric return lower than the arithmetic return, roughly by how much, and why does it matter which kind of projection tool you feed each figure into?",
    a: "Because compounding multiplies rather than adds, and percentage losses and gains are asymmetric. Down 50% then up 50% leaves 0.75, not 1.00, since the recovery applies to a shrunken base. Under a lognormal assumption the compound growth rate is approximately the arithmetic mean minus half the variance - an approximation, not an identity, and one that degrades as volatility rises. On the S&P 500 from 2007 to 2016 the arithmetic mean was 8.75% with 18.86% standard deviation, so the drag term was 1.78 percentage points and the predicted 6.97% matched the realised 6.94% compound return. On the Barclays Aggregate over the same period the arithmetic mean was 4.39% with 3.12% standard deviation, a drag of only 0.05 points, predicting 4.34% against a realised 4.35%. The penalty scales with the square of volatility, so roughly six times the volatility means roughly thirty-six times the drag.\n\nWhich figure to use depends entirely on the tool. A deterministic projection that compounds a single rate has no volatility of its own, so it needs the geometric figure, and handing it an arithmetic mean overstates terminal wealth. A Monte Carlo simulator draws returns from a volatility you supply and therefore produces the drag itself, so it needs the arithmetic mean - subtract half the variance before feeding it and you have counted volatility twice, understating returns and overstating the risk of the plan. Volatility drag is also distinct from sequence risk, which requires cashflows to exist at all: the drag applies to a portfolio nobody touches."
  },
  deepDive: "Show me the derivation of geometric as arithmetic minus half the variance under lognormality, then show me with worked numbers where that approximation breaks down at high volatility."
},
{
  id: "pension-taper-absorbs-a-crash-for-some",
  track: "risk",
  level: "applied",
  title: "A 25% market fall costs a median Australian retiree 5% of income and an 80th-percentile retiree 19%",
  source: "Australian Government Treasury, Retirement Income Review Final Report, November 2020, Chapter 2 (Adequacy), section 2C, Box 2C-6 and Chart 2C-23, Cameo modelling undertaken for the review",
  evidence: "Cameo modelling of a 25% fall in equity market returns in a single year immediately after retirement, producing a 12.5% fall in superannuation and non-superannuation asset values against the review's baseline 6.2% retirement-phase return, with asset prices recovering to trend over five years. Median earner: total retirement income falls 5% in the following year, because a 19% fall in superannuation drawdowns is offset by a 14% rise in Age Pension entitlement; the permanent effect is about a 1% fall in income across retirement. 80th percentile earner: income falls 19%, with no offsetting Age Pension, and in the review's words remains under pre-shock levels for longer than a median earner and does not fully recover until higher-wealth retirees begin to receive the Age Pension. The review puts no number of years on that recovery.",
  replication: "single",
  gateIntro: "Two Australians retire in the same month with the same balanced investment option and the same self-assessed appetite for risk. One is a median earner, one is at the 80th percentile. Markets fall 25% the following year. Before reading on: how differently do their retirement incomes move, and which of the two is more exposed?",
  idea: "Risk capacity is not risk tolerance, and in Australia the Age Pension means test is what draws the line between them. Treasury's modelling of a 25% market fall right after retirement shows a median earner losing 5% of income for a year and about 1% permanently, because the means test automatically raises their pension as their assets fall. An 80th-percentile retiree with identical psychology loses 19% with no offset at all.",
  why: "The mechanism is that the means test is a partial hedge you did not buy. Your assets fall, your assessable assets fall with them, and your Age Pension entitlement rises to fill part of the hole. In the modelled median case a 19% drop in superannuation drawdowns is met by a 14% rise in pension, netting out to a 5% income fall. The government is absorbing sequence risk on your behalf, and it does so automatically and immediately.\n\nThat hedge has a ceiling and the ceiling is the means test cut-off. Above it, the pension contributes nothing and a fall in assets translates straight through to a fall in income. The 80th-percentile retiree in the same scenario takes the full 19%, and Treasury's note is that their income stays below pre-shock levels until they eventually become pension-eligible. The counterintuitive result is that more wealth means more sequence exposure, not less, over the range where the pension is phasing out or absent. Capacity is not monotonic in balance.\n\nThis is why a risk questionnaire cannot answer the question. Two people with the same score, the same fund and the same option face materially different downside because their income floors differ. The number that governs capacity is the share of your required spending that must come from portfolio drawdowns rather than from a guaranteed indexed floor. That share is knowable in advance and it is not a psychological quantity.\n\nHold the evidence at the right strength. This is one modelling exercise by one team using one cameo, published in 2020, and it has not been independently reproduced. The parameters are assumptions, not measurements - the 6.2% baseline return, the five-year recovery to trend, the single-year shock shape. The direction and the rough scale are what to carry, not the decimal places, and the cameo gives you exactly two points, not a curve.",
  failureMode: "You benchmark your risk settings against a friend or a forum consensus without checking whether your income floor matches theirs. If you are above the assets test cut-off, you have been told a crash costs about 5% of income when for you it costs closer to 19%, and Treasury's own note is that it stays below pre-shock levels not for a year but until you draw down far enough to become pension-eligible - a duration the review deliberately does not quantify. Concretely, that means the de-risking or cash-buffer decision you deferred as unnecessary was in fact the one that would have mattered, and you find that out only once the fall has already happened.",
  experiment: "Work out today what fraction of your projected annual retirement spending would have to come from your own portfolio rather than from a guaranteed indexed source. Take your target annual spend, subtract the Age Pension you would actually be entitled to given your projected assessable assets, and divide the remainder by the target spend. That fraction is your sequence exposure coefficient. Multiply your portfolio drawdown by a 25% market fall and see what happens to total income. Treasury's cameo gives you two reference points to sit between - a median earner at minus 5% for a year, an 80th-percentile earner at minus 19% - so place yourself on that line rather than looking for a threshold, because the modelling does not contain one.",
  reflection: "What fraction of your planned retirement spending has to come out of assets you own, rather than from an indexed floor you cannot lose - and does your current asset allocation reflect that fraction or your personality?",
  recall: {
    q: "Why does the same market fall cost a median Australian retiree far less income than a wealthier one, and what does that tell you about the relationship between wealth and risk capacity?",
    a: "Because the Age Pension means test acts as an automatic partial hedge. When asset values fall, assessable assets fall, and pension entitlement rises to fill part of the gap. In Treasury's Cameo modelling of a 25% equity fall in the year after retirement, the median earner's superannuation drawdowns fell 19% but their Age Pension rose 14%, so total retirement income fell only 5% in the following year and about 1% permanently. The 80th-percentile earner, above the means test range, got no offset and took the full 19% income fall, with income staying below pre-shock levels until they eventually became pension-eligible - the review gives no number of years for that.\n\nThe implication is that risk capacity is not monotonic in wealth. Over the range where the pension is absent or phasing out, more assets mean more of your income is exposed to markets and less of it is guaranteed. The number that actually governs capacity is the share of required spending that must come from portfolio drawdowns rather than an indexed floor, which is calculable in advance and has nothing to do with how you feel about volatility. Two people with identical questionnaire scores can sit at opposite ends of this, and only one of them is being told the truth by the generic advice."
  },
  deepDive: "Model my situation specifically: given my projected assessable assets at retirement, compute what fraction of my target spending is pension-backed versus portfolio-backed, and show how that fraction moves under a 25% market fall."
},
{
  id: "measured-risk-tolerance-tracks-sentiment",
  track: "risk",
  level: "applied",
  title: "Measured risk tolerance rises and falls with consumer sentiment, so the score is contaminated by mood",
  source: "Claudia R. Sahm, \"Stability of Risk Preference\", Federal Reserve Board FEDS Working Paper 2007-66, 26 October 2007",
  evidence: "Maximum-likelihood estimation of a correlated random effects model on hypothetical lifetime-income gambles: 18,625 gamble responses from 12,003 individuals across the 1992, 1994, 1998, 2000 and 2002 waves of the US Health and Retirement Study. The macroeconomic predictor is the Index of Consumer Sentiment in the month of the gamble response, a household survey, not a market variable. A ten-point rise in the sentiment index is associated with a 9% rise in measured risk tolerance. Measured risk tolerance rose 36% from October 1992 to February 2000 and fell 15% between May 2002 and February 2003. Each year of age is associated with a 1.7% decline, implying almost a 20% decrease over the survey period. Persistent across-person differences account for 73% of the systematic variation, while systematic within-person change accounts for only 11% of total variance in the measure. The estimated standard deviation of transitory response error is 1.55, more than twice the 0.72 standard deviation of the persistent individual effect. The sentiment effect is short-lived: 0.006 at the time of response (t = 2.2), 0.004 six months prior (t = 1.6) and -0.001 a year prior (t = -0.4).",
  replication: "single",
  gateIntro: "You fill in your fund's risk profile questionnaire and it returns a score. Suppose you had filled in the identical questionnaire in February 2000 and again in February 2003, with no change to your job, health, family or balance. Before reading on: how different would your score be, and would you have called that a change in your preferences?",
  idea: "Risk tolerance as measured by survey instruments moves with consumer sentiment. Across a decade of US panel data, a ten-point rise in the Index of Consumer Sentiment is associated with a 9% rise in measured risk tolerance, and measured tolerance rose 36% from October 1992 to February 2000 then fell 15% between May 2002 and February 2003. Worse, the transitory noise in an individual response has more than twice the standard deviation of the stable personal component the questionnaire is trying to detect.",
  why: "Start with what was actually measured. Sahm's predictor is the Index of Consumer Sentiment in the month of response - a household confidence survey - and the paper never estimates a relationship with equity prices. The dated swings happen to bracket a market peak and a slump, and sentiment and markets do move together, but the estimated coefficient is on mood. The practical worry survives the distinction: an instrument that reads you as more tolerant when confidence is high and less tolerant after confidence has broken will bias a periodically-refreshed allocation toward the classic behavioural error. That it is mood rather than preference is visible in how quickly the effect decays - 0.006 at the moment of response, 0.004 six months earlier, and gone at a year.\n\nThe signal-to-noise problem is the deeper issue. Persistent across-person differences account for 73% of the systematic variation, so there is something stable and real being measured. But the estimated standard deviation of the transitory response error is 1.55 against 0.72 for the persistent individual effect. On any single administration of the instrument, more of what you observe is noise than signal. Systematic within-person change accounts for only 11% of total variance in the measure. A single questionnaire, taken once, is a weak read on a real but small quantity.\n\nThere is also a slow drift that has nothing to do with sentiment: each year of age is associated with a 1.7% decline in risk tolerance, almost 20% over the decade of the panel. That is a genuine trend and it runs in the direction most glide paths assume. But it is small next to the swings driven by sentiment, which means over any short window your questionnaire is telling you more about the month you filled it in than about you.\n\nOne team, one dataset, one instrument. This has not been independently re-run at this specification, so it is filed as single, not replicated. It also studies economists' hypothetical lifetime-income gambles rather than the specific questionnaires Australian funds use, so the transfer is an inference rather than a measurement. The general lesson - that stated risk attitude is a noisy, mood-contaminated read - is what to carry.",
  failureMode: "You take your risk profile score at face value, either from your fund or from an adviser, and let it set your allocation. Confidence runs high late in a long run-up and low after a fall, so a score taken in early 2000 reads you as more aggressive than you are and the same questionnaire in early 2003 reads you as more conservative. Acting on both readings means you raised your equity weight near a peak and cut it near a trough, and the round trip is a permanent, unrecoverable loss to a portfolio you are about to start drawing from. The instrument did not fail loudly - it returned a plausible number both times.",
  experiment: "Find the date you last completed a risk profile questionnaire and write down what the mood was that month - the headlines, what your colleagues and the forums were saying. Then answer it again today, cold, without looking at your previous answers, and compare. If your score moved, ask what changed in your actual circumstances - your income floor, your fixed costs, your time to preservation age, your dependents. If none of those moved, you have just measured the instrument's noise rather than your preferences, and you now know how much weight it deserves in an allocation decision.",
  reflection: "When you last felt like reducing risk, was it because a fact about your plan had changed, or because the mood around you had - and can you tell the difference from your own notes at the time?",
  recall: {
    q: "What is wrong with using a single risk tolerance questionnaire score to set your asset allocation, and what does the panel evidence say about how much of that score is signal?",
    a: "Two things are wrong. First, the score tracks mood. In Sahm's HRS panel of 18,625 gamble responses from 12,003 individuals across 1992 to 2002, a ten-point rise in the Index of Consumer Sentiment was associated with a 9% rise in measured risk tolerance, and measured tolerance rose 36% from October 1992 to February 2000 then fell 15% between May 2002 and February 2003. The predictor is a household confidence index, not an equity index - the paper does not estimate a relationship with market prices - but the effect decays fast, strongest at the moment of response and gone by a year prior, which is the signature of mood rather than preference. Setting allocation off it biases you toward adding risk when confidence is high and cutting it after it breaks.\n\nSecond, the single-administration signal is weak. Persistent across-person differences account for 73% of the systematic variation, so a real stable trait exists, but the estimated standard deviation of transitory response error is 1.55 against 0.72 for the persistent individual component - more noise than signal in any one reading. Systematic within-person change explains only 11% of total variance. There is also a genuine slow drift of about 1.7% decline per year of age. The practical conclusion is to treat the score as one weak input and to anchor allocation on capacity instead: your income floor, your fixed costs and the share of spending that must come from the portfolio, all of which are calculable and none of which move with the month you happened to fill in the form."
  },
  deepDive: "Compare the Sahm HRS gamble measure with the specific risk profile questionnaires Australian super funds actually use, and tell me whether the sentiment finding plausibly transfers to those instruments."
},
{
  id: "fund-drawdown-is-not-index-drawdown",
  track: "risk",
  level: "applied",
  title: "Your super fund fell 24% in the GFC while the ASX accumulation index fell 41%, and only one of those is your sequence exposure",
  source: "Australian Government Treasury, Retirement Income Review Final Report, November 2020, Chapter 2 (Adequacy), section 2C, Box 2C-6 and Chart 2C-22, using APRA and Market Index data",
  evidence: "Between September 2007 and March 2009 the ASX accumulation index, which includes dividend payments, fell 41%. The fall in superannuation fund returns over the same period was 24%, about 58% of the index move. Index set to 100 at December 2006. Treasury attributes the gap to diversification: superannuation funds help protect members from investment risk through prudent and diversified investment strategies, so falls in fund returns are typically significantly lower than those in equity markets. The box offers no other mechanism.",
  replication: "single",
  gateIntro: "You are trying to size how bad a crash could be for the money you will retire on. The obvious reference point is the worst peak-to-trough fall in the Australian share market. Before reading on: how close is that number to what a default super option actually lost over the same period, and would using the index number make you too pessimistic or too optimistic?",
  idea: "Headline index drawdowns are not portfolio drawdowns. Over the worst eighteen months of the GFC, September 2007 to March 2009, the ASX accumulation index fell 41% while superannuation fund returns fell 24%, roughly 58% of the index move. If you are stress-testing your retirement plan against the index number, you are testing a portfolio you do not own.",
  why: "The gap comes from what a default option actually holds. A MySuper balanced option is a mix of Australian and international equities, fixed interest, unlisted property and infrastructure, and cash. Only part of it tracks the ASX, and some assets rose while equities fell. Treasury's stated explanation is diversification and nothing else - that funds protect members through prudent and diversified investment strategies, so fund falls are typically significantly lower than equity market falls, and the 41% against 24% figures are the measurement of that protection over one episode. A second explanation is widely offered, that unlisted valuations lag listed markets and so flatter the reported drawdown in the short run. That one is not Treasury's. It appears nowhere in the box, the chart or the note, so treat it as a hypothesis to check against your own fund's valuation policy rather than as part of the finding.\n\nWhy this matters for sequence risk specifically: sequence risk is driven by how many units you are forced to liquidate at depressed prices, so the input is the drawdown of the thing you actually sell. Overstate it and you will over-insure, holding years of cash you did not need and paying for that in forgone compounding across a thirty-year retirement. Understate it and you will be short of buffer at the only moment a buffer matters. Neither error is cheap, and the index number produces the first one by default.\n\nThere is still a trap in taking comfort from the smaller number. A 24% fall in a portfolio you are drawing 4% a year from is a substantial permanent unit loss, and it is a fall you will experience while also selling into it. The right conclusion is to use your own option's realised drawdown as the input, not to conclude that diversification has solved sequence risk.\n\nThis is one measurement of one episode from one source, so it is filed as single. It also predates significant changes to how default options are constructed and how unlisted assets are valued, so the 41-to-24 ratio observed across 2007 to 2009 is not a constant you can apply to the next crash. What generalises is the method: get the drawdown of the option you hold, not the market you read about.",
  failureMode: "You size your cash buffer against a 41% equity fall when your option realistically falls half that, and you carry three or four extra years of cash into a thirty-year retirement. At a four percentage point return gap between cash and your growth option, that is a compounding drag on a large balance for decades, paid to insure against a scenario your portfolio does not face. The opposite error is less common but worse: sizing a buffer off a reported fund drawdown without asking how much of the option sits in assets that are not marked daily, which is a question for your fund's valuation policy rather than something this chart answers.",
  experiment: "Go to your fund's website and find the calendar-year or monthly return history for the specific investment option you are in, not the fund's headline balanced option. Find the worst peak-to-trough cumulative fall in that series. That percentage, applied to your projected retirement balance and combined with your planned annual dollar withdrawal, is your actual first-year sequence exposure. Compare it to what you would have assumed using the ASX number, and size your cash or defensive buffer off the first figure. While you are there, note what share of the option sits in unlisted assets and how often the fund revalues them.",
  reflection: "What is the worst peak-to-trough fall your specific investment option has actually recorded, and how many years of your planned withdrawals does your current cash holding cover against a fall that size?",
  recall: {
    q: "Why is the ASX accumulation index drawdown the wrong input for sizing your own sequence risk, and what should you use instead?",
    a: "Because you do not own the index. Between September 2007 and March 2009 the ASX accumulation index fell 41% while superannuation fund returns fell 24% over the same period, about 58% of the index move. Treasury attributes that gap to diversification: a default option holds international equities, fixed interest, unlisted property and infrastructure and cash alongside Australian shares, so only part of it tracks the ASX. Sequence risk is driven by the price at which you are forced to liquidate units, so the input has to be the drawdown of the thing you actually sell.\n\nUsing the index number makes you over-insure. Carrying several extra years of cash across a thirty-year retirement is a real compounding cost paid against a scenario your portfolio does not face. But do not swing the other way: a 24% fall on a portfolio you are drawing from is still a substantial permanent unit loss. The right method is to pull the realised peak-to-trough series for your specific investment option, apply it to your projected balance alongside your planned annual withdrawal, and size the defensive buffer off that. The 41-to-24 ratio is one measurement of one episode and predates changes to how default options are built, so do not treat it as a constant. And if your option holds a large unlisted allocation, ask the fund how often those assets are revalued - that is a real question about what a reported drawdown means, but it is your question to ask, not something Treasury's chart establishes."
  },
  deepDive: "Pull the realised monthly return history for my specific super option, find its worst peak-to-trough drawdown, and compare it against the ASX accumulation index over the same windows."
}
);
