/* Track: Framing the objection. Ordered foundational first.
 *
 * Between noticing and speaking there is a construction step that most people
 * skip. An unease said out loud is an unease. The work here is turning it into
 * an object the other person can pick up, test, and be wrong about. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "framing-claim-with-a-truth-value",
  track: "framing", level: "everyday",
  title: "If your objection cannot be false, it is not an objection",
  source: "Standard practice in design review and technical writing, where a review comment is expected to name a defect rather than register a reaction",
  gateIntro: "You have written a comment on a proposal that reads: I am not sure this is the right approach, it feels like it might cause problems down the line. You are about to post it. Reading it back, you notice that the author can agree with every word of it and change nothing, and that if the project succeeds nobody will ever be able to point at your comment and say it was wrong.",
  gatePrompt: "Rewrite that comment as something that could turn out to be false. Write the replacement.",
  evidence: "No trial. This is a convention of technical review rather than a finding, and it is enforced by culture rather than by evidence: a comment that names a defect creates an obligation to respond, and a comment that registers discomfort does not. Nobody has measured whether teams that enforce it make better decisions, and the convention would be worth keeping even if they did not, because the alternative is unfalsifiable review.",
  replication: "craft",
  idea: "State your objection so that some future observation could show it was mistaken, because an objection nobody can be wrong about is one nobody has to answer.",
  why: "The unfalsifiable comment feels safe and is worthless in both directions. It cannot be rebutted, which sounds like an advantage until you notice that it also cannot be accepted. There is no action that discharges it. The author reads it, agrees that things can indeed cause problems, and ships. Meanwhile you retain the private belief that you raised it, and you did, in a form that could never have changed anything.\n\nA claim with a truth value does the opposite. It creates a specific obligation. If you say the migration has no rollback path, then either it has one and you are wrong in a way that takes one sentence to establish, or it does not and something has to happen. Both outcomes are progress. The discomfort people have with this is that it exposes you to being demonstrably mistaken in public, and that discomfort is exactly the price of the objection being worth something. An objection that costs you nothing to be wrong about is an objection that costs the reader nothing to ignore.",
  failureMode: "You post the vague version, it gets a thumbs up reaction, and the proposal proceeds. Three months later the thing you had a bad feeling about goes wrong. You go back to the thread, find your comment, and discover you cannot honestly claim to have flagged it, because what you flagged was a feeling that things might go wrong down the line, and that is true of everything.",
  worked: "The rewrite has to name the mechanism, the trigger, and the consequence, in that order:\n\n\"The migration writes to both tables and the cutover reads from the new one, but there is no path back once the old table stops receiving writes. If we find a data problem after the cutover we cannot revert, we can only fix forward under load. I would want a documented reverse path before this ships.\"\n\nEvery clause in that can be false. There might be a reverse path you missed, in which case one reply settles it. That exposure is what makes it an objection rather than an atmosphere.",
  experiment: "Take your last ten review comments and mark each one with what observation would show it to be mistaken. Comments where you cannot fill that in are not review comments, they are reactions. Rewrite the three most important of those into claims and notice how much longer they are, because the vagueness was doing work.",
  reflection: "Which objection have you raised recently that the other person could have agreed with entirely while changing nothing?",
  recall: {
    q: "Why is an unfalsifiable objection worthless in both directions, and what three parts does the falsifiable version usually need?",
    a: "It cannot be rebutted, but it also cannot be accepted, because no specific action discharges it, so the author agrees and ships while you believe you raised it. The falsifiable version names the mechanism, the trigger that would expose it, and the consequence, which creates a specific obligation and exposes you to being shown wrong in one reply."
  },
  deepDive: "Here is an objection I have been circling. Push me until it is stated as something that could turn out to be false."
},
{
  id: "framing-observation-before-interpretation",
  track: "framing", level: "everyday",
  title: "Say what you saw before you say what it means, because the meaning is where you disagree",
  source: "Chris Argyris and Peter Senge, on the ladder of inference (The Fifth Discipline, 1990)",
  gateIntro: "You are about to tell a peer that their team is blocking yours. What you have actually got is this: three pull requests waiting on their review for more than four working days each, and a comment in standup last week about being underwater. The sentence you have drafted begins with the word blocking, and you have noticed they are likely to open by disputing it.",
  gatePrompt: "Write the opening two sentences, with everything you observed before anything you concluded.",
  evidence: "No trial. The ladder of inference is a teaching device, not a finding: it describes a sequence from observable data through selection, interpretation and belief to action, and prescribes walking back down it when two people disagree. It has been taught in organisational development for over thirty years on the strength of case observation. Related packaged methods that make similar separations, including nonviolent communication, are marketed with far more confidence than their published evidence supports.",
  replication: "craft",
  idea: "Put the raw observations in the room before the conclusion you drew from them, because two people almost always share the observations and diverge at the interpretation, and only one of those is worth arguing about.",
  why: "When you open with the conclusion, the other person has to dispute the conclusion, and disputing it requires disputing something about themselves. Blocking is a characterisation of their conduct. Four days on three pull requests is a fact about a queue. They will fight the first and concede the second, and the second is what you actually needed established.\n\nThe deeper reason this works is that it locates the disagreement. Once the observations are agreed, the argument narrows to what they mean, and that argument is frequently short, because the other person has information you do not. They may say those three sat because the author asked us to hold them, which resolves it entirely, and you would never have got that answer from an exchange about whether they are blocking you. Walking down the ladder is not a politeness technique. It is the fastest available route to finding out you were wrong, which is the outcome you should want most often.",
  failureMode: "You open with blocking. They dispute it, accurately, by naming two things they unblocked for you last month. You are now in an argument about the overall state of the relationship, which has no resolution, instead of an argument about three pull requests, which has one.",
  worked: "Observations first, in specifics, and then the interpretation offered as yours rather than as fact:\n\n\"Three of our pull requests have been waiting on your team's review for more than four days each, and I saw the note in standup about being underwater. What I have concluded from that is that review is where our throughput is going, and I want to check that conclusion with you before I act on it.\"\n\nThe last clause is the whole technique. You have stated a conclusion and simultaneously marked it as provisional, which gives them somewhere to stand other than defence, and gives you a route to change your mind without losing anything.",
  experiment: "Take a conclusion you currently hold about another team and write down only the observations under it, with dates and counts. Most people find the list is shorter than expected and that one or two items on it are themselves interpretations. Then take the list to the other team and ask what you are missing before you offer the conclusion at all.",
  reflection: "What conclusion about another team are you carrying, and how many dated observations are actually under it?",
  recall: {
    q: "Why does opening with the observation rather than the conclusion shorten the argument?",
    a: "Because the conclusion is usually a characterisation of the other person's conduct, which they must dispute, while the observations are facts about a queue, which they will concede. Once the observations are agreed the argument narrows to interpretation, and that is where the other person's information most often resolves it, frequently by showing you were wrong."
  },
  deepDive: "I have a conclusion about another team's behaviour. Strip it back to the observations underneath and tell me which of them are actually interpretations."
},
{
  id: "framing-name-your-disconfirmer",
  track: "framing", level: "everyday",
  title: "Naming what would change your mind is the cheapest credibility available",
  source: "Design review practice, and the general convention in forecasting and analysis of stating disconfirming conditions in advance",
  gateIntro: "You are opposing a build over a buy. You have a real argument about long-run cost, and you are aware that you also just prefer building things, and that the person across the table knows you prefer building things. They have heard you argue for building twice before. Whatever you say next will be weighed against that history before it is weighed on its merits.",
  gatePrompt: "Write the sentence that makes your position falsifiable in advance, before you argue for it.",
  evidence: "No trial. This is convention in forecasting practice and in serious analytical writing, where stating in advance what would count against your position is treated as a marker of good faith. There is no experiment showing that people who do it are believed more, and the reasoning is structural rather than empirical: a position with a stated disconfirmer can be settled by evidence, and one without can only be settled by who outlasts whom.",
  replication: "craft",
  cheat: "\"Here is what would change my mind\" costs one sentence and converts a preference fight into a question with an answer.",
  idea: "State the specific evidence that would move you off your position, before you argue the position, because it separates you from the version of you that always argues this way.",
  why: "The person you are talking to has a prior about you, and it is frequently correct. If you have argued for building three times, the fourth argument gets discounted, and the discount is applied before they hear a word of your reasoning. Nothing in the reasoning can fix that, because the discount is not about the reasoning.\n\nA named disconfirmer is the one move that operates on the prior rather than on the argument. If you say I will drop this if their SLA covers our peak and their pricing holds above ten thousand seats, you have made your position conditional on facts that someone can go and check. That does three things at once. It distinguishes you from a person who would argue this regardless, it tells the room exactly what research would end the discussion, and it commits you publicly, which is the part that costs something and is therefore the part that is believed. The cost is real: sometimes they check, the condition fails, and you have to drop it in front of everyone. That is the price and it is what makes the move work.",
  failureMode: "You argue the merits without a disconfirmer, well and at length. The room reads it as your standing preference expressed at greater volume, discounts accordingly, and buys. Nobody ever tells you the discount was applied, so you conclude your argument was not strong enough and prepare a longer one for next time.",
  worked: "Front-load the condition, before the argument rather than after it, and make it checkable by someone who is not you:\n\n\"Before I argue this, here is what would settle it against me. If their contract covers our peak throughput and the price per seat holds above ten thousand, I will drop the build case and help make the buy work. I am saying that first because I have argued for building twice this year and I would discount me too.\"\n\nNaming your own track record is not self-deprecation. It removes the other person's strongest unspoken objection by saying it for them, which means they no longer have to decide whether raising it would be rude.",
  experiment: "Before your next contested recommendation, write the disconfirmer down and give it to someone else to check. If you cannot construct one, that is the finding: your position may be a preference, and it is better to discover that at your desk than three exchanges into the meeting.",
  reflection: "On your most-argued position, what specific fact would make you drop it, and have you ever said that out loud?",
  recall: {
    q: "What does naming a disconfirmer do that a stronger argument cannot, and what does it cost?",
    a: "It operates on the other person's prior about you rather than on the argument, distinguishing you from the version of you that always takes this position, and it names the research that would end the discussion. The cost is genuine public commitment: sometimes the condition is checked, it fails, and you have to drop the position in front of everyone, which is why the move is believed."
  },
  deepDive: "Here is a position I keep arguing for. Help me work out whether I have a real disconfirmer or just a preference."
},
{
  id: "framing-one-objection-at-a-time",
  track: "framing", level: "costly",
  title: "Adding your weak objections to your strong one makes the strong one weaker",
  source: "Nisbett, Zukier and Lemley, The Dilution Effect (Cognitive Psychology, 1981)",
  gateIntro: "You have five problems with the proposal. One of them is serious and the other four range from moderate to nitpick. Your draft comment lists all five, numbered, in the order they appear in the document, and the serious one is number three. You are conscious that listing all five demonstrates you read it properly, and that leaving four out feels like letting them go.",
  gatePrompt: "You are going to raise one. Write it, and write the sentence that disposes of the other four.",
  evidence: "Participants given diagnostic information about a person made confident predictions; when the same diagnostic information was presented alongside non-diagnostic but plausible detail, predictions regressed toward the mean. Adding irrelevant information reduced the impact of relevant information rather than leaving it intact. The effect has been reproduced across judgement domains including legal and clinical settings, though it is a laboratory finding about person perception and its application to review comments is an extrapolation.",
  replication: "replicated",
  idea: "Raise your strongest objection on its own, because a set of arguments is weighed closer to its average than to its maximum and every weak item you add drags the strong one down.",
  why: "The intuition everyone has is that arguments add. Five reasons must be more persuasive than one, so listing all five is thoroughness. The dilution work says the opposite: introducing weak or non-diagnostic material alongside strong material moves the judgement toward the middle rather than reinforcing it. Applied to a review, the reader does not experience one serious defect plus four nitpicks. They experience a list of five comments of mixed seriousness and form a general impression of a picky review, and the serious item is inside that impression rather than outside it.\n\nThere is a second, purely practical mechanism on top of the psychological one. A list gets answered as a list. The author works down it, answers the four easy items convincingly because they are easy, and by the time they reach yours the reply has established a rhythm of these are all addressable. Your one real problem gets the same treatment as the naming convention, and the thread closes with all five marked resolved.",
  failureMode: "The author replies to all five in order. Four get good answers. Yours gets we will keep an eye on that. The thread now reads as a review that was conducted and addressed, and reopening the third item means reopening a resolved thread, which is a much higher bar than raising it would have been.",
  worked: "Separate the one from the rest explicitly, and give the rest away in a form that cannot be bundled back in:\n\n\"One blocking comment, and then some minor things I will leave as suggestions.\n\nBlocking: the events table has no tenant id, so any per-tenant deletion becomes a full scan and we cannot honour a deletion request inside the window we have promised. I do not think this ships without it.\n\nEverything else from me is naming and ordering, non-blocking, take or leave.\"\n\nThe word blocking is doing structural work. It creates two categories with different obligations, which is what stops the serious item being answered in the same breath as the naming.",
  experiment: "For a month, cap yourself at one blocking comment per review and put everything else under a non-blocking heading. Track how often the blocking comment is actually addressed compared with your previous reviews. The usual finding is that fewer comments produce more changes, which is uncomfortable and repeatable.",
  reflection: "In your last review, was your most serious comment buried in a list, and was it answered at the same depth as the minor ones?",
  recall: {
    q: "What is the dilution effect, and what practical mechanism compounds it in a written review?",
    a: "Adding non-diagnostic information alongside diagnostic information moves judgement toward the mean rather than reinforcing it, so weak arguments drag down a strong one instead of adding to it. In review, a list also gets answered as a list: the easy items get good answers, which establishes a rhythm of addressability, and the serious item receives the same treatment and is marked resolved."
  },
  deepDive: "Here are all my comments on a proposal. Help me pick the one that is genuinely blocking and rewrite the rest as clearly non-blocking."
},
{
  id: "framing-consider-the-opposite",
  track: "framing", level: "costly",
  title: "Argue your own position down before the meeting, because nobody else will do it as well",
  source: "Lord, Lepper and Preston, Considering the Opposite (Journal of Personality and Social Psychology, 1984)",
  gateIntro: "You are convinced the vendor decision is wrong and you have a strong case. You have spent two evenings assembling it. Every piece of evidence you gathered supports your position, which you have noticed and attributed to the position being correct. The meeting is tomorrow morning and you have forty minutes free tonight.",
  gatePrompt: "Assume you will be asked the strongest question against you. Write the sentence you would use to answer it honestly.",
  evidence: "Participants who were instructed to ask themselves whether they would have made the same judgement had the evidence pointed the other way showed reduced biased assimilation of mixed evidence, while merely being told to be unbiased did not help. The consider-the-opposite manipulation has since been shown to reduce anchoring, overconfidence and hindsight bias across a range of tasks, making it one of the better-supported debiasing techniques. Effects are typically modest and measured on laboratory judgement tasks rather than on real decisions with stakes.",
  replication: "replicated",
  idea: "Spend part of your preparation constructing the best case against your own position, because generic instructions to be objective do nothing and this specific exercise measurably does something.",
  why: "The 1984 result is worth knowing precisely because of its control condition. Telling people to be unbiased and objective had essentially no effect on how they assimilated mixed evidence. What worked was the concrete instruction to ask whether they would have reached the same conclusion had the evidence come out the other way. That distinction matters because almost all self-directed rigour takes the form of the useless version. Resolving to be fair-minded before a meeting is the intervention that does nothing.\n\nThe practical payoff in a disagreement is not only that you may be wrong. It is that the strongest counterargument exists whether or not you have found it, and the only question is whether you meet it at your desk with forty minutes or in the room with fifteen seconds. Having met it already, you can answer it without the visible recalculation that reads as being caught out. The people who look calm under challenge are usually not calmer. They have simply already had the argument.",
  failureMode: "You go in with the assembled case, and the first question is the one obvious objection you never made yourself. You improvise. The improvisation is not good, because it is being generated live against a case you spent two evenings not thinking about, and the room updates on your visible scrambling rather than on the merits of your position.",
  worked: "Having done the work, you can concede the strong counterargument cleanly and keep your position, which is a move that is unavailable to anyone who has not:\n\n\"The best argument against me is that building costs us two engineers for six months and we do not have them. That is real and I am not going to pretend it is not. My position is that we are trading six months of two engineers against a per-seat cost that becomes the largest line in the infrastructure budget at our current growth rate, and I would rather have that argument explicitly than have it decided by which cost is visible this quarter.\"\n\nConceding the strongest point against you is not a loss. It is the fastest way to establish that everything else you said was not advocacy.",
  experiment: "Before your next contested meeting, spend twenty minutes writing the opposing case as though you had been assigned it, and do it in prose rather than bullets so you cannot skim. Then mark the strongest item. In most preparation the strongest opposing argument turns out to be one you already half-knew and had never written down.",
  reflection: "What is the strongest argument against your current position, and have you ever written it out in full?",
  recall: {
    q: "What did the consider-the-opposite study show about generic instructions to be objective, and why does the exercise help in a live disagreement?",
    a: "Telling people to be unbiased had essentially no effect on biased assimilation, while the specific instruction to ask whether they would have concluded the same had the evidence pointed the other way did reduce it. In a live disagreement it helps because the strongest counterargument exists regardless, and meeting it at your desk rather than in the room lets you concede it cleanly instead of visibly improvising."
  },
  deepDive: "Take the opposite side of my position and argue it as strongly as you can. Do not hedge and do not concede anything to me."
},
{
  id: "framing-premortem",
  track: "framing", level: "costly",
  title: "Ask the room to imagine it already failed, which is a question people can answer",
  source: "Gary Klein, Performing a Project Premortem (Harvard Business Review, 2007), building on Mitchell, Russo and Pennington's work on prospective hindsight",
  gateIntro: "The launch plan has been presented and the room is enthusiastic. You have reservations that are diffuse rather than specific, and asking whether anyone has concerns will produce nothing, because it already has twice in this meeting. You have five minutes of the agenda and the authority to use them however you like.",
  gatePrompt: "Write the exact words you would use to run this, including the framing sentence that sets it up.",
  evidence: "Mitchell, Russo and Pennington found that describing an outcome as having already occurred and asking why increased the number and specificity of reasons generated, compared with asking about a possible future outcome. Klein packaged this as a project ritual. The underlying prospective hindsight finding is a small laboratory study on explanation generation; the claim that running a premortem improves project outcomes is Klein's practitioner inference and has not been tested. Treat the technique as well-motivated craft with one experiment somewhere behind it.",
  replication: "single",
  cheat: "\"It is six months from now and this failed badly. Everyone write down why.\" Silence in the room is not an absence of concerns.",
  idea: "Replace the question does anyone have concerns with the assertion that it is a year from now and this failed, then ask why, because the second question is one people can actually answer and the first one is not.",
  why: "Does anyone have concerns fails for a reason that has nothing to do with courage. It asks people to volunteer a negative prediction, attach their name to it, and defend it against a room that is currently enthusiastic. The premortem changes the task completely. The failure is now a given, supplied by you, so nobody is predicting it and nobody owns it. Generating an explanation for a stated fact is a normal, low-status-cost cognitive task, and people are good at it.\n\nThe prospective hindsight result is the mechanism: asking why something happened produces more and more specific reasons than asking what might happen. Everything else about the ritual is craft. Two details matter in practice. People write before they speak, so the first answer does not anchor the rest. And the failure has to be stated as severe and specific, because a mild failure produces mild reasons. It failed is weaker than we rolled it back in week two and lost the enterprise renewal.",
  failureMode: "You run it as a discussion rather than a write-first exercise. The most senior person answers first with a generic risk, the room converges on that risk, and you have produced one shallow answer instead of nine independent ones. Premortems degrade into consensus faster than almost any other technique because the framing sounds safe.",
  worked: "Set the failure hard and specific, force writing before talking, and give it a shape people cannot escape:\n\n\"Five minutes on this. It is April. The launch went badly, we rolled it back in week two, and we lost the Henderson renewal over it. That is the given. Do not discuss it yet. Everyone write down, in silence, the two most likely reasons that happened. Two minutes, then we go round and I want everyone's, including the ones that duplicate.\"\n\nIncluding the duplicates matters. Three people independently writing the same reason is the signal, and you lose it if the second and third defer to the first.",
  experiment: "Run one on a plan that is already approved and that you are not personally worried about. Doing it on a project you oppose contaminates it, because the room will read the ritual as your objection in costume. Run it where you have no position and you will find out whether the technique works in your organisation before you need it to.",
  reflection: "What plan of yours would benefit most from being declared already failed, and what would you not want people to write down?",
  recall: {
    q: "Why does a premortem get answers when asking for concerns does not, and what two details make or break the ritual?",
    a: "Asking for concerns requires volunteering a negative prediction and defending it against an enthusiastic room, while a premortem supplies the failure as a given so nobody owns it and explaining a stated fact is a low-cost task. The two details are writing before speaking, so the first answer does not anchor the rest, and stating the failure as specific and severe, because a mild failure produces mild reasons."
  },
  deepDive: "Run a premortem on this plan with me. State the failure as severe and specific, then generate the reasons without letting me steer them."
},
{
  id: "framing-what-would-have-to-be-true",
  track: "framing", level: "costly",
  title: "Ask what would have to be true for their plan to work, not whether it will",
  source: "Roger Martin, on reverse-engineering the conditions behind a strategic option (The Opposable Mind, 2007, and Playing to Win, 2013)",
  gateIntro: "Your head of sales wants to move the product upmarket. You think it is wrong and you have thought so for a while. Every previous version of this conversation has ended with the two of you restating your positions with more detail, and both of you leaving convinced. There is a strategy offsite in a fortnight and the item is on the agenda.",
  gatePrompt: "Write the question you would open with, phrased so that agreeing to answer it costs them nothing.",
  evidence: "No trial. Martin's method comes from strategy consulting practice and is taught in business schools on the strength of case narratives. There is no evidence that groups using it reach better strategic decisions, and the cases are selected by the author. What it has in its favour is structural: it converts an unresolvable clash of predictions into a list of conditions, and a list of conditions can be assigned to somebody to check.",
  replication: "craft",
  cheat: "\"What would have to be true for this to work?\" turns two competing forecasts into a checkable list, and costs nothing to agree to.",
  idea: "Stop arguing about whether their plan will work and get the room to list what would have to be true for it to work, because the list is checkable and the forecast is not.",
  why: "Two competing predictions about the future cannot be resolved in a meeting. Neither party has the information that would settle it, so the exchange becomes a contest of conviction and detail, and it is won by whoever is more senior or more stubborn. Both of you can restate your positions indefinitely and neither restatement contains new information.\n\nReframing to conditions changes the object. What would have to be true for upmarket to work is a question with a finite answer: enterprise buyers would have to accept our current security posture, the sales cycle would have to fit inside the runway, we would have to be able to hire two enterprise sellers in this market. Now there are three claims, each of which somebody can go and find out about. Crucially, this is a question your counterpart can agree to answer without conceding anything, which is why it works where direct opposition does not. You are not asking them to admit doubt. You are asking them to specify their own success conditions, which a confident person is happy to do, and which frequently turns out to be the whole argument.",
  failureMode: "You use it as rhetoric rather than as inquiry, with the conditions chosen to be obviously unmeetable. Your counterpart hears the trap immediately, because it is not subtle, and the technique is burned for you personally for a year. This move only works if you would genuinely accept the plan when the conditions check out.",
  worked: "Frame it as joint work with an explicit commitment attached to the outcome, which is the part that makes it inquiry rather than ambush:\n\n\"I want to try this differently, because we have both made our case three times and neither of us has moved. Rather than argue about whether upmarket works, can we list what would have to be true for it to work, and then go and find out about each one? I will take two of them. And I will say now that if the list checks out I am in, properly, not grudgingly.\"\n\nOffering to research the conditions yourself is what proves this is not a delaying tactic, which is what it will otherwise be assumed to be.",
  experiment: "Take a disagreement you have restated more than twice and write the conditions list on your own first, honestly, including the conditions that would favour their side. If your list has no condition that could plausibly check out in their favour, you have written an argument rather than a list, and taking it into the room will be worse than saying nothing.",
  reflection: "Which of your recurring arguments has never been converted into a list of checkable conditions, and what is the first one on the list?",
  recall: {
    q: "Why does asking what would have to be true break a deadlock that restating your position cannot, and what is the condition for it working?",
    a: "Because two competing forecasts contain no new information and are resolved by seniority or stubbornness, while a list of conditions can be assigned and checked. It works only if it is genuine inquiry: the conditions must include ones that could plausibly check out in the other side's favour, and you must be prepared to accept the plan if they do, otherwise it reads as an ambush and is burned."
  },
  deepDive: "I disagree with a plan. Help me build the list of what would have to be true for it to work, including the conditions that would favour it."
},
{
  id: "framing-name-the-trade-you-accept",
  track: "framing", level: "everyday",
  title: "Say what you are willing to give up, or your objection is heard as asking for everything",
  source: "Fisher and Ury, Getting to Yes (1981), on the distinction between positions and interests",
  gateIntro: "You are objecting to a deadline. Your team has been given six weeks for something you believe takes ten. You have made the case on estimates twice and been told to find a way. The programme manager's position, stated to you directly, is that every team says this and the date is external. You have a meeting with them this afternoon.",
  gatePrompt: "Write the sentence that offers something up, and be specific about what you are giving away.",
  evidence: "No trial in the experimental sense. Getting to Yes is the most influential negotiation text of the last half century and rests on the authors' practice at the Harvard Negotiation Project rather than on controlled studies. The positions-versus-interests distinction has been enormously productive as a teaching frame; claims that principled negotiation outperforms positional bargaining in general are not supported by anything resembling a trial.",
  replication: "craft",
  cheat: "Bring the trade with the objection. \"I can hit six weeks without the audit log or ten weeks with it\" beats arguing about estimates.",
  idea: "Attach a specific concession to the objection, because an objection with nothing given up is heard as a request for more time, more people or less work, and is answered as one.",
  why: "The person you are objecting to has heard your objection before, from every team, in the same form. Their model of it is that teams ask for more room, so they discount by a standard factor and hold the date. Nothing you say about your estimate escapes that model, because your estimate is exactly the thing they have learned to discount.\n\nA named trade escapes it, because it is not the same kind of object. Six weeks without the audit log or ten weeks with it is not a request. It is a menu, and it moves the decision to where it belongs, which is with the person who owns the date and the scope. It also does something to your credibility that no estimate can: it demonstrates that you have accepted the constraint rather than fighting it, which is the thing they are actually checking for. The cost is that you have to have genuinely decided what to give up, and that decision is harder than the argument you were planning to have.",
  failureMode: "You argue the estimate, and the estimate is discounted, and you are given eight weeks as a compromise between two numbers that were never negotiable quantities. Now you have neither the time nor the reduced scope, and the compromise has the appearance of having heard you.",
  worked: "Lead with the constraint accepted, then the menu, and put the decision explicitly in their hands:\n\n\"The date is external and I am not going to argue about that any more. Here is what I can do. Six weeks gets you the migration and the new read path, without the audit log, which means we cannot answer a compliance request on this data until the following quarter. Ten weeks gets you all three. I am not asking for ten. I am asking you to pick, because the audit log is a decision above my level and I do not want to make it by quietly running out of time.\"\n\nThe last clause is the one that matters. You have made the trade explicit rather than letting it happen by omission, which is what would have happened otherwise.",
  experiment: "Before your next scope or deadline objection, write the two options out as a menu with the consequence of each spelled out. If you cannot construct a version that fits the constraint, that is a genuine finding and should be said in exactly those words, but check first, because most people have never tried.",
  reflection: "In your current deadline disagreement, what would you actually be willing to give up, and have you said it?",
  recall: {
    q: "Why is an objection with no concession attached ineffective, and what does the named trade demonstrate?",
    a: "Because it matches the model the other side already has of every team asking for more room, so it is discounted by a standard factor before the merits are heard. A named trade is a different kind of object: it moves the decision to whoever owns scope and date, and it demonstrates that you have accepted the constraint rather than fighting it, which is what they are actually checking."
  },
  deepDive: "I am objecting to a deadline. Help me build the menu of what I can deliver in the time given, with the consequence of each cut spelled out."
},
{
  id: "framing-own-the-objection",
  track: "framing", level: "everyday",
  title: "Do not say some people are concerned when the person concerned is you",
  source: "Convention in professional and political communication, where an anonymous constituency is a recognised tell",
  gateIntro: "You are worried about the on-call rotation change. In your draft message you have written that a few people have raised concerns about sustainability. In fact one person mentioned it to you in a corridor and did not seem especially exercised, and the person who is genuinely worried is you. The message is ready to send.",
  gatePrompt: "Rewrite it in the first person singular. Write the version you would actually send.",
  evidence: "No trial. This is a convention rather than a finding, and it is enforced socially: the anonymous constituency is a well-recognised rhetorical device and readers discount it. There is no study showing that first-person objections are better received, and there is a substantial folk practice in the other direction, particularly among people who have concluded that borrowed authority is safer than their own.",
  replication: "craft",
  cheat: "First person singular. \"I think this is wrong\" is answerable. \"Some people are concerned\" is not, and everyone knows who the people are.",
  idea: "Put the objection in the first person singular with your name on it, because a concern attributed to an unnamed group cannot be answered and is understood by everyone as yours anyway.",
  why: "The anonymous constituency is meant to add weight and does the opposite. Some people are concerned is unanswerable in a specific way: the recipient cannot ask the concerned people what they meant, cannot check how many there are, and cannot resolve it by satisfying anyone in particular. So the rational response is to acknowledge it and proceed, which is exactly what happens.\n\nIt also fails at the thing it is for. It is used to distribute risk, and it does not, because everybody can see who sent the message. What it actually costs you is the credibility of the objection, since a person who will not put their name on a concern is signalling either that they do not fully hold it or that they expect to be punished for it, and both readings weaken the content. The exception is real and narrow: when you are carrying a concern on behalf of people who would genuinely be at risk if named, you are not hiding, you are representing, and that should be said explicitly as what it is.",
  failureMode: "You send the hedged version. It is acknowledged warmly and nothing changes. Later you raise it again, in the first person this time, and are asked why this is coming up now, because your earlier message is on record as a general note about sentiment rather than as an objection from you.",
  worked: "Own it, and be specific about how much of it is yours:\n\n\"This is me, not a general vibe. I think the new rotation is not sustainable. Under the current shape, the primary carries pages across two time zones with no secondary, and I would not want to do it for more than a month. One other person has mentioned it to me and I do not want to speak for them, so treat this as one person's view with some corroboration.\"\n\nSaying I do not want to speak for them is what lets you mention the corroboration without inflating it, which is the whole reason people reach for the anonymous version in the first place.",
  experiment: "Search your sent messages for phrases like some people, a few of us, there is a feeling that, and it has been suggested. For each hit, check who the people actually were. Then look at what the response was and whether anything changed.",
  reflection: "Where have you recently used a borrowed constituency, and what would the first-person version have cost you?",
  recall: {
    q: "Why does attributing a concern to unnamed others weaken it, and what is the legitimate exception?",
    a: "It cannot be answered, since the recipient cannot ask the group what they meant or satisfy anyone in particular, so acknowledging and proceeding is the rational response. It also fails to distribute risk, because everyone knows who sent it, while signalling that you do not fully hold the concern. The exception is genuinely representing people who would be at risk if named, which should be stated as what it is."
  },
  deepDive: "Here is a message where I hid behind other people's concerns. Rewrite it in the first person and tell me what I lose and gain."
},
{
  id: "framing-which-level-is-the-argument",
  track: "framing", level: "costly",
  title: "Establish whether you disagree about the goal, the constraint or the method before you argue any of them",
  source: "Standard practice in requirements and architecture review, where confusing levels of a decision is a recognised source of unresolvable argument",
  gateIntro: "You have spent twenty minutes arguing about whether to use a queue or a direct call. It has been unusually heated for a question of that size. You have just noticed that your counterpart believes the requirement is to never lose a message, and you believe the requirement is to keep the ninety ninth percentile latency under two hundred milliseconds. Neither of you has said either of those things out loud.",
  gatePrompt: "Write the sentence that stops the current argument and moves it to the right level.",
  evidence: "No trial. This is engineering review convention, learned by everyone who has sat through a long argument about an implementation that turned out to be an argument about a requirement. It generalises the older distinction between ends and means. No study has measured how often technical disagreements are level confusions, and the honest answer is that practitioners believe it is common on the basis of their own recurring experience.",
  replication: "craft",
  cheat: "\"I think we are arguing about the method and disagreeing about the requirement.\" Say it the moment a small question gets heated.",
  idea: "When a small technical argument runs hot, suspect that the two of you are working from different unstated requirements, and move the conversation up a level before continuing.",
  why: "Heat is diagnostic. An argument about a queue is a small argument and should feel small. When it does not, the usual explanation is that each party is defending something larger that has not been named, and both are defending it through a proxy. You are not actually arguing about queues, you are arguing about whether durability or latency is the constraint, and that argument cannot be won at the level of the queue because the queue is a consequence rather than a premise.\n\nThe reason this stays hidden is that both requirements are obviously reasonable, so neither person thinks to state theirs. Nobody announces a premise they assume is shared. The tell is the mismatch between the size of the topic and the temperature of the exchange, and it is worth learning to notice because the resolution is usually fast once the levels are separated. Frequently the answer is that both requirements are real and somebody senior needs to say which one wins, which is a two-minute conversation that neither of you can have while still arguing about queues.",
  failureMode: "You win the queue argument on technical merit. The queue is built. It satisfies the durability requirement you were never told about and violates the latency requirement you were defending, and the same argument reopens in three months about something else, because the actual disagreement was never located.",
  worked: "Name the level explicitly and put both premises in the room without adjudicating between them:\n\n\"Can we stop on the queue for a second. I think we are arguing about the mechanism and actually disagreeing about the requirement. I have been optimising for latency under two hundred milliseconds at the ninety ninth percentile. I think you have been optimising for not losing messages. Both are legitimate and I do not think either of us can pick, so I would rather take that question to Dana than keep doing this.\"\n\nStating their premise for them, accurately and without sarcasm, is what makes this land. If you get it wrong they will correct you, which is also progress.",
  experiment: "Next time an argument runs hotter than its topic warrants, stop and write down the requirement you are defending in one sentence. Then ask the other person to do the same before either of you says another word about the mechanism. Compare the two sentences.",
  reflection: "Which of your recurring technical arguments is actually a requirements disagreement that has never been named?",
  recall: {
    q: "What does disproportionate heat in a small technical argument usually indicate, and why does the argument not resolve at its own level?",
    a: "That both parties are defending different unstated requirements through a proxy. It cannot resolve at the level of the mechanism because the mechanism is a consequence of the requirement rather than a premise, and neither person states their requirement because they assume it is shared. The resolution is to name both premises and often to escalate the choice between them."
  },
  deepDive: "Here is a technical argument I keep having. Help me work out whether we are disagreeing about the goal, the constraint or the method."
},
{
  id: "framing-price-the-asymmetry",
  track: "framing", level: "costly",
  title: "Compare what it costs if you are wrong with what it costs if they are",
  source: "Standard practice in risk and safety analysis, where the cost of the two error types is compared rather than the probability of each",
  gateIntro: "You want a feature flag on the release. The team lead thinks it is unnecessary ceremony for a change this small, and they are probably right that the change is small. You put your chance of being right at maybe one in five. The flag costs about half a day. You are about to concede because four out of five times they are correct.",
  gatePrompt: "Write the sentence that argues for the flag without needing to be more likely right than wrong.",
  evidence: "No trial, and none is needed for the arithmetic. Comparing the cost of the two errors rather than their probability is the ordinary structure of expected-value reasoning and of every risk framework built on it. What is unevidenced is the behavioural claim underneath this entry, that people default to arguing probability rather than consequence, which rests on practitioner observation rather than measurement.",
  replication: "craft",
  cheat: "Argue the consequence, not the odds. \"If I am wrong we lose half a day, if you are wrong we lose the weekend\" needs no certainty.",
  idea: "Argue from the asymmetry of consequences rather than the balance of probabilities, because you do not need to be more likely right than your counterpart when the two errors cost wildly different amounts.",
  why: "Most people concede when they believe they are probably wrong, and that instinct throws away the majority of their justified objections. Being probably wrong is not the relevant question when the two errors are not the same size. If your objection costs half a day when unnecessary and saves a weekend outage when necessary, a one in five chance of being right is more than enough, and you can say so out loud in a way that does not require anybody to concede that you are likely correct.\n\nThis is also, socially, the least confrontational strong argument available. You are conceding the probability point, which is the point your counterpart is attached to, and moving to a different axis entirely. There is nothing for them to defend, because you have already agreed with them about the likely case. What is left is arithmetic that either survives inspection or does not. The failure to watch for is inflating the downside, which is easy and destroys the move: if you claim a weekend outage for something that would realistically be a twenty minute rollback, you have lost the argument and the next one.",
  failureMode: "You concede because you are probably wrong. The change ships without a flag. It is fine, as expected, and so are the next six. The seventh is not, and the rollback that would have taken thirty seconds takes four hours, and the retrospective records that nobody thought a change that size warranted a flag.",
  worked: "Concede the likelihood first, explicitly, then move to consequence and keep the numbers honest:\n\n\"You are probably right and I would put myself at about one in five here. I still want the flag, and the reason is the shape of the two mistakes rather than which of us is more likely correct. If I am wrong we have spent half a day on ceremony. If you are wrong, this touches the write path and we are rolling back by deploy on a Friday evening. I will take half a day against that trade even at one in five.\"\n\nPutting your own confidence at one in five, out loud, is what makes the rest credible. It shows you are not smuggling in a probability argument under a consequence argument.",
  experiment: "For a week, whenever you are about to drop an objection because you think you are probably wrong, write the two costs down before conceding: what it costs if you are wrong, and what it costs if they are. Concede only if the costs are comparable. Most people find they have been conceding on probability alone and that a third of those objections survive the arithmetic.",
  reflection: "Which objection did you drop recently because you thought you were probably wrong, and what were the two costs?",
  recall: {
    q: "Why is being probably wrong an insufficient reason to drop an objection, and what makes this argument socially cheap?",
    a: "Because the relevant comparison is the cost of the two errors rather than their probability, and a low chance of being right can still justify a cheap precaution against an expensive failure. It is socially cheap because you concede the probability point your counterpart is attached to and move to a different axis, leaving nothing for them to defend except arithmetic."
  },
  deepDive: "Here is an objection I am about to drop because I am probably wrong. Price both errors and tell me whether the arithmetic supports dropping it."
},
{
  id: "framing-steelman-before-you-swing",
  track: "framing", level: "costly",
  title: "State their position better than they did, then disagree with that",
  source: "Anatol Rapoport's rules for successful criticism, as set out by Daniel Dennett in Intuition Pumps and Other Tools for Thinking (2013)",
  gateIntro: "You are writing a response to an architecture proposal you think is wrong. Your draft opens by listing what the proposal gets wrong, and it is accurate. You have also noticed while writing that you do not fully understand why the author chose the event-sourced approach, and that your draft handles this by not mentioning it. The document has eleven readers.",
  gatePrompt: "Write the opening paragraph of your response, starting with their case rather than yours.",
  evidence: "No trial. Rapoport's rules are a prescription for productive criticism, popularised by Dennett and adopted widely in argumentation teaching. Nothing has tested whether critics who follow them change more minds. The rules do have one property that is not in dispute: following them requires understanding the position well enough to restate it, which is a real constraint on criticism written from a misreading.",
  replication: "craft",
  idea: "Open by restating their position so well that they would endorse the restatement, and only then disagree, because the restatement both earns you the hearing and frequently changes what you were going to say.",
  why: "There are two benefits and the second one is the real one. The first is rhetorical and well understood: a critique that opens with an accurate and generous statement of the target position cannot be dismissed as a misreading, and it disarms the defensive response before it forms. That alone is worth the paragraph.\n\nThe second is that the exercise is a genuine test you can fail. Attempting to state the case for the event-sourced approach forces you to find out whether you understand why it was chosen, and a meaningful fraction of the time you discover you do not, and that the reason is good. This is the uncomfortable part and it is where the value is concentrated. A critique written without this step is a critique of the version of the proposal you constructed, which may not be the one on the table. Rapoport's ordering, which puts the restatement and the acknowledgement of what you learned before any disagreement, is designed to make skipping the test impossible.",
  failureMode: "You write the accurate critique of the parts you understood and stay silent on the part you did not. The author replies explaining the event sourcing, which answers three of your points at once, and your critique now reads as confident about a document you had not fully read. The remaining objections, which were good, are collateral.",
  worked: "The restatement has to be genuinely generous, and the tell that you did it properly is that it contains something they did not say themselves:\n\n\"Let me state the case as I understand it before I disagree with any of it. The argument for event sourcing here is that reconciliation is currently manual and takes two people a week each month, and an append-only log makes that a query rather than an investigation. That is a real cost and I do not think the alternatives address it as directly. I want to raise one thing that I do not think the doc handles, which is the storage growth on the events table over a three year horizon.\"\n\nNote that the disagreement narrowed. It went from this approach is wrong to one unhandled consequence, and that narrowing happened during the restatement, not after it.",
  experiment: "Before your next written critique, write the other side's case in a paragraph and send it to them privately with the question: is this fair? Their correction is more valuable than your critique, and you will learn whether you were about to argue with a position nobody held.",
  reflection: "What proposal are you currently opposing where you could not write the author's own case for it?",
  recall: {
    q: "What are the two benefits of stating the other position first, and which one matters more?",
    a: "It disarms the dismissal that you misread them, and it is a test you can fail. The second matters more: attempting the restatement reveals whether you understand why the choices were made, and a meaningful fraction of the time you find you do not and the reason is good, which narrows or dissolves the critique before you publish it."
  },
  deepDive: "Here is a proposal I want to argue against. First make the strongest case for it that you can, and tell me what I have misunderstood."
},
{
  id: "framing-scope-the-objection",
  track: "framing", level: "everyday",
  title: "Say how much of it you are objecting to, or they will assume all of it",
  source: "Review convention in standards bodies and formal approval processes, where an objection is required to state its scope",
  gateIntro: "A colleague has spent three weeks on a strategy document. It is forty pages. You think thirty eight of them are good and that the section on pricing is badly wrong in a way that matters. You are about to leave a comment on the pricing section. They have already had two rounds of feedback and have mentioned twice that they are exhausted by it.",
  gatePrompt: "Write the comment, and make the scope of your objection the first thing they read.",
  evidence: "No trial. Formal standards processes require an objection to identify what it applies to, because unscoped objections cannot be resolved procedurally. The generalisation to everyday review is craft, and rests on the observation that authors under sustained critique read any objection as directed at the whole, which is a claim about human reading rather than a measured effect.",
  replication: "craft",
  cheat: "Lead with the fraction. \"One section, and the rest is right\" is not politeness, it tells them what to defend and what not to.",
  idea: "State what proportion of the work your objection covers before you state the objection, because an author who has been under critique reads any comment as being about the whole thing.",
  why: "This is not a manners point, although it is frequently mistaken for one. Scope is load-bearing information that changes what the author does next. Told that the pricing section is wrong, without scope, a tired author's most likely response is either to defend the document generally or to conclude the whole thing needs rework. Both are expensive and neither is what you wanted. Told that thirty eight pages are right and one section is wrong, they know exactly where to spend, and the conversation is about pricing within one exchange.\n\nThe accumulation of critique is the mechanism that makes this necessary. Your comment does not arrive alone. It arrives on top of two prior rounds, and the author is integrating all of it into a general sense of how the document is being received. Unscoped, your comment joins that general sense. Scoped, it stays a specific item. This is also why the scope has to be genuine: if you say one section and then leave nine comments elsewhere, you have spent the device and it will not work for you again.",
  failureMode: "You leave the pricing comment without scope, on top of two prior rounds. The author reads it as a third round of general dissatisfaction, rewrites large sections that were fine, and the pricing section survives in a slightly reworded form because it was never identified as the specific problem.",
  worked: "Scope first, in the first clause, before any content:\n\n\"One section only, and I want to be clear the rest of this is right and I would sign it as is. The pricing section does not work for me. It assumes we can hold the current discount structure through the enterprise motion, and the two enterprise deals we have closed both went out at twice the discount in the model. I think that section needs redoing and I do not think anything else does.\"\n\nEnding by restating the scope closes the loop. The author's last impression should be the boundary of the objection rather than its content, because the boundary is what determines what they do tomorrow.",
  experiment: "For your next three reviews of substantial work, open every objection with its scope as a fraction, stated plainly. Then check what the author actually changed. The usual finding is that scoped objections produce narrower and more accurate revisions, and that unscoped ones produce rewrites of things you never mentioned.",
  reflection: "When did you last see an author rewrite something you had no problem with, because your objection had no stated boundary?",
  recall: {
    q: "Why is stating the scope of an objection informational rather than merely polite?",
    a: "Because it determines what the author does next. Without it, a tired author integrates the comment into an accumulated sense of general dissatisfaction and either defends the whole or reworks large sections that were fine. With it, the comment stays a specific item and the conversation reaches the actual problem in one exchange. The scope must be genuine or the device stops working."
  },
  deepDive: "I have one serious problem with a long document that is otherwise good. Help me write the comment so the scope is unmistakable."
},
{
  id: "framing-not-a-principle-a-reason",
  track: "framing", level: "costly",
  title: "Citing a principle instead of a reason invites an argument about the principle",
  source: "General practice in technical argument, where an appeal to a named rule is weaker than the consequence the rule exists to prevent",
  gateIntro: "You are objecting to a service that reads directly from another team's database. Your draft says this violates service boundaries and creates coupling. The person you are objecting to has already said in the thread that they think boundary purism costs more than it saves, and several people reacted positively to that. Your comment is going into that context.",
  gatePrompt: "Write the objection without using any of the words boundary, coupling or principle.",
  evidence: "No trial. This is a rhetorical observation from technical practice rather than a finding: an appeal to a named principle transfers the argument onto the principle, which is contestable and abstract, while an appeal to consequence stays on ground where evidence exists. It is consistent with the general preference for concrete over abstract argument, which is itself supported mostly by teaching experience rather than by experiment.",
  replication: "craft",
  cheat: "Name the consequence, not the principle. \"Their schema change breaks us silently at 3am\" beats \"this violates service boundaries.\"",
  idea: "Argue from the specific consequence rather than from the principle that predicts it, because a principle can be disputed as dogma and a consequence has to be addressed.",
  why: "Principles are compressions of accumulated consequence, and the compression is what makes them contestable. Service boundaries is a summary of many bad experiences, and someone who has not had those experiences, or who has had good experiences with the shortcut, can dismiss the summary without dismissing anything real. Once they have, you are in an argument about architectural philosophy, which has no evidence in it and is won by whoever has more standing.\n\nDecompressing back to the consequence puts you on ground where facts exist. Their schema migration will not know we are reading that table, and the first we will learn about a dropped column is a null pointer at three in the morning is not a philosophy. It is a prediction about a specific mechanism, and it can be checked, mitigated or refuted. It is also much harder to wave away, because waving it away requires saying either that it will not happen or that it does not matter, and both of those are positions with owners.",
  failureMode: "You cite the principle. Your counterpart, who has already framed boundary discipline as purism and has the room's sympathy, wins the exchange on that framing without ever addressing the schema migration. The read stays. The migration happens in November and nobody connects the two.",
  worked: "Consequence, mechanism, and what you want, with no doctrine anywhere in it:\n\n\"My concern is specific rather than architectural. When their team runs a migration, nothing tells them we are reading that table, because our read does not appear in any dependency they can see. The first signal we get from a dropped or renamed column is a failure in production, most likely out of hours, and we will spend the first hour of that incident not knowing what changed. I would want either a view they own and version, or an alert on their migration channel that we own.\"\n\nOffering two concrete mitigations at the end is what makes this a design conversation rather than a values conversation.",
  experiment: "Go through your last quarter of review comments and mark every one that names a principle rather than a consequence. Rewrite three of them as predictions about specific mechanisms. Notice how many of the rewrites turn out to be about consequences you had not actually checked would occur here.",
  reflection: "Which principle do you invoke most often in review, and when did you last decompress it into the specific consequence?",
  recall: {
    q: "Why is arguing from a principle weaker than arguing from the consequence it summarises?",
    a: "Because the principle is a compression of accumulated experience and can be dismissed as dogma by someone who has not had that experience, which moves the argument onto philosophy where no evidence exists and standing decides. The decompressed consequence is a prediction about a specific mechanism, which can be checked or mitigated, and dismissing it requires claiming it will not happen or does not matter."
  },
  deepDive: "Here is a review comment where I invoked a principle. Decompress it into the specific consequence I am actually worried about."
},
{
  id: "framing-write-it-before-you-say-it",
  track: "framing", level: "everyday",
  title: "An objection you have not written down is not finished, whatever it feels like",
  source: "General writing practice, and the observation in technical review that the discipline of drafting exposes gaps that rehearsal does not",
  gateIntro: "You have thought about this objection for two days. You have rehearsed it while driving and you are confident it is solid. You have not written it down, because writing it down feels like an unnecessary step for something you can already say. The meeting is in an hour and you have that hour free.",
  gatePrompt: "Write the objection in full, as prose, in the form you would say it. Not notes.",
  evidence: "No trial that establishes the specific claim. The related and much-studied phenomenon is the illusion of explanatory depth, where people rate their understanding of a mechanism highly and then discover on attempting a full explanation that it is shallow. That effect is well replicated for causal mechanisms. Whether it extends to rehearsed arguments has not been tested, and the extension is an inference.",
  replication: "craft",
  idea: "Write the objection out in complete sentences before delivering it, because internal rehearsal cannot detect a missing step and writing reliably can.",
  why: "Thinking about an argument and stating an argument are different operations and only one of them is checkable. Internal rehearsal skips. You move from the second point to the fourth because the third is obvious to you, and it stays obvious to you every time you rehearse it, so the gap never surfaces. This is the same mechanism as the illusion of explanatory depth: confidence in an explanation is high until the explanation has to be produced in full, at which point it frequently is not there.\n\nWriting forces sequence. You cannot leave a step out of a written paragraph without seeing the hole, because the sentence before it and the sentence after it will not join. The hour before a meeting is the cheapest possible place to find that hole. The alternative is finding it live, when someone asks the obvious question and you discover in front of everyone that the answer you thought you had was a feeling of having one. This is not about having notes to read from. Most people never look at the page. The value is entirely in having written it.",
  failureMode: "You go in on rehearsal. Two thirds of the way through, someone asks how the second point leads to the third, and you find out at that moment that it does not, quite. You recover, but the room saw the recovery, and the objection is now associated with an unfinished argument even after you fix it.",
  worked: "The output is not a script, it is a discovered gap. But the written version tends to be tighter than the rehearsed one, and it sounds like this:\n\n\"I want to argue against the November date, and there are three steps. One, the compliance work has to land before the migration or we are storing data we cannot delete on request. Two, the compliance work has a dependency on the identity service that their team has scheduled for December and has not moved despite two asks. Three, that means a November migration date is not ours to hold. My ask is that we either escalate the identity dependency or we move to January now rather than in six weeks.\"\n\nThat structure, three linked steps and one ask, is what falls out of writing. Rehearsal produces the first and third points and skips the middle, which is the one carrying the argument.",
  experiment: "Take an objection you are confident about and write it as prose, not bullets, before you deliver it. Then find the sentence you had to add that was not in your rehearsed version. Almost everyone finds one, and it is usually the load-bearing link.",
  reflection: "What argument are you confident about that you have never written out, and which step would you find missing?",
  recall: {
    q: "Why is internal rehearsal unable to detect a gap in an argument, and what does writing add?",
    a: "Rehearsal skips steps that feel obvious, and they feel equally obvious on every repetition, so the gap never surfaces. Writing forces sequence, and a missing step is visible because the sentences on either side of it will not join. The value is in having written it rather than in having notes, and the hour before the meeting is the cheapest place to find the hole."
  },
  deepDive: "I am going to state an objection. Interrogate each link in it and tell me which step I have skipped."
}
);
