/* Track: Working the room. Ordered foundational first.
 *
 * The two most famous studies in this subject sit here, and the popular
 * reading of both is wrong in the same direction: they are quoted as showing
 * that people are weak, and what they actually show is that arrangements are
 * decisive. That distinction is the difference between hiring for courage and
 * changing how a meeting runs. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "room-asch-is-overclaimed",
  track: "room", level: "everyday",
  title: "The conformity studies are quoted backwards, and the useful result is what one dissenter did",
  source: "Solomon Asch's line-judgement studies (1951 to 1956), including the variations with a dissenting partner",
  gateIntro: "In a planning session, four people in a row have supported an approach you think is wrong. You are fifth. You are aware of the famous experiment about people caving to a unanimous group and you are treating your situation as an instance of it, which is making you feel that saying anything is heroic. The chair is looking at you.",
  gatePrompt: "Write what you say, treating this as ordinary rather than heroic.",
  evidence: "Across the main series, about three quarters of participants gave the group's wrong answer at least once and about a quarter never did, but participants conformed on only around a third of critical trials, against an error rate near zero when judging alone. The variation that matters most here is the dissenting partner: a single confederate who broke the unanimity cut conformity by roughly three quarters, and it worked even when that confederate gave a different wrong answer rather than the correct one.",
  replication: "overclaimed",
  idea: "Read the conformity result as showing that unanimity is the active ingredient rather than that people are weak, because the great majority of judgements were independent and one dissenting voice removed most of the effect.",
  why: "The version everyone carries is that people cave to groups. The data say something narrower and much more useful. Most individual judgements across the critical trials were correct, a quarter of participants never went along at all, and the pressure was overwhelmingly a function of the group being unanimous rather than of it being large. Asch himself found that adding more confederates past three or four made little further difference, which is not what a simple story about social pressure would predict.\n\nThe dissenting-partner variation is the finding worth carrying. One other person breaking the unanimity collapsed conformity, and the striking detail is that the partner did not have to be right. A confederate giving a third, also-wrong answer produced much of the same effect. So what the lone objector needs is not support for their position, which is a high bar, but the mere existence of visible disagreement in the room, which is a much lower one. That reframes your problem entirely: you are not looking for an ally who agrees with you, you are looking for anyone at all who will say something other than yes.",
  failureMode: "You treat your situation as the experiment and yourself as the subject, which makes speaking feel like an act of exceptional courage and therefore something requiring a level of certainty you do not have. You stay quiet. The framing that was supposed to warn you about conformity produced it.",
  worked: "Speak plainly and without any signal that you regard this as difficult, because the register you use tells the room how to classify what you are doing:\n\n\"I think this is wrong, and I will say why. The approach assumes we can backfill from the archive, and the archive has a two week lag that nobody in this plan has accounted for. That is my whole objection and I could be wrong about the lag.\"\n\nWhat makes that work is what is missing: no reference to being the only one, no acknowledgement that everybody else disagrees, no framing of yourself as the dissenter. Naming your isolation invites the room to treat your view as a minority position rather than as a point.",
  experiment: "In your next meeting where a run of people agree, count how many of the agreements contain any new information and how many are endorsements. Unanimity built from endorsements is much weaker than it looks, and knowing that in the moment is worth more than any amount of resolve.",
  reflection: "When did you last stay quiet because everyone had already agreed, and how many of those agreements actually contained a reason?",
  recall: {
    q: "What is the active ingredient in the Asch result, and what is surprising about the dissenting partner variation?",
    a: "Unanimity rather than group size or general human weakness: most judgements were independent, a quarter of participants never conformed, and adding confederates past three or four changed little. The dissenting partner cut conformity by about three quarters, and it worked even when the partner gave a different wrong answer, so what breaks the effect is visible disagreement existing at all rather than support for your position."
  },
  deepDive: "Help me work out who in an upcoming meeting is most likely to say something other than yes, even if they disagree with me too."
},
{
  id: "room-recruit-one-person",
  track: "room", level: "everyday",
  title: "Find one person before the meeting, and they do not have to agree with you",
  source: "The dissenting-partner variations in Asch's studies and the peer-refusal variation in Milgram's, together with ordinary pre-meeting practice",
  gateIntro: "The vendor decision is on Thursday's agenda. You are against it. From the pre-read you can tell that at least four people are in favour and two have not formed a view. You have Tuesday and Wednesday free, and your current plan is to spend both of them making your argument as strong as possible.",
  gatePrompt: "Write the message you send on Tuesday to one person, before you touch your argument.",
  evidence: "Two separate experimental literatures converge here: conformity dropped sharply when one confederate broke the unanimity, including when that confederate was also wrong, and compliance in the obedience studies fell to its lowest levels in the variation where two peers refused first. The convergence is suggestive rather than conclusive, and it is worth noting that a later modified replication of the obedience work did not reproduce the disobedient-model effect.",
  replication: "single",
  idea: "Spend your preparation recruiting one other person who will speak rather than perfecting your argument, because the room's behaviour depends more on whether a second voice exists than on how good the first one is.",
  why: "The two experimental results that bear on this point in the same direction: a room in which somebody has already broken unanimity behaves very differently from one in which nobody has, and the effect is large relative to almost anything else you can control. Against that, the marginal value of your fourth hour of argument preparation is small, because the argument was already adequate after the first hour and the constraint was never argument quality.\n\nThe recruitment target is not who agrees with you. It is who will say something that is not assent, and the two most useful categories are people who have a different objection from yours and people who have not formed a view and will admit it in the room. Both break the pattern. The mistake is spending the conversation trying to convert someone to your position, which is hard, when all you need is for them to be willing to say out loud that they are not sure, which is easy and which most people are happy to do if asked directly.",
  failureMode: "You spend two days on the argument and walk into a room where nobody has spoken to anybody. You deliver a strong case, it is the only note of disagreement, and it is absorbed as one person's reservation. The two undecided people, who might have said so, follow the run of agreement because nothing in the room made not being sure a legitimate thing to say.",
  worked: "The ask is small, specific, and does not require agreement:\n\n\"Are you going to Thursday's vendor session? I am going to argue against it. I am not asking you to back me, and I know you might well be in favour. What I am asking is that if you have any reservation at all, even a different one from mine, you say it in the room rather than after. I think this one gets decided by whether it sounds unanimous.\"\n\nEven a different one from mine is the load-bearing phrase. It converts a request for support, which people decline, into a request for honesty, which they do not.",
  experiment: "Before your next contested meeting, cap your argument preparation at one hour and spend the rest on two conversations. Then compare how that meeting went with the last one you over-prepared for. The comparison is not rigorous and it is usually decisive.",
  reflection: "Who in your next contested meeting has an unformed view or a different objection, and have you spoken to them?",
  recall: {
    q: "Why is recruiting one person a better use of preparation than improving your argument, and what should you actually ask them for?",
    a: "Because two converging experimental results suggest a room where unanimity is already broken behaves very differently, and that effect is large relative to the small marginal value of further argument polishing. Ask not for agreement but for them to voice any reservation they have, including a different one, or simply to say in the room that they are undecided."
  },
  deepDive: "Here is who will be in a meeting I need to challenge. Help me pick the one person to speak to beforehand and draft the ask."
},
{
  id: "room-senior-speaks-last",
  track: "room", level: "costly",
  title: "Whoever speaks first sets the range, so change the order rather than fighting the anchor",
  source: "Sunstein and Hastie on deliberative anchoring and self-silencing cascades (Wiser, 2015), and standard facilitation practice",
  gateIntro: "You now chair the architecture review. You have noticed that when the principal engineer states a view in the first two minutes, the rest of the discussion happens inside a narrow band around it, and when they hold off, the discussion is wider and takes longer. You have the authority to run the meeting however you want. The next review is on Monday and the principal will be there.",
  gatePrompt: "Write what you say at the start of Monday's review to change the order.",
  evidence: "The underlying components are reasonably well supported: early contributions anchor subsequent judgements, and people withhold information that contradicts an emerging consensus. Sunstein and Hastie assemble these into the prescription that leaders should speak last, which is sensible and is a synthesis rather than a tested intervention. No trial has compared meetings run with and without the rule.",
  replication: "craft",
  idea: "Have the most senior or most expert person state their view last as a standing rule of the meeting, because an early statement from them defines the range within which everything afterwards happens.",
  why: "The first substantive contribution in a discussion is not one input among several. It establishes what the discussion is about and roughly where the plausible answers lie, and every later contribution is positioned relative to it. When it comes from the most senior person, that positioning acquires a second layer, because disagreeing now costs something that disagreeing with a peer does not. The combination is why a strong opening view from the wrong person can compress a discussion that needed to be wide.\n\nThe reason to make it a standing rule rather than a request in the moment is that a request in the moment is a comment about that person. Announced as how this meeting runs, it applies to everybody, it does not single anyone out, and it survives you not being in the room. It also has a second benefit that is easy to miss: the senior person usually gets a better meeting out of it, because they hear the unanchored version, which is the version they actually wanted and were not getting. Framed that way it is an offer rather than a constraint, and it is much easier to introduce.",
  failureMode: "You raise it as a request to that individual, in the moment. It is heard as a comment on their tendency to dominate, which may be true and is not what you wanted to say. They agree, awkwardly, and the rule lasts two meetings.",
  worked: "Introduce it as a property of the meeting, applying to everyone, with the benefit stated in terms of what the senior person gets:\n\n\"One change to how these run, starting today. We are going to go round on the substance before anyone with a decision right gives a view, and I am including myself in that. Nothing to do with anybody in particular. It is that when the most experienced person in the room speaks first, we all argue inside whatever they said, and I think that costs us the version of the discussion where we find the thing nobody expected. Priya, that means I am going to come to you last, and I think you will get a better read out of it.\"",
  experiment: "Run three meetings with the rule and note the range of positions expressed, not the quality of the decision. Range is the observable this changes and it changes quickly. Decision quality is what you actually care about and you will not be able to measure it, which is worth being honest about rather than pretending otherwise.",
  reflection: "In your meetings, who speaks first on substance, and how wide is the discussion that follows?",
  recall: {
    q: "Why does the senior person speaking first compress a discussion, and why should the fix be a standing rule?",
    a: "Because the first substantive contribution establishes the range within which everything else is positioned, and when it comes from a senior person disagreeing carries an extra cost, so the discussion narrows twice over. A standing rule applies to everyone and survives your absence, whereas an in-the-moment request reads as a comment on that individual and lasts about two meetings."
  },
  deepDive: "Help me introduce a speak-last rule for my review meeting without it sounding like a complaint about one person."
},
{
  id: "room-write-before-you-talk",
  track: "room", level: "costly",
  title: "Collect positions in writing before discussion, because a discussed group produces fewer ideas than the same people alone",
  source: "Diehl and Stroebe's meta-analytic work on productivity loss in brainstorming groups (Journal of Personality and Social Psychology, 1987)",
  gateIntro: "Your team runs a design discussion every fortnight. It is well attended and people are engaged. You have noticed that the ideas that end up in the document are almost always variations on whatever the first two people said, and that a colleague who says very little in the session sends excellent written comments the next day that nobody reads because the decision has been taken.",
  gatePrompt: "Write the message that changes the format, sent to the team before the next session.",
  evidence: "Interacting groups reliably produce fewer and less varied ideas than the same number of individuals working separately and pooling their output, a result that has held across many studies and decades. The main mechanism identified is production blocking, since only one person can speak at a time and waiting degrades what you were going to say. The finding is robust for idea generation; extending it to evaluative discussion and to objection-raising is an inference.",
  replication: "replicated",
  idea: "Have everybody write their position before any discussion happens, because a group talking produces less than the same individuals writing separately, and the gap is largest for the people who speak least.",
  why: "The nominal group result is one of the sturdier findings in this area and it is consistently counterintuitive to the people it applies to: groups that discuss feel more productive and generate less. The identified mechanism is mundane rather than psychological. Only one person can talk at a time, so most of the meeting is spent waiting, and while waiting you either rehearse and lose the thread or listen and lose your idea. Add anchoring on the first contributions and the observed pattern, where everything in the document is a variation of the first two contributions, is exactly what you would predict.\n\nFor disagreement specifically there is an additional effect worth naming. Writing removes the social cost of going first, because everybody submits simultaneously and nobody is visibly the one who broke ranks. Your quiet colleague is not short of views, they are short of a channel whose cost they are willing to pay, and the written channel they are already using is arriving after the decision. Moving it before the decision costs nothing and is the entire intervention.",
  failureMode: "You keep the discussion format and ask people to send written thoughts afterwards. The thoughtful comments keep arriving the next day, when the direction is set, and they are read as afterthoughts. The team concludes that some people are just not verbal, which is a conclusion about the format wearing the costume of a conclusion about the people.",
  worked: "Change the format, state the mechanism briefly, and make the written step mandatory rather than optional:\n\n\"Changing how the design session runs from next time. I will send the problem two days ahead. Everyone writes their position and their main objection in the doc before the meeting, and we do not discuss anything until they are all in. The reason is that we keep converging on whatever the first two people say, and half the good material in this team arrives in written comments the day after the decision. Ten minutes of writing beforehand, and then we spend the session on where we disagree rather than on generating.\"\n\nSimultaneous submission is what makes this work. If people can see each other's comments before writing, you have rebuilt the anchoring problem in a slower medium.",
  experiment: "Run one session written-first and count the number of distinct positions before discussion against the number that surfaced in your last three discussion-first sessions. The difference is usually visible immediately and does not require any subtlety to interpret.",
  reflection: "Who on your team writes better than they speak, and is their channel arriving before or after the decision?",
  recall: {
    q: "What does the nominal group finding show, what is the mechanism, and what extra benefit does writing give to disagreement specifically?",
    a: "Individuals working separately and pooling output generate more and more varied ideas than the same people in discussion, mainly through production blocking, since only one person speaks at a time and waiting degrades what you had. For disagreement it also removes the cost of going first, because everyone submits simultaneously and nobody is visibly the one who broke ranks."
  },
  deepDive: "Help me redesign my team's design session to be written-first, including exactly what people should be asked to write."
},
{
  id: "room-groupthink-is-contested",
  track: "room", level: "costly",
  title: "Groupthink is a vocabulary that outran its evidence, and using it ends the diagnosis early",
  source: "Irving Janis, Victims of Groupthink (1972), and the subsequent reviews of empirical tests including Esser and Turner and Pratkanis (1998)",
  gateIntro: "After a bad decision, the retrospective has settled on groupthink as the explanation and everyone in the room is nodding. The action item that follows is to encourage more open debate. You think the actual cause was that the two people who knew most about the system were not invited and the decision was made in eleven days over a holiday period.",
  gatePrompt: "Write the intervention that redirects the retrospective without dismissing the people who reached for the label.",
  evidence: "Janis built the model from retrospective analysis of a small number of famous policy failures, selected because they had failed. Later reviews of laboratory and field tests found support for isolated components, particularly the effects of directive leadership and insulation, and little support for the full antecedent-process-outcome model. Cohesion, the central antecedent, has not shown the predicted relationship reliably. The vocabulary is far more established than the theory.",
  replication: "contested",
  idea: "Refuse the label and ask the mechanical questions instead, because groupthink names the outcome you are trying to explain and adopting it closes the investigation at the point it should start.",
  why: "The problem with the term is not that nothing it describes is real. It is that it is a single word covering several distinct mechanisms with different fixes, and once a room adopts it the investigation stops. The action item that follows is always some version of encourage open debate, which is not an intervention, because nobody was discouraging debate on purpose.\n\nThe evidential position is worth knowing because it changes how firmly you can push back. Janis worked backwards from failures, which cannot establish that the pattern distinguishes failures from successes, and the later tests were unkind to the full model, particularly to cohesion as the driver. Some components survived: directive leadership and insulation from outside information do show effects. Those are exactly the two that map onto your actual explanation, which is that the people with the information were not present and the timeline was compressed. Those are mechanical, checkable and fixable. Groupthink is none of the three.",
  failureMode: "The retrospective closes on groupthink with an action to foster more open debate. Nothing changes about who gets invited or how long decisions take, the same two people are left out of the next decision for the same structural reason, and the next retrospective reaches the same conclusion, which everyone finds confirming.",
  worked: "Accept what is right about the intuition, then convert it into questions that have answers:\n\n\"I think the instinct behind groupthink is right and I want to make it more specific, because encourage open debate is not something anyone can do on Monday. Three questions. Who had information about this that was not in the room? How long did we take, and was that our choice? And what did we do with the one objection that was raised on the fourteenth? I think the answers are Priya and Tom, eleven days over Christmas, and we deferred it. Those are three fixable things and groupthink is not.\"",
  experiment: "In your next retrospective, ban the word and require three specific answers instead: who was absent, how compressed the timeline was, and what happened to any objection that was actually raised. The quality difference in the resulting actions is immediate.",
  reflection: "When your organisation reaches for groupthink as an explanation, what mechanical question does it stop you asking?",
  recall: {
    q: "What is the evidential status of groupthink, and what should replace the label in a retrospective?",
    a: "Janis worked backwards from a small number of selected failures, which cannot show the pattern distinguishes failure from success, and later tests supported isolated components such as directive leadership and insulation while failing to support the full model or cohesion as the driver. Replace it with mechanical questions: who with relevant information was absent, how compressed the timeline was, and what happened to objections that were raised."
  },
  deepDive: "My team blamed groupthink for a bad decision. Help me build the specific mechanical questions that would find the actual cause."
},
{
  id: "room-authentic-dissent-beats-assigned",
  track: "room", level: "costly",
  title: "An assigned devil's advocate produces worse thinking than a real objector",
  source: "Charlan Nemeth's programme on minority influence and dissent, summarised in In Defense of Troublemakers (2018)",
  gateIntro: "Your team has instituted a rotating devil's advocate for design reviews. It has been running for two months. The person in the role makes competent objections and everybody knows they do not mean them, and the objections are answered efficiently and the design proceeds. You think the practice is doing nothing and you are aware it was introduced with good intentions by your own manager.",
  gatePrompt: "Write the case for changing it, addressed to the person who introduced it.",
  evidence: "Across a series of studies, exposure to authentic minority dissent produced more divergent thinking, more search for information on both sides, and better solutions than exposure to a role-played devil's advocate, with the assigned version sometimes strengthening the majority's original position. The programme is internally consistent and spans many experiments, but it comes overwhelmingly from one research group and has not been subject to large independent replication.",
  replication: "single",
  idea: "Prefer protecting the people who genuinely disagree over assigning someone to pretend, because authentic dissent produces broader thinking and role-played opposition can strengthen the position it was meant to test.",
  why: "The mechanism Nemeth's work points at is that authentic dissent is unsettling in a productive way. It forces reconsideration because it might be right and the dissenter clearly believes it. Assigned dissent carries none of that, because everyone knows the objection is an exercise, so the majority can rehearse its answers without ever entertaining the possibility of being wrong. In some of the studies the assigned version left people more confident than before, which is the worst possible outcome for a practice adopted to reduce overconfidence.\n\nThe honest caveat matters here, because this entry is arguing against a popular practice on the strength of one research programme. What can be said is that the assigned-advocate ritual has no positive evidence behind it at all, so the comparison is not between two evidenced options. And the practical observation is available to anybody: watch what happens in the room. If the objections are answered efficiently and nobody looks uncomfortable, the ritual is producing the appearance of challenge, which is worse than nothing because it discharges the obligation to seek the real thing.",
  failureMode: "The rotation continues. Everyone can point to a process that surfaces objections, so nobody looks for the people who actually have them, and the two engineers with real reservations stay quiet because the challenge slot is already filled by somebody performing it.",
  worked: "Credit the intent, name the specific observation, and propose the replacement rather than just the removal:\n\n\"I want to make the case for dropping the rotating advocate, and I know you brought it in for a good reason. What I have watched for two months is that the objections get answered efficiently and nobody in the room ever looks unsettled, including the person making them. The research I have seen on this suggests assigned opposition can actually leave a group more confident, because you rehearse the answers without ever thinking you might be wrong. What I would rather do is find the people who genuinely disagree before the review and make sure they are in it, even when their objection is awkward or half-formed.\"",
  experiment: "For one review, replace the rotation with a question asked of everyone beforehand: is there anything about this you would actually argue against? Invite whoever says yes, and watch whether the room feels different. The observable is discomfort, and its absence is the diagnosis.",
  reflection: "Does your team have a ritual that produces the appearance of challenge, and who has stopped objecting because the slot is filled?",
  recall: {
    q: "Why does an assigned devil's advocate underperform authentic dissent, and what caveat should be attached to this claim?",
    a: "Because everyone knows the objection is an exercise, so the majority rehearses its answers without entertaining being wrong, and in some studies the group ended more confident than before. The caveat is that this comes overwhelmingly from one research programme with no large independent replication, though the practice it argues against has no positive evidence at all."
  },
  deepDive: "My team runs a rotating devil's advocate. Help me design a replacement that surfaces people who genuinely disagree."
},
{
  id: "room-be-the-second-voice",
  track: "room", level: "everyday",
  title: "Being the second person to object is the cheapest high-value thing you can do in a meeting",
  source: "The dissenting-partner variations in the conformity studies, applied to ordinary meeting practice",
  gateIntro: "Someone junior has just raised an objection to the deployment plan. It was not well argued and it was partly wrong. The room has moved on politely. You think their underlying concern is correct even though their reasoning was not, and the discussion has already progressed two items past it.",
  gatePrompt: "Write what you say to go back, given that their argument was partly wrong.",
  evidence: "The relevant experimental result is that breaking unanimity, rather than supplying a correct alternative, is what reduces conformity, and that a partner who was themselves wrong still produced much of the effect. Extending this to endorsing a colleague's imperfect objection in a meeting is an application rather than a tested claim, and it should be held at that strength.",
  replication: "single",
  cheat: "Second the concern even when the reasoning was wrong. \"Their argument was off, the worry underneath it is not.\"",
  idea: "Support the concern behind a badly argued objection rather than letting it die with the argument, because the second voice is what makes the first one count and it costs you almost nothing.",
  why: "The first objection in a room is the expensive one. The second is cheap, because unanimity is already broken and the person making it is not exposed in the same way. That asymmetry means the second voice is the single best value intervention available to anyone in a meeting: near-zero cost to you, and it changes the status of the first objection from an outlier to a pattern.\n\nThe complication here is that the argument was partly wrong, and the instinct is to let it go rather than endorse something flawed. That instinct is the failure. You can separate the concern from the reasoning explicitly, which is honest and is also more useful to the person who raised it than silence. There is a second effect that outlasts the meeting: junior people calibrate how much objection costs by watching what happens to objections, and an objection that dies in silence is a stronger signal about your team than anything anybody says about psychological safety.",
  failureMode: "You let it go because the argument was weak. The concern was right. It resurfaces as an incident in six weeks. The junior engineer who raised it learns that raising something imperfectly formed results in polite dismissal, and adjusts, and you have lost more than one objection.",
  worked: "Go back explicitly, separate the concern from the argument, and take the work of restating it yourself:\n\n\"Can we go back two items. Sam raised something about the deploy order and we moved past it. I do not think the reasoning about the cache was right, but I think the concern underneath is, and I want to restate it. If the schema change lands before the consumers are updated, the consumers fail closed rather than degrading, and we have no signal that tells us that is happening. Sam, is that what was bothering you, or have I got the wrong end of it?\"\n\nHanding it back at the end matters. You have amplified them rather than taken it over, which is the difference between supporting a colleague and replacing them.",
  experiment: "For a fortnight, commit to seconding every objection you think has something in it, within the same meeting, even when the argument is poor. Count how many turn out to have been worth pursuing. The instructive part is usually how few of the good ones would have survived without the second voice.",
  reflection: "Whose objection died in silence in your last few meetings, and was the concern underneath it right?",
  recall: {
    q: "Why is the second objection so much cheaper than the first, and how do you second an argument you think is wrong?",
    a: "Because unanimity is already broken and the second speaker is not exposed the way the first was, while the second voice converts the first objection from an outlier into a pattern. You second it by separating the concern from the reasoning explicitly, restating the concern in its strongest form, and handing it back to the original speaker to confirm."
  },
  deepDive: "Someone on my team raised a weak version of a good objection. Help me restate the concern in its strongest form and give it back to them."
},
{
  id: "room-name-the-decision-rule",
  track: "room", level: "everyday",
  title: "Ask how this will be decided before you argue, because you may be arguing for a vote that is not happening",
  source: "Facilitation and decision-rights practice, where the decision rule is expected to be stated before deliberation begins",
  gateIntro: "The room has been debating for forty minutes. You have been arguing hard, on the assumption that the outcome depends on where the room lands. It has just become clear from an aside that the decision was effectively made last week by two people and this meeting is to bring everyone along. Nobody said that at the start, and probably nobody thought to.",
  gatePrompt: "Write the question you should have asked in the first two minutes.",
  evidence: "No trial. Stating the decision rule before deliberation is standard facilitation practice, because the alternative wastes participants' effort and produces resentment when the rule turns out to be different from the one assumed. There is no measurement of how frequently the rule goes unstated, and the observation that people argue as though it were a vote is practitioner experience.",
  replication: "craft",
  cheat: "First two minutes: \"Who is deciding this, and is this meeting an input or the decision?\" Everything else depends on the answer.",
  idea: "Ask at the start who decides and whether the meeting is input or decision, because the right way to spend your turn is completely different in the two cases and nobody will volunteer the answer.",
  why: "You are optimising for the wrong objective if you do not know the rule. In a room that is genuinely deciding, persuading the room is the goal and arguing at length is rational. In a room that is consulting on a decision already made, persuading the room does nothing, and the correct move is to make sure your specific input is recorded clearly enough to survive, and to spend your energy afterwards on the person who actually holds the call. Forty minutes of hard argument in the second case is not just wasted, it is actively costly, because it burns credibility in front of an audience that cannot act on it.\n\nThe reason the rule usually goes unstated is not concealment. The person who holds the call knows what the meeting is for and does not think to say, because it is obvious to them. Asking is therefore not an accusation and is almost never taken as one. The question also does useful work when the answer is unclear, because a room where nobody can say who decides has a bigger problem than whatever is on the agenda, and surfacing that in the first two minutes is more valuable than anything you were going to argue.",
  failureMode: "You argue for forty minutes in a room that was never deciding. The two people who made the call watch you spend your capital on an audience, your input never gets recorded in a form they can use, and the meeting ends with everyone brought along, which is what it was for.",
  worked: "Ask it flatly at the start, as an ordinary procedural question, with both options named so it is easy to answer:\n\n\"Before we start, can I check how this gets decided? Is this a discussion where the room lands somewhere, or is there a call being made and this is input into it? I ask because I have a strong view and I want to spend it the right way.\"\n\nI want to spend it the right way is what keeps this from sounding like a challenge to the process. You have said plainly that the answer changes your behaviour, which is true and is the reason for asking.",
  experiment: "Ask the question at the start of every meeting where a decision is on the agenda for a month. Record the answers. The pattern that usually emerges is that the answer is clear in a minority of cases, and the meetings where nobody can answer are the ones that generate the most rework.",
  reflection: "In the last decision meeting you argued hard in, who actually held the call, and did you know at the time?",
  recall: {
    q: "Why does the decision rule change how you should spend your turn, and why is asking rarely taken as a challenge?",
    a: "In a deciding room, persuading the room is the goal; in a consulting room, persuasion does nothing and the correct move is to get your specific input recorded and then work on whoever holds the call, so arguing at length burns credibility in front of people who cannot act. Asking is not taken as a challenge because the rule usually goes unstated through obviousness rather than concealment."
  },
  deepDive: "Help me phrase the opening question about who decides for a meeting where I suspect the call is already made."
},
{
  id: "room-agenda-slot",
  track: "room", level: "everyday",
  title: "An objection with no slot on the agenda is an objection that will run out of time",
  source: "Meeting practice, where agenda control is treated as the primary determinant of what actually gets discussed",
  gateIntro: "You have a substantial concern about the data model that needs about fifteen minutes. The agenda for Thursday has four items, none of them yours, and the meeting has run over every week for a month. Your plan is to raise it under any other business, which is the last item, and which has been reached twice in the last six weeks.",
  gatePrompt: "Write the message to the chair, sent today, that gets you a slot.",
  evidence: "No trial. This is operational reality rather than a finding: agenda position determines what is reached in a meeting that runs over, and any other business is structurally the least likely item to be reached. Nobody has studied it because nobody needs to.",
  replication: "craft",
  idea: "Get your objection onto the agenda as a named item with a time estimate rather than relying on finding a moment, because in an over-running meeting the unslotted item is the one that does not happen.",
  why: "This is the least intellectually interesting entry here and one of the highest-yield. A great deal of dissent fails at the logistical layer rather than the social one: people prepare a good objection, plan to raise it when there is a natural opening, and the opening does not come. The meeting runs over, the chair prioritises the slotted items correctly, and any other business is not reached. Nothing about that involves anybody suppressing anything.\n\nAsking for a slot is nearly always granted, because chairs want to know what is coming and a named item with a time estimate makes their job easier rather than harder. It also has a side effect worth having: an item on the agenda has a name, and the name is a small piece of framing you control, written down before anyone has heard your argument. Data model: deletion under retention rules frames the discussion before it starts, and framing it yourself is free.",
  failureMode: "You wait for the moment. The meeting runs over, any other business is not reached, and the same happens the following week. Three weeks later the data model is built, and you have a well-prepared objection to something that already exists.",
  worked: "Send it two days ahead, with the name, the time and what you want out of it:\n\n\"Can I get fifteen minutes on Thursday? Item name: data model, deletion under retention rules. I do not want to raise it under any other business because we have not reached that in a month. What I need from the meeting is a decision on whether the tenant key goes on the events table, and I will circulate a page beforehand so we are not spending the fifteen minutes on context.\"\n\nOffering the pre-read is what makes fifteen minutes affordable to a chair with a full agenda, and it means the slot gets used on the disagreement rather than the setup.",
  experiment: "For the next month, put every objection you intend to raise on an agenda in advance with a time estimate, and stop raising anything under any other business. Count what fraction of your objections actually get discussed, before and after.",
  reflection: "What have you been waiting for a natural opening to raise, and how many meetings has that been now?",
  recall: {
    q: "Why does a good objection commonly fail for logistical rather than social reasons, and what does asking for a slot buy beyond the time?",
    a: "Because in an over-running meeting the chair correctly prioritises slotted items and any other business is not reached, so an objection waiting for a natural opening never gets one, without anyone suppressing it. Beyond the time, a named agenda item gives you a piece of framing written down before anyone hears the argument, and a pre-read makes the slot affordable to grant."
  },
  deepDive: "Help me write an agenda item name and a fifteen-minute slot request for an objection I have been failing to raise."
},
{
  id: "room-who-is-not-here",
  track: "room", level: "costly",
  title: "Ask who is not in the room before you argue with the people who are",
  source: "Stakeholder analysis practice, and the recurring finding in incident and project reviews that the decisive information sat with somebody who was absent",
  gateIntro: "Eight people are deciding how to migrate the billing data. The room contains three engineers, two product managers, the programme lead and two people from finance operations. Nobody from support is present, and support handle every customer who notices a billing discrepancy. The discussion has been going for twenty minutes and nobody has mentioned this.",
  gatePrompt: "Write the intervention. It should take under thirty seconds.",
  evidence: "No trial. Reviews of failed projects and incidents recurrently identify information that existed in the organisation and was not present at the decision, and stakeholder analysis exists as a discipline in response. This is a pattern in retrospective accounts rather than a measured effect, and retrospective accounts have an obvious selection problem: the absent stakeholder is easy to identify once you know what went wrong.",
  replication: "craft",
  cheat: "\"Who is affected by this who is not here?\" Thirty seconds, and it is the highest-yield question in most decision meetings.",
  idea: "Ask early who is affected by the decision and not present, because an absent stakeholder is a hole in the room's information that no amount of argument between the people present can fill.",
  why: "Arguing well inside a room that is missing the relevant party is a way of producing a confident wrong answer efficiently. The people present will reach a conclusion, and the conclusion will be sound given what they know, and the thing they do not know is not visible to them by construction. This is a structurally different failure from the ones this site mostly deals with: nobody is suppressing anything and nobody is conforming, the information simply is not there.\n\nThe question is cheap and it is socially safe, which is unusual for a high-yield intervention. It is not a criticism of anybody, it does not require you to have a position, and the answer is usually obvious once asked. It is also a much better use of thirty seconds than continuing to argue, because if the answer is that support have not been consulted, then the argument you were about to have is premature and you have just saved the room twenty minutes. The honest caveat is that the evidence for this is retrospective, and retrospectives find absent stakeholders easily because they already know which absence mattered.",
  failureMode: "The decision is made by the eight people present. The migration produces a class of billing discrepancy that support have seen before under a different system and could have described in one sentence. They find out when the tickets arrive, and the fix costs more than the migration.",
  worked: "Short, neutral, and with a specific name attached so it cannot be answered abstractly:\n\n\"Quick one before we go further. Who is affected by this who is not in the room? I think support are, because they handle every billing discrepancy and they will see the fallout first. Should we get someone from there before we settle this, or is there a reason they do not need to be here?\"\n\nOffering the possibility that there is a good reason is what keeps it from being a criticism of whoever assembled the meeting.",
  experiment: "Ask the question in every decision meeting for a month, in the first five minutes, whether or not you have a view on the substance. Track how often the answer produces a change to the invite list. If it is more than one in five, your organisation has a systematic problem with who gets called.",
  reflection: "In your last significant decision, who was affected and absent, and did anyone ask?",
  recall: {
    q: "Why is an absent stakeholder a different kind of failure from the usual ones, and why is the question socially cheap?",
    a: "Because nobody is suppressing or conforming: the people present reason soundly from what they know, and what they do not know is invisible to them by construction, so more argument inside the room cannot fix it. The question is cheap because it criticises nobody, requires no position, and is usually answered immediately, and it can save the room the argument it was about to have."
  },
  deepDive: "Here is who is in a decision meeting I have coming up. Help me work out who is affected and missing."
},
{
  id: "room-no-corridor-caucus",
  track: "room", level: "costly",
  title: "The real meeting happening afterwards is a symptom, and joining it makes it worse",
  source: "Observation of meeting culture, and the standard treatment of the meeting-after-the-meeting in facilitation practice",
  gateIntro: "The decision meeting ended twenty minutes ago with apparent agreement. You are now in a corridor with two colleagues, and all three of you are saying things none of you said in the room. Somebody has just proposed that the three of you send a note afterwards. It is the fourth time this has happened this quarter and the previous three notes were never sent.",
  gatePrompt: "You are in the corridor. Write what you say to the two people you are standing with.",
  evidence: "No trial. The meeting-after-the-meeting is a widely described phenomenon in facilitation and organisational practice, understood as a symptom of a room where the cost of dissent exceeds the cost of a private conversation afterwards. It is a pattern description rather than a finding, and there is no measurement of prevalence or of what interventions reduce it.",
  replication: "craft",
  idea: "Treat the corridor conversation as a diagnosis rather than a venue, and convert whatever is said there into something that goes back into the room the same day.",
  why: "The corridor is where the real discussion goes when the room is more expensive than the corridor, and joining it feels like solidarity while functioning as a pressure valve. It discharges exactly enough frustration to make the formal channel survivable, which is why the same pattern recurs quarterly rather than escalating into a fix. The three notes that were never sent are the evidence: the conversation satisfied the need and the action was never required.\n\nThere are two legitimate uses. It is a genuine diagnostic, because it tells you precisely which topics are too expensive to raise in the room and roughly who else knows. And it can be the place where you find your second voice, which is a real function that connects directly to why a lone objection is so hard. What makes the difference is whether anything leaves. Corridor to record, the same day, in writing, with names on it. If nothing leaves, you have spent your dissent in the cheapest available place and it will not be there when you need it in the room.",
  failureMode: "You have the fourth corridor conversation. Nothing is sent, again. The decision stands, the three of you have each concluded independently that others share your view and that nothing can be done, and the shared belief that nothing can be done is now better established than the objection itself.",
  worked: "Name the pattern, in the corridor, and convert it before the group disperses:\n\n\"We have done this four times this quarter and we have never sent the note. I do not want to do it again. So: are we actually going to say this? I will write it up in the thread this afternoon, in my own name, with the two points about the rollback and the support load. If either of you will add a line, say so now, and if neither of you will I am still sending it and that is fine.\"\n\nCommitting to send it alone is what makes this honest rather than another negotiation, and it frequently produces two additions that would not have come from asking.",
  experiment: "Next time you are in one, ask a single question before the group breaks up: what will any of us actually do? Then note what happens. The most common answer is nothing, said out loud for the first time, and hearing it is more useful than the conversation was.",
  reflection: "What has been said to you in a corridor this quarter that never reached a document, and who else was there?",
  recall: {
    q: "Why does the corridor conversation perpetuate the problem it responds to, and what are its two legitimate uses?",
    a: "It functions as a pressure valve, discharging enough frustration to make the formal channel survivable, so the pattern recurs instead of forcing a fix. Its legitimate uses are diagnostic, telling you which topics are too expensive for the room and who else knows, and as the place to find a second voice, but only if something leaves it in writing the same day."
  },
  deepDive: "My team keeps having the real conversation after the meeting. Help me write the note that puts one of those conversations back on the record."
},
{
  id: "room-hold-the-floor",
  track: "room", level: "costly",
  title: "When you are interrupted, finish the sentence rather than restarting the point",
  source: "Facilitation and negotiation practice on floor-holding, and the general observation that a restarted point is heard as a repeated one",
  gateIntro: "You are eight words into an objection and someone has started talking over you. It is the third time in this meeting, and it is not aggressive, they are just quicker. Your instinct is to stop, let them finish, and come back to it in a minute. You have noticed that when you do come back, you tend to start the point again from the beginning.",
  gatePrompt: "You have been cut off mid-sentence. Write the exact words you use to continue.",
  evidence: "No trial. This is technique from facilitation and negotiation practice, where holding the floor through an interruption is taught as a skill and where the observed cost of yielding is that the point is either lost or restarted. There is a large sociolinguistic literature on interruption patterns and their distribution across status and gender, but it describes the phenomenon rather than establishing what recovery technique works.",
  replication: "craft",
  cheat: "Do not restart, continue. \"Let me finish the sentence\" and then say the sentence you were on. Restarting sounds like repeating.",
  idea: "Continue from where you were cut off rather than beginning again, because restarting makes a first attempt sound like a second one and spends your credit on repetition.",
  why: "Yielding and then restarting has a specific cost that is easy to miss. Your point has now been heard as beginning twice, and to everyone who was half-listening, which is most of the room, the second delivery registers as you making the same point again. You are charged for repetition without ever having completed a first attempt. If it happens three times, as it has here, you are perceived as the person who keeps returning to something, and that perception attaches to you rather than to the interruptions.\n\nContinuing from the interrupted position avoids all of that and it requires a short piece of technique, because simply talking louder does not work and reads badly. The move is to acknowledge the interruption in three or four words and then continue mid-thought rather than restarting, which signals that this is one continuous contribution rather than a new one. It is also worth being honest about the asymmetry: interruption is not distributed evenly, and if you are on the receiving end far more than others in the room, the individual technique is a coping mechanism and the actual fix belongs to whoever chairs.",
  failureMode: "You yield three times and restart three times. By the third, the chair moves on because it sounds like you have made this point before, which it does. Your objection has never once been stated in full, and the room's impression is that you laboured it.",
  worked: "Four words to hold the floor, then continue from the middle of the thought rather than the start of it:\n\n\"Let me finish the sentence. The dependency on the identity service is unscheduled, which means the March date is not something we control, and my ask is that we say that to the customer now rather than in March.\"\n\nWhat you avoid is the restart, which sounds like this: \"Sorry, so what I was saying was, if we look at the March date...\" That version has now started twice, and the room has heard the March date twice, and neither time was a complete argument.",
  experiment: "Count interruptions in your next three meetings, including who is interrupted and by whom. If the distribution is lopsided, take the count to whoever chairs rather than working harder on your own technique, because a technique that has to be deployed constantly is a tax rather than a solution.",
  reflection: "How often are you interrupted relative to others in your meetings, and have you ever counted rather than estimated?",
  recall: {
    q: "What does restarting after an interruption cost you, and what is the technique for continuing?",
    a: "It makes your first attempt sound like a repetition, so you are charged for labouring a point you have never completed, and after several rounds the perception attaches to you rather than to the interruptions. The technique is three or four words to reclaim the floor followed by continuing mid-thought rather than from the beginning, which marks it as one contribution."
  },
  deepDive: "I get interrupted a lot in one particular meeting. Help me decide whether to work on technique or take a count to the chair."
},
{
  id: "room-remote-gradient",
  track: "room", level: "costly",
  title: "A video call raises the price of interrupting, which silently raises the price of disagreeing",
  source: "Observation of remote meeting dynamics, and the general recognition in facilitation practice that turn-taking cues degrade over video",
  gateIntro: "Your team is half in a room and half on video. In the last four meetings, every objection has come from someone physically present. The remote participants include the two people who know the legacy system best. In the chat, which nobody reads during the call, there are several substantive comments from them, all posted and never spoken.",
  gatePrompt: "Write what you say at the start of the next call to change how it runs.",
  evidence: "No trial that isolates this. The mechanism proposed is that video removes the fine-grained turn-taking cues that let someone enter a conversation without a full interruption, so a remote participant must interrupt outright or stay silent, which raises the cost of the marginal contribution. Latency compounds it. This is a plausible mechanical account with wide practitioner agreement and no controlled evidence, and the hybrid-specific asymmetry is more strongly attested than the video-only one.",
  replication: "craft",
  idea: "Treat the remote half of a hybrid meeting as operating with a higher cost of speaking, and compensate structurally by going to them by name rather than waiting for them to enter the conversation.",
  why: "In a physical room, joining a conversation is a graded act: you can lean in, make a sound, catch someone's eye, and the current speaker yields without anyone having interrupted. Over video most of that is unavailable, and the remaining options are to talk over someone or to wait. Both are expensive, and the expense falls entirely on the remote participant. Layer a genuine objection on top of an already costly entry and you get exactly the pattern you have observed, which is not that remote people have no views but that their views are going to the chat.\n\nThe chat is the tell. Substantive comments posted and never spoken are the same phenomenon as written review arriving the day after the decision: the objection exists and has found the cheapest available channel, and the cheapest channel is the one nobody reads in time. The fix is structural and unglamorous. Go to the remote participants by name, before the room, and read the chat out loud as though it were speech. Neither requires anyone to be braver.",
  failureMode: "The meetings continue. The two people who know the legacy system best contribute in a channel that is read afterwards if at all, the room decides without them, and the conclusion drawn is that the remote members are less engaged, which is the same misreading as concluding that quiet people are not verbal.",
  worked: "Announce the change as a rule about the format, and make the chat explicitly first-class:\n\n\"Two changes for how we run this. First, on anything where we are deciding, I am going to come to the people on video by name before I open it to the room, because it is harder to get into a conversation from there and I do not want that deciding who we hear from. Second, I am going to read the chat out loud. If you put something in there, treat it as having said it, and I will make sure it gets treated that way too.\"",
  experiment: "For a month, record where each objection in your hybrid meetings came from: in-room, remote spoken, or chat. If the in-room share is far above their share of attendees, the format is selecting your dissent and no amount of encouragement will change it.",
  reflection: "In your hybrid meetings, what proportion of objections come from the remote half, and what is in the chat that nobody said out loud?",
  recall: {
    q: "Why does hybrid format suppress objections from remote participants, and what is the tell?",
    a: "Because the graded ways of joining a conversation in a physical room are unavailable over video, leaving only outright interruption or silence, so the cost of any contribution rises and the cost of an objection rises on top of it. The tell is substantive comments posted in chat and never spoken, which is the objection finding the cheapest channel, which is also the one nobody reads in time."
  },
  deepDive: "My hybrid meetings only produce objections from the people in the room. Help me write the format change and the rule about chat."
},
{
  id: "room-round-robin",
  track: "room", level: "costly",
  title: "Going round the table forces the silence to become a position",
  source: "Nominal group technique and standard facilitation practice on structured round-robin polling",
  gateIntro: "You are chairing. The proposal has been presented and you have asked twice whether anyone has concerns. Nobody has. You know from three separate corridor conversations this week that at least two people in this room have reservations, and both of them are sitting quietly and have made eye contact with nobody.",
  gatePrompt: "You are the chair and open questions have failed twice. Write what you say next.",
  evidence: "No trial isolating the round robin. Structured polling is a core component of nominal group technique, which as a package has evidence behind it for idea generation, and it is standard facilitation practice for the specific purpose of preventing silence being read as consent. The specific claim that polling surfaces objections that open questions miss is practitioner experience rather than a measured effect.",
  replication: "craft",
  idea: "Replace the open question with a poll by name that requires an actual position, because silence in response to does anyone have concerns is free and a named turn is not.",
  why: "The open question is answered by the group, and a group answers by nobody speaking. That costs nothing, requires no decision from anyone, and is systematically read as consent. Nobody has to lie. The two people with reservations have simply not volunteered, and not volunteering is not a statement.\n\nA poll by name removes the option. Each person is now individually asked and must say something, and saying I have no concerns is a small act with a name attached, whereas silence was not. That difference is enough to shake loose a meaningful share of unspoken reservations, particularly the mild ones that people judged not worth interrupting for. The cost is real: it is slower, it is uncomfortable the first few times, and it will produce some contributions that are not worth the time. The right response to that cost is to reserve it for decisions that are expensive to reverse rather than to abandon it.",
  failureMode: "You ask a third time in open form and get silence again, and record it as agreement. The two reservations surface six weeks later in the form of slow, unenthusiastic delivery from two people who never said yes and are now working on something they told nobody they doubted.",
  worked: "Announce the poll, make the ask specific enough that a nod does not satisfy it, and go by name:\n\n\"I am going to go round rather than ask the room, because I have asked twice and got nothing and I do not think that means everyone is happy. Same question to each of you: what is your biggest reservation about this, even if it is small and even if you think we should do it anyway? If you genuinely have none, say none and that is a real answer. Priya, start.\"\n\nEven if you think we should do it anyway is what separates having a reservation from opposing the plan, and it lets people contribute without appearing to be against it.",
  experiment: "Use it for one decision that would be expensive to reverse and note how many reservations surface after two rounds of open questions produced none. Then decide your own threshold for when the extra ten minutes is worth spending.",
  reflection: "In your last meeting where nobody raised a concern, how many people did you later learn had one?",
  recall: {
    q: "Why does an open call for concerns fail, and what makes a named poll different?",
    a: "Because the open question is answered by the group and a group answers with silence, which costs nothing, requires no decision from anyone and is read as consent, though nobody has actually stated agreement. A named turn removes the option: declining to raise anything becomes a small act with a name on it, which is enough to surface mild reservations people judged not worth interrupting for."
  },
  deepDive: "I chair a meeting where open calls for concerns get nothing. Write me the round-robin script including how to phrase the question."
},
{
  id: "room-mixed-signals-in-agreement",
  track: "room", level: "line",
  title: "Distinguish the people who agree from the people who have stopped arguing",
  source: "Practice in decision recording, where the distinction between consent, assent and exhaustion is treated as material",
  gateIntro: "The meeting has run ninety minutes on one topic. The last three contributions have been some version of fine, let us go with that. You are chairing and you have what looks like agreement. You also know that two of those three people were arguing the opposite position an hour ago and nothing new has been said in the last twenty minutes.",
  gatePrompt: "You are about to close. Write what you say instead of confirming agreement.",
  evidence: "No trial. Decision-recording practice in governance settings distinguishes agreement from acquiescence, and consensus processes in standards bodies formalise the difference by allowing a participant to stand aside from a decision without blocking it. The value of the distinction is procedural rather than empirical, and nobody has measured what happens to projects where exhaustion was recorded as agreement.",
  replication: "craft",
  idea: "Ask explicitly whether people agree or have merely stopped arguing, and record the difference, because a decision built on exhaustion has nobody who will defend it when it comes under pressure.",
  why: "Exhaustion and agreement produce identical behaviour in the room and completely different behaviour afterwards. Someone who agrees will defend the decision to their team, make the trade-offs it implies, and raise problems with it as problems to be solved. Someone who stopped arguing will implement it without conviction, describe it to their team as what was decided, and treat the first difficulty as evidence they were right. Neither of them lied to you.\n\nRecording the difference is more valuable than resolving it. You are frequently not going to convert the two people who stopped arguing, and you may not need to, since a decision can proceed with participants who have stood aside as long as everybody knows that is what happened. What is corrosive is recording it as agreement, because then the decision appears to have more support than it has, and when it comes under pressure in three months you will discover that its apparent supporters have no stake in defending it. The standards-body convention of allowing an explicit stand-aside exists for exactly this reason.",
  failureMode: "You close on apparent agreement and write it down as agreed. Three months later the approach hits trouble, and the two people who stopped arguing are the ones being asked to make it work. They describe it accurately as a decision that was made, nobody defends it, and it is reversed at a cost that the original ninety minutes could have avoided.",
  worked: "Ask the question plainly, offer standing aside as a legitimate answer, and say what you will do with it:\n\n\"Before I write this up, I want to be precise about what we have. Some of you have agreed and some of you have stopped arguing, and those are different things and both are acceptable. I am going to record it either way, so: if you are behind this, say so. If you are going along with it and would still do it differently, say that instead, and it goes in the notes as a stand-aside rather than as agreement. I would rather know now than find out in March.\"",
  experiment: "For a quarter, record stand-asides separately from agreement in every decision you chair. Then look back at which decisions ran into trouble and check the ratio. This is one of the few things on this site you can actually measure in your own organisation.",
  reflection: "Which decision that you recorded as agreed was actually built on two people who had stopped arguing?",
  recall: {
    q: "Why is exhaustion recorded as agreement corrosive, and what should be recorded instead?",
    a: "Because the two look identical in the room and diverge afterwards: someone who agrees defends the decision and treats difficulties as problems to solve, while someone who stopped arguing describes it as what was decided and treats the first difficulty as vindication, so the decision appears to have support it lacks when it comes under pressure. Record an explicit stand-aside as a legitimate distinct outcome."
  },
  deepDive: "Help me write the closing question for a long meeting that separates real agreement from people who have stopped arguing."
}
);
