/* Track: Cardiorespiratory fitness. Ordered foundational first.
 *
 * Drafted, then independently fact-checked against primary sources, then
 * revised against those verdicts. Entries whose central claim did not survive
 * the check were dropped rather than softened.
 */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "fitness-mortality-single-cohort",
  track: "cardio",
  level: "core",
  title: "Low fitness carried a larger mortality hazard than smoking or diabetes in one 122,007-person cohort",
  source: "Mandsager et al., JAMA Network Open, 2018",
  evidence: "Retrospective cohort of 122,007 consecutive adults referred for exercise treadmill testing at Cleveland Clinic between 1991 and 2014. Mean age 53.4, 59.2% male, median follow-up 8.4 years. Performance groups were defined by age- and sex-matched percentiles: low <25th, below average 25th-49th, above average 50th-74th, high 75th-97.6th, elite >=97.7th. Elite versus low: adjusted HR 0.20 (95% CI 0.16-0.24). Elite versus high: 0.77 (0.63-0.95). In the same adjusted model, smoking 1.41 (1.36-1.46), diabetes 1.40 (1.34-1.46), coronary artery disease 1.29 (1.24-1.35).",
  interval: { lo: 0.16, hi: 0.24, measure: "hazard ratio, elite versus low fitness" },
  replication: "single",
  verifiedOn: "2026-08-08",
  gateIntro: "You have seen the line that being unfit is worse for you than smoking. Before you look anything up, commit to two answers. First: how many independent cohorts do you think that specific comparison has been run in? Second: for it to be true, roughly how much larger would the low-fitness hazard have to be than the smoking hazard?",
  idea: "In a single large referral cohort, the mortality hazard associated with being in the lowest fitness band dwarfed the hazard associated with smoking, diabetes or coronary artery disease. The gradient kept improving into the elite band with no observed ceiling. That specific comparison comes from one hospital's treadmill lab, not from a body of replicated work.",
  why: "The comparison works because the two things being compared are not measured the same way. Smoking is a yes-or-no field on an intake form. Fitness here is a performance-graded percentile from a maximal treadmill test, so the low band is not \"a bit unfit\" - it is the bottom quartile of people who were sick enough to be sent for a stress test in the first place. Comparing an extreme percentile against a binary flag inflates the contrast before any biology enters.\n\nThe direction of the finding is solid and matches everything else in the literature. The magnitude is where the single-cohort caveat bites. This was a clinical referral population at one institution: everyone in it had a reason to be on that treadmill. People at the bottom of the fitness distribution in that setting carry undiagnosed disease, deconditioning from illness, and reverse causation that no covariate adjustment fully removes. For scale, inverting the 0.20 here implies a 5-fold spread between top and bottom. The pooled low-versus-high fitness estimate across 33 cohorts of healthy adults is RR 1.70 (95% CI 1.51-1.92) in Kodama et al., JAMA, 2009. Those two numbers describe different populations, not different biology, and only one of them is pooled.\n\nThe elite-versus-high result is the more interesting number for you and the one most often skipped. HR 0.77 (0.63-0.95) says that going from the 75th-97.6th percentile band to the top 2.4% still bought something, and the interval does not cross 1. That is the actual evidence against the \"too much cardio is bad for you\" claim, and it is far more modest than the headline.",
  failureMode: "You repeat the smoking comparison at a barbecue, someone who actually reads papers asks which cohorts it replicated in, and you have nothing. Worse, you use it to reason about yourself. You already race, so you are nowhere near the low band that generates the scary hazard ratio. The number that applies to you is the elite-versus-high one, and it is 0.77, not 0.20. Treating the headline as personally relevant leads to training as though enormous returns are still on the table when you are on the flat part of the curve, which is exactly how people over-train a plateau.",
  experiment: "Get your actual fitness percentile rather than guessing at it. Do a maximal-effort field test you can repeat: a flat 5 km time trial, or a 12-minute Cooper test on a track. Convert to an estimated VO2max, then look up the age-and-sex percentile from the FRIEND registry norms. Write the number down. Then ask the only question that matters for training decisions: which percentile band did you land in, and does the elite-versus-high hazard ratio or the elite-versus-low one describe your situation?",
  reflection: "Which claims in your own training beliefs are you holding at headline magnitude when only the direction has been established?",
  recall: {
    q: "The Mandsager cohort reported HR 0.20 for elite versus low fitness and 0.77 for elite versus high. Why does the second number matter more to a trained runner, and why should the first one not be quoted as an established fact?",
    a: "The 0.20 figure compares you against the bottom quartile of a clinical referral population - people sent for a stress test, disproportionately carrying undiagnosed disease and illness-driven deconditioning. If you race, you are not in that band and the number describes a transition you already made years ago. The 0.77 figure (95% CI 0.63-0.95) compares the elite group, the top 2.4%, against the 75th to 97.6th percentile band, which is the actual decision you face when choosing between maintaining and pushing. It is a real effect with an interval that excludes 1, and it is far smaller than the headline.\n\nThe first number should not be stated as established because it comes from one retrospective cohort at one institution. The direction is replicated everywhere. The magnitude is a property of that cohort's fitness distribution and its referral bias - the pooled low-versus-high estimate in healthy community cohorts is RR 1.70 (1.51-1.92), a different scale entirely. Direction and magnitude replicate at different rates, and the site's whole point is not to conflate them."
  },
  deepDive: "Show me how referral bias and reverse causation would inflate a low-fitness hazard ratio in a stress-test cohort, and what the same comparison looks like in a healthy community cohort."
},
{
  id: "fitness-mortality-per-met",
  track: "cardio",
  level: "core",
  title: "Each additional MET of aerobic capacity maps to about 13% lower all-cause mortality",
  source: "Kodama et al., JAMA 301(19):2024-2035, 2009",
  evidence: "Meta-analysis of 33 prospective cohorts of healthy men and women. All-cause mortality analysis: 102,980 participants, 6,910 deaths. CHD/CVD analysis: 84,323 participants, 4,485 events. Per 1-MET higher maximal aerobic capacity: RR 0.87 (95% CI 0.84-0.90) for all-cause mortality, 0.85 (0.82-0.88) for CHD/CVD. Low versus high fitness: RR 1.70 (1.51-1.92). Low versus intermediate: 1.40 (1.32-1.48).",
  interval: { lo: 0.84, hi: 0.9, measure: "relative risk per 1-MET higher fitness" },
  replication: "replicated",
  verifiedOn: "2026-08-08",
  gateIntro: "One MET is 3.5 mL of oxygen per kilogram per minute - roughly the difference a decent block of training can produce. Before reading on, commit to a number: how much do you think one extra MET is worth in all-cause mortality risk, and would you expect the effect to be bigger or smaller than the effect of moving from the bottom fitness third to the top?",
  cheat: "Retest your capacity instead of assuming it: RR 0.87 per MET (0.84-0.90) is between-person, so a MET you train will not buy the full 13%.",
  idea: "Pooled across 33 prospective cohorts of healthy adults, every 1-MET increment in maximal aerobic capacity was associated with 13% lower all-cause mortality and 15% lower coronary and cardiovascular event risk. This is the replicated backbone of the fitness-mortality literature. It is a smooth gradient, not a threshold you cross.",
  why: "This is the entry to reach for when someone asks whether fitness really matters, because it is the version that survived independent re-running. Thirty-three cohorts, over 100,000 healthy participants, and a tight interval of 0.84 to 0.90. Contrast that with single-cohort hazard ratios that produce more dramatic numbers from more selected populations.\n\nA MET is a usable unit. It is 3.5 mL·kg⁻¹·min⁻¹, so a runner going from a VO2max of 45 to 52 has gained two METs. The pooled estimate says that is worth roughly a quarter off relative all-cause mortality risk. It compounds multiplicatively across the range, which is why the low-versus-high category comparison lands at RR 1.70 rather than something enormous - the gradient is steady, not explosive.\n\nThe caveat that matters for a trained reader: these are observational associations across people, not within-person causal effects of training. Some of the fitness spread is genetic, some is inherited health, some is training. Individual response to a standardised training program varies enormously. Moving yourself up one MET through training is not guaranteed to move your risk by the full 13%, because part of the association is carried by the traits that made you trainable in the first place.",
  failureMode: "You treat fitness as binary. Once you are \"a runner\", you stop tracking capacity and let it drift down over a decade of consistent-but-easy volume, on the assumption that the health box is ticked. The per-MET gradient says the box is not binary and the drift costs you continuously. The opposite failure is treating the association as fully causal and chasing VO2max at the expense of injury risk, sleep and everything else, on the belief that each MET is a guaranteed 13% purchase.",
  experiment: "Convert your current best estimate of VO2max into METs by dividing by 3.5. Then dig out a test result or race time from five years ago and do the same. The difference, in METs, is the size of the change you have actually made or lost. Multiply 0.87 by itself once per MET gained to get the crude pooled association, then write next to it the honest note that part of that number is your genes and your baseline health, not your training.",
  reflection: "Have you measured your aerobic capacity in the last twelve months, or are you inferring it from the fact that you still run?",
  recall: {
    q: "What is the pooled relative risk of all-cause mortality per 1-MET higher cardiorespiratory fitness, and why should a trained runner discount it when reasoning about their own training?",
    a: "RR 0.87 (95% CI 0.84-0.90) per 1-MET, pooled from 33 prospective cohorts covering 102,980 participants and 6,910 deaths. The CHD/CVD estimate is 0.85 (0.82-0.88). This is the most replicated form of the fitness-mortality claim and the tight interval reflects the volume of independent data behind it.\n\nThe discount is that this is a between-person association, not a within-person training effect. The people with high measured fitness got there through some mixture of genetics, underlying health and training, and the association carries all three. Individual response to a standardised training block varies widely, so gaining a MET through training does not reliably deliver the full 13%. The gradient tells you the direction and the rough scale. It does not price your specific training block."
  },
  deepDive: "Explain how much of the between-person variance in VO2max is genetic versus trainable, and what that implies for reading a per-MET mortality gradient as a personal training target."
},
{
  id: "steps-mortality-seven-thousand",
  track: "cardio",
  level: "applied",
  title: "Seven thousand steps a day captures most of the mortality benefit and the curve flattens after",
  source: "Ding et al., Lancet Public Health 10(8):e668-e681, 2025",
  evidence: "Systematic review and dose-response meta-analysis, 57 studies from 35 cohorts, of which 31 studies from 24 cohorts entered the meta-analyses. Comparing 7,000 with 2,000 steps per day: all-cause mortality HR 0.53 (95% CI 0.46-0.60), from 14 studies. Cardiovascular disease incidence 0.75 (0.67-0.85), cardiovascular mortality 0.53 (0.37-0.77), cancer incidence 0.94 (0.87-1.01) from 2 studies, cancer mortality 0.63 (0.55-0.72), type 2 diabetes 0.86 (0.74-0.99), dementia 0.62 (0.53-0.73), depressive symptoms 0.78 (0.73-0.83), falls 0.72 (0.65-0.81). Inverse non-linear dose-response with inflection points around 5,000-7,000 steps per day for mortality, cardiovascular disease, dementia and falls.",
  interval: { lo: 0.46, hi: 0.6, measure: "hazard ratio, 7,000 versus 2,000 steps per day" },
  replication: "replicated",
  verifiedOn: "2026-08-08",
  gateIntro: "The 10,000-step target came from a 1960s Japanese pedometer brand name, not from a trial. Before you read the numbers: at what daily step count do you think the mortality benefit curve starts to flatten, and how much of the total benefit do you think is already banked by the time you reach that point?",
  cheat: "Check your median non-run-day steps against 5,000: the 5,000-7,000 inflection is all-cause only, cancer and cardiovascular mortality kept improving.",
  idea: "Pooling 57 studies across 35 cohorts, walking 7,000 steps a day was associated with 47% lower all-cause mortality than 2,000 steps, and the dose-response curve inflects somewhere around 5,000 to 7,000 steps rather than continuing to 10,000. The benefits extend well past mortality, to dementia, falls and depressive symptoms. Not every outcome flattens - cardiovascular mortality, cancer mortality and type 2 diabetes stayed roughly linear, and cancer incidence showed no association at either end.",
  why: "The shape matters more than the headline. An inverse non-linear association with an inflection between 5,000 and 7,000 steps means the steepest part of the curve is at the bottom. Going from 2,000 to 5,000 steps buys far more per step than going from 8,000 to 11,000. If you already run, you are past the inflection on most days, and the marginal value of your next thousand steps is small compared to the value of a sedentary colleague's next thousand.\n\nThe outcomes that did not flatten need reading carefully, because shape and benefit are different things. Cardiovascular mortality, cancer mortality and type 2 diabetes showed roughly linear shapes across the observed range, so more steps kept buying something for those. Cancer incidence was also modelled without a clear inflection, but its point estimate at 7,000 versus 2,000 steps is HR 0.94 with an interval of 0.87 to 1.01 - a null association from only two studies, not a benefit that keeps accruing. A straight line tells you nothing about whether the line is going anywhere. So \"7,000 is enough\" is true for the all-cause headline, wrong for the handful of outcomes that keep improving, and beside the point for cancer incidence, where the association is not there to begin with.\n\nThe confounding here is heavy and the authors would say so. Step count is measured mostly in cohorts of older adults, and low step counts are a symptom of illness as much as a cause of it. Reverse causation inflates the low end of the curve. The pooled hazard ratio of 0.53 should be read as the association across people, with the steepest part of it partly reflecting who is already unwell.",
  failureMode: "The specific way this goes wrong for a runner: you bank a 60-minute run, hit 12,000 steps by lunchtime, and then sit for nine hours. Step count is a poor proxy for the thing the epidemiology is actually capturing, which is a life with movement distributed through it. The other failure is the reverse - chasing 10,000 as a target on rest days, adding low-value junk volume on legs that need recovery, and buying almost nothing because you are already past the inflection.",
  experiment: "Pull your last 90 days of step data and split it into run days and non-run days. Look only at the non-run days, and find the median. That is your actual baseline movement with the training stripped out. If that median sits below 5,000, you have a sedentary life with a running habit stapled on, and the steep part of this curve applies to you on most days of the week.",
  reflection: "On your non-training days, are you actually an active person, or a sedentary person who trains?",
  recall: {
    q: "What was the pooled hazard ratio for all-cause mortality at 7,000 versus 2,000 steps per day, and which outcomes did not flatten?",
    a: "HR 0.53 (95% CI 0.46-0.60), from 14 studies within a review of 57 studies across 35 cohorts. The curve was inverse non-linear for all-cause mortality, cardiovascular disease, dementia and falls, with inflection points around 5,000 to 7,000 steps per day. That is the basis for the claim that 7,000 is a more realistic target than 10,000.\n\nThe outcomes without a clear inflection were cardiovascular mortality, cancer incidence and mortality, type 2 diabetes and depressive symptoms - but only some of those kept improving. Cancer incidence came in at HR 0.94 (0.87-1.01) from two studies, an interval crossing 1, so there is no benefit to keep accruing there regardless of the curve's shape. The flattening is outcome-specific and so is the benefit. Anyone who says \"the research shows 7,000 steps is all you need\" has collapsed a set of differently-shaped curves, one of them flat at zero effect, into one sentence."
  },
  deepDive: "Explain how reverse causation shapes the low end of a step-count dose-response curve in cohorts of older adults, and what the curve might look like if you could remove it."
},
{
  id: "polarised-versus-pyramidal-contested",
  track: "cardio",
  level: "advanced",
  title: "Polarised training's small VO2peak edge holds against pooled alternatives and disappears against pyramidal alone",
  source: "Silva Oliveira, Boppre & Fonseca, Sports Medicine, 2024; Rosenblat et al., Sports Medicine, 2025",
  evidence: "Silva Oliveira et al. pooled 17 studies (n=437) comparing polarised training against other intensity distributions pooled together, and found polarised superior for VO2peak, SMD 0.24 (95% CI 0.01-0.48), rising to 0.40 (0.08-0.71) in interventions under 12 weeks and 0.46 (0.10-0.82, p=0.01) in highly trained athletes. No advantage for time trial, -0.01 (-0.28 to 0.25), time to exhaustion, 0.30 (-0.20 to 0.79), or speed/power at the second threshold, 0.04 (-0.21 to 0.29). Rosenblat et al. ran a network meta-analysis of individual participant data from 13 studies, 348 athletes (296 male, 52 female, VO2max 46.6-68.3 mL·kg⁻¹·min⁻¹) and found no difference between polarised and pyramidal specifically for VO2max (SMD -0.06, p=0.68) or time trial (-0.05, p=0.34), with a significant competitive-versus-recreational subgroup difference (SMD -0.63, p<0.05): competitive athletes may improve VO2max more with polarised, recreational athletes more with pyramidal.",
  interval: { lo: 0.01, hi: 0.48, measure: "SMD, VO2peak, polarised versus other intensity distributions pooled" },
  replication: "contested",
  verifiedOn: "2026-08-08",
  gateIntro: "Polarised training - roughly 80% easy, 20% hard, with very little in between - is the most confidently repeated prescription in endurance coaching. Before you read the numbers: if two competent teams both meta-analysed the same trials, how far apart do you think their conclusions would be, and what would have to differ in their methods to produce that gap?",
  idea: "Two credible meta-analyses of the same small literature are quoted as disagreeing, and their headline results do differ - but they are not asking quite the same question. One compares polarised against all other intensity distributions pooled and finds a small VO2peak edge whose interval barely clears zero. The other runs a network model on individual participant data and finds polarised and pyramidal indistinguishable. Neither finds any advantage for time-trial performance, and their subgroup results point the same way, not opposite ways.",
  why: "Start with the comparators, because that is at least half the gap and it is the part nobody quotes. Silva Oliveira et al. pooled study-level effect sizes across 17 studies and 437 athletes, contrasting polarised against everything else lumped together, and found a small VO2peak edge, SMD 0.24 with a lower bound of 0.01. An interval that touches 0.01 is a result held together by rounding. Rosenblat et al. went to individual participant data from 13 studies and 348 athletes and modelled a network, which lets them isolate the polarised-versus-pyramidal node and handle within-athlete variation properly. Their main effect for that specific contrast was null, SMD -0.06, p=0.68. Different comparator, different pooling method, different answer. Only one of those differences usually gets mentioned.\n\nBoth agree on the part that matters most. Neither distribution wins on time trial. Silva Oliveira's time-trial estimate is -0.01 with an interval spanning -0.28 to 0.25. Rosenblat's is -0.05, p=0.34. VO2peak is a laboratory intermediate. If two intensity distributions produce the same race result, the argument about which one raises VO2peak by a fifth of a standard deviation is not a training decision.\n\nThe subgroups agree too, which is worth knowing if you have heard them described as contradictory. Silva Oliveira report polarised superiority for VO2peak in highly trained athletes, SMD 0.46 (0.10-0.82, p=0.01). Rosenblat report that competitive athletes may improve VO2max more with polarised while recreational athletes may improve more with pyramidal, SMD -0.63, p<0.05. Same direction: the more highly trained the group, the more polarised looks favourable. Rosenblat's overall null did not collapse the subgroup finding, it sat alongside it.\n\nThe evidence base is smaller than the confidence around it. 348 athletes across 13 studies, overwhelmingly male, with interventions typically under 12 weeks, and subgroup effects several times larger than the main effects. That is what an underpowered literature looks like when you slice it.",
  failureMode: "You restructure a season around a distribution rule and then defend it as evidence-based. The real cost is not the distribution itself - both work - it is that the rule displaces judgement. Athletes force themselves into the polarised template by making moderate days artificially easy and hard days artificially hard, generating either a recovery deficit or a stimulus deficit, when the data say the distribution was never the load-bearing variable. Total volume and consistency were, and neither review isolates those.",
  experiment: "Pull your last 12 weeks of training and classify every session by time in each intensity zone rather than by what you called the session. Most runners who believe they train polarised discover a pyramidal distribution with a fat middle. Then answer the question the meta-analyses cannot: over those 12 weeks, did total volume, consistency, or distribution vary most? Fix whichever varied most before touching the one that varied least.",
  reflection: "When you defend your intensity distribution, are you defending a result you observed in yourself or a rule you read?",
  recall: {
    q: "Two meta-analyses are quoted as disagreeing about polarised training. What did each actually compare, what did they find, and what do they agree on?",
    a: "Silva Oliveira et al. (17 studies, n=437) compared polarised against all other intensity distributions pooled and found it superior for VO2peak, SMD 0.24 (95% CI 0.01-0.48), with larger effects in short interventions and in highly trained athletes, 0.46 (0.10-0.82). Rosenblat et al. pooled individual participant data from 13 studies and 348 athletes into a network model and found no polarised-versus-pyramidal difference for VO2max, SMD -0.06, p=0.68. Two sources of the gap, not one: the comparator is different (everything else pooled versus pyramidal specifically), and the pooling is different (study-level versus individual participant data).\n\nThey agree on more than the framing suggests. Neither found any advantage for time-trial performance: -0.01 (-0.28 to 0.25) in one, -0.05 (p=0.34) in the other. And their subgroups point the same way, with polarised looking better in the more highly trained groups in both. It is filed contested because two competent teams do publish different headline conclusions on overlapping trials, not because they disagree about direction everywhere."
  },
  deepDive: "Walk me through why individual participant data meta-analysis can overturn a study-level pooled effect, using the polarised training literature as the worked example."
},
{
  id: "hiit-versus-continuous-vo2max-gap",
  track: "cardio",
  level: "applied",
  title: "Interval training beats continuous training for VO2max by about 1.2 mL·kg⁻¹·min⁻¹",
  source: "Milanović, Sporiš & Weston, Sports Medicine, 2015",
  evidence: "Meta-analysis of 28 controlled trials, 723 participants, mean age 25.1 ± 5 years, baseline VO2max 40.8 ± 7.9 mL·kg⁻¹·min⁻¹. Versus control, continuous endurance training raised VO2max by 4.9 mL·kg⁻¹·min⁻¹ (95% confidence limits ±1.4) and high-intensity interval training by 5.5 (±1.2). Head to head, interval training beat endurance training by 1.2 mL·kg⁻¹·min⁻¹ (±0.9), described by the authors as a possibly small beneficial effect.",
  interval: { lo: 0.3, hi: 2.1, measure: "mL·kg⁻¹·min⁻¹, 95% confidence limits on the interval-minus-continuous difference" },
  replication: "overclaimed",
  verifiedOn: "2026-08-08",
  gateIntro: "Interval training is sold as the time-efficient shortcut to aerobic fitness - same or better results in a fraction of the hours. Before reading on: in absolute mL·kg⁻¹·min⁻¹, how much more VO2max do you think interval training delivers than continuous training in a head-to-head pooled comparison?",
  idea: "Both interval training and continuous endurance training raise VO2max substantially against a control. Head to head, intervals win by 1.2 mL·kg⁻¹·min⁻¹ with confidence limits of ±0.9, which is roughly a third of one MET. The effect is real and the interval excludes zero. It is nothing like the transformation the popular framing implies.",
  why: "Look at the two arms separately first. Continuous training added 4.9 mL·kg⁻¹·min⁻¹ over control, intervals added 5.5. Both are large. The entire argument between them is that 0.6 gap, and the pooled head-to-head estimate of 1.2 has limits of ±0.9, so the plausible range runs from about 0.3 to 2.1. A third of a MET at the point estimate.\n\nThe popular version does not say \"intervals are somewhat better at raising VO2max\". It says intervals replace endurance training at a fraction of the time cost. That stronger claim is not what this meta-analysis measured. It pooled 28 controlled trials of the two modes as they were run and reported the difference in VO2max change. It does not report whether the interval arms took less weekly time, so nothing in the pooled estimate licenses the time-efficiency claim - you would need matched-duration trials to make it, and you would have to check each included trial to know whether you had them.\n\nThe population is the second discount. Mean age 25.1, mean baseline VO2max 40.8 - untrained to moderately trained young adults. If you already race, your position on the response curve is nothing like theirs, and the headroom for any intervention is smaller.\n\nThe overclaim is also a category error about what VO2max buys you. For a runner, VO2max is a ceiling, not a performance. Threshold and economy determine what fraction of that ceiling you can hold over a race distance, and neither is what this meta-analysis measured. A protocol that wins by 1.2 mL·kg⁻¹·min⁻¹ on the ceiling while costing you the weekly volume that builds the other two is a bad trade.",
  failureMode: "You convert easy volume into intervals on the basis that intervals are strictly better, and the arithmetic is brutal: you trade a 90-minute aerobic session for a 25-minute interval session, bank a fraction of a MET, and lose an hour of the mitochondrial and connective-tissue adaptation that easy volume was buying. Then the injury arrives, because the ratio of hard sessions to total load climbed while nobody was watching. The cost of this mistake is not the missing VO2max point, it is the six weeks off.",
  experiment: "Take the 1.2 mL·kg⁻¹·min⁻¹ figure and convert it into something you can feel. Divide it by 3.5 to get METs, then look up how much a third of a MET moves your predicted 10 km time using any standard VO2max-to-pace table. Write that time difference down. Now decide whether it justifies whatever change to your week you were about to make on the strength of the word \"time-efficient\".",
  reflection: "What proportion of your weekly training minutes are currently hard, and did you choose that proportion or inherit it from a headline?",
  recall: {
    q: "In the pooled head-to-head comparison, how much more did high-intensity interval training raise VO2max than continuous endurance training, and why is this filed as overclaimed rather than replicated?",
    a: "1.2 mL·kg⁻¹·min⁻¹ with 95% confidence limits of ±0.9, so a plausible range of roughly 0.3 to 2.1. Separately against control, continuous training added 4.9 (±1.4) and interval training 5.5 (±1.2), across 28 trials and 723 participants with a mean age of 25.1 and a mean baseline VO2max of 40.8.\n\nIt is filed as overclaimed because the effect is genuine but far smaller than the popular version. The interval does exclude zero, so intervals really are somewhat better for raising VO2max. What is not supported is the stronger claim the framing implies: that intervals substitute for endurance volume at a fraction of the time cost. The pooled estimate is a difference in VO2max change, not a difference per unit of training time, and it says nothing about the hours each arm spent. Add a young, only moderately trained population and the fact that VO2max is a ceiling rather than a race result, and you have a real, directionally correct effect a third of a MET wide."
  },
  deepDive: "Convert a 1.2 mL·kg⁻¹·min⁻¹ VO2max difference into an expected 10 km time change for a 45-year-old running 40 minutes, and show the assumptions the conversion depends on."
},
{
  id: "zone-two-prescription-is-craft",
  track: "cardio",
  level: "advanced",
  title: "The zone 2 prescription is coaching practice wearing a mitochondrial costume",
  source: "San-Millán & Brooks, Sports Medicine 48(2):467-479, 2018",
  evidence: "The most-cited physiological support is a cross-sectional comparison of professional endurance athletes, moderately active individuals and metabolic syndrome patients, measuring fat oxidation and blood lactate during submaximal exercise. Fat oxidation was significantly higher in professional athletes than in the other two groups (p<0.01) and blood lactate significantly lower, with strong inverse correlations between fat oxidation and lactate within groups (r = -0.92 to -0.98). No group was assigned a training dose, no intervention was applied and no alternative prescription was compared.",
  replication: "craft",
  verifiedOn: "2026-08-08",
  gateIntro: "Zone 2 has a specific popular prescription attached to it: several hours a week held strictly below the first lactate threshold, on the grounds that this intensity uniquely builds mitochondrial function. Before you read on, ask yourself: what would a controlled trial testing that specific prescription look like, and can you name one?",
  idea: "The physiological observations behind zone 2 are real - trained athletes oxidise more fat and clear more lactate at a given submaximal intensity. The prescription built on top of them is craft. No controlled trial has isolated the zone 2 dose itself against a matched alternative, and the flagship supporting study is a cross-sectional comparison of three populations, not an intervention.",
  why: "Separate three claims that get bundled together. First: fat oxidation and lactate at submaximal intensity differ sharply between trained and untrained people. That is measured and solid, with within-group correlations of -0.92 to -0.98. Second: training below the first threshold improves those markers. Broadly supported by the wider endurance literature. Third: a specific weekly dose of strictly sub-threshold work is the optimal way to build them, and superior to alternatives. That third claim is the prescription, and it is the one with no controlled test behind it.\n\nThe cross-sectional design is the crux. Professional cyclists have better metabolic flexibility than metabolic syndrome patients. This tells you nothing about which training produced the difference, because nobody trained anybody. It is exactly the shape of evidence that cannot distinguish \"zone 2 built this\" from \"twenty years of high-volume mixed training built this, and selection put the responders in the professional group\".\n\nWhat has been tested is training intensity distribution, and those trials do not answer the zone 2 question either. Polarised and pyramidal distributions both contain roughly 80% low-intensity work. They differ in how the remaining 20% is arranged, not in whether easy volume matters. No trial in that literature isolates time held strictly between the first and second thresholds as the manipulated variable. So the intensity-distribution evidence is about a different question.\n\nCalling this craft is not calling it wrong. High-volume easy running has produced fast athletes for sixty years and the coaching consensus is worth respecting. It just has not been through a controlled dose-finding trial, and it is presented as though it has.",
  failureMode: "The cost is spurious precision and the anxiety that follows it. You buy a lactate meter, or worse trust a wrist optical sensor's zone boundaries, and start treating a 5 bpm drift as a training error. Heart rate at a fixed metabolic intensity moves with heat, sleep, caffeine, hydration and cumulative fatigue by more than the width of the zone you are policing. You end up running slower than easy on hot days and calling it discipline, losing real aerobic volume to defend a boundary that was never validated as a boundary.",
  experiment: "Run your normal easy session and ignore the zone boundary entirely. Instead, apply the talk test: you should be able to speak a full sentence without gasping, and you should finish able to comfortably repeat the session tomorrow. Note the pace and heart rate this produces. Do it three more times across different conditions - hot, tired, well-slept - and look at the spread in heart rate at the same subjective effort. That spread is the honest measurement error on any zone boundary you were policing.",
  reflection: "How much of your training precision is measuring something real, and how much is measuring your instrument?",
  recall: {
    q: "Why is the zone 2 prescription filed as craft rather than as a single or replicated finding?",
    a: "Because the specific prescription has never been the manipulated variable in a controlled trial. The most-cited supporting work is a cross-sectional comparison of professional athletes, moderately active people and metabolic syndrome patients, measuring fat oxidation and lactate during submaximal exercise. It reports strong inverse correlations between fat oxidation and blood lactate (r = -0.92 to -0.98) and clear group differences, but nobody was assigned a training dose and nothing was compared against an alternative.\n\nThe training intensity distribution trials do not fill the gap, because polarised and pyramidal models both contain roughly 80% low-intensity work and differ in the arrangement of the hard 20%. None of them isolates time held strictly between the first and second thresholds. Craft is the honest label: decades of coaching practice, real physiological observations underneath, no controlled dose-finding trial. Filing it as single or replicated would imply a test that has not happened."
  },
  deepDive: "Design the controlled trial that would actually test the zone 2 prescription against a matched alternative, and tell me why it has not been run."
}
);
