/* Track: Ageing curves. Ordered foundational first.
 *
 * Drafted, then independently fact-checked against primary sources, then
 * revised against those verdicts. Entries whose central claim did not survive
 * the check were dropped rather than softened.
 */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "grip-strength-mortality-gradient",
  track: "ageing",
  level: "core",
  title: "Every five kilograms of lower grip strength maps to 16% higher all-cause mortality",
  source: "Leong et al., The Lancet 386(9990):266-273, 2015",
  evidence: "Prospective Urban Rural Epidemiology (PURE) study. 142,861 participants enrolled between January 2003 and December 2009, of whom 139,691 with known vital status were analysed, across 17 countries of varying income levels. Median follow-up 4.0 years (IQR 2.9-5.1). Per 5 kg lower grip strength: all-cause mortality HR 1.16 (95% CI 1.13-1.20, p<0.0001), cardiovascular mortality HR 1.17 (1.11-1.24, p<0.0001).",
  interval: { lo: 1.13, hi: 1.2, measure: "hazard ratio per 5 kg lower grip strength" },
  replication: "replicated",
  verifiedOn: "2026-08-08",
  gateIntro: "A hand dynamometer costs about forty dollars and takes ten seconds to use. Before reading on: how strong an association with death would you expect from something that crude, and would you expect it to hold across countries with completely different income levels and disease profiles?",
  cheat: "Treat grip as a reserve monitor, not a target: 5 kg lower is associated with 16% higher all-cause mortality, but training it moves the instrument.",
  idea: "Across 139,691 adults in 17 countries, each 5 kg decrement in grip strength was associated with 16% higher all-cause mortality and 17% higher cardiovascular mortality over a median 4 years. It is one of the most robust simple predictors in epidemiology. It is also a marker of systemic reserve rather than a lever you pull by training your hands.",
  why: "The reason a hand squeeze predicts death is that it is not really measuring hands. Grip strength integrates neuromuscular function, nutritional status, inflammatory burden, and the accumulated damage of everything else going on in the body. It is cheap, objective, hard to fake, and correlated with total lean mass and with the nervous system's ability to recruit it. That is why the association survives across 17 countries with wildly different baseline mortality.\n\nThe replication picture is strong. Beyond PURE, Marín-Jiménez et al. (BJSM, 2026) pooled 94 cohort studies and found that adults in the highest handgrip band had lower odds of cardiovascular disease (OR 0.73, 95% CI 0.67-0.80), dementia (0.62, 0.53-0.73), disability (0.57, 0.47-0.70), depression (0.70, 0.63-0.78) and Parkinson's disease (0.53, 0.31-0.91). The breadth of those outcomes is itself informative.\n\nThat breadth is also the warning. Grip strength cannot plausibly cause a lower risk of Parkinson's disease. When one measure predicts a dozen mechanistically unrelated conditions, it is functioning as an index of general physiological reserve. The correct inference is that things which raise your whole-body reserve will move both grip and mortality. The incorrect inference is that squeezing a device will move mortality.\n\nThe short follow-up matters too. A median of 4.0 years leaves plenty of room for reverse causation: people with undiagnosed disease at baseline have both weaker grips and higher near-term mortality. The gradient is real and the causal share of it is smaller than the hazard ratio implies.",
  failureMode: "You buy the dynamometer, train grip specifically with hangs and crushers, watch the number improve, and conclude you have moved the outcome. You have moved the instrument. Meanwhile the actual reserve the measurement was indexing - total lean mass, systemic health, whole-body strength - is unchanged, because you optimised a proxy instead of the thing it proxies. This is the same error as tuning a monitoring dashboard until the alerts stop firing.",
  experiment: "Measure it. Borrow or buy a dynamometer, take three attempts per hand, record the best. Compare against the age and sex norms. Then, and this is the part that matters, do not train grip. Retest in six months after a block of squats, deadlifts and consistent running, and see whether whole-body training moved the marker. That is the version of the experiment that tests reserve rather than technique.",
  reflection: "What metrics do you track at work that behave the same way - genuinely predictive, and completely useless as targets?",
  recall: {
    q: "What is the association between grip strength and all-cause mortality in PURE, and what is the correct causal reading of it?",
    a: "Per 5 kg lower grip strength, all-cause mortality HR 1.16 (95% CI 1.13-1.20) and cardiovascular mortality HR 1.17 (1.11-1.24), across 139,691 participants in 17 countries with a median follow-up of 4.0 years. It replicates broadly - a 94-cohort review by Marín-Jiménez et al. (BJSM, 2026) found the highest grip band associated with lower odds of cardiovascular disease, dementia, disability, depression and Parkinson's disease.\n\nThe correct reading is that grip strength indexes systemic physiological reserve, not that hand strength protects you. A measure that predicts mechanistically unrelated outcomes including Parkinson's disease is functioning as a general vitality marker. Training grip specifically moves the instrument, not the reserve. The short median follow-up also leaves substantial room for reverse causation from undiagnosed disease at baseline. Use it as a cheap monitor of whole-body trajectory, never as a target."
  },
  deepDive: "Explain how to tell a genuine causal lever from a proxy variable in observational health data, using grip strength as the worked example."
},
{
  id: "resistance-training-lean-mass-ageing",
  track: "ageing",
  level: "applied",
  title: "Resistance training buys an ageing adult about 1.1 kg of lean mass, and far more strength than that implies",
  source: "Peterson, Sen & Gordon, Medicine & Science in Sports & Exercise, 2011; companion strength meta-analysis Peterson, Rhea, Sen & Gordon, Ageing Research Reviews 9(3):226-237, 2010",
  evidence: "Meta-analysis of 49 studies, 1,328 participants aged 50 and over, pooled with random-effects models. Weighted pooled mean change in lean body mass 1.1 kg (95% CI 0.9-1.2). Heterogeneity high: Cochran Q 497.8 (p<0.01), I² 84%. No evidence of publication bias. Meta-regression: higher-volume interventions produced greater lean body mass increases (β = 0.05, p<0.01), and older participants gained less (β = -0.03, p=0.01). The companion meta-analysis by Peterson, Rhea, Sen & Gordon (Ageing Research Reviews, 2010), 47 studies and 1,079 participants, reported strength increases of 9.8 to 31.6 kg, with percentage changes of 29 ± 2, 24 ± 2, 33 ± 3 and 25 ± 2 for leg press, chest press, knee extension and lat pull respectively.",
  interval: { lo: 0.9, hi: 1.2, measure: "kg, pooled lean body mass change" },
  replication: "replicated",
  verifiedOn: "2026-08-08",
  gateIntro: "You are 45, you run, and you have decided to start lifting seriously to hold onto muscle as you age. Before reading on: over a typical intervention of a few months, how many kilograms of lean mass do you expect resistance training to add in adults over 50, and does that number change your reason for lifting?",
  cheat: "Past 50, judge lifting by strength, not mass: 1.1 kg of lean mass against 9.8 to 31.6 kg added on the lifts, so retest your maxes, not DEXA.",
  idea: "Pooled across 49 studies and 1,328 participants aged 50 and over, resistance training added 1.1 kg of lean body mass, with a tight interval of 0.9 to 1.2. Higher-volume programs did better and older participants did worse. If you are lifting to reverse age-related muscle loss by mass, the arithmetic is modest - which is a signal you are lifting for the wrong endpoint.",
  why: "One point one kilograms. Put that against the roughly 1% per year most people lose from midlife and do the arithmetic honestly. On total lean body mass of 55 to 60 kg, 1% is about 0.55 to 0.6 kg a year, so 1.1 kg is roughly two years of drift recovered. Reckoned against skeletal muscle mass alone, 25 to 30 kg, 1% is 0.25 to 0.3 kg a year and 1.1 kg buys four to five years. Two to five years, not a decade. The interval is narrow because 49 studies agree on direction, not because the effect is large.\n\nThe more important comparison is against what the same training does to strength. The companion meta-analysis of 47 studies and 1,079 participants found strength increases of 9.8 to 31.6 kg across leg press, chest press, knee extension and lat pull, with percentage changes of 24 to 33%. Strength moves in double-digit percentages while mass moves 1.1 kg. That gap is the actual finding, and it tells you what resistance training is for in an ageing body: neural drive, force production and function, not tissue accretion.\n\nThe two moderators are consistent with everything else in this literature. Volume helps (β = 0.05, p<0.01), age hurts (β = -0.03, p=0.01). Starting earlier is worth more than training harder later, which is unhelpful advice at any given moment and correct as a lifetime policy.\n\nThe I² of 84% deserves a mention. That is severe heterogeneity, meaning the studies disagree substantially about magnitude even while agreeing on direction. The tight confidence interval reflects the number of studies pooled, not consistency between them.",
  failureMode: "You set a body-composition target, train for it, gain 1.1 kg of lean mass over a hard year, and conclude that lifting does not work for you. So you stop - and give up the 24-33% strength gains that were the actual return, along with the bone loading and the fall resistance that come with them. Judging a strength intervention by a DEXA scan is measuring the wrong output, and the cost of the error is abandoning the intervention entirely.",
  experiment: "Pick a strength endpoint instead of a mass endpoint before your next block. Record a five-rep max on one lower-body lift and one upper-body lift today. Do not weigh yourself and do not book a body composition scan. Retest the same lifts in twelve weeks. Percentage change in those two numbers is the output this literature says you should expect to move, and it is the one that predicts whether you can still get off the floor at 80.",
  reflection: "When you judge whether a training block worked, which measurement do you reach for first, and is it the one the training actually changes?",
  recall: {
    q: "How much lean mass does resistance training add in adults over 50, and why is that the wrong number to judge the intervention by?",
    a: "1.1 kg (95% CI 0.9-1.2), pooled from 49 studies and 1,328 participants aged 50 and over, with high heterogeneity (I² = 84%). Higher-volume interventions gained more (β = 0.05, p<0.01) and older participants gained less (β = -0.03, p=0.01). At roughly 1% loss per year that is about two years of total lean body mass drift, or four to five years reckoned against skeletal muscle mass alone.\n\nIt is the wrong endpoint because the same training produces strength gains of 24 to 33% - between 9.8 and 31.6 kg across common lifts in the companion meta-analysis by Peterson, Rhea, Sen and Gordon (Ageing Research Reviews, 2010), 47 studies and 1,079 participants. Strength and function respond in double-digit percentages while mass barely moves, because much of the early adaptation is neural rather than structural. Function is also the endpoint that maps onto independence, fall resistance and quality of life in later decades. Judging resistance training by body composition guarantees you undervalue it and quit."
  },
  deepDive: "Explain why strength improves 24-33% while lean mass moves barely a kilogram in the same trials, and how much of that gap is neural adaptation."
},
{
  id: "exercise-falls-rate-reduction",
  track: "ageing",
  level: "applied",
  title: "Exercise cuts the rate of falls by 23%, and that is high-certainty evidence",
  source: "Sherrington et al., Cochrane Database of Systematic Reviews, 2019",
  evidence: "Cochrane systematic review of community-dwelling older people. The exercise-versus-control comparison spans 81 trials and 19,684 participants across all outcomes. For the rate of falls specifically: RaR 0.77 (95% CI 0.71-0.83), 12,981 participants, 59 studies, high-certainty evidence. Number of people experiencing one or more falls: RR 0.85 (95% CI 0.81-0.89), 13,518 participants, 63 studies, high-certainty evidence. Absolute effect approximately 195 fewer falls and 72 fewer fallers per 1,000 people over one year.",
  interval: { lo: 0.71, hi: 0.83, measure: "rate ratio, falls, exercise versus control" },
  replication: "replicated",
  verifiedOn: "2026-08-08",
  gateIntro: "Almost nothing in exercise science earns a high-certainty GRADE rating from Cochrane. Before reading on: name the exercise intervention and outcome pair you think has the strongest evidence base in the entire field, and guess the effect size.",
  cheat: "Running trains no balance, so add single-leg work to your lifting: exercise cut fall rate 23% and fallers 15% in older adults, high-certainty.",
  idea: "Pooling 59 randomised trials and 12,981 community-dwelling older adults, exercise reduced the rate of falls by 23%, and across 63 studies and 13,518 participants it reduced the number of people falling by 15%. Both are rated high-certainty by Cochrane. In absolute terms that is roughly 195 fewer falls per 1,000 people per year. This is among the best-evidenced exercise findings that exists.",
  why: "Take the certainty rating seriously. High-certainty in GRADE means further research is very unlikely to change the estimate. Most of what gets argued about in training - intensity distribution, set counts, supplement timing - sits at low or moderate certainty on much thinner data. Fifty-nine randomised trials with a tight pooled interval of 0.71 to 0.83 is a different class of evidence entirely. Note that the review's headline exercise-versus-control comparison covers 81 trials and 19,684 participants across all its outcomes, so if you see that larger number attached to the 0.77, it has been borrowed from a different row of the table.\n\nThe reason falls prevention matters more than it sounds is the downstream cascade. A hip fracture in your eighties is not an injury, it is a branch point: hospitalisation, deconditioning, loss of independence, and mortality risk that stays elevated for years afterwards. The intervention with the strongest evidence in exercise science targets the event that most reliably ends an active life.\n\nFor a runner in their forties this reads as somebody else's problem, which is the mistake. The trials recruit people who already have compromised balance and strength, and they recover 23%. The compounding is entirely in the other direction: balance and lower-limb strength built in midlife determine which side of the recruitment criteria you are on in thirty years. Running builds aerobic capacity magnificently and is close to useless for lateral stability and reactive balance.\n\nNote what the two estimates say together. Rate of falls drops more than the number of people falling, 23% versus 15%. Exercise does more to stop repeat fallers falling repeatedly than it does to convert fallers into non-fallers.",
  failureMode: "You bank thirty years of running, arrive at 70 with excellent cardiorespiratory fitness and no balance training whatsoever, and fall on a kerb. Running trains a narrow, sagittal-plane, highly practised movement pattern. It does not train recovering from an unexpected lateral perturbation, and it does not train single-leg stability under load. Aerobic fitness and fall resistance are separate accounts, and only one of them is being funded by your training.",
  experiment: "Test single-leg balance today. Stand on one leg, eyes closed, arms by your sides, near a wall. Time it. Then do the other leg. Under 10 seconds at any age under 60 is a signal, and the asymmetry between legs is more informative than the absolute number. If you find one, add single-leg work - split squats, step-downs, single-leg calf raises - to the strength session you are already doing. It costs nothing and it targets the account running does not credit.",
  reflection: "Which physical capacities are you accumulating for your seventies, and which are you assuming running covers?",
  recall: {
    q: "What did the Cochrane review find for exercise and falls in community-dwelling older people, and why should a mid-life runner care?",
    a: "Exercise of all types reduced the rate of falls by 23% (rate ratio 0.77, 95% CI 0.71-0.83) across 59 studies and 12,981 participants, and reduced the number of people experiencing one or more falls by 15% (RR 0.85, 0.81-0.89) across 63 studies and 13,518 participants. Both were rated high-certainty by Cochrane, which is rare in exercise science and means further research is unlikely to shift the estimate. The often-quoted 81 trials and 19,684 participants is the exercise-versus-control total across all outcomes, not the rate-of-falls analysis.\n\nA mid-life runner should care because the capacities these programs train - reactive balance, lateral stability, single-leg strength - are precisely the ones running does not develop. Running is a narrow sagittal-plane pattern and builds no defence against an unexpected perturbation. The trials recruit people already at risk and recover 23%. Whether you meet those recruitment criteria in thirty years is determined by what you build now, and the cost of adding it to an existing strength session is trivial."
  },
  deepDive: "Show me what the exercise programs in the highest-effect falls trials actually contained, session by session, and which components carry the effect."
},
{
  id: "lifelong-training-vo2max-advantage",
  track: "ageing",
  level: "advanced",
  title: "Lifelong trainers hold a large VO2max advantage, but that is not evidence that training bends the ageing curve",
  source: "Leslie, Luna & Gibson, International Journal of Exercise Science 16(3):620-637, 2023",
  evidence: "Systematic review of 10 studies meeting inclusion criteria, of which 5 entered meta-analysis, comparing older adults (65+) with 20 or more years of exercise training meeting ACSM weekly volume recommendations against sedentary peers. All included comparisons are cross-sectional. Cardiorespiratory fitness mean difference +11.36 mL·kg⁻¹·min⁻¹ (95% CI 5.63-17.09, p<0.01). Percent body fat mean difference -5.41% (95% CI -7.65 to -3.17, p<0.01). Higher volume of cardiorespiratory exercise beyond the minimum recommendations did not add further benefit. Resistance-trained older adults showed greater strength and lower body fat with cardiorespiratory fitness comparable to sedentary peers.",
  interval: { lo: 5.63, hi: 17.09, measure: "mL·kg⁻¹·min⁻¹, long-term trained minus sedentary" },
  replication: "single",
  verifiedOn: "2026-08-08",
  gateIntro: "You intend to still be running at 75. Before reading: do you believe lifelong training slows the rate at which VO2max declines with age, or does it simply start you from a higher point on the same slope? And what study design would be able to tell those two apart?",
  idea: "Older adults with 20 or more years of training carry a VO2max advantage of about 11 mL·kg⁻¹·min⁻¹ over sedentary peers, roughly three METs. The comparison is cross-sectional, drawn from five pooled studies, and it cannot distinguish a shifted intercept from a flattened slope. The advantage is real. The interpretation everyone attaches to it is not established.",
  why: "Two completely different models predict the same observation. In the shifted-intercept model, training raises your capacity and then age erodes it at the same rate as everyone else, so you stay 11 mL·kg⁻¹·min⁻¹ ahead and hit any given functional threshold later. In the flattened-slope model, training actually changes the rate of decline. A cross-sectional comparison of trained and sedentary 70-year-olds is compatible with both, and the popular version always asserts the second. Separating them needs repeated within-person measurement over decades, and none of the studies pooled here provide it.\n\nThe survivorship problem is severe and structural. To be in the trained group you had to keep training for 20 years, which requires not getting injured, not getting ill, not losing the joints and the motivation. The people whose ageing went badly left the exposure group. Comparing survivors of a 20-year filter against an unfiltered control will produce a large difference regardless of what training does.\n\nTwo other results in the same review are worth more than the headline and get quoted less. Volume beyond the ACSM minimum recommendations added no further cardiorespiratory benefit in these comparisons, which is an argument for defending a floor rather than chasing a ceiling. And resistance-trained older adults showed greater strength and lower body fat but cardiorespiratory fitness comparable to sedentary peers - the adaptations are specific, and lifting does not quietly buy you the aerobic account.\n\nFiled as single because the pooled estimate comes from one team's review of five cross-sectional studies, never independently reproduced. That a trained-versus-sedentary difference exists is unsurprising and obviously replicated. The 11.36 figure and the causal claim built on it are not.",
  failureMode: "You use the lifelong-athlete literature as reassurance that consistency alone will protect you, and let training volume decay through your fifties while still identifying as a runner. The cross-sectional design cannot tell you whether your own future capacity is being set by your age or by your volume, because nobody in it was measured twice. Treating an 11 mL·kg⁻¹·min⁻¹ group difference as a promise about your personal slope means you will read every decline as ageing, which is the one explanation you cannot act on.",
  experiment: "Find your training volume for the same 12-week window in each of the last five years - most platforms will export it. Plot weekly hours by year, then plot whatever capacity measure you have from the same years next to it. That pair of lines is repeated within-person data, which is exactly what every study in this review lacks. It will not settle intercept versus slope for the population, but it will tell you whether the input you control is drifting. Then set a floor for weekly hours you will defend regardless of how the year goes, and treat breaching it as the event worth reacting to.",
  reflection: "Over the last five years, has your training volume gone down, and if so did you decide that or did it just happen?",
  recall: {
    q: "Why can a cross-sectional comparison of lifelong-trained and sedentary older adults not show that training slows the ageing curve?",
    a: "Because a shifted intercept and a flattened slope predict the same snapshot. Long-term trained older adults show a cardiorespiratory fitness advantage of +11.36 mL·kg⁻¹·min⁻¹ (95% CI 5.63-17.09) over sedentary peers, pooled from five studies. That observation is equally consistent with training raising your starting capacity while age erodes it at the normal rate, and with training genuinely reducing the rate of decline. Only repeated within-person measurement can separate them, and every comparison in this review is cross-sectional.\n\nSurvivorship makes it worse. Membership of the trained group requires 20 years without the injury, illness or life disruption that ends a training habit, so the comparison is between survivors of a long filter and an unfiltered control. The review's less-quoted findings are the more usable ones: volume beyond the ACSM minimum added no further cardiorespiratory benefit, and resistance-trained older adults had cardiorespiratory fitness no better than sedentary peers. Defend a floor, and do not expect one mode of training to pay for another."
  },
  deepDive: "Design a study that could actually distinguish a shifted VO2max intercept from a flattened age-related slope, and tell me why the required design has rarely been run."
}
);
