/* Track: Sleep and measurement. Ordered foundational first.
 *
 * Drafted, then independently fact-checked against primary sources, then
 * revised against those verdicts. Entries whose central claim did not survive
 * the check were dropped rather than softened.
 */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "tracker-single-night-error",
  track: "sleep",
  level: "core",
  title: "Your watch's average sleep error is small and its single-night error is not",
  source: "Schyvens et al., Sleep Advances 6(2), 2025, zpaf021",
  evidence: "Single-night in-laboratory validation of six commercial wrist wearables against level-1 polysomnography, n = 62 adults (52 male, 10 female, mean age 46.0 +/- 12.6 years). Each participant wore only two to four of the six devices, so per-device n ran from 20 to 41 (Apple Watch Series 8 n = 20, Garmin Vivosmart 4 n = 25, Fitbit Sense n = 37, Fitbit Charge 5 n = 39, Whoop 4.0 n = 40, Withings Scanwatch n = 41). Sensitivity for detecting sleep ran 91.68% to 96.27%; specificity for detecting wake ran 29.39% to 52.15% (Garmin Vivosmart 4 lowest at 29.39%, Apple Watch Series 8 highest at 52.15%). All six devices overestimated total sleep time, by 6.31 to 39.87 minutes; four of the six reached significance. The Apple Watch Series 8 had the narrowest limits of agreement of the six at 115.9 minutes wide - bias +19.60 minutes, 95% limits of agreement -38.35 to +77.55 minutes - against 160 to 262 minutes for the other five.",
  interval: { lo: -38.35, hi: 77.55, measure: "minutes, 95% limits of agreement for Apple Watch Series 8 total sleep time against polysomnography, n = 20" },
  replication: "single",
  gateIntro: "You wear your usual wrist tracker into a sleep lab and get wired to polysomnography at the same time. Overnight, both systems score the same night. Before you read the number: on that one night, how far apart could the two totals be, in minutes, in each direction? Write down your range.",
  idea: "Wrist wearables are very good at recognising sleep and very bad at recognising wake. Across six current devices scored against polysomnography, sensitivity for sleep sat between roughly 92% and 96% while specificity for wake sat between roughly 29% and 52%, and all six overestimated total sleep time. That asymmetry means quiet wakefulness gets scored as sleep, and on a single night your total sleep time can be an hour out in either direction.",
  why: "The classifier is solving an easy problem badly. Inside a sleep opportunity window, most epochs really are sleep. A model that leans towards calling everything sleep therefore scores a high sensitivity almost for free, and the metric that would catch it out - specificity, the ability to correctly call a wake epoch wake - is the one that collapses. Between roughly 48% and 71% of wake epochs get labelled sleep across these six devices. The sensor stack makes this worse rather than better: an accelerometer sees a still body, and photoplethysmography sees a resting heart rate, and neither of those distinguishes lying awake in the dark from stage 2 sleep.\n\nEvery derived number inherits the error and some amplify it. Total sleep time is a count of sleep epochs, so misclassified wake inflates it directly - which is why all six devices here overestimated it. Sleep efficiency is total sleep time over time in bed, so it inflates in the same direction. Wake after sleep onset is the number that should expose the problem and it is precisely the number that gets suppressed. You cannot cross-check the device against itself, because all four headline figures are functions of the same faulty epoch labels.\n\nThe distinction that matters for you as an engineer is bias against limits of agreement. The device with the narrowest limits of agreement in this study had a mean bias of about twenty minutes, which reads as tolerable. But its 95% limits of agreement ran from thirty-eight minutes under to seventy-eight minutes over - a window 116 minutes wide, and that was the tightest of the six. The other five sat between 160 and 262 minutes wide. Bias is what survives averaging across many nights and many people. Limits of agreement are what you actually face tonight. Reporting the first and acting on the second is the same category error as quoting a p50 latency and paging on a p50 SLO.\n\nTwo caveats on how thin the ground is. That narrowest window rests on the twenty participants who happened to wear that device, not on the study's 62 - each person wore only two to four of the six, so every per-device figure here comes from a subsample. And the error is not evenly distributed across people. Someone who sleeps solidly has few wake epochs to misclassify, so the device looks accurate. Someone with fragmented sleep - a shift worker, a new parent, an athlete on the night before a race - has many, and every one of them is a chance for the device to add sleep that did not happen. The measurement degrades exactly in the population that most wants the measurement.",
  failureMode: "You wake up, see 5 h 42 m, and cut your long run to an easy 40 minutes. The lab-grade truth for that night might have been 5 h 04 m or 6 h 20 m, and the swing between those is larger than the difference between a good week and a bad one. Over a season you end up training a random number generator: the sessions you drop are not the sessions you were actually under-recovered for, and you develop a confident-feeling story about your sleep responsiveness built entirely on classifier noise.",
  experiment: "Export the last sixty nights of total sleep time from your device and compute the standard deviation. Then set that number next to the roughly 116-minute width of the limits-of-agreement window above - the narrowest of the six devices tested. If your night-to-night spread is smaller than the device's own single-night measurement error against polysomnography, you have no basis for treating any individual night as signal. Then do it properly for one week: note the clock time whenever you are actually awake in the night, and compare your log against what the device reported for wake after sleep onset.",
  reflection: "Which training or work decision have you actually changed on the basis of a single night's sleep score, and would you have made the same call if that number had arrived with a plus-or-minus one hour attached?",
  recall: {
    q: "A wrist tracker has about 94% sensitivity for sleep and about 40% specificity for wake. What does that combination do to your reported total sleep time, sleep efficiency and wake after sleep onset, and why does the group-level bias still look acceptable?",
    a: "High sensitivity with low specificity means the device correctly labels almost all real sleep as sleep, but labels roughly half to seven-tenths of real wake as sleep too. Total sleep time is inflated because misclassified wake epochs get added to the sleep count - every one of the six devices in this study overestimated it. Sleep efficiency is inflated for the same reason, since it is total sleep time over time in bed. Wake after sleep onset is deflated, because the wake it should be counting has been reassigned. All three numbers move together and none of them can be used to audit the others, since they are all functions of the same epoch labels.\n\nGroup-level bias looks acceptable because averaging across nights and people cancels a lot of the variance and leaves only the systematic component, which was between 6 and 40 minutes across these devices. That is the mean bias. What you face on any given night is the limits of agreement, which even for the tightest device in this study ran from thirty-eight minutes under to seventy-eight minutes over, on a subsample of twenty people. Reporting the bias and then acting on a single night is treating a population-level summary as an individual-level guarantee."
  },
  deepDive: "Show me the arithmetic of how sensitivity and specificity translate into total sleep time error when the base rate of sleep inside my sleep opportunity window is around 90%, and work it through with my own device's reported nightly numbers."
},
{
  id: "pooled-tracker-bias-is-not-staging",
  track: "sleep",
  level: "applied",
  title: "The pooled tracker-versus-lab difference covers four parameters and none of them is a sleep stage",
  source: "Lee et al., Journal of Clinical Sleep Medicine 21(3), 2025, 573-582",
  evidence: "Meta-analysis of 24 studies, 798 participants, comparing consumer wrist-worn sleep tracking devices with polysomnography. Four continuous parameters pooled: total sleep time, mean difference -16.854 minutes (95% CI -26.332 to -7.375); sleep efficiency, -4.691% (95% CI -7.079 to -2.302); sleep onset latency, 2.574 minutes (95% CI 0.606 to 4.542); wake after sleep onset, 13.255 minutes (95% CI 4.522 to 21.988). No publication bias was detected for total sleep time or sleep efficiency. Sleep staging accuracy is not among the pooled outcomes and the abstract does not define the sign convention for the mean differences.",
  interval: { lo: -26.332, hi: -7.375, measure: "minutes, pooled mean difference in total sleep time between consumer wrist devices and polysomnography" },
  replication: "replicated",
  gateIntro: "A meta-analysis pools two dozen validations of consumer wrist trackers against polysomnography. Before you look at it: how large do you expect the pooled disagreement on total sleep time to be, and how much do you expect that paper to tell you about how accurately your watch scores REM and deep sleep?",
  cheat: "Read tracker sleep totals as a monthly trend, about seventeen minutes off pooled, and ignore its REM and deep minutes: staging was never pooled.",
  idea: "The pooled disagreement on total sleep time is about seventeen minutes in magnitude, with a confidence interval that excludes zero. The paper covers four continuous parameters - total sleep time, sleep efficiency, sleep onset latency and wake after sleep onset - and stage accuracy is not one of them. Any claim about REM or deep sleep accuracy attributed to this meta-analysis is a number that is not in it.",
  why: "Seventeen minutes sounds like a rounding error and in one sense it is. Pooled across twenty-four studies and 798 people, the systematic component of the disagreement is small relative to how much your own sleep varies night to night. That is genuinely useful: for cohort-level work, for comparing a group before and after an intervention, or for tracking a trend over months, a bias of this size does not sink the analysis. It is what a mean difference is for.\n\nThe trap is what gets read into it. Sleep staging - the hypnogram, the REM and deep and light minutes your app puts on a coloured chart - is a categorical classification problem, judged by per-stage sensitivity, specificity and Cohen's kappa. It is a different question with different metrics and it was not pooled here. Those figures live in the device-level validation literature, where the picture is much worse: a six-device in-lab validation found wake specificity between about 29% and 52%. Citing a mean-difference meta-analysis as evidence about staging is the sleep-science equivalent of quoting a regression's R-squared to defend a classifier's precision.\n\nThere is a second thing to notice, and it is a lesson about reading papers rather than about sleep. The abstract reports signed mean differences but does not state whether the sign is device minus polysomnography or the reverse. All four signs are internally consistent under either reading. That means you cannot take the direction of the effect from the abstract alone, and anyone who tells you confidently that this paper shows devices overestimate or underestimate sleep is reading in a convention that is not stated there. Take the magnitude, take the interval, and get the direction from the device-level studies that state it - which, in the six-device validation above, is unambiguously overestimation.\n\nBoth things can be true and both matter. The systematic bias is small enough to ignore at the group level. The per-night error is large enough that nothing you read off the watch this morning is actionable. A parameter can be well calibrated on average and useless as an individual measurement, and confusing those two states is the most common mistake made with this class of device.",
  failureMode: "You cite this meta-analysis in a work-adjacent context - a health platform spec, a wellbeing dashboard, an internal argument about which wearable to standardise on - to justify a claim about staging accuracy. Someone checks. The number is not in the paper, the paper explicitly pools four continuous parameters, and now every other figure in your document is suspect. In personal terms the cost is smaller but the same shape: you optimise your evening around getting your deep sleep minutes up, on the basis of an output whose accuracy nobody has told you.",
  experiment: "Open your own device manufacturer's published validation white paper. Check which of the four continuous parameters they report, whether they report epoch-level specificity for wake, and whether they report per-stage kappa. Then check what sample size the staging figures are based on and whether the population resembles you. Most of the time the staging section either does not exist or is based on a few dozen laboratory nights.",
  reflection: "When you last quoted a study to support a decision, did you check that the specific number you needed was actually one of the study's outcomes, or did you check only that the study was about the right topic?",
  recall: {
    q: "Why can a sleep tracker meta-analysis report a pooled total sleep time difference of under twenty minutes while individual-night accuracy remains poor, and why does that meta-analysis say nothing about stage accuracy?",
    a: "A pooled mean difference estimates the systematic component of the error after averaging across studies and participants. Random error largely cancels in that average, so a small pooled bias is compatible with very large errors on any individual night. It is a statement about the centre of the error distribution, not its width, and the width is what determines whether the number is usable tonight.\n\nStage accuracy is a categorical classification problem measured by per-stage sensitivity, specificity and kappa, not by mean differences in minutes. A meta-analysis that pools total sleep time, sleep efficiency, sleep onset latency and wake after sleep onset has not evaluated staging at all. Those figures come from device-level validation studies, and when you go and read them the picture is considerably less flattering than the mean differences suggest."
  },
  deepDive: "Find the device-level validation studies for the specific wearable I own and tell me what they report for wake specificity and per-stage agreement, with sample sizes."
},
{
  id: "acute-sleep-loss-performance-cost",
  track: "sleep",
  level: "core",
  title: "Acute sleep loss costs roughly eight percent of physical performance and mostly in the afternoon",
  source: "Craven et al., Sports Medicine 52(11), 2022, 2669-2690",
  evidence: "Systematic review and meta-analysis of 69 publications, 959 participants, 89% male. Pooled mean change in exercise performance following acute sleep loss: -7.56% (95% CI -11.9 to -3.13, p = 0.001), I2 = 98.1%. Negative effects appeared across all exercise categories tested and were most pronounced for tasks performed in the afternoon, while morning tasks were largely unaffected. The pattern of sleep loss was an important moderator: consistent negative effects were observed only with deprivation and late-restriction protocols, not with early-restriction protocols, and performance declined by roughly 0.4% per additional hour awake before exercise.",
  interval: { lo: -11.9, hi: -3.13, measure: "% change in exercise performance following acute sleep loss" },
  replication: "replicated",
  gateIntro: "You get four hours instead of eight. That can happen two ways - you go to bed at your usual time and the alarm goes at 2am, or you stay up until 3am and get up as normal. Then you have a session or a race the next day. Before you read the pooled figure: what percentage of your physical performance do you expect to lose, does it matter which of those two nights you had, and does it matter whether you go at 7am or 4pm?",
  cheat: "After an early wake, move hard sessions to the morning: performance fell about 7.6%, 3% to 12%, and another 0.4% per hour awake.",
  idea: "Pooled across 69 studies and 959 participants, acute sleep loss reduced exercise performance by about 7.6%, with a confidence interval running from roughly 3% to 12%. The effect concentrated in afternoon tasks and scaled with time awake, at roughly 0.4% per hour before exercise. Consistent impairment showed up under total deprivation and under late restriction - sleep cut from the end of the night - but not under early restriction, where the night is shortened by a later bedtime.",
  why: "The time-of-day pattern is the most useful thing in this paper and it is the part people skip. If you are sleep deprived and you test at 7am, you are close to the point where you woke up and you have not yet accumulated much time-on-task. By late afternoon you have been awake far longer than you would have been on a normal day, and the homeostatic sleep pressure that has built up since waking is stacked on top of the deficit you started with. The paper puts a number on that: about 0.4% of performance per hour awake before exercise. The deficit does not sit still; it compounds through the day, and the same mechanism explains why late restriction - waking early, then being awake all day - hurt consistently while a later bedtime did not.\n\nThe magnitude is worth sitting with. Eight percent is enormous in racing terms. On a 40-minute 10k that is more than three minutes. That is not a taper-week refinement, it is the difference between a personal best and a bad day, and it comes from one night. Compare it against the effect sizes you see for supplements later in this corpus, where the honest numbers are one to three percent.\n\nThe interval is wide and the heterogeneity statistic tells you why that matters. I2 was 98.1%. Almost all of the variation between the pooled studies is genuine difference between them rather than sampling noise, which means the pooled figure is a summary across a family of different phenomena rather than an estimate of one quantity. Add that 89% of participants were male, that the protocols mixed total deprivation with partial restriction, and that most of it happened in laboratories, and 7.6% is a rough central tendency, not your personal expected loss.\n\nNote what this study does and does not tell you. It is about acute sleep loss - one or a few bad nights - not chronic mild restriction, which is the condition most working runners are actually in. Extrapolating a one-night effect to a habitual seven-hours-instead-of-eight pattern is an extra step the data do not support.",
  failureMode: "You race on four hours of sleep and read the result as a fitness verdict. You conclude your build was wrong, tear up a training plan that was working, and spend a block correcting a problem that was one night of sleep. The reverse costs just as much: you schedule the hardest session of the week for late afternoon after a night on call, then interpret the poor numbers as a signal to add more volume.",
  experiment: "Look back through the last three months of your training log and find every session that followed a night you know was short. Note the time of day for each, and note whether the night was short because you went to bed late or because you got up early. Compare the afternoon sessions against the morning ones. You will probably not have enough data for anything conclusive, and that is the point - the useful move is to start recording it, and to schedule your quality sessions before lunch on the days after a bad night rather than trying to push through at 5pm.",
  reflection: "In the last month, how many of your key sessions were scheduled in the afternoon following a night of short sleep, and what did you attribute the bad ones to at the time?",
  recall: {
    q: "Acute sleep loss reduced exercise performance by about 7.6% on average. Why did the effect concentrate in the afternoon, and what does the width of the confidence interval tell you about applying that number to yourself?",
    a: "By afternoon you have been awake far longer than a normal day would have you, and the meta-analysis found performance declining by roughly 0.4% for each additional hour awake before exercise. Early morning testing catches you close to wake time, before that pressure has built, so morning performance after a short night looks close to normal. The same logic explains the pattern moderator: consistent impairment appeared with total deprivation and with late restriction, where the night is cut short by an early wake and the day that follows is long, and not with early restriction, where the night is shortened by a later bedtime.\n\nThe interval from about -12% to -3% is wide, and I2 was 98.1%. At that level almost all of the between-study variation is real heterogeneity rather than sampling error, which makes the pooled point estimate close to uninterpretable as a single quantity. So 7.6% is a central tendency across a family of scenarios - different protocols, different sports, 89% male, mostly laboratory - not a personal prediction. And it says nothing about chronic mild restriction, which is a different exposure entirely."
  },
  deepDive: "Find the studies within this meta-analysis that used endurance running or cycling time trials specifically, and tell me what the effect looked like in that subset."
},
{
  id: "short-sleep-mortality-is-not-a-doubling",
  track: "sleep",
  level: "core",
  title: "Short sleep raises mortality risk by about a tenth, not by a multiple",
  source: "Cappuccio et al., Sleep 33(5), 2010, 585-592",
  evidence: "Systematic review and meta-analysis of prospective cohort studies: 16 studies with 27 cohort samples, 1,382,999 participants, 112,566 deaths, follow-up 4 to 25 years. Short sleep duration: pooled relative risk for all-cause mortality 1.12 (95% CI 1.06 to 1.18, p < 0.01), heterogeneity P = 0.02, with no evidence of publication bias. Long sleep duration: pooled relative risk 1.30 (95% CI 1.22 to 1.38, p < 0.0001), heterogeneity P < 0.0001.",
  interval: { lo: 1.06, hi: 1.18, measure: "relative risk of all-cause mortality, short versus normal sleep duration" },
  replication: "overclaimed",
  gateIntro: "The popular sleep literature tells you that short sleep is catastrophic for your lifespan. Before you look at the pooled epidemiology: by what factor do you think all-cause mortality risk rises for habitual short sleepers, and what do you expect the number to be for long sleepers?",
  idea: "Pooled across sixteen studies and nearly 1.4 million people, habitual short sleep carried a 12% higher relative risk of death, with a confidence interval from 6% to 18%. Long sleep carried a larger risk, 30% higher. The relationship is U-shaped and the short-sleep arm is the smaller of the two effects - which is close to the opposite of how the claim is usually sold.",
  why: "Take the popular version first. Matthew Walker's Why We Sleep asserts that the shorter your sleep the shorter your lifespan, and that sleeping under six or seven hours a night more than doubles your risk of cancer. Alexey Guzey's essay documenting factual and citation problems in that book, first published November 2019 and revised since, catalogues those and other claims and the sourcing behind them. You do not need to adjudicate that dispute, because the underlying epidemiology is public and it does not support a doubling of anything.\n\nA relative risk of 1.12 on all-cause mortality is a real effect on a population of 1.38 million and a marginal one for an individual. Whether it is worth anything to you depends entirely on your baseline hazard, which for a fit forty-something in Australia is low. Twelve percent more of a small number is a small number. This is the same arithmetic as an alert that fires 12% more often on a service that was already almost never failing.\n\nThe long-sleep arm is where the honest reading gets uncomfortable for everyone. Sleeping long carries a relative risk of 1.30, substantially larger than short sleep, and nobody seriously believes that lying in bed for nine hours kills you. The obvious explanation is reverse causation and confounding: undiagnosed illness, depression and frailty all lengthen sleep and all raise mortality. But that explanation is available symmetrically. Shift work, chronic pain, sleep apnoea and stress shorten sleep and also raise mortality. Once you accept the reverse-causation account for the larger arm you cannot refuse it for the smaller one.\n\nAnd the heterogeneity flag applies to both arms, including the one this entry is built on: P = 0.02 for short sleep, P < 0.0001 for long. Different cohorts, different definitions of short and long, different adjustment sets, different populations. When the studies disagree that much, the pooled point estimate is a summary of a disagreement rather than a measurement of a quantity - which is a reason to hold the 1.12 loosely too, not only the 1.30.",
  failureMode: "You internalise a dramatic version of this literature and it makes your sleep worse. Anxiety about not hitting eight hours is itself a well-recognised route into insomnia, and the mechanism has a name in the clinical literature - orthosomnia, when the pursuit of a perfect sleep metric degrades the sleep. The second cost is credibility: repeat the doubles-your-cancer-risk line at work or to a training group, get asked for the source, and find the source does not say it.",
  experiment: "Pick one dramatic sleep claim you currently believe - the eight-hour requirement, the cancer doubling, the WHO epidemic declaration - and spend twenty minutes tracing it to a primary source with a sample size and an interval. Not a book, not a podcast, not a review that cites a review. If you cannot land on a paper with numbers, that belief is decoration.",
  reflection: "Which health claim are you currently acting on where you have never seen the effect size, only the direction?",
  recall: {
    q: "Short sleep carries a pooled relative risk of 1.12 for all-cause mortality and long sleep carries 1.30. Why does that pattern undermine the popular reading rather than support it?",
    a: "If the causal story were simply that less sleep kills you, the risk should rise monotonically as sleep shortens. Instead the curve is U-shaped, and the arm with the larger effect is the long-sleep arm. Almost nobody argues that spending nine hours in bed is directly harmful, so the standard explanation for the long-sleep arm is reverse causation and confounding - illness, depression and frailty lengthen sleep and independently raise mortality.\n\nOnce you have accepted that explanation for the larger arm you cannot decline it for the smaller one. Shift work, sleep apnoea, chronic pain and stress shorten sleep and independently raise mortality. So the short-sleep relative risk of 1.12, already modest in absolute terms for a low-baseline-hazard individual and pooled across cohorts that disagreed significantly with each other, is at least partly a marker of the conditions that shorten sleep rather than a measure of what short sleep does. That is a very long way from doubling anything."
  },
  deepDive: "Trace the primary sources behind the specific claim that sleeping under six hours doubles cancer risk, and tell me what those sources actually report with sample sizes and intervals."
},
{
  id: "chronic-poor-sleep-injury-thin-signal",
  track: "sleep",
  level: "applied",
  title: "Poor sleep raises adolescent injury odds, on an interval that nearly reaches 1.0",
  source: "Gao et al., Journal of Pediatric Orthopaedics, 2019 (PMID 30888337)",
  evidence: "Systematic review and random-effects meta-analysis. 907 articles screened, 7 met inclusion criteria (studies published 1997 to 2017, athletes aged 19 or younger). Adolescents who chronically slept poorly had higher odds of sports or musculoskeletal injury: pooled odds ratio 1.58 (95% CI 1.05 to 2.37, p = 0.03). Five of the seven studies individually reported a significant association for chronic poor sleep. Two studies examined acute sleep loss; one found a significant association and one did not.",
  interval: { lo: 1.05, hi: 2.37, measure: "odds ratio for sports or musculoskeletal injury, chronic poor sleepers versus good sleepers" },
  replication: "replicated",
  gateIntro: "You have heard that poor sleep increases injury risk in athletes. Before you see the pooled figure: how much higher do you think the odds of injury are for chronically poor sleepers, and how confident do you think the evidence base is - how many studies, and in what population?",
  cheat: "Keep the 1.58 injury odds for chronic poor sleepers out of adult planning: 7 studies, athletes 19 or younger, and a 1.05 lower bound.",
  idea: "Seven studies in adolescent athletes pool to an odds ratio of 1.58 for injury among chronic poor sleepers. The lower bound of the confidence interval is 1.05, which is close enough to no effect that a single additional null study could move the conclusion. It is a real signal and a thin one, and the population is teenagers, not adult recreational runners.",
  why: "Start with what would have to be true for this to be a clean finding. You would want objectively measured sleep, prospectively collected injury data with a hard case definition, and adjustment for training exposure. What you get instead is mostly self-reported sleep from questionnaires, injury definitions that vary between studies, and seven studies total. The pooled estimate is doing a lot of work on a small and heterogeneous base.\n\nThe confounding is structural and it points in the direction of the observed result. In adolescent athletes, the ones sleeping badly are disproportionately the ones training hardest, travelling to competition, carrying the heaviest school load, and specialising early in a single sport. Every one of those independently raises injury risk. Sleep is a marker for a lifestyle, and separating the marker from the mechanism needs a design these studies do not have.\n\nCausation can run backwards here too, and it does so more plausibly than usual. Pain wakes people up. An athlete carrying an early-stage bone stress injury or a grumpy tendon sleeps worse because of it, and if the sleep questionnaire is administered anywhere near the injury window you have measured the consequence and called it the cause. The prospective studies mitigate this but do not eliminate it, because injuries in runners rarely announce themselves on a single day.\n\nThen there is the transfer problem, which is yours specifically. These are athletes aged nineteen and under, in mostly team and school sports, with adolescent physiology and adolescent sleep architecture. You are an adult recreational distance runner. The finding may well transfer. Nothing in this paper demonstrates that it does.",
  failureMode: "You treat 1.58 as though it were a well-established multiplier and start making training decisions off your sleep score, which - per the tracker entries in this track - you cannot measure accurately on a single night anyway. Two shaky layers stacked: an odds ratio whose interval nearly includes 1, applied to a measurement whose single-night error exceeds an hour. The output is confident-feeling and worthless. The opposite failure is cheaper but still real: dismissing sleep entirely because the interval is thin, when the point estimate is not small and the mechanism is plausible.",
  experiment: "Go through your last twelve months and list every running injury or niggle that cost you more than a week. For each, write down what your sleep was like in the four weeks before onset - from your log or your calendar, not your memory. Then write down your weekly volume, your travel, and your work load over the same window. If sleep never separates from the other three, you have learned the actual shape of the problem in your own data.",
  reflection: "When your sleep is bad, what else is true about that period - and could that other thing be the injury risk you are attributing to sleep?",
  recall: {
    q: "A pooled odds ratio of 1.58 with a lower bound of 1.05 from seven studies of adolescent athletes. What are the two strongest reasons not to act on this as though it were an established causal effect in an adult runner?",
    a: "The first is confounding by the things that co-occur with poor sleep. In young athletes, bad sleep travels with heavy training, competition travel, school load and early sport specialisation, and each of those independently raises injury risk. Sleep is functioning as a marker for a demanding lifestyle, and the study designs cannot separate the marker from any mechanism. Reverse causation compounds this, because a developing injury disturbs sleep before it becomes a diagnosis.\n\nThe second is that the evidence base is seven studies with mostly self-reported sleep and inconsistent injury definitions, in a population aged nineteen and under. The lower confidence bound of 1.05 means the pooled result is one null study away from crossing the null. Transferring that to an adult recreational runner adds an extrapolation the paper never tested. The mechanism is plausible and the point estimate is not small, so the honest position is to take sleep seriously without pretending a number this fragile licenses a specific decision."
  },
  deepDive: "Find whether any prospective study in adult recreational distance runners has tested sleep as an injury risk factor with objective sleep measurement, and tell me what it found."
},
{
  id: "sleep-regularity-versus-duration",
  track: "sleep",
  level: "applied",
  title: "Sleep regularity tracks mortality at least as strongly as sleep duration does",
  source: "Windred et al., Sleep 47(1), 2024, zsad253",
  evidence: "Prospective cohort using UK Biobank accelerometry: 60,977 participants (mean age 62.8 +/- 7.8 years, 55.0% female), over 10 million hours of recording, median Sleep Regularity Index 81.0 (IQR 73.8 to 86.3). 1,859 deaths over a mean 6.30 +/- 0.83 years of follow-up. All-cause mortality, most regular versus least regular SRI quintile: fully adjusted HR 0.70 (95% CI 0.59 to 0.83); minimally adjusted HR 0.52 (95% CI 0.45 to 0.60). Sleep duration, longest versus shortest quintile: fully adjusted HR 0.76 (95% CI 0.65 to 0.89). Hierarchical model comparison found that adding sleep duration to an SRI-only model did not improve fit (likelihood ratio test, minimally adjusted X2(4) = 6.88, p = 0.14; fully adjusted X2(4) = 5.94, p = 0.20), which the authors take as evidence that duration explains no mortality risk beyond regularity.",
  interval: { lo: 0.59, hi: 0.83, measure: "hazard ratio for all-cause mortality, most versus least regular sleep quintile, fully adjusted" },
  replication: "single",
  gateIntro: "Two people both average seven hours a night. One goes to bed within twenty minutes of the same time every night. The other swings by three hours between weekdays and weekends. Before you read on: do you expect their mortality risk to differ, and if so, which of the two variables - the average or the consistency - would you bet is the stronger predictor?",
  idea: "In 60,977 UK Biobank participants with accelerometer-measured sleep, the most regular sleepers had a fully adjusted hazard ratio for all-cause mortality of 0.70 against the least regular. The equivalent comparison for sleep duration was 0.76. The two intervals overlap across most of their range, and the paper's case for regularity being the stronger predictor rests on a non-significant likelihood ratio test, so the defensible claim is that regularity matters at least as much as duration, not that it beats it.",
  why: "Regularity is measured here by the Sleep Regularity Index, which is the probability that you are in the same state - asleep or awake - at the same clock time on two consecutive days. It is a percentage, not a duration, and it captures something duration cannot: the alignment between your sleep and your circadian system. A person averaging seven hours with a three-hour weekend shift is asking their internal clock to re-entrain twice a week, which is a small dose of jet lag on a repeating schedule.\n\nThe headline framing of this paper is that regularity is the stronger predictor, and the abstract says so. The evidence offered for it is a hierarchical model comparison: adding sleep duration to an SRI-only model did not improve fit, at p = 0.14 minimally adjusted and p = 0.20 fully adjusted. The authors read that as duration contributing nothing beyond regularity. Read it the way you would read any non-significant test - failing to reject a null is weak evidence for the null, and it is weakest exactly where power is limited, which with 1,859 deaths spread across quintiles it is. Then set it against the confidence intervals: 0.59 to 0.83 for regularity, 0.65 to 0.89 for duration, overlapping across most of their range. The point estimate for regularity is lower. That is suggestive, and it is not the demonstration the title implies.\n\nThe gap between the minimally adjusted hazard ratio of 0.52 and the fully adjusted 0.70 is the most informative number in the study. Roughly a third of the crude association vanished once sociodemographic, lifestyle and health factors were added. That is a large sensitivity to the adjustment set in a single observational cohort, and it tells you how much of what remains might be absorbed by covariates nobody measured. UK Biobank participants are also healthier, whiter and more affluent than the general population, and the cohort's mean age here is sixty-three.\n\nWhat makes this worth knowing anyway is that regularity is actionable in a way duration often is not. You can rarely decide to sleep an extra hour. You can almost always decide to get up at the same time. And it is a variable your wearable measures far more robustly than the ones it gets wrong - bedtime and wake time are clock events, not epoch classifications, so they do not inherit the sleep-wake specificity problem that ruins total sleep time.",
  failureMode: "You spend your effort chasing total sleep time - the metric your device measures worst and you control least - while your bedtime swings by two hours across the week and your long-run mornings are on a different schedule to your work mornings. The predictable outcome is that Saturday's key session lands in the middle of a self-inflicted circadian shift, and you attribute the flat legs to training load.",
  experiment: "Pull thirty days of your device's bed time and wake time - just the clock times, not the sleep scores, because those are the numbers it gets right. Compute the standard deviation of each in minutes. If either exceeds about sixty minutes, you have a regularity problem that no amount of chasing a nightly sleep score will fix. Fix wake time first: it is the anchor the circadian system actually uses.",
  reflection: "What is the actual spread between your earliest and latest wake time across a normal week, and which of those days do you schedule your hardest running on?",
  recall: {
    q: "Regularity gave a hazard ratio of 0.70 and duration 0.76 for all-cause mortality in the same cohort. Why is 'regularity beats duration' an overstatement, and why is regularity still the better thing for you to act on?",
    a: "The two confidence intervals - 0.59 to 0.83 and 0.65 to 0.89 - overlap across most of their range. The paper's own argument for superiority is a hierarchical model comparison showing that adding duration to an SRI-only model does not improve fit, at p = 0.14 and p = 0.20. That is a failure to reject a null, not a demonstration of one, and it is a weak form of evidence for the claim being made. This is also a single observational cohort, and the fact that the hazard ratio moved from 0.52 to 0.70 when the adjustment set was expanded shows how much of the association is sensitive to which covariates you include.\n\nRegularity is still the better target for two practical reasons. It is controllable in a way duration is not - you cannot decide to fall asleep an hour earlier, but you can decide to get up at the same time. And it is measured from clock events rather than epoch classification, so it does not inherit the sleep-wake specificity failure that makes your device's total sleep time unreliable on any single night. You are acting on a number your watch actually gets right."
  },
  deepDive: "Explain how the Sleep Regularity Index is computed from accelerometry and show me how to calculate my own from thirty days of bed and wake times."
}
);
