/* Track: Load, recovery and injury. Ordered foundational first.
 *
 * Drafted, then independently fact-checked against primary sources, then
 * revised against those verdicts. Entries whose central claim did not survive
 * the check were dropped rather than softened.
 */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "acwr-random-denominator",
  track: "load",
  level: "core",
  title: "The acute:chronic workload ratio predicts injury just as well when you divide by random numbers",
  source: "Impellizzeri et al., Sports Medicine, 2021 (PMID 33332011)",
  evidence: "Reanalysis of an existing injury dataset. The acute:chronic workload ratio was associated with injury at OR 2.45 (95% CI 1.28 to 4.71). Replacing chronic load in the denominator with a fixed constant (1510, the average chronic load) gave OR 1.95 (95% CI 1.18 to 3.52). Replacing it with random numbers gave odds ratios ranging from 1.16 to 2.07. Neither the ratio nor acute load alone conferred meaningful discrimination over an intercept-only model, with c-statistics of 0.574 and 0.544 against a baseline of 0.5.",
  interval: { lo: 1.28, hi: 4.71, measure: "odds ratio for injury per unit of acute:chronic workload ratio" },
  replication: "overclaimed",
  gateIntro: "A widely used training metric divides your recent workload by your longer-term workload and flags you when the ratio goes outside a safe range. Before you read on: if a researcher swapped the denominator for a randomly generated number, what do you expect would happen to the metric's association with injury?",
  idea: "When researchers replaced the chronic workload in the denominator with a fixed constant, and then with random numbers, the association with injury largely survived. The predictive contribution comes from the numerator - acute load - not from the ratio. And even acute load barely discriminates: a c-statistic of 0.574 against a coin flip's 0.5.",
  why: "The mechanism is mathematical coupling and rescaling. Dividing acute load by chronic load produces a variable that is still dominated by acute load, because the denominator varies far less than the numerator across athletes. What the division does is shrink the variance and inflate the coefficient on the resulting variable, so the odds ratio looks impressive. The random-denominator test is the cleanest possible demonstration: if a variable's predictive power survives replacing half of it with noise, that half was not doing the work.\n\nThe c-statistic is the part that should stop you. 0.574 means that if you pick one athlete who got injured and one who did not, the metric ranks them correctly about 57% of the time. A coin does 50%. In any other domain you would not ship a classifier with that discrimination, let alone build a squad management policy on it. An odds ratio of 2.45 and a c-statistic of 0.574 are not in tension - a variable can shift group-level odds meaningfully while being close to useless at ranking individuals - and confusing those two is precisely how this metric spread.\n\nThe deeper issue is that the ratio was never a mechanism, it was a summary statistic that got promoted to a theory. Once it became a theory, the safe-zone thresholds followed, and thresholds get enforced. This is a familiar shape if you have watched a dashboard metric become a target: the number was descriptive, someone drew a line on it, and the line acquired more authority than the measurement ever had.\n\nFile this as overclaimed rather than failed. The underlying signal is real - acute load carries some information about injury risk, and training a lot more than usual is genuinely riskier than not. What is overclaimed is the ratio as a construct. It is redundant with the acute load you already measured, and dressing it up as a ratio buys you nothing but a bigger-looking coefficient.",
  failureMode: "You build a personal ACWR out of your Strava or Garmin data, set a red zone, and start skipping quality sessions whenever the number goes above it. Because the metric is mostly acute load with extra variance suppression, what you have actually built is a rule that punishes any hard week - including the ones that were the point of the block. The season-level cost is a training plan whose peaks get sanded off by a metric with 57% discrimination, and a persistent belief that you are managing risk.",
  experiment: "If you already track an ACWR-style number, recompute it for the last six months with the denominator replaced by a single constant - your average weekly load over the period. Plot both series. If they track each other closely, you have reproduced the paper's finding on your own data and you now know the denominator was decoration. Then look at where your actual niggles landed relative to both.",
  reflection: "Which training metric are you currently treating as a mechanism when it is really a rescaling of a simpler number you already had?",
  recall: {
    q: "An odds ratio of 2.45 and a c-statistic of 0.574 for the same variable. Explain why those are consistent, and what the random-denominator experiment demonstrates.",
    a: "An odds ratio describes how much the odds of the outcome shift per unit of the predictor across a population. A c-statistic describes how well the predictor ranks individuals - the probability that a randomly chosen case scores higher than a randomly chosen non-case. A variable can move population odds appreciably while overlapping so heavily between cases and non-cases that it barely separates them. 0.574 against a baseline of 0.5 means the metric is only slightly better than chance at telling an injured athlete from an uninjured one, which is the task you actually want it for.\n\nThe random-denominator experiment isolates where the predictive information lives. Replacing chronic workload with a constant, and then with random numbers, left the association largely intact, so the denominator was contributing nothing. The ratio is a rescaling of acute load: dividing by a low-variance denominator shrinks the variable's variance and inflates its coefficient, making the odds ratio look larger without adding information. The construct is redundant with the acute load already being measured."
  },
  deepDive: "Walk me through the mathematical coupling argument against ratio variables in general, with a worked example using training load numbers."
},
{
  id: "weekly-progression-rule-origins",
  track: "load",
  level: "applied",
  title: "The weekly progression rule rests on a hazard ratio whose interval includes no effect",
  source: "Nielsen et al., Journal of Orthopaedic & Sports Physical Therapy, 2014 (PMID 25155475)",
  evidence: "Prospective cohort of 874 novice runners with GPS-measured running distance followed for one year; 202 sustained a running-related injury. Runners were grouped by weekly distance progression over a two-week period: less than 10% (or regression), 10 to 30%, and more than 30%. Across all injury types, Cox regression found no significant difference between the three groups. For distance-related injuries specifically (patellofemoral pain, iliotibial band syndrome, medial tibial stress syndrome and others), progressing more than 30% versus less than 10% gave a hazard ratio of 1.59 (95% CI 0.96 to 2.66, p = 0.07).",
  interval: { lo: 0.96, hi: 2.66, measure: "hazard ratio for distance-related running injury, >30% versus <10% weekly distance progression" },
  replication: "overclaimed",
  gateIntro: "You have almost certainly been told not to increase your weekly mileage by more than some fixed percentage. Before you read on: what do you think the primary evidence for that rule looks like - what study design, what sample size, and was the key result statistically significant?",
  idea: "The most-cited cohort behind weekly progression limits followed 874 novice runners for a year. Across all injury types there was no significant difference between progression groups. The one result that supports the rule - a hazard ratio of 1.59 for distance-related injuries at over 30% progression - has a confidence interval running from 0.96 to 2.66 and a p value of 0.07. The interval includes no effect.",
  why: "Look at what had to happen for this result to exist. The overall analysis was null. The signal appears only after splitting injuries into distance-related and not-distance-related subtypes, which is a defensible biological hypothesis and also a subgroup analysis. The subgroup that supports the rule returns p = 0.07. None of this makes the finding wrong. It makes it a hypothesis with supportive but inconclusive data, which is a very different object from a rule you follow.\n\nThe hazard ratio itself is not small. 1.59 is a substantial effect if real, and the lower bound of 0.96 is very close to 1 rather than deep in null territory. The honest reading is not that progression does not matter - it is that this study, with 874 runners and 202 injuries over a year, was not able to establish that it does. That is a statement about the power and design of the evidence, not a refutation.\n\nWhat got built on top is the problem. The specific thresholds - 10%, 30% - are cut points the researchers chose to define exposure groups. They are not a discovered biological boundary. Yet they now appear in coaching guidance, running apps and physiotherapy advice as though somebody had found the line where tissue tolerance breaks. A cut point chosen to make a cohort analysis tractable has been reified into a physiological law.\n\nThere is also a definitional issue that the same research group has written about extensively: what counts as workload, and how many workload exposures a study actually captures. Weekly distance ignores pace, surface, elevation, cumulative history, and the interval between sessions. A 30% increase from 20 km to 26 km on flat road is not the same exposure as 30% from 60 km to 78 km with two of those weeks having a hard session. The exposure variable is coarse enough that a null result would not be surprising even if the underlying mechanism were real.",
  failureMode: "You hold yourself to a hard 10% ceiling and it costs you in both directions. Coming back from a break, the ceiling makes your rebuild take twice as long as it needs to, because a return to a distance you comfortably ran two months ago is not the same exposure as a first-time increase. Going the other way, you hit 29% and feel safe, when the actual risk in that week was the two hill sessions and the new shoes, neither of which the rule can see.",
  experiment: "Compute your actual week-on-week distance change for the last twenty weeks and mark the weeks where you exceeded 30%. Then mark the weeks where something hurt. Now do it again but change the exposure variable - use time on feet, or vertical metres, or number of hard sessions. Whether the picture changes tells you how much your chosen workload metric is doing versus the arithmetic.",
  reflection: "Which of your training rules do you follow as a physiological fact when it is actually a cut point somebody chose to make an analysis tractable?",
  recall: {
    q: "Why is a hazard ratio of 1.59 with a 95% CI of 0.96 to 2.66 not an adequate basis for a hard weekly progression rule, and what is the wrong conclusion to draw from that?",
    a: "The interval includes 1, so the data are compatible with no effect, and the p value of 0.07 comes from a subgroup analysis after the all-injury comparison returned nothing. The specific thresholds of 10% and 30% were exposure-group cut points chosen by the researchers, not a discovered boundary in tissue tolerance. Treating them as a physiological limit gives a coarse statistical convention more authority than the underlying result carries.\n\nThe wrong conclusion is that progression does not matter. A point estimate of 1.59 with a lower bound of 0.96 is a study that failed to establish an effect, not a study that ruled one out. The correct reading is that weekly distance is a coarse proxy for the exposure that actually loads tissue - it ignores pace, surface, elevation, session spacing and training history - and that a cohort of 874 runners with 202 injuries was not enough to resolve the question with that proxy."
  },
  deepDive: "Find out how weekly running distance compares with other workload definitions as an injury predictor, and tell me which exposure variables have actually been tested prospectively."
},
{
  id: "volume-versus-intensity-unresolved",
  track: "load",
  level: "applied",
  title: "A randomised trial could not separate progressing volume from progressing intensity",
  source: "Ramskov et al., BMJ Open Sport & Exercise Medicine, 2018 (PMID 29527322)",
  evidence: "Randomised trial (Run Clever). 839 healthy recreational runners were randomised at baseline to a running-intensity progression schedule or a running-volume progression schedule. After an initial 8-week preconditioning phase, 447 participants entered the 16-week training period, with GPS data collection and real-time individualised feedback. 80 runners sustained a running-related injury following preconditioning (36 intensity, 44 volume). Cumulative incidence in the volume group: 4.6% at 2 weeks, 8.2% at 4 weeks, 13.2% at 8 weeks, 28.0% at 16 weeks. Risk differences between schedules: +2.9% at 2 weeks (95% CI -5.7 to 11.6), +1.8% at 4 weeks (95% CI -9.1 to 12.8), -4.7% at 8 weeks (95% CI -17.5 to 8.1), -14.0% at 16 weeks (95% CI -36.9 to 8.9).",
  interval: { lo: -36.9, hi: 8.9, measure: "percentage-point risk difference in running-related injury at 16 weeks, intensity progression versus volume progression" },
  replication: "single",
  gateIntro: "Two training schedules, one progressing weekly volume and one progressing intensity, randomised across 839 recreational runners, of whom 447 reach the sixteen-week training period. Before you read on: which do you expect to injure more runners, and how confident do you expect a trial of that size to be about the answer?",
  idea: "The trial found a risk difference of -14.0 percentage points at sixteen weeks, favouring the intensity schedule, with a confidence interval running from -36.9 to +8.9. That interval spans a large benefit, no difference, and a moderate harm. The conclusion is not that the two are equivalent - it is that the trial could not tell them apart.",
  why: "Read the interval as a range of futures the data are compatible with, not as a failed significance test. A risk difference of -36.9 percentage points would be one of the largest injury prevention effects ever measured in running. A risk difference of +8.9 would mean the intensity schedule is meaningfully worse. Both are inside the interval. The trial randomised 839 runners, 447 of whom reached the training period, and observed 80 injuries after preconditioning, and 80 events is simply not enough to resolve a question of this shape. This is the sports injury field's structural problem: the trials that get run are large by the standards of their funding and small by the standards of the question.\n\nThen there is compliance, and it is worse than you would guess. The same research group later documented adherence across eight large running injury trials. In Run Clever, 0 of 839 runners were fully compliant with the intervention at 24-week follow-up. In the companion ProjectRun21 study, 0 of 612 were fully compliant at 14 weeks. Zero. By contrast, shoe-based interventions in the same review achieved 68% to 90% compliance, because wearing a shoe is a thing you can comply with and following a prescribed weekly progression for four months is not.\n\nThat compliance figure reframes what the trial measured. An intention-to-treat analysis of two schedules that nobody followed is an estimate of the effect of being assigned to a schedule, which is a real and policy-relevant quantity but not the one you want. You want to know what happens if you progress intensity rather than volume. The trial can tell you what happens if someone hands you a plan to do that.\n\nThe practical implication is not nihilism. It is that the volume-versus-intensity question, which occupies an enormous amount of coaching argument, has one randomised trial behind it and that trial is uninformative. Anyone stating the answer confidently is stating a preference. Hold yours loosely.",
  failureMode: "You commit hard to one side of this - all your progression goes into volume, or all of it into intensity - on the strength of a coach's conviction or a podcast, and structure a year of training around it. If the effect exists at all it is smaller than the noise you can perceive in your own training, so you will never get feedback that corrects you. The cost is not a specific injury, it is a year spent optimising a variable that the best available evidence cannot resolve while ignoring the ones you can control, like session spacing and whether you actually take easy days easy.",
  experiment: "Look at your own last twelve months and classify each block by what you were progressing: distance, intensity, or both at once. The last category is usually the biggest and is the actual finding. Then pick one block ahead and progress only one of the two, deliberately, and write down beforehand what you expect to notice. The value is not in the result, it is in discovering how hard it is to comply with your own plan for even eight weeks - which is the same finding the trial made.",
  reflection: "When you last increased both your weekly volume and your session intensity in the same block, what were you going to attribute an injury to if one had happened?",
  recall: {
    q: "A trial reports a 16-week risk difference of -14.0 percentage points with a 95% CI of -36.9 to +8.9, and 0 of 839 runners were fully compliant with the intervention. What can and cannot be concluded?",
    a: "The interval is compatible with a very large benefit of the intensity schedule, with no difference at all, and with a moderate harm. With 839 randomised, 447 reaching the sixteen-week training period and 80 injury events, the trial did not have the resolution to separate these. The correct conclusion is that the question is unresolved, not that the two schedules are equivalent - an inconclusive trial is not evidence of no difference, and reporting it as such is one of the most common errors in reading this literature.\n\nThe compliance figure changes what the estimate even means. With zero runners fully adherent, an intention-to-treat analysis estimates the effect of being assigned a progression schedule, not the effect of following one. That is a legitimate and policy-relevant quantity, but it is not the biological question. It also explains something structural: interventions people can actually comply with, such as wearing a particular shoe, achieved 68% to 90% adherence in the same set of trials, which is why those trials can answer their questions and progression trials cannot."
  },
  deepDive: "Estimate how many runners and how many injury events a trial would need to detect a 5 percentage point difference in injury risk between two progression schedules, and tell me whether any trial in the field has come close."
},
{
  id: "mtss-risk-factors-are-tiny",
  track: "load",
  level: "advanced",
  title: "The measurable risk factors for shin splints separate cases from controls by almost nothing",
  source: "Hamstra-Wright et al., British Journal of Sports Medicine, 2015 (PMID 25185588)",
  evidence: "Systematic review and meta-analysis of 21 studies in runners and military personnel, with 9 risk factors qualifying for pooling. Medial tibial stress syndrome cases versus controls: BMI weighted mean difference 0.79 kg/m2 (95% CI 0.38 to 1.20, p < 0.001); navicular drop 1.19 mm (95% CI 0.54 to 1.84, p < 0.001); ankle plantarflexion range of motion 5.94 degrees (95% CI 3.65 to 8.24, p < 0.001); hip external rotation range of motion 3.95 degrees (95% CI 1.78 to 6.13, p < 0.001). Ankle dorsiflexion range and quadriceps angle were clearly not risk factors.",
  interval: { lo: 0.38, hi: 1.2, measure: "kg/m2, weighted mean difference in BMI between medial tibial stress syndrome cases and controls" },
  replication: "replicated",
  gateIntro: "You go to a physio with shin pain and get measured: BMI, arch drop, ankle range, hip rotation. Before you read on: how different do you expect those measurements to be, on average, between people who get medial tibial stress syndrome and people who do not?",
  idea: "Pooled across 21 studies, the statistically significant risk factors for medial tibial stress syndrome separate cases from controls by 0.79 kg/m2 of BMI, 1.19 mm of navicular drop, 5.94 degrees of ankle plantarflexion and 3.95 degrees of hip external rotation. Every one of those intervals excludes zero. Every one of them is also far too small to tell one runner apart from another, because the case and control distributions sit almost on top of each other.",
  why: "Take BMI first, because it is the one where the objection is purely distributional. A weighted mean difference of 0.79 kg/m2 is measured perfectly well - height and weight are not the problem. The problem is that BMI in a running population has a standard deviation of several units, so a 0.79 gap between group means describes two distributions that are nearly identical in shape and position. This is the difference between a risk factor and a screening test, and it is the whole point of the entry. Two distributions can have different means and overlap almost completely. If you screened runners on BMI you would misclassify almost everyone, in exactly the way a classifier with a c-statistic near 0.5 does.\n\nNavicular drop adds a second problem on top of the first. It is measured with a ruler against a bony landmark on a standing foot, by hand, on a person who is shifting their weight. Hamstra-Wright et al. do not report the reliability of that measurement, so treat this as an inference rather than a finding from the paper - but a pooled group difference of 1.19 mm is the sort of magnitude a hand-held ruler struggles to resolve. Whatever the exact reliability figure turns out to be, a single clinical measurement cannot place you meaningfully on a scale where the entire case-control difference is about a millimetre.\n\nThe negative results deserve more attention than they get. Ankle dorsiflexion range and quadriceps angle were clearly not risk factors, and both have been the target of years of clinical intervention. A field where the null results are this clean and the positive results are this small is telling you something about the underlying model: static anatomical measurements taken at rest are not capturing what loads a tibia during a run.\n\nWhat this does not mean is that the paper is useless. It is a well-executed synthesis and it correctly reports small effects as small. The problem is downstream, where a statistically significant pooled difference becomes clinical guidance to correct navicular drop, and the effect size never travels with the recommendation.",
  failureMode: "You spend a winter on orthotics, arch strengthening and hip external rotation work because a screen flagged you, and the underlying difference those interventions could plausibly move is a millimetre of navicular drop. Meanwhile the variables with real leverage - how much you ran, how fast, on what, after how long off - go unexamined. The specific cost is a false sense of having addressed the cause, which makes you more willing to return to the load that actually caused it.",
  experiment: "Next time a clinician gives you a measurement as an explanation for an injury, ask two questions: what is the typical difference on this measure between people who get this injury and people who do not, and how much do the two groups overlap on it. If the answer to the first is small relative to the spread within either group, the measurement is not carrying information about you - regardless of how precisely it was taken.",
  reflection: "Which anatomical feature have you been told is the cause of one of your injuries, and do you know the effect size behind that claim?",
  recall: {
    q: "Every pooled risk factor in this meta-analysis had a confidence interval excluding zero, and none of them is useful for screening an individual runner. How are both statements true?",
    a: "A confidence interval excluding zero establishes that a difference in group means exists, given the sample size. It says nothing about how much the two distributions overlap. When the mean difference is 0.79 kg/m2 in a population whose BMI standard deviation is several units, the case and control distributions sit almost on top of each other. Screening an individual requires separation, not a detectable shift in means, and there is essentially none here.\n\nFor some of these variables measurement adds a second layer. A pooled difference of 1.19 mm in navicular drop is of the same order as what a hand-held ruler against a bony landmark can plausibly resolve - the paper does not report reliability figures, so that is an inference rather than a finding, but it means a single clinical measurement cannot place you meaningfully on that scale even before you get to the overlap problem. The clean null results for ankle dorsiflexion and quadriceps angle point at the deeper issue: static measurements taken at rest are a poor proxy for what actually loads a tibia during running."
  },
  deepDive: "Show me the published reliability statistics for navicular drop and ankle range of motion measurement, and compare them against the pooled effect sizes in this meta-analysis."
},
{
  id: "return-to-run-is-expert-opinion",
  track: "load",
  level: "applied",
  title: "Every return-to-run progression you have been given is expert opinion",
  source: "Warden, Davis & Fredericson, Journal of Orthopaedic & Sports Physical Therapy 44(10), 2014, 749-765",
  evidence: "Clinical commentary on the management and prevention of bone stress injuries in long-distance runners. The paper carries its own evidence grading: Therapy, level 5 - the lowest rung, expert opinion. Its recommendations include a period of modified loading followed by progressive return to running, reducing impact through cueing runners to run softer and increasing stride rate, and strengthening local musculature such as the calf for tibial injuries and the foot intrinsics for metatarsal injuries. No controlled trial establishes the specific rate of progression.",
  replication: "craft",
  gateIntro: "You have a diagnosed bone stress injury and you are handed a return-to-run plan: so many weeks off, then walk-run intervals of a given length, progressing on a given schedule. Before you read on: what level of evidence do you think sits behind those specific numbers?",
  idea: "The most-cited clinical guidance on bone stress injuries in runners grades its own recommendations as level 5 - expert opinion. The progression schedules that circulate in clinics and forums are craft knowledge, refined by practitioners over decades and never tested against a control condition. That does not make them wrong. It means the specific numbers in your plan carry no more authority than the experience of whoever wrote them.",
  why: "Understand why the trial does not exist. To test a return-to-run progression you would need to randomise people with confirmed bone stress injuries to different progression rates, follow them for months, and use reinjury as the endpoint. Recruitment is slow because the injuries are relatively uncommon, the imaging to confirm grade is expensive, the follow-up is long, and the ethics of deliberately assigning someone to a faster progression are awkward. So the field runs on accumulated clinical experience, and it is honest enough to label it as such.\n\nCraft knowledge is not the same as no knowledge, and it deserves better treatment than either credulity or dismissal. The underlying biology is well characterised: bone responds to loading with a remodelling process that transiently weakens it before strengthening it, and the transient weakening is why progression has to be gradual. What is not established is the rate. Whether the right unit is two weeks or six, whether walk-run intervals should progress by time or distance, whether pain during is acceptable and pain after is not - these are conventions.\n\nTreat conventions accordingly. The value of a documented progression is that it is a pre-committed plan made when you were thinking clearly, which protects you from the decision you will want to make in week three when it feels fine. That is a real and substantial benefit and it does not require the schedule to be optimal. It requires it to be written down and followed.\n\nThe risk in labelling this craft is that someone takes it as permission to improvise. It is the opposite. When the evidence base is expert opinion, the sensible response is to follow one coherent expert's opinion rather than assembling a plan from four sources with different assumptions, which is what happens when you decide the schedule is arbitrary.",
  failureMode: "You read that return-to-run progressions are not evidence-based and conclude you can go by feel. Bone stress injuries have a high recurrence rate and the pain resolves well before the bone has remodelled, so feel is systematically optimistic in exactly the window where you are most likely to reinjure. The concrete cost is a second stress injury at the same site, which typically means a longer layoff than the first and a real question about whether you can keep racing the distance.",
  experiment: "Take whatever return-to-run plan you have been given or would use, and write next to each step what would have to happen for you to stop and go back a stage. Do it now, before you need it. Then find out where your plan came from - which clinician, which paper, which forum post - and whether the person who wrote it stated their reasoning or just the numbers.",
  reflection: "When a clinician gives you a specific number of weeks, do you ask whether it comes from a trial or from their experience, and would you follow it differently if you knew?",
  recall: {
    q: "Why is return-to-run progression classified as craft rather than as evidence with a weak effect, and how should that change how you follow a plan?",
    a: "Craft means practitioner knowledge with no controlled evidence behind it. There is no trial randomising people with bone stress injuries to different progression rates, because recruitment is slow, confirmation is expensive, follow-up is long and deliberately assigning a faster progression is ethically uncomfortable. The label is not a criticism of the guidance, it is an accurate description of where it comes from, and the paper itself grades its recommendations at level 5.\n\nIt should make you more disciplined about following a plan, not less. Because pain resolves well before bone remodelling completes, your subjective sense of readiness is systematically ahead of the tissue, which is exactly the situation where a pre-committed written schedule earns its value. When the evidence base is expert opinion, follow one coherent source rather than assembling a plan from several with different underlying assumptions, and decide your stop conditions before you are in the position of wanting to ignore them."
  },
  deepDive: "Find whether any randomised or prospectively controlled study has compared return-to-run progression rates after bone stress injury, and if not, tell me what the best observational evidence on reinjury rates looks like."
}
);
