/* Track: Signal and noise in nutrition. Ordered foundational first.
 *
 * Drafted, then independently fact-checked against primary sources, then
 * revised against those verdicts. Entries whose central claim did not survive
 * the check were dropped rather than softened.
 */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "cohorts-and-trials-agree-on-average",
  track: "noise",
  level: "core",
  title: "Nutrition cohorts and trials agree on average and diverge wildly in any single case",
  source: "Schwingshackl et al., BMJ 374:n1864, 2021 (PMID 34526355)",
  evidence: "Meta-epidemiological study matching 97 pairs of bodies of evidence - one from randomised controlled trials and one from cohort studies - addressing the same diet-disease question, identified through the Cochrane Database and Medline. For binary outcomes, the pooled ratio of risk ratios comparing trial estimates with cohort estimates was 1.09 (95% CI 1.04 to 1.14), with I2 = 68% and tau2 = 0.021. The 95% prediction interval ran from 0.81 to 1.46. Divergence was largest where the intervention and exposure definitions differed, particularly trials of supplements matched against cohorts measuring dietary nutrient intake. Continuous outcomes showed minimal divergence.",
  interval: { lo: 1.04, hi: 1.14, measure: "pooled ratio of risk ratios, randomised trial estimates versus cohort study estimates on matched diet-disease questions" },
  replication: "single",
  gateIntro: "Someone matches up ninety-seven diet-disease questions where both a randomised trial and an observational cohort have been run, and compares the answers. Before you read on: how far apart do you expect the two kinds of evidence to be on average, and how far apart on any individual question?",
  idea: "On average, trial and cohort estimates for the same diet-disease question differ by about 9%, with a tight confidence interval from 4% to 14%. But the prediction interval - the range you should expect for the next question you look at - runs from 0.81 to 1.46. The averages agree. Any particular pairing can be off by nearly 50%.",
  why: "The gap between the confidence interval and the prediction interval is the entire lesson and most people reading this paper miss it. A confidence interval describes uncertainty about the average across the ninety-seven pairs. A prediction interval describes where the next pair is likely to fall. With I2 at 68%, most of the variation between pairs is real heterogeneity rather than sampling noise, so the average is a poor guide to any individual case. Quote 1.09 and you have said something true and nearly useless. Quote 0.81 to 1.46 and you have said something true and actionable.\n\nThis matters because the two readings support opposite conclusions and both circulate. The reassuring reading - observational nutrition research broadly agrees with trials - is what gets quoted by people defending the field. The uncomfortable reading - for any given question the observational estimate could be a fifth too low or half again too high - is what you need when you encounter a specific headline about a specific food.\n\nThe authors identify where the divergence concentrates and it is instructive: mismatches in population, intervention, comparator and outcome definition, and especially trials of isolated supplements matched against cohorts that measured nutrient intake from food. That is not a subtle methodological quibble. It is the single most common structure of nutrition claims that reach you - a cohort observes that people eating more of some nutrient have better outcomes, and a trial of that nutrient in a capsule finds nothing.\n\nFor calibration on how noisy the primary literature is, hold this next to Schoenfeld and Ioannidis's cookbook review in the American Journal of Clinical Nutrition in 2013. They took fifty ingredients from random recipes; forty had published articles on cancer risk. Of 264 single-study assessments, 191 concluded the food was associated with increased or decreased risk, and 75% of the risk estimates had weak or no statistical significance. The median relative risk in studies claiming increased risk was 2.20. When the same questions were meta-analysed, the pooled estimates were on average null, median 0.96.",
  failureMode: "You read a headline built on a cohort study - a food, a supplement, a dietary pattern, an association with something you care about - and you change what you eat. The prediction interval says that estimate could be substantially wrong in either direction, and the cookbook review says the single-study effect sizes you are seeing are inflated by a factor of two before meta-analysis pulls them back to null. The cost is not the food. It is that you have spent your finite attention for dietary change on a claim with an expected value near zero, and you will not spend it again on the two or three interventions that actually have trial evidence.",
  experiment: "Take the last nutrition claim that changed your behaviour. Find whether it rests on a cohort study or a randomised trial. If it is a cohort, check whether a trial of the same intervention exists and what it found. If the cohort measured a nutrient in food and the trial gave a supplement, note that - it is the exact mismatch pattern this paper identifies as the largest source of divergence.",
  reflection: "What are you currently eating or not eating because of an observational study, and would you still be doing it if you had seen the prediction interval rather than the point estimate?",
  recall: {
    q: "The pooled ratio of risk ratios was 1.09 with a 95% CI of 1.04 to 1.14 and a 95% prediction interval of 0.81 to 1.46. Which of those two intervals should you use when you read a nutrition headline, and why?",
    a: "The prediction interval. The confidence interval quantifies uncertainty about the average agreement across all ninety-seven matched pairs - it answers the question of whether observational nutrition research is systematically biased as a field. The prediction interval answers the question you actually have, which is how far off the specific estimate in front of you might be. With I2 at 68%, most of the spread between pairs is genuine heterogeneity rather than sampling noise, so the average carries little information about any individual case.\n\nRead that way, the paper says an observational nutrition estimate could plausibly be about 20% too low or nearly 50% too high relative to what a trial would find. The divergence concentrates where the exposure definitions mismatch, most commonly when a cohort measures a nutrient obtained from food and a trial delivers the same nutrient as a supplement. That is the structure of most nutrition claims that reach the public, which is why the reassuring average and the unreliable individual estimate are both true at once."
  },
  deepDive: "Show me two or three specific diet-disease question pairs from this study where the trial and the cohort disagreed most sharply, and explain what caused the divergence in each."
},
{
  id: "creatine-buys-about-a-kilo",
  track: "noise",
  level: "applied",
  title: "Creatine adds about a kilogram of lean mass and only when you are lifting",
  source: "Delpino et al., Nutrition, 2022 (PMID 35986981)",
  evidence: "Systematic review and meta-analysis of 35 randomised controlled trials, 1,192 participants. Creatine supplementation increased lean body mass by 0.68 kg overall (95% CI 0.26 to 1.11). Stratified by exercise: with resistance training, 1.10 kg (95% CI 0.56 to 1.65); with mixed exercise, 0.74 kg (95% CI -3.89 to 5.36); with no exercise, 0.03 kg (95% CI -0.65 to 0.70). Stratified by sex: males 1.46 kg (95% CI 0.47 to 2.46); females 0.29 kg (95% CI -0.43 to 1.01).",
  interval: { lo: 0.26, hi: 1.11, measure: "kg change in lean body mass with creatine supplementation" },
  replication: "replicated",
  gateIntro: "Creatine is the supplement with the best evidence base in sports nutrition. Before you read on: how much lean mass do you expect it to add in a randomised trial, and does it do anything at all if you are not lifting weights?",
  cheat: "Take creatine only alongside lifting: 1.10 kg of lean mass with resistance training, 0.03 kg without, and no case for the running itself.",
  idea: "Across 35 randomised trials and 1,192 participants, creatine added 0.68 kg of lean body mass, rising to 1.10 kg when paired with resistance training. Without exercise the estimate was 0.03 kg with an interval spanning zero. It is a real effect, it is about a kilogram, and it requires the training to be there.",
  why: "The stratification is the substance of the paper. The no-exercise estimate of 0.03 kg with an interval from -0.65 to 0.70 is as clean a null as this literature produces. Creatine does not build tissue; it lets you do slightly more work in the sessions that build tissue, by supporting phosphocreatine resynthesis between high-intensity efforts. Take away the sessions and you have removed the mechanism. That is a mechanistically coherent result, which is worth noticing because coherence between mechanism and effect stratification is rare in supplement research.\n\nThe sex difference should be read carefully rather than as a finding. Males 1.46 kg with an interval from 0.47 to 2.46; females 0.29 kg with an interval from -0.43 to 1.01. Those intervals overlap. The female estimate crossing zero is at least as likely to reflect fewer and smaller trials in women as it is a genuine biological difference in response. The honest summary is that the evidence in women is thinner, not that creatine does not work in women.\n\nFor a distance runner the interesting question is whether a kilogram of lean mass is an asset. It is not obviously one. Some of the early gain is intracellular water rather than contractile tissue, and mass is mass when you are carrying it up a hill for two hours. The case for creatine in an endurance athlete rests on the strength work supporting the running, on bone loading, and on injury resilience, not on the running itself. It is a strength-training supplement that happens to be taken by runners who also lift.\n\nWhat makes this entry worth its place in a noise track is the contrast in shape. This is what a supplement with real evidence looks like: 35 randomised trials, over a thousand participants, an effect that is modest and precisely bounded, a clean null in the condition where the mechanism is absent, and honest heterogeneity in the subgroups. Almost nothing else in the supplement aisle looks like this.",
  failureMode: "You take creatine expecting it to improve your running and get a kilogram of extra mass to carry with no performance benefit for the running itself. Or you take it, skip the resistance training, and get the null condition the paper explicitly identifies. The broader failure is calibration: if a kilogram of lean mass across 35 trials is what the best-evidenced supplement in sports nutrition delivers, that is the ceiling you should hold every other supplement claim against.",
  experiment: "Before starting or continuing creatine, write down what you expect it to do for you and by how much, then check whether that expectation appears anywhere in this meta-analysis. If your reason is running performance rather than supporting resistance training, this paper is not evidence for it. If you are already taking it, weigh yourself daily for a fortnight after any change in dose and note how much of the movement is inside your normal day-to-day variation.",
  reflection: "For each supplement you currently take, can you state the effect size and the confidence interval, or only the direction?",
  recall: {
    q: "Creatine added 1.10 kg of lean mass with resistance training and 0.03 kg with no exercise. What does that stratification tell you about the mechanism, and why is the female estimate crossing zero not evidence that it does not work in women?",
    a: "The near-zero effect without exercise shows that creatine is not anabolic on its own. It supports phosphocreatine resynthesis between high-intensity efforts, which lets you accumulate slightly more quality work in a resistance session, and it is that additional work that produces the tissue. Remove the training and the mechanism has nothing to act on. The stratification and the proposed mechanism agree, which is uncommon in supplement research and is the main reason to trust this result.\n\nThe female estimate of 0.29 kg with an interval from -0.43 to 1.01 overlaps substantially with the male interval of 0.47 to 2.46. An interval crossing zero means the data are compatible with no effect, not that no effect exists. Fewer trials in women, with smaller samples, produce wider intervals, and a wider interval is more likely to include zero for reasons that have nothing to do with biology. The correct reading is that the evidence in women is thinner and less precise."
  },
  deepDive: "Find the trials in this meta-analysis that used endurance-trained participants and tell me whether creatine affected running performance rather than lean mass."
},
{
  id: "caffeine-time-trial-versus-exhaustion",
  track: "noise",
  level: "applied",
  title: "Caffeine's effect on a running time trial is a fraction of its effect on running to exhaustion",
  source: "Wang et al., Nutrients, 2022 (PMID 36615805)",
  evidence: "Systematic review and meta-analysis of 21 randomised controlled trials, 254 participants (220 men, 19 women, 15 unspecified; 167 recreational runners, 87 trained runners), caffeine doses 3 to 9 mg/kg. Time to exhaustion: Hedges g = 0.392 (95% CI 0.214 to 0.571, p < 0.001), with recreational runners at g = 0.469 (95% CI 0.185 to 0.754) and trained runners at g = 0.344 (95% CI 0.122 to 0.566). Endurance running time-trial performance: g = -0.101 (95% CI -0.190 to -0.012, p = 0.026), where a negative value indicates a reduced completion time and therefore an improvement.",
  interval: { lo: -0.19, hi: -0.012, measure: "Hedges g for endurance running time-trial performance with caffeine, negative favours caffeine" },
  replication: "replicated",
  gateIntro: "Caffeine is the most consistently supported ergogenic aid in endurance sport. Before you read on: how large do you expect its effect to be on a running time trial, and do you expect that to be the same size as its effect on how long you can hold a fixed pace before quitting?",
  cheat: "If you race, price caffeine off the time-trial g of -0.101, whose upper bound of -0.012 is nearly nothing, not the exhaustion g of 0.392.",
  idea: "Across 21 randomised trials in runners, caffeine produced a medium effect on time to exhaustion, g = 0.392, and a small one on time-trial performance, g = -0.101 with an upper bound of -0.012. The protocol that resembles a race shows a fraction of the effect of the protocol that does not. If you race, the second number is yours.",
  why: "The two protocols measure different things and only one of them is your event. Time to exhaustion holds pace or power fixed and asks how long you last, so the outcome variable is open-ended and the variance is enormous - coefficients of variation for time to exhaustion are routinely several times those of a time trial. It is also a protocol where the endpoint is a decision to stop, which makes it exquisitely sensitive to anything that affects perceived effort or motivation, which is precisely what caffeine does. A time trial fixes the distance and asks how fast, which constrains the outcome, reduces the variance, and is what you actually do on a Sunday morning.\n\nThe time-trial interval is the number to internalise: -0.190 to -0.012. The upper bound is effectively nothing. That does not mean caffeine does not work, it means the effect on the race-like protocol is small enough that this body of evidence can only just distinguish it from zero.\n\nTurning a Hedges g into seconds is where most people go wrong, because the answer depends entirely on which standard deviation you divide by and the paper does not do the conversion for you. Use the between-subject spread of finishing times, which is the conventional denominator for a standardised effect in this literature, and g = 0.1 works out at roughly 1 to 2% of your time - about 24 to 48 seconds on a 40-minute 10k. Use your own event-to-event standard deviation, which for a recreational runner is itself around 1 to 2% of finishing time, and the same g is about 2 to 5 seconds. Both are defensible arithmetic; they answer different questions, and you should say which one you are using. Neither is large. Even the more generous number is roughly a fifth of the 7.6% that a night of acute sleep loss costs per the sleep track - and that comparison is itself loose, because a Hedges g and a percentage change are not on a common scale until you have picked a denominator.\n\nThe sample composition constrains the transfer. 254 participants, of whom 220 were men and 19 were women. Doses ranged from 3 to 9 mg/kg, a threefold spread, and the pooled estimate averages across it. If you are a woman, or if you habitually consume caffeine daily and are therefore partly tolerant, the applicable evidence is thinner than the headline suggests.\n\nThe general lesson generalises beyond caffeine. When a supplement's evidence base looks strong, check which outcome protocol produced the strong result. Time to exhaustion, isolated muscle endurance tests, and repeated-sprint protocols are all more sensitive to motivational and perceptual effects than the competitive event is. A supplement literature dominated by those protocols will systematically overstate what happens on race day.",
  failureMode: "You calibrate your expectations from the time-to-exhaustion literature, take 6 mg/kg before a race expecting a medium-sized effect, and get somewhere between a couple of seconds and half a minute - along with an elevated heart rate you misread as being on pace, a gastrointestinal problem at 30 km, or a disrupted night before if you took it too late for a morning start. The larger cost is opportunity: caffeine gets your attention and your pre-race ritual while the variables with several times the effect size, like your sleep the night before, get none.",
  experiment: "Take your last three time-trial or race efforts and compute your own event-to-event standard deviation in seconds. Multiply it by 0.1. That number is your realistic caffeine expectation on the within-athlete scale, and it will be smaller than you expect. Then compare it against the spread between your best and worst effort at that distance in the last year, and note how much of that spread caffeine could possibly explain.",
  reflection: "Which of your pre-race rituals have you never estimated the effect size of, and how would you rank them if you had?",
  recall: {
    q: "Caffeine gave g = 0.392 for time to exhaustion and g = -0.101 for time-trial performance in the same meta-analysis. Why are these so different, and which applies to you?",
    a: "Time to exhaustion fixes the intensity and lets the duration vary, so the outcome is open-ended with very high variance, and the endpoint is a decision to stop. That makes it highly sensitive to anything affecting perceived effort or motivation, which is caffeine's primary mechanism. A time trial fixes the distance and measures speed, which constrains the outcome, reduces variance, and mirrors an actual race.\n\nIf you race, the time-trial estimate is yours, and its interval of -0.190 to -0.012 has an upper bound that is close to nothing. Converting it to seconds requires choosing a denominator: against the between-subject spread of finishing times g = 0.1 is roughly 1 to 2%, about 24 to 48 seconds on a 40-minute 10k, while against your own event-to-event standard deviation it is about 2 to 5 seconds. State which one you mean. The general principle transfers: when a supplement literature looks strong, check which outcome protocol produced the strength, because protocols sensitive to perception and motivation will systematically overstate what happens on race day."
  },
  deepDive: "Convert a Hedges g of 0.1 into seconds for a 10k and a half marathon under both denominators - between-subject spread and within-athlete event-to-event variability for recreational runners - and show me the working for each."
},
{
  id: "drinking-more-is-not-uniformly-better",
  track: "noise",
  level: "applied",
  title: "Whether drinking during exercise helps depends on how long and how hard you are going",
  source: "Holland et al., Sports Medicine 47(11), 2017, 2269-2284 (PMID 28497286)",
  evidence: "Meta-analysis of 9 studies producing 15 effect estimates on endurance cycling performance. For approximately 1 hour of cycling at about 80% VO2peak, fluid intake at 0.29 mL/kg/min impaired performance by 2.5% relative to no fluid (95% CI -4.1 to -0.9). For 1 to 2 hours at 60 to 70% VO2peak, fluid at 0.15 to 0.20 mL/kg/min improved performance by 2.1% (95% CI 1.2 to 2.9). For over 2 hours at moderate intensity, ad libitum intake or 0.14 to 0.27 mL/kg/min improved performance by 3.2% (95% CI 0.8 to 5.6).",
  interval: { lo: -4.1, hi: -0.9, measure: "% change in approximately 1 h high-intensity cycling performance when drinking at 0.29 mL/kg/min versus no fluid" },
  replication: "single",
  gateIntro: "You are about to do a hard hour. Before you read on: do you expect drinking during that hour to make you faster, slower, or neither - and would your answer change if the effort were three hours instead?",
  idea: "Drinking is not uniformly beneficial. In roughly an hour of hard cycling, drinking at a high rate made performance 2.5% worse than not drinking, with the whole interval on the harmful side. Beyond two hours at moderate intensity it improved performance by 3.2%. The sign of the effect flips with duration and intensity, and it rests on one pooled analysis of nine studies that nobody has independently repeated.",
  why: "The mechanism for the harm at short durations is not exotic. Fluid in the stomach during high-intensity exercise sits there, because gastric emptying slows as intensity rises. You have added mass to carry and a source of gastrointestinal discomfort, and you have not had time to accumulate the fluid deficit that drinking would offset. Over an hour at 80% you simply do not lose enough to matter. Past two hours you do, and the calculus reverses.\n\nIt is tempting to file this field as contested, and it is often presented that way, so be careful with the specific comparison usually offered. Eric Goulet's 2011 meta-analysis in the British Journal of Sports Medicine - 5 cycling time-trial studies, 13 effect estimates, 39 subjects - found that exercise-induced dehydration averaging 2.20 +/- 1.0% of body mass produced a non-significant 0.06% change in endurance performance, and that drinking to thirst outperformed drinking below thirst by 5.2%. That reads like a rival team's rebuttal. It is not: Goulet is the last author of the Holland meta-analysis above, and the two papers answer different questions - what drinking during exercise does to performance, versus what a given level of dehydration costs. Their findings are largely compatible. So this entry is filed as single. One pooled analysis, nine studies, no independent replication, and the duration-dependent sign flip has not been re-run by anyone else.\n\nNote the population too. Every effect estimate here comes from cycling, in laboratories, in trained cyclists. Running has different gastric tolerance, different thermal load per unit of work, and different mechanical consequences to carrying fluid. Applying a cycling meta-analysis to your long run is an extrapolation, and it is one that this paper cannot license.\n\nThere is also a hard asymmetry the performance numbers do not capture. Overdrinking during long events causes exercise-associated hyponatraemia, which is a medical emergency, whereas the performance cost of moderate underdrinking in this literature is a few percent at worst and arguably zero. When the downside distributions are that different in shape, the optimal strategy is not the one that maximises the point estimate of performance.",
  failureMode: "You carry a bottle for a hard 60-minute tempo, drink to a schedule, feel sloshy at 40 minutes, and run worse than you would have with nothing - and attribute it to the session being hard. The more serious version runs the other way: you apply the drink-more heuristic from short sessions to a hot marathon, drink well past thirst for four hours, and end up hyponatraemic. The performance downside of drinking too little is a few percent. The downside of drinking too much over a long event is a hospital.",
  experiment: "For the next four weeks, split your sessions by duration. Take nothing on anything under about seventy-five minutes and note whether anything actually degrades. On sessions over two hours, drink to thirst rather than to a schedule and weigh yourself before and after to see what your real losses are. Two or three data points will tell you more about your own sweat rate than any meta-analysis can - especially one built entirely on laboratory cycling.",
  reflection: "What is your current drinking rule, where did it come from, and does it distinguish between a hard hour and a long three hours?",
  recall: {
    q: "Drinking impaired performance in a hard hour and improved it beyond two hours. Explain the mechanism, and explain why the optimal strategy is not simply the one that maximises the performance point estimate.",
    a: "Gastric emptying slows as exercise intensity rises, so fluid taken during a hard hour largely stays in the stomach. You have added carried mass and a source of gastrointestinal discomfort without offsetting a deficit, because an hour at high intensity does not produce enough fluid loss to impair you. Past two hours at moderate intensity the losses become substantial, emptying is faster at lower intensity, and the balance reverses to a roughly 3% benefit.\n\nThe strategy question is not settled by the performance numbers because the two error directions have very different consequences. Underdrinking costs a few percent of performance at worst, and a meta-analysis from the same senior author found dehydration of about 2.2% of body mass produced no significant performance change at all. Overdrinking during a long event risks exercise-associated hyponatraemia, which is a medical emergency. When one tail is a few percent and the other is a hospital, you optimise against the tail, not the mean. All of these estimates also come from a single pooled analysis of laboratory cycling with no independent replication, which is a further reason not to over-tune."
  },
  deepDive: "Find what the running-specific evidence says about fluid intake and performance, and tell me how it compares with the cycling meta-analyses."
},
{
  id: "injured-runners-report-eating-less",
  track: "noise",
  level: "advanced",
  title: "Injured female runners report eating about three hundred calories a day less than uninjured ones",
  source: "Colebatch et al., Journal of Science and Medicine in Sport, 2025 (PMID 40000283)",
  evidence: "Systematic review and random-effects meta-analysis of prospective cohort studies: 15 studies, 5,942 adult distance runners (2,364 female), 9 studies in the meta-analyses, with certainty graded by an adapted GRADE approach. Injured female runners had lower energy intake than uninjured runners (mean difference -303 kcal/day, 95% CI -533 to -73) and lower total fat intake (-20 g/day, 95% CI -31 to -9), both p < 0.01, moderate certainty; a sex difference was observed for total fat intake (p = 0.01). Across both sexes, injured runners had lower dietary fibre intake (-3 g/day, 95% CI -5 to -0, p = 0.04, moderate certainty). Protein, carbohydrate, calcium and alcohol intake and disordered eating risk did not influence injury risk (low to moderate certainty).",
  interval: { lo: -533, hi: -73, measure: "kcal/day difference in reported energy intake, injured versus uninjured female distance runners" },
  replication: "replicated",
  gateIntro: "Across prospective cohorts of adult distance runners, someone compares the reported diets of those who went on to get injured against those who did not. Before you read on: which dietary variables do you expect to separate the two groups, and would you expect a screening questionnaire for disordered eating to be one of them?",
  cheat: "Compare your eating with your training load, not a calorie target: the 303 kcal/day less in injured female runners was self-reported.",
  idea: "Pooled across prospective cohorts, injured female runners reported eating about 303 kcal/day and 20 g/day of fat less than uninjured female runners, both with moderate certainty. Fibre was lower too, by 3 g/day across both sexes. Protein, carbohydrate, calcium, alcohol and disordered eating risk showed nothing. The signal is in total intake, and it is measured by the least reliable instrument in nutrition science.",
  why: "Take the finding seriously first. Low energy availability is a well-described mechanism for bone stress injury, running through suppressed reproductive and metabolic hormone signalling and impaired bone remodelling. A 300 kcal/day deficit in a female distance runner is exactly the magnitude that literature would predict to matter, and the prospective design means the dietary measurement preceded the injury. The direction, the magnitude and the sex specificity all line up with an established mechanism, and moderate GRADE certainty on a nutrition question is better than most of what you will read.\n\nNow take the measurement seriously. Every one of these numbers comes from self-reported dietary intake, whether food diaries or frequency questionnaires. Under-reporting of energy intake against doubly labelled water is one of the most robust findings in nutritional methodology, it is substantial, and it is not random - it correlates with body composition, with sex, and with how much the respondent cares about what the record says. A runner in pain, or a runner already worried about their weight, is not a neutral instrument. A reported 303 kcal/day difference could be a real intake difference, a reporting difference, or both.\n\nThe null on disordered eating risk cuts against the simplest version of the story and deserves more attention than it will get. If the mechanism were straightforwardly restrictive eating causing low energy availability causing injury, you would expect a validated disordered eating screen to detect it. It did not. Either the screens are insensitive in this population, or the energy shortfall in injured runners is arriving through some route other than deliberate restriction - high training volume with inadequate compensation is the obvious candidate.\n\nAnd note the fibre result, mean difference -3 g/day with an interval reported as -5 to -0 and p = 0.04. That -0 is a small negative rounded to one significant figure, not zero, so the interval does exclude no effect and the paper reports it as a real difference at moderate certainty. The reason to be careful with it is not statistical. It is that a 3 g/day gap in fibre is a secondary outcome from nine pooled studies of self-reported diet, and the most economical explanation is total food volume: a runner eating 303 kcal/day less is eating less of everything, fibre included. Expect this one to leave the paper as a headline about fibre being protective, which is a claim the study did not test.",
  failureMode: "You read this as licence to eat more and stop there, without changing what actually drives energy availability, which is the relationship between intake and training load rather than intake alone. Or you read the disordered eating null as reassurance and skip a conversation that a female runner with recurrent bone stress injuries genuinely needs to have. The specific cost of getting this wrong is a bone stress injury, which per the return-to-run entry in the load track has a high recurrence rate and no evidence-based rehabilitation timeline.",
  experiment: "Do not start a food diary to check this - you will reproduce the under-reporting bias in your own data and then trust it. Instead, take one hard training week and one easy week and note whether your eating actually changed between them. If your intake is roughly flat across a 40% swing in training load, you have an availability problem that no absolute calorie target will describe. Weight stability over months is a cruder but far more honest instrument than any diary.",
  reflection: "Does what you eat actually change between your biggest training weeks and your lightest ones, or is your intake essentially constant while your output is not?",
  recall: {
    q: "Injured female runners reported 303 kcal/day less than uninjured ones, but a validated disordered eating screen showed nothing. What are the two competing readings of that combination?",
    a: "The first reading is that the energy shortfall is real and does not arrive through deliberate restriction. A runner can be substantially under-fuelled relative to training load simply by not increasing intake as volume rises, with no disordered attitude to food that a screening instrument would flag. That fits the low energy availability mechanism, which is about the balance between intake and expenditure rather than about eating behaviour, and it fits the sex specificity of the result.\n\nThe second reading is that the 303 kcal/day is at least partly a reporting artefact. All of these numbers come from self-reported diaries or frequency questionnaires, and under-reporting of energy intake against doubly labelled water is large and systematically related to body composition, sex and how much the respondent cares about the record. If the disordered eating screen is picking up nothing while the intake numbers differ, one possibility is that the intake difference is a difference in reporting rather than in eating. Both readings are live, and a prospective design controls the temporal order without fixing the instrument."
  },
  deepDive: "Show me the doubly labelled water validation literature on how much self-reported energy intake is under-reported and what predicts the size of the error."
}
);
