/* Track: The contact patch. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "grip-four-hands-of-rubber",
  track: "grip", level: "everyday",
  title: "Everything you ask for goes through four hands of rubber",
  source: "Paul Haney, The Racing and High-Performance Tire",
  evidence: "Direct measurement. Press a loaded tyre onto pressure-sensitive film and the printed area for a typical passenger car at normal inflation comes out near 150 square centimetres per corner, which is roughly a spread palm. The result is reproduced routinely in tyre development and in any workshop with a footprint gauge.",
  replication: "replicated",
  cheat: "Every input you make reaches the road through four patches the size of your hand. Nothing you ask for is free of that limit.",
  idea: "Steering, braking, accelerating and stabilising all draw on the same four palm-sized areas of rubber, and no control input can exceed what those four areas can transmit.",
  why: "The car has no other connection to the world. Aerodynamic force changes how hard the tyres are pressed down, and it does so usefully at speed, but it still arrives at the road through the same four patches. Everything else - engine torque, brake torque, steering angle, the stability system's corrections - is a request that has to be honoured by rubber in contact with tarmac or not honoured at all.\n\nThe consequence is that all four demands compete. There is no separate braking system and cornering system as far as the road is concerned; there is one budget per corner and four of them in total. A driver who thinks in terms of separate controls will keep asking for the sum of two things that individually seem reasonable.\n\nThe patches are also not fixed. They move as the car rolls and pitches, they change size with load and pressure, and they change what they can do with temperature and surface. Treating them as four constants is the first simplification worth abandoning.",
  failureMode: "Someone fits larger brakes to a car that already locks its wheels or triggers ABS on the surface they drive. The braking system was never the limit; the patches were. The money buys resistance to fade on a long descent, which is real, and buys nothing at all in a single stop from the speed limit.",
  experiment: "Park on level ground and slide a sheet of paper under the leading edge of each front tyre until it stops. Mark where it stops, do the same from behind, and measure the gap. Then put your hand next to it. Write down the two numbers and which of the four is largest.",
  reflection: "Which corner had the biggest patch, and does that match where you assume the car has the most grip?",
  deepDive: "For a car I describe, work out roughly what the four contact patches are doing at rest and how that changes under hard braking."
},
{
  id: "grip-rubber-is-not-classical-friction",
  track: "grip", level: "limit",
  title: "Rubber does not obey the friction you were taught",
  source: "K. A. Grosch, The relation between the friction and visco-elastic properties of rubber",
  evidence: "Grosch's sliding experiments over a wide range of speeds and temperatures produced friction coefficients above 1 and showed that the friction curve is a function of the rubber's visco-elastic behaviour, not a constant. Persson's later contact-mechanics treatment reproduced the same dependence on speed and surface roughness. The area dependence is confirmed every time a wider tyre out-grips a narrower one of the same compound.",
  replication: "replicated",
  cheat: "Rubber grip rises with contact area and varies with temperature and sliding speed, so the schoolroom rule that friction ignores area does not apply to tyres.",
  idea: "Tyre grip comes from adhesion and from the rubber deforming over surface roughness, which makes it depend on area, speed and temperature in a way classical friction does not.",
  why: "Amontons gives friction proportional to normal load and independent of contact area, with a coefficient below 1 for most pairs of solids. Tyres break all three. Coefficients above 1 are ordinary and above 1.5 is normal for a competition compound, grip depends strongly on area, and it varies with sliding speed and temperature.\n\nThe reason is that rubber grips two ways. Adhesion is molecular bonding between rubber and road at the points where they genuinely touch, and it scales with real contact area. Hysteresis is the rubber deforming as it flows over the peaks of the road surface, losing energy to internal damping on the way; because rubber is visco-elastic, that loss depends on how fast the deformation happens and how warm the rubber is.\n\nThis is why a track surface that has been rubbered in grips better, why grip falls off a cliff in the cold, and why the same tyre feels different at the start and the end of a corner. None of that is available in a model where the coefficient is a property of two materials.",
  failureMode: "A calculation is done with a friction coefficient of 0.7 taken from a physics table, and the answers come out neat and wrong. The number is neither constant nor a property of rubber and road alone, so the stopping distance it predicts belongs to no actual car on any actual day.",
  experiment: "Take the same road, the same corner and the same speed on a cold early morning and again on a warm afternoon, driving well within your usual margin both times. Note the steering effort and how progressive the car feels at the same modest cornering load. Write both down before you compare them.",
  reflection: "Did the car feel different at the same speed, and would you have attributed that to the tyres or to yourself before reading this?",
  deepDive: "Explain where the adhesion and hysteresis components dominate for a road tyre on a surface I describe, and what that predicts about cold mornings."
},
{
  id: "grip-friction-circle",
  track: "grip", level: "everyday",
  title: "Braking and cornering share one budget",
  source: "William and Douglas Milliken, Race Car Vehicle Dynamics",
  evidence: "Measured tyre force data plotted as longitudinal against lateral force falls on a closed convex curve, usually a flattened ellipse rather than a true circle. The construction dates to Weber and Radt's work at Calspan and is reproduced by every tyre test rig that sweeps combined slip.",
  replication: "replicated",
  cheat: "Braking and turning draw on one shared budget. At full braking there is nothing left to steer with, so release the brake before you ask for steering angle.",
  idea: "The longitudinal and lateral force a tyre can produce are bounded by one closed curve, so any grip spent slowing is grip unavailable for turning.",
  why: "Plot how hard a tyre can push forwards and backwards on one axis and sideways on the other, and the reachable region is roughly an ellipse. You can sit anywhere inside it. You cannot sit outside it. Full braking puts you at the bottom of the ellipse, where the lateral capability is zero, which is the formal version of the observation that a locked wheel does not steer.\n\nThe useful consequence is that the sum matters and the parts do not. Braking at 70 per cent of capacity leaves roughly 70 per cent of lateral capability, not 30 per cent, because the boundary is curved rather than straight. That curvature is why trail braking works at all: giving up a little braking buys a lot of steering early on, and the exchange rate gets worse as you approach either axis.\n\nIt also explains why the panic response of braking hard and steering hard at once produces neither. The request is outside the ellipse, so the tyre delivers its best compromise, which is a direction nobody chose.",
  failureMode: "A hazard appears mid-corner, the driver stands on the brake without unwinding any steering, and the car runs straight on into the thing it was steering around. The brakes worked. The budget was already spent on the corner.",
  experiment: "On a quiet road at low speed and well inside your margin, take a familiar roundabout twice. Once brake to your entry speed before any steering goes in. Once carry a light brake a moment past turn-in. Note only how much steering angle each needed to hold the same line.",
  reflection: "Which one needed less steering for the same line, and can you tell whether that was the tyres or your entry speed?",
  deepDive: "Draw out the traction budget for a corner I describe and show me where a mid-corner brake application would put me."
},
{
  id: "grip-slip-angle",
  track: "grip", level: "limit",
  title: "A tyre only turns the car by slipping",
  source: "Hans Pacejka, Tyre and Vehicle Dynamics",
  evidence: "Force-versus-slip-angle curves from tyre test rigs show lateral force rising steeply from zero slip, peaking for a road tyre somewhere near six to ten degrees, then falling away. The curve shape is stable enough across compounds that Pacejka's Magic Formula fits it with a handful of coefficients, and it has been fitted to thousands of tyres since.",
  replication: "replicated",
  cheat: "A tyre makes cornering force only by pointing slightly away from where it is travelling, and that force peaks well before it starts to squeal.",
  idea: "Lateral force is generated by the difference between where a tyre points and where it actually travels, and that force peaks at a few degrees of difference before falling away.",
  why: "A rolling tyre under a side load does not travel where it points. The tread rubber entering the contact patch sticks to the road and is progressively sheared sideways as it passes through, and the force required to shear it is the cornering force. The angle between heading and travel is the slip angle, and it is the input the tyre actually responds to. Steering angle is only the driver's way of asking for it.\n\nThe curve rises steeply at first, so small slip angles produce most of the available force. It flattens near the peak, which is the region where the car feels loaded but stable, and past the peak it falls, which is the region where more steering produces less turning. A road tyre peaks broadly and forgives; a competition tyre peaks sharply and does not.\n\nThe practical content is that the tyre was already sliding, by a few degrees, long before anything audible or dramatic happened. Slip is not the failure mode. It is the mechanism.",
  failureMode: "A driver treats the onset of tyre noise as the limit and backs off there, believing they found it. Noise starts near the peak, so they have been driving in the useful part of the curve and calling it the edge, and they have never felt what the far side actually does.",
  experiment: "In a large empty sealed area with no kerbs, obstacles or traffic - a closed skid pan or a hired circuit, not a car park in use - hold a constant steering angle and raise speed one small step at a time until the car begins to run wide of the circle. Note the point at which extra steering stopped adding turn.",
  reflection: "How much warning did you get between the car feeling loaded and the car running wide, and was it more or less than you expected?",
  deepDive: "Describe how the slip angle curve differs between the tyres on my car and a competition tyre, and what that means for how much warning I get."
},
{
  id: "grip-slip-ratio-and-abs",
  track: "grip", level: "everyday",
  title: "Maximum braking happens before the wheel locks",
  source: "Hans Pacejka, Tyre and Vehicle Dynamics",
  evidence: "Longitudinal force plotted against slip ratio peaks in the region of ten to twenty per cent slip and falls away substantially once the wheel is fully locked. ABS control laws are built to hold the wheel in that band, and their design targets are drawn directly from this measured curve.",
  replication: "replicated",
  cheat: "Peak braking force happens at around ten to twenty per cent wheel slip, not at lock. A locked wheel both stops you more slowly and cannot steer.",
  idea: "A braking tyre produces most force when it is rotating slightly slower than the road is passing under it, and a fully locked wheel produces less.",
  why: "Slip ratio measures how much slower the tyre's circumference is moving than the car. At zero it is free-rolling and makes no braking force. As brake torque rises the tread shears, force climbs steeply, and it peaks somewhere in the region of ten to twenty per cent for a road tyre on dry tarmac. Past that the patch transitions from mostly gripping to mostly sliding, and force falls.\n\nA locked wheel sits at 100 per cent slip, on the low side of that curve, so it decelerates the car less well. It also has zero slip angle capability, because the contact patch is sliding in one direction and can no longer be persuaded to shear sideways. That is why a locked front wheel takes your steering away, and why the loss is total rather than gradual.\n\nABS exists to hold the wheel in the band on the useful side of the peak. It is not a system that lets you brake harder than a perfect driver; it is a system that keeps a normal driver on the right side of a curve they cannot feel accurately in an emergency.",
  failureMode: "Advice to pump the brakes survives from cars without ABS and is still repeated. On a car with ABS, releasing pressure gives up the deceleration the system was already delivering, and each release costs distance while the driver is doing the work the computer does better.",
  experiment: "Find out with certainty whether your car has ABS, then read what your owner's manual says the pedal will do when it activates. Write down what you would expect to feel. Do not go looking for it in traffic.",
  reflection: "Would you have recognised what your car's ABS feels like, or would you have interpreted it as something breaking?",
  deepDive: "Explain what my car's ABS is doing at the wheel when the pedal pulses, and what the correct pedal input is while it is active."
},
{
  id: "grip-load-sensitivity",
  track: "grip", level: "limit",
  title: "A tyre gets less efficient the harder you press it",
  source: "William and Douglas Milliken, Race Car Vehicle Dynamics",
  evidence: "Tyre rig data across a load sweep shows lateral force rising with vertical load but less than proportionally, so the ratio of lateral force to vertical load falls steadily as load increases. The effect is present in every passenger and competition tyre that has been measured and is treated as a design constant in vehicle dynamics.",
  replication: "replicated",
  cheat: "Doubling the load on a tyre gives less than double the grip, so anything that piles load onto one corner costs the axle grip overall.",
  idea: "Cornering force grows more slowly than the load pressing the tyre down, so an axle with its load shared evenly grips better than the same axle with its load piled on the outside wheel.",
  why: "Put 300 kilograms on a tyre and it might give you 300 kilograms of cornering force. Put 600 on it and you get less than 600. The ratio falls. This is the single most consequential fact in vehicle dynamics and it is almost never taught to road drivers.\n\nRun the arithmetic on an axle. With load shared evenly, both tyres work at the higher ratio. Transfer load to the outside wheel and the outside tyre moves down its curve into the inefficient region while the inside tyre, now barely loaded, has little left to give. The pair produces less together than they did shared. That is why total grip falls as the car rolls, independently of anything geometric.\n\nEverything downstream depends on this. It is why a stiffer anti-roll bar at one end reduces that end's grip: the bar makes that axle take a larger share of the transfer, so its outside tyre is pushed further down its curve. It is why balance can be tuned with springs and bars at all. Without load sensitivity, chassis tuning would barely work.",
  failureMode: "A stiffer rear anti-roll bar is fitted to a front-wheel-drive car to sharpen turn-in, and it works, and then the car snaps into oversteer on a wet roundabout. The bar did exactly what it does: it moved load transfer rearwards and took grip off the rear axle. The improvement and the failure are the same mechanism.",
  experiment: "Look up the front and rear anti-roll bar arrangement on your own car and find out which end is stiffer relative to its spring rate. Write down which way you would expect that to bias the balance, then check whether that matches how the car actually behaves on a wet roundabout at ordinary speed.",
  reflection: "Did the prediction match the car, and if not, what else about the car might be doing more of the work than the bars?",
  deepDive: "Work through the load sensitivity argument for my car and tell me which end the manufacturer has biased and why they would have chosen that."
},
{
  id: "grip-weight-transfer-is-geometry",
  track: "grip", level: "limit",
  title: "Springs do not change how much load transfers",
  source: "Carroll Smith, Tune to Win",
  evidence: "Total lateral load transfer is fixed by mass, lateral acceleration, centre of gravity height and track width, and follows from a static moment balance about the contact patches. Springs and anti-roll bars appear nowhere in that expression. The result is standard in vehicle dynamics texts and is confirmed by instrumented testing whenever it is checked.",
  replication: "replicated",
  cheat: "Total load transfer depends on mass, cornering force, centre of gravity height and track width. Springs decide only which axle takes it and how fast it arrives.",
  idea: "How much load moves across the car in a corner is set by mass, cornering force, centre of gravity height and track width, and springs only decide how that total is split front to rear and how quickly it settles.",
  why: "Take moments about the outside contact patches. The lateral force acts at the centre of gravity, some height above the road, and it is resisted by a change in vertical load at the tyres separated by the track width. The transferred load comes out as mass times lateral acceleration times centre of gravity height, divided by track width. That is the whole expression, and there is no spring rate in it.\n\nWhat springs and bars do is distribute that fixed total between the axles, and set how fast it arrives and how much the body rolls while it does. Both matter. Roll changes camber and it changes what the driver feels, and the rate of transfer is what makes a car feel nervous or settled. But the number of kilograms that leave the inside tyres is decided by the shape and mass of the car.\n\nSo the ways to actually reduce transfer are few and all structural: less mass, a lower centre of gravity, a wider track, or less cornering force. Lowering a car reduces load transfer for the same reason widening it does, and neither of those is a damper setting.",
  failureMode: "Stiffer springs are fitted to stop the car leaning, the lean duly goes away, and grip does not improve. Nothing about the load moving across the car changed. What changed is that it now arrives faster and the driver has less warning, which is the opposite of the intended result.",
  experiment: "Find the kerb weight and track width of your car, estimate its centre of gravity height, and work out how much load transfers laterally at a modest 0.4 g. Then compare that number to the static load on one wheel and write down the ratio.",
  reflection: "Was the transferred load a bigger fraction of the static wheel load than you expected, and does that change how you think about a loaded roof rack?",
  deepDive: "Run the load transfer arithmetic for my car at a lateral acceleration I give you, and tell me what a roof load would do to it."
},
{
  id: "grip-understeer-is-a-balance",
  track: "grip", level: "limit",
  title: "Understeer is a comparison, not an event",
  source: "William and Douglas Milliken, Race Car Vehicle Dynamics",
  evidence: "The formal definition is the sign of the understeer gradient, the rate at which required steering angle changes with lateral acceleration, and it follows from comparing front and rear slip angles. It is measured in standardised steady-state circular tests and is a required characteristic in vehicle certification testing worldwide.",
  replication: "replicated",
  cheat: "Understeer means the front axle is running a bigger slip angle than the rear. It is a balance between the two ends, present long before anything slides.",
  idea: "A car understeers when its front tyres are running larger slip angles than its rear tyres, which is a continuous property of the car at every speed rather than a dramatic loss of grip.",
  why: "Both axles slip in every corner. What matters is which slips more. If the front runs a larger slip angle than the rear, the car needs progressively more steering as cornering force rises, and that is understeer. If the rear runs larger, the car needs progressively less, and that is oversteer. The comparison exists at every corner you have ever driven, including the gentle ones.\n\nThis matters because the popular definitions describe only the endpoint. Understeer as the front sliding wide describes what a strongly understeering car does at the limit, and tells you nothing about the same car at a third of that. The gradient version tells you what the car is doing now, and that is the thing a driver can actually feel through the steering.\n\nAlmost every road car is deliberately built to understeer, because the response to running wide is to slow down, and slowing down is what a surprised driver does anyway. A car balanced the other way punishes the instinctive response.",
  failureMode: "A driver reports that their car does not understeer because they have never had it run wide. They have never approached the limit. The balance was there the whole time, and the first time it becomes visible will be the first time it matters.",
  experiment: "On a familiar roundabout at your normal speed, notice whether you have to add steering as you go around or whether you can unwind slightly. Do it three times on different roundabouts and write down which way each one went.",
  reflection: "Was it consistent across the three, and did you have to concentrate to notice something the car has been doing on every corner for years?",
  deepDive: "Explain what would shift my car's balance towards neutral and what the manufacturer gave up to build in the understeer it has."
},
{
  id: "grip-patch-area-load-over-pressure",
  track: "grip", level: "everyday",
  title: "Load over pressure is an estimate, not an identity",
  source: "Paul Haney, The Racing and High-Performance Tire",
  evidence: "The relation follows from treating the tyre as a pure membrane where the carcass carries no load, and it recovers the right order of magnitude. Measured footprints come out smaller than it predicts, because sidewall and belt stiffness carry a share of the vertical load. The discrepancy grows as pressure falls and as sidewall stiffness rises, which is why the same tyre in a run-flat construction departs from it further.",
  replication: "overclaimed",
  idea: "Contact patch area is roughly the vertical load divided by inflation pressure, which is right enough to reason with and wrong enough that it should not be used as a measurement.",
  why: "If the tyre were a bag of air with a limp skin, the pressure inside would have to balance the load over the contact area exactly, and area would be load divided by pressure. A 1500 kilogram car carries about 3700 newtons per corner, and at 220 kilopascals that gives about 168 square centimetres. Measure it and you find rather less.\n\nThe missing part is the carcass. Belts and sidewalls are structural, they carry a share of the load in bending, and that share does not need pressure to support it. The stiffer the construction the larger the discrepancy, which is the whole principle of a run-flat, where the sidewall carries the car with no pressure at all.\n\nSo the relation is a good way to see why a heavily loaded car has bigger patches and why an under-inflated tyre spreads out and overheats at the shoulders. It is a bad way to argue about a specific number, and it is quoted as though it were exact far more often than it deserves.",
  failureMode: "The formula is used to argue that wider tyres cannot grip better because the patch area is the same at the same pressure and load. The area is not the same, it is a different shape, and grip was never proportional to area in the way the argument assumes.",
  experiment: "Measure one front footprint with the paper method at your normal cold pressure. Let 40 kilopascals out, measure again, and put the pressure back immediately. Compare both measurements to what load over pressure predicted.",
  reflection: "How far off was the prediction, and did the error grow or shrink at the lower pressure?",
  deepDive: "Explain how much of my tyre's vertical load is carried by the carcass rather than the air, and what changes that fraction."
},
{
  id: "grip-relaxation-length",
  track: "grip", level: "limit",
  title: "A tyre takes distance to build cornering force",
  source: "Hans Pacejka, Tyre and Vehicle Dynamics",
  evidence: "Step-input tests on a tyre rig show lateral force rising towards its steady value over a rolling distance rather than instantly, with a relaxation length for a passenger car tyre commonly reported at roughly half a tyre circumference. Measurements are consistent in form across tyres, though the exact figure varies with construction, load and pressure and is not settled to a narrow band.",
  replication: "single",
  idea: "Cornering force does not appear the instant you turn the wheel; the tread has to be sheared into position, which takes a rolling distance rather than a time.",
  why: "The tread has to physically deform before it can carry a side load, and that deformation is laid down by the contact patch as it rolls. So the response is governed by distance travelled, not by how quickly you moved your hands. Turn the wheel instantly and the force still arrives over roughly the next half-circumference of rolling.\n\nThe consequence is that a fast steering input does not produce a fast response, it produces an overshoot. The driver asks, nothing happens for a metre or so, they add more, and then both requests arrive together. That is the mechanism behind a large class of corrections that feel like the car being nervous when they are actually the driver and tyre out of phase.\n\nIt also means the effect scales inversely with speed. At 100 kilometres per hour half a circumference passes in a small fraction of a second and the lag is barely perceptible. In a car park it is long enough to feel, which is part of why low-speed manoeuvring feels vague.",
  failureMode: "A skid correction is applied fast and hard, nothing happens, more is added, and then the full correction arrives at once and puts the car into a second slide the other way. The famous second slide is often not a new mistake, it is the first correction landing late.",
  experiment: "At a steady speed on a straight quiet road, make one small deliberate steering input and count how long before the car actually changes heading. Then do the same at half the speed. Write down whether the delay felt like the same time or the same distance.",
  reflection: "Did it feel like a fixed time or a fixed distance, and which one does the mechanism say it should be?",
  deepDive: "Estimate the relaxation length for my tyres and tell me at what speed the lag stops being something I could perceive."
},
{
  id: "grip-cold-tyres-in-winter",
  track: "grip", level: "everyday",
  title: "The seven degree rule is real and badly stated",
  source: "K. A. Grosch, The relation between the friction and visco-elastic properties of rubber",
  evidence: "Summer and winter compounds have been compared in braking and handling tests by several independent European test organisations, and the winter compound is consistently better once temperatures fall low enough. The crossover exists because rubber stiffness is temperature dependent. The specific figure of seven degrees is a single convenient number applied to a crossover that varies by compound, surface and manoeuvre.",
  replication: "overclaimed",
  idea: "Summer tyre compounds stiffen and lose grip as temperature falls, and the temperature at which a winter compound overtakes them is a range that depends on the tyre, not a single threshold.",
  why: "Rubber is visco-elastic, so its stiffness and its internal damping both depend on temperature. Below its working range a summer compound becomes glassy, deforms less readily over the road's roughness, and loses the hysteresis component of grip. A winter compound uses a formulation that stays compliant at lower temperatures, and it is better once the summer compound has stiffened past a certain point.\n\nThe crossover is genuine. Where it sits is not one number. It moves with the specific compounds being compared, with whether the surface is wet or dry, and with whether you are measuring braking or lateral grip. Seven degrees became the quoted figure because it is memorable and roughly right for a common comparison, and it has since hardened into a specification it never was.\n\nFor Australian conditions this mostly reads the other way: a genuine winter tyre is rarely justified, but a summer or performance compound on a frosty inland morning is doing measurably less than the driver assumes.",
  failureMode: "A driver on performance summer tyres treats a five degree morning exactly like a twenty degree afternoon because the road is dry and looks identical. It is dry. The compound is not in its working range, and the first indication will be the first time they need the grip.",
  experiment: "Note the outside temperature your car reports on your coldest regular morning drive and on a warm afternoon on the same road. Then find out what compound category your tyres are, which is on the sidewall and in the model name. Write down whether the cold reading is inside their working range.",
  reflection: "Did you know which compound category was on your car before you looked, and how many cold mornings have you driven assuming it did not matter?",
  deepDive: "Tell me what compound category my tyres are and whether the temperatures I actually drive in are inside their useful range."
},
{
  id: "grip-set-pressures-cold",
  track: "grip", level: "everyday",
  title: "Pressure is specified cold because it will not stay there",
  source: "Carroll Smith, Tune to Win",
  evidence: "Gas law behaviour plus measurement: air in a tyre warms as the carcass flexes, and pressure rises with it. Increases of the order of 15 to 40 kilopascals between cold and fully warmed are routine on road tyres and are recorded any time pressures are checked before and after a drive. Every manufacturer's placard specifies a cold pressure for this reason.",
  replication: "replicated",
  cheat: "Set pressures cold, before driving. A tyre checked after a drive reads high, and bleeding it down to the placard figure leaves it under-inflated.",
  idea: "Inflation pressure rises as a tyre warms with use, so the placard figure is specified cold and any pressure read after driving is not comparable to it.",
  why: "Flexing the carcass and shearing the tread put energy into the tyre, and most of it leaves as heat. The air inside warms, and since the volume is roughly fixed, pressure rises with temperature. On a road tyre after a normal drive the rise is commonly in the tens of kilopascals, and more after sustained high speed or heavy load.\n\nThe manufacturer's placard therefore specifies a cold pressure, meaning the car has been stationary for some hours or driven only a short distance at low speed. That is the only condition in which the number means anything. A tyre measured warm will read above its cold pressure by an amount that depends on how you have been driving, which is not a correction anyone can apply reliably.\n\nThe failure this creates is asymmetric. Reading warm and topping up is harmless. Reading warm and bleeding down to the placard figure leaves the tyre under-inflated once it cools, which raises sidewall flex, raises running temperature, and wears the shoulders.",
  failureMode: "A driver checks pressures at a service station at the end of a long drive, sees they are above the placard figure, and lets air out until they match. The tyres are now meaningfully under-inflated for every drive afterwards, and the wear pattern will not show it for months.",
  experiment: "Check all four pressures cold in the morning before driving. Drive your normal route, then check them again immediately on arrival. Write down all eight numbers and the difference at each corner.",
  reflection: "How large was the rise, and was it even across the four, or did one corner run hotter than the others?",
  deepDive: "My cold and warm pressures are as follows. Tell me what the spread across the four corners suggests about how the car is loaded or aligned."
},
{
  id: "grip-tread-depth-and-water",
  track: "grip", level: "everyday",
  title: "Wet grip is gone long before the legal limit",
  source: "Paul Haney, The Racing and High-Performance Tire",
  evidence: "Independent wet braking tests by European motoring and consumer organisations have repeatedly found large increases in wet stopping distance as tread wears from new towards the legal minimum, with the degradation accelerating in the last few millimetres. The direction and rough magnitude reproduce across testers; the exact distances depend on speed, water depth and tyre model and do not collapse to a single figure.",
  replication: "replicated",
  cheat: "Wet stopping distance degrades sharply in the last few millimetres of tread, so treat about three millimetres as the practical limit rather than the legal 1.6.",
  idea: "Tread grooves exist to move water out of the contact patch, and their capacity falls with depth, so wet braking degrades badly well before the legal minimum is reached.",
  why: "On a wet road the tyre has to clear the water in front of it before rubber can touch tarmac. The grooves are the drainage, and their volume is proportional to depth. Halve the depth and you halve the water the tyre can move per unit distance, which means the speed at which it can no longer keep up falls correspondingly.\n\nThe degradation is not linear in any useful sense. A tyre at four millimetres is meaningfully worse than new, and a tyre at the 1.6 millimetre legal minimum can take a large fraction more distance to stop in standing water at highway speed. The dry performance over the same range barely moves, and often improves slightly, which is what makes this dangerous: the tyre feels fine every day it is not raining.\n\nThe legal minimum is a threshold for enforcement, not a statement about safety. It is where a tyre becomes an offence, and it is well past where it became a poor tyre.",
  failureMode: "Tyres are run to the wear indicators because they are legal and still feel normal, and the first genuinely wet drive at highway speed is the first time the difference appears. Dry feel gave no warning because dry feel was never the thing that degraded.",
  experiment: "Measure the tread depth in three grooves across each tyre with a depth gauge, including the inner shoulder, which is where wear hides. Write down twelve numbers and note the lowest.",
  reflection: "Was any tyre below three millimetres anywhere across its width, and would you have known without measuring?",
  deepDive: "Given the tread depths I measured and the roads I drive, tell me what I have actually lost in the wet and what I should do about it."
},
{
  id: "grip-the-limit-is-a-plateau",
  track: "grip", level: "limit",
  title: "The limit is a plateau you can feel, not a cliff",
  source: "Ross Bentley, Speed Secrets",
  evidence: "This is coaching knowledge rather than a measured finding. It rests on the shape of the slip curve, which is real and measured, but the claim that a driver can detect the plateau and use it has not been tested against untrained drivers under controlled conditions in any study this corpus is aware of.",
  replication: "craft",
  idea: "A road tyre's force curve flattens before it falls, and instructors teach that this flat region is detectable through the steering as a loss of building effort.",
  why: "The measured part is not in dispute. Lateral force rises steeply with slip angle, flattens near the peak, and falls beyond it. A road tyre is deliberately given a broad, forgiving peak because a sharp one punishes ordinary drivers.\n\nWhat instructors add is that the plateau is perceptible. As the tyre approaches the peak, the self-aligning torque that has been building in the steering stops building and begins to fall away, so the wheel goes light while cornering force is still high. That lightening is taught as the usable signal, arriving before anything visible happens to the car's line.\n\nTreat that as craft. The mechanism is plausible and the self-aligning torque behaviour is real and measured. Whether a given driver in a given car with electric power steering can actually read it is a different claim, and electric assistance is specifically capable of filtering out the thing being described.",
  failureMode: "A driver takes the advice on faith in a car with heavily filtered electric assistance, waits for a signal the steering is not passing through, and finds the limit by arriving at the far side of it. The advice was written for cars that talked more.",
  experiment: "On a road you know well, at speeds well inside your margin, pay attention to how steering effort changes as cornering load builds through a long constant corner. Write down whether effort builds smoothly, plateaus, or stays flat throughout.",
  reflection: "Could you feel effort changing with load at all, and if not, what does that tell you about relying on this in your car?",
  deepDive: "Tell me how much steering feel my car's assistance is likely to be filtering, and what else I could use as a limit signal instead."
},
{
  id: "grip-smoothness-is-budget-management",
  track: "grip", level: "everyday",
  title: "Smooth is not a style, it is spending the budget slowly",
  source: "Ross Bentley, Speed Secrets",
  evidence: "Coaching orthodoxy, and consistent with load sensitivity and load transfer, both of which are measured. The prescription itself has not been isolated and tested: no controlled study this corpus is aware of has compared trained smooth inputs against ordinary inputs for crash risk or for grip retained on a public road.",
  replication: "craft",
  idea: "Every abrupt input transfers load abruptly, which pushes one tyre down its load curve faster than the others can compensate, so smoothness is the practice of not spending grip on transients you did not need.",
  why: "The two measured facts do most of the work. Load transfer is set by geometry and cornering force, and tyres are load sensitive, so an axle grips best when its load is shared. An abrupt input does not change the eventual amount of transfer but it changes how fast it arrives, and during that arrival the loaded tyre is being pushed down its efficiency curve while the unloaded one has not yet given up its share.\n\nSo a sharp input costs grip during the transient even where the steady state would have been fine. Chaining sharp inputs together means the car spends most of its time in transients, which is the state in which it has least available and gives least warning.\n\nWhat has not been established is the coaching claim built on top: that deliberately practising smooth inputs makes a road driver safer. The physics is real. The transfer from practice to outcome is the part with no evidence behind it, and this corpus has a whole track on why that gap is the norm rather than the exception.",
  failureMode: "Smoothness gets taught as an aesthetic, as being gentle, and a driver applies it by being slow to react as well as slow to move. Being unhurried in an emergency is not the lesson. Not asking for two things at once is.",
  experiment: "Put a full cup of water in a cup holder for one ordinary drive and note every time it spills or nearly does. Do not change your driving to protect it. Write down where on the route each event happened.",
  reflection: "Were the spills concentrated at particular junctions or manoeuvres, and were those the places you would have named in advance?",
  deepDive: "Given the route I describe, tell me where load transfer is likely to be sharpest and what input is probably causing it."
}
);
