/* Track: What the crash data says. Ordered foundational first.
 *
 * The opening entry is the one that makes the rest of the site awkward, and it
 * goes first on purpose. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "risk-training-does-not-transfer",
  track: "risk", level: "everyday",
  title: "Teaching people to drive better does not make them crash less",
  source: "Ker and colleagues, Post-licence driver education for the prevention of road traffic crashes, Cochrane Database of Systematic Reviews",
  evidence: "A Cochrane systematic review pooling randomised and quasi-randomised trials of post-licence driver education across several hundred thousand participants found no evidence that it reduces crashes or injuries. Separately, evaluations of advanced skid-control training in Scandinavia found crash rates for young men went up rather than down after training. The direction of the null is stable across reviews; the size of the harm signal in the skid-training subgroup rests on fewer studies.",
  replication: "failed",
  interval: { lo: 0.95, hi: 1.10, measure: "rate ratio for crash involvement, post-licence driver education against none, pooled across trials" },
  idea: "Driver education after licensing has been tested repeatedly and does not reduce crash rates, and skid training in particular has been found to raise them for young men.",
  why: "The finding is old, large and unwelcome. Trials of post-licence education keep returning rate ratios that straddle one. It is not that the training fails to teach anything; participants demonstrably improve at the tested skill. What does not follow is a change in the outcome.\n\nThe explanation with the most support is that crash risk is dominated by choices rather than by capability. How fast you go, how much space you leave, whether you drive tired, whether you drive at 2am on a Saturday: these determine exposure to situations where skill would be needed. Training raises capability, and it also raises confidence, and confidence spends the capability by choosing harder situations. The skid-training result is the sharpest version. A driver who has recovered a slide on a skid pan believes they can recover one on a road, and the belief arrives more reliably than the skill.\n\nThis is the ground the whole site stands on. Every entry in the physics track is true, and none of it is evidence that knowing it will make you safer. Those are separate claims and only one of them has been tested.",
  failureMode: "A parent pays for an advanced driving course for a newly licensed teenager as a safety measure. The best available evidence says this is at best neutral and, for the skid-control component with a young male driver, plausibly harmful. The money would buy more by funding supervised kilometres.",
  experiment: "Write down, before reading further today, what you believe made you a safer driver than you were at twenty. Then mark each item as capability or as choice. Count both columns.",
  reflection: "Which column was longer, and which column does the evidence say actually moved your risk?",
  deepDive: "Push back on my reasons for thinking I am a safer driver now, and separate the ones that are capability from the ones that are exposure."
},
{
  id: "risk-experience-is-the-thing-that-works",
  track: "risk", level: "everyday",
  title: "Crash risk collapses with solo kilometres, not with instruction",
  source: "Mayhew, Simpson and Pak, Changes in collision rates among novice drivers during the first months of driving",
  evidence: "Novice crash rates fall steeply over the first months of unsupervised driving, with the largest drop inside the first several months and thousands of kilometres, and the pattern reproduces across jurisdictions and licensing systems. It appears in cohorts with substantial formal training and in cohorts with almost none, which is what separates it from a training effect.",
  replication: "replicated",
  cheat: "Novice crash risk falls steeply over the first months of solo driving regardless of training, so supervised kilometres buy more safety than any course.",
  idea: "The steepest fall in a driver's crash risk happens during their first months of unsupervised driving and tracks distance covered rather than instruction received.",
  why: "Plot crash rate per kilometre against months since licensing and the curve drops sharply and then flattens. The drop is largest in the earliest period, which is exactly when formal instruction has stopped. Cohorts that arrived with heavy pre-licence training show the same curve as cohorts that did not, which is the observation that rules training out as the cause.\n\nWhat is being acquired is not car control. It is a library of situations. An experienced driver has seen this junction layout, this sort of vehicle behaving this way, this pattern of brake lights, and recognises it before it develops. That library is built by exposure and cannot be transmitted in a classroom, which is why the entry above and this one are consistent rather than contradictory.\n\nThe policy consequence is that the useful intervention is structuring the exposure so the early kilometres are survivable: supervised hours, passenger restrictions, night restrictions. That is what graduated licensing does, and it is why graduated licensing works when education does not.",
  failureMode: "A learner completes the minimum supervised hours and is licensed, and the family treats the licence as the end of the process. The steep part of the risk curve is entirely in front of them, and the restrictions that would have flattened it are treated as an inconvenience to be waited out.",
  experiment: "Estimate how many kilometres you drove in your first year of licensed driving and how many you drive in a year now. Then write down how many genuinely surprising situations you can remember from that first year.",
  reflection: "Were the memorable situations the ones you were trained for, or the ones nobody mentioned?",
  deepDive: "Help me design the exposure plan I would give a new driver in my household, given the roads and conditions we actually have."
},
{
  id: "risk-almost-everyone-is-above-average",
  track: "risk", level: "everyday",
  title: "Almost every driver believes they are above average",
  source: "Ola Svenson, Are we all less risky and more skillful than our fellow drivers?",
  evidence: "Svenson's samples of American and Swedish drivers placed themselves overwhelmingly in the safer and more skilful halves of their peer group, with a large majority rating themselves in the top 50 per cent and a substantial fraction in the top 20. The effect has been reproduced across countries, age groups and decades, and it is stronger for safety than for skill.",
  replication: "replicated",
  cheat: "Most drivers place themselves in the safer half of the population, so your own sense of being a careful driver is worth roughly nothing as evidence.",
  idea: "Self-assessment of driving ability is systematically inflated across whole populations, so a driver's confidence in their own safety carries no information about it.",
  why: "The arithmetic makes the finding hard to escape. If most of a population places itself in the top half, most of that population is wrong, and there is no way to know from the inside which part you are in. Repeated samples have found roughly three quarters or more of drivers rating themselves above the median for safety.\n\nWhy it matters here is that it disables the obvious feedback loop. In most skills, poor performance produces visible failure and calibration follows. Driving supplies almost no such feedback: crashes are rare per kilometre, near-misses are attributed to the other party, and a decade of not crashing is compatible with driving badly the whole time. The absence of a crash is very weak evidence, and it is the only evidence most drivers ever collect about themselves.\n\nCombined with the training entry this closes a loop. Training raises confidence measurably. Confidence was already miscalibrated upwards. There is no mechanism in ordinary driving that corrects it.",
  failureMode: "A driver reasons that the crash statistics are about other people, because they have driven for twenty years without an at-fault crash. That record is consistent with being genuinely careful and equally consistent with having been lucky at a rate the base rates predict.",
  experiment: "Rate yourself out of ten for driving safety compared with other drivers on your usual roads. Write the number down. Then ask two people who have been passengers with you to rate you privately on the same scale.",
  reflection: "How far apart were the numbers, and did you find yourself explaining away the gap while reading this?",
  deepDive: "Interrogate my self-assessment as a driver and name the specific evidence I am treating as stronger than it is."
},
{
  id: "risk-fatal-crashes-scale-with-speed",
  track: "risk", level: "everyday",
  title: "Fatal crashes scale with about the fourth power of speed",
  source: "Goran Nilsson, Traffic safety dimensions and the power model, and Rune Elvik's re-analyses",
  evidence: "Nilsson's power model, fitted to speed-limit changes across many jurisdictions, gives the relative change in fatal crashes as the speed ratio raised to roughly the fourth power, with lower exponents for serious and slight injury crashes. Elvik's later meta-analyses of a much larger study set reproduced the form and refined the exponent, and the model is used in road safety appraisal internationally.",
  replication: "replicated",
  interval: { lo: 3.5, hi: 4.9, measure: "exponent on the speed ratio for fatal crashes, across Elvik's re-analyses" },
  cheat: "Fatal crash risk goes roughly as speed to the fourth power, so a 10 per cent speed increase raises fatal risk by around 45 per cent.",
  idea: "Small changes in average speed produce large changes in fatal crash counts, because the relationship is a high power rather than a proportion.",
  why: "Two mechanisms multiply. Kinetic energy goes as the square of speed, and the energy that has to be absorbed in a collision determines whether an impact is survivable. Separately, higher speed shortens the time available to perceive and respond, and lengthens the distance required to stop, which raises the probability that a collision happens at all. The product of a probability that rises with speed and a severity that rises with the square is why the exponent lands near four.\n\nThe practical translation is unintuitive because people reason proportionally. Raising average speed by 10 per cent sounds like a 10 per cent problem. Taken to the fourth power it is a rise of around 45 per cent in fatal crashes. That is why speed limit changes produce effects on fatality counts that look wildly disproportionate to the change in journey time.\n\nIt also explains why the same 10 kilometres per hour matters far more in a 50 zone than on a motorway. The model is about ratios, and 10 over 50 is a much larger ratio than 10 over 110.",
  failureMode: "A driver reasons that being 10 kilometres per hour over the limit in a 50 zone is a fifth of a small number and therefore trivial. That ratio, taken to the fourth power, is close to a doubling of fatal risk, and 50 zones are where pedestrians are.",
  experiment: "Time your usual commute at your normal pace. Then drive it once deliberately at the posted limits with no overtaking and time it again. Write both times and the difference in minutes.",
  reflection: "How many minutes did the faster version actually buy, and how does that compare to the risk multiplier the model gives for the speed difference?",
  deepDive: "Work out what the power model predicts for a specific speed difference on a road I describe, and what it buys me in time."
},
{
  id: "risk-phone-use-quadruples-it",
  track: "risk", level: "everyday",
  title: "A phone conversation roughly quadruples crash risk, hands-free included",
  source: "McEvoy and colleagues, Role of mobile phones in motor vehicle crashes resulting in hospital attendance, BMJ",
  evidence: "An Australian case-crossover study linking driver phone records to crash times found around a fourfold increase in the risk of a crash resulting in hospital attendance in the minutes after phone use. Redelmeier and Tibshirani's earlier Canadian case-crossover study using the same design found a comparable increase. Both found hands-free operation gave no meaningful protection.",
  replication: "replicated",
  interval: { lo: 2.2, hi: 7.7, measure: "odds ratio for crash with hospital attendance, 95 per cent confidence interval, McEvoy" },
  cheat: "A phone conversation multiplies crash risk about fourfold and hands-free is no safer, because the cost is attention rather than hands.",
  idea: "Talking on a phone while driving raises crash risk roughly fourfold, and using a hands-free device does not reduce it, because the impairment is cognitive rather than manual.",
  why: "The case-crossover design is what makes this credible. Each driver is compared to themselves: phone activity in the minutes before a crash is compared against the same driver at the same time of day on an earlier day. That removes the objection that people who use phones while driving are simply worse drivers, because the comparison group is the same person.\n\nThe hands-free result is the one that changes behaviour and the one people refuse. Both major case-crossover studies found no meaningful advantage. The reason is that the scarce resource is attention, not hands. A conversation with a remote party imposes a continuous demand that a passenger conversation does not, because a passenger sees the road and falls silent when things get complicated.\n\nWhat this does not settle is legislation. Bans on handheld use have produced smaller effects on crash rates than the individual risk figures imply, most plausibly because compliance is partial and because the conversations continue hands-free. The individual risk is well established; the policy lever is a separate and weaker finding.",
  failureMode: "A driver moves to hands-free and treats the problem as solved, taking calls they would previously have let ring. The measured risk did not fall and the exposure went up, so the change made things worse while feeling responsible.",
  experiment: "For one week, log every call you take or make while driving, including hands-free, with the road type and whether the call was genuinely urgent. Do not change your behaviour, just count.",
  reflection: "How many were genuinely urgent, and what would the cost have been of returning each one on arrival?",
  deepDive: "Help me design a rule for phone use in the car that I will actually keep, given the calls I logged."
},
{
  id: "risk-sleep-loss-reads-as-alcohol",
  track: "risk", level: "everyday",
  title: "Seventeen hours awake performs like the legal alcohol limit",
  source: "Williamson and Feyer, Moderate sleep deprivation produces impairments in cognitive and motor performance equivalent to legally prescribed levels of alcohol intoxication, Occupational and Environmental Medicine",
  evidence: "An Australian laboratory study compared performance under sustained wakefulness against performance under measured blood alcohol, and found that after roughly 17 to 19 hours awake, performance on hand-eye coordination and vigilance tasks matched or exceeded the impairment at 0.05 per cent blood alcohol, with around 24 hours awake corresponding to roughly 0.10. Independent replications using different task batteries have found the same equivalence in the same range.",
  replication: "replicated",
  cheat: "About 17 hours awake impairs you like 0.05 blood alcohol and 24 hours like 0.10, and unlike alcohol there is no threshold you can feel arriving.",
  idea: "Sustained wakefulness produces measurable impairment comparable to blood alcohol concentrations that would be illegal to drive at, and the equivalence starts at a duration most people reach on an ordinary long day.",
  why: "The experiment is a direct substitution. Take a battery of tasks that respond to alcohol, run the same people under sustained wakefulness instead, and find the wakefulness duration that produces the same decrement. The answer lands near 17 to 19 hours for the 0.05 equivalent, which is a person who woke at 6am and is driving at midnight.\n\nWhat makes fatigue more dangerous than the equivalence suggests is that the two impairments differ in one respect. Alcohol is administered deliberately and its quantity is known. Wakefulness accumulates without a decision, has no unit anybody counts, and the impairment it produces includes impairment of the judgement being used to assess it.\n\nThe second finding is worse. Fatigue produces microsleeps, brief lapses of a few seconds during which the driver is not receiving information at all. At 100 kilometres per hour a four second lapse covers more than 100 metres. Alcohol does not do this.",
  failureMode: "A driver leaves after work on a Friday for a long drive, having been awake since early morning, and treats tiredness as something to push through with coffee and a window down. They are driving at an impairment level they would not accept from alcohol, and the countermeasures they are using have minutes of effect.",
  experiment: "For your next long drive, write down the time you woke and the time you expect to arrive. Compute hours awake at arrival. Do this before you plan the departure time, not after.",
  reflection: "What was the number at arrival, and would you have driven that trip at the equivalent blood alcohol level?",
  deepDive: "Given a trip I describe and my usual wake time, tell me where the fatigue equivalence crosses 0.05 and what the realistic options are."
},
{
  id: "risk-you-can-tell-you-are-tired",
  track: "risk", level: "everyday",
  title: "Drivers can tell they are sleepy and drive on anyway",
  source: "Torbjorn Akerstedt and colleagues, work on the Karolinska Sleepiness Scale in driving",
  evidence: "Simulator and instrumented on-road studies find that self-rated sleepiness on the Karolinska scale predicts subsequent lane departures and eye-closure measures within the same drive, so the subjective signal carries real information. The same studies record drivers continuing to drive at ratings associated with a high probability of a lapse. The correlation is well reproduced; how far ahead of a lapse the rating rises is less settled.",
  replication: "replicated",
  cheat: "Sleepiness you can feel does predict the lapse that follows, so the useful question is not whether you can tell but whether you will stop.",
  idea: "The common claim that you cannot detect your own sleepiness is wrong; drivers rate it accurately and predictively, and the failure is that they keep driving.",
  why: "This entry exists to correct a piece of safety folklore that is repeated in campaigns. The claim that fatigue is undetectable is comforting in a strange way, because it makes the failure perceptual and therefore not a choice. The measurements do not support it. Ratings on a simple nine-point sleepiness scale, taken during a drive, predict lane departures and long eye closures later in the same drive.\n\nWhat the studies also record is that drivers give high ratings and continue. The reason is situational rather than perceptual: they are close to home, the alternative is inconvenient, the destination has people expecting them. This is the same structure as the training entry. The capability to detect was present and the choice went the other way.\n\nThe practical consequence is a better intervention. If detection were the problem the answer would be a warning system. Since the choice is the problem, the answer is deciding the stopping rule before departure, when the destination is not yet exerting pressure.",
  failureMode: "A driver treats a yawn as normal because they believe fatigue arrives without warning and they have not blacked out. They have in fact received the signal, discounted it, and used the folklore as the reason to discount it.",
  experiment: "On your next drive longer than an hour, rate your sleepiness out of nine every fifteen minutes and write it down with the time. Do not change the drive. Look at the sequence afterwards.",
  reflection: "Did the number move before you would have said you were tired, and what would you have needed to decide in advance to act on it?",
  deepDive: "Help me write a stopping rule for long drives that I set before departure and that does not depend on my judgement at the time."
},
{
  id: "risk-esc-is-the-largest-single-gain",
  track: "risk", level: "limit",
  title: "Stability control is the largest single safety gain in the tyre's domain",
  source: "Alena Erke, Effects of electronic stability control on accidents, Accident Analysis and Prevention, and Rune Elvik's Handbook of Road Safety Measures",
  evidence: "Meta-analyses pooling studies from several countries find large reductions in single-vehicle crashes for vehicles fitted with electronic stability control, with the largest effects for rollover and loss-of-control crashes and much smaller effects for multi-vehicle crashes. Independent regulator and insurer analyses in the United States and Europe reached the same conclusion, which is why fitment became mandatory across major markets.",
  replication: "replicated",
  interval: { lo: 33, hi: 50, measure: "per cent reduction in single-vehicle injury crashes, spread of central estimates across meta-analyses" },
  cheat: "Stability control cuts single-vehicle crashes by roughly a third to a half, which is larger than any driver-side intervention that has ever been measured.",
  idea: "Electronic stability control produces a reduction in loss-of-control and single-vehicle crashes of a size no driver training intervention has ever demonstrated.",
  why: "The system compares where the driver is asking the car to point against where it is actually rotating, using steering angle, yaw rate and lateral acceleration. When those disagree beyond a threshold it brakes individual wheels to generate a corrective yaw moment. Braking the outside front pulls the nose out of an oversteering rotation; braking the inside rear helps a car that is running wide.\n\nWhat makes the effect so large is what it substitutes for. Correcting a developing slide requires recognising it in a few hundred milliseconds and applying a precisely sized, precisely timed input. That is exactly the skill that skid training attempts to install and fails to make stick. The stability system does it every time, in the dark, when the driver is distracted, without practice decay.\n\nThe honest framing is uncomfortable for a site about technique. The largest measured gain in this whole domain came from taking the task away from the driver, and the second largest came from restricting when new drivers are allowed to drive. Nothing on the technique side is close.",
  failureMode: "A driver believes stability control is a nanny system and looks for how to switch it off, or assumes the car is beyond help once it intervenes. The intervention is the system doing its job at the point where a trained driver would have a fraction of a second to do it worse.",
  experiment: "Find out from your owner's manual exactly what your car's system is called, what the warning lamp looks like when it activates, and what the off switch actually disables. Write down whether it fully disables or only raises the threshold.",
  reflection: "Have you ever seen that lamp flash, and did you know at the time what it meant?",
  deepDive: "Explain what my car's stability system will and will not do, and what its off switch actually turns off."
},
{
  id: "risk-graduated-licensing-restricts-exposure",
  track: "risk", level: "everyday",
  title: "Graduated licensing works by removing exposure, not by teaching",
  source: "Rune Elvik and colleagues, The Handbook of Road Safety Measures",
  evidence: "Evaluations of graduated licensing systems across the United States, Canada, New Zealand and Australia consistently find substantial reductions in crash rates for the youngest driver cohorts, with the largest effects from night driving restrictions and peer passenger limits. The finding reproduces across jurisdictions with very different training requirements, which is what identifies restriction rather than instruction as the active component.",
  replication: "replicated",
  cheat: "Night and passenger restrictions produce the measurable share of graduated licensing's benefit, so the restrictions are the intervention and the training is not.",
  idea: "The components of graduated licensing that carry the measured benefit are the ones that remove young drivers from high-risk situations, not the ones that add instruction.",
  why: "Decompose a graduated system and the components can be evaluated separately. Night driving restrictions and limits on carrying peer passengers show up repeatedly with large effects. Extended supervised hours show up with real but smaller effects, consistent with the experience entry. Added classroom or in-car instruction shows up with effects near zero, consistent with the training entry.\n\nThe mechanism for the passenger restriction is worth stating plainly, because it is counterintuitive. Carrying peer passengers raises a young driver's crash risk substantially, and the effect grows with each additional passenger. It is not distraction in the phone sense. It is that the presence of an audience changes the choices, and the choices are what dominate risk.\n\nThis is the third finding in this track pointing the same way. Capability interventions come out near zero. Exposure interventions come out large. A site about driving technique has to be honest that it is working on the side of the ledger where the effects are small.",
  failureMode: "A jurisdiction responds to a young driver fatality by mandating more training hours, which is politically legible and evaluates at close to zero. The night restriction that would have shown up in the data is unpopular and gets dropped.",
  experiment: "Look up the actual restrictions on a provisional licence in your state, including night and passenger conditions. Write down which ones you or people you know treated as negotiable.",
  reflection: "Which restriction was most commonly ignored, and is it one of the ones carrying the measured benefit?",
  deepDive: "Given my state's graduated licensing rules, tell me which conditions carry the evidence and which are there for other reasons."
},
{
  id: "risk-where-crashes-actually-happen",
  track: "risk", level: "everyday",
  title: "Urban crashes cluster at junctions, rural deaths happen off the road",
  source: "Australian Bureau of Infrastructure and Transport Research Economics, road safety statistical reporting",
  evidence: "National crash statistics in Australia and comparable reporting elsewhere show urban injury crashes concentrating heavily at intersections, while rural fatalities are dominated by single-vehicle run-off-road and head-on collisions. The split between the two environments is stable across years and appears in every jurisdiction that reports crash type by road class.",
  replication: "replicated",
  cheat: "Urban crashes concentrate at intersections and rural deaths are mostly running off the road, so the two environments need different attention entirely.",
  idea: "Crash types divide sharply by environment: intersections dominate urban injury crashes while leaving the road dominates rural fatal crashes, and the two demand different things from a driver.",
  why: "The division follows from what is present. In town, speeds are low enough that most impacts are survivable, and the risk is concentrated where paths cross: intersections, driveways, pedestrian crossings. Survivable does not mean harmless, because the vulnerable road users are all here.\n\nOn a rural road, paths rarely cross but speeds are high and the roadside is unforgiving. The dominant fatal patterns are leaving the road on a curve and crossing the centreline. Both are single-driver events with no other party to blame, and both are heavily associated with fatigue, speed and alcohol rather than with any failure of car control.\n\nThe consequence for attention is direct. In town, the useful discipline is scanning across your path and covering the brake at every place where something can emerge. On a rural road, the useful discipline is entry speed on unfamiliar curves, lane position, and not being tired, and almost none of the risk is where you are looking.",
  failureMode: "A driver applies motorway habits on a country road, settles into a comfortable cruise, and treats an unfamiliar crest as if the road beyond it continues straight. The rural fatal pattern is exactly this, and it does not feel like risk-taking at the time.",
  experiment: "Take your two most common routes, one urban and one not. For each, write down the three places you would nominate as most likely to produce a crash, and say for each whether it is a crossing-paths risk or a leaving-the-road risk.",
  reflection: "Did the two lists have different failure types, and were you giving them different kinds of attention before today?",
  deepDive: "For a route I describe, tell me which crash types the environment actually produces and what that implies about where my attention should go."
},
{
  id: "risk-hazard-perception-is-the-trainable-part",
  track: "risk", level: "everyday",
  title: "Hazard perception is the one skill with a real link to crashes",
  source: "Mark Horswill and Frank McKenna, work on hazard perception testing and training",
  evidence: "Hazard perception response time, measured with video-based tests, correlates with crash involvement and discriminates experienced from novice drivers, and that association is reproduced across research groups. Whether training the skill transfers to a reduced crash rate is less settled: training improves test scores reliably, and the crash-outcome evidence is thinner and mixed. Several jurisdictions including Australian states have adopted the test in licensing on the strength of the correlation.",
  replication: "contested",
  idea: "The ability to detect developing hazards early is measurable, correlates with crash involvement, and can be improved by training, but whether that improvement reaches crash rates is not established.",
  why: "This is the strongest candidate for a driver-side skill that actually matters, which is why it deserves a careful verdict rather than an enthusiastic one. The correlation is solid. Slower hazard responders crash more, experienced drivers respond faster than novices, and the difference persists after controlling for reaction time in general, which means it is about recognition rather than reflexes.\n\nWhat experienced drivers appear to be doing is scanning differently. They fixate further ahead, sample mirrors and the periphery more systematically, and, crucially, look at places where a hazard could emerge rather than at hazards that already exist. That is a learnable pattern and video training improves it on tests.\n\nThe gap is the last link. Improved test scores are not a reduced crash rate, and the whole point of the training entry is that this link is exactly where interventions in this field die. The honest position is that hazard perception is the most promising thing on the driver side and that it has not yet cleared the bar the site holds everything else to.",
  failureMode: "The correlation gets quoted as though the training result were equally strong, and a hazard perception app is sold as a crash reduction measure. The correlation is real and the causal claim is doing work the evidence has not done.",
  experiment: "On one urban drive, deliberately name out loud every place where something could emerge but nothing has yet: a parked van, a driveway, a gap in queued traffic. Count how many you name in ten minutes.",
  reflection: "How many were places rather than objects, and did naming them change where your eyes went afterwards?",
  deepDive: "Given a route I describe, list the places where a hazard could emerge that I am most likely to be scanning past."
},
{
  id: "risk-two-second-rule",
  track: "risk", level: "everyday",
  title: "The two second rule covers reaction and nothing else",
  source: "Rune Elvik and colleagues, The Handbook of Road Safety Measures",
  evidence: "Measured brake reaction times for alert drivers responding to an expected event cluster near three quarters of a second, and rise substantially for unexpected events, with distributions extending past two seconds for surprised drivers. The two second gap therefore approximates a reaction allowance under favourable conditions. It contains no allowance for braking distance, surface, or the lead vehicle stopping faster than you can.",
  replication: "overclaimed",
  idea: "A two second following gap is an approximation of reaction time under good conditions, not a safe stopping distance, and it is routinely taught as though it were the latter.",
  why: "The rule is genuinely useful and it is doing less than people think. Two seconds of gap means that if the vehicle ahead stops instantaneously, you begin braking two seconds later than it did. Under favourable conditions that roughly covers an alert driver's reaction to an expected event, and it leaves nothing over.\n\nThree assumptions are buried in it. That your reaction is at the fast end, which it is not if you are surprised, tired, or looking at something else. That your braking capability at least matches the vehicle ahead, which fails against a lighter or better-braked car and fails badly on worn tyres in the wet. And that the event is a deceleration rather than an instantaneous stop, which fails when the vehicle ahead hits something solid.\n\nThe defensible version is that two seconds is a floor for ideal conditions, four is a working figure for wet or unfamiliar roads, and more again for anything where you cannot see past the vehicle ahead. What is not defensible is treating two seconds as the safe answer, because the rule was never derived from stopping distances at all.",
  failureMode: "A driver holds a disciplined two second gap in heavy rain behind a modern car with good tyres, in an older heavier car with worn ones. The gap is correct by the rule they were taught and there is no version of the arithmetic in which it is enough.",
  experiment: "On a motorway at a steady cruise, pick a fixed roadside object and count the gap to the vehicle ahead three separate times. Do not adjust first. Write down the three numbers and what you thought you were leaving.",
  reflection: "Was the real gap larger or smaller than your estimate, and by how much?",
  deepDive: "Work out an honest following distance for my car, my tyres and the conditions I describe, rather than the rule of thumb."
},
{
  id: "risk-behavioural-adaptation",
  track: "risk", level: "everyday",
  title: "Safety improvements get partly spent rather than banked",
  source: "Sam Peltzman, The effects of automobile safety regulation, and the subsequent literature on behavioural adaptation",
  evidence: "Peltzman's original claim that safety regulation was fully offset by riskier driving has not held up; later re-analyses found the offset partial at most and the net effect of major measures clearly positive. Behavioural adaptation itself is well documented in specific cases, such as reduced following distances with anti-lock brakes in some studies. The size of the effect varies widely by measure and several studies find none at all.",
  replication: "contested",
  idea: "Drivers partly consume safety improvements by taking more risk, but the offset is partial rather than complete and its size varies enough that it cannot be predicted for a given measure.",
  why: "The mechanism is intuitive and the magnitude is where the argument lives. If a change makes a situation feel safer, some drivers will spend part of that margin on speed, gap or attention. Studies of anti-lock brakes found some driver groups following more closely. Studies of other measures found nothing detectable.\n\nWhat did not survive is the strong form. Peltzman argued the offset was complete, so regulation bought nothing. Later work with better data found the offset partial and the net effect of seatbelts, stability control and structural improvements clearly positive. The stability control literature is the clearest counterexample in this corpus: a large measured benefit that persisted in the crash statistics rather than being consumed.\n\nThe reason it belongs in this track is what it implies about learning driving technique. If capability improves and the margin gets spent, the outcome does not move. That is a plausible mechanism for the training result, and it is a live hypothesis rather than a demonstrated one.",
  failureMode: "The idea gets used as an argument against safety measures, on the grounds that drivers will simply compensate. The strong version of that claim was tested and failed, and the measures with the largest measured effects are precisely the ones that act when the driver has already run out.",
  experiment: "Think of a change to your car or your route that made you feel safer: better tyres, a newer car, a familiar road. Write down honestly whether your speed or following distance changed afterwards.",
  reflection: "Did you bank the improvement or spend part of it, and would you have noticed without being asked?",
  deepDive: "Help me work out where I have spent a safety improvement rather than banking it, based on what I tell you about my car and routes."
},
{
  id: "risk-unbelted-rear-passenger",
  track: "risk", level: "everyday",
  title: "An unbelted rear passenger endangers the people in front",
  source: "Ichikawa, Nakahara and Wakai, Mortality of front-seat occupants attributable to unbelted rear-seat passengers in car crashes, The Lancet",
  evidence: "A Japanese analysis of crash records found that front seat occupants were substantially more likely to die when a rear seat passenger behind them was unbelted, with the estimated increase around fourfold to fivefold. The finding is mechanically well motivated and has been supported by crash test work, but the epidemiological estimate rests largely on this analysis and has not been widely reproduced with comparable data elsewhere.",
  replication: "single",
  idea: "An unbelted rear seat occupant becomes a projectile in a frontal impact and substantially raises the chance that the person in the seat in front of them is killed.",
  why: "In a frontal impact everything not restrained continues at the vehicle's pre-impact speed until something stops it. A 70 kilogram adult in the rear seat arrives at the back of the front seat with an energy that the seat structure was never designed to absorb, and the front occupant is between that mass and the rest of the car.\n\nThe geometry is what makes it specific rather than general. The risk falls on the occupant directly in front, which is why the analysis could detect it at all: it compared front occupants with an unbelted passenger behind them against front occupants without one, within the same crashes.\n\nThe verdict is single rather than replicated because one dataset is carrying most of the estimate. The direction is not seriously in doubt and the mechanism is plain from crash testing. The size of the multiplier is the part that has not been independently confirmed at the same scale.",
  failureMode: "Adults in the back of a taxi or on a short suburban trip leave belts off because the risk feels like their own to take. It is not only theirs. The person most exposed by that decision is sitting in front of them and did not make it.",
  experiment: "On your next drive with rear passengers, check whether every belt is on before moving, and note whether you had to ask. Do it three times and record how often you had to.",
  reflection: "Did you previously treat rear belts as the passenger's own business, and does the geometry change that?",
  deepDive: "Explain what happens to an unbelted rear occupant in a frontal impact at a speed I give you, and where that energy ends up."
},
{
  id: "risk-technique-is-the-small-lever",
  track: "risk", level: "everyday",
  title: "Everything in this site is a small lever, and that is worth knowing",
  source: "Rune Elvik and colleagues, The Handbook of Road Safety Measures",
  evidence: "Ranking road safety measures by measured effect size puts vehicle engineering, exposure restriction, speed management and enforcement well above anything acting on individual driver capability, and driver education specifically evaluates near zero. This ordering is stable across the handbook's successive editions and across independent national reviews.",
  replication: "replicated",
  cheat: "Speed, fatigue, distraction, restraints and exposure dominate crash risk; technique is a real but small lever, so spend attention on the big ones first.",
  idea: "Ranked by measured effect, the levers that move crash risk are speed, fatigue, distraction, restraint use and exposure, and driver technique sits well below all of them.",
  why: "It is worth stating the ordering explicitly, because a site like this one creates the opposite impression by talking about technique every day. Measures that act on the vehicle, on how fast people go, and on when and whether they drive at all consistently produce the large effects. Measures that act on driver capability produce effects near zero.\n\nThat does not make the physics track false or useless. Understanding load transfer will make you smoother, and smoother is more pleasant and probably marginally safer. It will also make it obvious why a particular corner on your commute is worse in the wet, and that is real knowledge. What it will not do is move your crash risk the way going to bed earlier would.\n\nThe honest reason to learn this material is that it is interesting and it makes driving a better experience. Claiming a safety benefit for it would be doing exactly what the training industry does, and the whole first entry of this track is about how that claim was tested and failed.",
  failureMode: "A reader finishes a month of this site feeling meaningfully safer. Nothing measured has changed. The feeling is the confidence effect that the training literature documents, and it is the mechanism by which capability training has occasionally made things worse.",
  experiment: "List the five changes most likely to reduce your own crash risk over the next year. Rank them by expected effect. Note where anything you have learned here appears in the list.",
  reflection: "Did technique make the top five, and if it did, what evidence are you using that it belongs there?",
  deepDive: "Given how and where I actually drive, rank the interventions available to me by expected effect and tell me which one I am avoiding."
}
);
