/* Track: Proteins and heat. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "protein-myosin-actin-window",
  track: "protein", level: "weeknight",
  title: "Myosin sets at 50C and actin sets at 66C",
  source: "Harold McGee, On Food and Cooking",
  idea: "The usable texture window for a steak is bracketed by two protein denaturation temperatures, and it is only about ten degrees wide.",
  why: "Muscle is mostly two contractile proteins. Myosin begins to unfold and aggregate from around 50C, which is what turns translucent raw muscle opaque and gives cooked meat its bite. Actin holds out until roughly 66C, and when it goes it takes the water with it: the actin network contracts hard and expels the liquid held between the filaments. That is the difference between juicy and dry, and it happens over a few degrees.\n\nSo the target is a core hot enough that myosin has set and cool enough that actin has not. Roughly 50C to 60C, which maps onto rare through medium. Everything above 60C is a trade you are making on purpose, usually to convert collagen, and there is no way to have both in the same piece of muscle at the same time.",
  failureMode: "You pull a fillet at 68C because that is what medium looks like on a chart written for pork in 1975. Myosin set eighteen degrees ago, actin has now contracted, and the meat is grey and firm with a pool of liquid under it. No amount of resting brings that back, because the water is already outside the cells.",
  experiment: "Buy two steaks from the same cut, as close in thickness as you can get. Weigh each raw to the gram. Cook one to a core of 52C and one to 63C, same pan, same fat, same sear. Weigh each again after cooking and write down the loss in grams and as a percentage of raw weight.",
  reflection: "What was the percentage cook loss at each temperature, and was the gap larger or smaller than you expected from eleven degrees?",
  deepDive: "I cook a lot of one particular cut - help me work out where in the 50C to 60C band that cut should sit, and what about its structure decides that."
},
{
  id: "protein-denature-coagulate",
  track: "protein", level: "weeknight",
  title: "Denaturation and coagulation are two steps at two temperatures",
  source: "Peter Barham, The Science of Cooking",
  idea: "Unfolding a protein and cross-linking the unfolded chains are separate events, and the gap between them is where texture lives.",
  why: "A native protein is a folded ball held together by weak bonds, with its water-hating residues tucked inside. Heat breaks those weak bonds and the chain unfolds. That is denaturation, and on its own it changes almost nothing you can see. Coagulation is the second step: the exposed hydrophobic patches and free sulfur groups on neighbouring unfolded chains find each other and bond, building a three-dimensional network that traps water.\n\nOpacity is that network scattering light. Firmness is the network getting denser. Rubberiness and weeping are the same network continuing to tighten past the point where it can hold the water it trapped, squeezing it back out. One protein, three textures, all downstream of how far the second step has gone.",
  failureMode: "You treat a set custard and an overcooked custard as the same reaction gone too far in degrees, so you drop the temperature and keep the time. It still breaks, because coagulation is a rate: at a fixed temperature above the threshold the network keeps tightening for as long as you hold it there.",
  experiment: "Set a pot of water at 62C with a thermometer in it. Slide in one shell-on egg and start a timer. Every three minutes, tilt the egg under a light and note whether the white is still clear, cloudy, or holding a shape. Write down the minute at which it stops being pourable.",
  reflection: "How many minutes passed between the first cloudiness and the first set, and what does that gap tell you about how much control you have at that temperature?",
  deepDive: "Take a protein-set dish I make often and separate for me which of its failure modes are under-denaturation and which are over-coagulation."
},
{
  id: "protein-water-holding-capacity",
  track: "protein", level: "project",
  title: "Water-holding capacity collapses above 60C",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Juiciness is a measurable function of core temperature, and the function has a knee at about 60C.",
  why: "Raw muscle is roughly 75 percent water, most of it held by capillary action in the spaces between myofibrils. Two contractions squeeze it out. From about 40C to 60C the myofibrils shrink sideways, narrowing those spaces and pushing water into the gaps between fibres. Then from about 60C the collagen sheathing the fibre bundles shrinks lengthwise and acts like a wrung towel, driving that loose water out of the meat entirely.\n\nThat is why cook loss is not linear in temperature. Below 60C you are looking at roughly 5 to 15 percent loss depending on the cut and how long it took to get there. Above 65C it climbs steeply toward 30 percent and beyond. The knee is not a matter of opinion and you can put it on a graph in your own kitchen.",
  failureMode: "You blame dryness on the pan being too hot, so you turn it down and cook longer. The surface is now pale, the core spends more time above 60C rather than less, and the meat is drier than it was with the hard sear.",
  experiment: "Cut four 150g portions from one piece of steak or a single thick pork loin. Weigh each raw. Cook each to a core of 50C, 55C, 60C and 70C respectively, using the same method, and weigh each again immediately. Plot percentage loss against core temperature on paper and mark where the line bends.",
  reflection: "Where did your curve bend, and how much extra water did the last ten degrees cost compared to the first ten?",
  deepDive: "Here are my four data points - tell me whether the shape matches the published curve and what the deviations suggest about my method."
},
{
  id: "protein-collagen-shrink-dissolve",
  track: "protein", level: "weeknight",
  title: "Collagen shrinks at 60C and only dissolves above 70C",
  source: "Harold McGee, On Food and Cooking",
  idea: "Collagen makes meat tougher before it makes it tender, and the two effects are separated by both temperature and hours.",
  why: "Collagen is a triple helix of three protein chains wound together and stabilised by cross-links. Around 60C to 65C the helix loses its structure and the whole fibre contracts to something like a third of its length. That is the shrinking, and it is fast. It happens in minutes and it makes a tough cut tougher while wringing water out of it.\n\nConverting the collapsed collagen into gelatin is hydrolysis: water has to break the peptide bonds along the chain. That is slow, it needs temperatures above about 70C to run at a useful rate, and it speeds up sharply as you climb. So a cut full of collagen has a bad middle zone. You have to either stay under it or push well past it and wait.",
  failureMode: "You cook chuck like a steak, to 63C, because that is the right number for muscle. You have shrunk every collagen fibre in it and converted none of them. The result is drier and chewier than the same cut at 55C and far worse than at 85C.",
  experiment: "Take two similar pieces of chuck, 200g each. Hold one at 65C for four hours, in a low oven with a probe or a water bath. Cook the other at 85C for one hour. Cut a 2cm strip from each across the grain and pull it apart with two forks, counting how hard you have to pull on a 1 to 5 scale, then write both numbers down.",
  reflection: "Which piece needed more force to separate, and was it the one you expected before you started?",
  deepDive: "Given a cut I name, tell me how much collagen it carries and whether it belongs below the shrink point or well above it."
},
{
  id: "protein-braise-time-temperature",
  track: "protein", level: "project",
  title: "A braise trades hours against degrees",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Collagen to gelatin conversion follows a time and temperature curve, so two very different braises can land on the same tenderness.",
  why: "Hydrolysis rate rises steeply with temperature, roughly doubling for every ten degrees in the range that matters. So the same extent of conversion can be reached at 60C in about a day or at 88C in about three hours. Both routes end up with collagen turned to gelatin and the meat falling apart under a fork.\n\nThey do not end up in the same place otherwise. The high route also drives the muscle fibres well past actin denaturation, so the individual fibres are dry and the dish reads as shredded meat lubricated by gelatin. The low route keeps the fibres closer to intact and moist, so it reads as sliceable meat that happens to be tender. Choosing a braise temperature is choosing which of those two dishes you want, not choosing how tender it gets.",
  failureMode: "You take a recipe written for 24 hours at 60C, decide you do not have that long, and run it at 60C for four hours instead. Almost no collagen has converted at that temperature in that time, so you serve a cut that is perfectly cooked as muscle and completely unchewable as connective tissue.",
  experiment: "Split one piece of beef shin or chuck in two. Bag or cover one and hold it at 60C for 24 hours. Hold the other at 88C for 3 hours. Score both for fibre separation with a fork on a 1 to 5 scale, then weigh the liquid each one released. Write down both numbers for both pieces.",
  reflection: "Did the two routes match on tenderness, and if they did, what was different about the fibres and the amount of liquid lost?",
  deepDive: "I have a fixed number of hours before dinner - work back from that to the braise temperature that gets the most collagen conversion in the time available."
},
{
  id: "protein-carryover-gradient",
  track: "protein", level: "weeknight",
  title: "Carryover is a gradient equalising, and thickness sets its size",
  source: "J. Kenji Lopez-Alt, The Food Lab",
  idea: "Carryover cooking scales with thickness and surface temperature, not with a fixed number of degrees you can memorise.",
  why: "When meat leaves the heat it is not at one temperature. It is a gradient, hot at the surface and cool at the core, and the stored heat in the outer shell keeps flowing inward until the whole thing equalises. The core rises because it is the coldest part of a body that is still redistributing heat internally, while the surface falls.\n\nHow far the core rises depends on how much energy is sitting in that shell and how far it has to travel. A thick roast blasted at 220C has a large, very hot outer volume and a long conduction path, so the core can climb 5 to 8C. A thin steak has almost no shell and a short path, so it climbs 1 or 2C. A sous vide steak has no gradient at all before the sear, so carryover is close to nothing. The rule of thumb that says pull five degrees early is really a rule about one particular geometry.",
  failureMode: "You apply the same five-degree buffer to a 1.5cm minute steak that you learned on a 2kg roast. The steak carries over one degree, arrives four degrees under, and you put it back in a hot pan, which now overshoots on the second pass.",
  experiment: "Cook a 4cm thick steak and a 1.5cm steak to the same core temperature in the same pan. Leave a probe in each on the bench and log the core reading every 60 seconds for 10 minutes. Write down the peak each one reached and how many minutes it took to get there.",
  reflection: "How many degrees did each one carry, and what is the ratio between them compared to the ratio of their thicknesses?",
  deepDive: "Given a thickness and an oven temperature I give you, estimate the carryover and tell me what I should measure to check your estimate."
},
{
  id: "protein-resting-not-reabsorption",
  track: "protein", level: "weeknight",
  title: "Resting does not reabsorb juices",
  source: "J. Kenji Lopez-Alt, The Food Lab",
  idea: "Resting cuts the liquid that runs out because the meat is cooler, not because the fibres drink anything back in.",
  why: "Two things change while the meat sits. The internal gradient flattens, so the hot outer layers stop pressing liquid outward from contracted fibres, and the whole piece drops several degrees. Cooler liquid is more viscous and moves more slowly through the cut surface, so less of it escapes in the time between slicing and eating. Weigh the pooled liquid and the difference is real and repeatable.\n\nThe folk explanation, that the muscle fibres relax and suck the juice back up, is the part that does not hold. Denatured myofibrils have already lost the structure that held that water, and Modernist Cuisine argues the reabsorption story fails on the physics. Treat resting as a viscosity and gradient effect. It buys you less mess on the board, not a reversal of cook loss.",
  failureMode: "You rest a steak for 20 minutes on a cold plate expecting it to reclaim what it lost, and serve something lukewarm that still leaks when cut. You paid the temperature cost for a benefit that tops out in the first several minutes.",
  experiment: "Cook two identical steaks together. Slice one immediately onto a tared plate and slice the second after 10 minutes onto a second tared plate. Weigh the liquid pooled under each after five minutes of sitting. Record both weights in grams and the plate temperature of each steak.",
  reflection: "How many grams of liquid separated the two, and was the difference worth the degrees the rested one lost?",
  deepDive: "Work out the shortest rest that gets me most of the benefit for a cut and thickness I name, and tell me what to weigh to confirm it."
},
{
  id: "protein-sous-vide-decoupling",
  track: "protein", level: "project",
  title: "Sous vide decouples core temperature from time",
  source: "Douglas Baldwin, A Practical Guide to Sous Vide Cooking",
  idea: "When the water sits at the target core temperature, time stops controlling doneness and starts controlling only enzyme activity and collagen.",
  why: "In a pan, temperature and time are the same knob. The surface is at 200C and the core is climbing, so the only way to hold a core of 55C is to pull it at the moment it passes through. Put the meat in water at 55C and the core asymptotes to 55C and stays there. Doneness is now a property of the bath setting alone.\n\nWhat time still does is drive the slow reactions. Muscle proteases keep working up to around 50C to 60C depending on the enzyme, and collagen hydrolysis runs slowly even at 55C. So a steak held for six hours is measurably more tender than the same steak held for one hour at the same temperature, and it will also have released more liquid into the bag. Long is not free, it is just a different axis.",
  failureMode: "You treat the bath like an oven and leave a fillet in at 55C all afternoon because it cannot overcook. It cannot overcook in the doneness sense, but six hours of proteolysis has turned the texture pasty and mealy, and there is 20g of purge in the bag.",
  experiment: "Bag two steaks from the same piece and weigh each raw. Hold both at 55C, one for 1 hour and one for 6 hours. Weigh the purge from each bag in grams. Sear both identically and compare how much force it takes to cut across the grain with the same knife.",
  reflection: "How much extra purge did the six-hour steak give up, and did the tenderness gain justify it?",
  deepDive: "For a cut I name, tell me where the useful hold time tops out at a given bath temperature and what texture change signals I have gone past it."
},
{
  id: "protein-pasteurisation-curve",
  track: "protein", level: "project",
  title: "Pasteurisation is a time at temperature curve",
  source: "Douglas Baldwin, A Practical Guide to Sous Vide Cooking",
  idea: "Safety comes from log reduction accumulated over time, so a low temperature held for long is equivalent to a high one held briefly.",
  why: "Bacterial death is first order. At a fixed temperature a population falls by a constant factor per unit time, and the time for one tenfold reduction is the D value. Raising the temperature shortens D steeply. So a 6.5 log reduction of salmonella in beef takes roughly two hours at 54.4C, roughly twelve minutes at 60C, and under a minute at 66C. Same outcome, three different routes.\n\nThis is what makes low-temperature cooking legitimate rather than a gamble. The single-number targets on packaging are the instantaneous end of the same curve, chosen because a consumer can check a thermometer once and cannot integrate time. If you can hold a temperature and time it, you can use any point on the curve. Look up the published table for your thickness rather than interpolating by feel, because come-up time counts too.",
  failureMode: "You hold chicken at 60C for eight minutes, see the number that a table quotes for 60C, and serve it. That table time starts when the coldest point reaches 60C, not when the bath does, and a thick thigh may still have been at 52C for most of your eight minutes.",
  experiment: "Roast something with a probe left in the core and log the temperature every two minutes. Afterwards, add up the total minutes the core spent above 54.4C. Compare that total against the published pasteurisation table for the thickness you cooked and write down whether you cleared it and by how much.",
  reflection: "How much of your pasteurisation was already banked before the core hit its final temperature?",
  deepDive: "Take a bath temperature and thickness I give you and walk me through reading the pasteurisation table correctly, including come-up time."
},
{
  id: "protein-salt-45-minutes",
  track: "protein", level: "weeknight",
  title: "Salting 45 minutes ahead leaves meat wetter than salting at the pan",
  source: "J. Kenji Lopez-Alt, The Food Lab",
  idea: "Salt pulls water out of meat first and puts more of it back after about forty minutes, so early salting ends up net positive.",
  why: "The first phase is osmosis. Salt on the surface dissolves into the meat's own moisture and the concentration gradient pulls more water out, so within ten or fifteen minutes there are visible beads on the surface and the meat has genuinely lost weight.\n\nThe second phase is what makes it worth doing. That concentrated brine dissolves myofibrillar proteins, chloride ions bind to the filaments and increase their net negative charge, and the filament lattice swells apart and takes water with it. The surface liquid is drawn back in and held more tightly than it was before. The crossover is around forty minutes for a steak-sized piece. Salt at the pan and you get the seasoning without the swelling. Salt at fifteen minutes and you get the worst point on the curve, plus a wet surface that will not brown.",
  failureMode: "You salt twenty minutes out because you are almost ready, then hit a wet surface with a hot pan. The water has to boil off before the surface can pass 100C, so you steam the first two minutes away and get a grey crust instead of a brown one.",
  experiment: "Weigh a 200g steak on a plate, then lift the steak alone onto tared scales and record the number. Salt it at 1 percent by weight. Lift it off and weigh the steak alone at 5, 15, 30, 45 and 60 minutes, wiping nothing. Write down all six numbers and find the minute at which the weight stops falling.",
  reflection: "Where was your crossover, and how much of the early loss did the meat take back by 60 minutes?",
  deepDive: "Scale the crossover time for a piece much thicker or thinner than a steak and tell me how you are reasoning about it."
},
{
  id: "protein-wet-versus-dry-brine",
  track: "protein", level: "project",
  title: "Wet brining adds water, dry brining concentrates it",
  source: "Cook's Illustrated",
  idea: "A wet brine raises cooked yield with water that was never part of the meat, and dilutes the flavour that was.",
  why: "Both methods work through the same salt chemistry: dissolved myofibrillar protein, a swollen filament lattice, and better water retention through the cook. The difference is where the water comes from. A wet brine surrounds the meat with a 5 to 6 percent salt solution, so the swelling lattice takes up brine from outside and the piece can gain 6 to 10 percent in raw weight.\n\nThat gain survives cooking, so a wet-brined bird weighs more on the plate and reads as juicy. It is also carrying tap water through every muscle cell, which dilutes the soluble compounds that make it taste like chicken. A dry brine adds no water at all. It redistributes and retains what was already there, so the yield is lower and the flavour is more concentrated. Neither is wrong, but they are answers to different questions.",
  failureMode: "You wet brine a good free-range bird for 12 hours and cannot work out why it tastes flatter than the supermarket one you dry brined. It is heavier and wetter and less flavoured, all from the same cause.",
  experiment: "Take two chicken marylands of similar size. Weigh both. Wet brine one in 5 percent salt solution and dry brine the other at 1 percent salt by weight, both for 12 hours in the fridge. Weigh both again, pat both dry, roast them together to the same core temperature, and weigh both a third time. Write down all six weights.",
  reflection: "Which one finished heavier relative to its raw weight, and which one tasted more like chicken?",
  deepDive: "Help me pick between wet and dry for a specific piece I am cooking, and tell me what the yield difference should be so I can check it."
},
{
  id: "protein-egg-white-sequence",
  track: "protein", level: "weeknight",
  title: "Egg white sets in sequence from 62C to 80C",
  source: "Harold McGee, On Food and Cooking",
  idea: "Egg white is a mixture of proteins with different setting points, so it has several distinct textures rather than one.",
  why: "White is about 10 percent protein and that protein is at least a dozen species. Ovotransferrin is roughly 12 percent of it and coagulates at about 61C to 62C, which is the first thing to happen and the source of the loose, barely-holding gel of a slow-cooked egg. Ovalbumin is over half the protein and holds out until around 80C, which is what gives a hard-boiled white its firm, sliceable body. Lysozyme sits between them.\n\nSo the setting point of an egg white is not a number, it is a sequence. At 63C only the earliest protein has coagulated and the white is a fragile cloud. At 70C most of the mixture is in and the white is tender but intact. At 80C ovalbumin has joined and the network is tight enough to start squeezing out water, which is why a hard-boiled white goes rubbery and a very hot poach weeps.",
  failureMode: "You aim for a soft poached egg at 75C thinking softer means lower, and get a white that is fully set and tough while the yolk has also gone chalky. You crossed the ovalbumin threshold and the yolk was never the constraint.",
  experiment: "Set up four eggs in water baths at 62C, 66C, 70C and 75C for 40 minutes each. Crack each one onto a white plate and write one line describing the white: whether it pours, whether it holds a dome, whether liquid separates around it. Photograph all four side by side.",
  reflection: "At which of the four temperatures did the white first hold its own shape, and where did it start weeping?",
  deepDive: "I want a specific white texture for a dish - tell me which bath temperature and hold time gets me there and why."
},
{
  id: "protein-yolk-plateau",
  track: "protein", level: "project",
  title: "The 65C yolk is a plateau, not a knife edge",
  source: "Herve This, Molecular Gastronomy",
  idea: "Yolk thickens from about 65C and sets near 70C, and because the change is slow at the low end, the low route is far more forgiving.",
  why: "Yolk is a suspension of lipoprotein granules and dissolved proteins, and the ones that matter start unfolding around 65C. Full setting is near 70C. Coagulation is a rate, not a switch, so at 64C the network builds slowly and levels off at a texture that barely changes over the next half hour. At 72C it builds fast and does not stop.\n\nThat is the whole argument for the low-temperature egg. An hour at 64C lands you in the same place as fifty minutes at 64C, so timing precision is almost irrelevant. Two minutes past the right moment at 72C is a chalky yolk. Herve This popularised the 65C egg for exactly this reason: it is not that 65C is a magic number, it is that the curve is nearly flat there and you can stop worrying about the clock.",
  failureMode: "You try to hit the same texture in simmering water by timing it, get it right once, and never repeat it. The reaction at 95C surface temperature is running so fast that your fifteen-second variation in pot placement swamps your timing.",
  experiment: "Hold three eggs at 63C, 65C and 67C for one hour. Crack each onto a flat white plate and photograph from directly above. Measure how far the yolk spreads in centimetres after two minutes and write the three numbers next to the three temperatures.",
  reflection: "How much did four degrees change the spread, and which of the three would you be able to reproduce reliably?",
  deepDive: "Design a yolk texture target with me and tell me which point on the plateau to sit at and how much timing slack I get there."
},
{
  id: "protein-scramble-curd-size",
  track: "protein", level: "weeknight",
  title: "Curd size in scrambled eggs is set by heating rate",
  source: "Harold McGee, On Food and Cooking",
  idea: "How fast you put heat in decides how big the curds are, because coagulation competes with your stirring.",
  why: "Scrambling is a race. Protein chains that have unfolded start bonding to their neighbours immediately, and every bond that forms makes an aggregate. Your spoon breaks aggregates apart. If heat goes in fast, coagulation runs faster than you can shear, aggregates grow into large curds, and the network keeps tightening after it forms, expelling water.\n\nSlow heat plus constant agitation keeps every aggregate small, so you end up with a fine suspension of curds in unset egg rather than lumps in liquid. It also lets you stop at a lower final temperature, which matters because the water squeezed out of a tight network is what pools on the plate. Salting fifteen minutes before cooking helps too: dissolved salt interferes with protein to protein bonding, so the curds set softer at the same temperature.",
  failureMode: "You cook eggs on high while stirring hard, see them come together fast, and plate them looking good. Two minutes later there is a puddle of grey water around them, because the curds were still contracting on the plate.",
  experiment: "Scramble two 3-egg batches. Cook one on high heat, stirring, and one over low heat holding the pan below 70C with a probe. Note the pan time for each. Plate each on a dry plate and after five minutes measure the pooled liquid by tipping the plate and drawing it up with a syringe or blotting it onto a tared paper towel.",
  reflection: "Which batch released more liquid, and how much longer did the slow one take for that difference?",
  deepDive: "Tell me what changes about the curd mechanism when I add cream, milk or butter to the raw egg, and what to measure to see it."
},
{
  id: "protein-green-ring-iron-sulfide",
  track: "protein", level: "weeknight",
  title: "The green ring on a boiled egg is iron sulfide",
  source: "Harold McGee, On Food and Cooking",
  idea: "The grey-green layer at the yolk surface is ferrous sulfide and it marks overcooking, not a stale egg.",
  why: "White proteins carry sulfur in their cysteine residues. Sustained heat breaks those bonds and releases hydrogen sulfide, which diffuses inward through the egg. At the yolk surface it meets iron bound in phosvitin and other yolk proteins and forms ferrous sulfide, which is that dull green-grey.\n\nIt is a product of time and temperature, so it is a report on your cooking. Older eggs make it worse because they are more alkaline and alkaline conditions accelerate the sulfide release, which is where the folklore about stale eggs comes from. But a fresh egg boiled for twenty minutes will ring too. Cooling fast in ice water stops it early by killing the diffusion, which is why the ice bath is doing real chemistry rather than just making peeling easier.",
  failureMode: "You throw out a batch of eggs as off because they ringed, when the actual cause was leaving the pot on for eighteen minutes. You have diagnosed the ingredient for a process fault.",
  experiment: "Boil three eggs from the same carton for 8, 12 and 18 minutes. Cool all three in the same ice bath, peel and cut each in half. Write down which ones show a ring and how thick it is in millimetres.",
  reflection: "At what cooking time did the ring first appear, and how much did the ice bath change the result compared to eggs you have cooled on the bench?",
  deepDive: "Give me the shortest boiling time that fully sets the yolk of a given egg size without producing a ring, and tell me how to verify it."
},
{
  id: "protein-fish-collagen",
  track: "protein", level: "weeknight",
  title: "Fish collagen dissolves near 50C",
  source: "Harold McGee, On Food and Cooking",
  idea: "Fish connective tissue turns to gelatin at temperatures where beef is still raw, which is why fish flakes and beef does not.",
  why: "Fish collagen has fewer of the heat-stable cross-links that mammalian collagen accumulates with age and use, and a lower proportion of the hydroxyproline residues that stabilise the triple helix. So it denatures and hydrolyses in the mid forties to low fifties rather than needing hours above 70C.\n\nThe structure amplifies this. Fish muscle is built as short blocks of fibres, the myotomes, separated by thin sheets of connective tissue called myocommata. Those sheets are the only thing holding the blocks together. Dissolve them and the whole fillet comes apart into flakes with almost no force. Flaking is not a sign of doneness in the way it is for meat, it is the sign that the connective tissue has already gone.",
  failureMode: "You cook a fillet until it flakes easily, which is the standard advice, and by then the muscle proteins have been well past their own denaturation point for several minutes. The fish separates beautifully and each flake is dry and cottony.",
  experiment: "Take a thick fillet and cut it into three even pieces. Cook each to a core of 45C, 50C and 55C with a probe. Press a fork into the thickest part of each and record the temperature at which the sheets first separate under light pressure, and whether the flesh is still translucent at the centre.",
  reflection: "Which of the three would you actually serve, and how far below flaking was it?",
  deepDive: "For a species I name, tell me its collagen behaviour and where I should stop, given how I plan to cook it."
},
{
  id: "protein-cold-water-fish",
  track: "protein", level: "project",
  title: "Cold-water fish proteins denature at lower temperatures",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "A fish's doneness temperature tracks the water it evolved in, so salmon is finished where a tropical species is still underdone.",
  why: "Proteins have to stay folded and functional at body temperature, and for a fish that means water temperature. A species living at 4C only needs myosin stable to a few degrees above that, so its myosin is built with fewer stabilising interactions and unfolds early. A species living at 28C needs more thermal stability and gets it.\n\nSo salmon and ocean trout read as cooked somewhere between 42C and 50C, and pushing them to 60C gives you the white albumin curd and the dry, chalky texture. Warm-water species such as barramundi hold together to higher temperatures and can look raw at the point where salmon is done. The number on a chart is species-specific and the underlying variable is the habitat, not the family.",
  failureMode: "You cook barramundi and Atlantic salmon in the same tray to the same core temperature. One is right, the other is either raw in the middle or has white protein weeping out of every crack, depending on which one you set the timer for.",
  experiment: "Cook a piece of salmon and a piece of barramundi of similar thickness side by side to a core of 48C. Photograph both cut faces. Then press each with a flat spatula on a tared plate for ten seconds and weigh the liquid pressed out of each in grams.",
  reflection: "Which one looked underdone at 48C, and did the press-out weights agree with what your eyes said?",
  deepDive: "Build me a doneness temperature list for the fish I actually buy in Sydney, ordered by habitat temperature, and tell me which ones you are unsure about."
},
{
  id: "protein-dry-ageing",
  track: "protein", level: "project",
  title: "Dry ageing is enzymatic proteolysis plus dehydration",
  source: "Harold McGee, On Food and Cooking",
  idea: "Dry ageing runs two separate processes at once and you pay for both in weight.",
  why: "The tenderising is enzymatic. Calpains, which are active in the first week, and cathepsins, which work more slowly over weeks, cut myofibrillar proteins and the proteins anchoring them, so the structure that resists your teeth is dismantled from inside. This happens in any ageing, wet or dry, and it is largely done in the first two to four weeks.\n\nThe flavour change is dehydration and surface chemistry. Water evaporates from the exposed surface, concentrating everything left behind, while surface moulds and enzymes generate the nutty, cheesy compounds that people mean by dry-aged. That evaporation plus the hard crust you have to trim costs 15 to 30 percent of the starting weight. It is not a free improvement, it is a purchase, and the price per kilogram of edible meat goes up accordingly.",
  failureMode: "You age a single steak on a rack instead of a whole primal with its fat cap on. The exposed surface to volume ratio is enormous, you dry out most of what you started with, and after trimming there is almost nothing left to eat.",
  experiment: "Put a small bone-in primal with its fat cap intact on a rack in a fridge at 1 to 3C with air moving over it. Weigh it at the same time every day for 14 days and write the number down. Plot the daily loss and see when the curve starts to flatten.",
  reflection: "What percentage had you lost by day 14, and at what point did the daily loss stop being significant?",
  deepDive: "Given my fridge and the piece I can get, tell me whether home dry ageing is worth it and what the realistic yield after trim will be."
},
{
  id: "protein-wet-ageing",
  track: "protein", level: "weeknight",
  title: "Wet ageing gives tenderness without the flavour change",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Vacuum-bagged ageing runs the same enzymes with no evaporation, so it changes texture but not aroma.",
  why: "Sealed in plastic, calpains and cathepsins carry on cutting myofibrillar proteins exactly as they would on a rack. Tenderness improves on much the same schedule, with most of the gain in the first two to three weeks. What is missing is everything that depends on water leaving: no concentration of flavour compounds, no surface mould flora, none of the nutty crust chemistry.\n\nThe yield argument is why almost all supermarket beef is wet aged. Nothing evaporates and nothing gets trimmed, so you sell what you bought. It does pick up its own character, a slightly sour metallic note from lactic acid accumulating in a sealed bag, which is the thing people describe as bloody or confined. If you want tender and neutral, wet age. If you want tender and different, you have to pay the water.",
  failureMode: "You expect a wet-aged steak to develop dry-aged flavour if you leave it long enough, so you go to six weeks. You get the same tenderness you had at three weeks plus a sour note, because the flavour pathway you were waiting for needs evaporation that a sealed bag cannot allow.",
  experiment: "Buy one steak, vacuum-seal it and hold it at 1 to 3C for 10 days. On day 10 buy a fresh steak of the same cut from the same butcher. Have someone hand you each one raw with your eyes closed and write down whether you can pick the aged one by smell. Then cook both identically and compare how much force it takes to cut across the grain.",
  reflection: "Could you pick the aged one blind by smell alone, and was the texture difference larger or smaller than the aroma difference?",
  deepDive: "Tell me how long to wet age a cut I name before the tenderness gain stops being worth the fridge space."
},
{
  id: "protein-dry-cured-ham",
  track: "protein", level: "project",
  title: "Dry-cured ham gets its texture from months of proteolysis",
  source: "Harold McGee, On Food and Cooking",
  idea: "Prosciutto is never cooked, so its firmness and its savoury depth come entirely from muscle enzymes working slowly under salt.",
  why: "Salt and time drop the water activity to around 0.90 or below, which stops bacterial spoilage but does not stop the meat's own cathepsins. Over 12 to 36 months those enzymes hydrolyse muscle protein into peptides and then free amino acids. That is where the savoury intensity comes from: glutamate and its relatives accumulate to levels raw meat never reaches, which is why a thin slice tastes of far more than pork.\n\nThe texture is the same reaction seen from the other side. The protein network has been partly dismantled and partly dehydrated, so it is firm and yielding rather than fibrous. The white specks are tyrosine, an amino acid released in such quantity that it exceeds its own solubility and crystallises out. They are a marker of a long cure, not a fault, and they are literally the proteolysis made visible.",
  failureMode: "You send back a leg of jamon because it is full of white crystals, on the assumption they are salt or mould. You have rejected the exact evidence that it was cured long enough to be worth the price.",
  experiment: "Get a piece of long-cured ham sliced two ways, paper thin and about 3mm thick. Taste one of each at room temperature. Write down how long the savoury note lasts on each in seconds, and look for the white specks: note whether they sit in the muscle or along the seams.",
  reflection: "Which thickness delivered more flavour, and did the crystals turn out to be gritty or did they dissolve?",
  deepDive: "Explain how the water activity, salt level and time interact in a dry cure, and what would go wrong if I shortened any one of them."
},
{
  id: "protein-myosin-sausage-bind",
  track: "protein", level: "weeknight",
  title: "Mincing extracts myosin, and that is what binds a sausage",
  source: "Harold McGee, On Food and Cooking",
  idea: "Salt plus mechanical work pulls myosin out of cut fibres into a sticky sol that gels on cooking, and that gel is the whole difference between a sausage and a crumbly patty.",
  why: "Myosin is salt-soluble. Cutting the fibres exposes it, and at around 1.5 to 2 percent salt it dissolves out into the surrounding liquid. Working the mince mechanically drags more of it out and distributes it, and you can feel the moment it happens: the mix goes from loose grains to a tacky mass that pulls away from the bowl in one piece and sticks to your hand.\n\nOn cooking, that dissolved myosin coagulates into a continuous gel running through the whole mass, trapping water and emulsifying fat. Without it you have cooked grains of meat sitting next to each other with nothing between them. This is also the reason a burger and a sausage are made in opposite ways: for a burger you salt only the outside at the last minute, precisely to avoid extracting myosin and getting a bouncy, sausage-like texture.",
  failureMode: "You salt burger mince through the mix an hour ahead, the way you would season anything else, and the patties come out springy and dense like a supermarket meatball. You accidentally made sausage meat.",
  experiment: "Take 300g of mince and 1.5 percent salt by weight, so 4.5g. Mix the salt through evenly, then split into two 150g halves. Work one half hard for 90 seconds with a spoon or your hand and leave the other just mixed. Roll each into a ball, hold it upside down for five seconds and note whether it sags or holds, then cook both and compare how they break.",
  reflection: "Which one held its shape upside down, and how much liquid did each release into the pan?",
  deepDive: "Tell me how to hit a specific texture between crumbly and bouncy for something I am making, and what the salt percentage and working time should be."
},
{
  id: "protein-mince-geometry",
  track: "protein", level: "weeknight",
  title: "Mince needs 71C because contamination is mixed through it",
  source: "J. Kenji Lopez-Alt, The Food Lab",
  idea: "The higher safe temperature for mince is a geometry argument about where the bacteria are, not a judgement about mince as an ingredient.",
  why: "A whole muscle is effectively sterile inside. Contamination lands on the cut surface during processing, and searing that surface takes it well past lethal in seconds. That is why a rare steak is safe at a core of 52C: the core was never contaminated.\n\nGrinding takes every square centimetre of surface and folds it through the mass. Now the geometric centre carries the same bacterial load as the outside did, and the only thing that reaches it is core temperature. Hence 71C instant, or 75C under Australian guidance, which is the instantaneous end of the same pasteurisation curve. If you can hold a temperature you can trade down: a burger held at 55C for a couple of hours reaches the same log reduction and stays pink. The number is not the point, the accumulated lethality is.",
  failureMode: "You grind your own beef from a whole piece and cook it rare, reasoning that you know where the meat came from. You do, but your grinder plate spread whatever was on the outside of that piece straight through the middle, and provenance does not change the geometry.",
  experiment: "Probe the geometric centre of your next burger at the moment you would normally call it done and write down the number. Then keep cooking and note the temperature at which it stops running pink juice. Compare both to 71C.",
  reflection: "How far off was the point you would have called done, and would a held low-temperature cook have got you a better burger at the same safety?",
  deepDive: "Work out a time and temperature hold for a burger that is pink and pasteurised, and tell me what my equipment needs to do to hit it."
},
{
  id: "protein-plant-proteases",
  track: "protein", level: "weeknight",
  title: "Papain and bromelain do not stop at tender",
  source: "Harold McGee, On Food and Cooking",
  idea: "Plant proteases cut proteins indiscriminately and keep going until heat destroys them, so overexposure gives mush rather than tenderness.",
  why: "Pawpaw gives papain, pineapple gives bromelain, figs give ficin, kiwifruit gives actinidin and ginger gives zingibain. All of them are broad-specificity proteases: they cut collagen, which is what you want, and they also cut the myofibrillar proteins that give meat its structure, which is what you do not.\n\nThere is no self-limiting step. The enzyme is a catalyst, so it is not consumed, and it keeps working until heat denatures it. Papain is unusually heat tolerant and stays active up to around 80C, which means it carries on cutting during the early part of the cook. Because diffusion is slow, the damage is worst at the surface: you get a layer a couple of millimetres deep that has gone to paste over an interior that is barely affected. Mushy outside and tough inside is the signature.",
  failureMode: "You marinate steak in fresh pineapple juice overnight, expecting the same logic as a longer brine. The outside comes out grainy and slippery, almost like it has been partly digested, because it has.",
  experiment: "Cut three 50g cubes of beef from the same piece. Sit them in fresh pineapple juice for 15, 30 and 60 minutes. Rinse each, press each between finger and thumb with the same pressure, and write down how far it deforms and whether the surface feels slimy. Then cut each in half and measure how deep the softened layer goes in millimetres.",
  reflection: "How deep did the enzyme get in an hour, and at which interval did useful tenderising become damage?",
  deepDive: "Tell me whether an enzymatic tenderiser is the right tool for a cut I name, or whether time and temperature would do it better."
},
{
  id: "protein-marinade-depth",
  track: "protein", level: "project",
  title: "A marinade reaches about 3mm in a day",
  source: "Cook's Illustrated",
  idea: "A marinade is a surface treatment with a seasoning component, not a way to get flavour into the middle of anything thick.",
  why: "Diffusion through a dense protein gel is slow, and it gets slower as the molecule gets bigger. Sodium and chloride ions are small and charged and move reasonably well, which is why salt does penetrate over hours. The aroma compounds you actually chose the marinade for are ten to a hundred times larger, many of them are oil soluble and will not travel through an aqueous matrix at all, and they measure their progress in single millimetres per day.\n\nAcid makes it worse. It denatures the surface proteins into a tightened layer that slows everything behind it, so a highly acidic marinade partly seals its own entry route. What a marinade genuinely does is season the surface, add sugars and amino acids for browning, and put salt into the outer centimetre. Treat it as a coating and it works. Expect it to flavour the centre of a 5cm piece and it cannot.",
  failureMode: "You marinate a whole lamb leg for two days and taste nothing but lamb in the middle, so next time you go four days. The extra two days buy you maybe another millimetre and a surface that has gone soft from the acid.",
  experiment: "Make a marinade with a strong dye in it, turmeric or beetroot juice, plus salt. Submerge a thick piece of chicken breast or pork loin for 24 hours in the fridge. Cut it clean in half and measure the depth of the colour front with a ruler in millimetres at three points. Taste the centre and note whether it is salty.",
  reflection: "How many millimetres did the colour reach, and did the salt clearly get further than the colour did?",
  deepDive: "Given a piece I am marinating, tell me whether to change the geometry, the salt, or the timing to get flavour where I want it."
}
);
