/* Track: Starch, gels and thickening. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "starch-gelatinisation-window",
  track: "starch", level: "weeknight",
  title: "Starch granules gelatinise between 60C and 80C",
  source: "Harold McGee, On Food and Cooking",
  idea: "A starch granule thickens liquid only after it crosses its gelatinisation temperature, absorbs many times its weight in water and swells until the granules crowd each other.",
  why: "A raw granule is a dense, semi-crystalline packing of amylose and amylopectin chains held together by hydrogen bonds between the chains themselves. In cold water it takes up maybe a third of its own weight and stops, which is why a cold slurry stays a suspension and settles out if you leave it. Heat with water present is what breaks the chain-to-chain bonds and lets water in instead. The granule swells to tens of times its original volume, the ordered regions melt away, and eventually the swollen sac ruptures and leaks amylose into the liquid.\n\nThe viscosity you feel is mostly the swollen granules getting in each other's way, not dissolved starch. That is the whole mechanism. Every starch has its own window: maize about 62C to 72C, potato about 58C to 66C, wheat about 52C to 85C because its granules come in two size populations. Below the window nothing happens no matter how long you hold it.",
  failureMode: "A sauce held at 70C that never quite thickens, so you add more cornflour, and then it hits the boil and goes to wallpaper paste in ten seconds. The starch was never the problem. The pan never reached the number, and by the time it did you had doubled the dose.",
  experiment: "Whisk 10g maize cornflour into 200ml cold water, so a 5 percent slurry. Put a probe in it and heat over a low flame, stirring. Write down the temperature at which the liquid stops looking milky and turns translucent, and the temperature at which it first coats the back of a spoon. Expect the two to be within about five degrees of each other, somewhere in the seventies.",
  reflection: "How far above your measured thickening temperature had you been habitually cooking sauces, and were you actually cooking them long enough to hit it at all?",
  deepDive: "I am thickening a specific dish tonight - tell me which starch suits it, what gelatinisation window that starch has, and what I should see in the pan at each stage."
},
{
  id: "starch-amylose-amylopectin",
  track: "starch", level: "weeknight",
  title: "Amylose sets a gel and amylopectin makes a paste",
  source: "Shirley Corriher, CookWise",
  idea: "Linear amylose chains realign on cooling and lock the liquid into a sliceable gel, while branched amylopectin stays viscous and pourable no matter how cold it gets.",
  why: "Amylose is an unbranched chain of glucose. Once it has leaked out of a burst granule it is free to lie alongside its neighbours, and on cooling long stretches of adjacent chains hydrogen-bond into crystalline junction zones. Those junctions form a three-dimensional network that traps water, which is what a gel is. Amylopectin is the same glucose backbone with a branch roughly every twenty or thirty units, and the branches physically prevent long stretches from lining up. It thickens beautifully while hot and stays fluid when cold.\n\nSo the ratio in your starch is a specification, not a brand difference. Maize cornflour is roughly 28 percent amylose and sets firm. Tapioca and potato starch are much lower and stay glossy and slack. Waxy maize is near zero amylose, which is exactly why industrial sauces that must survive a fridge use it.",
  failureMode: "A pie filling thickened with tapioca that will not hold a cut, so the slice weeps across the plate, or the reverse: a cornflour gravy that was perfect in the jug and has set to a sliceable block in the fridge overnight. Both are the right starch used for the wrong requirement.",
  experiment: "Make two 5 percent slurries, 10g maize cornflour in 200ml water and 10g tapioca starch in 200ml water. Bring both just to the boil, pour into identical ramekins, chill for two hours. Press a spoon into each and photograph the surface. One holds the spoon mark and the other closes over. Note also which one is cloudy and which is glassy.",
  reflection: "Look at the last three things you thickened. For how many of them did you actually need a gel, and for how many did you need a paste that happened to be sitting in a cornflour jar?",
  deepDive: "Here is what I am making and how it will be served, hot or chilled, sliced or spooned - tell me which starch to use and why, in terms of amylose."
},
{
  id: "starch-viscosity-peak",
  track: "starch", level: "project",
  title: "Thickening power peaks at gelatinisation and falls with more boiling",
  source: "Harold McGee, On Food and Cooking",
  idea: "A starch sauce is at its thickest the moment the granules have finished swelling, and every further minute of hard boiling makes it thinner.",
  why: "Peak viscosity is the point where the granules are maximally swollen but still intact, jammed against each other like wet sponges in a box. Keep applying heat and mechanical shear and those fragile swollen sacs fragment. The fragments occupy far less volume than the whole granule did, so the crowding that produced the viscosity goes away. Instruments that measure this on a torque curve show a clear peak followed by a decline, and the decline is called breakdown for exactly that reason.\n\nAcid accelerates it, because hydrogen ions hydrolyse the glucose chains into shorter pieces. This is why a tomato or wine sauce thinned with cornflour loses body faster than a plain one, and why the standard advice is to add acid after thickening rather than before.",
  failureMode: "The gravy that was perfect at the twenty minute mark and is watery when the guests sit down, so you add another slurry, boil that down too, and end up with a sauce that is both thin and tastes of raw starch. The reflex to keep reducing is fighting the mechanism.",
  experiment: "Thicken 600ml of stock with 30g maize cornflour slurry. As soon as it boils, spoon 30ml onto a dinner plate tilted at a fixed angle against a book and time how long the leading edge takes to travel 10cm. Repeat at 5 minutes and 15 minutes of continued boiling, same plate, same angle, same volume. Write down three times. The last one should be the fastest.",
  reflection: "In your normal cooking, how much of the time between thickening and serving is the sauce actually at a rolling boil rather than sitting below a simmer?",
  deepDive: "Walk me through when to add the starch relative to reduction and acid for the sauce I am making, and what viscosity loss I should expect from each step."
},
{
  id: "starch-potato-varieties",
  track: "starch", level: "weeknight",
  title: "Floury and waxy potatoes are a starch content choice",
  source: "Harold McGee, On Food and Cooking",
  idea: "A floury potato has more starch per gram than a waxy one, so its cells swell hard enough to push each other apart into fluff, while a waxy potato holds its shape.",
  why: "Inside a potato cell the starch granules gelatinise as you cook, take on water and expand. In a high dry-matter variety such as Sebago there is enough starch to swell the cell until it rounds off and separates from its neighbours at the pectin-rich middle lamella. You get discrete, dry, mealy cells, which is exactly the structure you want for mash and for a roast potato that shatters. A low dry-matter variety like kipfler or Dutch cream does not generate enough internal pressure, so the cells stay glued together and the flesh stays dense and sliceable.\n\nAmylose ratio matters less here than the marketing suggests. The dominant variable is starch content, measurable as specific gravity, which is why the old trick of floating potatoes in brine sorts them: the floury ones sink. Amylose does its work later, when the mash cools and firms up.",
  failureMode: "Potato salad made with Sebago, which disintegrates into a starchy sludge the moment you fold the dressing through, or mash made with kipfler, which turns gluey because you have to beat a dense potato hard to break it down and beating ruptures cells and releases free starch.",
  experiment: "Boil 200g of Sebago and 200g of kipfler cut to the same 3cm dice in the same salted pot. From the moment the water returns to a simmer, probe one cube of each every three minutes with a skewer and write down the minute at which each variety first sheds a corner into the water. Then make brine at 200g salt per litre and float a whole one of each in it.",
  reflection: "Which variety do you actually buy by default, and is that a decision or just what the shop stacks at the front?",
  deepDive: "Tell me which Australian potato varieties are floury and which are waxy, and what specific gravity range each sits in."
},
{
  id: "starch-rice-amylose",
  track: "starch", level: "weeknight",
  title: "Rice varieties are sorted by amylose content",
  source: "Harold McGee, On Food and Cooking",
  idea: "Long grain rice stays separate because it is high in amylose, short grain sticks because it is low, and risotto rice sits in between on purpose.",
  why: "Amylose retrogrades on cooling and firms up, so a grain full of it sets into a discrete, resilient body that resists sticking to its neighbours. Basmati and most long grain sit around 22 to 25 percent amylose and behave exactly that way. Japanese and Korean short grains sit nearer 15 to 18 percent, and glutinous rice is effectively zero, which is why it clumps hard enough to eat with your fingers. None of this is about grain length as such. Length correlates with amylose because breeders selected the two together.\n\nRisotto rices such as arborio and carnaroli are a middle case with a further trick: a chalky, amylose-poor core surrounded by a firmer outer layer. The outer starch releases into the liquid to make the sauce while the core stays al dente. Carnaroli holds that core longer than arborio, which is the whole reason it costs more.",
  failureMode: "Risotto made with basmati, which never gives up enough starch to make a sauce, so you compensate with cream and produce a rice dish sitting in cream. Or sushi rice made with long grain, which will not hold a shape no matter how you season it.",
  experiment: "Cook 100g basmati and 100g arborio each in 300ml water, same pan type, same 12 minutes. Drain each through a sieve into a clear glass. Photograph the two glasses side by side against a printed page and note which one you can still read through. If you have a scale that reads to 0.1g, evaporate 50ml of each drained liquid in a dry pan and weigh the residue.",
  reflection: "You now have a number for how much starch each rice sheds. Which of the rice dishes you cook actually need that starch in the liquid rather than in the grain?",
  deepDive: "Given the rice I have in the cupboard, tell me its likely amylose content and what dishes it is genuinely suited to."
},
{
  id: "starch-retrogradation",
  track: "starch", level: "weeknight",
  title: "Retrogradation is gelatinised starch recrystallising, and it runs fastest just above freezing",
  source: "Harold McGee, On Food and Cooking",
  idea: "After starch has gelatinised, the dispersed chains slowly find each other again and rebuild crystalline regions that squeeze out water, and the rate of that peaks a few degrees above 0C.",
  why: "Gelatinisation is not permanent. The chains are thermodynamically happier bonded to each other than to water, so given time and mobility they reassociate. Amylose does this fast, within hours, and it is what firms a fresh loaf as it cools and sets a cooled sauce. Amylopectin does it slowly over days, because the branches have to shuffle into position, and that slow process is what stales bread. The water expelled from the crystallites does not leave the loaf. It migrates to the crust, which is why a stale loaf has a leathery crust and a dry crumb at the same time.\n\nRate is a compromise between two things moving in opposite directions. You need molecular mobility, which falls as it gets colder, and you need to be below the melting point of the crystals, which favours cold. The product peaks a little above 0C. Below about minus 7C the chains cannot move at all and staling effectively stops.",
  failureMode: "Treating stale bread as dry bread and trying to fix it with a damp tea towel. The water was never lost. Heating the slice above about 60C melts the amylopectin crystals and genuinely refreshes it, which is why a stale loaf revived in the oven is briefly good again and then stales faster than before.",
  experiment: "Take three slices from the same loaf on the same day. Seal each in its own bag and hold one at room temperature, one in the fridge and one in the freezer for 48 hours. Bring all three to room temperature in the sealed bags, then bend each slice over the edge of a chopping board and record the angle at which it cracks. Rank them.",
  reflection: "Which slice surprised you, and does that change where the bread lives in your kitchen from tomorrow?",
  deepDive: "Explain how retrogradation shows up in the specific starchy thing I am storing, and what the right storage temperature is for it."
},
{
  id: "starch-bread-fridge",
  track: "starch", level: "weeknight",
  title: "Bread stales faster in the fridge than on the bench",
  source: "Shirley Corriher, BakeWise",
  idea: "Refrigerating bread ages it several times faster than leaving it on the bench, because 4C is close to the temperature at which starch recrystallises fastest.",
  why: "This is the direct consequence of the retrogradation rate curve. A loaf held at 4C passes through roughly as much staling in one day as a loaf on the bench does in several. The folk intuition that cold preserves food is correct for microbial spoilage and wrong for this particular physical process, and bread on a two day timescale is limited by staling, not by mould.\n\nThe freezer is the right answer because it skips the fast zone. Below about minus 7C the chains have no mobility and the loaf is effectively frozen in time, so a properly wrapped loaf sliced before freezing and toasted from frozen is closer to fresh than a two day old refrigerated one. The rule is bench for two days, freezer beyond that, fridge never - unless the bread is enriched or filled enough that spoilage genuinely beats staling.",
  failureMode: "Buying good sourdough on Saturday, putting it in the fridge to make it last, and finding it dry and crumbly on Monday while the identical loaf a neighbour left in a paper bag is still fine. The fridge did that.",
  experiment: "Use the three slice test from the previous entry and record the bend angle at which each slice cracks. Then do the second half: toast one slice from the fridge batch and one from the bench batch and see whether toasting erases the difference. Write down both the crack angles and the toast verdict.",
  reflection: "How much bread have you thrown out because it went hard, and how much of that was your fridge doing it?",
  deepDive: "I have this much bread and this many days before I will finish it - tell me the storage plan and the reasoning."
},
{
  id: "starch-three-dispersions",
  track: "starch", level: "weeknight",
  title: "Roux, slurry and beurre manie disperse granules three ways",
  source: "Shirley Corriher, CookWise",
  idea: "All three techniques exist for one reason, to keep starch granules apart until each can hydrate on its own, and they differ only in what does the separating and when.",
  why: "Dry flour hitting hot liquid clumps because the outer granules on each lump gelatinise instantly and form a waterproof skin around dry flour inside. Nothing you whisk afterwards will fix that, because the interior never gets wet. Every dispersion technique is a way of physically isolating the granules before they meet hot water. A roux coats them in hot fat. A cold slurry wets them below the gelatinisation temperature, where they hydrate but cannot swell. A beurre manie coats them in cold soft butter that melts and releases them gradually as it disperses.\n\nThe costs are what should drive the choice. A roux is cooked, so the raw flour taste is gone and you can build a sauce on it, but you have to commit at the start. A slurry is instant and flavourless but goes in raw, so it needs a couple of minutes at the boil and it stays a little cloudy. Beurre manie is the late rescue: whisk knobs into an already finished simmering sauce, adjust by eye, done.",
  failureMode: "Lumps, obviously, but the subtler one is the gravy finished with a slurry thirty seconds before serving. It thickens, so it looks fine, and it tastes chalky and raw because the granules never got the two minutes at the boil they needed to finish swelling and lose the flour flavour.",
  experiment: "Take three 300ml portions of the same stock. Thicken one with a white roux, one with a cold flour and water slurry, one with beurre manie, using plain flour in all three so the comparison is honest. Target the same viscosity, judged by the tilted plate flow test. Weigh the flour each method actually needed and write down three numbers, plus how long each took from decision to done.",
  reflection: "Which method gave you the most control over the endpoint, and is that the one you reach for by habit?",
  deepDive: "For the sauce I am making, tell me which of the three dispersion methods fits the timing and flavour I need, and what quantities to start with."
},
{
  id: "starch-dark-roux",
  track: "starch", level: "project",
  title: "A dark roux thickens a fraction as much as a white one",
  source: "Shirley Corriher, CookWise",
  idea: "Browning a roux breaks the starch chains into shorter fragments, so you trade thickening power for flavour and need roughly twice as much roux for a peanut-coloured one and more again for a dark one.",
  why: "Prolonged dry heat with fat does two things to flour at once. It runs Maillard and caramelisation reactions on the flour proteins and sugars, which is where the nutty, toasted flavour comes from, and it hydrolyses and pyrolyses the starch chains, chopping long polymers into dextrins. Short chains cannot build the swollen, crowded network that produces viscosity. The darker the roux, the shorter the average chain, the weaker the body.\n\nSo the two things you want from a roux move in opposite directions and you cannot have both from the same quantity. A blond roux is close to full strength. A peanut-brown roux is around half. A dark chocolate roux is weaker still, which is why gumbo recipes use volumes of roux that look absurd next to a bechamel and why gumbo body comes partly from okra or file powder instead.",
  failureMode: "Substituting a dark roux for a light one at the same weight, getting a thin sauce, and reducing it hard to compensate. Reducing concentrates the browned flavours too, so you end up with something both bitter and still loose. The right move is more dark roux, not less liquid.",
  experiment: "Make two rouxs from 50g plain flour and 50g butter each, one cooked to white and one to milk chocolate, roughly 20 to 30 minutes over low heat with constant stirring. Add hot stock to each in 100ml increments, whisking, until each reaches the same consistency on the tilted plate test. Write down the total millilitres each absorbed. The ratio between those two numbers is your correction factor.",
  reflection: "What did the dark roux smell like at the point you stopped, and would you have pushed it further if you had not needed the thickening?",
  deepDive: "I want this much body and this much toasted flavour - work out the roux colour and quantity, and tell me what else could carry the body if the roux cannot."
},
{
  id: "starch-reduction-gelatin",
  track: "starch", level: "weeknight",
  title: "Reduction thickens with gelatin and dissolved solids, not starch",
  source: "Harold McGee, On Food and Cooking",
  idea: "Boiling a stock down raises viscosity by concentrating the gelatin and solids already dissolved in it, which is a completely different mechanism from adding starch and behaves differently on cooling.",
  why: "Gelatin is collagen that has been hydrolysed into long, flexible protein chains. In hot liquid those chains are a random coil and contribute modest viscosity. Concentrate them by driving off water and the coils start to overlap and entangle, and viscosity climbs steeply, non-linearly, once you get past a threshold concentration. Below about 15C to 20C the chains partially re-form their triple helix and the whole thing sets. That is why a properly reduced stock is a rubbery block in the fridge and a starch sauce is not.\n\nThe practical difference is mouthfeel and behaviour. A gelatin-thickened sauce coats the palate and then melts, because gelatin melts below body temperature. A starch sauce coats and stays coating. It is also why a reduction rewards a stock made from joints, trotters and wings, and why a reduction made from a stock cube will concentrate salt and never gain body.",
  failureMode: "Reducing a commercial liquid stock for forty minutes waiting for it to thicken. Most of them have negligible gelatin, so all you achieve is a salt concentrate. You find out when you taste it, by which point there is no way back.",
  experiment: "Reduce 500ml of your stock to 150ml, weighing the pan on the scale so you know when you are there. Taste for salt at the start and the end. Pour 20ml into a small container and put it in the fridge for two hours, then tip it on its side. Write down whether it holds, slumps, or pours. That single observation tells you whether your stock has gelatin in it.",
  reflection: "If it poured, what would you change about how you make stock - the cuts, the time, or the temperature?",
  deepDive: "Tell me which cuts and what simmering schedule will get enough gelatin into a stock that reduces to a sauce that sets."
},
{
  id: "starch-gelatin-melt",
  track: "starch", level: "weeknight",
  title: "Gelatin melts at about 30C, which is why it melts in the mouth",
  source: "Harold McGee, On Food and Cooking",
  idea: "Gelatin is the only common gelling agent whose melting point sits below body temperature, and every sensation people describe as luxurious in a jelly, a terrine or a reduced sauce comes from that one number.",
  why: "A gelatin gel is a network of protein triple helices that form as the liquid cools past roughly 15C to 20C. Those helices are held together by hydrogen bonds and they come apart again with a small amount of heat, at around 30C to 35C depending on concentration. Put a cube on your tongue at 37C and the network dissolves under you. The gel does not fracture, it liquefies, and it releases all its dissolved aroma at once as it goes.\n\nNothing else in the common toolkit does this. Agar melts at 85C and above, so it never melts in the mouth and reads as brittle. Pectin gels are thermally irreversible in the high-sugar case. Starch pastes do not melt at all. If a dish is supposed to disappear rather than be chewed, gelatin is not a preference, it is the only agent that behaves that way.",
  failureMode: "Substituting agar for gelatin in a panna cotta because both are gelling agents. The set is technically correct and the eating experience is wrong: it fractures cleanly instead of collapsing, and the flavour arrives late and muted because the gel never dissolves in your mouth.",
  experiment: "Set two jellies from the same 300ml of cordial, one with 6g of gelatin leaves bloomed in cold water, one with 3g of agar boiled in for two minutes. Chill both. Put a 2cm cube of each on your tongue, hold it still without chewing, and time to the second how long each takes to disappear. Then put a cube of each on a warm plate and leave them for ten minutes. Write down four observations.",
  reflection: "Which of the two did you want to keep eating, and can you say in one sentence what physical event you were enjoying?",
  deepDive: "For the set dish I am making, tell me whether the melt-in-mouth property matters, and pick the gelling agent and dose from that."
},
{
  id: "starch-agar-hysteresis",
  track: "starch", level: "project",
  title: "Agar sets around 35C and does not melt again until 85C",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Agar has roughly 50 degrees of hysteresis between its setting and melting temperatures, which is what lets a gel sit on a warm plate without collapsing.",
  why: "Agar is a polysaccharide from red seaweed, agarose plus agaropectin, and its network forms from double helices that then aggregate into thick bundles. Making those bundles is easy on cooling and hard to undo on heating, because you have to supply enough energy to pull apart the aggregate as well as the individual helices. So the sol-gel transition is not reversible at the same temperature the way gelatin is. It sets at about 32C to 43C and does not melt again until about 85C to 95C.\n\nThat gap is the whole reason to use it. A warm gel, a gelled sauce that survives service under a heat lamp, an agar fluid gel sheared while setting into a pourable but stable texture: all of these depend on a gel that forms at kitchen temperature and stays formed at eating temperature. The cost is texture. Agar gels are firm and brittle and release flavour poorly, because they never dissolve in your mouth.",
  failureMode: "Adding agar to a hot liquid and expecting it to hydrate. It needs a proper boil, around 90C for a minute or two, to disperse. Sprinkle it into an 80C sauce and you get grit that never dissolves and a liquid that never sets, and you will not find out until it has been in the fridge for an hour.",
  experiment: "Make a 1 percent agar gel, 3g agar in 300ml water, boiled for two minutes and poured into a shallow tray. Once set, cut a cube, put it in a small pan with a probe touching it, and warm gently. Record the temperature at which the cube visibly slumps and the temperature at which it is fully liquid. Then let it cool with the probe in and record the temperature at which it stops flowing. Two numbers, roughly 50 degrees apart.",
  reflection: "What dish have you avoided making because a gel would have melted, and does that 50 degree gap unlock it?",
  deepDive: "Given the serving temperature and the texture I want, tell me whether agar, gelatin or a blend is right, and at what percentage."
},
{
  id: "starch-pectin-sugar-acid",
  track: "starch", level: "project",
  title: "Pectin needs sugar and acid, unless it needs calcium",
  source: "Harold McGee, On Food and Cooking",
  idea: "High-methoxyl pectin gels only in the presence of a lot of sugar and a low pH, while low-methoxyl pectin cross-links with calcium instead, so a low-sugar jam is a different chemistry rather than a smaller version of the same one.",
  why: "Pectin chains carry negatively charged carboxyl groups that repel each other and hold the chains apart. High-methoxyl pectin, the kind in ordinary fruit, has most of those groups capped as methyl esters, so the remaining charge is what keeps it dispersed. Acid below about pH 3.5 protonates the rest and kills the repulsion, and sugar above about 55 percent competes for the water that was hydrating the chains. Strip both away and the chains have nothing to do but bond to each other. That is a high-sugar jam.\n\nLow-methoxyl pectin has far fewer methyl esters, so it has more free carboxyl groups, and divalent calcium ions can bridge two chains directly in the so-called egg-box structure. That needs no sugar and works up to about pH 6.5. It is why commercial jam setta for reduced-sugar jam lists calcium salts, and why the same recipe made with ordinary pectin and half the sugar simply will not set.",
  failureMode: "Halving the sugar in a traditional jam recipe to make it healthier and getting fruit syrup. Nothing was wrong with the fruit or the boiling. The sugar was a reagent, not a sweetener, and you removed half of it.",
  experiment: "Make a small jam, 500g fruit and 350g sugar, and boil it. Watch a probe for the set point, which is 104C to 105C at sea level, because that boiling point elevation is a direct readout of sugar concentration. At that moment take a teaspoon out, cool it, and touch a pH strip to it. Write down the temperature and the pH. Then do the cold plate wrinkle test and see whether it agrees with the thermometer.",
  reflection: "Your pH reading either was or was not below 3.5. If it was above, what acid would you add next time and how much?",
  deepDive: "Here is the fruit I have and how sweet I want the jam - tell me whether to use high or low methoxyl pectin, and what sugar, acid or calcium the set will need."
},
{
  id: "starch-gluten-development",
  track: "starch", level: "weeknight",
  title: "Gluten is glutenin plus gliadin plus water plus work",
  source: "Shirley Corriher, BakeWise",
  idea: "Flour does not contain gluten, it contains two proteins that form gluten once you hydrate them and apply mechanical work.",
  why: "Glutenin is a long, coiled molecule that provides elasticity, the tendency to spring back. Gliadin is compact and globular and provides extensibility, the tendency to flow and stay stretched. Dry, they sit inert in the endosperm. Add water and they hydrate and become mobile. Add work, whether kneading, folding or just time under hydration, and the glutenin molecules align, entangle, and link through disulfide bonds formed between cysteine residues, building a continuous viscoelastic network through the dough.\n\nThat means gluten strength is a variable you control at three points: protein content of the flour, hydration level, and work applied. Autolyse works because at high hydration the network partly builds itself through molecular motion alone, given twenty or thirty minutes. Salt tightens the network by shielding the charges that keep chains apart, which is why a dough salted from the start feels stiffer than the same dough salted later.",
  failureMode: "A pizza dough that tears into holes every time you stretch it, because it is under-developed, or a shortcrust that shrinks up the sides of the tin in the oven, because it is over-developed and the elastic network is contracting. Both are the same variable set wrong in opposite directions.",
  experiment: "Mix 100g bread flour with 65g water until just combined, no salt. Split into two 80g pieces. Rest one under a bowl for ten minutes and knead the other for five minutes by the clock. Then take each and stretch it slowly between your hands into a windowpane. Measure with a ruler how wide each gets before it tears, and hold each up to the light to see whether you can see through it.",
  reflection: "How much of the difference came from the kneading and how much from the rest, and what does that suggest about how hard you actually need to work your doughs?",
  deepDive: "For the dough I am making tonight, tell me how much gluten development it needs and the cheapest way to get there - hydration, time, or kneading."
},
{
  id: "starch-fat-shortening",
  track: "starch", level: "weeknight",
  title: "Fat shortens gluten and that is the point of pastry",
  source: "Shirley Corriher, BakeWise",
  idea: "Fat coats flour particles and physically blocks the proteins from linking into a continuous network, so the more thoroughly you rub it in, the shorter and more tender the result.",
  why: "The word shortening is literal. Fat interrupts the gluten strands, so instead of one continuous elastic web running through the dough you get short, discontinuous segments separated by greasy interfaces. A short crumb is one where the structure breaks under small deformation rather than stretching, which is exactly what you want to feel when you cut a shortcrust with a fork. Water is the enemy of this, which is why pastry recipes are miserly with it and why an egg yolk is a better binder than an equal volume of water.\n\nThe consequence people miss is that particle size of the fat is the control knob. Butter rubbed to fine breadcrumbs coats a lot of flour surface and gives a uniformly short, sandy, biscuity crust. Butter left in flattened 10mm lumps coats very little, so most of the flour is free to form gluten, and the lumps instead melt in the oven and leave voids that steam inflates. That is flakiness. Short and flaky are opposite outcomes of the same ingredient.",
  failureMode: "Rubbing the butter in thoroughly and then wondering why the pie lid is tender and sandy rather than flaky and layered. Nothing failed. You chose short and wanted flaky, and the fork you rubbed with made that choice for you.",
  experiment: "Make two shortcrusts, each 200g plain flour, 100g cold butter, 45ml iced water. In the first, rub the butter to fine breadcrumbs. In the second, flatten the butter into 10mm coins and toss them through, leaving them intact. Rest both, roll both to 3mm, bake both blind at 190C for 18 minutes. Snap a piece of each and note which shatters and which peels. Photograph the broken edges.",
  reflection: "Which of the two matches the pastry you thought you were making all these years, and what were you doing with the butter to get it?",
  deepDive: "I want this specific pastry texture - tell me the fat, the particle size, the hydration and the handling that produces it."
},
{
  id: "starch-lamination",
  track: "starch", level: "project",
  title: "Lamination is solid fat holding layers apart until steam inflates them",
  source: "Nathan Myhrvold, Modernist Bread",
  idea: "Laminated pastry works only if the butter stays a continuous solid sheet through every roll and melts for the first time in the oven, where the water in the dough flashes to steam and pushes the layers apart.",
  why: "The butter is not a flavouring or a shortener here, it is a barrier. Its job is to keep adjacent dough layers from fusing, so that when the water in the dough turns to steam in the oven the gas has nowhere to go but between the sheets. Each dough layer sets from the outside in as the temperature climbs, locking the expansion in place. If the butter has smeared into the dough at any point in the rolling, that region has no barrier, the layers fuse, and the pastry there is bread.\n\nThat is why temperature is the entire discipline. Butter below about 12C is brittle and cracks into shards when you roll, which punctures the sheet. Above about 18C it is soft enough to be absorbed into the dough. The window is roughly 13C to 17C, and the dough has to match it in firmness, because if the dough is much softer than the butter the butter will punch through it instead of stretching with it.",
  failureMode: "Butter leaking out at the edges during baking and the pastry sitting in a pool of fat, with a dense wet layer at the base. That means the sheet broke during rolling, usually because the block came straight out of a 4C fridge and shattered on the first turn.",
  experiment: "Make a small laminated block, 250g dough and 125g butter, and give it three single folds. Before each roll, probe the butter block and the dough and write down both temperatures. Rest in the fridge until both are between 13C and 17C before you roll. Bake a strip and count the layers on the cut edge against your fold arithmetic - three single folds on one butter layer should give 27.",
  reflection: "How many layers did you actually count against 27, and where in the process do you think the missing ones fused?",
  deepDive: "Talk me through the fold schedule and resting temperatures for the laminated pastry I am attempting, and what to check before each turn."
},
{
  id: "starch-pasta-water",
  track: "starch", level: "weeknight",
  title: "Pasta water is a dilute starch solution that stabilises the sauce",
  source: "Harold McGee, On Food and Cooking",
  idea: "Amylose leached off the pasta surface thickens the water slightly and helps hold fat and water together, which is why a splash of it turns oil and cheese into a sauce instead of a slick.",
  why: "As the outer layer of a dried pasta hydrates and gelatinises, some of its starch dissolves into the cooking water. That water is then a dilute starch solution, typically around one to two percent of the pasta's dry weight ends up in it. Two things follow. The dissolved amylose raises viscosity, which slows the rate at which dispersed oil droplets can find each other and coalesce. And the starch adsorbs at the oil and water interface, giving a physical barrier between droplets. Neither is a true emulsifier in the way an egg yolk is, but together they are enough to hold a short-lived sauce through service.\n\nThis is the argument against the large pot. Cooking in a lot of water dilutes the starch you are about to rely on. Cook 100g of pasta in 500ml rather than four litres and the same starch is four to eight times more concentrated, and the water you pull off is meaningfully thicker.",
  failureMode: "Cacio e pepe that seizes into a stringy clump or splits into oil and grit. Either the water was too hot, so the cheese proteins coagulated, or it was too dilute to carry the fat. Water straight from a four litre pot often is.",
  experiment: "Boil 100g of dried pasta in exactly 500ml of water, topping up only if it threatens to boil dry. Measure 100ml of the finished cooking water into a small dry pan, weigh the pan first, and evaporate the water off over low heat until nothing changes. Weigh the pan again. The difference minus the salt you added is your starch yield. Expect a few tenths of a gram, so use a scale that reads to 0.1g.",
  reflection: "Now that you have a number, is the water in your usual pot concentrated enough to be doing anything, or have you been adding a splash of hot salty nothing?",
  deepDive: "For this pasta and this sauce, tell me how much water to cook in and how to use the starchy water to bring the sauce together."
},
{
  id: "starch-risotto-abrasion",
  track: "starch", level: "weeknight",
  title: "Risotto's cream is starch abraded off the grain",
  source: "Peter Barham, The Science of Cooking",
  idea: "The creaminess of a risotto comes from surface starch rubbed off the grains by stirring and gelatinised in the liquid, not from dairy and not from the variety by itself.",
  why: "Arborio and carnaroli have a soft, amylopectin-rich outer layer over a firmer core. Cooking hydrates and gelatinises that outer layer and makes it soft enough to shear away. Stirring provides the shear: grains rubbing against grains and against the pan release swollen surface starch into the liquid, where it continues to swell and thickens the whole thing. The core, being denser and lower in released starch, stays intact and gives the bite. Two textures from one grain, achieved by mechanical means.\n\nThat is also why the liquid goes in gradually. Keeping the ratio of liquid to rice low maintains a thick, abrasive slurry where the grains are in constant contact, and it keeps the released starch concentrated instead of diluted. Flooding the pan with all the stock at once gives you boiled rice in a thin broth, no matter how much you stir at the end.",
  failureMode: "Risotto that is soupy and separate, fixed at the last minute with a large amount of butter and parmesan. That produces a rich dish sitting in stock rather than a bound one. The fat is masking a missing starch phase, and you can tell because it splits as it cools on the plate.",
  experiment: "Cook two risottos from 150g arborio each, same stock, same ladle schedule. Stir one constantly and the other twice in the whole cook. Spoon 60g of each onto a plate tilted against a book at the same angle and measure with a ruler how far each spreads in 30 seconds. Write down two distances. Do this before adding any butter or cheese.",
  reflection: "How much of the creaminess you have been chasing came from the stirring, and how much were you buying with butter?",
  deepDive: "Diagnose my risotto technique against the abrasion mechanism - liquid ratio, pan choice, stirring, and when to stop."
},
{
  id: "starch-custard-window",
  track: "starch", level: "project",
  title: "Custard coagulates between 79C and 85C, and starch raises the ceiling",
  source: "Shirley Corriher, BakeWise",
  idea: "A stirred egg custard thickens and then curdles inside a band a few degrees wide, and adding even a small amount of starch widens that band enough to let you boil the mixture.",
  why: "Egg proteins unfold with heat and then bond to each other into a loose three-dimensional mesh that traps liquid. In a dilute custard the yolk proteins start doing this around 79C to 80C and the mesh is what makes it coat a spoon. A few degrees further and the bonds keep forming and tightening, the mesh contracts, and it squeezes out the water it was holding. That is curdling: not burning, but the same reaction going too far. Sugar and dilution both push the whole window a few degrees higher by getting between the proteins.\n\nStarch changes the game because gelatinised starch physically interferes with protein cross-linking and because the swollen granules keep the proteins apart. With 30g or so of cornflour per litre you can take the mixture to a full boil without graining. You have to, in fact: raw egg yolk contains alpha-amylase, which will digest the starch and turn your pastry cream to soup in the fridge overnight, and only a proper boil for a minute or two destroys it.",
  failureMode: "Perfect pastry cream that is watery the next morning. Nobody did anything wrong at the mixing stage. The custard was pulled at 85C like a creme anglaise, the amylase survived, and it spent the night eating the starch.",
  experiment: "Make a creme anglaise from 4 yolks, 50g sugar and 500ml milk, with a probe in the pan the whole time. Write down the temperature at which it first coats the back of a spoon and holds a drawn line, then keep going deliberately and write down the temperature at which the first grains appear. Two numbers. Then whisk in 15g of cornflour slurry, bring it to a full boil, and see whether it curdles.",
  reflection: "How wide was your window between coating and graining, and is that wider or narrower than you had been assuming when you cook without a probe?",
  deepDive: "For the custard I am making, tell me the target temperature, whether it needs starch, and what the boil is doing if it does."
},
{
  id: "starch-split-diagnosis",
  track: "starch", level: "project",
  title: "A split sauce has three causes and three different repairs",
  source: "Harold McGee, On Food and Cooking",
  idea: "Sauces fail by protein coagulation, by emulsion coalescence or by starch breakdown, and since the repair for each is different, diagnosing which one happened matters more than any rescue trick.",
  why: "Protein coagulation is a hollandaise or a custard taken too hot: the egg proteins bond to each other, contract, and expel the liquid they were holding. You see visible solid grains suspended in thin liquid. It is largely irreversible, because the disulfide and hydrophobic bonds do not undo, and the best you can do is blend or sieve the grains out and rebuild.\n\nEmulsion coalescence is a beurre blanc or a mayonnaise where the dispersed droplets have merged into a continuous fat phase. The tell is a clear split into two liquid layers with no grain. It is fully reversible: start again with a small amount of the continuous phase, usually a spoon of water or a fresh yolk, and whisk the broken sauce into it slowly.\n\nStarch breakdown is a thickened sauce that has gone thin and slack with no visible separation at all. Acid hydrolysis over long cooking is the common cause; enzymatic attack is the other, from raw egg yolk amylase in an unboiled pastry cream or from a tasting spoon returned to the pot, since saliva is full of amylase. The repair is more starch, added late, and no more boiling.",
  failureMode: "Whisking harder. It is the reflex for all three and it only works for one. Whisking a curdled hollandaise emulsifies the protein grains into a fine grit that you can no longer sieve out, which converts a recoverable sauce into a lost one.",
  experiment: "Split three small sauces on purpose. Overheat a two yolk hollandaise past 85C. Break a beurre blanc by adding cold butter to a pan over high heat. Thin a cornflour-thickened sauce by simmering it with 30ml of lemon juice for fifteen minutes. Photograph all three and write one sentence describing what you see in each. Then attempt the matching repair on each and record which worked.",
  reflection: "Next time a sauce breaks, what is the first thing you will look at before you touch a whisk?",
  deepDive: "My sauce just broke - here is what it looks like and what I did to it. Tell me which of the three failure modes it is and whether it is recoverable."
}
);
