/* Track: Flavour chemistry and perception. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "flavour-taste-versus-smell",
  track: "flavour", level: "weeknight",
  title: "Taste has five channels and flavour is mostly smell",
  source: "Harold McGee, Nose Dive",
  idea: "The tongue reports sweet, sour, salty, bitter and umami, and everything else you call flavour is aroma arriving retronasally.",
  why: "Taste receptors sit on the tongue and palate and respond to non-volatile molecules dissolved in saliva. There are five well-established channels and they are low-resolution: sugars and some alcohols on sweet, protons on sour, sodium on salty, a family of around twenty-five receptors on bitter, free glutamate and aspartate on umami. That is the entire taste vocabulary.\n\nEverything that lets you tell coffee from cocoa, or lamb from beef, is volatile molecules reaching the olfactory epithelium at the roof of the nasal cavity. When you chew and swallow, warmed air carrying those volatiles is pumped up the back of the throat into the nose from behind. That is retronasal olfaction, and the brain files it as taste because it arrives while the mouth is busy. Block the nose and the dish collapses to five dimensions plus texture and temperature.",
  failureMode: "You cook with a head cold, keep adding salt because the dish reads flat, and end up with something you cannot eat two days later when your nose comes back. The missing channel was never salt.",
  experiment: "Pinch your nose shut, put a jelly bean or a fruit pastille in your mouth and chew. Write down what you can detect: it will be sweet, sour and a texture, with no identity. Keep chewing and release your nose. Write down how many seconds pass before the flavour name arrives. It is usually under two.",
  reflection: "When the identity appeared, did anything about the intensity of sweetness change too, or only the identification?",
  deepDive: "Take a dish I cooked that tasted flat and help me work out whether the missing element was a taste, an aroma, or a mouthfeel, and what test would separate them."
},
{
  id: "flavour-umami-receptor",
  track: "flavour", level: "weeknight",
  title: "Umami is free glutamate binding a specific receptor, not richness in general",
  source: "Ole Mouritsen and Klavs Styrbaek, Umami",
  idea: "Umami is the taste of free glutamate activating the T1R1 and T1R3 receptor pair, so anything that liberates glutamate from protein raises it.",
  why: "Glutamate bound inside a protein chain is tasteless. The receptor needs the free amino acid, with its carboxyl and amino groups exposed. This is why the umami-heavy ingredients of every cuisine are the ones where protein has been taken apart: aged parmesan, soy sauce, fish sauce, anchovies, cured ham, ripe tomatoes, kombu. Ageing, fermentation, enzymatic ripening and long cooking are four different mechanisms doing the same job, which is hydrolysing peptide bonds and releasing amino acids into solution.\n\nRipe tomatoes carry roughly 150 to 250 mg of free glutamate per 100g, parmesan aged two years carries over 1200 mg, and kombu can exceed 2000 mg. Fresh beef is low in free glutamate despite being almost entirely protein. That gap is the whole point: protein content and umami are not the same measurement.",
  failureMode: "You add more meat to a stew that tastes thin and it stays thin, because raw muscle protein contributes almost no free glutamate. A 20g anchovy fillet or 15g of tomato paste would have moved it further than another 200g of chuck.",
  experiment: "Dissolve 0.5g of MSG in 100ml of warm water, which is 0.5 per cent, and taste it against 100ml of plain warm water. Write down where in the mouth you feel each one and how long the sensation lasts after swallowing. The MSG solution should read as mouth-filling and persistent rather than strong, and should not read as salty.",
  reflection: "Did the glutamate solution taste like anything you would call a flavour, or only like a sensation with no identity attached?",
  deepDive: "Here is a dish that tastes thin; list the free-glutamate sources I could add, with approximate mg per 100g, and tell me which one fits without changing the flavour profile."
},
{
  id: "flavour-nucleotide-synergy",
  track: "flavour", level: "project",
  title: "Ribonucleotides multiply glutamate rather than adding to it",
  source: "Ole Mouritsen and Klavs Styrbaek, Umami",
  idea: "Inosinate and guanylate bind the same receptor complex as glutamate and raise its affinity, so the two together taste several times stronger than the sum of the parts.",
  why: "The T1R1 and T1R3 dimer has a binding pocket shaped like a Venus flytrap. Glutamate binds inside it. The 5-prime ribonucleotides, inosinate from animal tissue and guanylate from fungi, bind at a site nearby and stabilise the closed conformation, so the receptor holds glutamate longer and signals harder at the same concentration. This is allosteric enhancement, not a second taste being added.\n\nThe effect is multiplicative and large. For an equal mix of glutamate and inosinate the perceived intensity is commonly reported as around eight times what the same total weight of either alone would give, and the peak sits near a one to one ratio. That is why so many unrelated traditions pair a glutamate source with a nucleotide source without ever knowing why: kombu with katsuobushi, tomato with parmesan, tomato with anchovy, mushroom with soy, chicken stock with dried shiitake.",
  failureMode: "You buy MSG, taste it neat, decide it is one-dimensional, and stop. Used alone at 0.5 per cent it is mouth-filling but flat. The interesting behaviour only appears once a nucleotide is in the same glass.",
  experiment: "Make three 100ml warm-water solutions with the same total solute weight of 0.5g: one all MSG, one all dried shiitake powder or instant dashi granules, one 0.25g of each. Taste in that order and rank them for intensity from 1 to 3. If the mixture does not clearly beat both singles, your nucleotide source is too weak and you need a stronger one.",
  reflection: "How much stronger did the mixture read, in the sense that you would guess it contained roughly how many times as much solute as it actually did?",
  deepDive: "Look at the ingredient list for this dish and tell me which items supply glutamate, which supply inosinate or guanylate, and whether the pairing is already there or missing."
},
{
  id: "flavour-dashi",
  track: "flavour", level: "weeknight",
  title: "Dashi is receptor synergy with nothing else in the way",
  source: "Ole Mouritsen and Klavs Styrbaek, Umami",
  idea: "Kombu supplies glutamate and katsuobushi supplies inosinate, so a stock made in ten minutes with no browning, no fat and no aromatics gets its depth entirely from synergy.",
  why: "Every other stock tradition builds flavour by stacking mechanisms: Maillard products from roasted bones, gelatin from connective tissue, fat-soluble aromatics from mirepoix, hours of extraction. Dashi does none of that. Kombu contributes roughly 1500 to 3000 mg of free glutamate per 100g of dry weight and almost nothing else you would call flavour. Katsuobushi contributes inosinate at several hundred mg per 100g, from the breakdown of muscle ATP during drying and fermentation. Neither ingredient tastes like much alone at stock dilution.\n\nThe technique details are chemistry, not ritual. Kombu is held below the boil, around 60C, because boiling extracts alginates and bitter compounds along with the glutamate. Katsuobushi goes into water off the heat at about 80C for a minute or two, because the shavings are thin and prolonged heat pulls out sour and fishy notes. Both constraints exist to keep everything except the two target molecules out of the pot.",
  failureMode: "You simmer the kombu for twenty minutes to extract more, and get a slick, faintly bitter, marine-smelling liquid. You extracted more of everything, and most of the everything was not glutamate.",
  experiment: "Make three 300ml infusions with the same water. A: 3g kombu, held at 60C for 20 minutes. B: 6g katsuobushi in 80C water for 90 seconds, strained. C: both, kombu first then katsuobushi. Taste all three unsalted and score each from 1 to 10 for intensity. Write the three numbers down. C should beat A plus B, not sit between them.",
  reflection: "Did either single infusion taste like a stock on its own, or did they only become one when combined?",
  deepDive: "I want to build the same synergy into a Western stock without it tasting Japanese; suggest glutamate and nucleotide sources that fit and the quantities per litre."
},
{
  id: "flavour-volatility-temperature",
  track: "flavour", level: "weeknight",
  title: "Aroma release is a vapour pressure problem, so temperature changes which smells you get",
  source: "Harold McGee, Nose Dive",
  idea: "Vapour pressure rises roughly exponentially with temperature, so a hot dish sends far more volatiles to your nose than a cold one, and it sends a different mix.",
  why: "An aroma compound only reaches you if it leaves the food and enters the air. How readily it does that is set by its vapour pressure at that temperature and its solubility in the food matrix. Vapour pressure climbs steeply with heat, so warming a dish from 20C to 60C can multiply headspace concentration many times over.\n\nThe part that matters more than the intensity is the reordering. Each compound has its own vapour pressure curve. Light molecules such as short-chain aldehydes and esters are already airborne at room temperature and dominate a cold dish. Heavier ones such as pyrazines, vanillin and many sulfur compounds need heat before they contribute at all. So a soup at 60C is not a louder version of the same soup at 20C, it is a different aroma profile with different compounds leading.",
  failureMode: "You taste a braise straight off the stove at 85C, judge the seasoning, then serve it at 60C into cold bowls and it reads as a different dish. You calibrated at a temperature nobody eats at.",
  experiment: "Take one soup and pour three 50ml samples. Bring one to 60C, one to 40C and let one sit at 20C. Smell each with a short sniff and write exactly three descriptor words for each, then compare the three lists. Count how many words appear on the 60C list that do not appear on the 20C list.",
  reflection: "Was the difference between 60C and 20C mostly a change in intensity, or did entirely different descriptors show up?",
  deepDive: "Given the serving temperature I actually use for this dish, tell me what to change about how I season and taste it while cooking."
},
{
  id: "flavour-cold-dish",
  track: "flavour", level: "weeknight",
  title: "A cold dish tastes weaker for two independent reasons",
  source: "Ole Mouritsen and Klavs Styrbaek, Mouthfeel",
  idea: "Cold both suppresses aroma release and reduces taste receptor sensitivity, so a chilled dish needs more salt and more acid than the same dish hot.",
  why: "The first reason is the vapour pressure effect: fewer volatiles in the headspace and fewer reaching the olfactory epithelium retronasally, so the aroma half of flavour drops away. The second is separate and happens on the tongue. The transduction machinery for sweet, bitter and umami runs through TRPM5, an ion channel that is itself temperature sensitive and conducts far better warm than cold. Sweetness in particular falls off sharply below about 15C.\n\nSalty and sour are less affected, which is why the balance shifts rather than just fading. A vinaigrette or a gazpacho tasted warm at the bench and served at 5C will read as thin and unbalanced, not merely quiet. Commercial ice cream mixes are famously oversweet when tasted warm because they have to be, and a chilled soup follows the same logic.",
  failureMode: "You season a soup perfectly at the stove, chill it overnight for a hot Sydney evening, and serve something that tastes of nothing in particular. Then you salt it at the table and it goes straight past correct to salty, because you were correcting an aroma deficit with a taste lever.",
  experiment: "Season 300ml of a soup to taste at 60C. Put 100ml in the fridge for an hour. Taste the cold portion and add salt in 0.1g increments until it reads the same as the hot version did, weighing each addition. Write down the total grams added per 100ml. Then note whether it is now correct or just salty, and whether 2ml of lemon juice does more than the last 0.1g of salt did.",
  reflection: "Did the extra salt actually restore the dish, or did it fix the taste channel while the aroma stayed missing?",
  deepDive: "I am serving this dish cold; tell me what to adjust in seasoning and acid relative to the hot version, and what to check at serving temperature."
},
{
  id: "flavour-fat-carries-aroma",
  track: "flavour", level: "project",
  title: "Fat is an aroma reservoir, not a taste",
  source: "Harold McGee, Nose Dive",
  idea: "Most aroma molecules are more soluble in fat than in water, so fat holds them, releases them slowly, and changes the timing of flavour rather than its identity.",
  why: "Aroma compounds are mostly small and largely non-polar: terpenes, esters, aldehydes, pyrazines, thiols. Their partition coefficient strongly favours the fat phase in a mixed system. In a fatty dish, most of the aroma load is dissolved in the fat and only the fraction in equilibrium with the water phase and the headspace is available to your nose at any moment. As you chew, swallow and warm the fat, that reservoir keeps topping up the headspace.\n\nThe consequence is a time profile. A watery infusion delivers its aroma in a burst that peaks early and is gone in seconds. A fatty one delivers less at the peak and keeps delivering for half a minute or more. Removing fat from a dish therefore does not evenly reduce flavour, it truncates it, and the usual complaint about low-fat food is a complaint about a short finish. Fat also has genuine tactile and possibly gustatory dimensions, but the aroma carrier role is the one that changes how a dish is perceived.",
  failureMode: "You skim every trace of fat off a stock for clarity, then wonder why the finished soup smells right in the bowl and disappears the moment you swallow. The volatiles had nothing to sit in.",
  experiment: "Warm 100ml of water and 100ml of neutral oil to 60C. Put 3g of chopped rosemary or a crushed garlic clove in each, hold 20 minutes, strain both. Taste 5ml of each and start a timer at the swallow. Record the seconds until you can no longer detect the aroma. Also note which sample smelled stronger in the glass before tasting - it will usually be the water one, which is the point.",
  reflection: "Which sample smelled stronger in the glass, and which one lasted longer in your mouth, and were those the same sample?",
  deepDive: "This dish is being made leaner; tell me which aroma compounds I am likely to lose to the missing fat and what could carry them instead."
},
{
  id: "flavour-detection-thresholds",
  track: "flavour", level: "project",
  title: "Detection thresholds span twelve orders of magnitude, so quantity tells you nothing about contribution",
  source: "Harold McGee, Nose Dive",
  idea: "Some aroma compounds register at parts per trillion and others need parts per hundred, so a trace can dominate a dish while a major constituent contributes nothing.",
  why: "Threshold is set by how tightly a molecule binds its olfactory receptors, and that varies enormously. 2-methoxy-3-isobutylpyrazine, the capsicum and pea note, is detectable in water at single-digit parts per trillion. 2,4,6-trichloroanisole, the cork taint compound, is similar. Ethanol needs roughly parts per hundred. Between those extremes is a range of around a trillion to one.\n\nThis is why aroma chemists rank compounds by odour activity value, which is concentration divided by threshold, rather than by concentration. A compound present at 0.001 per cent with a threshold of 0.00001 per cent matters a hundred times more than one present at 1 per cent with a threshold of 1 per cent. It also means a contaminant you cannot weigh can ruin a dish, and that the compound your gas chromatograph reports as the largest peak may be the one nobody can smell.",
  failureMode: "One tainted dried mushroom or a chopping board that held garlic yesterday flavours an entire pot of delicate stock, and you go looking for the fault in the recipe rather than in a milligram of something.",
  experiment: "Put 1 drop of vanilla extract into 100ml of water and stir. That is roughly step one. Take 10ml of that into 90ml of fresh water for step two, and repeat to step five, which is ten thousand times weaker than step one. Smell each from the weakest upward and write down the first step number at which you detect anything. Do the last two steps twice to check you are not guessing.",
  reflection: "How many dilution steps below the step where you were confident could you still detect something above chance?",
  deepDive: "Something is dominating this dish and I cannot identify it; help me reason from the ingredients to the likely low-threshold compound responsible."
},
{
  id: "flavour-olfactory-adaptation",
  track: "flavour", level: "weeknight",
  title: "You stop smelling your own kitchen within a couple of minutes",
  source: "Harold McGee, Nose Dive",
  idea: "Olfactory receptors adapt fast to a constant stimulus, so the cook is systematically the worst judge of aroma intensity in the room.",
  why: "Adaptation happens at two levels. In the receptor neuron, sustained calcium influx feeds back on the transduction cascade and desensitises it within seconds to tens of seconds. Centrally, the olfactory bulb and cortex suppress a stable, unchanging input in favour of change, because the informative signal in olfaction is almost always a difference. Sensitivity to a compound you have been breathing for ten minutes can fall by well over half.\n\nThe recovery is also fast, which is the useful half. A minute or two out of the room restores most of it. This is why the person who walks in at the end tells you the truth about how the house smells, and why professional tasters sniff in short bursts with breaks rather than inhaling steadily.",
  failureMode: "You stand over a reducing sauce for forty minutes, cannot smell the garlic burning in the corner of the pan, and only find it when someone else arrives and asks what is burning.",
  experiment: "Hold an open jar of ground cumin or a crushed clove of garlic 5cm under your nose and breathe normally. Start a timer. Record the seconds until the smell has clearly halved and the seconds until you can barely detect it. Then leave the room for 90 seconds, come back and smell again, and note how much of it returned.",
  reflection: "How long did full recovery take compared with how long the fade took, and does that change when you would taste a long-cooked dish?",
  deepDive: "Design me a tasting routine for a two-hour braise that works around olfactory adaptation, with specific timings."
},
{
  id: "flavour-salt-suppresses-bitter",
  track: "flavour", level: "weeknight",
  title: "Salt improves food mainly by removing bitterness, not by adding saltiness",
  source: "Paul Breslin and Gary Beauchamp, Salt enhances flavour by suppressing bitterness, Nature 387 (1997)",
  cheat: "Salt is a bitterness eraser first, so it rescues dishes that read bitter; 0.3g in 100ml usually cuts bitter without reading salty.",
  idea: "Sodium suppresses bitter perception more strongly than it enhances anything else, so salting a bitter food works by subtraction.",
  why: "Breslin and Beauchamp showed this cleanly. In a mixture of urea and sucrose, adding sodium raised the perceived sweetness. But the increase came from sodium knocking down the bitterness of the urea, which had been masking the sweet, not from sodium acting on the sweet channel. Remove the bitter component and the sweetness enhancement largely disappears. Other sodium salts behaved the same way regardless of their anion, so the effect follows the sodium ion itself.\n\nThe practical reading is that salt is a bitterness eraser first and a taste in its own right second. That covers most of what salt does for coffee, tonic water, bitter greens, radicchio, grapefruit, dark chocolate and over-extracted stock. It also sets an upper bound: if a dish is not bitter, salt has much less work to do, and adding more of it will just make the dish salty.",
  failureMode: "A stock reduced too far turns harsh and you add salt until it tastes salty and still harsh. The bitterness came from concentrated bitter compounds that a small amount of salt would have masked and a large amount cannot.",
  experiment: "Pour 200ml of tonic water or strong black coffee. Take 100ml as the control. Add 0.3g of salt to the other 100ml, which is about 0.3 per cent, and stir until dissolved. Taste both blind if you can get someone to pour them. Rate bitterness on a 1 to 10 scale for each and write both numbers. Also note whether the salted one tastes salty, because at this dose it usually does not.",
  reflection: "How many points of bitterness did 0.3g remove, and could you detect the salt itself at that dose?",
  deepDive: "This dish reads harsh rather than under-seasoned; help me work out whether the fix is salt for bitterness, fat, acid, or dilution."
},
{
  id: "flavour-capsaicin-trigeminal",
  track: "flavour", level: "weeknight",
  title: "Chilli heat is pain, reported by the same nerve that reports a burn",
  source: "Harold McGee, On Food and Cooking",
  idea: "Capsaicin activates TRPV1, the receptor that also opens above about 43C, so chilli heat is a trigeminal pain signal rather than a taste.",
  why: "TRPV1 is a cation channel on sensory neurons of the trigeminal nerve, which serves the face and mouth. It opens in response to temperatures above roughly 43C, to acidity, and to capsaicin. Capsaicin lowers the channel's thermal activation threshold, so at ordinary mouth temperature the neuron fires as if the tissue were being burned. The brain gets a genuine heat and pain signal from an ingredient at 20C. Nothing has been damaged.\n\nThis is why chilli behaves nothing like a taste. It has no dedicated taste receptor, it does not fit into the sweet and sour and salt balancing exercise, it builds with repeated exposure over minutes rather than reaching an immediate peak, and it is felt on the lips and throat and skin, not just the tongue. Repeated exposure also desensitises the neurons over weeks, which is the whole basis of chilli tolerance.",
  failureMode: "You treat chilli as a seasoning and add it in three rounds while tasting, not realising the signal from round one is still climbing. The dish that was fine at plating is punishing ten minutes later.",
  experiment: "Cut two identical small pieces of fresh chilli. Eat one with your nose firmly pinched and keep it pinched for 30 seconds, writing down the heat level from 1 to 10 and what flavour you can detect. Wait 15 minutes, then eat the other normally and write both numbers again. Heat should be effectively unchanged and flavour should be much richer in the second trial.",
  reflection: "Did pinching your nose change the heat at all, and if you thought it did, was that expectation or sensation?",
  deepDive: "Help me plan the chilli additions for this dish given that heat builds over minutes and I taste it while cooking."
},
{
  id: "flavour-scoville-dilution",
  track: "flavour", level: "project",
  title: "Scoville was a human dilution panel before it was a laboratory number",
  source: "Harold McGee, On Food and Cooking",
  idea: "The original Scoville scale measured the dilution at which trained tasters could no longer detect heat, and modern figures are chemical measurements converted into those units.",
  why: "Wilbur Scoville published the organoleptic test in 1912. An alcohol extract of the chilli was diluted with sweetened water until a panel of five tasters could no longer detect heat, and the dilution factor became the rating. A number of 100,000 meant the extract had to be diluted a hundred thousand-fold before the burn vanished. It was a threshold measurement of human perception, with all the panel variance that implies.\n\nToday capsaicinoids are quantified by high performance liquid chromatography and reported as parts per million, then multiplied by roughly 16 to express them in Scoville heat units so the historical scale still works. That conversion is a convention, not a measurement. It also means the modern number ignores something the panel could not: the different capsaicinoids have different onset speeds and locations of burn, so two chillies with the same rating do not feel the same.",
  failureMode: "You substitute a bird's eye for a habanero on the grounds that the Scoville numbers are similar in order of magnitude, and get a burn in a different place with a different time course, because the capsaicinoid mix is different.",
  experiment: "Blend 5g of one chilli with 100ml of vodka, leave 30 minutes, strain. That is your stock extract. Make five tenfold dilutions in water. Taste a 2ml sip of the weakest first, working up, holding each for 10 seconds, with a minute between. Write down the first dilution at which you can definitely detect heat. Multiply back to get your own rough Scoville figure and compare it with the published range for that chilli.",
  reflection: "How close was your number to the published range, and was the disagreement about your sensitivity or about the chilli itself?",
  deepDive: "I want to substitute one chilli for another in this dish; compare them on capsaicinoid profile and burn character, not just Scoville units."
},
{
  id: "flavour-milk-versus-water",
  track: "flavour", level: "weeknight",
  title: "Milk removes capsaicin where water only moves it around",
  source: "Harold McGee, On Food and Cooking",
  idea: "Capsaicin is lipophilic and binds tightly to tissue, so a fat and casein carrier strips it off while water cannot dissolve enough of it to matter.",
  why: "Capsaicin has a long non-polar tail and is essentially insoluble in water. Once it has partitioned into the lipid membranes around the TRPV1-bearing nerve endings, rinsing with water does almost nothing: there is nowhere for the molecule to go. Worse, water spreads it across a wider area of mucosa.\n\nMilk works on two mechanisms at once. The milk fat provides a lipid phase capsaicin will happily partition into, and casein, an amphiphilic protein, surrounds and carries non-polar molecules the way it does in any emulsion. Full-cream milk therefore beats skim, and both beat water. Alcohol dissolves capsaicin well but at drinking strength there is not enough of it and it irritates the same neurons. Sugar and starch help by a different route, physically coating the tissue.",
  failureMode: "You reach for a glass of water mid-mouthful, it feels briefly better because it is cold and TRPV1 quietens when cooled, then the burn returns worse than before because you have spread the capsaicin over more tissue.",
  experiment: "Use three equal doses of the same chilli sauce, say 0.5g each, on three occasions 20 minutes apart. Trial one: nothing, just wait. Trial two: rinse with 50ml of water. Trial three: rinse with 50ml of full-cream milk. Each time start a timer at the dose and record the seconds until the burn falls to about half. Write down three numbers. Randomise or repeat the order if you can, since expectation is doing real work here.",
  reflection: "Did water beat doing nothing at all, and by how many seconds compared with the milk?",
  deepDive: "Given what I am serving with this hot dish, tell me which accompaniments will actually reduce the burn and which only feel like they do."
},
{
  id: "flavour-cooling-compounds",
  track: "flavour", level: "weeknight",
  title: "Cooling compounds are the mirror image of capsaicin",
  source: "Ole Mouritsen and Klavs Styrbaek, Mouthfeel",
  idea: "Menthol activates TRPM8, the cold receptor, producing a sensation of cold with no change in temperature.",
  why: "TRPM8 sits on the same trigeminal sensory neurons as TRPV1 but opens below roughly 26C. Menthol binds it and shifts its activation threshold upward, so at normal mouth temperature the neuron reports cold. The architecture is exactly the reverse of capsaicin on TRPV1, and the perceptual result is exactly the reverse: a temperature sensation with no thermal cause. Nothing in your mouth has cooled.\n\nInhaling sharply amplifies it for two compounding reasons. The airflow evaporates moisture from the mucosa, which genuinely cools the tissue by a few degrees, and that real cooling lands on receptors already sensitised by menthol, so the two effects stack. Other cooling agents work the same channel: eucalyptol in eucalyptus, camphor, and the synthetic WS-3 and WS-23 used in confectionery when the mint flavour is not wanted.",
  failureMode: "You add mint to a dish for freshness and it fights the temperature you intended, because the cooling is a sensation independent of the flavour and it does not switch off when the mint note fades.",
  experiment: "Hold a mint leaf or a small piece of strong mint confectionery in your mouth for 30 seconds. Note the cooling on a 1 to 10 scale. Then inhale sharply through your mouth and score it again immediately. Write both numbers. Then take a mouthful of water at 40C, which is warm, and note that the cooling sensation survives it.",
  reflection: "How many points did a single sharp inhale add, and did warm water abolish the cooling or leave it running underneath?",
  deepDive: "I want a cooling element in this dish without a mint flavour; suggest ingredients that carry cooling compounds with different aroma profiles."
},
{
  id: "flavour-three-burns",
  track: "flavour", level: "project",
  title: "Chilli, mustard and pepper are three different burns with three different time courses",
  source: "Harold McGee, On Food and Cooking",
  idea: "Capsaicin, allyl isothiocyanate and piperine differ mainly in volatility and binding persistence, which is why wasabi hits the nose and vanishes while chilli sits on the tongue for minutes.",
  why: "Allyl isothiocyanate, from mustard, wasabi and horseradish, is small and volatile. It reaches the nasal cavity through the back of the throat and irritates TRPA1 there, which is why the sensation is felt in the sinuses. Because it is volatile and does not bind tightly, it clears in well under a minute. Capsaicin is non-volatile, oily and binds hard to membranes, so it never reaches the nose and takes many minutes to leave the tongue. Piperine from black pepper is intermediate, less potent than capsaicin by an order of magnitude and shorter-lived.\n\nSichuan pepper is a fourth case entirely. Hydroxy-alpha-sanshool does not produce heat at all but a tingling paraesthesia, by acting on mechanoreceptive fibres, at a beat frequency around 50Hz. Dunlop describes the resulting combination with chilli as ma la, numbing and hot, which is a deliberate pairing of two distinct trigeminal channels rather than two intensities of one.",
  failureMode: "You add wasabi to a dish half an hour before serving and get nothing, because the compound you paid for has volatilised out of the bowl. The same amount stirred in at the table would have been sharp.",
  experiment: "Taste four things separately, 15 minutes apart, in equal small doses: a pinch of fresh chilli, a small dab of fresh wasabi or hot English mustard, 0.2g of freshly cracked black pepper, and a few crushed Sichuan peppercorns. For each, write where you feel it, and time the seconds until it has faded to half. You should see roughly one order of magnitude between the mustard and the chilli.",
  reflection: "Which of the four was felt somewhere other than the tongue, and did any of them still register after five minutes?",
  deepDive: "Help me build a layered heat for this dish using two different trigeminal compounds, and tell me at what point in the cooking each should go in."
},
{
  id: "flavour-season-early-late",
  track: "flavour", level: "weeknight",
  title: "Salt added early and salt added late do different jobs",
  source: "Samin Nosrat, Salt Fat Acid Heat",
  idea: "Salt added during cooking diffuses in and changes the food structurally, while salt added at the end sits on the surface and delivers a sharper hit at lower total dose.",
  why: "Diffusion is slow and one-directional in effect. Salt stirred into a simmering dish equilibrates through the whole volume, so every mouthful is uniformly at, say, 0.8 per cent. On the way it does structural work: it dissolves myofibrillar proteins in meat, draws water out of vegetables by osmosis, and firms pectin in some cases and softens it in others depending on the ion exchange.\n\nSalt scattered on at the end never equilibrates. It hits the tongue as a concentrated pulse before it dilutes into the saliva, so perceived saltiness spikes well above the average concentration. A flaky finishing salt exaggerates this further because the crystal takes longer to dissolve and produces distinct bursts. The two are different tools. Uniform interior seasoning cannot be added at the end, and a bright surface hit cannot be achieved by stirring in more.",
  failureMode: "You salt a stew only at the table and it tastes salty on the first bite and bland underneath, so you add more and end up over the total you would have used had you salted the pot.",
  experiment: "Cook a simple dish, divide into two 200g portions, and give each exactly 1g of salt: one stirred in and left for 10 minutes, one scattered on the surface immediately before eating. Taste both and rate perceived saltiness from 1 to 10. Write both numbers. The surface-salted one usually scores 2 or 3 points higher at identical total salt.",
  reflection: "Which one tasted saltier, which one tasted better, and were those the same portion?",
  deepDive: "For this dish, tell me how to split the total salt between during-cooking and finishing, and what the split does to the eating experience."
},
{
  id: "flavour-acid-contrast",
  track: "flavour", level: "weeknight",
  title: "Acid works by contrast, and perceived sourness tracks titratable acidity rather than pH",
  source: "Samin Nosrat, Salt Fat Acid Heat",
  cheat: "When a rich dish reads heavy, add 5ml of vinegar per 200ml before more salt; the missing element is contrast, not sodium.",
  idea: "Adding acid lifts a dish because contrast sharpens everything around it, and how sour it tastes depends on total acid available, not on the pH reading.",
  why: "Sour is transduced by protons entering the taste cell, largely through the OTOP1 channel. But weak organic acids such as acetic, citric, lactic and malic are mostly undissociated in solution, and the undissociated form crosses the cell membrane and releases its proton inside. That is why acetic acid tastes far more sour than a strong mineral acid at the same pH: pH measures only the free protons in the liquid, while your tongue also gets at the large undissociated reserve. Perceived sourness therefore correlates with titratable acidity, and pH alone will mislead you.\n\nThe culinary effect is contrast rather than sourness for its own sake. A squeeze of lemon into a rich braise does not make it lemony. It introduces a channel that was absent, and against that contrast the fat reads cleaner, the salt reads sharper and the aroma reads brighter. This is the same reason acid rescues a dish that is over-rich, which is a problem no amount of salt fixes.",
  failureMode: "You keep adding salt to a fatty braise that reads heavy and dull, and every addition makes it heavier. Five millilitres of red wine vinegar would have solved it, because the missing element was contrast, not sodium.",
  experiment: "Take 200ml of a finished savoury sauce. Measure the pH with strips or a meter and write it down. Taste it and rate richness and brightness out of 10. Add 5ml of vinegar, stir, measure the pH again and taste again. The pH will usually move a few tenths at most; write down how many points the brightness score moved for that small a pH change.",
  reflection: "How large was the taste change relative to the pH change, and would you have predicted the taste change from the number alone?",
  deepDive: "This dish reads heavy and I have already checked the salt; recommend which acid to use, in what quantity, and at what point to add it."
},
{
  id: "flavour-taste-suppression-pairs",
  track: "flavour", level: "weeknight",
  title: "Tastes suppress each other in predictable pairs, so a balance problem usually has two fixes",
  source: "Ole Mouritsen and Klavs Styrbaek, Umami",
  idea: "Sweetness damps sourness and bitterness, sodium damps bitterness, and umami raises perceived saltiness, so most imbalances can be corrected from either direction.",
  why: "These interactions happen partly in the receptor cells and partly centrally, but the pattern is reliable enough to cook by. Sugar reduces perceived sourness and bitterness. Sodium reduces perceived bitterness strongly and sourness a little. Umami raises perceived saltiness, which means adding a glutamate source lets you cut salt by a meaningful fraction without the dish reading under-seasoned. Acid raises perceived saltiness too. Bitterness and sourness, notably, do not suppress each other much and can compound into something genuinely unpleasant.\n\nThe useful consequence is that a dish which is too sour has two exits: add sweetness to mask it, or add salt and fat to shift the whole balance. They are not equivalent. Sugar hides the acid and leaves the total acid load in place, which will still read on the finish and in the belly. Salt changes the relationship between the components. Which one you want depends on whether the acid is genuinely too high or only unbalanced.",
  failureMode: "A sauce is too sour, you add sugar until it tastes correct, and it comes back as cloying on the finish because you masked the acid rather than reduced it. A dilution or a knob of butter would have moved the actual balance.",
  experiment: "Make 100ml of a deliberately too-sour dressing at one part vinegar to one part oil. Split into two 50ml portions. Add 1g of sugar to one and 0.5g of salt to the other, mix, and taste both against the original. Rate perceived sourness out of 10 for all three and write the numbers. Then decide which one you would actually put on a salad, and note that it is not always the one with the lowest sourness score.",
  reflection: "Which correction lowered the sourness score more, and which one produced a dressing you would eat?",
  deepDive: "Here is what is wrong with the balance of this dish; give me two different corrections from opposite directions and tell me what each one costs."
},
{
  id: "flavour-mouthfeel-channel",
  track: "flavour", level: "project",
  title: "Mouthfeel is a third channel and it changes how strong the other two seem",
  source: "Ole Mouritsen and Klavs Styrbaek, Mouthfeel",
  idea: "Viscosity, astringency, temperature and particle size are reported by touch and trigeminal nerves, and they alter perceived taste intensity without changing a single molecule of the recipe.",
  why: "Taste requires the molecule to reach a receptor. In a thickened liquid, diffusion to the tongue surface and mixing with saliva both slow down, so the concentration at the receptor over the time the food is in the mouth is lower even though the concentration in the bowl is identical. Above roughly 0.5 per cent added hydrocolloid the effect becomes obvious, and studies of thickened liquids routinely find perceived saltiness and sweetness dropping by tens of per cent at unchanged composition. Aroma release into the headspace falls for the same reason.\n\nAstringency is different again and not a taste at all. Tannins and polyphenols bind and precipitate salivary proline-rich proteins, so the lubricating layer between tongue and palate collapses and you feel friction. That is a tactile report, which is why it builds over successive sips of red wine or strong tea rather than adapting away.",
  failureMode: "You thicken a gravy with cornflour at the end and it goes bland, so you salt it. Next time you make it thinner and it is now over-salted, because the seasoning was calibrated against the viscosity, not against the food.",
  experiment: "Make 200ml of broth and season it once, uniformly. Split into two 100ml portions. Thicken one with 0.5g of cornflour slurry and the other with 2g, cooking both out equally so the starch is fully gelatinised, and bring both back to the same temperature. Rate saltiness out of 10 for each. Write both numbers. Then add salt to the thick one in 0.1g steps until they match and record the grams it took.",
  reflection: "How many grams of extra salt did the thicker version need to taste equal, and would you have guessed that number in advance?",
  deepDive: "I am thickening this dish; tell me how to adjust seasoning for the change in viscosity and at which point in the process to taste."
},
{
  id: "flavour-aroma-families",
  track: "flavour", level: "project",
  title: "Aroma compounds fall into chemical families and the family tells you which process made it",
  source: "Harold McGee, Nose Dive",
  idea: "Pyrazines read roasted, thiols sulfurous, terpenes fresh and resinous, esters fruity and lactones creamy, so identifying the family tells you what happened in the pan.",
  why: "McGee organises smells by molecular family rather than by source, and once you have the map it runs backwards into cooking. Pyrazines are nitrogen heterocycles formed in the late stages of the Maillard reaction, so a roasted note means browning happened, and no amount of stewing will produce one. Sulfur compounds, thiols and disulfides and thiophenes, come from cysteine and methionine and from the alliums, and they are potent at parts per trillion and heat-labile. Terpenes are plant secondary metabolites made in oil glands, so they are present before you cook and are lost to volatilisation once you do.\n\nEsters come from an acid and an alcohol combining, which is why they dominate ripe fruit and fermented products but never appear from dry heat alone. Lactones are cyclic esters and read as coconut, peach and dairy. The practical payoff is diagnostic: a smell tells you which chemistry has and has not run, so if there are no pyrazines you did not brown, and if the terpenes are gone you added the herbs too early.",
  failureMode: "You add fresh thyme at the start of a two-hour braise, and by service the terpenes have boiled off and left behind only the heavier, more bitter fraction. The dish smells woody rather than herbal and nobody can name why.",
  experiment: "Line up four things and smell each for two seconds with a gap between: ground coffee, a freshly cut brown onion, crushed rosemary, and a ripe banana. Write the chemical family next to each: pyrazine, thiol, terpene, ester. Then name the process that made it: roasting, enzymatic breakdown on cutting, plant oil gland, ripening. Getting four out of four is the test.",
  reflection: "Which of the four could you have produced in your own kitchen tonight, and which one requires a process you cannot run on a stove?",
  deepDive: "Describe the aroma of a dish I am working on and tell me which chemical families are present, which are missing, and what process would supply the missing ones."
}
);
