/* Track: Acid, salt and fermentation. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "acid-salt-diffusion-rate",
  track: "acid", level: "weeknight",
  title: "Salt diffuses roughly a centimetre a day into muscle",
  source: "Harold McGee, On Food and Cooking",
  cheat: "Time a dry brine from thickness, not weight: salt moves about a centimetre a day, so a 6cm shoulder needs three days a face.",
  idea: "Curing time is set by the thickness of the piece, not by its weight.",
  why: "Two different transport processes run at once and they run at wildly different speeds. Osmosis pulls water out of the cells almost immediately, because the concentration gradient across the cell membrane is steep and the distance is microns. Diffusion carries sodium and chloride ions inward through a crowded protein gel, and that is slow: at fridge temperature the seasoned front advances on the order of a centimetre per day.\n\nSo the useful number is the distance from the surface to the centre, halved if you are salting both sides. A 2cm pork chop is seasoned through in about a day. A 6cm pork shoulder needs three days from each face, and no amount of extra salt speeds it up - more salt steepens the gradient a little but does not change the order of magnitude. Weight tells you how much salt to use. Thickness tells you how long to wait.",
  failureMode: "You dry-brine a 5cm pork loin for two hours because a recipe said two hours, and you get a salty crust over bland interior. The salt is all sitting in the outer 2mm, which is also why it tastes harsher than the same total amount evenly distributed would.",
  experiment: "Salt a 4cm block of pork on all faces at 1 percent of its weight, uncovered in the fridge. After 24 hours cut it in half and taste inward from the cut face in 5mm steps. Write down the depth in millimetres where it stops tasting seasoned.",
  reflection: "How far did the front actually travel in 24 hours, and how does that compare with the thickness of the cuts you normally season an hour before cooking?",
  deepDive: "Given the cuts I cook most often, help me work out a dry-brining schedule from their thickness rather than from recipe timings."
},
{
  id: "acid-salt-protein-structure",
  track: "acid", level: "project",
  title: "Salt concentration changes protein structure, not just flavour",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Below about 2 percent salt swells muscle protein and holds water in, and above about 5 percent it strips water out.",
  why: "Chloride ions bind to the myofibrillar proteins, mainly myosin, and give them a net negative charge. Like charges repel, the filament lattice pushes apart, and water moves into the widened spaces. That is salting-in, and it peaks somewhere around 1 to 2 percent salt in the meat. The proteins are also partly solubilised, which is why salted mince becomes tacky and binds into a sausage while unsalted mince crumbles.\n\nPush the concentration higher and the ions start competing with the proteins for water molecules. The proteins salt out: they aggregate, the lattice contracts, and water leaves. Above roughly 5 percent you are dehydrating and firming the tissue. That single continuum is the whole difference between a brine and a cure. Same ion, opposite outcome, and the boundary is a concentration you can weigh.",
  failureMode: "You brine chicken breast in a 10 percent solution because it will only be in there an hour, and it comes out both salty and dry. The high concentration expelled water instead of holding it, and the fibres tightened while they were at it.",
  experiment: "Take three 100g pieces of chicken thigh, weigh each to the gram, and hold them for four hours in solutions of 1, 3 and 8 percent salt by weight of water. Pat dry, reweigh, then cook all three the same way and weigh again. Record six numbers.",
  reflection: "Which concentration gained weight in the soak, and which one lost the least during cooking? Were they the same one?",
  deepDive: "Help me pick a brine concentration and time for a specific cut, working from whether I want water held in or water driven out."
},
{
  id: "acid-nitrite-cure",
  track: "acid", level: "project",
  title: "Nitrite fixes colour and blocks botulism",
  source: "Harold McGee, On Food and Cooking",
  idea: "Curing salt is doing microbiology, and the pink colour is only the visible side effect.",
  why: "Sodium nitrite is reduced to nitric oxide, which binds the iron at the centre of myoglobin to form nitrosylmyoglobin. That complex survives cooking as a stable pink pigment, which is why ham stays pink at a temperature that turns roast pork grey. More importantly, nitrite inhibits the germination and outgrowth of Clostridium botulinum spores, which is what makes a low-acid, low-oxygen, ambient-temperature meat product survivable at all.\n\nCelery powder cures are the same chemistry wearing a different label. Celery is high in nitrate, a culture reduces the nitrate to nitrite, and the meat then sees exactly the nitrosylmyoglobin route. The one real difference is dose control: a curing salt is 6.25 percent nitrite in a carrier, used at 0.25 percent of meat weight to land near 150 parts per million, while a vegetable powder cure is far harder to hit a target with.",
  failureMode: "You make a confit or a sous vide terrine, hold it low and slow in a sealed bag with no nitrite and no acid, and then keep it in the fridge for a fortnight. Nothing about the process addresses spores, and the anaerobic bag is the condition they want.",
  experiment: "Cure two 100g pork pieces for 48 hours in the fridge, one with 2 percent plain salt and one with 2 percent salt plus 0.25 percent curing salt. Cook both to the same internal temperature, cut them, and photograph the two cut faces side by side.",
  reflection: "How different is the colour, and does the cured piece read as cooked at a temperature where the plain one still looks raw?",
  deepDive: "Walk me through whether a specific thing I want to make needs nitrite, or whether refrigeration and a short shelf life already cover it."
},
{
  id: "acid-ceviche-denaturation",
  track: "acid", level: "weeknight",
  title: "Acid denatures protein but it does not cook",
  source: "Harold McGee, On Food and Cooking",
  idea: "Ceviche looks cooked because acid unfolds protein, which is not the same as heating it.",
  why: "Dropping the pH towards 3 protonates the acidic side chains on the protein, the internal charge balance that held the fold together breaks, and the chain unravels and tangles with its neighbours. The result is opaque, firm and white, exactly the visual signature of heat coagulation. Same endpoint, different route.\n\nEverything heat does that acid does not still has not happened. Parasites are not killed - Anisakis larvae survive citrus marinades comfortably, which is why ceviche uses fish you would eat raw. Collagen is not converted to gelatin, because that needs sustained heat above about 60C. And the process is diffusion-limited from the surface inward at millimetres per hour, so a thick cube is raw in the middle no matter how long it sits, while the outer layer keeps firming until it goes chalky.",
  failureMode: "You marinate diced snapper for two hours thinking longer means more cooked. The outside has gone dry and cotton-textured because the proteins kept aggregating and squeezing out water, and the centre is still raw. Fifteen to twenty minutes on 1cm dice is usually the whole job.",
  experiment: "Cut 50g of sashimi-grade fish into a slab and cover it in lime juice. Every 10 minutes for an hour, slice off a piece, and measure with a ruler how deep the opaque zone has reached. Plot depth against time.",
  reflection: "Is the front moving at a constant rate, or slowing as it goes deeper? What does that tell you about picking a dice size?",
  deepDive: "Help me choose a dice size and marinating time for a specific fish so the acid reaches the centre exactly as the surface finishes."
},
{
  id: "acid-isoelectric-point",
  track: "acid", level: "project",
  title: "Meat holds least water near pH 5.2",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Muscle protein sits close to its isoelectric point, so moving pH in either direction makes meat juicier.",
  why: "At the isoelectric point the positive and negative charges on the protein cancel out. With no net charge there is nothing pushing the filaments apart, the lattice packs to its tightest spacing, and the water that was held in those gaps gets expressed. For myofibrillar protein that point is around pH 5.0 to 5.4, and post-rigor meat lands right there at about 5.5. Meat is naturally sitting near its own worst case for water retention.\n\nMove away in either direction and you restore net charge, the lattice opens, and water-holding capacity climbs. Bicarb pushes upward and is why velveted Cantonese chicken stays plump. A marinade with vinegar or yoghurt pushes downward and does the same thing from the other side. Both work, and both stop working when you overshoot: too far up gives a soapy, slippery texture, too far down starts denaturing the surface into ceviche.",
  failureMode: "You add bicarb to mince by eye, and the burger comes out springy and faintly metallic with an ammoniacal edge. About 0.3 to 0.5 percent of meat weight is the useful band, and past 1 percent the texture goes rubbery and the flavour turns.",
  experiment: "Soak three 100g pieces of chicken breast for 20 minutes: one in 200ml water, one in water plus 5ml white vinegar, one in water plus 2g bicarb. Weigh each before cooking and after cooking to the same internal temperature. Record the cooking loss as a percentage.",
  reflection: "Which of the three lost the least weight, and could you taste the pH shift as well as feel it?",
  deepDive: "Help me work out whether a specific dish wants a pH shift up or down, and what dose gets me there without a texture penalty."
},
{
  id: "acid-ph-4-6-safety-line",
  track: "acid", level: "project",
  title: "pH 4.6 is the safety line",
  source: "Harold McGee, On Food and Cooking; FSANZ Food Standards Code",
  cheat: "Botulinum cannot grow below pH 4.6, so treat 4.6 as the cliff edge and 4.2 as where you stand; garlic in oil goes in the fridge, briefly.",
  idea: "Clostridium botulinum cannot grow below pH 4.6, which is the whole basis of shelf-stable acid preserving.",
  why: "Botulinum spores survive boiling. What stops them producing toxin is an environment they cannot grow in, and acidity is the cheapest one available at home. Below pH 4.6 growth stops, which is why jams, most pickles, chutneys and tomato products with added acid are safe on a shelf, and why low-acid vegetables in oil or water are not, no matter how clean the jar looked.\n\nTwo things make the number harder than it sounds. First, it is the pH of the equilibrated food, not the brine - a cucumber packed in pH 3 vinegar can hold a near-neutral interior for days while the acid diffuses in. Second, home practice targets 4.2 or lower rather than 4.6, because your measurement has error, your ingredient acidity varies and buffering by proteins and starch shifts the endpoint. Treat 4.6 as the cliff edge and 4.2 as where you stand.",
  failureMode: "Garlic or chilli in oil at room temperature. Both are low-acid, the oil is anaerobic, and there is no hurdle in the jar at all. This is a recurring source of real botulism cases, and the fix is either refrigeration with a short life or acidification first.",
  experiment: "Make a jar of pickles. Measure the pH of the brine with strips or a meter at the moment you seal it, then after a week blend a spoonful of the solid with a little of its own brine and measure that. Write down both numbers.",
  reflection: "How far apart were the brine and the solid, and how long would it actually take your jar to equilibrate below 4.2?",
  deepDive: "Help me check whether a preserve I want to make actually gets below pH 4.2 throughout, or whether it belongs in the fridge."
},
{
  id: "acid-ferment-succession",
  track: "acid", level: "project",
  title: "Lacto-fermentation runs as a succession of organisms",
  source: "Sandor Katz, The Art of Fermentation",
  idea: "A vegetable ferment is a relay, and the flavour changes because the population changes.",
  why: "The jar starts near neutral with a mixed population off the vegetable surface. Leuconostoc mesenteroides goes first: it is heterofermentative, so it produces lactic acid plus acetic acid, ethanol and carbon dioxide. That is the fizzing in week one, and the CO2 also displaces oxygen and helps make the jar anaerobic for what follows.\n\nLeuconostoc is not very acid-tolerant and inhibits itself out of the job somewhere around pH 4.0. Lactobacillus plantarum and its relatives take over, they are homofermentative, and they drive the pH down towards 3.4 producing almost purely lactic acid. So a young ferment tastes complex, gassy and mixed while a mature one tastes cleanly sour. If you want the interesting aromatics you stop early and refrigerate. If you want the keeping quality you let the second phase finish.",
  failureMode: "You taste at day three, decide it tastes right, and leave it on the bench anyway. Two weeks later it is flatly sour and the aromatic top notes are gone, because the organism making them was outcompeted by the one that only makes lactic acid.",
  experiment: "Shred 500g of cabbage with 10g of salt, pack it under its own brine, and record pH and one line of tasting notes every day for two weeks. Plot pH against day.",
  reflection: "Where does the curve bend, and does the day it bends line up with the day the taste stopped being interesting?",
  deepDive: "Help me read a pH curve from a ferment I am running and decide which day to refrigerate it on."
},
{
  id: "acid-salt-selects-organisms",
  track: "acid", level: "weeknight",
  title: "Salt concentration selects which organisms survive",
  source: "Sandor Katz, The Art of Fermentation",
  idea: "The 2 percent in a ferment is a selection pressure, not a seasoning decision.",
  why: "Lactic acid bacteria are unusually salt-tolerant, comfortably working at 2 to 3 percent and surviving well above that. Most of the organisms that would otherwise win the jar - the pseudomonads, the enterobacteria, many moulds and wild yeasts - are not. Setting the salt at 2 percent handicaps everything except the organism you want, and then that organism produces the acid that finishes off the rest.\n\nSalt also draws water and sugars out of the plant cells by osmosis, which is what creates the brine in a dry-salted kraut and what makes the sugars available to the bacteria. Go too low and you get soft, slimy, off-smelling ferments because spoilage organisms got a head start. Go too high, past about 5 percent, and you slow the lactic bacteria enough that the ferment stalls half-acidified, which is its own risk.",
  failureMode: "You salt a kimchi to taste rather than to weight, land near 1 percent, and get a jar that smells of solvent and turns slimy at the surface. The dextran slime is typically Leuconostoc under stress or a competing organism that the salt should have suppressed.",
  experiment: "Fill three jars with the same shredded vegetable at 1, 2 and 4 percent salt by total weight. At day five, record the pH of each and one word for the smell. Keep them all at the same temperature.",
  reflection: "Did the low-salt jar acidify fastest, and did fastest also mean best? What did the 4 percent jar cost you in time?",
  deepDive: "Help me set a salt percentage for a specific ferment based on how fast I want it and how long I want it to keep."
},
{
  id: "acid-sourdough-consortium",
  track: "acid", level: "project",
  title: "Sourdough is a bacteria and yeast consortium at about 100 to 1",
  source: "Nathan Myhrvold, Modernist Bread",
  idea: "A mature starter holds roughly a hundred lactic acid bacteria for every wild yeast cell.",
  why: "The two populations do different jobs. The yeasts, typically Kazachstania humilis and relatives rather than commercial Saccharomyces, ferment sugars to CO2 and give you the rise. The lactic acid bacteria, dominated by Fructilactobacillus sanfranciscensis in a classic starter, produce the acid and most of the flavour. They coexist because they eat different things: the bacteria take maltose and leave glucose, the yeasts take glucose and are indifferent to maltose.\n\nThat ratio matters practically because rise and sourness are driven by different populations with different doubling times and different temperature optima. The bacteria are faster and prefer it warmer. So a warm, long, infrequently fed starter drifts acidic without gaining leavening power, and a cool, frequently fed one stays mild and lively. You are not adjusting one dial, you are adjusting the balance between two organisms.",
  failureMode: "Your starter smells sharply of acetone and vinegar and your loaf still will not rise. The bacteria are thriving and the yeast has been starved and acid-stressed. More feeds at a higher ratio, not a longer wait, is the fix.",
  experiment: "Feed a starter 1:5:5 by weight, mark the jar level, and record the time in minutes to double and the pH at peak. Repeat the next day at 1:1:1 and record the same two numbers.",
  reflection: "Which feeding ratio gave the faster rise, and which gave the lower pH? Did they move together or in opposite directions?",
  deepDive: "Help me design a feeding schedule that gets me a specific level of sourness and a specific rise time in my kitchen temperature."
},
{
  id: "acid-hydration-lactic-acetic",
  track: "acid", level: "project",
  title: "Hydration decides whether sourdough is lactic or acetic",
  source: "Nathan Myhrvold, Modernist Bread",
  idea: "The kind of sourness you get is a process variable you set, not a property of your starter.",
  why: "Lactic acid is mild, yoghurt-like and rounded. Acetic acid is sharp and volatile and reads as vinegar. Both come from heterofermentative lactic acid bacteria, but the split between them depends on conditions. A stiff starter around 50 to 60 percent hydration, kept cool, shifts the metabolic route towards acetic acid, partly because the reduced water activity and the availability of alternative electron acceptors like fructose favour the acetate branch.\n\nA slack starter at 100 percent hydration kept warm, around 28 to 30C, does the opposite and pushes towards lactic. So the two levers that actually control your bread's flavour are water and temperature in the starter, not the flour or the age of the culture. This is also why the same starter behaves differently in a Sydney summer and a Sydney winter unless you change the hydration to compensate.",
  failureMode: "You chase a sharper loaf by simply retarding it longer in the fridge, and get a duller one. Cold slows everything including the bacteria, and if the starter is slack the extra time mostly adds lactic acid and protease activity, which softens the crumb without adding the sharpness you wanted.",
  experiment: "Split a starter and maintain one half at 60 percent hydration and one at 100 percent for a week, same flour, same feed schedule, same bench. At the end, measure the pH of both and taste each on a spoon. Write down both pH readings and which one is sharper.",
  reflection: "Did the pH numbers actually differ much, and if they were close, was the difference in sharpness still obvious? What does that say about pH as a proxy for perceived sourness?",
  deepDive: "Help me adjust my starter hydration and temperature to move my bread towards sharp or towards mild."
},
{
  id: "acid-vinegar-aerobic",
  track: "acid", level: "weeknight",
  title: "Vinegar is a second, aerobic fermentation",
  source: "Harold McGee, On Food and Cooking",
  idea: "Acetobacter needs oxygen to turn ethanol into acetic acid, which is why vinegar is made open and wine is made sealed.",
  why: "Yeast fermentation is anaerobic: sugar to ethanol and CO2, no oxygen required, and you seal the vessel to keep oxygen out. Acetic fermentation is the opposite reaction and needs the oxygen. Acetobacter oxidises ethanol first to acetaldehyde and then to acetic acid, consuming O2 at both steps, and it will only do it at the interface with air.\n\nThat is why the traditional vinegar vessel is wide and shallow with a cloth over the top, and why the mother forms as a cellulose raft floating at the surface where the oxygen is. It is also why an unfinished bottle of wine goes to vinegar in the fridge over weeks: you have just built a small, badly designed vinegar generator. Surface area, not volume, sets the rate.",
  failureMode: "You try to make vinegar in a narrow bottle with the lid on and get nothing but oxidised, sherry-like wine. No air interface, no acetic acid. Sulfited wine or anything above about 12 percent alcohol also stalls, because the Acetobacter cannot cope.",
  experiment: "Pour 100ml of a low-sulfite red into a wide bowl, cover with a cloth, leave it at about 25C for two weeks, and pour the same wine into a sealed bottle as a control. Measure pH on both at day 0 and day 14.",
  reflection: "How far did the open one drop, and did the sealed control move at all? Was the smell change bigger than the pH change?",
  deepDive: "Help me set up a small vinegar ferment from something I already have, and tell me what pH would mean it worked."
},
{
  id: "acid-vinegar-strength",
  track: "acid", level: "weeknight",
  title: "Vinegar strength is 4 to 6 percent acetic acid",
  source: "Harold McGee, On Food and Cooking",
  idea: "Every vinegar is a labelled acid dose, and swapping one for another changes the acid load by up to half.",
  why: "Vinegar acidity is regulated and printed on the bottle, usually as percent acetic acid or degrees. Australian white vinegar is commonly 4 percent, cider vinegar around 5, many imported wine vinegars 6, and rice vinegar often 4 or lower. Between the weakest and the strongest that is a 50 percent difference in the amount of acid you are adding, before you have thought about flavour at all.\n\nThat matters twice. In a dressing it changes the perceived sharpness and how much oil it takes to balance. In a pickle it changes whether you get below pH 4.2, which is a safety property, not a preference. If you substitute a 4 percent rice vinegar into a recipe written for 6 percent wine vinegar, you have quietly cut the acid by a third and you should compensate by weight, not by eye.",
  failureMode: "You use a mild rice vinegar in a quick pickle recipe developed for white vinegar and then keep the jar on the bench. It tastes fine and it is sitting well above pH 4.6.",
  experiment: "Line up three vinegars from your cupboard and write down the labelled acidity of each. Pick the strongest as the reference, then calculate by weight how much of each of the others you would need to deliver the same acid, and make one dressing with the adjusted amount.",
  reflection: "How big was the spread between your three bottles, and did the by-weight adjusted dressing actually taste as sharp as the reference?",
  deepDive: "Help me convert a recipe written for one vinegar strength to the bottle I actually have, by weight."
},
{
  id: "acid-alcoholic-fermentation",
  track: "acid", level: "project",
  title: "Alcoholic fermentation is sugar to ethanol plus CO2",
  source: "Harold McGee, On Food and Cooking",
  idea: "Each gram of sugar becomes about half a gram of ethanol and half a gram of carbon dioxide, so the gas you lose tells you the alcohol you made.",
  why: "The stoichiometry is fixed: 180g of glucose gives 92g of ethanol and 88g of CO2, so 51 percent and 49 percent by weight. The CO2 leaves the vessel. That means a fermenting jar on a scale is an alcohol meter - every gram of weight lost is roughly a gram of ethanol gained, which is the same measurement a brewer makes indirectly with a hydrometer.\n\nTemperature does not change that ratio but it changes everything else. Warm ferments, above about 25C, run fast and produce more higher alcohols and more fusel character, which reads as rough and solventy. Cool ferments, 15 to 18C for a wine yeast, run slowly and retain more of the light fruity esters like isoamyl acetate. Same sugar, same alcohol, different aroma profile, and the variable you control is the temperature of the room.",
  failureMode: "You ferment a cider on a warm Sydney bench at 28C, it finishes in four days and tastes hot and nail-polish sharp. The yeast was stressed, and the ester and fusel profile it produced under that stress is not something you can remove later.",
  experiment: "Weigh a 500ml jar of unpasteurised apple juice with an airlock, pitch yeast, and reweigh at the same time each day for a week. Record the cumulative grams lost, then double it to estimate the sugar consumed.",
  reflection: "How many grams of CO2 came off in total, and does the alcohol that implies match the sugar listed on the juice label?",
  deepDive: "Help me estimate the alcohol in a small ferment from its weight loss, and sanity check it against the starting sugar."
},
{
  id: "acid-ferment-family",
  track: "acid", level: "project",
  title: "Kimchi, sauerkraut, miso and soy are one family",
  source: "Sandor Katz, The Art of Fermentation",
  idea: "All four use salt to select the microbes and time to break down substrate, and they differ mainly in whether the work is acidification or proteolysis.",
  why: "The shared template is simple. Salt at a concentration that only the organisms you want can tolerate, exclude oxygen or don't depending on which organism you want, and then wait while enzymes and microbes take large molecules apart into small ones. What varies is the substrate and which reaction dominates.\n\nSauerkraut and kimchi are carbohydrate substrates and bacterial acidification: lactic acid bacteria eating plant sugars over days to weeks, and the product is defined by its pH. Miso and soy sauce are protein substrates and enzymatic proteolysis: Aspergillus oryzae growing on grain first to make koji, then its proteases and amylases working in a high-salt mash for months while salt-tolerant bacteria and yeasts add acid and aroma slowly around the edges. Sourness versus savouriness is not a flavour preference, it is which macromolecule was on the menu.",
  failureMode: "You treat miso like a pickle and expect it in a fortnight. Proteolysis on that scale takes months, and the high salt that makes the long timescale safe also makes it slow. Rushing it gives you salty bean paste with no glutamate.",
  experiment: "Put small amounts of sauerkraut, kimchi, miso and soy sauce on one plate. Taste each and score it out of five for sourness, then go around again and score each out of five for savouriness. Write down eight numbers.",
  reflection: "Did the two rankings come out roughly inverted? Which one scored high on both, and what does that say about how long it was fermented?",
  deepDive: "Help me map a ferment I want to try onto this family, and tell me whether I am buying acid or amino acids."
},
{
  id: "acid-miso-proteolysis",
  track: "acid", level: "project",
  title: "Miso and soy build glutamate by enzyme, not by acid",
  source: "Ole Mouritsen and Klavs Styrbaek, Umami",
  idea: "The umami in miso and soy sauce is free amino acids cut out of soy protein by fungal proteases over months.",
  why: "Aspergillus oryzae is grown on rice or barley to make koji, and what you are actually farming is its enzyme kit. The proteases hydrolyse soy protein into peptides and then into free amino acids, and the one that matters for taste is free glutamate, which binds the umami receptor while bound glutamate inside an intact protein does not. Amylases do the same job on starch, releasing glucose, which is why aged miso tastes sweet as well as savoury.\n\nSalt in the mash, typically 5 to 13 percent depending on the style, does none of that work. It is there to keep everything except the salt-tolerant organisms out for the year or more the enzymes need. So the two variables are time, which sets how much protein has been cut up, and salt, which sets how slowly and how safely. Sweet white shiro miso is low salt and a few weeks. Dark hatcho is high salt and a couple of years.",
  failureMode: "You substitute a young white miso for a dark aged one in a braise and the dish tastes thin and just salty. You matched the volume, not the free glutamate, and the aged one had several times more of it.",
  experiment: "Buy a young miso and an aged one, taste each on its own on the tip of a spoon, and rank them for savoury intensity. Then read the salt percentage off both labels and write the two numbers next to your ranking.",
  reflection: "Did the more savoury one also have more salt, or less? If more, how much of what you tasted was actually glutamate rather than sodium?",
  deepDive: "Help me pick a miso for a specific dish based on age and salt rather than on colour."
},
{
  id: "acid-enzymatic-browning",
  track: "acid", level: "weeknight",
  title: "Enzymatic browning is polyphenol oxidase plus oxygen",
  source: "Harold McGee, On Food and Cooking",
  idea: "Cut fruit browns because a damaged cell releases an enzyme onto phenolics in the presence of air, and acid slows the enzyme down.",
  why: "In an intact cell the polyphenol oxidase and the phenolic compounds are in different compartments. Cutting breaks the barrier, they meet, and with atmospheric oxygen the enzyme oxidises phenolics to quinones. The quinones then polymerise on their own into brown melanins, no enzyme required for that second step. This has nothing to do with the Maillard reaction and needs no heat at all.\n\nPPO has a pH optimum near 6 to 7 and its activity falls off steeply below about pH 4. Lemon juice at pH 2.3 pushes the cut surface well under that, which is why it works, and the ascorbic acid in it does a second job by reducing quinones back to phenols before they can polymerise. Salt water inhibits the enzyme too, via chloride binding at the copper active site, and water alone works only by limiting oxygen contact.",
  failureMode: "You hold cut apple in plain water for an hour and it browns anyway, just more slowly and unevenly at the waterline. Water restricts oxygen but does not touch the enzyme, and dissolved oxygen is enough to keep it going.",
  experiment: "Cut an apple into four wedges. Leave one dry, submerge one in water, one in lemon juice and one in 2 percent salt water. Photograph all four together at 0 and 30 minutes and rank them by how brown they are.",
  reflection: "Did the ranking match what you predicted, and how big was the gap between plain water and lemon juice?",
  deepDive: "Help me choose an anti-browning treatment for a specific fruit or vegetable where I cannot afford the flavour of lemon juice."
},
{
  id: "acid-blanching-vs-acid",
  track: "acid", level: "weeknight",
  title: "Blanching stops browning permanently where acid only slows it",
  source: "Harold McGee, On Food and Cooking",
  idea: "Heat destroys polyphenol oxidase for good, and acid only suppresses it while the pH stays low.",
  why: "Acid inhibition is reversible. The enzyme is still there, still folded, still functional, and it is simply operating far from its pH optimum. Dilute the acid, rinse it, or let it diffuse away into the flesh, and browning resumes. That is why lemon-treated apple that gets rinsed browns within the hour.\n\nHeat is irreversible. PPO denatures at around 70 to 80C and a couple of minutes at that temperature destroys the tertiary structure permanently, which is the whole reason commercial frozen vegetables are blanched before freezing. The cost is that the same heat gelatinises surface starch, softens pectin and starts cooking the thing you wanted raw. So it is a genuine trade: a temporary fix with no texture cost, or a permanent one that changes the food.",
  failureMode: "You prep potatoes for a dinner party, hold them raw in water for three hours, and they go grey anyway. Cut potato browns both enzymatically and through iron-phenolic complexes, and cold water does not stop either. A 60 second blanch would have.",
  experiment: "Cut a potato into matchsticks, blanch half for 60 seconds in boiling water then cool, and hold both halves in plain cold water. Photograph both at two hours and note which one has discoloured.",
  reflection: "Did the blanched half stay pale, and did it cost you anything in bite when you cooked it?",
  deepDive: "Help me decide between blanching and acid for something I want to prep hours ahead, given how much texture change I can tolerate."
},
{
  id: "acid-gravlax-weight-loss",
  track: "acid", level: "weeknight",
  title: "Gravlax is a cure you can weigh",
  source: "Harold McGee, On Food and Cooking",
  idea: "Salt and sugar firm a salmon fillet with no heat at all, and the water they pull out is directly measurable on a kitchen scale.",
  why: "The cure mix sets up a steep osmotic gradient at the surface. Water leaves the muscle cells, dissolving the salt and sugar into a brine that then carries ions back inward by diffusion. Over 24 to 48 hours a 300g fillet typically sheds 10 to 15 percent of its weight as liquid. The protein left behind is partly denatured by the salt, which is what turns the flesh from translucent and soft to firm, dense and sliceable.\n\nSugar is not just for flavour. It moderates the harshness of the salt and, because it is a larger molecule, it penetrates more slowly and moderates the rate of dehydration, which is why a straight salt cure at the same weight gives a drier, harder edge. The whole thing is protein chemistry that you can track with nothing but a scale and a clock.",
  failureMode: "You cure a thin tail piece for the same 48 hours as a thick centre cut, and the tail comes out hard and oversalted. Cure time scales with thickness, exactly like brining, and a 1.5cm tail is finished in well under a day.",
  experiment: "Weigh a 300g salmon fillet, bury it in 50g salt and 50g sugar on a rack over a tray, and reweigh the drained fillet at 12, 24 and 48 hours. Record three weights and convert each to percentage loss.",
  reflection: "Is the rate of water loss constant or slowing, and at what percentage loss did the texture become what you wanted?",
  deepDive: "Help me scale a gravlax cure to the thickness of the fillet I have and pick a target weight loss."
},
{
  id: "acid-hurdle-technology",
  track: "acid", level: "project",
  title: "Preserving is three hurdles, not one",
  source: "Lothar Leistner, Food preservation by hurdle technology; Harold McGee, On Food and Cooking",
  idea: "Acidity, water activity and temperature combine multiplicatively, so a preserve can be safe on three moderate barriers that none of them would provide alone.",
  why: "Leistner's framing is that microbes must clear every barrier in the food to grow, not just one. Low pH, low water activity, low temperature, competing organisms, preservatives and packaging each cut the population that can survive. Stack several moderate ones and you get the same effect as one extreme one, without the food becoming inedible.\n\nThis is why a salami works. It is not acidic enough to be a pickle, not dry enough to be a biscuit and not refrigerated, but it is somewhat acidic from its ferment, somewhat dry at a water activity below about 0.90, nitrite-cured and colonised by a mould that occupies the surface. Four moderate hurdles. Understanding your preserve as a stack rather than a single trick is also how you find the gap: if you soften one hurdle, you have to harden another.",
  failureMode: "You lower the salt in a preserve because it tastes salty, and change nothing else. Water activity rises, one hurdle is gone, and the acid and temperature that were adequate as part of a stack are now carrying the whole load on their own.",
  experiment: "List everything you currently have preserved in the fridge and the pantry. For each one write which hurdles it actually uses: pH, water activity, temperature, nitrite, alcohol, competing culture. Count how many have only one.",
  reflection: "Which item on your list has the fewest hurdles, and is it in the fridge or on the shelf?",
  deepDive: "Help me audit the hurdles in a preserve I make regularly and find the one that is doing all the work."
},
{
  id: "acid-fermented-vs-vinegar-pickle",
  track: "acid", level: "weeknight",
  title: "Fermented pickles make their own acid and vinegar pickles do not",
  source: "Sandor Katz, The Art of Fermentation",
  idea: "A vinegar pickle is an acidification with a fixed endpoint and a fermented pickle is a biological process that keeps moving.",
  why: "A quick pickle starts at its final pH. You add a known concentration of acetic acid, it diffuses into the vegetable over hours to days, and the equilibrium pH is arithmetic you could have done in advance. Nothing is growing, nothing is producing anything, and the flavour on day 30 is close to the flavour on day 3.\n\nA fermented pickle starts near neutral and gets to safety on its own, by growing the organisms that produce lactic acid. That means it passes through a window where it is not yet acidic and is relying on salt alone, and it means the endpoint is a moving target that depends on temperature, sugar in the vegetable and how long you leave it. It also means it contains live organisms and gas and will keep changing in the fridge. Different process, different flavour, and different safety logic: one you can calculate, one you have to measure.",
  failureMode: "You treat a fermented pickle like a shelf-stable vinegar one and seal it hard in a full jar on the bench. It is still producing CO2, the jar has no headspace and no airlock, and you get either a mess or a genuinely dangerous pressure vessel.",
  experiment: "Split one cucumber. Half goes into a 5 percent vinegar brine, half into a 2 percent salt brine under a weight. Measure the pH of each at day 1 and day 7 and write down four numbers.",
  reflection: "Where did the fermented half sit at day 1, and how long was it above pH 4.6 with nothing but salt protecting it?",
  deepDive: "Help me decide whether something I want to pickle should be acidified or fermented, given how long I want to keep it."
}
);
