/* Track: Heat transfer and equipment. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "heat-three-modes",
  track: "heat", level: "weeknight",
  title: "Conduction, convection and radiation each dominate somewhere",
  source: "Peter Barham, The Science of Cooking",
  idea: "Every cooking method is dominated by one of three heat transfer modes, and knowing which one is doing the work tells you which variable to change.",
  why: "Conduction moves energy through direct contact, and it is what a pan does: metal touching protein, with a transfer coefficient in the hundreds or thousands of watts per square metre per kelvin. Convection moves energy in a moving fluid, and it is what an oven mostly does: hot air sweeping past the surface at maybe 10 to 25 W/m2K in a still oven, three or four times that with the fan on. Radiation moves energy as infrared with no medium at all, and it is what a grill element or a bed of coals does, scaling with the fourth power of the source's absolute temperature.\n\nThe practical consequence is that the lever differs by mode. Under conduction, contact area and pan temperature are the levers, which is why a warped pan cooks in patches. Under convection, air speed matters as much as air temperature, which is why the fan setting changes browning more than 10C on the dial does. Under radiation, distance is the lever and the dial is nearly irrelevant. Reaching for the temperature knob when the dominant mode is radiation is why grilling goes wrong so reliably.",
  failureMode: "You turn the grill down because the top of the parmigiana burnt, and now the cheese is pale and greasy and the middle is still cold. The problem was 5cm of distance, not the element temperature. Radiant intensity fell but so did the total energy, so nothing browned and nothing heated.",
  experiment: "Preheat a pan to about 200C, an oven to 200C and the grill on high. Hold your palm 15cm above each for as long as is comfortable and record the seconds for each. Then hold your palm 15cm above the pan and 3cm above the pan and record both. The pan at distance will feel almost cold: that gap is the difference between conduction and the weak convection above it.",
  reflection: "Which mode was dominant in the last thing you cooked that disappointed you, and were you adjusting a lever that belonged to a different mode?",
  deepDive: "Take a dish I cook regularly, break the cooking into stages, and tell me which heat transfer mode dominates in each stage and which single variable I should be adjusting there."
},
{
  id: "heat-capacity-vs-conductivity",
  track: "heat", level: "project",
  title: "Heat capacity and thermal conductivity are different properties",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Conductivity governs how fast heat spreads sideways through a pan, capacity governs how much energy the pan holds, and pan materials trade the two off against each other.",
  why: "Thermal conductivity in W/mK: copper about 400, aluminium about 205, cast iron about 55, stainless steel about 15. That number sets how quickly a hot spot over the burner evens out across the base, which is why a copper pan tracks the flame with almost no lateral gradient and why bare stainless has a scorched ring where the element sits. Cladding exists to fix exactly this: a tri-ply pan is a slab of aluminium wearing a stainless skin, because stainless is a terrible conductor and a good cooking surface.\n\nSpecific heat capacity in J/kgK: aluminium about 900, iron about 460, copper about 385. Iron looks poor per kilogram, but a 26cm cast iron skillet weighs about 2.3kg against maybe 700g for aluminium, so it stores roughly 1060 J/K against 630 J/K. Mass wins. That stored energy is what survives contact with 200g of cold steak. The two properties answer different questions: conductivity answers how even is it, capacity answers how much does it sag when you load it.",
  failureMode: "Buying a heavy pan and expecting it to be even, or buying a conductive pan and expecting it to hold. A thin copper crepe pan is beautifully even and drops 60C the moment batter hits it. Thick cast iron holds temperature and still gives you a bright ring over the burner and cool corners.",
  experiment: "Heat a cast iron pan and an aluminium or clad pan until both read 200C at the centre with an infrared thermometer or a probe. Drop 200g of fridge-cold chopped onion into each. Read the surface temperature again at 30 seconds and record the drop in degrees for each pan. Write down both numbers and the pan weights.",
  reflection: "Which of your pans has the largest sag under a cold load, and is that the pan you have been searing in?",
  deepDive: "Here is what is in my cupboard, with rough weights and materials. Tell me which pan I should be using for each of searing, gentle egg cookery, reducing a sauce and shallow frying, and why."
},
{
  id: "heat-cast-iron-slow",
  track: "heat", level: "weeknight",
  title: "Cast iron is slow in and slow out",
  source: "J. Kenji Lopez-Alt, The Food Lab",
  idea: "Cast iron's virtue is thickness and mass, not the metal, and that makes it the wrong pan for responsive work and the right pan for absorbing a cold steak.",
  why: "At 55 W/mK, iron conducts about a quarter as well as aluminium, so heat crawls sideways and the pan carries a persistent hot ring over the burner and cold corners. A preheated cast iron skillet routinely spreads 40 to 60C across its base. That gradient does not disappear with more preheating, it only shifts upward, because the burner keeps feeding one region and the metal cannot redistribute fast enough.\n\nWhat it does have is stored energy and thermal inertia, and that is a mass effect rather than a material one. Two kilograms of iron at 230C will surrender a lot of joules to a cold steak before it drops out of searing range, and it will not respond to you turning the gas down either. Both directions of that lag are the same property. Treat cast iron as a battery you charge slowly and discharge into something cold, not as a control surface.",
  failureMode: "Scrambled eggs in cast iron, set solid over the burner ring and still liquid at the edge. Or a sauce that catches in the middle while the perimeter never comes to a simmer. Both are the conductivity gradient, and neither is fixable by stirring more.",
  experiment: "Preheat a cast iron pan and a clad or aluminium pan on the same burner at the same setting for 8 minutes. Probe five points on each base with an infrared thermometer: centre, and four points 3cm in from the rim at twelve, three, six and nine o'clock. Record the highest minus the lowest for each pan. Then turn both burners off and probe the centres again at 3 minutes to get the cooling rate.",
  reflection: "Given the spread you measured, where exactly on your cast iron should the steak go, and what should never go in that pan at all?",
  deepDive: "I measured this temperature spread across my cast iron pan. Tell me which dishes in my usual rotation that gradient will ruin and what I should cook in it instead."
},
{
  id: "heat-pan-vs-oven",
  track: "heat", level: "weeknight",
  title: "A hot pan and a hot oven are not the same heat",
  source: "J. Kenji Lopez-Alt, The Food Lab",
  idea: "The same number on a pan and on an oven dial delivers energy at rates that differ by one to two orders of magnitude, so oven temperature and pan temperature are not interchangeable.",
  why: "Heat transfer rate is the temperature difference multiplied by a transfer coefficient, and it is the coefficient that varies wildly. Still air in an oven manages roughly 10 to 25 W/m2K. A fan raises that to maybe 40 to 60. Metal in direct contact with food is in the hundreds to low thousands. So 220C air and 220C steel are the same temperature delivering completely different power, because air is a poor conductor and holds almost no energy per unit volume in the first place.\n\nThis is why the oven is a soaking device and the pan is a surfacing device. An oven at 220C will bring a whole chicken to 74C in the middle without ever scorching it, because the surface loses heat to evaporation almost as fast as the air supplies it. A pan at 220C will build crust in 90 seconds and cannot reach the middle of anything thicker than a finger. The two are not settings on the same scale, they are different tools, and the standard sear then roast is just using each for the job the coefficient suits.",
  failureMode: "Trusting oven temperature as if it were surface temperature. You roast vegetables at 200C, expect the browning you get in a 200C pan, and get pale steamed pieces instead. The air never got the surface hot enough, and the tray was crowded so the moisture never left.",
  experiment: "Cut two slices from the same loaf. Put one in a 220C oven on a rack and one in a dry pan preheated to 220C on the surface. Time each to the same medium brown. Record both times. Expect a factor of five or more.",
  reflection: "Where in your cooking have you been treating an oven number and a pan number as the same setting?",
  deepDive: "For a dish I want both crust and a cooked interior on, tell me how to split the work between pan and oven, and give me the target temperature and the checkpoint for each stage."
},
{
  id: "heat-water-clamp-100c",
  track: "heat", level: "weeknight",
  title: "Water clamps the surface at 100C",
  source: "Harold McGee, On Food and Cooking",
  idea: "While liquid water is boiling at sea level, its temperature cannot rise past 100C no matter how much energy you add, so a violent boil cooks no faster than a gentle one.",
  why: "Additional energy going into water already at its boiling point does not raise the temperature, it converts liquid to vapour. That is latent heat, about 2257 kJ per kilogram, and it all goes into the phase change. The thermometer sits at 100C while the pot empties. Turning the burner from a bare simmer to a roaring boil buys you a little extra agitation, which thins the boundary layer around the food and speeds transfer somewhat, but the driving temperature is identical.\n\nThe same clamp explains why boiled and steamed and braised food never browns. Maillard chemistry needs surface temperatures well above 100C to run at any useful rate, and pyrolysis needs more still. As long as free water is present at the surface it holds that surface at or below 100C. Browning in a wet dish therefore has to happen before the liquid goes in or after it has cooked off, never during.",
  failureMode: "Cranking the pasta water to a violent boil in the belief it is faster, boiling off a litre, scorching the base once the water drops below the element line, and having pasta break up in the turbulence. Or waiting for a braise to brown in the liquid, which it never will.",
  experiment: "Bring a pot to a bare simmer with occasional bubbles and probe the water away from the base. Then take it to a full rolling boil and probe again in the same spot. Write down both readings. They will agree within your thermometer's resolution. Note the ambient reading too: if you are not at sea level, the clamp sits below 100C.",
  reflection: "Which pot on your stove has been on high for no reason, and what did the two readings actually differ by?",
  deepDive: "Walk me through a braise I cook, and tell me exactly where the browning has to happen given that everything under liquid is clamped at 100C."
},
{
  id: "heat-pressure-cooker-121c",
  track: "heat", level: "project",
  title: "A pressure cooker reaches 121C and roughly quadruples reaction rates",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "One bar of gauge pressure lifts water's boiling point to about 121C, and since most cooking reactions roughly double per 10C, that is a fourfold speed-up plus browning inside a wet pot.",
  why: "Boiling point rises with pressure. At 1 bar above atmospheric, the standard setting on most consumer cookers, water boils at about 121C. That is the same number autoclaves use, and it is not a small change: reaction rates in cooking follow an Arrhenius curve that works out to roughly a doubling per 10C over the range that matters, so 21C above the clamp is close to a factor of four on collagen hydrolysis, starch breakdown and Maillard chemistry.\n\nThe browning part is the interesting one, because it breaks the rule that wet means pale. Maillard runs slowly but measurably at 121C even submerged, so a pressure-cooked stock develops colour and roasted notes that a simmered one never will in the same time. Adding a pinch of bicarb to raise the pH accelerates it further. The trade is loss of volatiles: nothing escapes the sealed pot during cooking, and the delicate aromatics you would want in a fish stock get cooked into something heavier.",
  failureMode: "Treating the pressure cooker as a fast simmer and using it for something delicate. A pressure-cooked prawn stock comes out muddy and cooked-tasting, because the aromatics that make it worth the effort are exactly what 121C destroys.",
  experiment: "Split a batch of chicken bones and aromatics in two. Simmer one at 95C for 45 minutes and pressure cook the other for 45 minutes at full pressure. Cool both, pour into identical glasses side by side, and record the colour difference and which tastes more roasted. Weigh both before and after to check you have not just concentrated one.",
  reflection: "Which of your slow dishes would gain from 121C, and which one depends on volatiles that pressure would flatten?",
  deepDive: "Take a stock or braise I make and tell me whether pressure would improve it or damage it, based on which compounds carry its flavour."
},
{
  id: "heat-evaporative-cooling",
  track: "heat", level: "project",
  title: "Evaporative cooling holds a roast surface below 100C until it dries",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "A wet surface in a hot oven sits far below air temperature because evaporation carries heat away, so nothing browns until that surface has dried.",
  why: "Every gram of water leaving the surface takes about 2257 joules with it. While free moisture is available, that latent heat draw balances most of the energy arriving from the air, and the surface settles near a wet bulb temperature that in a dry 220C oven lands somewhere around 70 to 90C rather than at 220C. The oven can be as hot as you like and the skin stays in the range where Maillard chemistry barely moves.\n\nBrowning therefore has a queue: dry the surface first, then heat it, then react. Everything you do to shorten the drying stage buys browning time. Uncovered in the fridge overnight pulls surface moisture out in advance. Salting the skin draws water out and then lets it evaporate. A rack under the bird stops it sitting in a puddle. Spacing on the tray lets vapour leave instead of raising local humidity and stalling every neighbour. This is also why a crowded tray of vegetables steams: the tray is not too cool, it is too wet.",
  failureMode: "Roasting a chicken straight from the packet with damp skin, getting 40 minutes into a 30 minute browning window with pale flabby skin, then cranking the oven and overcooking the breast trying to catch up.",
  experiment: "Take two pieces of chicken thigh with skin. Pat one dry and leave it uncovered on a rack in the fridge for 12 hours. Pat the other dry only just before cooking. Roast both together at 200C. At 15 minutes, probe the skin surface of each with an infrared thermometer and record both readings. Note the time each reaches equal colour.",
  reflection: "How many degrees apart were the two surfaces at 15 minutes, and how much roasting time did the fridge-dried piece save?",
  deepDive: "Tell me which of the things I roast are limited by surface drying rather than oven temperature, and what to change the night before for each."
},
{
  id: "heat-alcohol-retention",
  track: "heat", level: "weeknight",
  title: "Alcohol does not all cook off",
  source: "Augustin, Augustin, Cutrufelli, Hagen and Teitzel, Alcohol retention in food preparation, Journal of the American Dietetic Association, 1992",
  idea: "Ethanol and water form an azeotrope and leave the pot together rather than the alcohol boiling out first, so a dish simmered for an hour still holds about a quarter of the alcohol added.",
  why: "The folk belief comes from ethanol's boiling point of 78C, which suggests it should vanish before the water even boils. Mixtures do not work that way. Ethanol and water form a positive azeotrope, so the vapour leaving a dilute solution is richer in ethanol than the liquid but nowhere near pure, and the remaining liquid keeps a falling but non-zero alcohol concentration for as long as there is liquid at all. You are distilling slowly, not evaporating selectively.\n\nThe measured retention figures are blunt. In the 1992 study behind the USDA retention tables, alcohol added to a boiling liquid and removed from the heat retained about 85 percent. Flamed, about 75 percent. Simmered or baked for 15 minutes, about 40 percent. At 30 minutes, about 35 percent. At an hour, about 25 percent. At two and a half hours, still about 5 percent. Nothing in normal cooking gets to zero.",
  failureMode: "Telling someone who does not drink, or is pregnant, or is on metronidazole, that the wine has cooked out of the sauce after twenty minutes. It has not. Roughly 35 to 40 percent is still there. The flavour reasoning is also wrong in the other direction: cooks who splash in wine and boil hard for two minutes think they have removed harshness when they have removed almost nothing.",
  experiment: "Put 100ml of wine in a small pan, bring to a simmer and measure the remaining volume at 15, 30 and 60 minutes by pouring into a measuring jug and returning it. Record all three volumes. Note that volume reaching a third does not mean alcohol reaching zero, because the ratio in what left is not the ratio in what stayed. Then taste the 60 minute reduction neat and see whether it still reads as alcoholic.",
  reflection: "Which dish do you serve to people who avoid alcohol, and what is your honest estimate of the retention in it now?",
  deepDive: "Given a dish I cook with wine or spirits, estimate the alcohol retained at serving and tell me what to change if I need it genuinely low."
},
{
  id: "heat-frying-oil-uptake",
  track: "heat", level: "project",
  title: "Frying is heat in and water out, and oil enters late",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Escaping steam keeps oil out while the food is frying, and most oil uptake happens during cooling as the interior contracts and pulls surface oil inward.",
  why: "The bubbling around a chip is water leaving as vapour at over a thousand times its liquid volume. That outward flow pressurises the crust from inside and physically prevents oil from entering. Oil at the surface is doing one job during frying: conducting heat in at a rate air cannot match, because oil can sit at 180C without a phase change and has a transfer coefficient in the hundreds. Almost none of it crosses the crust while steam is coming out.\n\nWhen the food leaves the oil, the steam generation stops and the trapped vapour in the crust condenses. That creates a pressure drop inside the porous structure, and the surface oil clinging to the outside gets drawn in. This is why the standard fried chip carries most of its oil in and just under the crust rather than distributed through the potato, and why drying, draining and separating hot matters far more than anything you did in the fryer. A limp chip resting in a bowl is a chip actively pumping oil into itself.",
  failureMode: "Piling hot chips into a bowl lined with paper towel and letting them sit. The steam condenses, the crust softens, and the pool of oil at the bottom goes back into the chips. Ten minutes later they are greasy and soft, and the fryer gets the blame.",
  experiment: "Weigh 200g of raw chips. Fry them, lift out, shake off and weigh immediately hot. Then spread them in a single layer on a rack and weigh again at 10 minutes. Record all three numbers. Compare with a second 200g batch left heaped in a bowl for the same 10 minutes and weighed. The difference between the racked and heaped batches is oil you chose to eat.",
  reflection: "How many grams apart were the racked and heaped batches, and how much of your fried food's greasiness has been a draining problem rather than a frying problem?",
  deepDive: "Take something I deep fry and tell me where in the process oil is actually entering it, and what to change to cut the uptake without losing crust."
},
{
  id: "heat-batch-size-recovery",
  track: "heat", level: "weeknight",
  title: "Batch size is really a question of temperature recovery",
  source: "J. Kenji Lopez-Alt, The Food Lab",
  idea: "Overloading a fryer is a thermal problem, not a crowding problem: cold food drags the oil down and the recovery rate depends on oil mass and burner power.",
  why: "Oil has a specific heat capacity around 2000 J/kgK, roughly half of water's. Two litres of oil at 180C dropped to 140C by a cold load has to reabsorb something like 160 kJ to get back, and a domestic burner delivering maybe 2kW to the pot takes over a minute to do it, assuming nothing is being lost to the ongoing evaporation from the food itself, which it is. So the oil sits below target for a meaningful fraction of the cook.\n\nBelow about 150C the physics changes character. Steam generation slows, the outward pressure that keeps oil out weakens, the crust sets slowly and the food spends longer in contact with oil at a temperature where it soaks rather than seals. The result is not just paler, it is measurably greasier. More oil volume gives more thermal mass and a smaller dip for the same load, which is the entire reason a deep pot of oil outperforms a shallow one for the same food.",
  failureMode: "Dumping 500g of frozen chips into 1.5 litres of oil at 180C, watching the temperature fall to 130C, and pulling out limp grey chips eight minutes later. The oil never recovered because the load kept boiling water off and stealing latent heat faster than the burner could resupply.",
  experiment: "Heat oil to 180C with a probe in it. Add a small batch, say 100g, and record the temperature at 30 seconds and 2 minutes. Let it recover fully to 180C, then add 400g and record the same two readings. Write down all four numbers, plus the oil volume and the time to recover to 180C in each case. That recovery time is your real batch size limit.",
  reflection: "What is the largest load your pot can take without dropping below 150C, and have you been exceeding it every time?",
  deepDive: "Given my pot size, oil volume and burner, work out the maximum batch I can fry without dropping below 150C, and how long I need between batches."
},
{
  id: "heat-smoke-point-falls",
  track: "heat", level: "weeknight",
  title: "Smoke point falls with use",
  source: "Harold McGee, On Food and Cooking",
  idea: "Smoke comes from free fatty acids and breakdown products that accumulate with heating and food debris, so a published smoke point applies only to fresh oil.",
  why: "Triglycerides themselves are fairly stable. What smokes at low temperature is the small volatile fraction: free fatty acids released by hydrolysis, plus aldehydes, ketones and short chain fragments from oxidation and thermal cracking. Every hour at frying temperature raises the free fatty acid content, and every crumb of batter left in the pot accelerates it by adding water for hydrolysis and surface area for oxidation. Unrefined oils start lower on the same logic, because they carry more free fatty acids and more particulate to begin with, which is why extra virgin olive oil smokes earlier than refined olive oil from the same fruit.\n\nSo the published number is a property of a batch, not of a species of oil. Refined peanut oil quoted at 230C might be smoking at 190C after four fries. The visible smoke matters beyond the alarm: acrolein and the other volatiles are irritants, and the same breakdown chemistry produces the stale, fishy, painty flavours that make old fryer oil recognisable before you see it.",
  failureMode: "Reusing oil from the same pot for weeks because it still looks clear, then finding a batch of chips tastes of old oil at the same time as the kitchen fills with smoke at a temperature that used to be fine. Both symptoms are the same accumulated free fatty acids.",
  experiment: "Heat 200ml of fresh oil in a small pan with a probe in it and record the temperature at the first wisp of continuous smoke. Repeat with 200ml of oil from your last fry, strained, in the same pan. Record both numbers and the difference. Do this with a window open and the oil shallow.",
  reflection: "How many degrees had your used oil lost, and does that change how many fries you get out of a batch?",
  deepDive: "Tell me how to judge when to discard frying oil using observations I can make at home, and what the smoke point drop I measured implies about my current reuse habit."
},
{
  id: "heat-steam-latent-heat",
  track: "heat", level: "project",
  title: "Steam at 100C carries far more energy than air at 100C",
  source: "Peter Barham, The Science of Cooking",
  idea: "Condensing steam releases about 2257 kilojoules per kilogram directly onto the food surface, which is why steaming outruns a 100C oven by a wide margin.",
  why: "Dry air at 100C transfers heat only by the temperature difference, and its volumetric heat capacity is tiny: a litre of air cooling from 100C to 60C gives up around 50 joules. Steam is a different proposition, because when it touches a surface below 100C it condenses, and the phase change releases the full latent heat of vaporisation at the point of contact. Effective transfer coefficients for condensing steam run into the thousands of W/m2K, two orders of magnitude above still air.\n\nThe same mechanism explains the counterintuitive behaviour of steam injection in bread ovens. Steam heats the loaf surface faster than dry air, which is why a steamed oven gives better oven spring, and simultaneously keeps that surface wet, which is why it browns later. You get heat sooner and colour later, and the baker's trick is to have steam for the first ten minutes and dry heat after. Once the surface dries above 100C, browning starts from an already-hot crust and moves quickly.",
  failureMode: "Assuming steaming is the gentle slow option because 100C sounds low. Steamed fish overcooks faster than oven-baked fish at the same nominal temperature, and people who transfer an oven time to a steamer serve it dry.",
  experiment: "Cut two 3cm cubes from the same potato. Steam one over boiling water and put the other on a rack in an oven set to 100C, both with a probe in the centre. Record the core temperature of each at 15 minutes. Expect a gap of tens of degrees.",
  reflection: "What was the core temperature gap at 15 minutes, and which of your steamed dishes have you been timing as if it were oven cooking?",
  deepDive: "Explain where steam would help a dish I bake or roast, at which stage, and how to generate it in a domestic oven without ruining the browning."
},
{
  id: "heat-radiant-inverse-square",
  track: "heat", level: "weeknight",
  title: "Distance is the grill's real control, not the dial",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Radiant intensity falls off steeply with distance from the element, so moving the shelf is a far bigger lever than changing the setting.",
  why: "A compact radiant source obeys an inverse square law: double the distance, quarter the intensity. A grill element is not a point source, it is an extended one, so close in the falloff is gentler than the square and only approaches it once you are far enough away that the element subtends a small angle. The honest version is that intensity drops steeply and non-linearly with distance, somewhere between linear and inverse square depending on how wide your element is and how close you are. Either way the effect of moving a shelf rung dwarfs anything the dial does.\n\nThe dial is weak for a second reason. Most domestic grills are on or off, and the setting changes duty cycle rather than element temperature. Since radiant emission scales with the fourth power of absolute temperature, the element's actual temperature is the thing that matters and you have almost no access to it. Distance you have complete access to, in 2cm increments, for free.",
  failureMode: "Turning the grill to medium to stop the top burning, which just means the element spends half its time off. The surface still burns during the on phase, and the interior gets less total energy, so you end up with a burnt and cold piece of food instead of a burnt and hot one.",
  experiment: "Grill two slices of bread to the same medium brown, one on a shelf 5cm below the element and one at 10cm, both on high. Time each. Record both times and the ratio. If your element is wide, the ratio will be well under four, which tells you how far from a point source it is.",
  reflection: "What was your time ratio between 5cm and 10cm, and which shelf position should the things you grill actually live on?",
  deepDive: "For the things I grill, tell me what shelf distance and what stage of cooking each should be at, given that distance is the main lever."
},
{
  id: "heat-oven-cycling",
  track: "heat", level: "weeknight",
  title: "Your oven cycles about 20C either side of the set point",
  source: "Cook's Illustrated",
  idea: "Domestic ovens are bang-bang controllers with wide hysteresis and persistent hot spots, so the number on the dial is an average at best and often not even that.",
  why: "The thermostat has two states: element on and element off. It fires when the sensor reads below a threshold and stops when it reads above one, and the gap between those thresholds plus the thermal lag of the element means the air temperature oscillates. Swings of 15 to 25C either side of the set point are normal, so an oven set to 180C spends its time between roughly 160C and 200C on a slow sawtooth of several minutes per cycle. The sensor is also in one location, usually near the back wall, so it is measuring one point in a cavity that is not uniform.\n\nOn top of the cycling there is a static gradient. Ovens are hotter near the element, hotter at the back, and hotter at the top where buoyant air collects. Differences of 20 to 30C between corners of the same shelf are common, and they do not average out over time because they are geometric rather than temporal. This is the whole reason recipes tell you to rotate the tray, and the reason two identical trays of biscuits on two shelves come out different.",
  failureMode: "Blaming a recipe when one side of the tray of biscuits is brown and the other is pale, or a cake domes and cracks on one edge. Neither is the recipe. Also: calibrating your oven once by the dial offset and assuming it now behaves, when the swing and the gradient are untouched by any offset.",
  experiment: "Put an oven probe in the geometric centre of the middle shelf, set the oven to 180C, wait for it to signal preheated, then log the reading every minute for 20 minutes. Write down the maximum, the minimum and the mean. Then move the probe to the back left corner of the same shelf and log five more minutes. Record the difference between positions.",
  reflection: "What was your oven's swing, and where on the shelf is its hot corner?",
  deepDive: "Here is my oven's measured swing and hot spot map. Tell me which of the things I bake are actually sensitive to that and what to change."
},
{
  id: "heat-instant-read",
  track: "heat", level: "weeknight",
  title: "An instant-read thermometer is the highest-leverage tool in the kitchen",
  source: "J. Kenji Lopez-Alt, The Food Lab",
  idea: "Every temperature-dependent claim in cooking is unverifiable without a fast thermometer, and response time and probe placement matter more than the quoted accuracy.",
  why: "Almost everything worth knowing in the kitchen is a temperature threshold. Egg proteins set between 62C and 70C. Collagen converts to gelatin usefully above about 70C. Starch gelatinises between 60C and 80C depending on the source. Maillard chemistry needs a surface well above 100C. None of those are visible, and every one of them is a number you can check in two seconds. A thermometer converts cooking from a timing exercise, where the variables you cannot see all conspire, into a measurement exercise.\n\nThe specification that matters is response time, not accuracy. A probe quoted at plus or minus 0.5C that takes 12 seconds to settle is worse than one quoted at plus or minus 1C that settles in 2 seconds, because your hand is not steady and the oven door is open. Placement matters more than either: the reading is only meaningful at the coldest point, which is the geometric centre of the thickest part, away from bone and away from the pan surface. A probe 5mm off centre in a steak can read 8C high.",
  failureMode: "Pulling a roast at the right time and finding it 10C off, because the probe tip was in the shallow part of the muscle or touching bone. Or trusting a slow probe read two seconds after insertion, which is reading the air the probe was just in, not the meat.",
  experiment: "Cook a thick steak or a chicken breast. When you think it is done, probe it at five depths along one insertion line: just under the surface, quarter depth, centre, three quarter depth, and just under the far surface. Record all five numbers. Then push the probe in slowly from the side and watch the number fall and rise, and note where the minimum sits.",
  reflection: "What was your surface to core spread, and how far off centre would your usual probe placement have been?",
  deepDive: "For the proteins I cook most, tell me the pull temperature, where exactly to place the probe, and how much carryover to expect for each."
},
{
  id: "heat-calibrate-two-points",
  track: "heat", level: "weeknight",
  title: "Calibrate in ice water and boiling water",
  source: "Harold McGee, On Food and Cooking",
  idea: "Every kitchen has two free reference temperatures, 0C in a stirred ice slurry and 100C in boiling water at sea level, so any probe's drift is detectable in two minutes.",
  why: "An ice slurry, meaning crushed ice with just enough water to fill the gaps and stirred continuously, is pinned at 0C by the same phase change logic that pins boiling water at 100C. It is a genuine fixed point and it is more reliable than the boiling point, which moves with altitude and weather. Sydney is at sea level so 100C holds, but a few hundred metres of elevation costs you about a degree per 300m, and a deep low pressure system is worth a few tenths.\n\nTwo points give you more than one, because they separate offset from span. If both readings are 2C high, you have a fixed offset you can subtract everywhere. If ice reads correct and boiling reads 4C high, the scaling is wrong and the error grows with temperature, which matters most at exactly the temperatures you care about. Some probes have a calibration screw or a software offset. For the ones that do not, the offsets written on a note in the drawer work just as well.",
  failureMode: "Deciding your oven runs cold based on a probe that reads 6C low, then compensating in the oven and stacking the two errors. Or discovering after a year that the cheap probe you have been trusting for chicken has drifted 5C in the direction that matters.",
  experiment: "Fill a glass with crushed ice, add water to just cover, stir for 30 seconds and probe it while stirring, tip in the middle and not touching the glass. Record the reading. Then probe a pot of boiling water, tip well clear of the base. Record that. Do both for every probe you own, including the oven thermometer and any leave-in. Write the two offsets on a note and tape it inside the drawer.",
  reflection: "Which of your probes was furthest out, and was the error a fixed offset or did it grow between 0C and 100C?",
  deepDive: "I measured these offsets at 0C and 100C for each of my probes. Tell me how to correct for them and which readings I should stop trusting."
},
{
  id: "heat-induction-vs-gas",
  track: "heat", level: "project",
  title: "Induction heats the pan and gas heats the air around it",
  source: "Nathan Myhrvold, Modernist Cuisine",
  idea: "Induction couples energy directly into a ferromagnetic pan base at around 85 percent efficiency, while a gas burner puts roughly 40 percent into the pan and the rest into the kitchen.",
  why: "An induction hob is a coil driven at 20 to 50 kHz. It induces eddy currents in the pan base, and those currents dissipate as resistive heating in the metal itself, with hysteresis losses in the ferromagnetic material adding to it. The cooktop stays cool except for what the pan conducts back into it. Because the heating element is the pan, the response to a control change is near instant and the delivered power is well defined. It also means the pan base must be ferromagnetic: aluminium and copper without a steel disc will not couple.\n\nGas burns above the pan's needs and loses most of it. Flame contacts only the base annulus, hot combustion gases sweep up the sides and away, and radiant losses go in every direction. Typical delivered efficiency is 35 to 45 percent. The response is also slower than it feels, because the pan and the trivet and the burner head all hold heat: turning gas off leaves a hot burner radiating for a while. The everyday consequence is that gas needs more burner watts for the same result and heats the room, and induction lets you hold a genuine low simmer without a diffuser.",
  failureMode: "Buying a beautiful copper or aluminium pan for an induction kitchen and finding it does nothing. Or moving from gas to induction and burning the first three things because the same nominal setting delivers more than twice the power to the pan.",
  experiment: "Put 1 litre of cold tap water in the same pan, record the starting temperature, and time it to a full boil on each hob you have access to, at maximum. Record the times and the rated wattage of each burner. Then divide: 1 litre going from 20C to 100C needs about 335 kJ, so 335 divided by your time in seconds gives the delivered kilowatts. Compare that to the rating for your efficiency.",
  reflection: "What delivered efficiency did you calculate for each hob, and does that explain any timing you have found unreliable?",
  deepDive: "Given the delivered power I measured for my hob, tell me what settings correspond to the temperatures I actually want for searing, frying and simmering."
},
{
  id: "heat-air-fryer",
  track: "heat", level: "weeknight",
  title: "An air fryer is a small convection oven with a fast fan",
  source: "Cook's Illustrated",
  idea: "There is no separate mechanism in an air fryer, only a small chamber and high air velocity that thins the boundary layer and raises the convective heat transfer coefficient.",
  why: "Every surface in moving air carries a thin stagnant boundary layer, and that layer is the bottleneck: heat has to conduct across still air before the bulk flow can carry it away or bring it in. Raising air velocity thins the layer and raises the convective coefficient. A domestic fan oven manages maybe 40 to 60 W/m2K. An air fryer's small chamber and aggressive fan can push that meaningfully higher, and the small cavity preheats in two minutes instead of fifteen. That is the whole trick. There is no frying, no oil mechanism, no separate physics.\n\nWhich means the same result is available in a fan oven if you match the conditions: high fan, food on a rack so air reaches all sides, and a load small enough that the escaping moisture does not raise chamber humidity. That last point is where air fryers usually win by accident, because their basket forces you to cook small quantities in a single layer on a perforated surface, which is exactly what a crowded oven tray prevents. The advantage is geometry and discipline, not technology.",
  failureMode: "Believing you need the appliance, or believing it scales. Filling the basket to the top gives you the same steamed grey result as a crowded oven tray, because the mechanism that was helping you was single layer airflow and you just removed it.",
  experiment: "Cook 300g of the same chips in the air fryer basket in a single layer, and 300g on a wire rack over a tray in a fan oven at the same temperature. Time each to the same colour and record both times. Then repeat the air fryer batch with 600g heaped in and record how long that takes to reach the same colour, if it ever does.",
  reflection: "How much faster was the air fryer at equal load, and did doubling the load cost you more than double the time?",
  deepDive: "Tell me which things in my rotation genuinely benefit from an air fryer's airflow and which are just a fan oven with fewer steps."
}
);
