/* Track: One tradition in depth. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "sichuan-profiles-not-recipes",
  track: "sichuan", level: "weeknight",
  title: "Sichuan cooking is a system of flavour profiles, not a set of recipes",
  source: "Fuchsia Dunlop, Invitation to a Banquet",
  idea: "The tradition names and codifies its seasoning combinations as compound flavours, so learning about two dozen profiles generalises across every ingredient in a way that memorising dishes never does.",
  why: "Sichuan cooking has an explicit vocabulary for its combinations. They are called fuhe wei, compound flavours, and the canonical teaching list runs to roughly twenty-three of them: yu xiang, guai wei, mala, hong you, jiao ma, suan la, hu la, jia chang, tang cu and so on. Each one names a set of seasonings held in a rough proportion. A dish is then a profile applied to an ingredient by a cooking method, and the three axes are largely independent.\n\nThat is why the tradition is worth studying as a system. Twenty-three profiles crossed with the ingredients in your fridge and half a dozen methods is a very large space you can navigate, whereas forty memorised recipes is forty memorised recipes. When Dunlop writes that Sichuan chefs are taught the profiles first, she is describing a curriculum built around the reusable part.",
  failureMode: "You cook fish-fragrant aubergine from a recipe perfectly, then buy 400g of pork mince with no recipe to hand and have nothing to reach for, because you learned a dish rather than the yu xiang proportions that would have carried straight over to the mince.",
  experiment: "Write down three Sichuan dishes you have eaten or cooked. Beside each, name the compound flavour it belongs to. Score yourself out of three. If you get zero, that is the honest baseline this track starts from.",
  reflection: "Which of the three could you not place, and was it because you did not know the profile or because the dish genuinely sits between two of them?",
  deepDive: "Give me the canonical list of Sichuan compound flavours with the defining seasonings for each, and tell me which five would cover the most weeknight ground."
},
{
  id: "sichuan-ma-la-two-channels",
  track: "sichuan", level: "weeknight",
  title: "Ma la is two senses running in parallel",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  idea: "Capsaicin and Sichuan pepper act on different nerve populations, so the burn and the numbing are separate channels you can dial independently rather than one combined intensity.",
  why: "Capsaicin binds TRPV1, a heat-and-acid receptor on nociceptive C fibres. The brain reads that firing as thermal pain, which is why chilli genuinely feels hot and why the sensation builds slowly and clears slowly, over several minutes. Hydroxy-alpha-sanshool from Sichuan pepper works on a different population entirely: it blocks two-pore potassium channels in touch-sensitive fibres, and a fibre that cannot leak potassium depolarises and fires. So the touch channel reports contact where there is none.\n\nTwo consequences follow. First, ma and la are orthogonal, so a dish can be strongly numbing with almost no heat, or fiercely hot with no tingle, and the classical profiles exploit exactly that. Second, they have different time courses. The sanshool tingle arrives within seconds and fades in ten to twenty minutes; capsaicin heat lags and outlasts it. If you season both at once and taste once, you are sampling two curves at one arbitrary point.",
  failureMode: "You judge a mapo doufu as \"too spicy\" and cut the chilli, when what was actually overwhelming was 4g of ground Sichuan pepper flooding the touch channel. The next version is bland and still tingles.",
  experiment: "Set out three tastes: a pinch of chilli flakes alone, three toasted Sichuan peppercorns alone, then both together. Rate burn 0 to 5 and tingle 0 to 5 for each, separately, and write the six numbers down. Wait 90 seconds between them.",
  reflection: "Did the combined taste score higher on either axis than the single ingredient did, or did it just feel busier?",
  deepDive: "Help me rebalance a dish I cooked where the ma and la felt wrong, by asking me which of the two channels was actually excessive before suggesting any change."
},
{
  id: "sichuan-sanshool-50hz",
  track: "sichuan", level: "project",
  title: "Hydroxy-alpha-sanshool feels like a 50Hz vibration",
  source: "Nobuhiro Hagura, Harry Barber and Patrick Haggard, Food vibrations: Asian spice sets lips trembling, Proceedings of the Royal Society B 2013",
  idea: "The tingling from Sichuan pepper was matched psychophysically against real mechanical vibration and came out around 50Hz, which is direct evidence that it is a touch sensation rather than a taste.",
  why: "The experiment is clean. Subjects had Sichuan pepper applied to the lip, then a mechanical vibrator applied to a finger, and were asked to adjust the vibrator frequency until it matched what their lip was feeling. The matches clustered near 50Hz. That frequency band is the response peak of RA1 mechanoreceptors, the Meissner corpuscles that handle flutter and light contact, so the numbing is your touch system reporting a stimulus that is not there.\n\nThis reframes what the ingredient is doing. It is not a taste that happens to be odd, and it is not a mild anaesthetic despite the English word numbing. It is a chemically induced tactile hallucination, and it stacks on top of the real texture of the food rather than replacing it. That also explains why the sensation is spatially located, on the lips and tongue tip where mechanoreceptor density is highest, rather than diffuse the way a taste is.",
  failureMode: "Treating ma as a taste leads you to balance it against salt, sugar or acid, which does nothing. Nothing you dissolve in the sauce turns down a mechanoreceptor. The only lever is dose and freshness of the pepper itself.",
  experiment: "Crush two Sichuan peppercorns onto your lower lip and leave them for 30 seconds. Set your phone to a continuous vibrate and hold it against a fingertip. Write down whether the phone feels faster, slower or about the same as your lip, and note the minute mark at which the lip sensation drops below noticeable.",
  reflection: "Was the sensation located, or general across the whole mouth, and what does your answer imply about which receptors are involved?",
  deepDive: "Explain how sanshool blocking two-pore potassium channels produces firing in touch fibres, and why that reads as flutter rather than as pressure."
},
{
  id: "sichuan-profile-taxonomy",
  track: "sichuan", level: "project",
  title: "The flavour profiles are a taxonomy with defined ratios",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  idea: "Yu xiang, guai wei, hong you, mala and jiao ma are each defined by which seasonings appear and in what proportion, which makes them reproducible specifications rather than loose styles.",
  why: "Take five of them side by side. Yu xiang is pickled chilli, ginger, garlic, spring onion, sugar and vinegar, served hot, with the sweet-sour balanced against the pickle. Guai wei is sesame paste, soy, sugar, vinegar, chilli oil, ground Sichuan pepper and sesame oil, served cold, with no note allowed to lead. Hong you is chilli oil, soy and sugar, cold, with the chilli oil carrying the dish and little or no Sichuan pepper. Mala is chilli plus Sichuan pepper at real strength, usually with doubanjiang, served hot. Jiao ma is Sichuan pepper pounded with fresh spring onion greens, salt and stock, cold, with no chilli at all.\n\nThe last pair is the clearest proof that these are specifications. Mala and jiao ma both centre on Sichuan pepper, and they are different profiles because one includes chilli and one excludes it. Two profiles can share most of their ingredient list and be distinguished by a ratio: hong you and guai wei overlap heavily, and guai wei becomes hong you if you drop the sesame paste and let the chilli oil lead.",
  failureMode: "Treating the profiles as vibes produces a sauce that is nearly guai wei but with the vinegar too high, which is not a variation of anything. It is just a sour sauce, and it has left the taxonomy without arriving anywhere.",
  experiment: "Pick two profiles from the list above and write their seasoning lists in two columns on paper. Circle every ingredient that appears in one and not the other. Then write one sentence naming what the differences do. You should end with three or fewer circled items for most pairs.",
  reflection: "Which pair turned out to be closer than you expected, and what single ingredient was carrying the distinction?",
  deepDive: "Give me the seasoning specification for five Sichuan compound flavours as a table with rough proportions by weight, and mark which are served hot and which cold."
},
{
  id: "sichuan-yu-xiang",
  track: "sichuan", level: "weeknight",
  title: "Yu xiang has no fish in it and a fixed proportion of six things",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  idea: "Fish-fragrant flavour is pickled chilli, ginger, garlic, spring onion, sugar and vinegar in balance, and its identity is the sweet-sour tension against the pickle rather than any single ingredient.",
  why: "The name records where the seasoning came from, not what is in it. This is the combination Sichuan cooks traditionally used for fish, and it kept the name when it moved to aubergine, pork and chicken. The pickled chilli is the non-negotiable part. Pao la jiao has been through a lactic ferment in brine, so it brings lactic and acetic acid, glutamate and a soft fruity heat that fresh chilli does not have, and it is why the profile cannot be faked with chilli plus vinegar.\n\nThe ratio matters more than the list. A workable starting point is 15g sugar, 15g Chinkiang vinegar, 15g soy sauce and 30g chopped pickled chilli, with 10g each of finely chopped ginger, garlic and spring onion white. Sugar and vinegar are meant to arrive together and neither should be identifiable on its own. Shift the sugar by 2g in either direction and the sauce stops reading as fish-fragrant and starts reading as sweet-and-sour or as plain sour.",
  failureMode: "Substituting fresh chilli and a splash of vinegar for pickled chilli. You get heat and acid, no ferment, and the sauce tastes thin and one-dimensional next to a real one, because you removed the only ingredient that was contributing amino acids.",
  experiment: "Mix the sauce alone by weight, no dish, and taste a teaspoon. Add 2g more sugar to the whole batch and taste again. Write down at which of the two you could name a leading flavour, because the correct answer is that you can name one only in the unbalanced version.",
  reflection: "At the balanced point, what did the sauce taste of, and did you find yourself reaching for a word other than the six ingredients?",
  deepDive: "Help me scale a yu xiang sauce for 400g of pork mince and tell me what to change if my only vinegar is Chinkiang rather than a Sichuan pickle brine."
},
{
  id: "sichuan-guai-wei",
  track: "sichuan", level: "project",
  title: "Guai wei succeeds when nothing dominates",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  idea: "Strange-flavour puts salty, sweet, sour, numbing, spicy, nutty and savoury in one cold sauce, and the pass condition is that a taster cannot name a leading note.",
  why: "Most sauces are built around a lead with the rest in support. Guai wei is built to have no lead, which is why the Chinese name translates as strange or odd: what is strange is the absence of a hierarchy, not the presence of anything unusual. Every component is present at a level where it is detectable in isolation but not identifiable in the mixture, and the result is a sauce your palate keeps trying to resolve and cannot.\n\nThat makes it the hardest profile to build and the best diagnostic exercise in the tradition, because it is the only one with an objective pass condition you can test on another person. A rough starting balance for 100g of sauce is 20g sesame paste, 20g soy sauce, 12g sugar, 12g Chinkiang vinegar, 20g chilli oil with sediment, 1g ground roasted Sichuan pepper, 8g sesame oil and finely chopped garlic and spring onion. Sesame paste is doing structural work as well as flavour, since it thickens the sauce and slows every component onto the tongue at the same rate.",
  failureMode: "The usual failure is the vinegar, which is volatile and hits first. A sauce that is 3g over on vinegar reads as sour-with-things-in-it, and the taster names sour immediately. The second most common is chilli oil poured without its sediment, which loses the body and lets the soy lead.",
  experiment: "Build 100g of the sauce by weight. Give a teaspoon to someone else with one instruction: name the dominant taste. If they answer in under three seconds, you have failed and the thing they named is the thing to cut by 2g. Repeat until they hesitate.",
  reflection: "Which component did you have to pull back, and did the finished sauce taste better to you or merely harder to describe?",
  deepDive: "I will give you my guai wei weights and what a taster named first; tell me which single component to adjust and by how much."
},
{
  id: "sichuan-doubanjiang",
  track: "sichuan", level: "project",
  title: "Doubanjiang is broad bean and chilli fermented for years",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  idea: "Pixian chilli bean paste gets its depth from a long mould and lactic fermentation of broad beans with salted chilli, which accumulates free amino acids and colour over months to years, so age is the main quality variable.",
  why: "Two ferments run in sequence. Broad beans are inoculated with Aspergillus, which secretes proteases that cut bean protein into peptides and free amino acids, glutamate among them. The mould-covered beans are then combined with chillies that have been salted and fermented separately, and the mixture sits in open jars, stirred and sunned, for anywhere from six months to three years or more. Over that time proteolysis continues, Maillard chemistry proceeds slowly at ambient temperature, and the paste darkens from bright red to a deep brick brown.\n\nSo the label to read is the age, not the brand. A young supermarket paste is salty, sharply chilli-forward and thin in the mouth. A three-year Pixian paste is darker, less aggressively hot, and has a savoury weight that comes from accumulated free amino acids rather than from anything added. Most bought pastes are also cut with wheat flour and colouring, which is another reason two jars labelled the same thing are not the same ingredient.",
  failureMode: "Swapping a young paste one-for-one into a recipe developed on aged Pixian gives you a dish that is salty and hot but hollow, and the usual reaction is to add more paste, which makes it saltier without adding any of the depth that was missing.",
  experiment: "Buy an aged Pixian doubanjiang and put 5g of it beside 5g of whatever you currently have. Taste both raw. Write exactly three words for each, and note the colour difference, which should be visible before you taste anything.",
  reflection: "Was the difference mostly in the salt, the heat or the savouriness, and could you have identified the aged one blind?",
  deepDive: "Tell me what to look for on a doubanjiang label to judge age and whether it has been cut with flour, and which brands sold in Australia are the real thing."
},
{
  id: "sichuan-frying-bean-paste",
  track: "sichuan", level: "weeknight",
  title: "Frying the bean paste is a step with a temperature",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  idea: "Cooking doubanjiang in oil at a moderate heat around 120C extracts its red pigment into the fat and cooks off the raw fermented smell, and taking it much hotter turns it bitter.",
  why: "The red in chilli is capsanthin and capsorubin, fat-soluble carotenoids that are locked in the solid paste and invisible in the dish until a hot fat pulls them out. That is the visible signal of the step working: the oil goes from clear to a deep translucent red in 30 to 60 seconds of gentle frying, and everything cooked in that oil afterwards is coloured. The aroma change is separate and slower, as the sharp raw-ferment volatiles boil off and the paste develops a rounder roasted smell.\n\nThe ceiling is set by everything else in the paste. Doubanjiang carries residual sugars, amino acids and bean solids, and past roughly 140 to 150C those scorch rather than brown, giving acrid burnt notes that no amount of stock will cover. This is why the classical instruction is a gentle heat and constant stirring, and why the step is done at the start with the oil off full heat, not thrown into a screaming wok.",
  failureMode: "Adding the paste to a wok already at stir-fry temperature. It hits 200C oil, the solids catch inside 15 seconds, and the whole dish carries a bitter edge that reads as burnt garlic. You cannot rescue it, because the bitterness is in the oil that everything else will be cooked in.",
  experiment: "Put 40g of neutral oil in a small pan with a probe thermometer in the oil, add 30g of doubanjiang, and warm it slowly. Write down the oil temperature at the moment the fat visibly turns red, and the temperature at which the raw smell disappears. Keep it under 140C.",
  reflection: "How far apart were the colour temperature and the aroma temperature, and which one arrived first?",
  deepDive: "Walk me through the order of operations for a mapo doufu, and say at which point the wok goes back up to full heat after the bean paste step."
},
{
  id: "sichuan-chilli-oil-extraction",
  track: "sichuan", level: "project",
  title: "Chilli oil is an extraction with a temperature range",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  cheat: "Pour oil onto chilli flakes at 130C to 150C; above about 180C they pyrolyse and you get ashy notes instead of fragrance.",
  idea: "Capsaicin, pigment and aroma compounds move into oil at different rates and have different heat tolerances, so roughly 130C to 150C is the window that gets aroma and colour without scorching.",
  why: "Three separate extractions are happening. Capsaicin is strongly lipophilic and comes out readily at almost any temperature above warm, so heat is not what controls the burn - the amount of chilli is. The carotenoid pigments need real heat to leave the plant tissue and are why cold-infused chilli oil looks pale. The aroma compounds are the fragile part: volatile esters and aldehydes that carry the fruity, toasted character, and they are both driven off and destroyed at high temperature.\n\nSo the window is narrow at the top. Below about 110C you get heat and very little colour or fragrance. Between 130C and 150C the pigment comes out and the aroma survives. Above about 180C the sugars and proteins in the flake pyrolyse rather than toast, and you get acrid, ashy notes and a duller brown-red. This is also the argument for the multi-pour method some cooks use: a small first pour hotter for toasted character, the bulk poured in the middle of the window for colour and fragrance.",
  failureMode: "Heating oil until it shimmers and smokes, then pouring it over the flakes. Smoke point on a neutral oil is around 200C or above, so the flakes scorch on contact, the oil goes brown rather than red, and the finished oil smells of ash. It will still be hot, which is why people conclude it worked.",
  experiment: "Weigh out three 20g portions of chilli flakes into three heatproof bowls. Pour 60g of oil at 180C, 150C and 120C over them, one each, with a probe to confirm. Photograph all three after 10 minutes and rank them by colour and by smell separately. Write down whether the rankings agree.",
  reflection: "Did the hottest pour smell the strongest or merely the harshest, and which bowl would you actually eat from?",
  deepDive: "Help me design a two-pour chilli oil, specifying temperatures and the split by weight, using the chilli varieties I can buy in Sydney."
},
{
  id: "sichuan-chilli-varieties",
  track: "sichuan", level: "weeknight",
  title: "Different chillies are used for different jobs",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  idea: "Erjingtiao is chosen for fragrance and deep colour, facing-heaven types for pungency, and a Sichuan chilli blend is a deliberate composition of three separable properties rather than one ingredient at one strength.",
  why: "Fragrance, colour and heat come from different compounds and do not correlate. Heat is capsaicinoids, concentrated in the placental tissue holding the seeds. Colour is carotenoids in the pericarp. Fragrance is a volatile fraction that varies by cultivar and by how the chilli was dried, and slow sun-dried chillies keep more of it than kiln-dried ones. A variety can therefore be high in one and low in another, and erjingtiao is the clearest case: long, wrinkled, deeply red, intensely fragrant, and only moderately hot.\n\nThat is why Sichuan cooks blend. You choose erjingtiao because you want the smell and the colour, then add a proportion of a hotter upward-pointing chilli because erjingtiao alone will not deliver the heat. Buying one bag of unlabelled generic chilli flakes fixes all three properties at whatever ratio that cultivar happens to have, and takes away the only real control you had.",
  failureMode: "Trying to get more fragrance by adding more of a hot generic flake. Heat scales with the dose, fragrance does not appear, and you end up with an oil that is punishing to eat and still smells of nothing much.",
  experiment: "Make two small batches of chilli oil, one from erjingtiao alone and one from a 70:30 blend of erjingtiao and a hot chilli, using the same oil temperature and the same total 20g of chilli. Smell both, then taste both on plain rice. Rate aroma 0 to 5 and heat 0 to 5 separately and write down all four numbers.",
  reflection: "Did the single-variety oil actually lack heat, or did it lack heat only relative to what you have got used to?",
  deepDive: "Tell me which dried chillies sold in Sydney Asian grocers correspond to erjingtiao and to facing-heaven types, and what a sensible starting blend ratio is."
},
{
  id: "sichuan-velveting",
  track: "sichuan", level: "weeknight",
  title: "Velveting holds water in the meat with starch and alkali",
  source: "Fuchsia Dunlop, The Food of Sichuan; Harold McGee, On Food and Cooking",
  idea: "Egg white and cornflour form a barrier that slows heat transfer and moisture loss, while a small amount of alkali raises the meat's pH away from the isoelectric point so the proteins hold more water.",
  why: "Muscle protein holds least water at its isoelectric point, around pH 5.2, where positive and negative charges balance and the filament lattice collapses. Fresh meat sits close to that, around pH 5.6. Push it up to 6.2 or 6.5 with a little bicarb soda and the filaments carry net negative charge, repel each other, and the lattice swells and traps water that would otherwise be squeezed out as the proteins denature. About 0.5 to 1 percent bicarb by meat weight is the working range, so 2g for 300g of pork.\n\nThe coating is a separate mechanism. Egg white and cornflour form a hydrated gel layer on the surface that gelatinises as it heats, which both slows conduction into the meat and physically holds the released juice at the surface where it thickens the sauce instead of pooling in the pan. Two mechanisms, two levers, and they are worth understanding separately because too much bicarb gives a soapy, slippery texture that no amount of starch will hide.",
  failureMode: "Skipping the rest. Bicarb needs 15 to 30 minutes to diffuse through 3mm slices, and mixing it in immediately before the wok gives you surface alkalinity and untreated interior, which is the soapy-outside, dry-inside result people blame on velveting itself.",
  experiment: "Slice 300g of pork thinly and split it. Velvet one half with 1g bicarb, one egg white and 10g cornflour, rest 20 minutes. Stir-fry both halves identically in separate batches. Pour the liquid left in each pan into a measuring jug and record the two volumes in millilitres.",
  reflection: "How large was the gap in pan liquid, and did the velveted half also feel different in the mouth or only weigh differently?",
  deepDive: "Tell me the right bicarb percentage and rest time for chicken breast, beef flank and prawns, and which of the three should skip the egg white."
},
{
  id: "sichuan-dry-frying",
  track: "sichuan", level: "weeknight",
  title: "Dry-frying removes water first and browns second",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  idea: "Gan bian holds the ingredient in moderate oil long enough to drive off internal moisture, concentrating flavour and turning the texture chewy and wrinkled before any real browning happens, which makes it a dehydration technique.",
  why: "The oil in dry-frying is a heat transfer medium, not a cooking fat in the deep-frying sense. It is present in enough quantity to make contact with the whole surface and hot enough to hold that surface above 100C, so water inside the bean or the meat boils and escapes continuously for several minutes. The name is accurate: what you are doing is drying. Green beans go from smooth and turgid to blistered and wrinkled because the cell walls collapse as the water leaves.\n\nBrowning is a consequence, not the goal, and it arrives late. Surfaces cannot exceed 100C while they are still wet, so Maillard chemistry only starts once a patch has dried out, which is why the char appears in blisters rather than evenly. The flavour change is mostly concentration: the same sugars, amino acids and aromatics in 70 percent of the original mass. That is also why dry-fried dishes take more seasoning than their raw weight suggests.",
  failureMode: "Crowding the pan. Steam from the beans cannot leave, the surface never gets above 100C, and after 10 minutes you have limp oily beans that are cooked but not dried. The tell is that they lost almost no weight.",
  experiment: "Weigh 300g of green beans. Dry-fry them until wrinkled and blistered, drain the oil off, and weigh again on the same scale. Calculate the percentage lost. Expect somewhere between 15 and 30 percent, and write down which end you landed on.",
  reflection: "At what minute did the beans start to wrinkle, and how much longer after that did the first brown blisters appear?",
  deepDive: "Give me a target weight-loss percentage for dry-frying beef, eels and green beans, and tell me how to tell by eye that each has got there."
},
{
  id: "sichuan-wok-hei",
  track: "sichuan", level: "project",
  title: "Wok hei needs the pan hotter than the food and the food moving",
  source: "J. Kenji Lopez-Alt, The Wok",
  idea: "The aroma depends on brief contact between food and a metal surface far above 200C, which requires both high stored heat in the wok and constant motion so nothing sits in one place long enough to steam.",
  why: "Two things have to be true at once. The surface has to be hot enough for rapid Maillard chemistry and for the fat itself to break down into the volatile compounds that carry the smell, which means well above 200C. And contact has to be brief, because food sitting still on the metal drops that patch below 100C within seconds and then blankets it in its own steam, so the surface never recovers while the food is on it.\n\nThe reason a wok works is thermal mass and geometry, not magic. A carbon steel wok is thin, so it responds fast, but the sloped sides mean the flame heats a large area and the food you toss is repeatedly returning to metal that has been reheating while it was in the air. Tossing is not showmanship. It is how you keep giving the food fresh hot surface while giving each patch of surface time to recover.",
  failureMode: "Stirring rather than tossing, with a heavy stainless pan. The metal is thick, it recovers slowly, and stirring keeps food in continuous contact. The surface sits around 100C for the whole cook and you have made a stew in a frying pan.",
  experiment: "Heat your wok until a drop of water balls and skitters. Take a surface reading with an infrared thermometer, aiming at a black seasoned patch rather than bare shiny steel, which reads badly. Add 250g of food, wait 20 seconds, and take a second reading. Write down both numbers and the drop.",
  reflection: "How far did it fall, and how long did the empty wok take to climb back to the first reading once you removed the food?",
  deepDive: "Given the drop I measured, tell me whether my burner and wok can support a single-batch stir-fry or whether I have to split it, and by how much."
},
{
  id: "sichuan-burner-power",
  track: "sichuan", level: "weeknight",
  title: "A domestic burner delivers a fraction of a restaurant range",
  source: "J. Kenji Lopez-Alt, The Wok",
  idea: "A home cooktop supplies roughly a tenth of the power of a Chinese restaurant range, so the workable compensations are smaller batches, longer preheat and drier ingredients rather than a bigger wok.",
  why: "A typical Australian domestic gas burner runs 2 to 3.5kW, and a dedicated home wok burner might reach 5kW. A restaurant range burner is commonly 30kW and can be far more. The consequence is not that your food cooks more slowly, it is that your wok cannot recover heat while food is in it. The restaurant burner is replacing energy faster than the food removes it; yours is not, so every gram you add is a withdrawal from stored heat that will not be replaced until the pan is empty again.\n\nThat is why the three fixes are the ones they are. Smaller batches reduce the withdrawal. Longer preheat increases the stored balance you start with, and a wok needs several minutes on full heat, not thirty seconds. Drier ingredients cut the largest single heat sink, because evaporating 100g of surface water costs about 226kJ, which is more than a 3kW burner delivers in a minute. A bigger wok does not help, since it adds mass your burner cannot heat.",
  failureMode: "Emptying 500g of just-washed bok choy into the wok at once. The pan temperature collapses below 100C, the water on the leaves boils, and the food braises in its own liquid. The dish is grey and there is 80ml of water in the bottom of the wok.",
  experiment: "Cook 400g of stir-fry in one batch. Tip it out, measure the liquid pooled in the wok in millilitres, and write it down. Clean, reheat, and cook another 400g in two batches of 200g. Measure again. Compare the two numbers.",
  reflection: "Did splitting the batch halve the pooled liquid or do better than that, and how much extra clock time did the two-batch version actually cost?",
  deepDive: "Tell me the maximum batch size my burner can handle for a given wok, and how to estimate it from the temperature drop I measured."
},
{
  id: "sichuan-preserved-vegetables",
  track: "sichuan", level: "project",
  title: "Preserved vegetables are concentrated glutamate",
  source: "Fuchsia Dunlop, The Food of Sichuan; Ole Mouritsen and Klavs Styrbaek, Umami",
  idea: "Ya cai, zha cai and the other salt-preserved Sichuan vegetables undergo long fermentation that liberates free amino acids, which is why 20g of them changes a dish more than 200g of the fresh vegetable would.",
  why: "Salting draws water out and selects for salt-tolerant lactic bacteria, and over months of fermentation the vegetable's own proteases plus microbial enzymes break stored protein into free amino acids. Glutamate is the one that matters for taste, because bound glutamate inside a protein chain is tasteless and only the free form binds the umami receptor. The same process concentrates everything else, since the vegetable has lost most of its water: Yibin ya cai is mustard greens that have been salted, dried and fermented for a year or more, and zha cai is stem mustard pressed, salted and fermented with chilli.\n\nSo these are not vegetables in a dish, they are seasonings that happen to look like vegetables. They also bring lactic acid and a large amount of salt, which is the practical constraint. Adding 20g of ya cai to a stir-fry is adding roughly 2 to 4g of salt along with the savouriness, and the rest of the seasoning has to come down to match.",
  failureMode: "Rinsing ya cai thoroughly because it seems too salty, then adding soy sauce to compensate. You have washed away water-soluble glutamate and lactic acid and replaced them with salt from a different source, so the dish is as salty as before and less savoury.",
  experiment: "Cook the same simple stir-fry twice, identical except that one gets 20g of ya cai. Hold the added salt constant between them so the only variable is the ya cai. Rate savouriness 0 to 5 for each and write down both numbers, plus whether you needed less soy in the second one.",
  reflection: "Was the difference in savouriness or in salt, and could you separate the two while tasting?",
  deepDive: "Tell me the difference between ya cai, zha cai, dong cai and suan cai, what each is for, and roughly how much salt 20g of each is contributing."
},
{
  id: "sichuan-pepper-degrades",
  track: "sichuan", level: "weeknight",
  title: "Sichuan pepper loses its numbing with age",
  source: "Fuchsia Dunlop, The Food of Sichuan",
  cheat: "Never double the dose of an old Sichuan pepper jar: sanshool degrades in months while the aroma survives, so buy 50g at a time.",
  idea: "Sanshools are chemically unstable and degrade over months, so an old jar delivers citrus aroma with little tingle, and the fix is to buy small quantities and toast lightly just before grinding.",
  why: "Hydroxy-alpha-sanshool is a polyunsaturated fatty acid amide with a conjugated double-bond chain, which is exactly the structure that oxidises and isomerises readily. Light, air and warmth all accelerate it, and the isomers it converts to are far less active on the touch fibres. The aroma is a separate fraction, mostly terpenes like limonene and linalool in the husk, and it survives better and evaporates on a different schedule. That mismatch is why an old jar still smells convincingly of Sichuan pepper and does almost nothing to your lips.\n\nToasting is a compromise, not a repair. A brief dry-pan toast at low heat drives off moisture and makes the husks brittle enough to grind, and it volatilises aroma compounds so they are perceptible. It cannot regenerate degraded sanshool, and pushing the toast too far destroys what is left. Buy in 50g lots, keep the jar dark and closed, grind to order, and discard on a timescale of months rather than years.",
  failureMode: "Doubling the dose of a two-year-old jar to get the tingle back. You get twice the woody, husky bitterness and no more numbing, because the compound you wanted is gone and the one you are adding more of is not it.",
  experiment: "Buy a fresh 50g bag. Chew three peppercorns from your current jar, note the second at which the tingle starts and the minute it fades. Rinse, wait five minutes, repeat with three fresh ones. Write both durations down. A gap of more than five minutes means your jar is spent.",
  reflection: "Did the old jar still smell right, and if so, how much would you have trusted your nose to judge it?",
  deepDive: "Tell me how to store Sichuan pepper for maximum sanshool retention, and what toasting temperature and time gives aroma without destroying the numbing."
}
);
