/* Track: Capital allocation. Ordered foundational first. */
(window.LESSONS = window.LESSONS || []).push(
{
  id: "capital-outsiders-eight-cases",
  track: "capital", level: "read",
  title: "Capital allocation is the chief executive's real job and eight cases prove it",
  source: "Thorndike, The Outsiders: Eight Unconventional CEOs and Their Radically Rational Blueprint for Success (Harvard Business Review Press)",
  idea: "In Thorndike's eight cases the outperformance came from where the money went, not from how well the business was run.",
  why: "The method is what makes the book usable rather than inspirational. Thorndike measures each chief executive by compound annual return to shareholders over the full tenure, then benchmarks that against the market index over the same period and against peers in the same industry over the same period. The double benchmark strips out the decade and the sector, so what is left is attributable to the person. None of the eight ran a glamorous business. Several ran declining ones.\n\nWhat they shared was treating the deployment of each dollar as the decision and everything else as execution. That is the transfer for you. Operating excellence has a ceiling set by allocation: a platform team that ships flawlessly against a badly chosen roadmap returns less than an average team pointed at the right thing. Your re-charter is an allocation question and it will be decided by people who think in those terms whether or not you present it that way.",
  failureMode: "You walk into the funding room with an operating argument. On-time delivery, defect rate, incident count, developer satisfaction. Every one of those is a claim about execution quality, and none of them competes with a revenue project's claim about where the dollars should go. The revenue project does not have to be better run than you. It only has to have a return.",
  experiment: "Apply Thorndike's benchmark logic to your own last four quarters. List every engineer-quarter your team spent, group them into three or four buckets of work, and rank the buckets by the dollar effect you can actually defend, whether cost removed or revenue enabled. Output one number: the percentage of engineer-quarters that went into the highest-ranked bucket. Write it down before you read it charitably.",
  reflection: "What percentage of your capacity went to the highest-value bucket, and who decided that split - you, or accumulated obligation?",
  recall: {
    q: "What are the two benchmarks Thorndike measures each chief executive against, and why does he need both?",
    a: "Compound annual shareholder return over the full tenure, measured against the broad market index and against industry peers over the identical period.\n\nOne benchmark alone would let a good decade or a good sector masquerade as a good chief executive. Using both strips out the market and the industry, leaving the part attributable to the person's decisions."
  },
  deepDive: "Take the four work buckets I ran last year and help me rank them by defensible dollar effect, telling me which ones I cannot yet put a number on and what I would have to measure to fix that."
},
{
  id: "capital-five-uses-of-a-dollar",
  track: "capital", level: "read",
  title: "There are five things a company can do with a dollar",
  source: "Thorndike, The Outsiders, introduction (five deployment choices, three funding sources); Mauboussin and Callahan, Capital Allocation, Counterpoint Global Insights, Morgan Stanley Investment Management",
  idea: "Every dollar can be reinvested in the existing business, spent acquiring another one, used to pay down debt, used to buy back stock, or paid out as a dividend, and your funding request competes against the other four.",
  why: "Thorndike sets this out in the introduction: five ways to deploy capital, three ways to raise it (internal cash flow, debt, equity issuance). The list matters because it makes the competition explicit. Your platform investment is not being weighed against other engineering projects. It is being weighed against a buyback, against an acquisition that buys the same capability, and against simply not spending the money.\n\nMauboussin and Callahan add the empirical layer: they break down how capital is actually deployed across public companies and split investment into mergers and acquisitions, capital expenditure, research and development, and working capital, with the return of capital happening through dividends, repurchases and debt paydown. For a software company the R and D line is the dominant one and it is mostly your salaries. That is the sentence that should change how you write your ask.",
  failureMode: "You assume the alternative to funding your team is funding a different engineering team. It is not. At a company generating cash, the standing alternative is a share repurchase, which has a known and immediate effect, or holding the cash. Your proposal has to beat a mechanical option, not just a rival roadmap.",
  experiment: "Open the most recent 10-K of any of the comparables in this corpus - Snowflake, Datadog, MongoDB, Confluent, GitLab, Elastic or HashiCorp - and go to the consolidated statement of cash flows. Read the investing and financing sections line by line and tick off which of the five uses appear and which do not. Output: the list of uses that company actually exercised last fiscal year. Then find the research and development line in the income statement and note where it sits relative to every investing line.",
  reflection: "For the comparable you read, which of the five uses did the company not exercise at all, and what does that tell you about how it sees its own reinvestment opportunities?",
  recall: {
    q: "Name the five uses of a dollar and the three sources of one, and say which use dominates for a software company.",
    a: "Uses: reinvest in the existing business, acquire, pay down debt, repurchase stock, pay a dividend. Sources: internal cash flow, debt, equity issuance.\n\nFor a software company reinvestment dominates, and most of it is research and development, which is mostly engineering salaries. Your headcount is the company's largest capital deployment even though it never appears as an investing cash flow."
  },
  deepDive: "Walk me through the investing and financing sections of a specific software 10-K cash flow statement and tell me which of the five uses that company is actually exercising."
},
{
  id: "capital-roic-computed-right",
  track: "capital", level: "model",
  title: "Return on invested capital is computable and commonly computed wrong",
  source: "Mauboussin and Callahan, Return on Invested Capital: How to Calculate ROIC and Handle Common Issues, Counterpoint Global Insights, Morgan Stanley Investment Management",
  idea: "Return on invested capital is net operating profit after tax over invested capital, and both terms need adjustments before the number compares across two companies.",
  why: "The numerator is not net income. It is operating profit after cash taxes, before financing, because you are measuring the business rather than the capital structure. Using net income mixes in interest and makes a leveraged company look different from an identical unleveraged one. The denominator is the capital actually tied up in operations: operating working capital plus net fixed assets plus other operating assets. Excess cash comes out, because cash sitting on a balance sheet is not invested in anything.\n\nTwo choices change the answer materially and both are defensible depending on the question. Goodwill in or out: including it asks whether the acquisitions paid off, excluding it asks whether the underlying operating business earns a return. Operating leases: since the current lease accounting standard these sit on the balance sheet as right-of-use assets, so the adjustment that used to be manual is now largely done for you, but check rather than assume. The paper walks each adjustment. The reason to do the walk is that the number only means something when the two companies you are comparing were computed the same way.",
  failureMode: "Someone quotes a return on invested capital figure for a company off a data provider screen and compares it to one computed by hand from a filing. The two used different goodwill treatments and different definitions of excess cash. The comparison is noise presented as a decision input, and nobody checks because both numbers are percentages with one decimal place.",
  experiment: "Pick one comparable and compute return on invested capital from its most recent 10-K twice: once with goodwill in the denominator, once with it out. You need operating income, the effective cash tax rate, total assets, cash and equivalents plus short-term investments, current liabilities that are non-interest-bearing, and goodwill, all of which are on the face of the statements. Output: two percentages and the size of the gap between them. If the gap is large, that company bought its capability rather than building it.",
  reflection: "Which of the two figures would you quote if you were arguing that the company should build rather than acquire, and does that make you uncomfortable?",
  recall: {
    q: "Why is the numerator of return on invested capital operating profit after tax rather than net income, and what comes out of the denominator?",
    a: "Net income is after interest, so it mixes the financing decision into a measure of operating performance and makes two otherwise identical businesses look different because one carries debt. Operating profit after cash taxes measures the business itself.\n\nExcess cash comes out of the denominator because it is not deployed in operations. Whether goodwill stays in depends on the question: in, to judge whether acquisitions earned their price; out, to judge the underlying operating business."
  },
  deepDive: "Help me compute return on invested capital from a specific 10-K, naming every line item you need from the statements and flagging where I have to make a judgement call."
},
{
  id: "capital-intangibles-expensed",
  track: "capital", level: "model",
  title: "Software return on capital is overstated because intangible investment is expensed",
  source: "Mauboussin and Callahan, Categorizing for Clarity: Cash Flow Statement Adjustments for Intangible Investments, Counterpoint Global Insights, Morgan Stanley Investment Management",
  idea: "Engineering spend runs through the income statement as an expense rather than onto the balance sheet as an asset, which shrinks invested capital and inflates every return ratio a software company reports.",
  why: "Under US accounting rules research and development is expensed as incurred, with only a narrow carve-out for certain internal-use software development costs. A factory that costs a hundred million dollars becomes an asset and is depreciated over its life. A hundred million dollars of engineering that produces a durable platform becomes an expense in the year it is spent and never appears as capital. The economics are similar. The accounting is not.\n\nThe consequence for the ratio is mechanical. Invested capital is understated, so return on invested capital is overstated, and for a company whose only real assets are intangible the denominator can approach nothing and the ratio stops meaning anything at all. Mauboussin and Callahan's fix is to reclassify the investment portion of research and development and of sales and marketing out of operating expense, capitalise it, and amortise it over an estimated useful life. Two things follow that matter to you directly. Reported operating margin understates a growing software company's economics. And your team's payroll is capital investment wearing an expense costume, which is exactly why a headcount ask should be argued as a capital request.",
  failureMode: "You benchmark your company's operating margin against a comparable and conclude you are inefficient, when the comparable is simply growing more slowly and therefore expensing less investment. Growth spend and running cost land on the same income statement line, so the line cannot distinguish a company that is investing from one that is bloated.",
  experiment: "Take one comparable's last three fiscal years of research and development expense from the 10-K. Capitalise it: assume a three-year straight-line useful life, build the running asset balance and the annual amortisation, then add that asset to the invested capital you computed in the previous entry and recompute the return. Output: the reported return, the adjusted return, and the ratio between them. Change the useful life to five years and watch how much the answer moves, which tells you how load-bearing your assumption is.",
  reflection: "How large was the gap between reported and adjusted return, and does that change which comparable you think is actually the better business?",
  recall: {
    q: "Why does expensing research and development inflate a software company's return on invested capital, and what is the adjustment?",
    a: "Expensing keeps the spend off the balance sheet, so invested capital is understated. The same profit divided by a smaller denominator produces a larger return, and for a company with almost no tangible assets the denominator can be small enough that the ratio is meaningless.\n\nThe adjustment is to treat the investment portion of research and development and sales and marketing as capital: capitalise it, amortise it over an estimated useful life, add the resulting asset to invested capital, and add back the amortisation difference in the numerator."
  },
  deepDive: "Take three years of research and development expense from a filing I give you and show me the capitalisation schedule and the adjusted return, with the useful-life assumption stated separately so I can flex it."
},
{
  id: "capital-moat-is-persistence",
  track: "capital", level: "read",
  title: "A moat is a return above the cost of capital that persists",
  source: "Mauboussin and Callahan, Measuring the Moat: Assessing the Magnitude and Sustainability of Value Creation, Credit Suisse Global Financial Strategies",
  idea: "Competitive advantage is defined numerically as a return on invested capital above the cost of capital, and the moat is how long that gap survives.",
  why: "The definition is a subtraction and a duration. Value is created when return on invested capital exceeds the weighted average cost of capital. A company earning twenty per cent on capital that costs it ten per cent creates value at ten points of spread. If the spread closes next year, there was no moat, just a good year. The magnitude is the spread; the sustainability is the competitive advantage period. Mauboussin and Callahan spend most of the paper on the second because it is the part that gets assumed rather than argued: industry structure, the five forces, the interaction of firms, disruption risk, and where the company sits on the value chain.\n\nThis is the frame that lets you argue a platform creates advantage rather than convenience. The claim has to be that it produces a return above the cost of capital, and that something specific prevents the gap from closing. Switching cost, scale economies in your cloud spend, accumulated data, or a compliance boundary a competitor would have to rebuild. If you cannot name the mechanism that keeps the spread open, you have built efficiency, not a moat, and efficiency is copied.",
  failureMode: "A platform team claims strategic value with no number and no persistence mechanism. Strategic becomes the word used when the return is not computed. Meanwhile the actual moat in the business is somewhere else entirely, usually in data gravity or an integration surface nobody funded deliberately, and it goes unmaintained because it was never named.",
  experiment: "Write two lines for your own platform. Line one: the return, expressed as annual dollars of cost removed or revenue enabled over the capital deployed to build and run it. Line two: the mechanism that stops a competitor or an internal alternative from closing that gap within three years, named specifically. Then write a third line: what would have to happen for the gap to close in eighteen months. If line three is easy to write and line two is hard, you have your answer.",
  reflection: "Could you name the persistence mechanism without hedging, and if not, what does that imply about how you should describe the platform in the re-charter?",
  recall: {
    q: "State the numerical definition of a moat and name its two components.",
    a: "A moat is return on invested capital sustained above the weighted average cost of capital. The two components are magnitude, which is the size of the spread between the two rates, and sustainability, which is how many years the spread persists before competition closes it.\n\nA large spread for one year is not a moat. The sustainability half is the part that requires an argument about industry structure rather than an arithmetic result."
  },
  deepDive: "Pressure-test the persistence mechanism I claim for my platform and tell me the three most credible ways a competitor or an internal build closes the gap inside two years."
},
{
  id: "capital-build-buy-partner-tco",
  track: "capital", level: "model",
  title: "Build against buy against partner is computed, not argued",
  source: "Mauboussin and Callahan, Capital Allocation, Counterpoint Global Insights, mergers and acquisitions section; Wang and Casado, The Cost of Cloud, a Trillion Dollar Paradox, Andreessen Horowitz; your fully loaded engineering cost",
  cheat: "Add a maintenance row to every build estimate; over a three-year horizon it often exceeds the one-time engineering cost.",
  idea: "Put build, buy and partner in one table with total cost of ownership over the same horizon and the same discount rate, and let the arithmetic pick.",
  why: "The three options are almost never compared on the same terms. Build gets quoted as an initial engineering estimate with no ongoing maintenance line. Buy gets quoted as year-one licence with no contractual escalator and no integration cost. Partner gets quoted as a revenue share with no exit cost. Force them into one table with identical rows and the comparison becomes possible: initial engineering in engineer-years times the loaded rate, annual maintenance in engineer-years, incremental cloud spend, vendor fees with the escalator from the actual contract, one-time integration and migration, and exit cost if you have to reverse the decision.\n\nWang and Casado's argument is the interesting shape here rather than any single figure they quote. Buying is right early because it converts fixed cost into variable and preserves optionality, and building becomes right at scale because the variable cost keeps growing while the fixed cost does not. That means the answer is a crossover point, not a preference, and the crossover moves as your volume moves. Their piece cites the Dropbox infrastructure optimisation disclosed in Dropbox's own S-1 as the worked case, which is where to go for a real disclosed number rather than a plausible one.",
  failureMode: "The build estimate excludes the maintenance annuity. A team quotes six engineer-months to build, ships it, and then carries one engineer indefinitely on upkeep, on-call and dependency upgrades. Over a three-year horizon the omitted row is larger than the row that was included, and it is the row that made build look cheaper.",
  experiment: "Take one real decision in front of you. Build the table: three columns, and rows for initial engineering, annual maintenance, incremental cloud cost, vendor fees with escalator, integration, and exit. Fill it for three years. Discount each column at the hurdle rate from the Damodaran entry. Output: three net present values and the annual volume at which the ranking flips. If you cannot find a flip point, one option is dominated and you should say so out loud.",
  reflection: "What was the maintenance row worth over three years, and had anyone in the original discussion mentioned it?",
  recall: {
    q: "Which row is most often missing from a build estimate, and why does the buy-then-build crossover exist at all?",
    a: "Ongoing maintenance. Build is usually quoted as one-time engineering, but it creates a recurring engineer-year commitment for upkeep, on-call and dependency work that frequently exceeds the initial cost over a three-year horizon.\n\nThe crossover exists because buying is largely variable cost that scales with volume while building is largely fixed. At low volume the variable option wins on total cost and on optionality; above some volume the fixed option wins. The decision is therefore a volume threshold, not a philosophy."
  },
  deepDive: "Help me build the three-column total cost of ownership table for a specific build against buy decision, and solve for the volume at which the ranking flips."
},
{
  id: "capital-headcount-is-capital",
  track: "capital", level: "decide",
  title: "A headcount request is a capital request",
  source: "Thorndike, The Outsiders, on deploying capital into the existing business; Berman and Knight, Financial Intelligence, Part Two, on the income statement and cost allocation",
  idea: "Asking for engineers is asking for multi-year committed capital, so it should be written in the format of an investment case rather than a staffing plan.",
  why: "An engineer is not an annual expense that stops when the year ends. Hiring commits a recurring cost that is slow and costly to reverse, carries onboarding cost before it produces anything, and in most organisations survives the project it was hired for. In cash terms it behaves like a capital commitment with a long payback and a high exit cost, even though the accounting sends it to operating expense. The previous entries make the same point from the other direction: for a software company, engineering payroll is the dominant form of reinvestment.\n\nSo the format follows. A staffing plan says how many people and what they will work on. An investment case says how much capital over what period, what return, measured how, against what hurdle, with what payback, displacing what named alternative, and under what condition you would stop. The second one survives a room where finance is present. The first one gets deferred to the next planning cycle, which is how most platform re-charters die.",
  failureMode: "The request is written as a team shape. Two backend, one SRE, one to be determined, and a roadmap of themes. Nobody in the room can compute anything from it, so it is judged on advocacy and organisational politics. When budget tightens, the requests with numbers survive and the ones with themes do not, and the team concludes the decision was political.",
  experiment: "Take your next headcount ask and write it twice on one page. Version A as you would have written it: roles, skills, roadmap. Version B as an investment case: total capital over three years in dollars, the return with the measurement method named, payback in months, the named alternative use of the same money, and the kill criterion. Output: the count of numbers in each version. If version B has fewer than five, it is still a staffing plan.",
  reflection: "Which numbers in version B did you have to invent rather than source, and who owns each of those numbers?",
  recall: {
    q: "Why is a headcount request a capital request rather than an expense request, and what does that change about the format?",
    a: "Hiring commits recurring, slow-to-reverse spend with a long payback and a high exit cost, and for a software company engineering payroll is the largest form of reinvestment even though accounting puts it in operating expense.\n\nThe format changes from roles and roadmap to total capital, return with a stated measurement method, hurdle rate, payback period, a named displaced alternative, and a kill criterion."
  },
  deepDive: "Rewrite my staffing plan as an investment case and tell me every place where I substituted a theme for a number."
},
{
  id: "capital-loaded-cost-per-engineer",
  track: "capital", level: "model",
  title: "Fully loaded cost per engineer is a number finance owns and you must ask for",
  source: "Berman and Knight, Financial Intelligence, Part Two, on cost allocation and the fact that no cost figure is independent of the allocation rule behind it; your finance business partner owns the loaded rate",
  idea: "Name the exact loaded rate you need, name the person who owns it, and never estimate it yourself inside a funding document.",
  why: "Berman and Knight's point about allocation is that a cost figure is a judgement, not a fact. Overhead, facilities, tooling and shared services get pushed onto cost centres by a rule someone chose, and different rules produce different answers for the same team. That is why estimating the loaded rate yourself is worse than not having it. If you guess and the guess disagrees with the finance model, every downstream number in your case is discredited and the conversation becomes about your arithmetic instead of your proposal.\n\nAsk for it precisely. The fully loaded annual cost per engineering full-time equivalent for your cost centre, for the current fiscal year, inclusive of base, on-costs such as payroll tax and superannuation, benefits, equipment, software licences, facilities and allocated overhead, with the allocation basis stated. Ask a second question in the same message: whether any of your team's labour is being capitalised as internal-use software development, because if it is, part of your headcount is already being treated as a balance sheet asset and amortised, and that changes both the expense profile and the argument you are making about intangibles.",
  failureMode: "You take a public salary benchmark, add a round multiplier you heard somewhere, and build a three-year business case on it. Finance's actual loaded rate differs materially because of an overhead allocation you did not know existed. Your payback period is wrong, and you found out in the meeting rather than before it.",
  experiment: "Send one message to your finance business partner today asking for exactly two things: the fully loaded annual cost per engineering full-time equivalent for your cost centre this fiscal year with the allocation basis stated, and whether any of your team's development labour is capitalised. Output: the rate, the allocation basis, the capitalisation answer, and the name of the person who owns each. Put those names in your case so a reviewer can check without going through you.",
  reflection: "How far off was the number you would have guessed, and what was in the loaded rate that you did not know was being allocated to your team?",
  recall: {
    q: "Why must the fully loaded engineering rate come from finance rather than from your own estimate?",
    a: "Loaded cost depends on an overhead allocation rule that finance chooses, so it is a judgement embedded in the company's cost model rather than a fact you can derive. A guess that disagrees with the model discredits every number built on it.\n\nAsk for the rate for your specific cost centre and fiscal year with the allocation basis stated, and ask in the same message whether any of your development labour is being capitalised as internal-use software."
  },
  deepDive: "Draft the message to my finance business partner asking for the loaded rate and the capitalisation answer, phrased so the reply is a number rather than a meeting."
},
{
  id: "capital-opportunity-cost-named",
  track: "capital", level: "decide",
  title: "Opportunity cost is the next best funded project, named",
  source: "Mauboussin and Callahan, Capital Allocation, Counterpoint Global Insights, on opportunity cost and hurdle rates",
  idea: "Opportunity cost stated properly is a specific alternative use of the same dollars with its own expected return, not a general appeal to focus.",
  why: "The comparison that determines whether your project should be funded is against the best thing that would have been done with the same money. Mauboussin and Callahan make the hurdle rate the formal version of this: the rate exists so that projects are compared against the opportunity of returning the capital instead of deploying it. If your project clears the hurdle and the alternative clears it by more, yours still loses, and that is the correct outcome.\n\nNaming the alternative changes the conversation in two ways. It forces you to estimate someone else's return, which is uncomfortable and usually reveals that nobody has. And it converts a debate about priorities into a comparison of two numbers, which is a debate you can win with work rather than with seniority. It also protects you: if the named alternative is genuinely weaker, you have made the decision maker's argument for them.",
  failureMode: "Opportunity cost gets invoked as rhetoric. We need to focus, we cannot do everything, this is a distraction. None of that identifies what specifically would be funded instead, so it cannot be checked, and it usually functions as a way of declining without an argument. The counter is one question: which project gets the money if this one does not?",
  experiment: "For the single largest thing your team is currently spending capacity on, identify the specific project elsewhere in the organisation that would receive the same engineer-quarters if yours stopped tomorrow. Not a category, a project with an owner. Estimate its annual return using the same units you use for yours. Output: two numbers and one name. If you cannot find the alternative, ask the person who allocates the capacity, because they can.",
  reflection: "Did your project beat the named alternative on the numbers, and if it did not, what would you change about the proposal rather than about the framing?",
  recall: {
    q: "What is the difference between opportunity cost stated properly and opportunity cost used as rhetoric, and what is the hurdle rate's role?",
    a: "Stated properly it is a specific named alternative project with an owner and an estimated return in the same units, so the two can be compared arithmetically. Used as rhetoric it is an appeal to focus that identifies nothing and cannot be checked.\n\nThe hurdle rate is the formalised version: a floor derived from the cost of capital that represents the opportunity of returning the money to investors instead of deploying it. Clearing the hurdle is necessary but not sufficient, because the named alternative may clear it by more."
  },
  deepDive: "Help me find and quantify the named alternative use of the engineer-quarters my project consumes, and tell me honestly whether mine wins."
},
{
  id: "capital-payback-npv-irr",
  track: "capital", level: "model",
  title: "Payback, net present value and internal rate of return give different answers and one of them survives contact",
  source: "Berman and Knight, Financial Intelligence, Part Six, How to Calculate (and Really Understand) Return on Investment",
  idea: "Compute all three for one efficiency project and find out which one your audience will actually accept.",
  why: "The three methods disagree by construction. Payback is months until cumulative cash flow turns positive; it ignores the time value of money and ignores everything that happens after the payback point, which biases it against long-lived investments like a platform. Net present value discounts every future cash flow at the hurdle rate and sums; it is the theoretically correct one and it outputs a dollar figure, which is exactly what makes it hard to communicate, because a reviewer has to accept your discount rate before the number means anything. Internal rate of return is the discount rate at which net present value is zero; it produces a percentage that people compare intuitively, and it misbehaves when cash flows change sign more than once.\n\nWhat matters operationally is that different audiences accept different ones. Payback is what most operators actually decide on because it answers a cash question and needs no assumption. Net present value is what a finance reviewer will ask for. So compute all three, lead with the one your audience uses, and carry the other two in an appendix so that the first challenge does not stall the discussion.",
  failureMode: "You present net present value to a room that thinks in payback, spend the meeting defending your discount rate, and never get to the proposal. Or the reverse: you present a fourteen-month payback for a platform whose benefits compound in years three to five, and payback silently discards the majority of the value you were trying to argue for.",
  experiment: "Take one efficiency project you could actually run, ideally a cloud cost reduction with a known monthly saving. Lay out monthly cash flows for thirty-six months: negative engineering cost up front using the loaded rate from finance, positive saving thereafter. Compute payback in months, net present value at your hurdle rate, and internal rate of return. Output: three numbers on one line. Then ask the person who will approve it which of the three they want to see, and record the answer.",
  reflection: "Which of the three did your approver ask for, and how much of your project's value does that method throw away?",
  recall: {
    q: "State what each of payback, net present value and internal rate of return measures, and name the blind spot of each.",
    a: "Payback is months until cumulative cash flow turns positive; it ignores the time value of money and everything after the payback point, so it penalises long-lived investment. Net present value is the sum of discounted future cash flows less the outlay; its weakness is that it depends entirely on a discount rate the reviewer has to accept, and it outputs dollars rather than a comparable rate.\n\nInternal rate of return is the discount rate at which net present value equals zero; it gives an intuitively comparable percentage but is unreliable when cash flows change sign more than once."
  },
  deepDive: "Take the monthly cash flows for my efficiency project and compute payback, net present value and internal rate of return, showing the arithmetic rather than just the results."
},
{
  id: "capital-hurdle-rate-damodaran",
  track: "capital", level: "model",
  title: "The hurdle rate comes from the cost of capital and you can look yours up",
  source: "Damodaran, Cost of Capital by Industry Sector dataset, NYU Stern current data page, which states the number of firms in each industry group",
  idea: "A published sector cost of capital gives you a defensible discount rate instead of a threshold you invented.",
  why: "Damodaran publishes a cost of capital table by industry, updated annually from the current data page at NYU Stern, in United States and global variants. Each row carries the number of firms in the group, an unlevered and levered beta, a cost of equity, an after-tax cost of debt, the debt-to-capital ratio and the resulting weighted average cost of capital. The relevant rows for you are the software groups and computer services. The sample size on the row is why this citation clears the bar that a blog-quoted number does not.\n\nUse it two ways. As a discount rate for your net present value calculation, so the number in your case rests on a published dataset rather than a round figure. And as the reference point in the moat definition: your platform creates value only if its return exceeds this. One caution to state in the document rather than hide: the published sector figure is an average across many firms with different leverage and different risk, and your company's own internal hurdle rate may be deliberately higher. Ask finance whether one exists, use it if it does, and use the published figure as the defensible fallback.",
  failureMode: "The business case uses ten per cent because it is round. A reviewer who knows the sector figure asks where the number came from, gets no answer, and now discounts the whole document rather than just the rate. A made-up hurdle is worse than a slightly wrong sourced one, because the sourced one is arguable and the made-up one is not.",
  experiment: "Go to the NYU Stern current data page, open the cost of capital by sector file, and find the row for the software group closest to your business. Record three things: the weighted average cost of capital, the number of firms in that row, and the date of the dataset. Then ask finance whether the company has its own internal hurdle rate. Output: two rates, one sample size and one date, all of which go in the appendix of your case.",
  reflection: "How far apart were the published sector rate and your company's internal hurdle, and which one makes your project look better?",
  recall: {
    q: "Where does a defensible hurdle rate come from, and what should you record alongside the rate itself?",
    a: "From the company's own internal hurdle rate if one exists, and otherwise from Damodaran's published cost of capital by industry sector dataset on the NYU Stern current data page, using the software or computer services row.\n\nRecord the number of firms in that row and the dataset date alongside the rate. The sample size is what makes the citation checkable, and the date matters because the table is refreshed annually and the rate moves with the risk-free rate."
  },
  deepDive: "Help me pick the right Damodaran sector row for my business and explain why the sector average may understate or overstate the hurdle my company would actually apply."
},
{
  id: "capital-platform-return-dora",
  track: "capital", level: "model",
  title: "Platform team returns are real and measurable through delivery outcomes",
  source: "DORA, Accelerate State of DevOps Report, annual, with respondent counts stated in the methodology section; Forsgren, Humble and Kim, Accelerate: The Science of Lean Software and DevOps",
  idea: "Published survey research links platform and delivery capabilities to software delivery performance, which gives a platform team the attribution bridge it otherwise lacks.",
  why: "A platform team cannot claim revenue because it does not touch a customer. What it can claim is a change in the delivery performance of the teams it serves, measured by the four delivery metrics the DORA programme uses: deployment frequency, lead time for changes, change failure rate, and time to restore service. Forsgren, Humble and Kim's book sets out the research design behind those measures, and the annual report restates the respondent count for each year in its methodology, which is the number you cite.\n\nBe accurate about what the evidence is. This is cross-sectional survey research using self-reported measures and latent constructs, not a randomised trial, and recent reports have found that platform engineering effects are not uniformly positive across every outcome. That honesty is an advantage in the room: you are citing a bounded, sample-stated finding rather than asserting a causal claim you cannot support. The bridge you build is a chain with each link stated separately. Platform capability changes delivery metrics for served teams, delivery metrics link to organisational performance in the published research, and the served teams' output is what carries revenue. Present the chain and let the reviewer discount whichever link they choose.",
  failureMode: "The platform team claims a productivity multiplier with no baseline, no measurement of the teams it serves, and a citation to nothing. It reads as self-assessment. When budget tightens, the team cannot show a before and an after for a single served team, so it is treated as overhead and cut, which is the outcome the numbers were supposed to prevent.",
  experiment: "Pick one platform change you shipped in the last two quarters and one team it affected. Pull the four delivery metrics for that team for the eight weeks before and the eight weeks after, from your deployment and incident systems rather than from a survey. Output: four before-and-after pairs for one named team. Separately, open the most recent Accelerate State of DevOps Report, find the methodology section, and record the stated respondent count and the survey period. Put both in the same appendix.",
  reflection: "Which of the four metrics moved for the team you measured, and which link in the attribution chain is the one a sceptical reviewer will attack?",
  recall: {
    q: "What is the attribution chain a platform team uses in place of a revenue claim, and what is the honest limitation of the evidence?",
    a: "Platform capability changes the four delivery metrics for the teams it serves, those delivery metrics are linked to organisational performance in the published DORA research, and the served teams produce the revenue-carrying work. Each link is stated separately so a reviewer can discount the one they doubt.\n\nThe limitation is that the DORA evidence is cross-sectional survey research with self-reported measures rather than a controlled experiment, and recent reports report mixed effects for platform engineering across different outcomes. Cite the year's stated respondent count and do not upgrade the finding to a causal claim."
  },
  deepDive: "Help me assemble the before-and-after delivery metrics for one team my platform serves and write the attribution chain so each link can be challenged independently."
},
{
  id: "capital-efficiency-versus-feature",
  track: "capital", level: "decide",
  title: "An efficiency project competes for capital with a feature project",
  source: "Berman and Knight, Financial Intelligence, Part Six on return on investment and Part Two on the income statement; your hurdle rate and your allocated cloud cost",
  cheat: "Convert a saving into revenue equivalent by dividing by gross margin: at seventy-five per cent a dollar saved is about one dollar thirty-three.",
  idea: "Margin work and revenue work draw on the same pool of engineer-quarters, so cost savings must be presented in units that compare directly to revenue.",
  why: "The conversion is a single division and most engineers never make it. A dollar of cost of revenue removed adds a full dollar of gross profit. A dollar of new revenue adds only the gross margin fraction of a dollar. So a recurring saving is equivalent to new revenue of the saving divided by the gross margin. At seventy-five per cent gross margin, a dollar saved is worth about one dollar thirty-three of new revenue. Compute your own company's product gross margin from the filing or from finance and use that, not an assumed figure.\n\nThe second half is that a recurring saving is an annuity, not a one-off. A monthly cloud saving that persists is a stream, and the honest way to size it is to discount the stream at the hurdle rate over a defensible horizon rather than quoting an annualised run rate. State the horizon and state the assumption that the saving persists, because that assumption is where a reviewer will push, particularly if the saving depends on usage that is growing.",
  failureMode: "The efficiency project is presented as a percentage reduction in the cloud bill. Nobody in the room converts that to revenue equivalent, so it is mentally filed as housekeeping and loses to a feature with a smaller expected contribution but a customer name attached. The margin work is deferred, the bill compounds, and next year the same project has a larger saving and still no dollar framing.",
  experiment: "Take one cloud efficiency project you could start this quarter. Compute four numbers: the monthly saving in dollars, the revenue equivalent using your company's product gross margin, the present value of the saving over three years discounted at your hurdle rate, and the engineer-quarters required at the loaded rate. Output: one sentence of the form, this project is worth the equivalent of X dollars of new annual revenue and costs Y engineer-quarters. Take that sentence to the next prioritisation meeting.",
  reflection: "What was your revenue-equivalent multiplier, and did stating it change where the project landed in the priority order?",
  recall: {
    q: "Why is a dollar of cost of revenue removed worth more than a dollar of new revenue, and what is the conversion?",
    a: "New revenue only contributes its gross margin fraction to gross profit, because serving it carries cost of revenue. Removing a dollar of cost of revenue contributes the whole dollar.\n\nThe conversion is the saving divided by the gross margin. At seventy-five per cent gross margin a dollar saved equals roughly one dollar thirty-three of new revenue. Use your own company's product gross margin from the filing or from finance rather than an assumed rate, and size a recurring saving as a discounted stream rather than an annualised run rate."
  },
  deepDive: "Take my monthly cloud saving estimate and my company's gross margin and produce the revenue-equivalent sentence plus the three-year discounted value, flagging the assumption a reviewer will attack."
},
{
  id: "capital-write-the-request",
  track: "capital", level: "decide",
  title: "Write the capital request for your re-charter",
  source: "Thorndike, The Outsiders; Mauboussin and Callahan, Capital Allocation, Counterpoint Global Insights",
  idea: "Produce the re-charter as a one-page investment case with the ask in dollars, a hurdle rate with a source, a payback period, a named opportunity cost and an explicit list of the numbers finance must supply.",
  why: "This is the assembly step for the track. Every input has already been produced: the loaded rate from finance, the hurdle rate from Damodaran or from the company's own model, the return computed as either cost removed converted to revenue equivalent or delivery outcomes with the attribution chain stated, the named alternative use of the same money, and the three return methods with the one your approver prefers leading. The document's job is to let a reviewer disagree with a specific line rather than with the whole proposal.\n\nTwo structural choices carry most of the weight. Lead with the ask and the return in the first three sentences, because the buried version gets skimmed and the load-bearing claim never lands. And write the kill criterion yourself: the condition under which you would recommend stopping, with a date. Volunteering it does more for the case's credibility than any other single line, because it signals that you are allocating capital rather than defending territory, and it is exactly what the reviewer is trying to work out about you.",
  failureMode: "The document opens with context. History of the team, current pain, three paragraphs of background, and the ask on page two. The reviewer reads the first screen, cannot tell what is being requested or what it returns, and puts it in the pile of things to discuss later. There is no later in a budget cycle.",
  experiment: "Write the page today. Required lines: total capital requested over three years in dollars and in engineer-years; the return with the measurement method named; the hurdle rate with its source and date; payback in months; the named alternative project and its estimated return; a table of every number that came from finance with the owner's name against each; and the kill criterion with a date. Output: a single page where a reader can locate all eight items in under sixty seconds. Give it to one person who does not work for you and time how long that takes them.",
  reflection: "Which of the eight items was hardest to write, and is that because the number is hard to get or because the answer is uncomfortable?",
  recall: {
    q: "List the items a capital request for a team re-charter must contain, and say why the kill criterion belongs in it.",
    a: "Total capital in dollars and engineer-years, the return with its measurement method, the hurdle rate with source and date, payback in months, the named alternative use of the same money with its estimated return, the finance-supplied numbers with an owner against each, and the kill criterion with a date. The ask and the return go in the first three sentences.\n\nThe kill criterion belongs there because volunteering the stopping condition is the clearest available signal that you are allocating capital rather than defending headcount, and it is the question the reviewer is trying to answer about you regardless of what the document says."
  },
  deepDive: "Review my one-page capital request against the eight required items and tell me which line a sceptical finance reviewer attacks first."
}
);
